### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by yashwanthm3012** [uBlockOrigin/uAssets#14339] opened 2022-08-10 05:39 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=O_1xOlg1IWE`

### Category

ads

### Describe the issue

Ads showing when i restart the system

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80140
  cosmetic: 45210
  scriptlet: 17584
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69308-51, 20h.2m
    easyprivacy: 27305-123, 20h.1m
    plowe-0: 3634-776, 20h
    ublock-abuse: 76-0, 19h.58m
    ublock-badware: 4176-92, 19h.56m
    ublock-filters: 32396-121, 19h.55m
    ublock-privacy: 231-3, 19h.54m
    ublock-quick-fixes: 363-1, 19h.53m
    ublock-unbreak: 1855-43, 19h.52m
    urlhaus-1: 4968-0, 19h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 783 ms (selfie)
  maxAssetCacheWait: 537 ms
popupPanel: 
  blocked: 64
  blockedDetails: 
    youtube.com: 35
    doubleclick.net: 5
    google.co.in: 1
    google.com: 8
    googlesyndication.com: 12
    googlevideo.com: 3
```
</details>

**Comment by okiehsch** [comment] 2022-08-10 06:03
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by okiehsch** 2022-08-10 06:03 UTC

**Comment by MasterKia** [comment] 2022-08-10 07:46
See: https://github.com/easylist/easylist/wiki/youtube-issues
