### ISSUE TITLE
Broken layout on YouTube front page

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#14453] opened 2022-08-20 09:35 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.youtube.com/`

### Describe the issue

There's a layout issue on the YouTube front page, which only appears when uBO is active. 
If I use the big *enable/disable* button (to add youtube.com to the list of trusted sites), the fixed site layout appears again.. 

NB 1: Apparently, this is only triggered while logged in into your YouTube account.
This should be obvious as soon as you sign in. In my test (with an clean profile, default uBO etc.), when visiting the site the layout looks normal, like it's supposed to be. If you use the big *Sign In* button, you are redirected to the standard Google login dialog at `https://accounts.google.com/`, when entering your credentials you are then redirected to YouTube again, and then the layout shift can be observed immediately.

NB 2: If you use the category switcher bar at the top (where you can switch between *All*, *Gaming*, *Music*, etc. (These vary depending on your subscriptions, recommendations, history etc. in your YouTube profile)), you can see how the correct layout is supposed to look (cf. second screenshot). 
It works for *every* category, except *All*, which is the normal front page, i.e. when initially visiting the site.

### Screenshot(s)

![yt-standard-frontpage](https://user-images.githubusercontent.com/12064918/185739250-c21508ba-8ce2-4083-8881-652f173060ac.png)

![yt-picked-category](https://user-images.githubusercontent.com/12064918/185739261-b897d4f4-5d36-4d9d-b2c9-bb44a3310c0e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80920
  cosmetic: 45397
  scriptlet: 17676
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69600-51, 13m
    easyprivacy: 27394-126, 13m
    plowe-0: 3632-776, 13m
    ublock-abuse: 76-0, 13m
    ublock-badware: 4259-92, 13m
    ublock-filters: 32536-122, 13m
    ublock-privacy: 231-3, 13m
    ublock-quick-fixes: 429-37, 13m
    ublock-unbreak: 1832-41, 13m
    urlhaus-1: 5419-0, 13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 488 ms
  maxAssetCacheWait: 234 ms
```
</details>

**Comment by MasterKia** [comment] 2022-08-20 09:39
> - [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

You can discuss this issue there.

Also see: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-20 09:39 UTC

**Comment by Hrxn** [comment] 2022-08-20 09:43
...

I *did* search #7636 

I did *all* the steps listed in the wiki page you've linked.

This is a different issue. Not a duplicate.

**Comment by okiehsch** [comment] 2022-08-20 09:45
That issue is for "All" youtube issues.

**Comment by MasterKia** [comment] 2022-08-20 09:45
Please just copy and paste the issue you sent here into #7636.

**Comment by okiehsch** [comment] 2022-08-20 09:49
Btw, I don't think it's broken looks like there is a hidden ad to me, if you disable cosmetic filtering I am pretty sure the first row will have an additional ad.

**Comment by MasterKia** [comment] 2022-08-20 09:50
I haven't used YouTube for some time but I do remember the first screenshot, where there was an empty spot in the same place.

**Comment by MasterKia** [comment] 2022-08-20 09:51
Maybe one of the filters needs `:upward(1)` so that it removes the blank spot with it?

**Comment by Hrxn** [comment] 2022-08-20 09:58
Pasted into #7636, not sure if those huge single thread pages are really helpful.
Btw, GitHub hides a lot of older items in such an issue thread, does anyone know how to make them all visible automatically?
Because Ctrl+F search is kinda useless otherwise..


> Btw, I don't think it's broken looks like there is a hidden ad to me, if you disable cosmetic filtering I am pretty sure the first row will have an additional ad.

Seems like you're right... not sure if that's the correct way to use this uBO option though.

![seemslkeit](https://user-images.githubusercontent.com/12064918/185740332-11349d13-c0f1-4ac8-9d30-13fd5ce52296.png)

**Comment by okiehsch** [comment] 2022-08-20 09:59
> how to make them all visible automatically?

Not possible.

**Comment by MasterKia** [comment] 2022-08-20 10:02
> GitHub hides a lot of older items in such an issue thread

True, the main idea of "ALL" youtube issues theread is that other people subscribed to that thread might be able to reproduce the said problem.

**Comment by okiehsch** [comment] 2022-08-20 10:03
The main idea is frankly that there have been 389 youtube issue in this repo!
It makes sense to centralize them imo.

**Comment by MasterKia** [comment] 2022-08-20 10:07
The attempt to "centralize" has failed successfully because every week there is another "YouTube ads" issue.

**Comment by okiehsch** [comment] 2022-08-20 10:08
Which we close immediately.

Hm, I could reproduce and was trying to find a fix but now the layout suddenly looks normal on my end....

**Comment by MasterKia** [comment] 2022-08-20 10:10
https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1221271200
