### ISSUE TITLE
9to5google.com: breakage

### ISSUE THREAD

**Issue by Kaoxt** [uBlockOrigin/uAssets#21898] opened 2024-01-11 12:12 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://9to5google.com/2024/01/10/google-reorganizing-hardware/?extended-comments=1`

### Category

breakage

### Description

Toggling Dark Mode / Light Mode does not work under hamburger menu when uBlock is enabled on Firefox Mobile. Additionally I am unable to read comments when Dark Mode is enabled with uBlock on. Turning off uBlock allows me to read comments. When uBlock is turned on when Dark Mode is already enabled, the comments text is black so it's unreadable.
![Screenshot_20240111-061117](https://github.com/uBlockOrigin/uAssets/assets/105674902/f63a7dd7-d362-4451-a877-93bf128d80e9)

### Other extensions used

ByPass Paywalls
Google Search Fixer
Reedit Annoyances 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 117198
 cosmetic: 51943
 scriptlet: 18725
 html: 2015
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37341-233, 24m Δ
  ublock-badware: 7767-11, 24m Δ
  ublock-privacy: 959-0, 24m Δ
  ublock-unbreak: 2238-0, 24m Δ
  ublock-quick-fixes: 225-1, 24m Δ
  adguard-mobile: 9034-102, now
  easylist: 76982-596, 24m Δ
  easyprivacy: 43408-832, 24m Δ
  urlhaus-1: 10065-0, now
  plowe-0: 3787-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 923 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  aniview.com: 1
  doubleclick.net: 2
  doubleverify.com: 5
  google.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  spot.im: 8
  videoplayerhub.com: 1
  wp.com: 2
  youtube.com: 1
 extended:
  ##.ad-container--leaderboard
  ##.inlinead
  ##ins.adsbygoogle
  ##.ad-disclaimer-container
  ##.ad-container
  ##.ad-disclaimer-container, .inlinead, .ad-container
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by Daxy7** [comment] 2024-03-20 19:49
Why is this post open since `Jan 11, 2024, 12:12 PM GMT` with no comments?
Anyways [I can't reproduce on desktop PC.](https://github.com/uBlockOrigin/uAssets/assets/91396482/06d61cbc-cac5-4cb3-9e8a-1040ecc753e2) Can someone test on `Firefox Mobile Android`?

**Comment by gwarser** [comment] 2024-03-20 20:37
I had no issues with comments on mobile. On first load, dark theme toggle did not work, but works now - not sure if filters update or some quirk.

**Comment by Kuron85** [comment] 2024-03-20 23:36
This can probably be closed. It appears to be a an odd website issue. It happens on Chrome as well

**Comment by Kaoxt** [comment] 2024-03-20 23:37
Yep happens on Chrome too on mobile with no extensions installed after I further tested this.

**Comment by gorhill** [comment] 2024-03-21 01:43
There was a filter added a while ago to fix the breakage. It requires creating a dummy element, it's in _Unbreak_ - -this was fixed in <https://github.com/uBlockOrigin/uAssets/issues/22103>.

**Comment by Daxy7** [comment] 2024-03-21 02:05
Appears to be a site issue then, and they have updated their HTML maybe
Original fix 100ms allow it for testing:
`9to5google.com#@#+js(trusted-rpnt, script, (function($), '(function(){const a=document.createElement("div");document.documentElement.appendChild(a),setTimeout(()=>{a&&a.remove()},100)})(); (function($)')`
Updated to 1000ms test filter [compensating for high latency, slow internet etc]:
`9to5google.com##+js(trusted-rpnt, script, (function($), '(function(){const a=document.createElement("div");document.documentElement.appendChild(a),setTimeout(()=>{a&&a.remove()},1000)})(); (function($)')`

**Closed** 2024-03-21 07:59 UTC
Labels: unable to reproduce
