### ISSUE TITLE
music.amazon.es: ads

### ISSUE THREAD

**Issue by darkneptune** [uBlockOrigin/uAssets#18403] opened 2023-06-06 00:40 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://music.amazon.es/search/running+up+that+hill+epic?filter=IsLibrary%7Cfalse&sc=none`

### Category

ads

### Description

can play in shuffle mode only

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 96787
 cosmetic: 44896
 scriptlet: 18019
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34481-74, 1d.16m
  ublock-badware: 7240-0, 1d.15m
  ublock-privacy: 420-0, 4d.59m
  ublock-abuse: 69-69, 4d.58m
  ublock-unbreak: 2041-3, 1d.14m
  ublock-quick-fixes: 184-0, 13h
  easylist: 66854-730, 1d.13m
  easyprivacy: 31573-625, 5d.1h.4m
  urlhaus-1: 6921-0, 13h.1m
  plowe-0: 3735-3, 11d.2h.19m
  spa-0: 3682-1, 8h.58m
  spa-1: 5259-157, 3d.25m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1644 ms (selfie)
 maxAssetCacheWait: 222 ms
popupPanel: 
 blocked: 3954
 network: 
  amazon.es: 2024
  aiv-delivery.net: 943
  amazon.com: 987
```
</details>

**Comment by mapx-** [comment] 2023-06-06 07:59
@darkneptune 

what kind of ads ? audio ads ? on gratis / free podcasts or some subscription ?

I guess we'll need your account to investigate (if you are ok with giving us your user / pass I'll provide an email address)

**Comment by mapx-** [comment] 2023-06-06 16:06
We cannot investigate without an account.  Closing.

**Closed by mapx-** 2023-06-06 16:06 UTC
Labels: account required, Waiting for feedback

**Comment by okiehsch** [comment] 2023-06-06 17:31
This is very hard to debug unless you have an unlimited account,
I only have a basic account and with that you can' fast forward throug ha playlist, you have to let it "play out" in real time.

**Comment by darkneptune** [comment] 2023-06-06 17:32
ublock works with spotify free limitation.

**Comment by okiehsch** [comment] 2023-06-06 17:35
> ublock works with spotify free limitation.

Your point is? 
I can easily debug spotify with a free account,
To debug Amazon Music I need an unlimited account on top of a "normal" Amazon Prime account.

**Comment by darkneptune** [comment] 2023-06-06 17:57
cant you create a free amazon music account to debug it, in the same way as a spotify free account?

**Comment by darkneptune** [comment] 2023-06-06 20:55
>  If you have an Amazon Prime account you get access to "basic" Amazon Music.
No. It is similar to spotify free and spotify premium. (at least, in .es)
[](https://www.amazon.es/music/free)
There is a free version, no Amazon Prime is needed.

**Comment by okiehsch** [comment] 2023-06-06 21:20
Ok, after logging out and creating a new account I can see a free version.
It's not a visible option if you are logged in with a Prime account.

The problem now is that I skipped though your running up that hill library without encountering an ad. 😞

**Comment by darkneptune** [comment] 2023-06-06 21:39
> And you can fast forward through a playlist on your end using this free version?

No. And I can't select a specific song or album either. that is the problem. ublock solves it well on spotify, but not on https://music.amazon.es

**Comment by stephenhawk8054** [comment] 2023-06-07 03:08
I tried playing this playlist: `https://music.amazon.es/playlists/B07S6C66WM`, but I can't reproduce any ads.

From what I read, what you want is not about removing ads, but about having other functionalities of higher tier subscription? Is it correct?

---

Also, no need to mention spotify here. These are 2 different services with different coding, so need different investigations. Bringing it here just bringing more noises.

**Comment by okiehsch** [comment] 2023-06-07 06:08
> No. And I can't select a specific song or album either.

So your issue isn't about ads but about some missing functionality?

**Comment by darkneptune** [comment] 2023-06-07 17:14
I can't select a specific song or album either. Force to consume another product different from the one desired: That is intrusive advertising.

**Comment by stephenhawk8054** [comment] 2023-06-07 17:24
Well, it's server-sided paywall, out-of-scope of uBO
