### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4123] opened 2018-11-15 20:45 UTC
### URL(s) where the issue occurs

`https://www.filmweb.pl/film/Dziewczyny+do+wzi%C4%99cia-1972-5307/posters`

### Describe the issue

Agreement overlay annoyance.

### Versions

- Browser/version: Firefox 63
- uBlock Origin version: uBlock Origin 1.17.2

### Settings

+uBlock filters – Annoyances

**Comment by krystian3w** [comment] 2018-11-15 21:33
## Above list have filters:

### Cookies

```
filmweb.pl##.cookieInfo, div.topBarCont
```

\+


### GDPR:

<pre><code>www.filmweb.pl##.rodo:style(overflow: auto !important; <b>position: static !important;</b>)
filmweb.pl##.rodo__overlay</code></pre>

**Comment by krystian3w** [comment] 2018-11-15 21:33
## Above list have filters:

### Cookies:

```
filmweb.pl##.cookieInfo, div.topBarCont
```

\+


### GDPR:

<pre><code>www.filmweb.pl##.rodo:style(overflow: auto !important; <b>position: static !important;</b>)
filmweb.pl##.rodo__overlay</code></pre>

**Comment by okiehsch** [comment] 2018-11-15 23:53
GDPR-Messages will not be fixed in `uAssets`.

**Closed by okiehsch** 2018-11-15 23:53 UTC

**Comment by adranger** [comment] 2018-11-16 14:52
@okiehsch When was this discussed and @gorhill decided that? That site is showing the warning to non-EU IPs.

**Comment by krystian3w** [comment] 2018-11-16 14:56
Polish websites have more GDPR with no detect IP / Geolocation. 

And now all of a sudden it will come out on the list of parishes almost everything from list `Polish GDPR-Cookies Filters` (`Polskie Filtry RODO-Ciasteczkowe`).

**Comment by okiehsch** [comment] 2018-11-17 03:41
> That site is showing the warning to non-EU IPs.

Well, is there not a polish list dedicted to cookie notices and alike which can add **krystian3w**'s
````
filmweb.pl##.rodo:style(overflow: auto !important; position: static !important;)
filmweb.pl##.rodo__overlay
````
it works on my end.

**Comment by krystian3w** [comment] 2019-01-09 12:30
@adranger  you need new filter should use:

`https://www.filmweb.pl/news/Powi%C4%99ksza+si%C4%99+obsada+prequela+%22Gry+o+tron%22-131352`

```
filmweb.pl##body.rodo #header:style(position: relative !important;)
``` 

**related:** https://github.com/MajkiIT/polish-ads-filter/issues/11004, https://github.com/MajkiIT/polish-ads-filter/pull/11006#issuecomment-452675332

**Comment by adranger** [comment] 2019-01-10 17:10
@krystian3w  Thanks. I've started using the Adguard Annoyances list, and it has those rules.

**Comment by theinstantmatrix** [comment] 2019-03-02 23:45
heads up, they now have an anti-adblock script that prevent you from seeing the rest of the page (starting at actors list) when detected.

test urls:
`https://www.filmweb.pl/film/Alita%3A+Battle+Angel-2019-193450`
`https://www.filmweb.pl/film/Ballada+o+Busterze+Scruggsie-2018-811694`

ss at Ballada o Busterze Scruggsie:
![screenshot_2019-03-02 ballada o busterze scruggsie the ballad of buster scruggs](https://user-images.githubusercontent.com/24980766/53688980-fb3bfc80-3d19-11e9-83a0-a4f6e81718de.png)

**Comment by okiehsch** [comment] 2019-03-03 00:08
That is fixed in th regional
````
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
````
list, which is enabled by default for users with a polish browser locale.

The fix they use, whitelisting
````
@@||r.sascdn.com/config.js$script,domain=www.filmweb.pl
@@||ced-ns.sascdn.com/diff/js/smart.js$script,domain=www.filmweb.pl
````
is not necessary though - as far as I can see - if I block those requests and add 
`filmweb.pl##+js(set-constant.js, sas, noopFunc)`
the issue is fixed on my end.

**Comment by krystian3w** [comment] 2019-03-03 08:04
Possible use this constant as bait in Monday..., The 3 scripting rules have been disabled / removed so far in less than a week.

**Comment by KiLL4FuNK** [comment] 2019-03-29 04:01
anti-adblock

**Comment by okiehsch** [comment] 2019-03-29 04:08
It is fixed in the regional filter list.
