### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by bretthl** [uBlockOrigin/uAssets#11130] opened 2021-12-29 21:35 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/watch?v=sJ3L-E-ufYo`

### Category

breakage

### Describe the issue

blocks video comments when logged in.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot from 2021-12-29 14-33-12](https://user-images.githubusercontent.com/11840200/147705166-4722997b-96d5-44ad-a586-52e99143950d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78175
  cosmetic: 39963
  scriptlet: 16214
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30334-30, 2d.7h.18m
    ublock-badware: 3635-1, 2d.7h.17m
    ublock-privacy: 179-0, 2d.7h.24m
    ublock-abuse: 81-0, 2d.7h.23m
    ublock-unbreak: 1689-0, 2d.7h.22m
    easylist: 62257-564, 2d.7h.21m
    easyprivacy: 26554-490, 2d.7h.20m
    urlhaus-1: 7737-0, 52m
    plowe-0: 3681-3, 2h.58m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1571 ms
popupPanel: 
  blocked: 110
```
</details>

**Comment by iam-py-test** [comment] 2021-12-29 21:51
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by gorhill** [comment] 2021-12-29 21:54
You have custom filters, investigate these -- comments work fine with default lists and no other filters.

**Comment by iam-py-test** [comment] 2021-12-29 21:58
@bretthl can you post your custom filters or disable _My filters_ and retest

**Closed** 2021-12-30 06:03 UTC
