### ISSUE TITLE
[nsfw] facebook.com: privacy

### ISSUE THREAD

**Issue by paperboy1981** [uBlockOrigin/uAssets#13353] opened 2022-05-23 03:39 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.facebook.com/nt/screen/?params=....`

### Category

privacy

### Describe the issue

I can't acces to my account.. help please

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 86677
  cosmetic: 29833
  scriptlet: 17240
  html: 660
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32148-328, 1d.22h.42m
    ublock-badware: 4132-3, 1d.22h.40m
    ublock-privacy: 220-1, 6d.8h.30m
    ublock-abuse: 75-0, 6d.8h.29m
    ublock-unbreak: 1796-0, 1d.22h.39m
    ublock-quick-fixes: 181-0, 14h.41m
    adguard-mobile: 7752-172, 1d.22h.43m
    easylist: 67282-24786, 1d.22h.38m
    easyprivacy: 27055-603, 1d.12h.58m
    urlhaus-1: 8181-0, 9h.6m
    plowe-0: 3673-3, 5d.14h.48m
    spa-0: 3884-219, 14h.42m
    spa-1: 4493-183, 1d.22h.44m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1440 ms (selfie)
  maxAssetCacheWait: 1237 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    facebook.com: 11
```
</details>

**Comment by krystian3w** [comment] 2022-05-23 11:57
First: Duplicate of #3367 

Second: try login in Firefox Private Tab if works then bug may not related with uBo.

**Closed** 2022-05-23 17:11 UTC
Labels: unable to reproduce
