### ISSUE TITLE
thepiratebay.org: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#22434] opened 2024-02-10 17:00 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thepiratebay.org/description.php`

### Category

ads

### Description

#22403 is still not solved. Only solved partially, I can still see a "Download" ad button.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/50150516/9f226f4a-848b-4be3-9e63-0beb10545f1d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 329116
 cosmetic: 235340
 scriptlet: 47814
 html: 0
listset (total-discarded, last-updated):
 added:
  ROU-1: 1342-1, now
  adguard-cookies: 28580-30, now
  adguard-generic: 82639-507, now
  adguard-other-annoyances: 14154-6, now
  adguard-popup-overlays: 26902-84, now
  adguard-social: 22135-878, now
  adguard-spyware: 94460-1195, now
  adguard-spyware-url: 1440-5, now
  adguard-widgets: 2431-5, now
  block-lan: 56-0, now
  curben-phishing: 104571-25, now
  dpollock-0: 11638-217, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  easylist: 80677-2109, now
  easyprivacy: 50207-32416, now
  plowe-0: 3783-1623, now
  ublock-badware: 7847-329, now
  ublock-filters: 37215-4037, now
  ublock-privacy: 998-415, now
  ublock-quick-fixes: 253-24, now
  ublock-unbreak: 2212-149, now
  urlhaus-1: 7430-1, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 26 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1016 ms (selfie)
 maxAssetCacheWait: 662 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 11
 network:
  thepiratebay.org: 1
  d1n3aexzs37q4s.cloudfront.net: 1
  exdynsrv.com: 1
  googletagmanager.com: 1
  iconcardinal.com: 1
  onautcatholi.xyz: 1
  pagespeed-mod.com: 1
  ricewaterhou.xyz: 2
  spotscenered.info: 1
  wpadmngr.com: 1
 extended:
  ##a[href^="https://italarizege.xyz/"]
  ###ad-bottom
  ##.ad728
  ##.ad468
  ##.ad234
  ##.ad120
  ##+js(addEventListener-defuser, click, popMagic)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(remove-attr, href, #home > header a[href^="https://"])
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(abort-on-property-read, _wm)
  ##+js(addEventListener-defuser, /^(?:click|mousedown)$/, _0x)
  ##+js(abort-on-property-write, spot)
  ##+js(abort-on-property-read, popjs.init)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
```
</details>

**Comment by ItsProfessional** [comment] 2024-02-10 17:06
Duplicate of #22403. Continue there.

**Closed by ItsProfessional** 2024-02-10 17:06 UTC
Labels: duplicate
