### ISSUE TITLE
uBO gets detected on filmisub.com

### ISSUE THREAD

**Issue by dimitarkolevdtd** [uBlockOrigin/uAssets#10895] opened 2021-12-13 12:36 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`filmisub.com`

### Describe the issue

website detects ublock origin and blocks content.

### Screenshot(s)

![Screenshot (28)](https://user-images.githubusercontent.com/72911640/145812520-838f808f-a3e8-43dd-a826-6acc0cc651de.png)

### uBlock Origin version

1.39.2

### Browser name and version

Firefox 95.0 (64-bit)

### Settings

I have the default settings.

**Comment by uBlock-user** [comment] 2021-12-13 12:39
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10876

**Closed by uBlock-user** 2021-12-13 12:39 UTC
