### ISSUE TITLE
ubo failing to filter on http://gorillavid.in/

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#2070] opened 2018-04-24 12:15 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://gorillavid.in/az3jnf9aiix6`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

Shows ads in uBo, but not in ABP. https://i.imgur.com/HPiAqbi.jpg

### Versions

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.16.0

### Settings

- Disable uBo specific filters., just enable Easylist, Easyprivacy.

### Notes

Tested in ABP+ and it works fine.

**Comment by ryanbr** [comment] 2018-04-24 12:32
Ok, not sure but these filters should be working?

`gorillavid.in##[style*="base64"]`
`gorillavid.in##[style*="url(&quot"]`
`gorillavid.in##[style*="overflow: hidden; border: 0px none; margin: 0px;"]`
`gorillavid.in##[style*="overflow: visible; visibility: visible;"]`
`gorillavid.in##[style*="data:image"]`

**Comment by mapx-** [comment] 2018-04-24 12:33
I cannot reproduce those ads, already filtered by ublock filters (only disabling ublock filters I get the ads)

**Comment by ryanbr** [comment] 2018-04-24 12:33
Test in Firefox Nightly?

**Comment by gorhill** [comment] 2018-04-24 12:34
Yes, tested in Nightly and without uBO's filters:

![a](https://user-images.githubusercontent.com/585534/39187067-404d6992-479a-11e8-9d1a-6209026b093a.png)

**Comment by gorhill** [comment] 2018-04-24 12:35
What does the logger say? Are cosmetic filters disabled?

**Comment by gorhill** [comment] 2018-04-24 12:36
You screenshot says that EasyList is not selected -- "Ads (0/4)".

**Comment by ryanbr** [comment] 2018-04-24 12:40
Can you re-test with Enhanced tracking list enabled? refresh a few times..

**Comment by gorhill** [comment] 2018-04-24 12:43
Refreshed 10+ ties, still can't reproduce. One difference is that you have custom filters which we do not have.

While at it, I see this filter reported in the logger:

    /\:\/\/[a-z0-9]{4,12}\.(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|host|info|loan|men|ml|online|ovh|party|pro|pw|racing|review|rocks|science|site|space|stream|tk|top|trade|webcam|website|win|xyz|store|solutions|software|social|site|shop|services|sale|run|rip|reviews|restaurant|report|zone)\/[\w\/\-.+]{120,}/$third-party,subdocument

It's really an inefficient regex, because not anchored. This should be anchored like so:

    /^https?:\/\/[a-z0-9]{4,12}\.(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|host|info|loan|men|ml|online|ovh|party|pro|pw|racing|review|rocks|science|site|space|stream|tk|top|trade|webcam|website|win|xyz|store|solutions|software|social|site|shop|services|sale|run|rip|reviews|restaurant|report|zone)\/[\w\/\-.+]{120,}/$third-party,subdocument

**Comment by gorhill** [comment] 2018-04-24 12:51
@mapx- 

> only disabling ublock filters I get the ads

Even when I disable uBO filters (and select exact filter lists in @ryanbr's screenshot) I still do not get the ads.

**Comment by mapx-** [comment] 2018-04-24 13:04
right, probably I got the ads on chrome (or not updating easylist)

**Comment by krystian3w** [comment] 2018-04-24 13:08
I see only befor play video text "advertisement":

> ![image](https://user-images.githubusercontent.com/35370833/39188902-35c99662-47d1-11e8-812b-bd268b0d73b4.png)

```
###flvvideo_ima-countdown-div
```

**Comment by ryanbr** [comment] 2018-04-24 13:08
I seem to only get the ads in Enhanced tracking is enabled. i'll test it later today, something isnt quite right

**Comment by ryanbr** [comment] 2018-04-24 13:13
![error](https://user-images.githubusercontent.com/1659004/39189243-e2a324b2-4825-11e8-9ceb-c4d5d923601e.jpg)

if it helpd

**Comment by mapx-** [comment] 2018-04-24 17:37
it seems fixed by https://github.com/ryanbr/fanboy-adblock/commit/b6cc3ba61baa429b477e7720db486018e2d189f2

**Closed by mapx-** 2018-04-24 17:37 UTC
Labels: unable to reproduce

**Comment by SMed79** [comment] 2018-04-24 18:26
@gorhill 
> This should be anchored

What other regex filters should be anchored in easylist?

**Comment by mapx-** [comment] 2018-04-24 18:40
all ...of them, for exampl,e Propellerads regex filters

https://stackoverflow.com/questions/42557392/what-is-the-difference-between-an-anchored-regex-and-an-un-anchored-regex

**Comment by ghajini** [comment] 2019-06-02 05:37
video broken ,video doesn't play with ubo enabled
opera browser stable
`https://gorillavid.in/14i2837qkrkh`

**Comment by okiehsch** [comment] 2019-06-02 05:44
Works on my end.
![image](https://user-images.githubusercontent.com/16838044/58757285-22b58780-850a-11e9-9b93-76e949ba8148.png)

**Comment by ghajini** [comment] 2019-06-02 06:06
`^https?:\/\/.*\/.*sw[0-9a-z(.|_)].*/$domain=123movies.com|123unblock.info|123unblock.xyz|1337x.st|1337x.to|1movies.is|adsrt.com|ancient-origins.net|anitube.cz|aniwatcher.com|c123movies.com|clicknupload.org|daclips.in|datpiff.com|downloadpirate.com|dwatchseries.to|estream.nu|estream.to|estream.xyz|eztv.io|eztv.tf|eztv.yt|ffmovies.ru|flvto.biz|fmovies.io|fmovies.is|fmovies.taxi|fmovies.to|fmovies.today|fmovies.world|fullmatchesandshows.com|gifsis.com|gomovies.sc|gomovieshub.is|gorillavid.in|gostreams.net|hdmoza.com|hdonline.is|healthline.com|intoupload.net|kickass2.ch|kickass2.st|kimcartoon.to|limetorrents.info|masterkreatif.com|megaup.net|monova.org|monova.to|movies.is|movies123.xyz|moviescouch.co|moviewatcher.is|movpod.in|mrunlock.icu|mrunlock.pro|newser.com|nocensor.icu|nocensor.pro|nowwatchtvlive.ws|onhax.me|openload.co|openload.pw|otakustream.tv|peggo.tv|pirateiro.com|postimg.cc|prox4you.pw|prox4you.xyz|putlocker.ninja|putlockers.movie|queenfaucet.website|seedpeer.me|sendit.cloud|skidrowcrack.com|stream2watch.ws|swatchseries.to|tinypic.com|torlock.com|torrentdownload.ch|torrentdownloads.me|torrentfunk.com|torrentfunk2.com|torrentz2.eu|tubidy.io|uiz.io|unblockall.org|unblocked.app|unblocked.cx|unblocked.is|unblocked.llc|unblocked.lol|unblocked.pet|unblocked.si|unlockproject.icu|unlockproject.live|upload.ac|uploadproper.net|uplod.cc|uplod.io|uplod.ws|uptobox.com|userscloud.com|ustreamix.com|ustreamyx.com|vidbull.tv|vidoza.co|vidoza.net|vidtomp3.com|vidup.io|watchcartoononline.io|watchseries.sk|watchsomuch.info|x1337x.eu|x1337x.se|x1337x.ws|yesmovies.to|yify-movies.net|yify.bz|yifyddl.movie|yifytorrent.co|ymovies.tv|yourbittorrent2.com|yts.am|zippyshare.com`

    from easylist

filter is causing trouble....

same is true with
`https://daclips.in/zp2obglrd5lh`
`https://movpod.in/08ubk9kcgmbt`

**Comment by mapx-** [comment] 2019-06-02 06:22
![image](https://user-images.githubusercontent.com/10303732/58757609-69f24700-850f-11e9-994b-31ea0330b27a.png)

it's for `sw.js` crap but without indicating at least `script`

**Comment by ghajini** [comment] 2019-06-02 06:23
@mapx- 
iam on default setup
opera browser stable
ubo dev build latest

video doesn't play
` https://gorillavid.in/14i2837qkrkh`
`https://daclips.in/zp2obglrd5lh`
`https://movpod.in/08ubk9kcgmbt`

**Comment by okiehsch** [comment] 2019-06-02 06:26
Is this an Opera only issue? I have no video problems at all mentioned domains.
Making the `sw.js` filter script only makes sense in any case.

**Comment by mapx-** [comment] 2019-06-02 06:28
tested in firefox, it's object element, 

I'll add
`@@/video-js.swf$object,1p`

and modify their filter but - as they add other and other domains ... will soon be broken

**Comment by ghajini** [comment] 2019-06-02 06:43
> 
> 
> Is this an Opera only issue?
not really ,site is blocked on my network, hence need to use opera browser's vpn for accessing that....firefox also suffers,just checked....
allowing @mapx- filter takes care ....
may be make that filter ***less generic***

**Comment by ghajini** [comment] 2019-06-02 07:00
@ryanbr @smed79 abp also suffers
