### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by stefan85224** [uBlockOrigin/uAssets#19992] opened 2023-10-06 16:15 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=PR-WmxKlct4&ab_channel=Girlfail2`

### Category

detection

### Description

Youtube detects now the uBlock Origin. It dosen't matter what video I am looking, it detects it and shows me a Message that i use a blocker.

### Other extensions used

Ad Block
Ghostery
SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://www.youtube.com/watch?v=H_0d9g83LaY&ab_channel=Jimi

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 109
filterset (summary):
 network: 106788
 cosmetic: 44621
 scriptlet: 18715
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  DEU-0: 7096-0, now
  easylist: 71554-19, now
  easyprivacy: 33213-73, now
  plowe-0: 3717-1065, now
  ublock-badware: 7186-133, now
  ublock-filters: 34971-157, now
  ublock-privacy: 557-6, now
  ublock-quick-fixes: 173-29, 1h.7m
  ublock-unbreak: 2132-32, now
  urlhaus-1: 11180-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1694 ms (selfie)
 maxAssetCacheWait: 316 ms
popupPanel:
 blocked: 206
 network:
  youtube.com: 106
  doubleclick.net: 7
  google.com: 93
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, …
  #@#+js(json-prune-fetch-response, [].playerResponse.adPlacements…
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/,…
```
</details>

**Comment by gwarser** [comment] 2023-10-06 16:18
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19976

**Closed** 2023-10-06 16:17 UTC
Labels: duplicate

**Comment by stephenhawk8054** [comment] 2023-10-06 16:19
> Ad Block
>
> Ghostery

Turn off all other extensions, restart the browser and test again.

Then only discuss in this thread: https://github.com/uBlockOrigin/uAssets/issues/19976

> [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
