### ISSUE TITLE
ca.investing.com: nuisance

### ISSUE THREAD

**Issue by tomlinite** [uBlockOrigin/uAssets#18926] opened 2023-07-10 13:50 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ca.investing.com/`

### Category

nuisance

### Description

Overlay requesting the disabling of adblocker.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 25d.9h.4m
Chromium: 114
filterset (summary):
 network: 96813
 cosmetic: 39532
 scriptlet: 17956
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68143-11, now
  easyprivacy: 33422-63, now
  plowe-0: 3739-1074, now
  ublock-badware: 7536-139, now
  ublock-filters: 33893-145, now
  ublock-privacy: 428-4, now
  ublock-quick-fixes: 346-84, now
  ublock-unbreak: 2070-31, now
  urlhaus-1: 6426-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms (selfie)
 maxAssetCacheWait: 195 ms
popupPanel:
 blocked: 14
 network:
  investing.com: 2
  adnxs.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 2
  google-analytics.com: 1
  googleadservices.com: 1
  googletagmanager.com: 1
  hotjar.com: 1
  outbrain.com: 1
  pbxai.com: 1
  scorecardresearch.com: 1
 extended:
  ##.dfpAdUnitContainer
  ##.rightColumnAd
  ###ad1
  ###ad2
  ###ad3
  ###findABroker
  ##.dfp-native
  ##.dfpVideo
  ##.generalOverlay
  ##.midHeader
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by okiehsch** [comment] 2023-07-10 13:54
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18917

**Closed by okiehsch** 2023-07-10 13:54 UTC
