### ISSUE TITLE
warecracks.com: badware

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#14046] opened 2022-07-16 15:11 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://warecracks.com/facerig-pro-crack/`

### Category

[unknown]

### Describe the issue

`https://www.virustotal.com/gui/file/3d05b67e336f8a4776a32c6a699d9889a1adb71b3831e80c487b4ae40670ffe1`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80412
  cosmetic: 45748
  scriptlet: 17459
  html: 706
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32823-126, 35m
    ublock-badware: 4228-3, 35m
    ublock-privacy: 240-0, 35m
    ublock-abuse: 77-0, 35m
    ublock-unbreak: 1852-0, 35m
    ublock-quick-fixes: 224-0, 35m
    easylist: 68410-511, 35m
    easyprivacy: 27422-585, 35m
    urlhaus-1: 4970-0, 35m
    plowe-0: 3644-3, 35m
    VIE-1: 1836-1, 35m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 190 ms (selfie)
  maxAssetCacheWait: 263 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    wp.com: 2
```
</details>

**Comment by MasterKia** [comment] 2022-07-16 15:37
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14045

**Closed** 2022-07-16 15:44 UTC
