### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by BGRSSHN** [uBlockOrigin/uAssets#14740] opened 2022-09-09 09:36 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

can't block ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83742
  cosmetic: 47800
  scriptlet: 18215
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8469-20, 21h
    easylist: 64470-68, 20h.58m
    easyprivacy: 27498-131, 20h.57m
    plowe-0: 3671-837, 20h.56m
    ublock-abuse: 76-0, 20h.54m
    ublock-badware: 4222-101, 20h.52m
    ublock-filters: 32579-121, 20h.51m
    ublock-privacy: 251-1, 20h.50m
    ublock-quick-fixes: 431-1, 20h.48m
    ublock-unbreak: 1851-40, 20h.47m
    urlhaus-1: 7716-0, 20h.46m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 470 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    amazon-adsystem.com: 2
    amplitude.com: 1
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 2
    google-analytics.com: 2
    imrworldwide.com: 1
    scorecardresearch.com: 24
    sentry.io: 3
```
</details>

**Comment by MasterKia** [comment] 2022-09-09 09:37
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-09-09 09:37
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-09-09 09:37 UTC
