### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by KrakenNG** [uBlockOrigin/uAssets#14328] opened 2022-08-09 08:31 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

advertisement  in twitch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 83850
  cosmetic: 51667
  scriptlet: 17983
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-quick-fixes: 356-3, 20h.27m
  default: 
    user-filters: 0-0, never
    TUR-0: 8730-66, 1d.39m
    easylist: 69301-69, 1d.44m
    easyprivacy: 27300-128, 1d.42m
    plowe-0: 3640-778, 6d.12h.36m
    ublock-abuse: 76-0, 20h.28m
    ublock-badware: 4176-92, 1d.40m
    ublock-filters: 32398-131, 1d.41m
    ublock-privacy: 231-3, 20h.29m
    ublock-unbreak: 1852-43, 1d.43m
    urlhaus-1: 6920-0, 20h.26m
filterset (user): [empty]
modifiedUserSettings: 
  largeMediaSize: 8
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 35768 ms (selfie)
  maxAssetCacheWait: 1050 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    amazon-adsystem.com: 2
    ddacn6pr5v0tl.cloudfront.net: 1
    google-analytics.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-08-09 09:01
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by okiehsch** 2022-08-09 09:01 UTC
