### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by ADRBT** [uBlockOrigin/uAssets#14493] opened 2022-08-22 16:34 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/feed/subscriptions`

### Category

ads

### Describe the issue

Not working as intended, still showing ads no matter what

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 84179
  cosmetic: 50272
  scriptlet: 17906
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 69560-51, 4d.12h.15m
    easyprivacy: 27354-127, 4d.12h.14m
    plowe-0: 3630-777, 8d.15h.40m
    spa-0: 3897-37, 1d.1h.25m
    spa-1: 4592-176, 4d.12h.16m
    ublock-abuse: 76-0, 8d.15h.38m
    ublock-badware: 4233-92, 4d.12h.13m
    ublock-filters: 32507-173, 4d.12h.12m
    ublock-privacy: 231-3, 8d.15h.34m
    ublock-quick-fixes: 381-0, 1d.1h.24m
    ublock-unbreak: 1858-45, 4d.12h.11m
    urlhaus-1: 5688-0, 1d.1h.23m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1948 ms (selfie)
  maxAssetCacheWait: 612 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    youtube.com: 26
    doubleclick.net: 4
    googlesyndication.com: 7
```
</details>

**Comment by MasterKia** [comment] 2022-08-22 16:39
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-22 16:39 UTC
