### ISSUE TITLE
KissAnime.ru.boohoo specifically calling out uBlock and preventing viewing

### ISSUE THREAD

**Issue by Zetawilk** [uBlockOrigin/uAssets#3850] opened 2018-10-27 02:34 UTC
### URL(s) where the issue occurs

`http://kissanime.ru/Anime/JoJo%60s-Bizarre-Adventure-Golden-Wind/Episode-004?id=151444&s=default`

### Describe the issue

Erroneous behavior:
Videos on loaded pages are swiftly replaced with a message demanding the user disable ublock or other ad blockers on their own computer, and that the user has been "banned" from the site for several days (even if they don't and wouldn't have an account). 

Expected behavior:
The video doesn't disappear and plays as per usual, and kissanime doesn't baw about what people have the right to put on their own computer, and they go out and get real jobs to earn real money instead of crying about revenue from advertisements nobody likes let alone trusts. 

### Screenshot(s)

I'd put a screenshot here (if that's even possible with this form), but since I disabled all cookie access from kissanime, I just get that meaningless five second waiting period placebo. 

### Versions

- Browser/version: Firefox 62.0.3 (the Internet)
- uBlock Origin version: 1.17.3b2

### Settings

- None.

### Notes

I learned search engines aren't particularly helpful, least of all Google. I also learned never trust a Russian.

**Comment by okiehsch** [comment] 2018-10-27 02:40
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2719

**Closed by okiehsch** 2018-10-27 02:40 UTC
