### ISSUE TITLE
Brid.tv / index.hr filter not working

### ISSUE THREAD

**Issue by bmatic385** [uBlockOrigin/uAssets#13361] opened 2022-05-23 11:33 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.index.hr/magazin/clanak/courtney-love-johnny-depp-mi-je-spasio-zivot-kad-sam-se-predozirala/2366389.aspx`

### Describe the issue

When trying to play video on site index.hr uBlock blocks ad, but can not play video.
When I click on play button on video, video box turn black, and nothing happens.
Videos are embedded from Brid.tv platform.

### uBlock Origin version

1.42.4

### Browser name and version

Mozzila Firefox for Ubuntu v100.0.2 (64-bit)

### Settings

No changes.

**Comment by Yuki2718** [comment] 2022-05-23 16:25
Provide details about your settings including enabled filter lists.

**Comment by okiehsch** [comment] 2022-05-23 18:31
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/13324


Update the `uBO-unbreak` list the issue was fixed three days ago.

**Closed by okiehsch** 2022-05-23 18:31 UTC
Labels: unable to reproduce

**Comment by bmatic385** [comment] 2022-09-22 23:19
There was some change, and again, it is showing "Loading ad" and no video playback.
Example:

https://www.index.hr/vijesti/clanak/video-lavrov-zakasnio-sat-i-pol-na-sjednicu-una-ukrajince-usporedio-s-nacistima/2397356.aspx
