### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Allu71** [uBlockOrigin/uAssets#14548] opened 2022-08-27 10:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=Ga3UQBeVDb0`

### Category

ads

### Describe the issue

ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82090
  cosmetic: 45352
  scriptlet: 17729
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    FIN-0: 2013-1, 5m
    easylist: 67552-51, 5m
    easyprivacy: 27436-127, 5m
    plowe-0: 3633-776, 5m
    ublock-abuse: 76-0, 5m
    ublock-badware: 4162-96, 5m
    ublock-filters: 32487-121, 5m
    ublock-privacy: 241-3, 5m
    ublock-quick-fixes: 394-5, 5m
    ublock-unbreak: 1839-41, 5m
    urlhaus-1: 6711-0, 5m
filterset (user): [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9037 ms (selfie)
  maxAssetCacheWait: 205 ms
popupPanel: 
  blocked: 108
  blockedDetails: 
    youtube.com: 92
    doubleclick.net: 3
    google.com: 5
    googlesyndication.com: 2
    googlevideo.com: 6
```
</details>

**Comment by Yuki2718** [comment] 2022-08-27 10:36
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by Yuki2718** 2022-08-27 10:36 UTC
Labels: duplicate

**Comment by MasterKia** [comment] 2022-08-27 10:40
See: https://github.com/easylist/easylist/wiki/youtube-issues
