### ISSUE TITLE
duckduckgo.com: breakage

### ISSUE THREAD

**Issue by frankenzombies** [uBlockOrigin/uAssets#19828] opened 2023-09-23 04:06 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Using DuckDuckGo causes a redirect loop when Ublock is active.

### A specific URL where the issue occurs.

`https://duckduckgo.com/`

### Steps to Reproduce

1. Visit url with Ublock active
2. Browser will spit out error

### Expected behavior

Able to use search engine as normal

### Actual behavior

The browser says the page isn't redirecting properly.

### uBO version

1.52.0

### Browser name and version

Librewolf 117.0.1-1

### Operating System and version

Win 10 Home 21H2

**Comment by stephenhawk8054** [comment] 2023-09-23 04:16
Librewolf enables some additional lists. Please turn off them to see which list causes issue.

**Comment by ziaulrehman12** [comment] 2023-09-23 06:38
I use Firefox and i'm facing the same issue. i tried enabling filters one by one and i think 'AdGuard URL Tracking Protection' is causing the issue in my case because when i enable it, ddg says 'The page isn’t redirecting properly' but when i disable it ddg works fine.

**Comment by stephenhawk8054** [comment] 2023-09-23 06:44
I can't really reproduce it.

@Yuki2718 @Alex-302 Sorry, can you take a look?

**Comment by Yuki2718** [comment] 2023-09-23 07:34
No such issue on my end with or without AGURLTP. Needs *details* and *steps to reproduce*.

**Comment by Yuki2718** [comment] 2023-09-23 11:23
On my end `atb`, `perf_id`, and `parent_perf_id` are removed but no problem.

**Comment by stephenhawk8054** [comment] 2023-09-23 11:24
Not sure if it's geo-related?

@SlomoDuke Which country are you when accessing the site?

**Comment by SlomoDuke** [comment] 2023-09-23 11:50
> @SlomoDuke Which country are you when accessing the site?

Italy.

> @SlomoDuke I can't reproduce that `atb` parameter but when I add:

Maybe the location you are accessing DDG from does not make use of the [atb parameter](url=https://duckduckgo.github.io/duckduckgo-help-pages/privacy/atb/).

But what if you click on https://duckduckgo.com/?q=github+login&atb=v352-1&ia=web, which is an example of url generated when I search for something, isn't the filter causing a "The page isn’t redirecting properly" error  in Firefox?

**Comment by mapx-** [comment] 2023-09-23 11:59
Tested from Italy => no such error

**Comment by SlomoDuke** [comment] 2023-09-23 11:59
As for when DuckDuckGo decides to use or not use the 'atb' parameter (https://duckduckgo.github.io/duckduckgo-help-pages/privacy/atb) in the urls of their search queries, I have no clue, but for sure it happens to me. I started to see this issue 2-3 days ago.

Maybe DDG have recently enabled the use of that parameter by default in some geographies as @stephenhawk8054 suggests above or there we have DDG search settings that are different (I don't store any DDG setting and I clear cookies, data, history etc. at browser close).

**Comment by SlomoDuke** [comment] 2023-09-23 12:02
> Tested from Italy => no such error

Thanks for having checked. Doy confirm you used the offending url (https://duckduckgo.com/?q=github+login&atb=v352-1&ia=web) and had _AdGuard URL Tracking Protection_ filter enabled?

**Comment by stephenhawk8054** [comment] 2023-09-23 12:13
I tested 3 ways (AG URL TP enabled and VPN to Italy): from duckduckgo home page, from URL bar and access the link directly. I still cannot reproduce the issue.

**Comment by SlomoDuke** [comment] 2023-09-23 12:21
Weird, I would expect it to trigger at least from the direct url containing the 'atb' parameter. 
Is your AdGuard URL Tracking Protection list up-to-date and containing the below?
```

! DuckDuckGo
! https://duckduckgo.github.io/duckduckgo-help-pages/privacy/atb/
||duckduckgo.com^$removeparam=atb                           <----
```
Is there any further log/information I can provide?

**Comment by stephenhawk8054** [comment] 2023-09-23 12:23
Yes, it removes that query successfully for me without breakages: https://github.com/uBlockOrigin/uAssets/assets/66517106/4f858ce8-8225-4a22-887f-6879ffbd8f37

**Comment by SlomoDuke** [comment] 2023-09-23 12:39
Ok, I think I probably have found the issue, at least the one affecting my machine. 

uBlock Origin is clashing with the _DuckDuckGo Privacy Essentials_ extension, which I had set to _OFF_ for the duckduckgo.com website but still was evidently interfering:
![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/2e0954ac-82f2-493a-af22-275cda282a35)

If I _properly disable_ the DuckDuckGo Privacy Essentials extension, then the 'atb' parameter is removed from the search url (i.e. the AdGuard URL Tracking Protection filter does its job) and the results page is shown as it should.

So, apologize for having made a newbie error when I marked 
![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/96d30032-fe6f-4cc1-9e5b-eda08a877c2c)
as setting the other extension to OFF for the site while the extension is enabled is not sufficient. 

This is what instead needs to be done:
![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/dbaef9c5-f019-48c9-b19f-dfd1d487fcbc)

Thanks to all of you who helped, really appreciated @stephenhawk8054 @mapx- @MasterKia @Yuki2718. And sorry again for the misleading information re. other extensions being actually disabled.

**Comment by Yuki2718** [comment] 2023-09-23 12:59
You should not run DuckDuckGo Privacy Essentials alongside with uBO.

> 
> ### I tried to reproduce the issue when...
> * [x]  uBO is the only extension.

I heard other conflicts cases as well.

**Comment by Yuki2718** [comment] 2023-09-23 13:04
Closing, I can reproduce if DDGPE and AGURLTP are enabled on Firefox (not on Chromium though).

**Closed by Yuki2718** 2023-09-23 13:04 UTC
Labels: unable to reproduce, Waiting for feedback, broken by other list

**Comment by SlomoDuke** [comment] 2023-09-23 13:09
> You should not run DuckDuckGo Privacy Essentials alongside with uBO.

I have been running both extension for years without issues, but I'll keep this in mind in case of additional problems.

For the posterity, the workaround I have found for the issue described in this case is to whitelist/exclude the _$removeparam=atb_ rule for the duckduckgo.com site in uBlock configuration (uBlock > Dashboard > MyFilters):

```
! https://duckduckgo.com - disable a specific rule in 'AdGuard URL Tracking Protection' filter that is clashing with DuckDuckGo Privacy Essentials extension:
@@||duckduckgo.com^$removeparam=atb
```

**Comment by Nimras186** [comment] 2023-09-23 13:56
I am running into this problem duckduckgo.com works fine but the second I try to do a search I get the redirect issue, when I disabled Ublock it works, if I disable the AdGuard "URL Tracking Protection" filter it instantly works as planned.

Disabling the DDGPE and enabling the filter and it works so why is DDGPE breaking this now?

And is there a fix?

**Comment by Nimras186** [comment] 2023-09-23 14:12
> > so why is DDGPE breaking this now?
> 
> Maybe you should ask _them_?

Yeh never really had to use them before always worked but I guess I need to find a way of contacting them, was just wondering why that filter manage to break DDGPE or vice versa lol.

**Comment by colejohnson66** [comment] 2023-09-24 12:25
Can confirm. DDG Privacy Essentials seems to be the culprit. Could it be that uBlock (one of the lists) removes a URL parameter that DDGPE then puts back in?
