### ISSUE TITLE
kisscartoon.ac

### ISSUE THREAD

**Issue by pokee200** [uBlockOrigin/uAssets#2363] opened 2018-05-24 21:27 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://kisscartoon.ac/]`

### Describe the issue

[any video you played it asked for closing Ad block]

### Screenshot(s)

[https://imgur.com/MLeG0k6]

### Versions

- Browser/version: [firefox 56]
- uBlock Origin version: [uBlock Origin v1.16.6]

### Settings

- [using Nano Defender Integration​​​​​-Nano filters​​-Nano filters - Whitelist​​​​​​ ]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment] 2018-05-24 21:36
I can't reproduce, example:
` https://kisscartoon.ac/Cartoon/SpongeBob-SquarePants-Season-11-2017.96810/Episode-036-Ink-Lemonade?id=79589`

The video plays fine with Chrome and Firefox on my end, you are using Firefox 56, that could be the reason you are having this issue.

**Comment by zaphodbeebblebrox** [comment] 2018-05-24 22:10
To reproduce:
Go to `https://kisscartoon.ac/Cartoon/SpongeBob-SquarePants-Season-11-2017.96810/Episode-036-Ink-Lemonade?id=79589`.
Click the play video button in the middle of the video, do not go into fullscreen mode.
Wait 10-15 seconds, something like 
![this](https://user-images.githubusercontent.com/22801430/40516177-a44e10f4-5f7d-11e8-8e75-f154f70314f3.png) will appear.

To remove: `kisscartoon.*###upgrade_pop`

**Comment by okiehsch** [comment] 2018-05-24 22:12
Thx, that I can reproduce, though I would not say that it is "asking for closing Ad block"  like the OP mentioned.

**Closed** 2018-05-24 22:15 UTC
