### ISSUE TITLE
youmath.it: detection

### ISSUE THREAD

**Issue by max334422** [uBlockOrigin/uAssets#11350] opened 2022-01-17 20:53 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youmath.it/formulari/formulari-di-geometria-analitica/3343-coniche-degeneri-e-non-degeneri.html`

### Category

detection

### Describe the issue

I am accessing the site but after a few seconds that im in and reading, it detects ublock and asks me to disable it to continue reading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78127
  cosmetic: 40513
  scriptlet: 16423
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30752-29, 2d.3h.16m
    ublock-badware: 3723-1, 2d.3h.22m
    ublock-privacy: 187-0, 2d.3h.21m
    ublock-abuse: 76-0, 2d.3h.20m
    ublock-unbreak: 1733-0, 2d.3h.19m
    easylist: 63006-583, 2d.3h.18m
    easyprivacy: 26626-481, 2d.3h.17m
    urlhaus-1: 7135-0, 18m
    plowe-0: 3684-2, 6d.5h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 805 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by uBlock-user** [comment] 2022-01-17 20:54
> I verified that the issue has not already been reported (use this button to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11337

**Closed by uBlock-user** 2022-01-17 20:54 UTC
