### ISSUE TITLE
computerbase.de: Microsoft Edge Crash

### ISSUE THREAD

**Issue by kloetsack** [uBlockOrigin/uAssets#16613] opened 2023-02-02 21:12 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Visiting computerbase.de causes Edge to hang for about 30 seconds and generate a crashlog

### URL(s) where the issue occurs.

`https://www.computerbase.de`

### uBO version

1.46.0

### Browser name and version

Microsoft Edge 109.0.1518.70

### Settings

Show Number of Blocked request is OFF
About 5 Filters for other websites
Reset uBlockOrigin to default and tried different settings/filters/etc.

### Notes

Steps to replicate:

Visit `https://www.computerbase.de` (preferably in a new InPrivate-Window, if not clear cache completely maybe restart browser for each test)

After 'accepting' ads on the paywall Edge will freeze for about 30 seconds (obvious if you open any other links in the background - these tabs will stop loading, pages are completely white, loading-circle on the tab just spins - after about 30 seconds background pages will continue to load)

A .dmp file will be generated when the error occurs - see: edge://crashes/ or (%localappdata%\Microsoft\Edge\User Data\Crashpad\reports)

What I found out so far:
- Might be affected by cache (only noticed this on first browser start in a normal edge-window, after clearing cache, or in an InPrivate-Window)
- Whatever happens/gets blocked causes Edge to hang and generate the .dmp-file - I assume it is not uBlock directly causing the freeze, but generating the dump file is - since it is not noticable in a regular browsing-session when the site has already been visited before
- Important: It seems that a new .dmp-file only gets generated after at least 5 minutes since the last one!
- Deactivating 'uBlock filters' (the first of the 6 uBlock-own filterlists) fixes the issue
https://user-images.githubusercontent.com/124305110/216446930-3b3f2d8e-3b6f-40a7-a12e-855cbcbfddf3.png
Here is a screenshot of what uBlock detects on the site
https://user-images.githubusercontent.com/124305110/216447832-20f4912e-4533-490a-a9ae-90fde5847c7e.png
IIRC this is the same with the 'uBlock filters'-list on or off

Thanks

**Comment by mapx-** [comment] 2023-02-02 23:11
> After 'accepting' ads on the paywall

I get no paywall ?!

**Comment by kloetsack** [comment] 2023-02-02 23:26
I mean this popup
![popup](https://user-images.githubusercontent.com/124305110/216473864-784ddb48-530a-4130-bd8f-3df03b44577c.png)

**Comment by mapx-** [comment] 2023-02-02 23:34
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by kloetsack** [comment] 2023-02-02 23:49
I already deleted %localappdata%\Microsoft\Edge\User Data -> complete reset of Edge
Reinstalled uBlockOrigin
Issue also occurs with default uBlock settings (Filter lists are updated)
Disabled all other extensions (problem only occurs, when the first uBlockOrigin filter is checked)
No other blocking software installed
DNS is not modified
System got already restarted a couple of times during the last few days, since I noticed and tried to find the issue

**Comment by iam-py-test** [comment] 2023-02-03 00:22
You seem to be behind on updates (the latest Edge is 109.0.1518.78). Can you still repro on the newest version?

**Comment by kloetsack** [comment] 2023-02-03 00:39
Thats gotta be pretty new - checked a few hours ago.
Gonna test in a min, my crash is on cooldown...
It definitely only happens, when i check this first uBO filterlist.
Tried disabling trackin protection and defender smart screen, reset uBO -> still happening

Checked -> dmp file
unchecked -> nothing

Tried unchecking the filterlist i mentioned but copied its content into 'my filters' -> dmp file, browser hang
Damn I thought I had something, but edge://crashes/ itself just would not update, because of this whole issue.

Gonna update and check, back in a few minutes

**Comment by kloetsack** [comment] 2023-02-03 00:51
OK, updated Edge, cleared cache/etc, no other extensions active, reset uBO und updated filters, disabled Edge tracking protection/defender smart screen/and something with secure dns in edge
open new inprivate window - visit site - click the popup away - close inprivate, back to regular window - edge://crashes/
and i got a new dmp file.

@mapx: did you get the popup?
don't clear history right after visiting the site, it also clears dmp files

**Comment by kloetsack** [comment] 2023-02-03 01:24
So I got it to not crash I think - at least once.
What I did:
deleted %localappdata%\Microsoft\Edge\User Data -> complete reset of Edge (settings, extensions, bookmarks...)
Open Edge, skip through the settings page so I can use the browser, installed uBlockOrigin, updated Filters, went to computerbase (no dmp so far) clicked the popup away - and it still seemed fine.
Reopened Edge and tried again - crashed again

**Comment by iam-py-test** [comment] 2023-02-03 01:35
Wonder if anyone here has the skills to analyze a dump file. 
A few questions: Do you use Edge's sync? Do you sign into Edge? If uBo installed from the Microsoft extensions store or the Chrome one?

**Comment by kloetsack** [comment] 2023-02-03 01:40
No Edge sync, Not signed in. 
Tried uBO from both, normally Edge store, after this reset chrome store, doesn't matter.
I tried opening the dbg files with BlueScreenView - didn't work
Tried WinDbg from Microsoft Store didn't really tell me much... something with msedge_elf.dll

**Comment by iam-py-test** [comment] 2023-02-03 02:42
Odd. Do you have any security software installed (firewall, antimalware, etc)?

**Comment by kloetsack** [comment] 2023-02-03 03:36
To sum this all up a little bit - the issue only happens:
- Microsoft Edge (didn't test other chromium based browsers)
- computerbase.de (haven't noticed anywhere else)
- since a few weeks
- with first uBO-own filterlist enabled (see screenshot above)
- on second or later browser starts (after deleting %localappdata%\Microsoft\Edge\User Data)
	on first start edge propably downloads something to edge\user data
	on second start, there is some stuff added under settings then
- when fetch request from either googlesyndication or googletagmanager is allowed (blocked everything via noscript and tried one by one), so I assume uBO tries to block these then
- when setting computerbase.de googlesyndication.com * block and computerbase.de googletagmanager.com * block as dynamic rules -> dbg file, browser hang

But: when setting computerbase.de googlesyndication.com * allow and computerbase.de googletagmanager.com * allow -> no dbg file (even with first uBO filterlist enabled)

@iam-py-test: No, just Windows 10 default

**Comment by kloetsack** [comment] 2023-02-03 04:57
A few more things...
Given the fact that it works after the first Edge start after a complete reset (only installing uBO) seems to me like this is not a pc problem on my end (I even tried and repaired Edge via apps - Edge - change and then repair).
When i then restart the browser the issue starts to happen. IDK what exactly Edge updates in the %localappdata%\Microsoft\Edge\User Data folder that propably is part of the problem, but this should not be a only me problem (since i did nothing but install uBO until then) but happen to everyone else using Edge with uBO and visiting this site and propably some other sites which try to load the same stuff than this one?
One thing I just noticed is that this site has a WebApp - I never installed it and there is no popup or something that tries to make you install it - just saying.
![app](https://user-images.githubusercontent.com/124305110/216513886-5be24676-a608-460b-a8b5-bb57e0412f3e.png)

Also the (kinda paywall) popup mentioned above isn't really relevant to the issue. As long as it is displayed there is no problem (besides you can't view the site). I only get a dmp file after clicking it away. Also if I close the site, wait 5 minutes and then reopen it -> hang and dmp file.

**Comment by stephenhawk8054** [comment] 2023-02-03 05:29
You might need to use [Chromium Profiler](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/) and upload the saved profile here so someone else can investigate it.

**Comment by garry-ut99** [comment] 2023-02-03 12:57
Invalid, browser crashes are a browser issue: https://github.com/uBlockOrigin/uBlock-issues/issues/2471#issuecomment-140886196.
Only "freezing" issues are accepted, example: https://github.com/uBlockOrigin/uBlock-issues/issues/2469

**Comment by kloetsack** [comment] 2023-02-03 13:54
> Invalid, browser crashes are a browser issue: [uBlockOrigin/uBlock-issues#2471 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/2471#issuecomment-140886196) Only "freezing" issues are accepted, example: [uBlockOrigin/uBlock-issues#2469](https://github.com/uBlockOrigin/uBlock-issues/issues/2469)

Edge doesn't crash, it freezes for 10-60 seconds, which is why sometimes you can't really notice because it keeps working again after a few secs. That's why looking at edge://crashes/ is how to see that something is off.
Browserwindow stays open all the time, you can switch tabs, they just don't load/reload. When you got uBO settings page open you can reload it but not change between its settings tabs.
It seems like it just goes offline.

**Comment by kloetsack** [comment] 2023-02-03 13:58
Gonna look at Chromium Profiler and test Beta/Dev... maybe even other Chromium browser.

Has anyone been able to at least reproduce this jet?

**Comment by kloetsack** [comment] 2023-02-03 16:44
First uBO filterlist off (no dmp)
![1](https://user-images.githubusercontent.com/124305110/216659011-7dce9abe-6016-44ee-93e4-1b75e2cf7b4a.png)

First uBO filterlist on (freeze, dmp file)
![2](https://user-images.githubusercontent.com/124305110/216659119-c12c0be8-1d46-4971-9e31-3485c8feb3b9.png)

**Comment by stephenhawk8054** [comment] 2023-02-03 16:51
Screenshots will not help. Did you save the profile as instruction?

https://developer.chrome.com/docs/devtools/performance/reference/#save

**Comment by kloetsack** [comment] 2023-02-03 17:38
I did save them, just looking into them right now. 
If theres something in particular that you need, let me know. 
I know that screenshots are not the best way to do this, but I don't know how much info is in there and how I feel about uploading them jet...

A few more from when the freeze happens:

![konsole](https://user-images.githubusercontent.com/124305110/216669231-1e505932-c228-4131-9d56-a7d16e7b89f8.png)

![network](https://user-images.githubusercontent.com/124305110/216669242-c801f27c-4a04-49bb-b244-607b645e4934.png)

![perf](https://user-images.githubusercontent.com/124305110/216669248-00ebd717-e22c-4289-af83-88f971af55c6.png)

**Comment by kloetsack** [comment] 2023-02-03 18:09
First uBO filterlist off (no dmp)
![working](https://user-images.githubusercontent.com/124305110/216675952-3832386f-daab-40d9-b5ca-61a9bfd64d20.png)


First uBO filterlist on (freeze, dmp file)
![no](https://user-images.githubusercontent.com/124305110/216675965-930b7a4f-995c-4557-9a9a-a9d2b21e7f57.png)

**Comment by kloetsack** [comment] 2023-02-03 19:04
I just tried Edge Beta which also generates a dmp file.
Also tried Chrome and it also generates a dmp file (has to be activated first, see chrome://crashes)

![chrome](https://user-images.githubusercontent.com/124305110/216685893-74d61e89-42b8-4aa9-b952-74831fb5e237.png)

**Comment by stephenhawk8054** [comment] 2023-02-04 00:41
Can you upload the saved profile file here? So others can help investigate.

**Comment by kloetsack** [comment] 2023-02-04 01:46
Honestly I'd prefer if someone here would able to reproduce the issue and then check his own devtools recordings...
I have no idea what exactly gets logged there and that I might not want to post publicly.
If someone has an idea and points me to where to look/what to klick - I will post more screenshots of that.

Tomorrow I might be able to check on a different PC and see if it also freezes on that site with uBO

**Comment by stephenhawk8054** [comment] 2023-02-04 01:50
Not sure if it's geo-related or not. @okiehsch @JobcenterTycoon Sorry can you reproduce the issue?

**Comment by okiehsch** [comment] 2023-02-04 04:44
No.

**Comment by mapx-** [comment] 2023-02-04 15:13
@kloetsack test this filter

`@@||googletagmanager.com/gtag/js$xhr,domain=computerbase.de`

**Comment by krystian3w** [comment] 2023-02-04 15:16
This can be small A/B Test be webmaster.

**Comment by kloetsack** [comment] 2023-02-04 20:25
I just tested it at someone elses PC 
Edge - no extensions - works fine
         - with uBO - dmp file gets generated

@mapx tried, still generates dmp.
Since setting computerbase.de googlesyndication.com * allow and computerbase.de googletagmanager.com * allow under rules and ticking 'advanced user' works, I tried to do a second line with: @@||googlesyndication.com/gtag/js$xhr,domain=computerbase.de 
which doesn't seem to work (googletagmanager shows green when I click uBO extension, googlesyndication still red)
What am I doing wrong here?

**Comment by krystian3w** [comment] 2023-02-04 20:30
Maybe main script `adsbegoogle.js` is still red.

**Comment by kloetsack** [comment] 2023-02-04 20:46
Thats how it looks now (with @@||googletagmanager.com/gtag/js$xhr,domain=computerbase.de)
![1](https://user-images.githubusercontent.com/124305110/216788779-c3056267-aea4-42b4-8bc0-5e94dafe9bc1.png)

with additional @@||googlesyndication.com/gtag/js$xhr,domain=computerbase.de
![2](https://user-images.githubusercontent.com/124305110/216788848-e97af612-c602-419f-bd98-b0ad029b4137.png)

**Comment by mapx-** [comment] 2023-02-04 21:11
`@@||googletagmanager.com/gtag/js$xhr,domain=computerbase.de`

not `@@||googlesyndication.com/gtag/js$xhr,domain=computerbase.d`

**Comment by krystian3w** [comment] 2023-02-04 21:25
Learn how use logger:

https://github.com/gorhill/uBlock/wiki/The-logger

His red rows may better show unlocked resources/request like https://github.com/uBlockOrigin/uAssets/issues/16613#issuecomment-1416778480

**Comment by kloetsack** [comment] 2023-02-04 23:20
OK, so on top of filter that mapx posted:
@@||googletagmanager.com/gtag/js$xhr,domain=computerbase.de

I added:
@@||pagead2.googlesyndication.com/pagead/js/*$xhr,domain=www.computerbase.de
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*$xhr,domain=www.computerbase.de
@@||pagead2.googlesyndication.com/getconfig/*$xhr,domain=www.computerbase.de

And I get no dmp file anymore. 
I am not sure if this can be done with less exeptions...
Will this eventually be put into a uBO filter?




One more thing:

I don't think that this is a site-specific problem.
When I tested on someone elses PC today, I happened to find Opera already installed, so I tested there too.
First nothing - no dmp files. 
Then I realized that Opera was still on v94 (chromium 108.xxx). So I ran an update, tested again and got dmp files!
And I also found threads with people complaining about getting lots of these dmp files in different chromium based browsers - starting with v109.xxx

**Comment by krystian3w** [comment] 2023-02-04 23:23
As far as I'm concerned, this can disrupt privacy, so maybe it's better to wait for it to be fixed at the Chromium level - check their issues tracker:

https://crbug.com

**Comment by kloetsack** [comment] 2023-02-04 23:59
Well, after spending quite some time on figuring out this issue over the last few days, I think i'll pass on digging through 64000 bug reports...
I will keep these filters in my uBO for now and check if the issue is completely fixed that way or if freezes still occur with or even without dmp files being generated.
Then propably going to disable them every now and then or when Edge gets updated and test if it got fixed.

**Comment by garry-ut99** [comment] 2023-02-05 00:05
> kloetsack : I am not sure if this can be done with less exeptions...

It can be done by a single broader exception:
```adb
@@||pagead2.googlesyndication.com/*$xhr,domain=computerbase.de
```
- but it's not recommended, as it could accidentaly allow more requests which shouldn't be allowed.
- also `www.` can be omitted, but only if the issue occurs on subdomains too, otherwise it could accidentaly allow more requests which shouldn't be allowed

> kloetsack : Will this eventually be put into a uBO filter?

No, unless it will either:
- be proven at 100% that the issue is caused by uBO
- or many others users will have the same issue

**Comment by mapx-** [comment] 2023-02-05 05:48
closing for now but you can still comment here

**Closed by mapx-** 2023-02-05 05:48 UTC
