### ISSUE TITLE
mdn.lol: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#16582] opened 2023-01-31 15:59 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page
```
https://clks.pro/OWklx0mr1rm
https://mdn.lol/2022/08/21/where-do-we-really-feel-inflation/
```
### Category

detection

### Description

detection adblock 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83506
  cosmetic: 38547
  scriptlet: 17119
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 220-0, never
    easylist: 61357-46, 1h.31m
    easyprivacy: 30909-1172, 1h.31m
    plowe-0: 3668-898, 1h.31m
    ublock-abuse: 77-0, 1h.31m
    ublock-badware: 4216-119, 1h.31m
    ublock-filters: 32238-259, 1h.31m
    ublock-privacy: 259-1, 1h.31m
    ublock-quick-fixes: 519-141, 1h.31m
    ublock-unbreak: 1869-48, 1h.31m
    urlhaus-1: 6697-1, 1h.31m
filterset (user): [array of 85 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1132 ms (selfie)
  maxAssetCacheWait: 552 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    bambarmedia.com: 4
    clickiocdn.com: 2
    d3u598arehftfk.cloudfront.net: 1
    demand.supply: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    wtg-ads.com: 1
```
</details>

**Comment by iam-py-test** [comment] 2023-01-31 16:30
Where did you find that `clks[.]pro` link?

**Comment by iam-py-test** [comment] 2023-01-31 17:16
Ok, thanks. Just curious why antiadblock only appears with that link.

**Comment by ghajini** [comment] 2023-01-31 17:26
@king-iskan force update filters & see of that works

**Comment by garry-ut99** [comment] 2023-01-31 17:26
> king-iskan : detection adblock

I can reproduce. 

> king-iskan : 
> * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

(Another) duplicate of https://github.com/uBlockOrigin/uAssets/issues/16345, (previous duplicate here  https://github.com/uBlockOrigin/uAssets/issues/16207#issuecomment-1410293745) 

(not off-topic, technical facts related to the issue, confirming the issue on my site, it's useful, and another technical fact related to the issue, pointing users to the proper thread, it's useful as well)

**Comment by garry-ut99** [comment] 2023-01-31 17:31
> ghajini : king-iskan force update filters & see of that works

Working for me.

**Comment by king-iskan** [comment] 2023-01-31 17:39
> > ghajini : king-iskan force update filters & see of that works
> 
> Working for me.

ok, i try

**Closed** 2023-01-31 17:45 UTC

**Comment by king-iskan** [comment] 2023-01-31 17:49
> @king-iskan force update filters & see if that works

done. working. thanks

**Comment by Sandor-Helper** [comment] 2023-02-27 09:42
Problem link is `http://clks.pro/OW5471vw5vm`
Shows this message:
![1](https://user-images.githubusercontent.com/31479044/221528800-e8260306-4ba7-44fe-8ca0-f8d0798413b8.PNG)

**Comment by Sandor-Helper** [comment] 2023-02-28 08:02
Now it works in Chrome, thanks, but in Mozilla it still sees the adblock. I reset uBlock settings to default, it doesn't help.
Also cleared cookies. Adding this rule manually to filters doesn't help.
`https://www54.zippyshare.com/v/YtKnkHAX/file.html`

**Comment by stephenhawk8054** [comment] 2023-02-28 08:15
> `http://clks.pro/OW5471vw5vm`

I can't reproduce the anti-adblock on Firefox using above link.

**Comment by king-iskan** [comment] 2023-03-24 20:29
Now detection again in the middle step
![Screenshot_20230325-032818](https://user-images.githubusercontent.com/120553425/227632397-56f68098-9482-4764-bbae-b10ff606a16c.png)

**Comment by blader-render** [comment] 2023-03-28 08:01
For this link http://clks.pro/OW5471vw5vm
Need reproduce again, because hidden frame box recaptcha/cloudflare if allow adb

**Comment by stephenhawk8054** [comment] 2023-03-29 07:34
Can you click at `Continue` button?

**Comment by king-iskan** [comment] 2023-03-29 07:41
> It still "see adblock" as at the screen I posted before. Here I collect a log `https://www116.zippyshare.com/v/Ml63Z9VC/file.html`

i think already done, already reproduce by @stephenhawk8054. work better in all type browser (android or PC)

**Comment by stephenhawk8054** [comment] 2023-03-29 08:00
Can you send the screenshot again?

**Comment by Sandor-Helper** [comment] 2023-03-29 08:01
Its the same as in this post:
`https://github.com/uBlockOrigin/uAssets/issues/16582#issuecomment-1446012089`

**Comment by king-iskan** [comment] 2023-03-29 08:01
> > Bisakah Anda mengklik `Continue`tombol?
> 
> Tidak, tidak ada tombol apa pun, hanya frasa:
> 
> > Nonaktifkan adblocker Anda untuk mengunjungi halaman ini!
> 
> lihat tangkapan layar

clear filter all you have, purge all caches and update. should be work

**Comment by stephenhawk8054** [comment] 2023-03-29 08:19
Sorry, I can't reproduce the issue (video recording: https://user-images.githubusercontent.com/66517106/228471359-bb9e4d21-5e63-4d18-ae44-ff5a79fdad24.mp4).

Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

I cannot help you more. Good luck.

**Comment by king-iskan** [comment] 2023-03-30 16:57
need more help again, now detect again
![image](https://user-images.githubusercontent.com/120553425/228910040-db5139e6-c90a-4b85-bd44-55d4cfbfd9b4.png)

**Comment by king-iskan** [comment] 2023-03-31 10:17
is this kind of issue not reproduced anymore?

**Comment by mapx-** [comment] 2023-03-31 10:26
link ?

**Comment by king-iskan** [comment] 2023-03-31 10:29
> link ?

Still same link with above, 
`http://clks.pro/OW5471vw5vm`

**Comment by mapx-** [comment] 2023-03-31 10:32
404 Not Found

**Comment by king-iskan** [comment] 2023-03-31 10:35
> 404 Not Found

Sorry, maybe already delet in he server. 
You can try new link
`http://clks.pro/demo`

**Comment by mapx-** [comment] 2023-03-31 10:50
which should be the final destination in demo case ?

**Comment by king-iskan** [comment] 2023-03-31 11:00
> 

In last step, if allow adb, he cannot be solve. Just last step. But not allow adb. Can be solve. That the problem.
For that link goes to the site `https://gr8.cc/list/url-shorteners`

**Comment by mapx-** [comment] 2023-03-31 11:42
try

```
||clickiocdn.com/*log$script,important,from=mdn.lol,badfilter
||mdn.lol^$csp=script-src *
mdn.lol#@#+js()
@@||d3u598arehftfk.cloudfront.net/prebid_$script,domain=mdn.lol
```

**Comment by king-iskan** [comment] 2023-03-31 12:05
Done, work better 🙏👍
