### ISSUE TITLE
academy.hackthebox.com: detection

### ISSUE THREAD

**Issue by bceez** [uBlockOrigin/uAssets#12012] opened 2022-03-02 18:07 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://academy.hackthebox.com/dashboard`

### Category

detection

### Describe the issue

Login is required to see the anti-adblock script

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 97
filterset (summary): 
  network: 81504
  cosmetic: 24547
  scriptlet: 19267
  html: 634
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4437-7, 7m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30919-266, 7m
    ublock-badware: 3903-3, 7m
    ublock-privacy: 208-1, 7m
    ublock-abuse: 72-0, 7m
    ublock-unbreak: 1737-0, 7m
    adguard-mobile: 7285-169, 7m
    easylist: 64090-24265, 7m
    easyprivacy: 26639-579, 7m
    urlhaus-1: 8437-0, 7m
    plowe-0: 3673-2, 6m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  uiAccentCustom: true
  uiAccentCustom0: #21a1de
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8030 ms (selfie)
  maxAssetCacheWait: 3899 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    segment.com: 1
```
</details>

**Comment by mapx-** [comment] 2022-03-02 18:14
Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by bceez** [comment] 2022-03-02 18:21
<details><summary>Logger output</summary>

```
+51
##+js(set-constant, rwt, noopFunc)
www.google.com
dom
https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeI6LsaAAAAAKgdStgBC6B4UVbXlpYNaYGN46Ah&co=aHR0cHM6Ly9hY2FkZW15LmhhY2t0aGVib3guY29tOjQ0Mw..&hl=en-GB&v=PdoyIVkd8v16xl_NMp3H0N1Y&size=invisible&cb=1vghhd6v886k
```
```
+50
##+js(set-constant, rwt, noopFunc)
www.google.com
dom
https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeI6LsaAAAAAKgdStgBC6B4UVbXlpYNaYGN46Ah&co=aHR0cHM6Ly9hY2FkZW15LmhhY2t0aGVib3guY29tOjQ0Mw..&hl=en-GB&v=PdoyIVkd8v16xl_NMp3H0N1Y&size=invisible&cb=1vghhd6v886k
```
```
+44
||cdn.segment.com^
--
academy.hackthebox.com
3
script
https://cdn.segment.com/analytics.js/v1/eLzeD0QoARKZ42pc8AGEUYpcFLpYkf0I/analytics.min.js
```
```
+42
https://academy.hackthebox.com/dashboard
```
```
+4
##+js(set-constant, rwt, noopFunc)
www.google.com
dom
https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeI6LsaAAAAAKgdStgBC6B4UVbXlpYNaYGN46Ah&co=aHR0cHM6Ly9hY2FkZW15LmhhY2t0aGVib3guY29tOjQ0Mw..&hl=en-GB&v=PdoyIVkd8v16xl_NMp3H0N1Y&size=invisible&cb=clhl1tubhgp3
```
```
+3
##+js(set-constant, rwt, noopFunc)
www.google.com
dom
https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeI6LsaAAAAAKgdStgBC6B4UVbXlpYNaYGN46Ah&co=aHR0cHM6Ly9hY2FkZW15LmhhY2t0aGVib3guY29tOjQ0Mw..&hl=en-GB&v=PdoyIVkd8v16xl_NMp3H0N1Y&size=invisible&cb=clhl1tubhgp3
```
```
+1
||cdn.segment.com^
--
academy.hackthebox.com
3
script
https://cdn.segment.com/analytics.js/v1/eLzeD0QoARKZ42pc8AGEUYpcFLpYkf0I/analytics.min.js
```
```
+0
https://academy.hackthebox.com/dashboard
```
</details>

**Comment by bceez** [comment] 2022-03-02 18:25
<details><summary>Logger output</summary>

```
+9
||cdn.segment.com^
--
academy.hackthebox.com
3
script
https://cdn.segment.com/analytics.js/v1/eLzeD0QoARKZ42pc8AGEUYpcFLpYkf0I/analytics.min.js
```
```
+8
https://academy.hackthebox.com/dashboard
```
```
+1
||cdn.segment.com^
--
academy.hackthebox.com
3
script
https://cdn.segment.com/analytics.js/v1/eLzeD0QoARKZ42pc8AGEUYpcFLpYkf0I/analytics.min.js
```
```
+0
https://academy.hackthebox.com/dashboard
```
</details>

**Comment by mapx-** [comment] 2022-03-02 18:30
Are you sure in the logger you are seeing only this blocking filter?
`||cdn.segment.com^`

**Comment by bceez** [comment] 2022-03-02 18:37
I copy and pasted everything that was in the logger

**Comment by mapx-** [comment] 2022-03-02 18:45
Do you have the same issue using the desktop ?

**Comment by bceez** [comment] 2022-03-02 18:47
I unfortunately do not have a desktop

**Comment by mapx-** [comment] 2022-03-02 19:09
test these filters and see if you get some breakage

```
academy.hackthebox.com##.show.fade
academy.hackthebox.com##body:style(overflow:auto !important)
```

**Comment by bceez** [comment] 2022-03-02 19:15
I did not find any breakage after adding the filter

**Comment by mapx-** [comment] 2022-03-02 19:16
and .. is working ? no more detection ?

**Comment by bceez** [comment] 2022-03-02 19:19
after adding the filter the detection is gone

**Comment by bceez** [comment] 2022-03-02 19:22
Everything works

**Comment by mapx-** [comment] 2022-03-02 19:24
it will be fixed as annoyance in `uBlock filters – Annoyances`

**Comment by bceez** [comment] 2022-03-02 19:26
Thank you

**Closed** 2022-03-02 19:25 UTC
Labels: account required

**Comment by tsids** [comment] 2024-05-21 17:42
HackTheBox has changed their site. Now these two filters actually cause the site to break (modals can no longer be seen).

To test this, I reset UBlock Origin to factory settings. If I enable the `uBlock filters - Annoyances` filter, it doesn't allow me to access any modals. To fix it, I need to "disable" the `fade` and `overflow` by adding these 2 lines to `My Filters`:

```
academy.hackthebox.com#@#.show.fade
academy.hackthebox.com#@#body:style(overflow:auto !important)
```

I'd appreciate it if the filters below could be removed from `uBlock filters - Annoyances` since it causes the site to not operate properly. @mapx- 
```
academy.hackthebox.com##.show.fade
academy.hackthebox.com##body:style(overflow:auto !important)
```
