### ISSUE TITLE
canadacomputers.com: breakage

### ISSUE THREAD

**Issue by qeveren** [uBlockOrigin/uAssets#20407] opened 2023-11-02 00:32 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.canadacomputers.com/login.php`

### Category

breakage

### Description

The "Login" button is non-responsive when uBlock Origin is enabled for the site, preventing the user from logging in.  Disabling uBlock and reloading the page restores function.

### Other extensions used

NoScript (disabled while testing this site)
BetterTTV
TTV LOL PRO
Image Search Options
Load Reddit Images Directly
View Image Info Reborn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104828
 cosmetic: 40334
 scriptlet: 18692
 html: 1077
listset (total-discarded, last-updated):
 default:
  user-filters: 22-0, never
  ublock-filters: 36028-136, 1m
  ublock-badware: 7416-5, 1m
  ublock-privacy: 667-0, 1m
  ublock-unbreak: 2181-0, 1m
  ublock-quick-fixes: 211-42, 1m
  easylist: 72249-698, 1m
  easyprivacy: 32853-724, 1m
  urlhaus-1: 11340-0, 7m
  plowe-0: 3721-1, 1m
filterset (user): [array of 22 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 159 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 7
 network:
  canadacomputers.com: 2
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  windows.net: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by gorhill** [comment] 2023-11-02 00:38
Caused by `/jquery.browser-fingerprint-` in EasyPrivacy.

cc @ryanbr

**Comment by gorhill** [comment] 2023-11-02 00:39
You can add `@@/jquery.browser-fingerprint-$domain=canadacomputers.com` until it's fixed in the list.

**Closed** 2023-11-02 01:51 UTC
Labels: broken by EasyPrivacy, fixable by EasyPrivacy
