### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by afroeagle** [uBlockOrigin/uAssets#10972] opened 2021-12-18 16:34 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

While watching any YouTube video, when using keyboard shortcuts to seek backwards/forwards (either using 'j' or 'l' or the left and right arrow keys) the input simultaneously performs the desired seek action, but it also activates the YouTube video gear/settings menu and begins navigating it with each left/right 'j'/'l' input.

If I disable uBO, YouTube functions normally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![youtube issue](https://user-images.githubusercontent.com/46386620/146648599-b88c663b-e41d-4703-9479-8acbc0d7c538.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77292
  cosmetic: 39827
  scriptlet: 16369
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61823-8, 2d.18h.33m
    easyprivacy: 26501-17, 1d.18h.55m
    plowe-0: 3698-810, 9d.1h.50m
    ublock-abuse: 81-0, 1d.18h.53m
    ublock-badware: 3509-61, 1d.22h.29m
    ublock-filters: 30024-132, 1d.22h.27m
    ublock-privacy: 188-2, 1d.22h.25m
    ublock-unbreak: 1723-39, 1d.22h.23m
    urlhaus-1: 7061-0, 4h.11m
filterset (user): [array of 94 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 279
  launchFromSelfie: true
popupPanel: 
  blocked: 22
```
</details>

**Comment by uBlock-user** [comment] 2021-12-18 16:35
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2021-12-18 16:35 UTC

**Comment by afroeagle** [comment] 2021-12-18 16:47
@uBlock-user I had read #7636 before posting this issue. My issue is categorically different.

**Comment by uBlock-user** [comment] 2021-12-18 16:49
Doesn't matter, there's one place for all YT issues.

**Comment by gorhill** [comment] 2021-12-18 17:11
I am not able to reproduce such issue with default settings/lists. Is it when logged in or logged out? I see you have a lot of custom filters, did you try just with default settings/lists?
