### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by Theo4322** [uBlockOrigin/uAssets#16353] opened 2023-01-16 07:46 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.facebook.com/`

### Category

ads

### Description

Site includes ads as normal messages 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Untitled](https://user-images.githubusercontent.com/122776701/212624131-3db15b4d-8320-4577-9bda-bf19842cb36a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 102
filterset (summary): 
  network: 84060
  cosmetic: 38878
  scriptlet: 16816
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-1, never
    ublock-filters: 32431-50, 3d
    ublock-badware: 4296-0, 2d.23h.59m
    ublock-privacy: 304-0, 18m
    ublock-abuse: 77-0, 17m
    ublock-unbreak: 1936-2, 2d.23h.58m
    ublock-quick-fixes: 472-0, 16m
    easylist: 62223-626, 20m
    easyprivacy: 30931-1743, 19m
    urlhaus-1: 6868-0, 15m
    plowe-0: 3668-2, 7d.27m
filterset (user): [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1908 ms (selfie)
  maxAssetCacheWait: 310 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by krystian3w** [comment] 2023-01-16 08:48
Duplicate of #3367

**Comment by krystian3w** [comment] 2023-01-16 08:49
Also you don't highlight greek text to detect post as 3-rd party ad.

**Closed** 2023-01-16 09:05 UTC
