### ISSUE TITLE
gmx.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#19785] opened 2023-09-19 11:53 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when opening  ' gmx.com ' it automatically opening '  `https://www.gmx.com/consentpage` ' and a cookie notice appearing. 

### URL(s) where the issue occurs.

gmx.com

### Screenshot(s)

![www gmx](https://github.com/uBlockOrigin/uAssets/assets/145432904/03d37d8b-d6ad-41fb-8b66-da99d6100e6e)

### uBO version

1.52.0

### Browser name and version

Brave Browser

### Settings

using default ublock settings

**Comment by JobcenterTycoon** [comment] 2023-09-19 15:15
Got fixed in the filterlist `uBlock filters – Cookie Notices` which need to be enabled by the user.

**Comment by JobcenterTycoon** [comment] 2023-10-04 10:14
Its fixed in the `EasyList – Cookie Notices` filterlist.

**Comment by JobcenterTycoon** [comment] 2023-10-04 10:18
I can reproduce without a account on `https://support.gmx.com/`. I will take a look

**Comment by JobcenterTycoon** [comment] 2023-10-04 10:20
@Green-Leaves500 please test

```
gmx.com##+js(trusted-set-cookie, euconsent-v2, CPzHq4APzHq4AAcABBENDZCgAIAAAAAAAAYgJnJd9H7fbXFjef5_aft0eY0X1dB76-QjDhTAk-AF3JuQ8LwG12E6METApqgCERIgolZBIQMEHEFUAFCQYIAFAQHsIkSUpAAKICDEEBEQAAIQAAoKEgIAEAAIgERHIhWAmBiQ69LkxcCAGIAQB0BYgogBCIBBAgMBBUAIQBgIAIIIwygAAQBAAIIAAAAAATAAAgBDQAAAIAEAAAHwAAAJBIIIACAAFwAUABUADkAHgAgABlADQANQAeQBDAEQAJgATwAqgBmADeAHoAPwAhIBDAEQAI4ASwAmgBSgC3AGAAMMAZYA54B3AHeAPaAfYB-gEDAIoARgAjQBJQCUgFPALmAYoA1gBtADcAHEAQ6Aj0BIgCdgFDgKPAUiAtABbAC8wGDAMNgZGBkgDMwGfQNYA1kBwQDlAHjgQ5AkVBMsEzAgBEABwAJAAfgBHAE4AOYAg4BHACaAE7ASsAqEBf4DFgGQgP3AmaGAAgDmDQBgCCgFPANYAh0BnwDlBAAEAcwiAKAU8A1gCHQGfAOUFQAwAhgM-AcoKABADmAIKMgBgBDAZ8A5QYABAHMOARgAIAAcABcAEgAPwAjgBQADQAI6AcgBzADoAILAQcBCACIgEcAJoATsApYBrADyAIQASsAqEBaAC1AF0AL_AYIAxYBkMD9gP3AkIBMMCZYEzR0EwABcAFAAVAA5AB8AIAAXAAygBoAGoAPIAhgCIAEwAJ4AVYAuAC6AGIAMwAbwA9AB-gEMARAAlgBNACcAFGAKUAWIAtwBgADDAGiAOeAdwB3gD2gH2AfoBAwCKAEWAIwAR0AkoBKQCngFiALmAXkAxQBtADcAHEAOcAdQBDoCLwEegJEATsAocBR4C2AFugLzAYMAw2BkYGSAMqAZYAzMBnwDWAHFgOUAeOA-sCAIEOQJFATMIADAAEABogHIAcwBBQCOAFLALEAwQB-wEMwJhgTNIQIAAFgAUABcADUAIYATAAqgBcADEAG8APQAjgBSgCxAGAAOeAdwB3gEUAJKASkAp4BcwDFAG0AOcAdQBHoDIwGfAOUAeOBIolAjAAQAAsACgAHAAPgA8ACIAEwAKoAXAAxQCGAIgARwAowBbgDAAHeAPwAp4BcwDFAHUAQ6Ai8BHoCRAFHgLYAXnAyMDJAGfANYAgCBIqCZYJmEgB4AFwAjgDmAHcAQcAjgBSwDtgJWAX-AxYBlgD9wIZgTNKQOAAFwAUABUADkAHwAggBoAGoAPIAhgCIAEwAJ4AUgAqgBiADMAH6AQwBEACjAFKALEAW4AwABogDnAHfAPwA_QCLAEYAI6ASUAlIBcwC8gGKANoAbgA6gCHQEXgI9ASIAnYBQ4C0AFsALzAYbAyMDJAGWAM-gawBrIDggHKAPHAhmBDkCRQEzCgBkAC4AJAAXAAyAB-AEcARwAnIByAHMAO4AfYBBwClgFiALqAa8A7YB5AD_gLoAYIAxaB-wH7gTLAma.cAAAAAAAAZAA)
```

**Comment by JobcenterTycoon** [comment] 2023-10-04 10:35
I can’t register

>  Your IP address suggests you are trying to sign up in a country where GMX registration is no longer possible. Unfortunately, this means we can’t create an account for you. 

@mapx- do you have access?

**Comment by mapx-** [comment] 2023-10-04 10:37
mmhmm, I guess @okiehsch could test it

**Comment by okiehsch** [comment] 2023-10-04 10:43
The suggested filter works on the homepage but I can't register at `gmx.com`, I get the same message as `JobcenterTycoon`.

**Comment by okiehsch** [comment] 2023-10-04 10:45
I think `gmx.com` is for all countries except Germany, Austria, or Switzerland.

**Comment by okiehsch** [comment] 2023-10-04 10:51
> ok then kindly fix that annoyance on gmx.com homepage 😟

The homepage on my end.

<details>
<summary>Screenshot(s)</summary>


![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/4155b961-86a4-4683-ac80-37d3b80b2e9d)

</details>

**Comment by mapx-** [comment] 2023-10-04 11:00
@Green-Leaves500 

test this filter for cookies in inbox

`navigator-bs.gmx.com##.dialog-app__blocker`

**Comment by okiehsch** [comment] 2023-10-04 11:02
Regarding click on login, I can't reproduce the only thing happening is that the login panel slides out.

**Comment by mapx-** [comment] 2023-10-04 11:33
@ryanbr for cookies list

`navigator-bs.gmx.com##.dialog-app__blocker`

**Closed** 2023-10-05 05:47 UTC
Labels: geo specific, account required

**Comment by mapx-** [comment] 2023-10-07 06:33
enable `uBlock filters – Annoyances`
