### ISSUE TITLE
9anime.to: detection

### ISSUE THREAD

**Issue by TheNojusLTU** [uBlockOrigin/uAssets#10553] opened 2021-11-23 20:37 UTC
### URL address of the web page

`https://9anime.to/`

### Category

detection

### Describe the issue

Doesnt allow to use the page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/75728675/143104126-58eba869-9264-4d51-bc91-c50ed1f751db.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 76878
  cosmetic: 39211
  scriptlet: 16158
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30275-114, 1d.2h.50m
    ublock-badware: 3424-1, 1d.2h.48m
    ublock-privacy: 182-0, 1d.2h.46m
    ublock-abuse: 67-0, 1d.2h.44m
    ublock-unbreak: 1701-0, 1d.2h.42m
    easylist: 60964-445, 1d.2h.40m
    easyprivacy: 26279-482, 1d.2h.38m
    urlhaus-1: 7455-0, 1d.6h.1m
    plowe-0: 3689-3, 4d.31m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 7957
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment] 2021-11-23 20:57
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10547

**Closed by uBlock-user** 2021-11-23 20:57 UTC
