### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Gaatjeniksaan1** [uBlockOrigin/uAssets#12704] opened 2022-04-12 14:34 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=63CERXBm_jc`

### Category

detection

### Describe the issue

Áds keep coming 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-04-12 163427](https://user-images.githubusercontent.com/103041015/162986884-50a4215a-7185-42b1-9057-3c5cf7bd2a8b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80612
  cosmetic: 43794
  scriptlet: 16432
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2161-13, 1d.9m
    easylist: 65673-52, 1d.8m
    easyprivacy: 26776-121, 1d.7m
    plowe-0: 3687-808, 6d.8m
    ublock-abuse: 74-0, 1d.6m
    ublock-badware: 4032-90, 1d.5m
    ublock-filters: 30492-140, 1d.4m
    ublock-privacy: 206-2, 1d.3m
    ublock-quick-fixes: 129-0, 1d.2m
    ublock-unbreak: 1744-56, 1d.1m
    urlhaus-1: 7301-0, 1d
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 520 ms (selfie)
  maxAssetCacheWait: 425 ms
popupPanel: 
  blocked: 182
  blockedDetails: 
    youtube.com: 136
    doubleclick.net: 5
    google.com: 19
    google.nl: 1
    googleadservices.com: 1
    googlesyndication.com: 14
    googlevideo.com: 6
```
</details>

**Comment by JobcenterTycoon** [comment] 2022-04-12 14:40
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

try the solutions here: https://github.com/easylist/easylist/wiki/Youtube-Issues

**Closed by JobcenterTycoon** 2022-04-12 14:40 UTC
