### ISSUE TITLE
serialghar.me: detection

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#14689] opened 2022-09-05 15:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://serialghar.me/bade-achhe-lagte-hain-1st-september-2022/`

### Category

detection

### Describe the issue

There is a detection at serialghar.me + advertisment (blank) in sidepanels

After that any post in that website has 3 links - hdstream,vupload,vkspeed

Hdstream has popup,opens new tab & vkspeed has skip ad timer..they all leads to techautomate.in links but functions differently i think

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_2022-09-05-21-19-45-077_com kiwibrowser browser](https://user-images.githubusercontent.com/112684643/188481099-ae9e3b6c-622e-4270-ad6f-679d6d90e162.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 106
filterset (summary): 
  network: 88909
  cosmetic: 35311
  scriptlet: 20874
  html: 751
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4599-7, 9m
    IND-0: 11415-1, 9m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33353-297, 9m
    ublock-badware: 4220-0, 9m
    ublock-privacy: 273-1, 9m
    ublock-abuse: 76-0, 9m
    ublock-unbreak: 1865-0, 9m
    ublock-quick-fixes: 424-0, 9m
    adguard-mobile: 8042-169, 9m
    easylist: 64958-21495, 9m
    easyprivacy: 27487-624, 9m
    urlhaus-1: 7510-0, 9m
    plowe-0: 3671-3, 9m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1188 ms
  maxAssetCacheWait: 462 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    doubleclick.net: 2
    googletagmanager.com: 3
    histats.com: 1
    mahimeta.com: 1
    pubfuture.com: 9
    selectmedia.asia: 2
    themoneytizer.com: 11
```
</details>

**Comment by MasterKia** [comment] 2022-09-05 16:38
`serialghar.me##^script:has-text(mMRequest)` works but these don't using Firefox:
```
serialghar.me##+js(set, mMRequest, noopFunc/falseFunc/undefined/null)
serialghar.me##+js(acis, mMRequest)
```

Anybody have any ideas?

**Comment by MasterKia** [comment] 2022-09-05 16:39
> Hdstream has popup,opens new tab & vkspeed has skip ad timer..they all leads to techautomate.in links but functions differently i think

I can't reproduce timers, they go straight to `techautomate.in`.
Also that popup was opened but closed by uBO on my end.

**Closed** 2022-09-05 16:44 UTC
