### ISSUE TITLE
discoveryplus.com: ads

### ISSUE THREAD

**Issue by nicolosesta** [uBlockOrigin/uAssets#10871] opened 2021-12-11 13:52 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-5-puntata-24-del-10-dicembre-2021`

### Category

ads

### Describe the issue

Since discoveryplus updated it's web site, Ublock can't detect and avoid commercials anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 83454
  cosmetic: 46776
  scriptlet: 16238
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ITA-0: 12573-0, 18h.8m
    easylist: 61410-10, 2d.6h.57m
    easyprivacy: 26477-19, 2d.6h.17m
    plowe-0: 3697-811, 1d.19h.54m
    ublock-abuse: 72-0, 2d.6h.15m
    ublock-badware: 3549-61, 2d.6h.13m
    ublock-filters: 29830-133, 2d.6h.10m
    ublock-privacy: 189-2, 2d.6h.8m
    ublock-unbreak: 1704-39, 2d.6h.6m
    urlhaus-1: 7847-0, 18h.6m
filterset (user): [array of 361 redacted]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 275
  launchFromSelfie: true
popupPanel: 
  blocked: 203
```
</details>

**Comment by gorhill** [comment] 2021-12-11 14:39
Duplicate of #10870.

**Closed by gorhill** 2021-12-11 14:39 UTC
