### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by SebastianTroy** [uBlockOrigin/uAssets#14618] opened 2022-09-01 08:55 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=uMdZ3JDMX8I`

### Category

breakage

### Describe the issue

The page loads, the video thumbnail appears with the play button in the centre. When play is pressed it loads forever. Disabling the plugin and reloading the page leads to ads playing followed by the video, seamlessly, every time.

This is not a duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636 where there is an error message displayed.

I have tried restarting my browser and PC.

I have tried with a completely clean install of uBlock Origin.

This happens on certain videos, I have noticed that after a few days some tabs have miraculously started playing the previously affected video.

This is also an issue with AdBlockPlus, so is perhaps a new youtube feature designed to prevent videos being watched if ads are blocked. These blockers were never installed simultaneously!

Other videos with the same issue:
 - https://www.youtube.com/watch?v=2Sdw9h2HxZA
 - https://www.youtube.com/watch?v=KVTa2xkly1g

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/1526977/187872580-bb50fefc-d7df-4380-89f9-0920cfe4d370.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 80435
  cosmetic: 45243
  scriptlet: 17647
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33207-37, never
    ublock-badware: 4237-1, never
    ublock-privacy: 247-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1871-0, never
    ublock-quick-fixes: 386-34, never
    easylist: 69310-571, never
    easyprivacy: 27312-580, never
    urlhaus-1: 5164-0, never
    plowe-0: 3634-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3963 ms
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    doubleclick.net: 2
    google.co.uk: 1
    google.com: 2
    youtube.com: 19
```
</details>

**Comment by MasterKia** [comment] 2022-09-01 08:57
> This is not a duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636 where there is an error message displayed.

Comment here: https://github.com/uBlockOrigin/uAssets/issues/7636

Also see: https://github.com/easylist/easylist/wiki/youtube-issues

**Comment by MasterKia** [comment] 2022-09-01 08:57
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by MasterKia** 2022-09-01 08:57 UTC

**Comment by SebastianTroy** [comment] 2022-09-01 09:19
@MasterKia Are

> > This is not a duplicate of #7636 where there is an error message displayed.
> 
> Comment here: #7636
> 
> Also see: https://github.com/easylist/easylist/wiki/youtube-issues

Are you telling me to comment on that bug? Or are you telling me it is a duplicate of something already commented on that bug?

**Comment by okiehsch** [comment] 2022-09-01 09:38
The title of https://github.com/uBlockOrigin/uAssets/commit/ba66fc3151cd274057c9c1ef060073b7e2589f17 is literally
"ALL youtube issues".
It means what it says.
