### ISSUE TITLE
criticker.com: nuisance

### ISSUE THREAD

**Issue by Machou** [uBlockOrigin/uAssets#22759] opened 2024-03-04 17:42 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.criticker.com/
```

### Description

at the top of the site, there's a banner advertising the site, which is very disturbing.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Sans titre](https://github.com/uBlockOrigin/uAssets/assets/1043650/09d198fa-2132-414f-a60a-54c14617104c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 259580
 cosmetic: 261230
 scriptlet: 49298
 html: 1995
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://hostfiles.frogeye.fr/firstparty-only-trackers-hosts.txt: 11907-0, 2m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt: 1472-6, 2m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt: 113726-33537, 2m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2589-156, 2m
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 2m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-19, 2m
  adguard-generic: 79039-5472, 1m
  adguard-mobile: 9101-84, 1m
  block-lan: 61-0, 1m
  adguard-social: 22206-865, 1m
  fanboy-thirdparty_social: 68-0, 1m
  [15 lists not shown]: [too many]
 default:
  user-filters: 416-26, never
  ublock-filters: 37376-458, 1h.33m Δ
  ublock-badware: 7750-14, 1h.33m Δ
  ublock-privacy: 739-112, 1h.33m Δ
  ublock-unbreak: 2293-1, 1h.33m Δ
  easylist: 82120-623, 1h.33m Δ
  easyprivacy: 50327-1008, 1h.33m Δ
  urlhaus-1: 8255-0, 1m
  ublock-quick-fixes: 140-1, 1h.33m Δ
filterset (user): [array of 419 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 583 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1061 ms (selfie)
 maxAssetCacheWait: 477 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 no-remote-fonts: true
 network:
  huggingface.co: 2
  cloudflare.com: 2
  fonts.googleapis.com: 4
  googletagmanager.com: 1
  hf.space: 3
  segment.com: 1
  stripe.com: 1
```
</details>

**Comment by gorhill** [comment] 2024-03-04 18:40
You can close it, close button on the right side of the banner.

I don't see it on my side, does it show only with signed in? Did you try to see if the issue is present when using only default settings/lists? It could be that the site detects you are using a blocker because one of the many lists you enabled is interfering negatively.

**Comment by gorhill** [comment] 2024-03-04 18:48
Alright, closing as invalid, you copied/pasted troubleshooting information from [another report](https://github.com/uBlockOrigin/uAssets/issues/22756) instead of providing accurate troubleshooting information.

**Closed by gorhill** 2024-03-04 18:48 UTC
Labels: invalid

**Comment by Machou** [comment] 2024-03-05 21:01
> Alright, closing as invalid, you copied/pasted troubleshooting information from [another report](https://github.com/uBlockOrigin/uAssets/issues/22756) instead of providing accurate troubleshooting information.

Oh I'm sorry, This is indeed a mistake on my part, I didn't proofread myself when pasting the data and the others have apparently been copied incorrectly. I'll correct it when I get back to my PC.

**Comment by Machou** [comment] 2024-03-06 07:27
> You can close it, close button on the right side of the banner.
> 
> I don't see it on my side, does it show only when signed in? Did you try to see if the issue is present when using only default settings/lists? It could be that the site detects you are using a blocker because one of the many lists you enabled is interfering negatively.

I've corrected the problem with the report, following the wrong copy and paste.

Concerning the nuisance, yes it is only when we are connected on the site.

**Comment by ItsProfessional** [comment] 2024-03-06 07:44
> ```yaml
>listset (total-discarded, last-updated):
> added:
>  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76980-76980, now
>  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 7m
>  https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt: 42535-1425, 7m
>  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97237-97216, now
>  https://www.i-dont-care-about-cookies.eu/abp/: 25840-22, now
>  adguard-generic: 79068-5653, now
>  adguard-mobile: 9109-141, now
>  adguard-spyware-url: 1470-106, now
>  adguard-spyware: 113728-33889, now
>  block-lan: 61-0, now
>  curben-phishing: 105383-43, 7m
>  adguard-social: 22200-865, now
>  [16 lists not shown]: [too many]
>```
>```yaml
>filterset (user): [array of 19 redacted]
>```

You are using a heavily customized configuration of uBO. We can't help such users. More lists means more breakages and more exceptions. Reset uBO to defaults, and do not change anything.

**Comment by Machou** [comment] 2024-03-06 07:59
> > ```yaml
> > listset (total-discarded, last-updated):
> > added:
> >  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76980-76980, now
> >  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 7m
> >  https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt: 42535-1425, 7m
> >  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97237-97216, now
> >  https://www.i-dont-care-about-cookies.eu/abp/: 25840-22, now
> >  adguard-generic: 79068-5653, now
> >  adguard-mobile: 9109-141, now
> >  adguard-spyware-url: 1470-106, now
> >  adguard-spyware: 113728-33889, now
> >  block-lan: 61-0, now
> >  curben-phishing: 105383-43, 7m
> >  adguard-social: 22200-865, now
> >  [16 lists not shown]: [too many]
> > ```
> 
> > ```yaml
> > filterset (user): [array of 19 redacted]
> > ```
> 
> You are using a heavily customized configuration of uBO. We can't help such users. More lists means more breakages and more exceptions. Reset uBO to defaults, and do not change anything.

Ok, i have use a Firefox 123.0.1 without Addon and uBO without Filters :)

**Comment by ItsProfessional** [comment] 2024-03-06 08:41
Actually I've just realized that what you've highlighted in your screenshot isn't actually an ad. It's self promotion for a subscription plan. We don't hide self promotion. as per the easylist filter policy (which we follow)
