### ISSUE TITLE
https://github.com/easylist/easylist/issues/19752

### ISSUE THREAD

**Issue by rthfhgyhy567** [uBlockOrigin/uAssets#24841] opened 2024-08-09 03:27 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.splcenter.org/fighting-hate/extremist-files/individual/david-duke
```

### Description

Newsletter pop after a couple seconds.

### Other extensions used

Bitwarden, dark reader, better history, tamper monkey

### Screenshot(s)

<img width="893" alt="Untitled" src="https://github.com/user-attachments/assets/a1163e41-f796-4a15-a84a-e37ee55f3ff5">

### Configuration

uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 165446
 cosmetic: 208265
 scriptlet: 34638
 html: 2158
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30833-46, 8m
  ublock-cookies-adguard: 1304-19, 4d.21h.18m
  fanboy-cookiemonster: 51454-3940, 4d.21h.18m
  ublock-cookies-easylist: 1304-1304, 4d.21h.18m
  adguard-social: 23259-52, 9m
  fanboy-social: 16096-754, 4d.21h.17m
  fanboy-thirdparty_social: 68-19, 7d.21h.38m
  adguard-popup-overlays: 27748-1041, 8m
  adguard-mobile-app-banners: 5396-26, 9m
  adguard-other-annoyances: 14860-419, 9m
  adguard-widgets: 2633-16, 9m
  easylist-annoyances: 4667-303, 4d.21h.18m
  [4 lists not shown]: [too many]
 default:
  user-filters: 344-61, never
  ublock-filters: 39760-118, 3h.9m Δ
  ublock-badware: 10406-6, 3h.9m Δ
  ublock-privacy: 1039-4, 3h.9m Δ
  ublock-unbreak: 2525-1, 3h.9m Δ
  ublock-quick-fixes: 135-2, 3h.9m Δ
  easylist: 87945-172, 3h.9m Δ
  easyprivacy: 53081-62, 3h.9m Δ
  urlhaus-1: 27255-0, 3h.9m
  plowe-0: 3548-990, 12d.21h.22m
filterset (user): [array of 345 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings:
 cloudStorageEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1186 ms
 maxAssetCacheWait: 644 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  addthis.com: 2
  adroll.com: 1
  d21y75miwcfqoq.cloudfront.net: 2
  d31qbv1cthcecs.cloudfront.net: 1
  googletagmanager.com: 2
  newrelic.com: 2
 extended:
  ##.addthis_toolbox
  ##.addthis_default_style
  ##.addthis_button_facebook
  ##.addthis_button_twitter

**Comment by rthfhgyhy567** [comment] 2024-08-09 03:55
Also, moderator abuse from the /r/ublockorigin group.  I advise anyone reading this issue to take extra due diligence in handling my request, as it will be part of a permanent, public, record.

https://imgur.com/a/sk8jrk0

**Comment by stephenhawk8054** [comment] 2024-08-09 04:06
The [EL issue thread](https://github.com/easylist/easylist/issues/19752#issuecomment-2272259975) said it's a duplicate of this thread: https://github.com/easylist/easylist/issues/19752

Continue commenting in https://github.com/easylist/easylist/issues/19752

**Closed by stephenhawk8054** 2024-08-09 04:06 UTC

**Comment by rthfhgyhy567** [comment] 2024-08-09 04:12
![image](https://github.com/user-attachments/assets/37926827-edb1-4cd9-9280-77edd8a0fb32)

It's only a nuisance because you are taking sides and can't handle being called out for it.  I will continue to expose how your adblocker is meddling with our elections by intentionally allowing left winged extremist sites like this to continue to receive donation money from pop ups that in your own policies are considered a _nuisance_.  Ironic, huh?

**Comment by rthfhgyhy567** [comment] 2024-08-09 04:25
Why exactly can't I raise this issue on the uBlock github too?  uBlock and Easy list both manage filter lists for "annoyances", and since this is a newsletter pop up, it clearly meets that criteria.  From the overwhelming response I have got from Easylist, you, and the /r/ublockorigin reddit moderators, it seems that there is a strong bias to allow this radical left winged organization to continue to display newsletter pop ups which are used to promulgate their agenda. [ I have been banned from the Official Reddit group for simply cross posting this issue.](https://imgur.com/a/easy-list-ublock-origin-is-adblocker-software-that-manipulates-experience-its-users-by-intentionally-not-blocking-newsletter-donation-pop-ups-left-winged-sites-sk8jrk0)  Is that not political manipulation from multiple members of the uBlock/easylist team?

**Comment by stephenhawk8054** [comment] 2024-08-09 04:29
> Continue commenting in https://github.com/easylist/easylist/issues/19653

Your issue thread there is not closed yet.

**Comment by stephenhawk8054** [comment] 2024-08-09 05:51
> Ublock tells me that my post is a duplicate of another, even though I thought Easylist was "unrelated" to ublock.

Read: https://github.com/uBlockOrigin/uAssets#uassets

> The rationale for including a specific filter in uBO's filter lists is the same as the [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html) and also takes into account whether a filter requires uBO's extended filter syntax.
> 
> It is preferred to fix filter issues in EasyList. Any filters included in uBO's filter lists must use the [extended syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax).
