### ISSUE TITLE
animeshouse.net: nuisance

### ISSUE THREAD

**Issue by Serpentario** [uBlockOrigin/uAssets#14941] opened 2022-09-20 01:59 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animeshouse.net/episodio/yowai-5000-nen-no-soushoku-dragon-iwarenaki-jaryuu-nintei-s1-episodio-7-legendado-hd/`

### Category

nuisance

### Describe the issue

As much as you try to manually block the link above the player, it returns when updating.

Blocking the suspicious link prevents the player from loading.

I think that's it...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/81823298/191148070-383ba360-4ffa-45a3-ab94-f6f0e8781dd4.png

</details>

https://user-images.githubusercontent.com/81823298/191149574-1f8c6811-9e3c-4e08-b287-a8cf17f62ee7.png

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 84819
  cosmetic: 42897
  scriptlet: 18039
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 20-1, never
    ublock-filters: 33505-72, 7h
    ublock-badware: 4204-0, 7h.6m
    ublock-privacy: 273-0, 9d.8h.36m
    ublock-abuse: 76-0, 9d.8h.35m
    ublock-unbreak: 1869-0, 7h.5m
    ublock-quick-fixes: 222-0, 6h.59m
    easylist: 63265-654, 7h.3m
    easyprivacy: 30609-1717, 7h.2m
    urlhaus-1: 6762-0, 6h.58m
    plowe-0: 3674-3, 8d.31m
    spa-1: 4646-14, 7h.1m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 622 ms (selfie)
  maxAssetCacheWait: 343 ms
popupPanel: 
  blocked: 6
  no-popups: true
  blockedDetails: 
    animeshouse.net: 1
    disqus.com: 3
    googletagmanager.com: 1
    outoctillerytor.com: 1
```
</details>

**Comment by stephenhawk8054** [comment] 2022-09-20 02:14
Can you check if adding this works?

```adb
animeshouse.net##+js(ra, href, a[rel="nofollow"][href*="brasilro.com"])
```

**Comment by ariehfabbro** [comment] 2023-09-05 01:28
I have a similar problem, but my problem is the video player doesn't work when the adblocks is running. See this screen:
![image](https://github.com/uBlockOrigin/uAssets/assets/8531737/4c4714e2-0145-4712-b413-8e29d4ca3111)
The link I used was this one https://animeshouse.net/episodio/okashi-na-tensei-s1-episodio-11-legendado-hd/

**Comment by FanOfRootBeer** [comment] 2023-09-05 04:31
@ariehfabbro on my side, it looks like it's not because of uBlock Origin

**Comment by ghajini** [comment] 2023-09-05 04:36
500 internal server error

**Comment by mapx-** [comment] 2023-09-05 05:38
@ariehfabbro are you able to play the show disabling uBO ?

**Comment by ariehfabbro** [comment] 2023-09-05 08:25
please, close the issue, the problem is gone, I really don't know what happened, but the video is working while ublock is running. Now I can't replicate the issue and I was able to play the video disabling uBO.

**Closed** 2023-09-05 08:29 UTC
Labels: geo specific
