### ISSUE TITLE
interpals.net

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7875] opened 2020-09-05 14:22 UTC
### URL(s) where the issue occurs

homepage:
`https://interpals.net/`

### Describe the issue

Google contributor anti-adblock after many refresh, found by @kolor33

### Screenshot(s)

see https://user-images.githubusercontent.com/35370833/92307022-bf7b9600-ef93-11ea-90c2-dc8b709c70c4.png

### Versions

- Browser/version: 1.29.2
- uBlock Origin version: 1.29.2

### Settings

Stock without Annoyance.

### Notes

>⚠️ You are seeing this message because ad or script blocking software is interfering with this page.
> Disable any ad or script blocking software, then reload this page.

**Comment by uBlock-user** [comment] 2020-09-05 14:22
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7874

**Closed by uBlock-user** 2020-09-05 14:22 UTC
