### ISSUE TITLE
techradar.com anti adb 

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#3664] opened 2018-10-07 12:19 UTC
Anti-Adblock Script

Example:
`https://www.techradar.com/news/the-best-free-media-player`

**Comment by krystian3w** [comment] 2018-10-07 13:58
```
techradar.com##+js(abort-on-property-read.js, _sp_._networkListenerData)
```
Made by @jspenguin2017.

**Comment by krystian3w** [comment] 2018-10-07 16:39
Maybe moved to main list uBlock Origin.

**Comment by jspenguin2017** [comment] 2018-10-07 16:48
It's just an annoyance, once you close it, it doesn't come back.

**Comment by krystian3w** [comment] 2018-10-07 16:54
You can see the author of the issue is not covered by what is an annoying element and a strong anti-blocking (eg something limiting).

**Comment by jspenguin2017** [comment] 2018-10-07 17:04
It's a soft anti-adblock for me, once I close it, it doesn't come back: 
![image](https://user-images.githubusercontent.com/7283682/46584462-afae4c80-ca20-11e8-88e2-c216a0d4350e.png)

**Comment by mapx-** [comment] 2018-10-07 17:16
@erosman  you have to enable ublock annoyances list

**Closed by mapx-** 2018-10-07 17:16 UTC

**Comment by krystian3w** [comment] 2018-10-07 18:00
[uBO annoyance - Subscribe][uBO annoyance - Subscribe]

[uBO annoyance - Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt&title=annoyances%20uBO

**Comment by erosman** [comment] 2018-10-07 18:06
@krystian3w Is the subscribe method via above link or is there a setting on the addon?

**Comment by krystian3w** [comment] 2018-10-07 18:06
Yes, should activate correct list in uBO.

**Comment by mapx-** [comment] 2018-10-07 18:07
open the dashboard and enable that list.

**Comment by erosman** [comment] 2018-10-07 18:11
​​​​​​​​Which one?

Annoyances (0/5)

Adguard’s Annoyance List​
Fanboy’s Annoyance List​
​​​Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
​​​​​​​​Fanboy’s Social Blocking List​

**Comment by okiehsch** [comment] 2018-10-07 18:13
![image](https://user-images.githubusercontent.com/16838044/46585165-7223e080-ca6d-11e8-8f91-4fe54ab68159.png)

**Comment by erosman** [comment] 2018-10-07 18:15
Thank you @okiehsch

**Comment by okiehsch** [comment] 2018-10-07 18:16
> Every time I go to
techradar.com/news/the-best-free-media-player
It forwards to
techradar.com/cc.html

I can't reproduce, if I disable `uBO-annoyances`
![image](https://user-images.githubusercontent.com/16838044/46585184-bfa04d80-ca6d-11e8-9466-e39ce726d75d.png)

**Comment by erosman** [comment] 2018-10-07 18:17
My setting had 5/7

These were off

uBlock filters – Annoyances
uBlock filters – Experimental

**Comment by okiehsch** [comment] 2018-10-07 18:19
That is the default setup,
