### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by Totherphoenix** [uBlockOrigin/uAssets#10811] opened 2021-12-07 21:32 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.facebook.com/`

### Category

ads

### Describe the issue

sponsored post from airbnb appeared
adblock ultimate blocks those posts

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/47739689/145109292-474eb8ff-b6ca-455e-a647-960d94b4b7f2.PNG

</details
)
>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78384
  cosmetic: 39370
  scriptlet: 16222
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61183-6, 1d.22h.1m
    easyprivacy: 26436-17, 1d.21h.59m
    plowe-0: 3696-811, 1d.21h.57m
    ublock-abuse: 72-0, 1d.21h.53m
    ublock-badware: 3509-59, 1d.21h.49m
    ublock-filters: 29791-123, 1d.21h.47m
    ublock-privacy: 191-1, 1d.21h.45m
    ublock-unbreak: 1703-38, 1d.21h.43m
    urlhaus-1: 8593-0, 19h.49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 268
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by uBlock-user** [comment] 2021-12-07 21:37
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/3367

**Closed by uBlock-user** 2021-12-07 21:37 UTC
