### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by itscharbel** [uBlockOrigin/uAssets#11233] opened 2022-01-08 19:49 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

http://streamingcommunity.fun/

### Describe the issue

Adblock works on the website but it gets detected when you open a movie/series

### Screenshot(s)

![image](https://user-images.githubusercontent.com/53374274/148657762-e61dcf3b-0b16-490f-b3f9-107c90b9ff87.png)
![image](https://user-images.githubusercontent.com/53374274/148657785-48a25311-65c6-4f99-9af1-f599c3725a79.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 78794
  cosmetic: 40070
  scriptlet: 16253
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, never
  default: 
    easylist: 62547-9, never
    easyprivacy: 26592-17, never
    plowe-0: 3681-816, never
    ublock-abuse: 72-0, never
    ublock-badware: 3648-65, never
    ublock-filters: 29794-133, never
    ublock-privacy: 185-3, never
    ublock-unbreak: 1678-39, never
    urlhaus-1: 8145-0, never
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 1143 ms (selfie)
```
</details>

**Comment by gorhill** [comment] 2022-01-08 19:58
> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/11225>.

**Closed by gorhill** 2022-01-08 19:58 UTC
