### ISSUE TITLE
Openload Ads and Popups

### ISSUE THREAD

**Issue by xmaestro21** [uBlockOrigin/uAssets#106] opened 2016-08-18 22:17 UTC
Hello, first of all i hope this is the right place for this now! (I'm Sorry for posting this in the first place first,)
So there is an issue with ublock origin and the Openload video player.
Whenever you click on an openload video, it opens at least 2 ads as popup tabs.
Openload seems to be packed with ads, i tried everything including working through the logger but stil couldnt solve the problem. In the end there was always 1 ad / popup left, that doesnt want to be blocked. This happens on every openload video for me, but i added an example link:

https://openload.co/embed/Y8WzfvdsVrU

### Steps for anyone to reproduce the issue

Simply wanting to play an openload video will reproduce this issue.
- Open the link with the openload video.
- press play -> popup will appear, but wont start the video
- press play again -> another popup will appear (sometimes the popups close themselves immdediately, but not always, and stil annoying.)
- you have to press play a couple times until it starts, sometimes the browser windows size changes by itself while doing this.
- thats it

### Settings
- default
- i am an experiences user is switched on

- Browser/version: Chrome 52.0.2743.116 m
- uBlock Origin version: 1.8.4

### Filter lists:

Default filter lists + adblock warning removal list, fanboys annoyance list, easylist germany
no costume filters

in the ublock pop ui, i have: 
3rd party scripts globally blocked
3rd party frames globally blocked
openload nooped globally
cloudflare nooped globally (otherwise openload wont work on other sites)
anything else is default.

i already tried blocking every possible thing that could be an ad or popup
i watched what happens in the logger when i try to play an openload video, and blocked everything ad related.
nothing helped, never got rid of every ad / popup
at last i deleted every single one of my own rules because everything was messed up

### Logger Screenshot

i will attach a screenshot of how the logger looks, beginning from when i load the site with the video, until the video actually starts (after all the ads and clicks)

![openload ads](https://cloud.githubusercontent.com/assets/21089903/17785655/f4eef444-6581-11e6-8929-5e359bf70c93.png)

this is the logger without any own rules to block an ad on openload

i hope you can help, thanks :)

Edit: the no pop-ups switch is not an option because i really need to open new tabs frequently on some sites, and i cant switch it on and off a thousand times

**Comment by IDKwhattoputhere** [comment] 2016-08-19 00:55
The no-popups switch only applies to the current site. They're called **per-site** switches after all.

Have you tried creating a simple filter that blocks all popups on the site? Like `*$popup,domain=openload.co`?

**Comment by gwarser** [comment] 2016-08-19 01:00
Try `openload.co##script:inject(noeval.js)`

**Comment by gorhill** [comment] 2016-08-19 01:14
Can't reproduce: the site does try to open popups, but they are filtered out by uBO -- through EasyList filters from what I have observed.

Use the logger, select _All_ in the drop down list, and reproduce the problem. This will show you what popup-related URL where not filtered by the filter lists. Report your findings here.

**Comment by xmaestro21** [comment] 2016-08-19 12:45
thanks for the quick responses!
@IDKwhattoputhere i know the pop up switch is only per site, i tried it and cant open anything in a new tab on that site than, and yes its the same site where i watch openload videos, so thats the issue.
unfortunately the filter didnt do much

@gwarser thanks but also this filter didnt do much

@gorhill to be clear, do you mean nothing pops up at all, or it pops up and closes right away?
because thats the case for me now, the pop ups dont stay open, they close themselves right away. i mean that can't be it, right?!

i did what you said, here is the logger with everything that has "pop" in it
![openload popups without filter](https://cloud.githubusercontent.com/assets/21089903/17809646/5e4d3306-6618-11e6-831a-bc400a6cedf8.png)

this is how it looks like without any costum filters / rules, just the ones i listed. 
My uBO panel looks like this:
![ublock panel](https://cloud.githubusercontent.com/assets/21089903/17809704/c726cda6-6618-11e6-95d2-6e8061adf3b5.png)


i tried again with the 2 suggested filters:
openload.co##script:inject(noeval.js)
*$popup,domain=openload.co

and did the same thing. the logger showed an additional block, but the behaviour and popups were the same:
![obenload with filters](https://cloud.githubusercontent.com/assets/21089903/17809901/f83aa1f0-6619-11e6-8a91-74eb5592d872.png)

its almost always the same, in some rare cases there is only one ad, refreshing the same page and trying again has different results, it seems to load random ads or something.
the first click opens the data:text/**** popup
the second click makes my screen go white for a split second, and forces the chrome window out of "maximized" .. really strange

**Comment by IDKwhattoputhere** [comment] 2016-08-19 22:37
I can't quite reproduce. I get popups but they're closed in like .1 seconds (even without any custom filters) and that's it. Your first logger screenshot doesn't show a script from 'popads.net', almost like you're getting a different site.
![](https://cloud.githubusercontent.com/assets/16030872/17826146/3af12ba0-666e-11e6-8c2f-aefb2efa1653.png)
You could try these filters just to try something:
`@@/googlead.js$script,domain=openload.co`
`@@/popunder2.js$script,domain=openload.co`

**Comment by gorhill** [comment] 2016-08-19 23:17
> do you mean nothing pops up at all, or it pops up and closes right away?
because thats the case for me now, the pop ups dont stay open, they close themselves right away. i mean that can't be it, right?!

If this is the issue you are reporting, then yes, it is right. That's the way thigns work: a popup can be opened with `about:blank`, then be redirected by the opener to another site, etc. Window/tab opening is not the same as network request blocking.

By design.

**Closed by gorhill** 2016-08-19 23:17 UTC

**Comment by kasper93** [comment] 2016-08-20 10:44
@gorhill: This is not quite correct. Openload have really obfuscated js code, but this is to guard link to the video. Advertising code is not obfuscated. noeval.js is not proper solution for this site.

Take a look at their inline scripts. I still get the popup. It is closed by uBlock, but there is easy fix to make it go away completely. 

All you need to do is inject `window.turnoff = true;` They check the value before executing the ads code. Not sure how long it will be there tho. Anyway we can always block inline scripts one by one if needed. But for now `turnoff` disables all popunder code.

**Comment by gorhill** [comment] 2016-08-20 12:03
The video plays fine without that eval code. I agreed to use noeval.js because that code serves no visible purpose, so I will assume it's not for a good purpose and not spend precious time on deobfuscating it.

Aside this, I do not get popups which are not handled by uBO, again, if all work as expected, no point spending precioustime on this specific site.

**Comment by kasper93** [comment] 2016-08-20 12:33
Fair enough, I personally prefer blocking js code which invokes popups and do other crap rather than block the popups itself. I don't like this popup window blinking in front of me. On firefox blank window is shown for a sec but you probably know that :)

Luckily with uBlock and Greasemonkey I can fully control what I want :)

Cheers

**Comment by xmaestro21** [comment] 2016-08-20 12:43
@gorhill when you say by design, do you mean uBO design or adblocking design generally?
because just to TRY i used the addon adguard, and there it didnt even open any popup.

i know its good that uBO closes the opened popups so fast, but i wanted to ask for a solution to prevent those popups from opening AT ALL.

btw openload is not the only site that does this, i dont have an example now but can say it happened elsewhere too.

@IDKwhattoputhere thanks but again the filters didnt change anything.

@kasper93 im glad you understand my point, and happy to see you solved it. i wouldnt like to avoid using more addons though (greasemonkey)

any idea how i can get this done with ublock?
i couldve sticked with adguard (dont know if this is forbidden to mention or something, sorry if yes)
but i prefer ublock in any way so i returned to it, its just this openload issue..

anyway, would appreciate any help if gorhill doesnt have time to look into this

**Comment by kasper93** [comment] 2016-08-20 13:10
@xmaestro21: Injecting JS using uBlock need changes in the extensions itself because it need to be one of existing snippets. But since the `turnoff` value is checked only in inline scripts that are used to setup ads you can use this filter which will prevent those script from executing. IIRC this works only on Firefox. 

`openload.co##script:contains(window.turnoff)`

**Comment by xmaestro21** [comment] 2016-08-20 13:21
@kasper93 you seem to remember correctly, i use chrome and it didnt work.

i would've given up and accepted that it is how it is, but after i saw that adguard can do this, i kinda think it should be possible with ublock too right? (in chrome)

i am stil spending a lot of time with trying to solve this and researching, i will end up learning something about programming because of this lol. if i come up with something i will update it here

**Comment by gorhill** [comment] 2016-08-21 11:04
> but after i saw that adguard can do this, i kinda think it should be possible with ublock too right? (in chrome)

A popup opened and didn't close with AdGuard for you link in OP (just clear the cookie and try).

**Comment by gorhill** [comment] 2016-08-21 11:19
The site apparently was modified such that I can't play the movie anymore no matter how often I click. Will fix.
