### ISSUE TITLE
client.falixnodes.net: detection

### ISSUE THREAD

**Issue by Xpro34** [uBlockOrigin/uAssets#19180] opened 2023-07-26 18:52 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://client.falixnodes.net/disableadblock.php`

### Category

detection

### Description

an ad blocker is detected and shows a banner about its disabling, preventing you from using the service completely.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://ru.paste.pics/OVY7R
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.10h.38m
Chromium: 115
filterset (summary):
 network: 114895
 cosmetic: 60490
 scriptlet: 19405
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  RUS-0: 39608-9, 9m
  easylist: 69089-33, now
  easyprivacy: 33349-152, now
  plowe-0: 3720-1076, now
  ublock-badware: 7594-142, now
  ublock-filters: 34145-248, now
  ublock-privacy: 441-7, now
  ublock-quick-fixes: 283-86, now
  ublock-unbreak: 2098-34, now
  urlhaus-1: 6406-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 405 ms (selfie)
 maxAssetCacheWait: 185 ms
popupPanel:
 blocked: 0
 extended:
  ##.mb-4.flex-center.d-flex
```
</details>

**Comment by JobcenterTycoon** [comment] 2023-07-26 19:29
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18260

**Closed by JobcenterTycoon** 2023-07-26 19:29 UTC

**Comment by Xpro34** [comment] 2023-07-26 20:07
how to finally fix this problem
