### ISSUE TITLE
imgfrost.net anti-adb/malicious redirects

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#9123] opened 2021-05-18 07:44 UTC
### URL(s) where the issue occurs
`http://imgfrost.net/aucw5bhn`

### Describe the issue
`http://imgfrost.net/aucw5bhn` redirects to `http://imgkor.xyz/aucw5bhn` which shows a banner "Continue to image"
after timer of 5 secs. Upon clicking it redirects to malicious links.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/80951522/118611936-f10f5700-b7da-11eb-876d-436847fbb175.png)

### Versions
- Browser/version: **90.0.xx**
- uBlock Origin version: **v1.35.2**

### Settings
All default settings.

### Notes

**Comment by okiehsch** [comment] 2021-05-18 07:50
Do you think it is wise to post clickable links that lead to maliciuos redirects?

**Comment by blazesprings** [comment] 2021-05-18 07:52
Sorry but i didn't post knowingly, I just copy pasted from notepad.
I will remember it next time. Thanks.

**Comment by JobcenterTycoon** [comment] 2021-05-19 13:04
It still open popups when i click on the button

**Comment by blazesprings** [comment] 2021-05-19 17:10
I purged the cache and updated all filters, still issue persists. Please suggest any workaround?

**Comment by Yuki2718** [comment] 2021-05-19 17:22
@blazesprings Fixed

**Comment by JobcenterTycoon** [comment] 2021-05-19 19:30
I get popups on `http://imgopp.xyz/aucw5bhn`

**Comment by blazesprings** [comment] 2021-05-20 03:20
@Yuki2718 No bro, after your post, I purged cache and updated filters once again, but doesn't work.
Again the timer is there and popups too.

**Comment by Yuki2718** [comment] 2021-05-20 10:47
> I purged cache and updated filters once again, but doesn't work.
> Again the timer is there and popups too.

Because now they change the domain nearly hourly basis.

**Comment by blazesprings** [comment] 2021-05-20 17:01
@mapx @Yuki2718 When u mention a update, which lines should be copied? Those highlighted in green?
Please clarify..

**Comment by Yuki2718** [comment] 2021-05-20 17:06
@blazesprings I don't get what you're talking.

**Comment by blazesprings** [comment] 2021-05-20 17:09
> @blazesprings I don't get what you're talking.
I mean when u mention an update in code (see mapx's post above). What I am asking is whether the code highlighted in green
needs to copied to custom filters in UBOrigin to update the filters at my end?

**Comment by blazesprings** [comment] 2021-05-20 17:15
I always do that bro @Yuki2718 but the issue still persists.

**Comment by Yuki2718** [comment] 2021-05-21 12:04
It's proven they're watching us. Just after I added `/gf4g9h0s?key=` they changed the key to `/sdgds54353?key=` and it has been stable until yesterday before I added the filter.

**Comment by avotoko** [comment] 2021-05-21 13:51
works for me.
```
! disable popup script
||imgopp.xyz/rest/rest.js$script,1p
! disable click handling
imgopp.xyz###pbe
imgopp.xyz##+js(set, hold_click, false)
! speed up countdown
imgopp.xyz##+js(nano-stb, .url-link)
imgopp.xyz##+js(nano-sib, .url-link)
imgopp.xyz##+js(nano-stb, , 6000, 0.1)

```

**Comment by blazesprings** [comment] 2021-05-21 15:39
I checked, the timer becomes 0 fast and the redirects too disappeared but 2 things I observed : 
You have to click the continue to image button.
When the image opens you see nasty ads on the right side of the page.
I wanted just the image to open. But thanks for the above code, at least we found some breakthrough.

**Comment by avotoko** [comment] 2021-05-22 03:49
> I wanted just the image to open.

works for me.
```
/c-hive.min.js$script,1p,domain=imageking.xyz|imgair.net|imgao.xyz|imgflyer.xyz|imgbigo.xyz|imgbird.xyz|imgblaze.net|imgbrd.xyz|imgex.xyz|imgez.xyz|imgfish.xyz|imgfl.xyz|imgfrost.net|imgfsh.xyz|imggoing.xyz|imghb.xyz|imgkaida.xyz|imgkes.xyz|imgkis.xyz|imgko.xyz|imgkoi.xyz|imgkor.xyz|imglin.xyz|imglion.xyz|imgopp.xyz|imgsup.xyz|imgsupa.xyz|imgtiger.xyz|imgtigr.xyz|imgviv.xyz|imgvivo.xyz|imgweng.xyz|imgwew.xyz|imgxen.xyz|imgxn.xyz|imgxx.xyz|imgzer.net|venpix.xyz|vestimage.site
```

**Comment by blazesprings** [comment] 2021-05-22 07:50
My dear @mapx- and @Yuki2718 : I have found a workaround to deal with the creepy and pesky developers who build
such malicious image hosting websites. As they keep track of the code changes done here, I request you NOT TO POST
the link to updated code as you have posted above. These creepy fellows read that code and update immediately and 
the cat and mouse game goes on. Please update code without displaying what you have updated. That will save your as
well as end user's time.
Thanks :)

**Comment by Yuki2718** [comment] 2021-05-22 08:31
@blazesprings Impossible, all the codes are open source. Even if we hide, it's trivial to find the code.

**Comment by uBlock-user** [comment] 2021-05-22 08:42
Expect any filter to last no more than 24 hours.

**Comment by JobcenterTycoon** [comment] 2021-05-23 13:44
the frame filter is too generic it breaks the site `catlive.xyz/ipl/` (scorecard dissapear) and `https://updatesmovie.xyz/movies/army-of-the-dead-2021-hindi-dubbed/` (video player dissapear)

and i just checked 15 of 500 domains

**Comment by avotoko** [comment] 2021-05-23 22:33
image does not display.
works for me.
```
@@||kekolangti.com/shrinker/js/ionqs11.js$script,1p
```

**Comment by blazesprings** [comment] 2021-05-24 07:32
@avotoko Yes the counter now stops and page doesn't redirect to image even when u click continue.

**Comment by electronicwhisper** [comment] 2021-05-25 20:33
@mapx- @Yuki2718 
Could I request that we remove the rule on [line 22289 of filters.txt](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L22289)?

```
xyz##+js(aeld, , _0x)
```

As I understand it, this is adding the `addEventListener-defuser` functionality to every page in the xyz TLD, which seems heavy-handed.

It's breaking my site https://cuttle.xyz/ which is using the [mithril.js](https://mithril.js.org/) framework.

**Comment by mapx-** [comment] 2021-05-25 20:50
it's not that specific filter, the framework is broken even using aell (which is only logging addEventListener requests)

this 1 breaks the site too (even not matching addEventListener )

@gorhill

**Comment by electronicwhisper** [comment] 2021-05-25 22:01
Thanks @mapx- 

I'm going to try to see if the mithril.js folks have any ideas. It seems like the problem is `aeld` and `aell` are trying to convert the second argument of `addEventListener` (ostensibly the listener function) to a string and that's causing problems because mithril is passing something weird in as the second argument. Does that align with your understanding?

In the meantime, is it possible to remove the `xyz##+js(aeld, , _0x)` rule since it's applying a javascript injection to every site in the xyz TLD?

**Comment by mapx-** [comment] 2021-05-25 22:04
That filter was already commented (see my update / commit above)

**Comment by electronicwhisper** [comment] 2021-05-25 22:36
FWIW I tracked down the issue to Mithril using a synthetic `EventListener` object (that is, an object that has a `handleEvent` property).
https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L882

They have this object inherit from `Object.create(null)` (I'm not sure why) which is exactly the `x` that would break `String(x)` or `x.toString()`.

I filed [an issue](https://github.com/MithrilJS/mithril.js/issues/2687) with Mithril. But it would also be good for uBlockOrigin to be resilient to an event listener that can't be turned into a string, or just to consider that case.

**Comment by blazesprings** [comment] 2021-05-26 06:22
But the image doesn't appear after clicking continue. Timer is still there.

**Comment by gorhill** [comment] 2021-05-26 11:24
> it would also be good for uBlockOrigin to be resilient to an event listener that can't be turned into a string

Thanks for tracking this down, I've changed the code to catch the error. The fix will be in next dev build.

**Comment by Xerios** [comment] 2021-05-27 19:40
Thee following lines block any javascript file that's like `file/file.js` or `main/main.js` breaking many websites, including two of my projects. This caused a lot of confusion and complaints from my users.

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L22066-L22069

Such patterns clearly breaks and punishes many websites that make use of short repeating name pattern. Clearly it's a catch-all kind of case which does not care if something is malicious that needs to be blocked.

**Comment by mapx-** [comment] 2021-05-27 19:46
test again after updating the lists

**Comment by Xerios** [comment] 2021-05-27 20:14
The main file in question is `https://tradinglite.com/wasm/wasm.js`, which is integral part of the app.

Although this shouldn't matter since those patterns are way too generic to be included in the first place.

**Comment by What-Zit-Tooya** [comment] 2021-05-29 22:58
I get anti adblock on this site and domain changed to `http://opalekr.icu/aucw5bhn`
![1](https://user-images.githubusercontent.com/9832875/120086765-030ec500-c10c-11eb-8ea8-948b737c8668.png)

**Comment by DandelionSprout** [comment] 2021-05-31 17:22
Apparently all domains in this thread are hosted by CloudFlare, so that rules out IP address blocking as a theorethical approach.

**Closed** 2021-06-27 15:48 UTC

**Comment by JobcenterTycoon** [comment] 2021-07-02 03:01
ads on `http://imguiwe.buzz/aucw5bhn`

**Comment by What-Zit-Tooya** [comment] 2021-07-02 03:27
ads & tracker
`india17.hottracker.biz`
`reverseaggressivedependent.com`

**Comment by JobcenterTycoon** [comment] 2021-07-04 03:48
ads on `http://imgweika.buzz/aucw5bhn`

**Comment by okiehsch** [comment] 2021-07-04 04:37
`clutchsavage.com` is already blocked in `EasyList`.

**Comment by dimisa-RUAdList** [comment] 2023-10-28 17:25
@mapx- 
New domain pixsera's: `pickjsn.cfd`
Example: `http://pickjsn.cfd/ksbut`
