### ISSUE TITLE
maxstream.video: breakage

### ISSUE THREAD

**Issue by Zaword** [uBlockOrigin/uAssets#19268] opened 2023-08-03 14:28 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/videostream/b9kgyud91ji9/3b547nk0me38/WW54bDNmWENsbkZLQWdPL3hDT1orUT09`

### Category

breakage

### Description

The website is a video hosting, it detects ublock and show a warning with a browser message after 5-10 seconds, then it hides the player and breaks the page.
I've already reported this behavior here: https://github.com/uBlockOrigin/uAssets/issues/17070, but it appears that many ips (or maybe countries?) are banned by the site owner, so it was really hard for everyone here to check and make some test.
I will try to send more proof this time.
The anti-adblock protections seems to be these scripts:

```
https://ads.host-cdn.net/statsublocker.js
https://maxstream.video/js/antiadblock0.js
https://maxstream.video/js/antiadblock1_check.js
https://maxstream.video/js/antiadblock2.js
```

In the screenshots, I will show the behavior, the filter logs and the console.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![reportublock1](https://github.com/uBlockOrigin/uAssets/assets/43016094/6ccad473-d8ac-4ac7-97c8-ccb197296195)
![reportublock2](https://github.com/uBlockOrigin/uAssets/assets/43016094/e8cf2bc8-8324-4a9f-a2fb-0d5f757ca981)
![reportublock3](https://github.com/uBlockOrigin/uAssets/assets/43016094/ed1d2f64-407c-4f02-98b4-9d3c182cb2f8)
![reportublock4](https://github.com/uBlockOrigin/uAssets/assets/43016094/9bcc06b2-d077-4cbd-b126-cdb527d36f9d)
![reportublock5](https://github.com/uBlockOrigin/uAssets/assets/43016094/c6b5007e-f5a7-4bdf-87e3-5f8622b6a538)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 111556
 cosmetic: 173203
 scriptlet: 27124
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69650-101, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92520-21272, now
  fanboy-cookiemonster: 47994-47994, now
  ublock-annoyances: 5319-235, now
 default:
  user-filters: 0-0, never
  ITA-0: 10621-15, now
  easylist: 69252-105, now
  easyprivacy: 33319-269, now
  plowe-0: 3717-1072, now
  ublock-badware: 7651-143, now
  ublock-filters: 34153-536, now
  ublock-privacy: 447-6, now
  ublock-quick-fixes: 274-47, 18m
  ublock-unbreak: 2106-37, now
  urlhaus-1: 6843-0, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1338 ms (selfie)
 maxAssetCacheWait: 420 ms
popupPanel:
 blocked: 5
 network:
  dogcollarfavourbluff.com: 2
  googletagmanager.com: 1
  host-cdn.net: 1
  intellipopup.com: 1
 extended:
  ##+js(addEventListener-defuser, contextmenu, preventDefault)
  ##+js(abort-on-property-read, onload)
  ##+js(abort-current-script, document.body.oncontextmenu)
  ##+js(nano-setTimeout-booster, .fadeIn(), 3000)
  ##+js(no-window-open-if)
  ##+js(remove-attr, style, div[style="display: none;"])
```
</details>

**Comment by JobcenterTycoon** [comment] 2023-08-03 15:01
Works fine for me with a german IP.

What happens when you whitelist `ads.host-cdn.net/statsublocker.js`? I can’t test because i don’t see this request in my logger.

**Comment by Zaword** [comment] 2023-08-03 15:55
> Works fine for me with a german IP.
> 
> What happens when you whitelist `ads.host-cdn.net/statsublocker.js`? I can’t test because i don’t see this request in my logger.

Made a try, nothing changes

**Comment by okiehsch** [comment] 2023-08-03 16:17
I tried with a VPN but I get an access denied message.

**Comment by Zaword** [comment] 2023-08-03 18:10
I've just been banned from maxstream.video and the redirect one (uprot.net).
I guess the website owners are frequently watching here.
Anyway, how will the remote control thing work?

**Comment by ghajini** [comment] 2023-08-03 20:32
don't post clickable links

**Comment by stephenhawk8054** [comment] 2023-08-04 01:23
So can you access the link now or not?

**Comment by ghajini** [comment] 2023-08-04 03:45
i can access link,it plays fine

**Comment by stephenhawk8054** [comment] 2023-08-04 03:49
@ghajini Can you access the link `https://ads.host-cdn.net/statsublocker.js`? What does it say inside?

**Comment by stephenhawk8054** [comment] 2023-08-04 03:53
This one might help

```adb
@@||ads.host-cdn.net/*.js|$script,domain=maxstream.video
```

**Comment by ghajini** [comment] 2023-08-04 04:17
i don't get that request, also op has confirmed not work
https://github.com/uBlockOrigin/uAssets/issues/19268#issuecomment-1664238911
may be needs to confirm again@Zaword

**Comment by stephenhawk8054** [comment] 2023-08-04 04:23
> i don't get that request

Yeah, it depends on region I think. Similar to older discussion: https://github.com/uBlockOrigin/uAssets/issues/18115

Previous one is fixed by this: https://github.com/uBlockOrigin/uAssets/commit/d7ab86d5e0725a6d24d34a6eeeb2b3c041f77643

**Comment by Zaword** [comment] 2023-08-05 00:55
> i don't get that request, also op has confirmed not work [#19268 (comment)](https://github.com/uBlockOrigin/uAssets/issues/19268#issuecomment-1664238911) may be needs to confirm again @Zaword `@@||ads.host-cdn.net/*.js|$script,domain=maxstream.video`

This one works, thank you and @stephenhawk8054 !

**Closed** 2023-08-05 12:51 UTC
Labels: unable to reproduce, geo specific
