### ISSUE TITLE
discord.com: breakage

### ISSUE THREAD

**Issue by omar-chaar** [uBlockOrigin/uAssets#24334] opened 2024-07-01 20:43 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://discord.com/app
```

### Description

When using the discord web app with a Tampermonkey script Vencord, turning on the plugin of "WebRichPresence (arRPC)" on the browser doesn't work with the filter “Block Outsider Intrusion into LAN”.

The user keeps getting a warning of “Failed to connect to arRPC” and the plugin doesn't work.

Console:
```
Firefox can’t establish a connection to the server at ws://127.0.0.1:1337/. @me line 9 > injectedScript:56:8775
```
Disabling the filter “Block Outsider Intrusion into LAN” make it work as expected. 

The LAN access is needed to it work and the user is well aware of it, since it needs a node server running to work.

More information about the [plugin arRPC](https://github.com/Vendicated/Vencord/blob/main/src/plugins/arRPC.web/index.tsx) inside the [script Vencord](https://github.com/Vendicated/Vencord/)

### Other extensions used

Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 222094
 cosmetic: 259403
 scriptlet: 52663
 html: 2113
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82297-4052, now
  adguard-mobile: 9558-57, now
  adguard-spyware-url: 1572-120, now
  adguard-spyware: 69638-1529, now
  curben-phishing: 537-3, now
  adguard-cookies: 30208-48, now
  ublock-cookies-adguard: 1248-14, now
  fanboy-cookiemonster: 51287-3926, now
  ublock-cookies-easylist: 1248-1248, now
  adguard-social: 23031-57, now
  fanboy-social: 16350-750, now
  fanboy-thirdparty_social: 68-19, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 39070-114, now
  ublock-badware: 9050-0, now
  ublock-privacy: 938-2, now
  ublock-unbreak: 2425-2, now
  ublock-quick-fixes: 116-5, now
  easylist: 86338-2262, now
  easyprivacy: 51123-28484, now
  urlhaus-1: 14945-0, now
  plowe-0: 3543-1483, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1548 ms (selfie)
 maxAssetCacheWait: 371 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  127.0.0.1: 2

```
</details>

**Comment by stephenhawk8054** [comment] 2024-07-02 01:06
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) and find which connection is being blocked

**Comment by omar-chaar** [comment] 2024-07-02 02:35
<details><summary>Logger output</summary>

```
+10
/^\w+:\/\/127\.(?:(?:[1-9]?\d|1\d\d|2(?:[0-4]\d|5[0-5]))\.){2}(?:[1-9]?\d|1\d\d|2(?:[0-4]\d|5[0-5]))[:/]/$3p,from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
discord.com
3
get
websocket
ws://127.0.0.1:1337/
```
```
+0
https://discord.com/channels/@me
```
</details>


added the following static rule and it worked:
`
@@||127.0.0.1:1337^$websocket,domain=discord.com`

**Comment by stephenhawk8054** [comment] 2024-07-02 03:17
You can use that as your custom filter. Since the issue is caused by a custom userscripts in another extension, it won't be addressed in uBO stock lists.

**Closed by stephenhawk8054** 2024-07-02 03:17 UTC
