### ISSUE TITLE
Youtube Consent popup

### ISSUE THREAD

**Issue by grande-mephistopheles** [uBlockOrigin/uAssets#8218] opened 2020-11-15 07:21 UTC
### URL(s) where the issue occurs
youtube.com

### Describe the issue

Every time I open YouTube I have to click this popup to agree to continue. I don't keep any persistent data and everyting is wiped out on exit. Is there a filter I can use to block this?

### Screenshot(s)

![utube](https://user-images.githubusercontent.com/58479925/99179143-7de53500-2712-11eb-9832-19c76350da74.jpg)

### Versions

- Browser/version: [Mozilla Firefox 82.0.3 (64-bit)
- uBlock Origin version: 1.30.6

### Settings

-

**Comment by uBlock-user** [comment] 2020-11-15 07:24
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7842

**Closed by uBlock-user** 2020-11-15 07:24 UTC

**Comment by grande-mephistopheles** [comment] 2020-11-15 07:27
> Duplicate of #7842

I saw that issue but didn't understand what to do. It's quite a long thread. Could you please highlight me the solution?

**Comment by uBlock-user** [comment] 2020-11-15 07:34
> Also see #7636 (comment)

Solution causes breakage for some users, so not added in main filter list.

**Comment by grande-mephistopheles** [comment] 2020-11-15 07:37
thanks, will try it

**Comment by grande-mephistopheles** [comment] 2020-11-29 06:16
Unfortunately, none of the solutions in the mentioned issue is working properly. Search option is broken. I give up for now and will be waiting for a better solution.

**Comment by gwarser** [comment] 2020-12-02 08:22
> Search option is broken.

What do you mean by this? If you mean that dialog is not fixed on search pages, then new filter was added just now in this message: https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-716228744

**Comment by grande-mephistopheles** [comment] 2020-12-02 15:22
> > Search option is broken.
> 
> What do you mean by this? If you mean that dialog is not fixed on search pages, then new filter was added just now in this message: [#7636 (comment)](https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-716228744)

Yep thanks. it's working without issue now. No problems untill Google changes YT again.
BTW, I was that reddit user. :wink:
