### ISSUE TITLE
Issue with uBlock Origin & https://www.naval-technology.com

### ISSUE THREAD

**Issue by I-Heart-Unicorns** [uBlockOrigin/uAssets#7052] opened 2020-03-03 17:45 UTC
### Description

[Description of the bug or feature] Articles don't load on `www.naval-technology.com` with uBO enabled

### A specific URL where the issue occurs
`https://www.naval-technology.com/projects/haminaclass/`

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Go to `https://www.naval-technology.com/projects/haminaclass/` and the article isn't displayed (this applies to any article on this site with uBO enabled).
2. [Second Step] Disable uBO for the site, reload the page and the article appears. I can't for the life of me work out what is causing this proble, I have  a handful of filters enabled and I have Google domains globally blocked (Analytics, Syndication, Tag Services). Enabling them in grey and reloading the page doesn't cause the article to load. 
3. [and so on...]

### Expected behavior:

[What you expected to happen] Articles to be displayed.

### Actual behavior: 

[What actually happened] Articles don't load.

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Firefox 73.0.1 (64-bit)
* Operating System and version: Windows 10 Home (version 1903) (64-bit)

**Comment by mapx-** [comment] 2020-03-03 17:55
Purge + update all your lists and test again.
If still happens, open the logger, refresh the page, select only the blocked elements and post them here.

**Comment by yourduskquibbles** [comment] 2020-03-03 17:58
It's caused by a filter in Fanboy's Annoyances / Fanboy's Social filter list `##.share-container` causing the issue. (Not a stock uBO list so issue should be fixed in Fanboy list) @ryanbr 

@I-Heart-Unicorns add  `naval-technology.com#@#.share-container` to `My Filters` as temporary workaround.

**Comment by mapx-** [comment] 2020-03-03 18:04
closing, @ryanbr  hopefully will see & fix the issue.

**Closed by mapx-** 2020-03-03 18:04 UTC

**Comment by yourduskquibbles** [comment] 2020-03-03 20:03
@ryanbr `##.share-container` may also be used in articles on other [`Verdict Media Network sites`](https://www.verdict.co.uk/verdict-network/) with the same site template as `naval-technology.com` and would need the same exception filter. From my testing I think the sites below all use the same template as `naval-technology.com`


```
aerospace-technology.com
airport-technology.com
army-technology.com
chemicals-technology.com
clinicaltrialsarena.com
cosmetics-technology.com
designbuild-network.com
drinks-insight-network.com
foodprocessing-technology.com
homelandsecurity-technology.com
hospitalmanagement.net
hotelmanagement-network.com
hydrocarbons-technology.com
medicaldevice-network.com
mining-technology.com
naval-technology.com
offshore-technology.com
packaging-gateway.com
pharmaceutical-technology.com
power-technology.com
railway-technology.com
renewable-technology.com
retail-insight-network.com
roadtraffic-technology.com
ship-technology.com
verdict.co.uk
verdictfoodservice.com
water-technology.net
```

String of domains you can use in cosmetic filter: `aerospace-technology.com,airport-technology.com,army-technology.com,chemicals-technology.com,clinicaltrialsarena.com,cosmetics-technology.com,designbuild-network.com,drinks-insight-network.com,foodprocessing-technology.com,homelandsecurity-technology.com,hospitalmanagement.net,hotelmanagement-network.com,hydrocarbons-technology.com,medicaldevice-network.com,mining-technology.com,naval-technology.com,offshore-technology.com,packaging-gateway.com,pharmaceutical-technology.com,power-technology.com,railway-technology.com,renewable-technology.com,retail-insight-network.com,roadtraffic-technology.com,ship-technology.com,verdict.co.uk,verdictfoodservice.com,water-technology.net`
