### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by gamersnl3** [uBlockOrigin/uAssets#17190] opened 2023-03-15 21:45 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aternos.org/server/`

### Category

detection

### Description

Aternos.org detects uBO and warns you about it and then makes you press on a button and makes you wait 3 seconds. 
![Control-V](https://user-images.githubusercontent.com/108799082/225450934-92632adb-2a62-4450-8aa5-e6e81535ba09.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 86255
  cosmetic: 39028
  scriptlet: 17040
  html: 898
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32846-55, 13h.15m
    ublock-badware: 4707-0, 13h.14m
    ublock-privacy: 339-0, 3d.23h.46m
    ublock-abuse: 77-0, 3d.23h.45m
    ublock-unbreak: 1938-0, 13h.13m
    ublock-quick-fixes: 374-0, 1d.20m
    easylist: 63889-578, 1h.40m
    easyprivacy: 31035-1767, 4d.8h.21m
    urlhaus-1: 6834-0, 1d.19m
    plowe-0: 3757-2, 3d.2h.32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 166 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    aternos.org: 1
    ad-delivery.net: 1
    amazon-adsystem.com: 1
    cloudflareinsights.com: 2
    d1oykxszdrgjgl.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    quantserve.com: 1
    upapi.net: 1
    venatusmedia.com: 1
```
</details>

**Comment by gorhill** [comment] 2023-03-15 22:34
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Duplicate of #13144.

**Closed by gorhill** 2023-03-15 22:34 UTC
