### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Jkker** [uBlockOrigin/uAssets#14221] opened 2022-08-03 01:48 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=Ug9hHqKBHL8`

### Category

ads

### Describe the issue

The `ytd-promoted-sparkles-web-renderer` element is not properly blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 97444
  cosmetic: 55419
  scriptlet: 17655
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    CHN-0: 28519-91, 20h.35m
    easylist: 69000-74, 20h.31m
    easyprivacy: 27471-147, 20h.30m
    plowe-0: 3642-781, 4d.23h.38m
    ublock-abuse: 76-0, 4d.23h.37m
    ublock-badware: 4170-92, 20h.34m
    ublock-filters: 32373-140, 20h.33m
    ublock-privacy: 225-3, 4d.23h.36m
    ublock-quick-fixes: 344-21, 5h.40m
    ublock-unbreak: 1852-43, 20h.32m
    urlhaus-1: 4401-0, 5h.39m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 17 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 515 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 98
  blockedDetails: 
    youtube.com: 84
    doubleclick.net: 1
    google.com: 6
    googlesyndication.com: 1
    googlevideo.com: 6
```
</details>

**Comment by MasterKia** [comment] 2022-08-03 05:10
> - [X] I verified that the issue has not already been reported (use this button to find out)
> - [X] I did not answer truthfully to **all** the above checkpoints

Please read and follow the prerequisites carefully and truthfully instead of _**blindly ticking them**_

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed** 2022-08-03 05:58 UTC
