### ISSUE TITLE
What to do when reporting to easylist receives no response?

### ISSUE THREAD

**Issue by Jap2-0** [uBlockOrigin/uAssets#4305] opened 2018-12-13 02:28 UTC
About a month and a half ago, I reported a false positive to the [easylist forum](https://forums.lanik.us/viewtopic.php?f=64&t=42049), which has received no response.  A few weeks later, [I opened a pull request](https://github.com/easylist/easylist/pull/2319), which did not receive a response either.  I know that fixing the issue in easylist is preferred, but what should I do when that does not happen?

All relevant information is in the forum thread.

**Comment by okiehsch** [comment] 2018-12-13 02:44
That was fixed 10 days ago https://github.com/easylist/easylist/commit/da765e06863b3e0225f62757159a5093444a1f7e#diff-f24091089cd8ad441a6c4b0d5e514305
![image](https://user-images.githubusercontent.com/16838044/49911899-6945f580-fe88-11e8-9c29-32dcfd19b954.png)

To be clear, even if the filter had not been added to `Fanboy's Annoyance List` this is not an issue that will be fixed in `uAssets`, because `Fanboy's Annoyance List` is not part of `uBlock Origins` default setup.

**Closed by okiehsch** 2018-12-13 02:44 UTC

**Comment by okiehsch** [comment] 2018-12-13 02:46
>  I know that fixing the issue in easylist is preferred, but what should I do when that does not happen?

If the issue is about site breakage you can open an issue here, provided that the breakage is caused by a list that is enabled by default.

**Comment by Jap2-0** [comment] 2018-12-13 02:49
Okay, thanks.  I've closed the pull request there (to be honest I expected at least some sort of mention).  Thanks for finding that and for the clarification.
