### ISSUE TITLE
minhaconexao.com.br: ads

### ISSUE THREAD

**Issue by diogoSiqueira3** [uBlockOrigin/uAssets#14518] opened 2022-08-24 18:42 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.minhaconexao.com.br/`

### Category

ads

### Describe the issue

website showing ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 81566
  cosmetic: 47718
  scriptlet: 17923
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 69095-51, 1d.15h.31m
    easyprivacy: 27405-126, 1d.15h.30m
    plowe-0: 3633-776, 1d.7m
    spa-1: 4600-79, 4d.15h
    ublock-abuse: 76-0, 1d.6m
    ublock-badware: 4214-92, 1d.15h.29m
    ublock-filters: 32509-158, 1d.15h.28m
    ublock-privacy: 241-3, 1d.5m
    ublock-quick-fixes: 383-0, 1d.4h.11m
    ublock-unbreak: 1838-42, 1d.15h.27m
    urlhaus-1: 4707-0, 1d.4h.10m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 345 ms (selfie)
  maxAssetCacheWait: 71 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    minhaconexao.com.br: 2
    ampproject.org: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment] 2022-08-24 19:10
@Alex-302
`minhaconexao.com.br##+js(set, canRunAds, true)´

**Comment by Alex-302** [comment] 2022-08-25 15:34
@okiehsch I can't reproduce

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/186708272-e98c35e7-50da-4f95-9506-715190c9b44d.png)


</details>

**Comment by okiehsch** [comment] 2022-08-25 16:03
Hm, I still can
![image](https://user-images.githubusercontent.com/16838044/186713922-966d8f83-8f5b-47e9-bc0b-d6ff00e22dee.png)

The ads are caused by this bait request
`https://www.minhaconexao.com.br/_mini/static/scripts/ads_detect.min.js`.

**Comment by Alex-302** [comment] 2022-08-25 19:08
Which filter blocks this request?
On my side it is neither blocked nor unblocked.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/186748171-593b9d2b-0aae-4427-a185-7abb577b4b78.png)


</details>

**Comment by okiehsch** [comment] 2022-08-25 19:10
My bad, it's an EasyList filter I forgot that Adguard does not use it as a default list.
I will close the issue as fixed.

**Closed by okiehsch** 2022-08-25 19:10 UTC
Labels: to be fixed by regional list
