### ISSUE TITLE
rsgames.xyz: detection

### ISSUE THREAD

**Issue by absouini** [uBlockOrigin/uAssets#23004] opened 2024-03-20 22:29 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rsgames.xyz/link?token=VD3hSALyE/fx+XFW/dKLNYRmvsD6nsWoWmmKA9hna+W5tTtVkulQz4dFnwg//pHTPWIL7icpxdGepn68I2qZI89qJHcoYCwjLpSHbmMERSEAe1hryXbhhFGk/4pPx7nmvWzhUSaZgM4TTPro0i/+ymahVm9qrE3YrqZAKEUS2+wgcq6lwfx6Q+SS7HIt8/8UIMxBpaIFd7pcKXdyKXZPQ3elTyc6v9iBZrOc8Q==`

### Category

detection

### Description

Detect Adblock 

### Other extensions used

Adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 141454
 cosmetic: 52462
 scriptlet: 20495
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1468-3, never
  FRA-0: 23185-36, 4h.34m
  easylist: 82804-163, 4h.34m
  easyprivacy: 50395-252, 4h.34m
  plowe-0: 3765-1192, 4h.34m
  ublock-badware: 7977-162, 4h.34m
  ublock-filters: 37407-1756, now
  ublock-privacy: 765-6, 4h.34m
  ublock-quick-fixes: 221-45, 3h.34m Δ
  ublock-unbreak: 2252-37, 4h.34m
  urlhaus-1: 8040-0, 4h.34m
filterset (user): [array of 765 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18847 ms (selfie)
 maxAssetCacheWait: 5720 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by gorhill** [comment] 2024-03-21 01:14
https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by gorhill** [comment] 2024-03-21 01:15
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/22986

**Closed by gorhill** 2024-03-21 01:14 UTC
