### ISSUE TITLE
web.de [anti-adblock]

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10401] opened 2021-11-05 11:39 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://web.de/fairplay/`

### Describe the issue

anti-adblock

### Screenshot(s)

![r](https://user-images.githubusercontent.com/75935068/140505009-23c6512e-7efa-4b2b-933e-d5050354868f.png)

### uBlock Origin version

1.38.7b15

### Browser name and version

FF 94 / O 80

### Settings

- DEU: EasyList Germany

**Comment by okiehsch** [comment] 2021-11-05 11:47
How do you get that page `https://web.de/fairplay/` ?

I don't see it on my end.

**Comment by felix-22** [comment] 2021-11-05 11:54
https://github.com/AdguardTeam/AdguardFilters/issues/84380

**Comment by okiehsch** [comment] 2021-11-05 11:57
Isn't that issue already fixed by https://github.com/uBlockOrigin/uAssets/commit/bf62432033d24a826a83bdb9a2dedcbe0b93e531 on your end?

I can't reproduce.

**Closed** 2021-11-05 12:13 UTC

**Comment by felix-22** [comment] 2021-11-05 12:32
> Isn't that issue already fixed by [bf62432](https://github.com/uBlockOrigin/uAssets/commit/bf62432033d24a826a83bdb9a2dedcbe0b93e531) on your end?
> 
> I can't reproduce.

Nope. It has been fixed right now with uBlock-user's f28c6c1
