### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by OmriOn** [uBlockOrigin/uAssets#16940] opened 2023-02-25 14:59 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=fjClcxfSa-8`

### Category

ads

### Description

Showed me an ad for Monday.com at the start of the video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/76548146/221363797-352a4c30-65d6-474e-8c24-250d279ff6a0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 83452
  cosmetic: 38674
  scriptlet: 16964
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62092-46, 4d.21h.33m
    easyprivacy: 30984-1172, 4d.21h.32m
    plowe-0: 3681-902, 15d.4h.4m
    ublock-abuse: 79-0, 4d.21h.31m
    ublock-badware: 4417-121, 4d.21h.29m
    ublock-filters: 32009-139, 4d.21h.28m
    ublock-privacy: 274-1, 4d.21h.30m
    ublock-quick-fixes: 319-17, 2d.9h.15m
    ublock-unbreak: 1899-44, 4d.21h.27m
    urlhaus-1: 5949-0, 2d.9h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2319 ms (selfie)
  maxAssetCacheWait: 74 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    doubleclick.net: 3
    google.co.il: 1
    google.com: 1
    googlesyndication.com: 5
    youtube.com: 14
```
</details>

**Comment by garry-ut99** [comment] 2023-02-25 15:37
>  * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
>  * [x]  I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)


You didn't, duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636.

**Closed** 2023-02-25 16:07 UTC
Labels: duplicate
