### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by Shaddaaa** [uBlockOrigin/uAssets#14107] opened 2022-07-23 20:07 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=lZD4rL0_RU4`

### Category

breakage

### Describe the issue

Starting a few days ago random videos like the one above refuse playing with uBlock enabled. This does not happen for all videos, this one for example: `https://www.youtube.com/watch?v=JtI_cscIpC4` works just fine.

Both videos start with an ad when not using uBlock, so the issue can't just be that.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 88403
  cosmetic: 48581
  scriptlet: 17415
  html: 711
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 8425-1818, 5m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32955-127, 5m
    ublock-badware: 4213-0, 5m
    ublock-privacy: 240-0, 5m
    ublock-abuse: 76-0, 5m
    ublock-unbreak: 1850-0, 5m
    easylist: 68753-514, 5m
    easyprivacy: 27435-590, 5m
    urlhaus-1: 4853-0, 5m
    plowe-0: 3640-3, 5m
    DEU-0: 5894-2, 5m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 211 ms (selfie)
  maxAssetCacheWait: 221 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    youtube.com: 36
    doubleclick.net: 4
    google.com: 11
    google.de: 1
```
</details>

**Comment by krystian3w** [comment] 2022-07-23 20:58
Duplicate of #7636

**Comment by Shaddaaa** [comment] 2022-07-23 21:36
I do not get any error code, it's just endlessly loading:
![grafik](https://user-images.githubusercontent.com/40697861/180623556-ff57eab1-4bcc-461d-8162-47a4f48e85eb.png)

So I do not believe it's an exact duplicate.

**Closed** 2022-07-24 05:43 UTC
Labels: duplicate

**Comment by sk42git** [comment] 2022-07-25 16:03
Not a duplicate of #7636.

**Comment by mapx-** [comment] 2022-07-25 16:55
#7636 is ... ALL YT issues

However, see the comments from https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1193797211

**Comment by krystian3w** [comment] 2022-07-25 17:05
I consider bannish your multi-accounts.
