### ISSUE TITLE
Add "I don't care about cookies" to built-in list collections

### ISSUE THREAD

**Issue by zcyzcy88** [uBlockOrigin/uAssets#451] opened 2017-06-11 18:45 UTC
https://www.kiboke-studio.hr/i-dont-care-about-cookies

**Comment by gorhill** [comment] 2017-06-11 19:15
Duplicate of <https://github.com/gorhill/uBlock/issues/909>.

**Closed by gorhill** 2017-06-11 19:15 UTC

**Comment by zcyzcy88** [comment] 2017-06-11 19:27
Sorry. I searched issues but GitHub don't find it.
