### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by JacketyJack4** [uBlockOrigin/uAssets#14418] opened 2022-08-17 15:22 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=HXiqwuAgJRc`

### Category

breakage

### Describe the issue

Video never loads (continuously has the loading animation) until UBO is toggled off and the page is refreshed.  Just started on this new 1.44 version it seems?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 80179
  cosmetic: 45309
  scriptlet: 17646
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33174-40, 2d.1h.29m
    ublock-badware: 4237-0, 2d.1h.28m
    ublock-privacy: 247-0, 2d.1h.24m
    ublock-abuse: 76-0, 2d.1h.23m
    ublock-unbreak: 1873-0, 2d.1h.27m
    easylist: 69428-590, 2d.1h.26m
    easyprivacy: 27344-581, 2d.1h.25m
    urlhaus-1: 4828-0, 2h.16m
    plowe-0: 3635-3, 2h.17m
    ublock-quick-fixes: 400-0, 2h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2053 ms (selfie)
  maxAssetCacheWait: 1192 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    youtube.com: 30
    doubleclick.net: 3
    google.com: 5
    googlevideo.com: 3
```
</details>

**Comment by okiehsch** [comment] 2022-08-17 16:02
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by okiehsch** 2022-08-17 16:02 UTC
Labels: unable to reproduce

**Comment by MasterKia** [comment] 2022-08-17 16:28
See: https://github.com/easylist/easylist/wiki/youtube-issues
