### ISSUE TITLE
pharmacy.amazon.com: popups

### ISSUE THREAD

**Issue by ssm2130** [uBlockOrigin/uAssets#17170] opened 2023-03-14 06:34 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pharmacy.amazon.com/?_encoding=UTF8&ref_=CS_ILM_HI_V1_RB2_230304&pd_rd_w=tgxIy&content-id=amzn1.sym.bffce72a-55a6-4ee0-8db2-6353fa1e0234&pf_rd_p=bffce72a-55a6-4ee0-8db2-6353fa1e0234&pf_rd_r=5DYBYW3WG5MEKF6BF86F&pd_rd_wg=V2GR9&pd_rd_r=b076ec20-81d9-4c52-b718-52e537f45742`

### Category

redirect

### Description

When on Amazon.com while UBolck Origin is running randomly this page is brought up replacing the current page I am on.

### Screenshot(s)

https://user-images.githubusercontent.com/89034783/224915595-dc8c28d7-5674-49d9-9659-919ab4598151.png

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 86262
  cosmetic: 39059
  scriptlet: 17029
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-3, never
    easylist: 63813-44, 3d.7h.18m
    easyprivacy: 31035-1174, 3d.7h.19m
    plowe-0: 3750-931, 11d.7h.58m
    ublock-abuse: 78-0, 1d.6h.48m
    ublock-badware: 4710-114, 1d.2h.46m
    ublock-filters: 31981-76, 1d.2h.45m
    ublock-privacy: 291-1, 1d.6h.47m
    ublock-quick-fixes: 374-19, 13h.42m
    ublock-unbreak: 1920-39, 1d.2h.44m
    urlhaus-1: 6962-0, 13h.41m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 33 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6848 ms (selfie)
  maxAssetCacheWait: 335 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    amazon.com: 3
```
</details>

**Comment by krystian3w** [comment] 2023-03-14 07:21
Are you sure you're not clicking somewhere on the side where there could be a tracking pixel with apharmacy (drug) ad?

As the url does not change dynamically like in YouTube, maybe it will partially work:
```adb
||pharmacy.amazon.com^$doc,domain=amazon.com|~I-don-t-want-buy-medicine.*
```
And click "back" in uBo warming.

**Comment by ssm2130** [comment] 2023-03-14 07:30
It has happened 3 times and I have clicked nothing.  It is quite strange but it feels like there is a "timer" that once elapsed it brings me to that page.  I often open Amazon pages and let them sit.  If it happens to be the page in "focus" at the time, this page seems to come up.  Just started yesterday.

**Comment by krystian3w** [comment] 2023-03-14 08:13
If you want, you can review all the events at your leisure:

https://github.com/gorhill/uBlock/wiki/Resources-Library#no-settimeout-ifjs-
https://github.com/gorhill/uBlock/wiki/Resources-Library#no-setinterval-ifjs-

> ```adb
> amazon.com##+js(nostif)
> amazon.com##+js(nosiif)
> ```

If page don't mask redirect in poor method like meta refresh tag:

https://github.com/gorhill/uBlock/wiki/Resources-Library#refresh-defuserjs-

this one could be checked if it is in the `view-source:` of the redirect page (assuming that pasted after "DOMContentLoaded" or first "blur" would not work).

Or found a way for the scriptlet to not detect his timeout/interval.

**Comment by gorhill** [comment] 2023-03-14 17:36
Be sure it's not another extension causing this, you need to verify that the issue occurs with just uBO enabled, and restart the browser after you disable your other extensions to be sure. It could also be caused by a malicious application in your system.

**Comment by ssm2130** [comment] 2023-03-14 18:12
I wonder if this is the function that is doing it:  window.navmet.push

    <script type='text/javascript'>
                                window.navmet.push({
                                    key: 'SWM',
                                    end: +new Date(),
                                    begin: window.navmet.tmp
                                });

**Comment by ssm2130** [comment] 2023-03-14 18:19
Its once you are on a product page...

Line 828

https://www.amazon.com/WizKids-Pathfinder-Battles-Premium-Dragons/dp/B084M96N2Q/?_encoding=UTF8&pd_rd_w=ZtQaO&content-id=amzn1.sym.bc5f3394-3b4c-4031-8ac0-18107ac75816&pf_rd_p=bc5f3394-3b4c-4031-8ac0-18107ac75816&pf_rd_r=5DNVC72J487JTY6H0CM5&pd_rd_wg=1H5lz&pd_rd_r=94536a77-16d2-4eb8-b135-22c140a8b0e6&ref_=pd_gw_ci_mcx_mr_hp_atf_m&th=1

**Comment by gorhill** [comment] 2023-03-14 18:34
I find it hard to believe Amazon would randomly open page to prescription drug products. Any other people with such issues?

**Comment by ssm2130** [comment] 2023-03-14 18:46
Its actually the "One Medical" page and the "Pharmacy" page that come up.  Amazon purchased the One Medical company in 2022 and it is a new product push for them that has been in the news,

Honestly, the first time it happened I assumed I clicked something.  The second time I was sure I didn't click anything.  The third time I was positive I didn't click anything.

The use case is having a product page open on amazon for some number of minutes (up to 30 minutes) and then going back to interact with that window via scrolling, ect.

I would be interested if anyone else is having this issue as well.  I do run my computer with 3 chrome instances running at all times with 5-30 tabs open on each instance.  Its never happened before this week to me.  I figured I would post it because UBlock didn't catch whatever it was and was curious if this was some sort of new automated redirect process that Amazon is taking advantage of in Chrome.  If it is, there is certainly a risk here of others taking advantage and force redirecting to other sites.

**Comment by gorhill** [comment] 2023-03-14 18:51
Are you logged in into amazon?

**Comment by ssm2130** [comment] 2023-03-14 18:53
Yes

**Comment by Daxy7** [comment] 2023-03-14 19:56
Have you tried scanning your system with [Malwarebytes](https://www.malwarebytes.com/mwb-download/thankyou)?

**Comment by stephenhawk8054** [comment] 2023-03-14 22:17
Does it happen in Firefox?

**Comment by ssm2130** [comment] 2023-03-15 05:31
Yes.  System free of all Malware, viruses, ect.

**Comment by ssm2130** [comment] 2023-03-15 17:05
yes, I am logged into amazon

**Comment by ssm2130** [comment] 2023-03-15 17:06
Yes, I am logged into amazon

**Comment by mapx-** [comment] 2023-03-15 18:20
closing for now - comment back here if you find a way to reproduce the problem at will

**Closed by mapx-** 2023-03-15 18:20 UTC
Labels: unable to reproduce
