### ISSUE TITLE
dropgalaxy.com : anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12097] opened 2022-03-08 08:58 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://dropgalaxy.com/frfz4zkt4l0s

### Describe the issue

dropgalaxy redirects to techmatter.xyz where there's  a timer.
After the timer expires, click "Create download link". 
Again you are redirected to dropgalaxy where the Adblock is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/157202737-aa9b4315-f7df-45c4-99fd-ea5e3523f6d0.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by okiehsch** [comment] 2022-03-08 09:02
Update your filter lists.

**Comment by okiehsch** [comment] 2022-03-08 09:02
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/12084

**Closed by okiehsch** 2022-03-08 09:02 UTC

**Comment by blazesprings** [comment] 2022-03-08 09:08
@okiehsch I updated the filter lists but the problem still exists.

**Comment by okiehsch** [comment] 2022-03-08 09:15
I can't reproduce. It works fine on my end with a default setup.

**Comment by blazesprings** [comment] 2022-03-08 09:24
I just checked this link : https://dropgalaxy.in/frfz4zkt4l0s
dropgalaxy redirects to techmatter.xyz where there's a timer.
After the timer expires, click "Create download link".
Again you are redirected to dropgalaxy where the Adblock is detected.

**Comment by okiehsch** [comment] 2022-03-08 09:27
With your link after I click "Create download link
![image](https://user-images.githubusercontent.com/16838044/157207843-6411507a-b0b1-46f6-96d2-4c8e95ca7a31.png)

**Comment by mapx-** [comment] 2022-03-08 09:31
maybe `techthematter`  which was fixed yesterday. So, you should update again your lists.

**Comment by blazesprings** [comment] 2022-03-08 09:37
@mapx I purged the cache and updated filter lists. Is it sufficient or do i have to add something else?

**Comment by mapx-** [comment] 2022-03-08 09:42
Disable any other extension if any and test again.
Also, if you have some antivirus with web-shield feature enabled try disabling it (the shield)
or ... even if at router level you have some advanced blocking rules ..

**Comment by blazesprings** [comment] 2022-03-08 10:43
I don't have any other extension. I guess they have updated the code.

**Comment by blazesprings** [comment] 2022-03-08 11:06
@mapx- and @okiehsch In your case after clicking the "Create download link" you are redirected to techthematter
(refer to the @okiehsch screenshot) whereas I am redirected to https://dropgalaxy.com/829-find-out-what-are-the-prices-on-mortgage-loans-to-live-with-life.html). I noted this difference in behavior. Please suggest me the changes to be made.

**Comment by okiehsch** [comment] 2022-03-08 11:58
> Please suggest me the changes to be made.

We can't reproduce.

**Comment by JobcenterTycoon** [comment] 2022-03-08 12:56
I can reproduce i get `Adblock Detected! token missing` but going through this crap a second time works for me

`@@||freychang.fun^$xhr,domain=dropgalaxy.*|financemonk.net|techssting.com|techthematter.xyz` works for me

**Comment by blazesprings** [comment] 2022-03-08 19:35
@mapx- I have added this line to my filters. At first it worked but after sometime the adblock got detected.

**Comment by mapx-** [comment] 2022-03-08 19:59
unticked.

However more filters were added to the list by JobcenterTycoon.

**Comment by JobcenterTycoon** [comment] 2022-03-08 20:15
My last fix was 3 hours ago. I tested and the fix still works

**Comment by blazesprings** [comment] 2022-03-09 07:38
Thanks everyone.

**Comment by AbhiDGamer** [comment] 2022-04-08 00:42
Drop galaxy is blocking ublock again try this link
https://dgdrive.xyz/cf5upi0y3w92

**Comment by AbhiDGamer** [comment] 2022-04-08 03:41
Hi
I had Firefox enhance privacy protection enabled which was being caught as an adblock by drop galaxy. Disabling it made the ads go away
