### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by HypnoticHydronic** [uBlockOrigin/uAssets#18194] opened 2023-05-22 21:29 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/lyrics`

### Category

ads

### Description

Ads would persist even with the blocker on, but, it never played audio or showed how much time was left.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 92457
 cosmetic: 38786
 scriptlet: 17454
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66035-48, 36m
  easyprivacy: 31825-49, 2d.17h.40m
  plowe-0: 3737-944, 5d.17h.26m
  ublock-abuse: 70-0, 4d.16h.32m
  ublock-badware: 7144-128, 19h.11m
  ublock-filters: 33038-116, 2d.22h.53m
  ublock-privacy: 392-75, 4d.16h.33m
  ublock-quick-fixes: 360-36, 34m
  ublock-unbreak: 2020-39, 17h.10m
  urlhaus-1: 5659-0, 35m
filterset (user): [empty]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 472 ms (selfie)
 maxAssetCacheWait: 228 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 1
  sentry.io: 1
```
</details>

**Comment by okiehsch** [comment] 2023-05-22 21:32
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18148

**Closed by okiehsch** 2023-05-22 21:32 UTC
