### ISSUE TITLE
btcut.io: detection

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#22481] opened 2024-02-14 11:44 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokrealtime.com/tech/?url8j=https://btcut.io/m33Xp`

### Category

detection

### Description

Website detects adblocker and extended the time to 500 seconds.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/674efae7-bfa1-4707-a633-44b37d3d7abe)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122862
 cosmetic: 45470
 scriptlet: 20442
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 81045-14, now
  easyprivacy: 50196-38, now
  plowe-0: 3782-1184, now
  ublock-badware: 7861-141, now
  ublock-filters: 37277-349, now
  ublock-privacy: 975-6, now
  ublock-quick-fixes: 138-26, now
  ublock-unbreak: 2216-32, now
  urlhaus-1: 7220-0, 11m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 425 ms (selfie)
 maxAssetCacheWait: 182 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  tiktokrealtime.com: 1
  googlesyndication.com: 2
  profitsfly.com: 1
```
</details>

**Comment by ItsProfessional** [comment] 2024-02-14 12:01
Duplicate of #17361

**Closed by ItsProfessional** 2024-02-14 12:01 UTC
Labels: duplicate
