### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Redstar1988** [uBlockOrigin/uAssets#10880] opened 2021-12-12 03:53 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/watch?v=5mz_hPMU3gQ`

### Category

ads

### Describe the issue

ads running despite ublock on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78452
  cosmetic: 39430
  scriptlet: 16272
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61351-6, 3d.20h.8m
    easyprivacy: 26467-17, 3d.20h.6m
    plowe-0: 3697-810, 2d.15m
    ublock-abuse: 72-0, 3d.20h.4m
    ublock-badware: 3539-60, 3d.20h.1m
    ublock-filters: 29892-127, 3d.19h.59m
    ublock-privacy: 192-5, 3d.19h.57m
    ublock-unbreak: 1705-38, 3d.19h.55m
    urlhaus-1: 8445-0, 22h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 288
  launchFromSelfie: true
popupPanel: 
  blocked: 766
```
</details>

**Comment by uBlock-user** [comment] 2021-12-12 04:30
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2021-12-12 04:30 UTC
