### ISSUE TITLE
[nsfw] youtube.com: detection

### ISSUE THREAD

**Issue by gamer69420gfgfg** [uBlockOrigin/uAssets#19451] opened 2023-08-24 18:08 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

detection

### Description

its blockt

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98400
 cosmetic: 39302
 scriptlet: 18313
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69615-10, now
  easyprivacy: 33309-63, now
  plowe-0: 3726-1065, now
  ublock-badware: 7777-146, now
  ublock-filters: 34340-122, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 226-44, now
  ublock-unbreak: 2116-32, now
  urlhaus-1: 6007-0, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 416 ms (selfie)
 maxAssetCacheWait: 122 ms
popupPanel:
 blocked: 11
 no-remote-fonts: true
 network:
  youtube.com: 5
  doubleclick.net: 2
  gstatic.com: 4
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by JobcenterTycoon** [comment] 2023-08-24 18:10
Duplicate of #7636

**Closed by JobcenterTycoon** 2023-08-24 18:10 UTC
