### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by ClaraRenna** [uBlockOrigin/uAssets#12900] opened 2022-04-22 13:57 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=kbJ2Pr_ccR0&list=RDMMJg2_Vw_rzNI&index=27`

### Category

ads

### Describe the issue

It shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 86641
  cosmetic: 49777
  scriptlet: 16541
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 12943-0, 54m
    easylist: 66067-55, 3d.1h.53m
    easyprivacy: 26842-123, 3d.1h.52m
    plowe-0: 3682-805, 2d.13h.45m
    ublock-abuse: 74-0, 7d.21h.32m
    ublock-badware: 4077-93, 3d.1h.51m
    ublock-filters: 30609-114, 3d.1h.50m
    ublock-privacy: 209-2, 7d.21h.31m
    ublock-quick-fixes: 166-0, 55m
    ublock-unbreak: 1762-42, 3d.1h.49m
    urlhaus-1: 7919-1, 56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 522 ms (selfie)
  maxAssetCacheWait: 217 ms
popupPanel: 
  blocked: 936
  blockedDetails: 
    youtube.com: 747
    doubleclick.net: 34
    google.com: 112
    google.it: 1
    googleadservices.com: 1
    googlesyndication.com: 35
    googlevideo.com: 6
```
</details>

**Comment by krystian3w** [comment] 2022-04-24 20:07
Duplicate of #7636

**Closed** 2022-04-26 00:56 UTC
Labels: duplicate
