### ISSUE TITLE
www2.kickassanime.ro: ads

### ISSUE THREAD

**Issue by FlyingJudgement** [uBlockOrigin/uAssets#15436] opened 2022-10-27 14:41 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www2.kickassanime.ro/`

### Category

ads

### Describe the issue

Little new pop up on left sneaked through as of today. 
Possible to pick it with uBlock

With addblocker is Not possible to pick it, add occupies the same space as the picker and disapears as the picker comes up the page code also swaps out under F12. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 80435
  cosmetic: 45243
  scriptlet: 17647
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33207-138, never
    ublock-badware: 4237-0, never
    ublock-privacy: 247-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1871-0, never
    ublock-quick-fixes: 386-0, never
    easylist: 69310-176, never
    easyprivacy: 27312-133, never
    urlhaus-1: 5164-0, never
    plowe-0: 3634-779, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1245 ms
  maxAssetCacheWait: 7 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    googletagmanager.com: 2
    offerimage.com: 4
    outoctillerytor.com: 1
    pubfuture.com: 4
    tzegilo.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-10-27 14:43
> I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Why did you tick the box? You have not updated your filter lists.
Update them.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/15423

**Closed by okiehsch** 2022-10-27 14:43 UTC
