### ISSUE TITLE
Youtube Ads didn't get filtered (screenshot)

### ISSUE THREAD

**Issue by Seraangel** [uBlockOrigin/uAssets#12939] opened 2022-04-24 16:35 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.youtube.com/watch?v=uzFvGbpaZ34

### Describe the issue

While running the videos ads pop up from below, around 1:01 (screenshot). Looks like rendered in the video stream. i don't even know if it's possible for uBlock origin to block it?

### Screenshot(s)

![Uploading Werbung.png…]()

### uBlock Origin version

1.42.2

### Browser name and version

Edge 100.0.1185.50

### Settings

none

**Comment by okiehsch** [comment] 2022-04-24 17:02
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by okiehsch** 2022-04-24 17:02 UTC

**Comment by okiehsch** [comment] 2022-04-24 17:05
> While running the videos ads pop up from below, around 1:01

Your screenshot is not working, if you mean the "tic tac" ad that is part of the stream and can't be removed by uBO.
