### ISSUE TITLE
youtube.com: [unknown]

### ISSUE THREAD

**Issue by AnikiOW** [uBlockOrigin/uAssets#20414] opened 2023-11-02 11:36 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=GwzspUds1wA`

### Category

[unknown]

### Description

did everything right and worked until yesterday, now it's only a gioant black rectangla with no video 

### Other extensions used

there is tampermonkey that i used before when i had only adblock with it now i got rid of adblock for u block and puttd tampermonkey off 
![image_2023-11-02_123630810](https://github.com/uBlockOrigin/uAssets/assets/125697544/19c9dbd1-5730-4ffe-a065-1ca5b385ff42)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/125697544/d2f5f728-7c31-4f02-a974-b65aa0d0893f)
![image](https://github.com/uBlockOrigin/uAssets/assets/125697544/ded142f4-c986-4c0d-ad49-f46ef8abbafa)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 285950
 cosmetic: 246262
 scriptlet: 46448
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27977-33, 2m
  adguard-generic: 79255-703, 2m
  adguard-mobile: 8811-46, 2m
  adguard-mobile-app-banners: 4720-10, 2m
  adguard-other-annoyances: 13718-11, 2m
  adguard-popup-overlays: 25002-92, 2m
  adguard-social: 21967-929, 2m
  adguard-spyware: 62661-1432, 2m
  adguard-spyware-url: 1293-5, 2m
  adguard-widgets: 2335-7, 2m
  block-lan: 54-0, 2m
  curben-phishing: 76992-20, 2m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  FRA-0: 28489-39, 2m
  easylist: 72269-1640, 2m
  easyprivacy: 32851-16870, 2m
  plowe-0: 3721-1583, 2m
  ublock-badware: 7417-348, 2m
  ublock-filters: 35159-4333, 2m
  ublock-privacy: 668-172, 2m
  ublock-quick-fixes: 219-138, 2m
  ublock-unbreak: 2133-151, 2m
  urlhaus-1: 11180-2, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3653 ms (selfie)
 maxAssetCacheWait: 668 ms
popupPanel:
 blocked: 13
 network:
  youtube.com: 1
  doubleclick.net: 2
  google.com: 6
  googlesyndication.com: 4
 extended:
  ###offer-module
  ###ticker.ytd-masthead
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##ytd-enforcement-message-view-model:has(> div.ytd-enforcement-m…
  ##yt-playability-error-supported-renderers:has(yt-button-view-mo…
  ###merch-shelf
  ###player-ads
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###social-links
  ##.ytp-share-button
  ##ytd-watch-flexy[player-unavailable] #player-container-outer.yt…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?\/(aclk\?…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
```
</details>

**Comment by gwarser** [comment] 2023-11-02 11:38
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19976

**Closed** 2023-11-02 11:37 UTC
