### ISSUE TITLE
geeksforgeeks.org: nuisance

### ISSUE THREAD

**Issue by John-Kilo** [uBlockOrigin/uAssets#14442] opened 2022-08-19 20:19 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.geeksforgeeks.org/python-theharvester-how-to-use-it/`

### Category

nuisance

### Describe the issue

Asks to sign up, continues asking. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 83905
  cosmetic: 45852
  scriptlet: 34410
  html: 739
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23921-26, 18h.39m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33221-2866, 18h.40m
    ublock-badware: 4237-0, 18h.39m
    ublock-privacy: 247-0, 18h.38m
    ublock-abuse: 76-1, 18h.37m
    ublock-unbreak: 1848-1, 18h.36m
    ublock-quick-fixes: 401-5, 18h.35m
    easylist: 69581-600, 18h.34m
    easyprivacy: 27378-579, 18h.33m
    urlhaus-1: 4611-0, 18h.32m
    plowe-0: 3635-3, 18h.31m
filterset (user): [empty]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 136 ms (selfie)
  maxAssetCacheWait: 58 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    geeksforgeeks.org: 2
    adrecover.com: 2
    google.com: 2
    googletagmanager.com: 1
    googletagservices.com: 1
    servedby-buysellads.com: 2
```
</details>

**Comment by Sandvici** [comment] 2022-08-19 21:29
Did you enable `uBlock filters -- Annoyances` ?
![image](https://user-images.githubusercontent.com/111546575/185709753-80c93785-87d7-4372-8176-9f14d42f0fc4.png)

**Comment by Sandvici** [comment] 2022-08-19 21:29
Did you enable `uBlock filters -- Annoyances` ?
![image](https://user-images.githubusercontent.com/111546575/185709753-80c93785-87d7-4372-8176-9f14d42f0fc4.png)

**Comment by MasterKia** [comment] 2022-08-20 05:54
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/12132

Go to uBlock Origin settings => Filter lists => Annoyances => Enable "uBlock Filters - Annoyances" => Click "Update now"

**Closed by MasterKia** 2022-08-20 05:54 UTC
