### ISSUE TITLE
Wikia/Fandom autoplay ads

### ISSUE THREAD

**Issue by index-eab** [uBlockOrigin/uAssets#7879] opened 2020-09-05 23:55 UTC
### URL(s) where the issue occurs

`https://gta.fandom.com/wiki/Grand_Theft_Auto_V`
`https://elderscrolls.fandom.com/wiki/Skyrim`
`https://fable.fandom.com/wiki/Snowspire_Village`

### Describe the issue

Autoplay videos widespread across Wikia/Fandom masquerade as content, but they were only introduced as an initiative to [sell advertising space](https://community.fandom.com/wiki/Thread:1319939#9). Unlike the articles themselves (the content that people visit the site for)  they are not made by wiki volunteers and are usually inane/inaccurate. In short, it's just an ad spot, nothing of value.

Note the disclaimer under the video in the first link: "The above video was added by FANDOM staff, not the editors of this site. Its content may not accurately represent the content of this article." I've seen similar messages on quite a few wikis. Wiki maintainers are unable to control the ad-videos and they're very obnoxious so they're widely derided by editors.

### Screenshot(s)

`https://i.imgur.com/0FmOTZv.png`

### Versions

- Browser/version: Mozilla Firefox 81
- uBlock Origin version: 1.29.2

### Settings

N/A

### Notes

N/A

**Comment by okiehsch** [comment] 2020-09-06 01:12
Duplicate of
https://github.com/uBlockOrigin/uAssets/issues/1532

Has already been fixed in `uBO-annoyances`.
If you don't want to enable that list add 
`fandom.com,wikia.com##.featured-video__wrapper`
to your personal filter list.

**Closed by okiehsch** 2020-09-06 01:12 UTC

**Comment by krystian3w** [comment] 2020-09-06 10:56
IMO `wikia.com` down all - converted to:

`fandom.com,wikia.org`

also org may no have that player.

**Comment by PIZZA90** [comment] 2020-10-30 06:48
maybe nothing related with uBO

```
https://wow.fandom.com/es/wiki/Ganz%C3%BAa
https://wow.fandom.com/es/wiki/
```

but i cant access to this site.. even with uBO OFF (Full White Screen). If i try visit: `https://wow.fandom.com/es/wiki/` i can see the page, with after 1 second, the Full White Screen appears

i dont know why but i can reproduce a lot of errors in console of `blockadblock.js` the numbers of this errors is constant increasing

![Captura](https://user-images.githubusercontent.com/33556647/97669172-d4504380-1a83-11eb-95b1-971ea16c39ce.PNG)

**Comment by krystian3w** [comment] 2020-10-30 07:02
Works on **blocked all** JavaScript.

**Comment by PIZZA90** [comment] 2020-10-30 07:11
wohooo working filter **krystian3w**

**Comment by krystian3w** [comment] 2020-10-30 07:15
But it's rather suitable for own filters if you must to read wikis of WoW.

**Comment by mapx-** [comment] 2020-10-30 07:23
@PIZZA90 

test
`wow.fandom.com##+js(aost, Math.random, runScript)`

**Comment by PIZZA90** [comment] 2020-10-30 07:24
also works **mapx-** nice!

**Comment by krystian3w** [comment] 2020-10-30 07:30
This imo works better than `aost` (?):

`||wow.fandom.com/*load.php?*ext.fandom.ImportJs%2Csite*version=$script,domain=wow.fandom.com`

+ I see empty comments sections (maybe broken becase still blocked too much.
+ loaded is orange 🟧  sticky to bottom bar "`wikia-bar-annon`"

**Comment by mapx-** [comment] 2020-10-30 07:38
even less blocking:

`||wow.fandom.com/es/load.php*modules=jquery`

**Comment by krystian3w** [comment] 2020-10-30 07:44
For my no works.

I have blank on `https://wow.fandom.com/es/wiki/Arthas_Menethil#articleComments`

**Comment by PIZZA90** [comment] 2020-10-30 07:47
this filter not working for me.. (blank)
`||wow.fandom.com/*load.php?*ext.fandom.ImportJs%2Csite*version=$script,domain=wow.fandom.com`

**Comment by krystian3w** [comment] 2020-10-30 07:57
OK, maybe chrome no load `ext.fandom.ImportJs,site`.
