### ISSUE TITLE
uBlock Origin

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#490] opened 2017-06-30 18:38 UTC
https://github.com/gorhill/uBlock

![ublock origin](https://user-images.githubusercontent.com/26278182/27749224-aeacb99a-5da0-11e7-8d31-e973b322d46c.jpg)

![ublock pop up](https://user-images.githubusercontent.com/26278182/27749662-7008dd2a-5da2-11e7-8e2d-3ff60f3e73ed.jpg)

Why isn't the quality of uBlock Origin as good as it used to be? It seems that uBlock Origin, doesn't block ads on certain websites, opens ads briefly in new tabs and sometimes windows before closing them which is annoying, and sometimes doesn't close them at all, and shows an annoying warning message for certain websites saying that a certain website's been blocked. Lots of websites now show a warning saying that they detected that you're using an adblocker and ask you disable the adblocker or use a different one. If you try to disable 3rd-party content for a certain website in uBlock Origin's advanced settings to stop ads from opening and then closing in new tabs and sometimes windows, then sometimes the site's content doesn't work anymore. Also, uBlock Origin's advanced settings cog wheel doesn't appear anymore in the top left corner of the uBlock Origin settings window. Thanks.

Firefox Developer Edition 55.0b6 (32-bit)
uBlock Origin 1.13.0
Anti-Adblock Killer 10.0
uBlock Protector List 8.61
AdBlock Protector Script 7.33

**Comment by SMed79** [comment] 2017-06-30 19:43
> It seems that uBlock Origin, doesn't block ads on certain websites

Do you have an example?

**Comment by okiehsch** [comment] 2017-06-30 19:46
This is  a rather generic issue, so you want me to improve the quality of uBO by blocking ads on certain websites closing tabs instantly and remove annoying warning messages on others.
I will fix this in no time.

**Comment by okiehsch** [comment] 2017-06-30 19:46
If you have a specific issue, I will reopen it.

**Closed by okiehsch** 2017-06-30 19:46 UTC

**Comment by js017** [comment] 2017-06-30 21:35
Ok. Have a good day. Thanks.

**Comment by gorhill** [comment] 2017-06-30 23:18
> doesn't block ads on certain websites, opens ads briefly in new tabs and sometimes windows before closing them which is annoying, and sometimes doesn't close them at all, and shows an annoying warning message for certain websites saying that a certain website's been blocked

If you un-check all selected filter lists in uBlock Origin, nothing will be blocked. What does this tell you? 

Answer: all the blocking done by uBO or any similar such blockers depends on filter lists, and these filter 
 lists exist because of the  completely voluntary work put in by volunteers on their free time to maintain them<sup>[1]</sup>.

Complaining that these lists are not perfect to catch _everything_, _everywhere_, _all the time_ contribute absolutely nothing.

A positive contribution is to report specific cases, with all the details so that volunteers can reproduce on their side to enable them to investigate a solution. The best contributions are the ones which provide a sensible solution on top of the detailed report.

The issue you opened here is not a contribution, rather the opposite.

***

[1] <https://github.com/easylist/easylist/graphs/contributors>, <https://github.com/AdguardTeam/AdguardFilters/graphs/contributors>,
 <https://github.com/uBlockOrigin/uAssets/graphs/contributors>, and many many more as you can see at <https://filterlists.com/>

**Comment by js017** [comment] 2017-07-01 14:51
Ok so how do you get uBlock Origin to block ads on websites, without showing annoying warning messages that say "uBIock Origin has prevented the following page from loading:" and then the website that was blocked? Other adblockers such as uBlock, and Adblock Plus used to block ads seamlessly without showing any warning messages or opening tabs and windows and then closing them, so is there a way to get uBlock Origin to work like that? Also, if I politely commented, "Ok. Have a good day. Thanks." as my last comment, then you shouldn't keep posting rude comments. The feedback users provide you, is actually valuable in terms of suggesting what you could do to make your program better. Have a good day. Thanks.

**Comment by gorhill** [comment] 2017-07-01 15:16
> Other adblockers such as uBlock, and Adblock Plus used to block ads seamlessly without showing any warning messages **or opening tabs and windows and then closing them**

Because they won't block the page that uBO outright blocks. They let the page load, and the inline script tags in that page execute. uBO doesn't let this happen, that is [strict blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking), unsupported by ABP (uBlock is abandonware, why is this even mentioned...). It's all explained to you.

The part I emphasized in your above sentence is just plain false. Feel free to provide evidence to substantiate this baseless claim, just as you failed to provide such specific case when you opened that issue here.

Feel free to use ABP or even uBlock if it's what works for you.

**Comment by uBlock-user** [comment] 2017-07-02 11:21
He did the same on uBP repo https://github.com/jspenguin2017/uBlockProtector/issues/341 and https://github.com/jspenguin2017/uBlockProtector/issues/342

**Comment by js017** [comment] 2017-07-14 19:24
Look at the screenshot that I posted. It would be nice if you could design uBlock Origin to block ads without showing those types of error messages. As for uBlock Origin opening tabs and windows and then closing them, that's exactly what it seems to be doing, and I already gave you the best explanations I could of that in my posts, so what other information do you need? It would also be nice if uBlock Origin could just block ads automatically without opening tabs and windows and then closing them. Thanks.

**Comment by gorhill** [comment] 2017-07-14 19:38
> It would be nice if you could design uBlock Origin to block ads without showing those types of error messages

Read **very** carefully: **filter list issues**, not a uBO issue.
