### ISSUE TITLE
dgdrive.xyz / dropgalaxy.com: detection

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#19165] opened 2023-07-25 12:27 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After the timer expires, the UBO is detected. 

### URL(s) where the issue occurs.

`https://dgdrive.xyz/4wwvulfbhshz`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/80951522/424601da-f9fe-4d39-b77b-3cda4512030d)

### uBO version

uBlock Origin 1.50.0

### Browser name and version

Chrome 104.xx

### Settings

All defaults

**Comment by BlazeFTL** [comment] 2023-07-25 13:08
```
@@*$ping,script,xhr,frame,image,domain=dropgalaxy.com
||cloudfront.net^$script,domain=dropgalaxy.com,important
dropgalaxy.com#@#iframe
dropgalaxy.com#@#[id^="div-gpt-ad-"]
dropgalaxy.com##iframe:style(left:-4000.39px !important;position:absolute !important)
dropgalaxy.com#@#[id^="div-gpt-ad-"]:style(opacity: 0 !important; pointer-events: none !important;)
dropgalaxy.com##[src*="dgpromo.jpg"]
dropgalaxy.com##DIV.container.pt-5.page.premium.downloadPage:has(.py-3)
dropgalaxy.com##div[id*="gpt-ad"]:upward(center)
dropgalaxy.com##.footer:style(left:-3000px !important;position:absolute !important)
dropgalaxy.com##.mt-5.col-md-12:style(left:-3000px !important;position:absolute !important)
dropgalaxy.com##.text-primary:style(left:-3000px !important;position:absolute !important)
dropgalaxy.com##.mb-1.pr-5.btn-block.btn-danger.btn
dropgalaxy.com##.mb-4.m-0.sharetabs
dropgalaxy.com##.btn-danger:style(left:-3000px !important;position:absolute !important)
dropgalaxy.com##.py-3
dropgalaxy.com##[id^="TR-"]:style(left:-3000px !important;position:absolute !important)
dropgalaxy.com#@#[src^="//ad.a-ads.com/"]
dropgalaxy.*#@##modalpop
dropgalaxy.com#@##nativefluid
dropgalaxy.com###vi-smartbanner:style(left:-3000px !important;position:absolute !important)
```

Try In My Filters

**Comment by JobcenterTycoon** [comment] 2023-07-25 16:03
@blazesprings fixed now. If you get detections again in the future just ping us with a comment here.

**Comment by blazesprings** [comment] 2023-07-26 04:12
Hey experts, i applied the custom filter, updated my lists but still UBO is detected

**Comment by BlazeFTL** [comment] 2023-07-26 05:31
@blazesprings U Applied My Filters ?
Then Try To Change Value Here ##iframe:style(left:-4000.39px To Random Numbers 4120.17px

**Comment by JobcenterTycoon** [comment] 2023-07-26 08:20
It works fine for me with the uBO filter without additional custom filter.

**Comment by BlazeFTL** [comment] 2023-07-26 10:48
@JobcenterTycoon Bro They Change Script,Xhr Depending On Region..Same As Devuploads...My Filters Were Working Looks Like DGOwner Joined The Chat😂

**Comment by blazesprings** [comment] 2023-07-29 12:54
@BlazeFTL Yes bro i applied your filters but it didn't work. I guess the host's guy is  watching this thread. Can someone PM me
the code so that I could apply it in custom filters section and get rid of this problem without the host server's developer actually knowing it.

**Comment by BlazeFTL** [comment] 2023-07-30 12:21
@blazesprings This Is Still Working For Me - https://github.com/uBlockOrigin/uAssets/issues/19165#issuecomment-1651006024

Somethings Wrong On Your Side

**Comment by blazesprings** [comment] 2023-07-30 13:42
@BlazeFTL Bro I updated the filters still the issue exists. Can someone suggest me some other filter. But the DG site guy is watching the thread. Can i share my id where you can send the cod to me in private ?

**Comment by BlazeFTL** [comment] 2023-07-31 04:55
@adsdestroyer Try Only This One...Remove Everything Else
```
@@*$ping,script,xhr,frame,image,domain=dropgalaxy.com
||cloudfront.net^$script,domain=dropgalaxy.com,important
dropgalaxy.com#@#iframe
dropgalaxy.com#@#[id^="div-gpt-ad-"]
dropgalaxy.com##iframe:style(left:-4000.39px !important;position:absolute !important)
dropgalaxy.com#@#[id^="div-gpt-ad-"]:style(opacity: 0 !important; pointer-events: none !important;)
```

**Comment by BlazeFTL** [comment] 2023-08-08 08:17
@blazesprings I Can Reproduce On Mobile Data But Not On Wifi.. However This Works For Me On Mobile Data Too
`https://pastelink.net/hxzpv00h`

**Comment by blazesprings** [comment] 2023-08-09 03:44
Sorry @BlazeFTL your code doesn't work. Is there any way to send code privately @mapx- @JobcenterTycoon Is it permitted if I
publish my email id here?

**Comment by BlazeFTL** [comment] 2023-08-09 04:02
@blazesprings There Is Nothing Much Too Do For You..I've Updated The Filters In My Previous Comment But It Would Get Patched Again So Dont Use This Trash Site

**Comment by BisArg** [comment] 2023-08-21 06:58
@BlazeFTL Don't lose hope mate. Even if it requires applying private code then please add it. We can't let that bastard site owner get away with imposing malware ads into users' devices.

**Closed** 2023-09-01 16:30 UTC
Labels: unable to reproduce, ongoing

**Comment by BlazeFTL** [comment] 2023-09-03 17:13
Filters Updated Test Lemme Know..Didnt Update Bcz Got Bored...
https://github.com/uBlockOrigin/uAssets/issues/19165#issuecomment-1669137843

**Comment by BlazeFTL** [comment] 2023-09-12 14:42
@dgisbaap Updated

**Comment by Fatcavill** [comment] 2023-09-15 05:21
thanks working bro😁

**Comment by BlazeFTL** [comment] 2023-09-22 03:10
@adsdestroyer You Added My Rules ?

**Comment by BlazeFTL** [comment] 2023-09-22 04:01
@adsdestroyer I Said If You Added Anything To My Filters Then Remove Those..Update Ubo Filters And Test Again

**Comment by BlazeFTL** [comment] 2023-09-22 04:48
Again Seems Liks Problem On Your Side Or Region Specific...I Cant Reproduce

**Comment by BlazeFTL** [comment] 2023-09-22 04:58
Does This Work ?
```
@@||vlitag.com^$script,xhr,domain=dropgalaxy.com
@@||login.popmonetizer.com^$xhr,domain=dropgalaxy.com

**Comment by BlazeFTL** [comment] 2023-09-22 07:14
Try This 🤣
```
@@*$script,xhr,domain=dropgalaxy.com
||d1rp4yowwe587e.cloudfront.net^$script,domain=dropgalaxy.com,important
*$script,redirect-rule=noopjs,domain=dropgalaxy.com,important
*$image,redirect-rule=1x1.gif,domain=dropgalaxy.com
*$xhr,redirect-rule=noop.txt,domain=dropgalaxy.com,important
dropgalaxy.com##+js(no-xhr-if, /adsbygoogle|doubleclick|mobileoffers|googlesyndication|histats|creativecdn|crwdcntrl|prebid|sync|cloudflareinsights|vlitag|inklinkor|popmonetizer|adsco|blockadsnot|ads|youtube|dubzenom/)
dropgalaxy.com##+js(no-fetch-if, /adsbygoogle|doubleclick|mobileoffers|googlesyndication|histats|creativecdn|crwdcntrl|prebid|sync|cloudflareinsights|vlitag|inklinkor|popmonetizer|adsco|blockadsnot|ads|youtube|dubzenom/)

**Comment by BlazeFTL** [comment] 2023-09-22 07:23
@MasterKia My Skill Issues😭🤣

**Comment by BlazeFTL** [comment] 2023-09-22 15:35
@adsdestroyer Then Problem On Your Side Or Region..
That Filter https://github.com/uBlockOrigin/uAssets/issues/19165#issuecomment-1730921332 Just Allowed Everything
Try Without UBO To Check If U Get Anti Adb Then Try With A Vpn

**Comment by JobcenterTycoon** [comment] 2023-11-02 12:13
Can’t reproduce on chrome, very unstable results on Firefox.

**Comment by Fatcavill** [comment] 2023-11-02 12:51
yes bro i tried after a hour it seems working now...sorry
but i would get random detection then after some time it works

**Comment by BlazeFTL** [comment] 2023-11-02 19:44
@Fatcavill Try In My Filters
```
@@*$script,domain=dropgalaxy.com
dropgalaxy.com##+js(no-xhr-if, /adsbygoogle|doubleclick|mobileoffers|googlesyndication|histats|creativecdn|crwdcntrl|prebid|sync|cloudflareinsights|vlitag|inklinkor|popmonetizer|adsco|blockadsnot|ads|youtube|dubzenom|rum|google-analytics|openx|hazoopso|lijit|4dex/)
dropgalaxy.com##+js(no-fetch-if, /adsbygoogle|doubleclick|mobileoffers|googlesyndication|histats|creativecdn|crwdcntrl|prebid|sync|cloudflareinsights|vlitag|inklinkor|popmonetizer|adsco|blockadsnot|ads|youtube|dubzenom|rum|google-analytics|openx|hazoopso|lijit|4dex/)
dropgalaxy.com#@#div[id^="TR-"][tr-id][style*="z-index: 9999"]
dropgalaxy.com##li, #a-ads5, .downloadPage > center, .mt-5.col-md-12, .footer, .text-primary, .mb-4.m-0.sharetabs [href], .mt-5.col-md-8, .share
dropgalaxy.com###vi-smartbanner, .btn-danger, .btnDownload1:remove()

**Comment by Fatcavill** [comment] 2023-11-03 03:42
thank you bro now works everytime

**Comment by Sintayew4** [comment] 2023-11-11 00:38
#19165

**Comment by Omega-6** [comment] 2023-12-03 21:13
![image](https://github.com/uBlockOrigin/uAssets/assets/152656980/5fa293cd-bcfe-4a0c-ae65-11a6fb67c89e)

**Comment by alekhyadas** [comment] 2024-04-13 09:57
did anyone find an option to this one?

**Comment by JobcenterTycoon** [comment] 2024-04-13 10:09
https://github.com/uBlockOrigin/uAssets/commit/4c268f9fd1789dc465e73c880d1925fdf5a6a604

**Comment by alekhyadas** [comment] 2024-04-13 10:48
> [4c268f9](https://github.com/uBlockOrigin/uAssets/commit/4c268f9fd1789dc465e73c880d1925fdf5a6a604)

Do I need to copy paste into my filters?

**Comment by JobcenterTycoon** [comment] 2024-04-13 11:25
No run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1 one time to force update the filterlist.

**Comment by Fatcavill** [comment] 2024-06-08 14:55
the site does not work anymore 
Please fix
T.i.a

**Comment by im-izz** [comment] 2024-11-02 20:32
Detection is back

**Comment by JobcenterTycoon** [comment] 2024-11-02 21:08
Please post a example link (the shortened one).

**Comment by im-izz** [comment] 2024-11-03 09:26
> @im-izz `financemonk.net##+js(rmnt, script, height())` works ?

I see what you where trying to do, I already tried that before and it lets me open the generated link tho after I open the link I get this
![image](https://github.com/user-attachments/assets/6aeb9b8f-ce08-449c-b0ec-a03e4404d35d)

**Comment by im-izz** [comment] 2024-11-03 09:47
> Please post a example link (the shortened one).

https://dropgalaxy.com/drive/flvqos70ivy3

**Comment by Rachitidk** [comment] 2025-01-24 18:41
Pop up ads and adblocker detection

**Comment by Rachitidk** [comment] 2025-01-25 19:21
Someone look into this.

**Comment by anburocky3** [comment] 2025-02-21 08:47
Have they fixed the issue? Its so frustating to browse ads in dropgalaxy.

**Comment by BlazeFTL** [comment] 2025-02-22 10:37
I Get Detected Without Any Adblocking...So Site Issue...They Even Force Adblock Depending On Region/TimeZone

**Comment by anburocky3** [comment] 2025-02-22 12:46
if you use Guest profile in chrome, there is no problem. But even if i have disabled UblockOrigin, it is detecting somewhat.

**Comment by BlazeFTL** [comment] 2025-02-22 13:05
Its Working For Me With Adblocking Now...Site Owner Probably Fixed It..He Is Here BTW

**Comment by anburocky3** [comment] 2025-02-22 21:09
Its still not working: 

![Image](https://github.com/user-attachments/assets/54cea73b-1c71-4815-862d-e55cfe1ddbe9)

**Comment by BlazeFTL** [comment] 2025-02-23 07:21
Test these
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-12228017

**Comment by anburocky3** [comment] 2025-02-23 07:53
> Test these [#17361 (reply in thread)](https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-12228017)

This one really worked! But still the overview appears check this: 

![Image](https://github.com/user-attachments/assets/015f1714-3b0a-475e-9004-adbdbf56f899)

Is there way, we can get rid of it and stop all popups, even popups are opening and ublock blocks at opening that popups.

**Comment by BlazeFTL** [comment] 2025-02-23 08:54
I Can Get Rid Of Everything But The Site Owner Aggressively Patches Everything Posted Here...See My Video Every Useless Elements Can Be Removed...But Try To Avoid This Site

**Comment by anburocky3** [comment] 2025-02-23 10:42
> Did you Tick "Allow custom filters requiring trust" In My Filters ? I Can Get Rid Of Everything But The Site Owner Aggressively Patches Everything Posted Here...See My Video Every Useless Elements Can Be Removed...But Try To Avoid This Site

Where can i find your video?
