### ISSUE TITLE
xnxx-sexfilme.com [ADS][NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3341] opened 2018-08-28 14:39 UTC
URL(s) where the issue occurs

`https://www.xnxx-sexfilme.com/film/zwei-lesben-ficken-auf-der-terrasse-9343/`

Describe the issue

ADS NSFW

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by ZaphodBeebblebrox** [comment] 2018-08-28 15:08
Fixed in aa359ed

**Closed by ZaphodBeebblebrox** 2018-08-28 15:08 UTC

**Comment by lain566** [comment] 2019-04-19 02:21
The site has ads and pre roll when playing the video

**Comment by lain566** [comment] 2019-04-19 04:03
There's a popup when clicking anywhere on the page.

`https://www.xnxx.com/video-frme5da/step_sister_maya_bijou_fucked_by_her_sleepwalking_brother_enjoypornhd.com_`

the same for
`https://www.xvideos.com/video26482973/step_sister_maya_bijou_fucked_by_her_sleepwalking_brother_enjoypornhd.com_`

Suggested filter, fixed in nano defender
`xvideos.com,xnxx.com##+js(abort-on-property-write.js, openpop)`

**Comment by okiehsch** [comment] 2019-04-19 04:14
I can't reproduce.

**Comment by lain566** [comment] 2019-04-19 04:18
You have to delete this cookie `wpn-popupunder`

**Comment by okiehsch** [comment] 2019-04-19 04:22
There is no such cookie on my end, I can't reproduce with Chrome or Firefox.

**Comment by okiehsch** [comment] 2019-04-19 04:33
![image](https://user-images.githubusercontent.com/16838044/56405553-0bc61900-626d-11e9-820c-a4293489f3cc.png)
![image](https://user-images.githubusercontent.com/16838044/56405505-d7eaf380-626c-11e9-948c-bda6528e2954.png)


I can see the openpop function in a script and the wpn-popunder cookie but weirdly I can't reproduce the popup and the cookie is not set.
Anyway I will add your suggested filter.

**Comment by lain566** [comment] 2019-04-19 04:34
I can reproduce it even using Tor browser with uBO installed, to be able to change my ip.

![Anotación 2019-04-19 063254](https://user-images.githubusercontent.com/27441315/56405547-010b8400-626d-11e9-96a3-95e4e0ab90b6.png)

**Comment by okiehsch** [comment] 2019-04-19 04:36
See my comment posted just before yours.

**Comment by lain566** [comment] 2019-04-19 04:37
Ok, thanks

**Comment by garry-ut99** [comment] 2023-02-18 15:22
A big ad placeholder, caused by `ghide` from "uBlock Filters" : [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219873779-deb9d5fa-65ec-45de-abbd-14354515276b.png)
on both main page and subpages, there is still adblock in the source code
