### ISSUE TITLE
gamepedia.com Instart Logic

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2468] opened 2018-06-04 14:47 UTC
### URL(s) where the issue occurs

`https://suigeneris.gamepedia.com/Exanima`
`https://theforest.gamepedia.com/V1.0`

### Describe the issue

Gamepedia uses instart logic, which usually can only be countered with uBlock Origin Extra. However, Gamepedia still has full functionality with `||gamepedia.com^$inline-script`. Should this filter be added to uBlock Lists?

### Settings

- Default Settings

**Comment by okiehsch** [comment] 2018-06-04 20:51
gamepedia has more than 1900 wikis, are you sure all of them are still fully functional with inline scripting disabled?
I would rather not add such a filter, just my opinion. 
The issue is fixed by installing uBO-extra, but I can see the beneffits of fixing instart logic for all Chrome users. 
@gorhill what do you think.

**Comment by zaphodbeebblebrox** [comment] 2018-06-04 22:33
All of the ones I have looked through appear to be reskinned versions of the same wiki. If you think it is too risky to add, that is fine.

**Comment by zaphodbeebblebrox** [comment] 2018-06-05 13:53
That works. I had assumed it would not work because it doesn't usually work with instart logic, but it works.

**Closed** 2018-06-05 14:04 UTC

**Comment by pcjtulsa** [comment] 2018-09-02 01:48
Hello, this filter is breaking some incidental scripts from loading.

For example, https://blacksurvival.gamepedia.com/index.php?title=Sandbox&oldid=11172 doesn't load the graphs with this filter active.

Can you please revise the filter to avoid preventing such scripts from working?

**Comment by okiehsch** [comment] 2018-09-02 02:05
Update your `uBO-filter` list, should work fine after that.

**Comment by pcjtulsa** [comment] 2018-09-02 02:16
Looking good, thanks!
