### ISSUE TITLE
puppet.com: breakage

### ISSUE THREAD

**Issue by jficz** [uBlockOrigin/uAssets#18032] opened 2023-05-11 12:35 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.puppet.com/docs/puppet/7/types/exec.html`

### Category

breakage

### Description

No CSS, page not styled. Content is ok.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 187841
 cosmetic: 40852
 scriptlet: 17624
 html: 952
listset (total-discarded, last-updated): 
 added: 
  CZE-0: 742-0, 21h.32m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34046-53, 3d.22h.55m
  ublock-badware: 7099-0, 3d.22h.54m
  ublock-privacy: 443-0, 9d.15m
  ublock-abuse: 70-70, 9d.14m
  ublock-unbreak: 2026-4, 3d.22h.53m
  ublock-quick-fixes: 248-0, 4h.26m
  easylist: 67042-628, 2d.23h.20m
  adguard-spyware-url: 1018-5, 21h.35m
  easyprivacy: 32250-614, 21h.36m
  urlhaus-1: 6939-1, 21h.33m
  curben-phishing: 91125-35, 21h.34m
  plowe-0: 3742-3, 9d.13m
  LegitimateURLShortener: 2185-137, 21h.31m
filterset (user): [empty]
trustedset: 
 added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 566 ms (selfie)
 maxAssetCacheWait: 151 ms
popupPanel: 
 blocked: 6
 network: 
  googletagmanager.com: 1
  puppet-docs-herrera.netlify.app: 4
  trendemon.com: 1
```
</details>

**Comment by gorhill** [comment] 2023-05-11 14:37
> `puppet-docs-herrera.netlify.app: 4`

I see no list blocking this.

> `LegitimateURLShortener: 2185-137, 21h.31m`

This is not a default filter list. Did you tamper with the troubleshooting information?

Open the logger, reload the page, and see what is blocking `puppet-docs-herrera.netlify.app` on your side. Report findings here.

**Comment by gorhill** [comment] 2023-05-11 14:45
Since this is clearly a bad false positive, I have added a counter filter to quick-fixes until the issue is fixed in `curben-phishing`.

**Closed** 2023-05-11 14:44 UTC
Labels: unable to reproduce

**Comment by gorhill** [comment] 2023-05-11 14:48
https://gitlab.com/malware-filter/phishing-filter/-/issues/64

**Comment by jficz** [comment] 2023-05-11 14:57
yes, LibreWolf is what I use. Didn't realize it changes the defaults

**Comment by gorhill** [comment] 2023-05-11 14:58
Ok, didn't realize this, I will keep that in mind in the future.

**Comment by okiehsch** [comment] 2023-05-11 15:44
> I think LibreWolf enables LegitimateURLShortener in the pre-installed uBO by default.

Thx, I was wondering why the Configuration of the OP showed a rather unique "default" setup.
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/2f913e07-55e0-4023-9647-8fa4138a7e48)

**Comment by okiehsch** [comment] 2023-05-11 15:46
>  not clear what "I did not enable external filter lists

It means filter lists that are not enabled by default, i.e. lists you have added manually after installing.

**Comment by jficz** [comment] 2023-05-11 16:08
> > not clear what "I did not enable external filter lists
> 
> It means filter lists that are not enabled by default, i.e. lists you have added manually after installing.

That's what I assumed (forgetting that LibreWolf changes the defaults) but it's not obvious. I suggest to change the wording to make it more explicit. Specifically, don't use the word "external" a it (imho) doesn't have any relevant meaning in this context.

**Comment by stephenhawk8054** [comment] 2023-05-12 01:33
Librewolf enables both `Legitimate URL Shortener` and `curben-phishing` by default.
