### ISSUE TITLE
twitch.tv: [unknown]

### ISSUE THREAD

**Issue by hy36521** [uBlockOrigin/uAssets#14685] opened 2022-09-05 10:59 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/s7735061`

### Category

[unknown]

### Describe the issue

ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 101031
  cosmetic: 52340
  scriptlet: 17895
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 29118-90, 2d.3h.8m
    easylist: 65738-82, 2d.3h.5m
    easyprivacy: 27453-150, 2d.3h.4m
    plowe-0: 3671-815, 2d.3h.3m
    ublock-abuse: 76-0, 2d.3h.1m
    ublock-badware: 4202-101, 2d.2h.59m
    ublock-filters: 32483-128, 2d.2h.58m
    ublock-privacy: 241-1, 2d.2h.57m
    ublock-quick-fixes: 413-4, 22h.57m
    ublock-unbreak: 1846-42, 2d.2h.55m
    urlhaus-1: 7594-0, 22h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 199 ms (selfie)
  maxAssetCacheWait: 64 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 4
```
</details>

**Comment by MasterKia** [comment] 2022-09-05 11:00
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-09-05 11:00
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-09-05 11:00 UTC
