### ISSUE TITLE
Any URL Containing "action=browse" is Blocked

### ISSUE THREAD

**Issue by HoldOffHunger** [uBlockOrigin/uAssets#11345] opened 2022-01-17 15:03 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.revoltlib.com/people/view.php?action=browse&perpage=20`

### Describe the issue

As you can see, this is blocked: `php?action=browse&`

Source: https://easylist.to/easylist/easyprivacy.txt

I have no idea why this is blocked. I was able to get around it by changing my URL to 
`.php?blahblah=1&action=browse`
 (OOoooOOoooOOooooOOooooo, super secure!)

Also, the list maintainers, so-called "Easy List", do not allow anyone now to join their forum to complain. Source: `https://forums.lanik.us/ucp.php?mode=register`

Can this list be permanently removed from uBlockOrigin? I know it can be customized and disabled (that's how I found out it was responsible for blocking valid websites). But why is it even included at all, if there's no accountability for those who maintain and work on the list, and especially when the list contains clearly valid, good URI components?

There is absolutely nothing about "action=browse" being malicious. Actions are defined as the interface of MVC (model-view-control) and ORM (object-relational modeling) -- so why would you ban something that basically runs half of the Internet?

### uBlock Origin version

1.40.8

### Browser name and version

Chrome 97.0.4692.71

### Settings

- No changes.

**Comment by mapx-** [comment] 2022-01-17 15:14
some issue on registering on forum => @LanikSJ

for `php?action=browse&` => @ryanbr

**Comment by gorhill** [comment] 2022-01-17 15:15
Discussion on Reddit, I asked OP to report here: <https://www.reddit.com/r/uBlockOrigin/comments/s65qiq/why_is_actionbrowse_blocked/>

**Comment by gorhill** [comment] 2022-01-17 15:17
There are two filters which are of dubious value:

    .php?action=browse&
    .php?action_name=

If not resolved in EasyPrivacy, I suggest maybe:

    .php?action=browse&$badfilter
    .php?action_name=$badfilter
    .php?action=browse&$3p
    .php?action_name=$3p

**Comment by gorhill** [comment] 2022-01-17 15:19
> OOoooOOoooOOooooOOooooo, super secure!
> so-called "Easy List"

@HoldOffHunger I asked you to drop the sarcasm, this accomplishes nothing of value.

**Comment by uBlock-user** [comment] 2022-01-17 15:32
> Can this list be permanently removed from uBlockOrigin? I know it can be customized and disabled (that's how I found out it was responsible for blocking valid websites). But why is it even included at all, if there's no accountability for those who maintain and work on the list, and especially when the list contains clearly valid, good URI components?

No, breakages are to be reported, no list is perfect. Neither are the web-admins who in the first place decided to use such phrases to collect some data which caused such filters to be added in the first place.

**Closed** 2022-01-17 16:04 UTC

**Comment by gorhill** [comment] 2022-01-17 19:05
> `https://www.revoltlib.com/people/view.php?action=browse&perpage=20`
> 
> As you can see, this is blocked: `php?action=browse&`

I don't see anything blocked by that filter when I navigate to the provided URL.

**Comment by uBlock-user** [comment] 2022-01-17 19:08
https://www.reddit.com/r/uBlockOrigin/comments/s65qiq/why_is_actionbrowse_blocked/ht1n3e0/

He bypassed the filter already.

**Comment by uBlock-user** [comment] 2022-01-17 19:17
git blame https://github.com/easylist/easylist/commit/71a74c7159d5ba5734ecb009dadcf14385057507

**Comment by gorhill** [comment] 2022-01-17 19:34
> He bypassed the filter already.

When I filter the logger output using `action=browse`, I see nothing which would be blocked. Only the main document shows a match with `action=browse`, and uBO does not block the main document when the match is a generic filter.

**Comment by uBlock-user** [comment] 2022-01-17 19:46
I know, the filter has existed for 4 years and not a single report has been filed over here or on reddit.

**Comment by iam-py-test** [comment] 2022-01-17 19:46
> Also, the list maintainers, so-called "Easy List", do not allow anyone now to join their forum to complain

Spam prevention. Issues can be reported at https://github.com/easylist/easylist on GitHub. 
In terms of issue reporting, EasyList is _far_ better than many lists

> Can this list be permanently removed from uBlockOrigin? I know it can be customized and disabled (that's how I found out it was responsible for blocking valid websites). But why is it even included at all, if there's no accountability for those who maintain and work on the list, and especially when the list contains clearly valid, good URI components?

The answer is NO. All lists will have false positives or issues. What matters is what happens next. If Easylist just ignored all the issues reported and @ryanbr (and the rest of the @EasyList team) refused to change, **then** we would consider removing EasyList. That hasn't happened yet and probably won't happen ever.
Keep in mind that we all are volunteers - which includes the EL team.

**Comment by gorhill** [comment] 2022-01-17 20:55
Given the filter has existed for four years and the case is not made that the filter is actually interfering at the provided URL, I think we should just revert the `badfilter` until there is more good faith to discuss what is the issue. At first I was open to consider that maybe `php?action=browse&` could cause issue (unlike say, `php?action=track&`) but due to the tone of the request and the inability to reproduce anything that resemble an issue made me change my stance.

**Comment by uBlock-user** [comment] 2022-01-17 21:08
He copy-pasted his pompous rant from github, very LQ effort. Should have stayed on reddit.

**Comment by uBlock-user** [comment] 2022-01-17 21:09
He copy-pasted his pompous rant from reddit, very LQ effort. Should have stayed on reddit only.

**Comment by LanikSJ** [comment] 2022-01-17 21:50
> Also, the list maintainers, so-called "Easy List", do not allow anyone now to join their forum to complain. Source: `https://forums.lanik.us/ucp.php?mode=register`

There's been 2 registration as of this morning so without any more info I'm not able do anything for you.  And if you bothered to read the [rules](https://forums.lanik.us/rules#affiliation) you'd know that EastList project has no connection what so ever to their forum aside from the shared name.
