### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by alvesdofutebol** [uBlockOrigin/uAssets#11489] opened 2022-01-28 10:02 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/?sk=h_chr`

### Category

ads

### Describe the issue

Sponsored ads bypassing uBlock Origin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79877
  cosmetic: 43336
  scriptlet: 16671
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63478-9, 1d.16h.25m
    easyprivacy: 26670-17, 1d.16h.24m
    plowe-0: 3679-817, 13h.51m
    spa-1: 4198-76, 1d.16h.26m
    ublock-abuse: 76-0, 1d.16h.23m
    ublock-badware: 3801-69, 1d.16h.22m
    ublock-filters: 30272-191, 1d.16h.21m
    ublock-privacy: 195-3, 1d.16h.20m
    ublock-unbreak: 1699-40, 1d.11h.29m
    urlhaus-1: 7189-0, 13h.49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2533 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment] 2022-01-29 21:34
Duplicate of #3367

**Closed** 2022-01-29 21:34 UTC
Labels: duplicate
