### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by antoniotari** [uBlockOrigin/uAssets#11991] opened 2022-03-01 18:04 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/2/`

### Category

breakage

### Describe the issue

page does not load the email. I can still see the title. page loads fine when I deactivate Ublock origin. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1970605/156223870-bd13854c-3a4b-4eb1-ad62-d4caaa8111db.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79758
  cosmetic: 41279
  scriptlet: 16501
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63961-9, 2d.22h.44m
    easyprivacy: 26626-122, 2d.22h.30m
    plowe-0: 3673-805, 3d.4h.21m
    ublock-abuse: 77-0, 2d.22h.29m
    ublock-badware: 3863-83, 2d.22h.24m
    ublock-filters: 30351-157, 2d.22h.28m
    ublock-privacy: 202-2, 2d.22h.27m
    ublock-unbreak: 1718-39, 2d.22h.25m
    urlhaus-1: 8437-0, 25m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 153 ms (selfie)
  maxAssetCacheWait: 127 ms
popupPanel: 
  blocked: 81
  blockedDetails: 
    google.com: 79
    googleusercontent.com: 2
```
</details>

**Comment by okiehsch** [comment] 2022-03-01 18:12
![image](https://user-images.githubusercontent.com/16838044/156225090-ef836956-972a-4ba0-85c2-276a605c24f2.png)

Indeed.

**Comment by okiehsch** [comment] 2022-03-01 18:13
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906

**Closed by okiehsch** 2022-03-01 18:12 UTC
