### ISSUE TITLE
Twitch infinite loading black screen

### ISSUE THREAD

**Issue by DManuel010** [uBlockOrigin/uAssets#14430] opened 2022-08-19 03:25 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Can't view Twitch live streams while uBlock is activated.  Not using any custom filters for blocking Twitch ads.  The stream is stuck on a black screen with a "play" button in the middle and tries to load the screen infinitely.

### A specific URL where the issue occurs

https://www.twitch.tv/gusjohnson

### Steps to Reproduce

1. Go to any stream on Twitch with uBlock activated.
2. Try to view the live stream.

### Expected behavior

Stream is viewable with or without ads.

### Actual behavior

The stream does not load, but instead is a black screen with a "play" button in the middle and "blocking ads..." in the top left.  The screen then seems to try to play and go back to this screen infinitely. 

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80274
  cosmetic: 45355
  scriptlet: 17652
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69581-51, 3h.41m
    easyprivacy: 27359-126, 3h.40m
    plowe-0: 3634-776, 11d.13h.9m
    ublock-abuse: 76-0, 12d.5h.35m
    ublock-badware: 4233-92, 3h.39m
    ublock-filters: 32514-121, 3h.38m
    ublock-privacy: 231-3, 12d.5h.34m
    ublock-quick-fixes: 404-37, 14h.28m
    ublock-unbreak: 1835-41, 3h.37m
    urlhaus-1: 4828-0, 14h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 130 ms (selfie)
  maxAssetCacheWait: 78 ms
```
</details>

**Comment by gwarser** [comment] 2022-08-19 08:54
Try addin `twitch.tv#@#+js(twitch-videoad)` to My filters?

**Comment by MasterKia** [comment] 2022-08-19 09:09
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-08-19 09:09 UTC
Labels: unable to reproduce
