### ISSUE TITLE
uBlock Origin shuts down tabs intentionally opened by users

### ISSUE THREAD

**Issue by fmrk** [uBlockOrigin/uAssets#21939] opened 2024-01-12 14:22 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Intentionally clicking a redirect button on any page that opens a new tab with e.g.:`ad.doubleclick.net` in the redirect path immediately shuts down the newly opened tab. 
I'm aware this example is linked with the EasyList filter: `||doubleclick.net^$popup` as observed in logs, but I believe it's not an expected behavior as this is an intended user's navigation choice rather than a popup.
It happens on multiple pages only with uBlock Origin, not with AdGuard, AdBlock, or Adblock Plus with the same EasyList filters on.

### A specific URL where the issue occurs.

https://www.finder.com.au/home-loans/best-home-loans

### Steps to Reproduce

1. Open https://www.finder.com.au/home-loans/best-home-loans
2. Click on any `Go to site` button for `Unloan Variable Home Loan`
<img width="1237" alt="image" src="https://github.com/uBlockOrigin/uBlock-issues/assets/12071815/1d002fb1-b1fb-45aa-a02a-9903188b28bb">
3. Wait for the redirect to init in the new tab

The same thing occurs for Unloan redirects on other pages such as:
- https://mozo.com.au/home-loans/information/unloan
- https://www.infochoice.com.au/institutions/unloan/unloan-home-loans
Or even any product redirect on: https://www.canstar.com.au/home-loans/

### Expected behavior

The user can get redirected to the final destination in the new tab

### Actual behavior

The tab is autoclosed

### uBO version

1.54.0

### Browser name and version

Google Chrome Version 120.0.6099.199 (Official Build) (x86_64)

### Operating System and version

Mac OS Ventura 13.6.3 (22G436)

**Comment by gorhill** [comment] 2024-01-12 15:41
I reopened to have another opinion as I am not sure this should be fixed. If I use `@@||doubleclick.net^$popup,domain=finder.com.au`, the tab is not closed but then strict blocking kicks in. The whole site's purpose seems to be have people click on ads.

**Comment by fmrk** [comment] 2024-01-12 16:00
> @@||doubleclick.net^$popup,domain=finder.com.au

Can we get `@@||doubleclick.net^$popup,domain=finder.com.au` added to uBlock Origin's own set of filters or do I have to reach out to EasyList?

**Comment by okiehsch** [comment] 2024-01-12 16:03
>  the tab is not closed but then strict blocking kicks in. The whole site's purpose seems to be have people click on ads.

The destination is not an ad, the strict blocking occurs because the site redirects through doubleclick.

> Can we get @@||doubleclick.net^$popup,domain=finder.com.au added to uBlock Origin's own set of filters or do I have to reach out to EasyList?

It should be fixed in `EasyList`
@ryanbr fyi 
Popup is blocked `||doubleclick.net^$popup.`
`@@||doubleclick.net^$popup,domain=finder.com.au`
fixes the isue.

**Closed** 2024-01-13 11:45 UTC
Labels: fixable by EasyList

**Comment by krystian3w** [comment] 2024-02-28 09:29
> AdGuard doesn't use EasyList.

That's not true.
'AdGuard Base' aka 'AdGuard – Ads' list copy up to 90-99% of filters from EL heritage:

https://filters.adtidy.org/extension/firefox/filters/2.txt

See his description:

```adb
! Checksum: SYRrrBCohynDqG8RoLiIjA
! Diff-Path: ../patches/2/2-s-1709109373-3600.patch
! Title: AdGuard Base filter
! Description: EasyList + AdGuard English filter. This filter is necessary for quality ad blocking.
! Version: 2.3.24.44
```

---

The reason of unable reproduction with AdGuar9 may then be the exclusion.txt file:

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/exclusions.txt
 or the AdGuard self-promo advertising unblocking list:

https://github.com/AdguardTeam/AdguardFilters/tree/master/UsefulAdsFilter/sections

**Comment by krystian3w** [comment] 2024-02-28 11:57
Why my comment was marked as off topic when gorhill lie:

![Screenshot_20240228-125505](https://github.com/uBlockOrigin/uAssets/assets/35370833/7a898c5b-e387-4330-b42d-6738af20265f)

AdGuard addon after enable AdGuard base have 54% filters from EL.

https://filters.adtidy.org/extension/firefox/filters/2.txt

<H3>

```adb
! Title: AdGuard Base filter
! Description: EasyList + AdGuard English filter. This filter is necessary for quality ad blocking.
! Version: 2.3.24.44
```

**Comment by garry-ut99** [comment] 2024-02-28 16:20
> AdGuard doesn't use EasyList, "based on EasyList" is not actual EasyList.

Earth must be flat then I guess, because when comparing EasyList vs EasyList embeded in AG Base Filter - they are plain copies with comments removed, all "modifications" are in "AG English Filter" itself, just like in "uBlock filter - Ads" itself, in such case saying AG doesn't use EasyList, is like saying uBO doesn't use EasyList either.
