### ISSUE TITLE
all profiles on pixiv.net are blocked

### ISSUE THREAD

**Issue by reyard** [uBlockOrigin/uAssets#8312] opened 2020-12-03 04:47 UTC
### **URL(s) where the issue occurs**

all profiles on pixiv.net are blocked 
Example: https://www.pixiv.net/en/users/37266970

uBlock Origin blocks scripts, styles and pictures on websites requesting them from *.pixiv.net subdomains making it inoperable for the users.

**filter line**
https://prntscr.com/vurb84

**With ublock**
https://prntscr.com/vurdvs

**Without ublock**
https://prntscr.com/vuredg

### **Versions**

Browser/version: all browsers
uBlock Origin version: current version

**Comment by Steelage** [comment] 2020-12-03 05:00
I'm also having same issues; the following filters have filter lines that causes the issue in pixiv.net which I had to disable them until they get fixed:
> - uBlock filters
> - KOR: YousList

**Comment by okiehsch** [comment] 2020-12-03 05:03
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/8311

Update your `uBO-filters` list.

**Closed by okiehsch** 2020-12-03 05:03 UTC

**Comment by krystian3w** [comment] 2020-12-03 09:58
@Yous

**Comment by krystian3w** [comment] 2020-12-03 10:25
> KOR: YousList

IMO no generate breakage...

**Comment by Steelage** [comment] 2020-12-03 11:50
> 
> 
> > KOR: YousList
> 
> IMO no generate breakage...

Oof that's my mistake and I'm sorry about that. I realized only the uBlock filter has gotten fixed but the issue is completely gone, I think I must have roughly inspected which filter(s) caused the issues and I thought it was causing issue just because it was shown in the log, but didn't inspected carefully.
