### ISSUE TITLE
tf1info.fr: detection

### ISSUE THREAD

**Issue by feierflorin** [uBlockOrigin/uAssets#20608] opened 2023-11-11 14:46 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tf1info.fr/environnement-ecologie/video-plus-grand-chantier-d-europe-comment-edf-va-agrandir-la-centrale-nucleaire-de-penly-avec-des-reacteurs-nouvelle-generation-2273732.html`

### Category

detection

### Description

Hi, in the past I hade the same issue  : tf1info.fr: detection #12611 ( https://github.com/uBlockOrigin/uAssets/issues/12611 ) 

But now is back again , the site is detecting the uBlock

Thank you ! 
https://github.com/uBlockOrigin/uAssets/assets/103038722/79eee945-cc2f-4c5e-a1fa-510e45ec5817

### Other extensions used

Wappalyzer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 125346
 cosmetic: 57353
 scriptlet: 19025
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7156-0, 16m
 default:
  user-filters: 0-0, never
  FRA-0: 28551-52, 12m
  easylist: 75229-95, 16m
  easyprivacy: 32866-340, 16m
  plowe-0: 3723-1086, 16m
  ublock-badware: 7443-149, 16m
  ublock-filters: 35263-242, 16m
  ublock-privacy: 667-6, 16m
  ublock-quick-fixes: 174-99, 16m
  ublock-unbreak: 2149-38, 16m
  urlhaus-1: 10825-0, 16m
filterset (user): [empty]
trustedset:
 added: [array of 1015 redacted]
switchRuleset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms
 maxAssetCacheWait: 160 ms
popupPanel:
 blocked: 13
 network:
  abtasty.com: 1
  aticdn.net: 1
  doubleclick.net: 1
  facil-iti.app: 1
  hubvisor.io: 1
  mediarithmics.com: 1
  outbrain.com: 1
  ownpage.fr: 1
  pbstck.com: 1
  poool.fr: 1
  sentry.io: 2
  teads.tv: 1
 extended:
  ##+js(no-fetch-if, static.adsafeprotected.com/favicon.ico method…
  ##+js(no-fetch-if, /^https:\/\/ads\.stickyadstv\.com\/$/ method:…
  ##+js(set-constant, __NEXT_DATA__.runtimeConfig.playerTF1.ads.en…
```
</details>

**Comment by gorhill** [comment] 2023-11-11 14:56
This filter fixes the issue:

    ||teads.tv^$3p,script,redirect-rule=noop.js,from=tf1info.fr

Should probably be fixed in AdGuard Français?

**Comment by gorhill** [comment] 2023-11-11 14:59
Since it's a high traffic site, I added a fix in quick-fixes list, we can remove when the fix is in the regional list.

**Comment by okiehsch** [comment] 2023-11-11 15:02
> cc who?

@alex-302 see https://github.com/uBlockOrigin/uAssets/issues/20608#issuecomment-1806837292

**Comment by mapx-** [comment] 2023-11-11 17:59
usually anti adblocking is fixed in AG base, so we can add it to our list

**Comment by Alex-302** [comment] 2023-11-12 21:59
Ok, will check today.

**Comment by Alex-302** [comment] 2023-11-13 09:53
I can't reproduce even with only Easylist.
Reproduced only when these two requests are redirected (uBO's filter) or unblocked:

```
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$domain=tf1info.fr
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$domain=tf1info.fr
```

also I can't reproduce with badfiltered two rules

```
||teads.tv^$script,3p,redirect-rule=noop.js,from=tf1info.fr,badfilter
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js:5,badfilter
```

So you can just block `gpt.js` on this site instead of redirecting.

**Closed** 2023-11-13 18:02 UTC
