### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by Cephee-Sensei** [uBlockOrigin/uAssets#13853] opened 2022-06-27 07:18 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Describe the issue

When trying to load a page tagged as NSFW on the mobile version of Reddit, the page is blurred, and no pop-up appears to unblur the page (the pop-up is the "this page looks better on the Reddit apps").

I have to turn-off uBO, reload the page to make the pop-up appears, click on it to unblur the page, then turn-on uBO. The problem won't come back before a week.

This problem doesn't happen on desktop version of Reddit.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 101
filterset (summary): 
  network: 183737
  cosmetic: 153422
  scriptlet: 36785
  html: 689
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 4d.1h.32m
    adguard-generic: 65027-5855, 4d.17h.52m
    adguard-spyware: 25799-1218, 4d.1h.30m
    adguard-annoyance: 54320-4670, 4d.1h.29m
    adguard-social: 17711-1646, 4d.1h.31m
    fanboy-thirdparty_social: 69-1, 11d.1h.22m
    fanboy-annoyance: 72684-61141, 7d.15h.1m
    fanboy-cookiemonster: 33643-15280, 7d.14h.58m
    fanboy-social: 23267-13682, 2d.3h.30m
    ublock-annoyances: 4497-7, 2d.3h.29m
    dpollock-0: 10375-1663, 7d.15h.9m
    adguard-spyware-url: 646-15, 2d.3h.31m
    block-lan: 43-0, 4d.1h.33m
    curben-phishing: 23735-3, 2d.3h.23m
    curben-pup: 219-0, 2d.3h.24m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32555-310, 13h.5m
    ublock-badware: 4219-4, 2d.3h.52m
    ublock-privacy: 230-1, 7d.15h.10m
    ublock-abuse: 75-0, 7d.15h.27m
    ublock-unbreak: 1829-0, 11h.12m
    adguard-mobile: 7860-201, 2d.3h.26m
    easylist: 67930-25303, 2d.3h.27m
    easyprivacy: 27253-10552, 4d.17h.53m
    urlhaus-1: 5056-0, 2d.3h.25m
    plowe-0: 3644-346, 2d.3h.58m
    FRA-0: 28912-3760, 2d.3h.28m
    ublock-quick-fixes: 227-2, 2d.3h.16m
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 628 ms (selfie)
  maxAssetCacheWait: 161558 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    reddit.com: 2
    amazon-adsystem.com: 1
    googletagservices.com: 1
    redditmedia.com: 4
    redditstatic.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment] 2022-06-27 08:46
Caused by `reddit.com##.XPromoBlockingModal` in Adguard Annoyances @Yuki2718

Account is needed, test page (nsfw) `https://www.reddit.com/r/gayporn/comments/vlg6bc/would_u_taste_me_in_locker_room_after_workout/` (tested with simulated mobile device)

**Comment by mapx-** [comment] 2022-06-27 10:20
already included here: `to be fixed by EasyList / EasyPrivacy / fanboy's annoyances / AdGuard Annoyances`

**Comment by Yuki2718** [comment] 2022-06-27 16:58
Maybe `reddit.com##.m-blurred:style(filter: none !important;)`

**Closed** 2022-06-27 17:02 UTC
Labels: to be fixed by EL / EP / FA / AGA
