### ISSUE TITLE
akasoggybunz.website

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#4453] opened 2018-12-29 16:39 UTC
### Describe the issue

anti-adblock alert

**Comment by okiehsch** [comment] 2018-12-29 20:13
I can't reproduce.

**Comment by mapx-** [comment] 2018-12-29 20:15
I got 3-4 hours ago the anti adb message (annoyance) but now .. not anymore

It's about (now broken ?)  
`http://akasoggybunz.website/wp-content/plugins/deadblocker/assets/js/blockadblock.js`

**Comment by okiehsch** [comment] 2018-12-29 20:19
I have seen that request but as you say right now there is nothing to fix, because it does not function properly.
The standard fix is to allow the request and use `generichide`.

**Comment by okiehsch** [comment] 2018-12-30 00:09
Now I can reproduce.

**Comment by okiehsch** [comment] 2018-12-30 00:12
Fixed in `annoyances`.

**Closed** 2018-12-30 00:11 UTC
