### ISSUE TITLE
slant.co

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#7950] opened 2020-09-25 08:08 UTC
### URL(s) where the issue occurs

`https://www.slant.co/topics/5335/~alternatives-to-github-for-open-source-projects#1`

### Describe the issue

Buttons "Free/Paid" have event listener with "mousedown" button.

Normal click generate badly redirection:

```js
d = `http://go.redirectingat.com/?id=${f.env.SKIM_LINKS_ID}&url=${s}&sref=${o}`, e.currentTarget.href = d), "false" === f.env.USE_AI_URLS && !p.getAttribute("data-no-lustre-popup")) return _.delay(() => new i({
    utmSource: f.view.utmSource,
    utmMedium: f.view.utmMedium,
    utmCampaign: f.view.utmCampaign
}), 1e3)
}
}, d = function(e) {
    return _.defer(function() {
        var t;
        if (t = e.dataset.href) return e.href = t
    })
},
```

### Screenshot(s)

![](https://user-images.githubusercontent.com/66819865/94242427-4ded9280-ff16-11ea-92e8-d2440ec13074.png) |
--- |

### Versions

- Browser/version: Firefox 81
- uBlock Origin version: uBO 1.29.2

### Settings

stock

### Notes

Maybe possible kill redrection? If no maybe needed is allow something like that:

`@@||go.redirectingat.com/?*www.slant.co*$doc`
`@@||go.skimresources.com/?*www.slant.co*$doc`

because both blocked by HOSTS `Peter Lowe’s Ad and tracking server list`.

**Comment by okiehsch** [comment] 2020-09-25 08:25
You get redirected to the strict block page.
You can get to your destination domain https://github.com/gorhill/uBlock/wiki/Strict-blocking#ability-to-parse-the-strict-blocked-url without issue as far as I can see.

**Comment by bug-rules** [comment] 2020-09-25 08:30
So use <kbd>tab</kbd> button and <kbd>enter</kbd> button, when redirect no exist.

Mousedown fail when use keyboard to open links, maybe touch screen is good workaround, but who sell me for free?

**Comment by okiehsch** [comment] 2020-09-25 08:37
I don't understand what you want to tell me. 
If someone has a working filter to disable the redirection **without** exception filters we will add them.
My comment was meant to clarify that the blocked page you see is by design.

**Comment by uBlock-user** [comment] 2020-09-25 08:40
test `slant.co##+js(ra, target|rel, .GetItHereButton-Price)`

**Comment by bug-rules** [comment] 2020-09-25 08:40
No works.

**Comment by mapx-** [comment] 2020-09-25 08:43
We could badfilter such filters
```
||redirectingat.com^$badfilter
||skimresources.com^$badfilter
```

**Comment by okiehsch** [comment] 2020-09-25 08:44
Why? It's by design behaviour.

**Comment by uBlock-user** [comment] 2020-09-25 08:45
`slant.co##+js(ra, target|rel, a[itemprop="url"][data-href])` works for me.

**Comment by okiehsch** [comment] 2020-09-25 08:47
Does not work on my end. Tried with Chromium and Firefox.

**Comment by mapx-** [comment] 2020-09-25 08:48
> `slant.co##+js(ra, target|rel, a[itemprop="url"][data-href])` works for me.

does not work, strict blocking again

**Comment by mapx-** [comment] 2020-09-25 08:48
> Why? It's by design behaviour.

I mean skimresources seems legit stuff

**Comment by uBlock-user** [comment] 2020-09-25 08:51
Race condition perhaps, user could just right click on the button and open in a new tab.

**Comment by lain566** [comment] 2020-09-25 08:53
Something like this might help too
https://github.com/uBlockOrigin/uBlock-issues/issues/760

**Comment by okiehsch** [comment] 2020-09-25 08:53
"Redirections.skimresources.com
If you've landed on this page, you may be wondering exactly what it's all about. We're Skimlinks — a service that helps online publishers earn money."

Don't we always strict block such services to make the user aware that they have clicked a tracking link?
@gorhill

**Comment by okiehsch** [comment] 2020-09-25 08:54
`slant.co##+js(aeld)` works but, well that's alittle bit broad.

**Comment by uBlock-user** [comment] 2020-09-25 09:00
`slant.co##+js(aeld, mousedown)` a bit less broad ?

**Comment by okiehsch** [comment] 2020-09-25 09:02
Yes much better but that could still break stuff.

**Comment by gorhill** [comment] 2020-09-25 12:21
> Don't we always strict block such services to make the user aware that they have clicked a tracking link?

Yes, these hostnames are in Peter Lowe's and I rather not second guess why they are there, this is the kind of stuff we want to enforce, and especially in the current case it reveals the tracking.

It's just fine to not fix this case, bringing forth the redirection to the user attention is by-design, and when redirection occurs, users are free to bypass the redirection using the information given to them in the document-blocked page through the [URL-parsing feature](https://github.com/gorhill/uBlock/wiki/Strict-blocking#ability-to-parse-the-strict-blocked-url).

**Comment by gorhill** [comment] 2020-09-25 12:33
@bug-rules 

> Maybe possible kill redrection? If no maybe needed is allow something like that:

This does not kill the redirection, this just hides it -- why would you want to hide redirections to all users?

**Closed** 2020-09-25 13:31 UTC
