### ISSUE TITLE
Ads reappear after blocking them because they get renamed

### ISSUE THREAD

**Issue by Elliander** [uBlockOrigin/uAssets#21611] opened 2023-12-28 00:33 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://www.amazon.com/

### Description

On multiple websites ads keep reappearing after I block them. For example, Amazon has an annoying full screen video ad for sports that I'd rather not have to see. They also have prime ads on the top and middle of the home page. (see screenshot section for example of what I see right now).

When I use the object picker I can see a code which corresponds with what I am trying to block and each time I refresh the page the ad comes back and the object picker shows a slightly different code. Here are the last 3 codes for one of the objects I want to block:

`##.pd_rd_r-5f1cd3b8-8ae7-4bd0-aab3-f9ba4b7f4187.pd_rd_w-4XopZ.pd_rd_wg-jzsPJ.celwidget.desktop-gateway-atf_7c2a8e11-21a0-46b5-a65e-d58b72a4d484.csm-placement-id-5af45aa7-715b-4ed8-811b-7f9befef5ba2.gw-col`

`##.pd_rd_r-5f8c5d7d-1445-4897-920d-f63da085a01f.pd_rd_w-0Lyr1.pd_rd_wg-WKIZh.celwidget.desktop-gateway-atf_7c2a8e11-21a0-46b5-a65e-d58b72a4d484.csm-placement-id-5af45aa7-715b-4ed8-811b-7f9befef5ba2.gw-col`

`##.pd_rd_r-9dd0b288-e511-414c-8ade-9869d0fafb9e.pd_rd_w-4AjfT.pd_rd_wg-iaaPL.celwidget.desktop-gateway-atf_7c2a8e11-21a0-46b5-a65e-d58b72a4d484.csm-placement-id-5af45aa7-715b-4ed8-811b-7f9befef5ba2.gw-col`

And referring to the banner on the top these are the last 4 codes I get trying to block those:

```
||m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/615FVBUkFKL._SX3000_.jpg

||m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/710Q61rv7mL._SX3000_.jpg

||m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71laC9yrhtL._SX3000_.jpg

||m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/51IKiHnvoRL._SX1500_.jpg
```

As you can see, again, the names are all slightly different. If you copy and paste these specific codes in a web browser you can actually load the jpeg images. For example, these two links go to the exact same image:

m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/710Q61rv7mL._SX3000_.jpg

m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/51IKiHnvoRL._SX1500_.jpg

This should at least prove that Amazon is using rotating codes in order to circumvent adblockers. There DOES seem to be a limited number of these so if I keep redoing it eventually on a page refresh they are all gone, but they seem to change the names periodically so they then come back or only half come back. That's probably why the stupid sports ad taking the full page isn't currently back, but it'll come back eventually.

That's not the only website I am having this issue with. This is just the easiest example I can provide because it's a commonly known and used website with easy to show links. I can provide other speciifc examples as well though.

This is actually a continuation of this case:

https://github.com/uBlockOrigin/uAssets/issues/21517

However it was closed because I was somehow expected to respond on Christmas weekend so now I am forced to start over. Please understand that I may be unable to immediately respond on new years either and would rather not have to keep creating cases over this. Give me until at least after the holidays before closing the case if you need information from me.

If for whatevr reason uBlock cannot deal with these kinds of ads I'd request to know a workable alternative. I didn't have these problems when I was using Adblock plus (well, with few exceptions) but they started pushing their own popup ads so I uninstalled and replaced with uBlock based on frequent recommendations.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![amazon_home_page](https://github.com/uBlockOrigin/uAssets/assets/15022396/2982abf1-4b98-46af-b6e5-a06787f8e116)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.54.0
Chromium: 92
filterset (summary):
 network: 105728
 cosmetic: 44321
 scriptlet: 19828
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 131-58, never
  easylist: 76438-15, 2h.50m
  easyprivacy: 33166-65, 2h.50m
  plowe-0: 3782-1152, 6d.14h.55m
  ublock-badware: 7555-137, 2h.50m
  ublock-filters: 36557-297, 2h.50m
  ublock-privacy: 952-12, 6d.14h.55m
  ublock-quick-fixes: 128-4, 2h.50m
  ublock-unbreak: 2176-32, 2h.50m
  urlhaus-1: 10910-0, 7h.51m
filterset (user): [array of 131 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 25690 ms (selfie)
 maxAssetCacheWait: 22591 ms

```
</details>

**Comment by stephenhawk8054** [comment] 2023-12-28 00:34
Just continue on the old thread. We all see it, and we will re-open it if needed. No need to create duplicated issue.

**Comment by gorhill** [comment] 2023-12-28 00:51
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/21517

**Closed by gorhill** 2023-12-28 00:51 UTC
