### ISSUE TITLE
deezer.com: ads

### ISSUE THREAD

**Issue by vivekbibs** [uBlockOrigin/uAssets#16531] opened 2023-01-28 13:47 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deezer.com/fr/profile/22110492/loved`

### Category

ads

### Description

audio ads once every  3 songs played

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 102875
  cosmetic: 47365
  scriptlet: 16967
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 29995-28, 1d.13h.42m
    easylist: 61143-89, 5d.20h.58m
    easyprivacy: 30950-1495, 5d.20h.57m
    plowe-0: 3667-924, 5d.20h.56m
    ublock-abuse: 77-1, 5d.20h.53m
    ublock-badware: 4169-137, 1d.17h.11m
    ublock-filters: 31709-238, 1d.17h.10m
    ublock-privacy: 258-1, 5d.20h.49m
    ublock-quick-fixes: 506-20, 22h.47m
    ublock-unbreak: 1869-49, 1d.17h.9m
    urlhaus-1: 6554-0, 2h.4m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 926 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 6
  no-popups: true
  blockedDetails: 
    deezer.com: 2
    googletagmanager.com: 1
    sentry.io: 3
```
</details>

**Comment by garry-ut99** [comment] 2023-01-28 13:59
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/13571.

> vivekbibs : `ublock-filters: 31709-238, 1d.17h.10m`

The ads have been already fixed 17 hours ago, update your filters and try again.

**Closed** 2023-01-28 13:59 UTC

**Comment by vivekbibs** [comment] 2023-01-28 21:07
i did update my filters. the problem is still present. sorry if im mistaken, im not that skilled with computers lol

**Comment by mapx-** [comment] 2023-01-28 21:10
open uBO logger, take the steps to get again the ads, go back to the logger and post here what `media` requests you see there

**Comment by garry-ut99** [comment] 2023-01-29 16:30
It might be still `media` but with a different path, or as it has turned out, it might be a different type than `media`: https://github.com/uBlockOrigin/uAssets/issues/13571#issuecomment-1407515365, so better if he paste all requests from the logger.

**Comment by vivekbibs** [comment] 2023-01-29 17:36
<details><summary>Logger output</summary>

```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/3722b6f876813ecf4bdf75443bf02da1/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/a2f66f08468fb9897019e82ffb7a5fcb/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/adc9dbd489510fd9d38ac840672ba469/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/56bdb7a86a27fadb96332c0c8f1b8e81/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/708bc70bf794634be324a77bcbce586f/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/1fe2d9357a77ac4cfc192016783ecac7/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/9b0db563c287eb798c578e2e664dc1f8/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/0433e2a0abc3fdbe27e352b1eeeb50f0/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/79ba3cd515942d1dc62f49f859a374fd/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/49719b05c94d80af169bd52cd885ef9a/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/eea35658898e296aa8b5d817827e6aaf/40x40-000000-80-0-0.jpg
```
```
+25
www.deezer.com
0,3
xhr
https://e-cdns-images.dzcdn.net/images/cover/7ce6b8452fae425557067db6e6a1cad5/40x40-000000-80-0-0.jpg
```
```
+25
ogs.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+23
||deezer.com/ajax/gw-light.php?method=triton.pixeltracking&
--
www.deezer.com
0,1
xhr
https://www.deezer.com/ajax/gw-light.php?method=triton.pixelTracking&input=3&api_version=1.0&api_token=uT2HA86Js6bg7G-2TMefOeA29z6AzmUw&cid=586580406
```
```
+23
www.deezer.com
0,3
xhr
https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/en_UK_Unlimited_Skips.mp3
```
```
+14
ogs.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+14
ogs.google.com
3,3
script
https://www.gstatic.com/_/mss/boq-one-google/_/js/k=boq-one-google.OneGoogleWidgetUi.fr.y8yzIeodyDE.es5.O/ck=boq-one-google.OneGoogleWidgetUi.Lk0SWcHCbM8.L.B1.O/am=oNkAAEA/d=1/exm=A7fCU,BVgquf,COQbmf,EEDORb,EFQ78c,GkRiKb,IZT63,JNoxi,KG2eXe,KUM7Z,L1AAkb,LEikZe,MI6k7c,MdUzUe,Mlhmy,MpJwZc,NwH0H,O1Gjze,O6y8ed,OTA3Ae,OmgaI,PrPYRd,QIhFr,RMhBfe,SdcwHb,SpsfSb,U0aPgd,UUJqVe,Uas9Hd,Ulmmrd,V3dDOb,VwDzFe,XVMNvd,Z5uLle,ZfAoz,ZwDk9d,_b,_r,_tp,aDfbSd,aW3pY,aurFic,bm51tf,byfTOb,e5qFLc,fKUV3e,gychg,hKSk3e,hc6Ubd,kWgXee,kjKdXe,lKZxSd,lazG7b,lsPsHb,lsjVmc,lwddkf,mI3LFb,mdR7q,n73qwf,ovKuLd,pjICDe,pw70Gc,s39S4,w9hDv,wmnU7d,ws9Tlc,xQtZb,xUdipf,yDVVkb,zbML3c,zr1jrb/excm=_b,_r,_tp,appwidgetauthview/ed=1/wt=2/rs=AM-SdHtaoUtzUdW-8Wcs-pIcNMxV0xfZMw/ee=cEt90b:ws9Tlc;QGR0gd:Mlhmy;uY49fb:COQbmf;yxTchf:KUM7Z;qddgKe:xQtZb;dIoSBb:SpsfSb;EmZ2Bf:zr1jrb;xqZiqf:wmnU7d;zxnPse:GkRiKb;EVNhjf:pw70Gc;NSEoX:lazG7b;JsbNhc:Xd8iUd;oGtAuc:sOXFj;eBAeSb:zbML3c;Pjplud:EEDORb;io8t5d:yDVVkb;Oj465e:KG2eXe;Erl4fe:FloWmf;ul9GGd:VDovNc;sP4Vbe:VwDzFe;kMFpHd:OTA3Ae;NPKaK:SdcwHb;pXdRYb:MdUzUe;nAFL3:s39S4;iFQyKf:QIhFr;SNUn3:ZwDk9d;LBgRLc:SdcwHb;wR5FRb:O1Gjze/m=Wt6vjf,hhhU8,FCpbqb,WhJNk
```
```
+14
ogs.google.com
3,3
script
https://www.gstatic.com/_/mss/boq-one-google/_/js/k=boq-one-google.OneGoogleWidgetUi.fr.y8yzIeodyDE.es5.O/ck=boq-one-google.OneGoogleWidgetUi.Lk0SWcHCbM8.L.B1.O/am=oNkAAEA/d=1/exm=A7fCU,BVgquf,COQbmf,EEDORb,EFQ78c,GkRiKb,IZT63,JNoxi,KG2eXe,KUM7Z,L1AAkb,LEikZe,MI6k7c,MdUzUe,Mlhmy,MpJwZc,NwH0H,O1Gjze,O6y8ed,OTA3Ae,OmgaI,PrPYRd,QIhFr,RMhBfe,SdcwHb,SpsfSb,U0aPgd,UUJqVe,Uas9Hd,Ulmmrd,V3dDOb,VwDzFe,XVMNvd,Z5uLle,ZfAoz,ZwDk9d,_b,_r,_tp,aDfbSd,aW3pY,aurFic,byfTOb,e5qFLc,fKUV3e,gychg,hKSk3e,hc6Ubd,kWgXee,kjKdXe,lKZxSd,lazG7b,lsPsHb,lsjVmc,lwddkf,mI3LFb,mdR7q,n73qwf,ovKuLd,pjICDe,pw70Gc,s39S4,w9hDv,wmnU7d,ws9Tlc,xQtZb,xUdipf,yDVVkb,zbML3c,zr1jrb/excm=_b,_r,_tp,appwidgetauthview/ed=1/wt=2/rs=AM-SdHtaoUtzUdW-8Wcs-pIcNMxV0xfZMw/ee=cEt90b:ws9Tlc;QGR0gd:Mlhmy;uY49fb:COQbmf;yxTchf:KUM7Z;qddgKe:xQtZb;dIoSBb:SpsfSb;EmZ2Bf:zr1jrb;xqZiqf:wmnU7d;zxnPse:GkRiKb;EVNhjf:pw70Gc;NSEoX:lazG7b;JsbNhc:Xd8iUd;oGtAuc:sOXFj;eBAeSb:zbML3c;Pjplud:EEDORb;io8t5d:yDVVkb;Oj465e:KG2eXe;Erl4fe:FloWmf;ul9GGd:VDovNc;sP4Vbe:VwDzFe;kMFpHd:OTA3Ae;NPKaK:SdcwHb;pXdRYb:MdUzUe;nAFL3:s39S4;iFQyKf:QIhFr;SNUn3:ZwDk9d;LBgRLc:SdcwHb;wR5FRb:O1Gjze/m=bm51tf
```
```
+14
ogs.google.com
3,3
font
https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2
```
```
+14
ogs.google.com
3,3
script
https://www.gstatic.com/_/mss/boq-one-google/_/js/k=boq-one-google.OneGoogleWidgetUi.fr.y8yzIeodyDE.es5.O/ck=boq-one-google.OneGoogleWidgetUi.Lk0SWcHCbM8.L.B1.O/am=oNkAAEA/d=1/exm=_b,_r,_tp/excm=_b,_r,_tp,appwidgetauthview/ed=1/wt=2/rs=AM-SdHtaoUtzUdW-8Wcs-pIcNMxV0xfZMw/ee=cEt90b:ws9Tlc;QGR0gd:Mlhmy;uY49fb:COQbmf;yxTchf:KUM7Z;qddgKe:xQtZb;dIoSBb:SpsfSb;EmZ2Bf:zr1jrb;xqZiqf:wmnU7d;zxnPse:GkRiKb;EVNhjf:pw70Gc;NSEoX:lazG7b;JsbNhc:Xd8iUd;oGtAuc:sOXFj;eBAeSb:zbML3c;Pjplud:EEDORb;io8t5d:yDVVkb;Oj465e:KG2eXe;Erl4fe:FloWmf;ul9GGd:VDovNc;sP4Vbe:VwDzFe;kMFpHd:OTA3Ae;NPKaK:SdcwHb;pXdRYb:MdUzUe;nAFL3:s39S4;iFQyKf:QIhFr;SNUn3:ZwDk9d;LBgRLc:SdcwHb;wR5FRb:O1Gjze/m=n73qwf,ws9Tlc,GkRiKb,e5qFLc,IZT63,UUJqVe,O1Gjze,byfTOb,lsjVmc,xUdipf,OTA3Ae,COQbmf,fKUV3e,aurFic,U0aPgd,ZwDk9d,V3dDOb,mI3LFb,O6y8ed,PrPYRd,MpJwZc,LEikZe,NwH0H,OmgaI,lazG7b,XVMNvd,L1AAkb,KUM7Z,Mlhmy,lKZxSd,s39S4,lwddkf,gychg,w9hDv,EEDORb,RMhBfe,SdcwHb,aW3pY,pw70Gc,EFQ78c,Ulmmrd,ZfAoz,mdR7q,wmnU7d,Z5uLle,xQtZb,JNoxi,kWgXee,MI6k7c,kjKdXe,BVgquf,QIhFr,ovKuLd,hKSk3e,yDVVkb,hc6Ubd,SpsfSb,KG2eXe,MdUzUe,VwDzFe,zbML3c,zr1jrb,lsPsHb,A7fCU,aDfbSd,Uas9Hd,pjICDe
```
```
+14
ogs.google.com
3,3
image
https://ssl.gstatic.com/gb/images/sprites/p_1x_4f8a89234111.png
```
```
+14
ogs.google.com
3,3
image
https://lh3.googleusercontent.com/ogw/AAEL6sjZUBoDyWSJlOzMRsJPaGXKp4ABnzencmVvmU3v=s128-b16-cc-rp-mo
```
```
+14
ogs.google.com
3,3
script
https://www.gstatic.com/_/mss/boq-one-google/_/js/k=boq-one-google.OneGoogleWidgetUi.fr.y8yzIeodyDE.es5.O/am=oNkAAEA/d=1/excm=_b,_r,_tp,appwidgetauthview/ed=1/dg=0/wt=2/rs=AM-SdHtAj6GdM9Btz6KslIJ36Vuhl4TMgg/m=_b,_tp,_r
```
```
+10
www.google.com
3,1
image
https://www.google.com/logos/2023/boba/rc3/ui-sprite.png
```
```
+10
www.google.com
3,3
font
https://fonts.gstatic.com/s/itim/v10/0nknC9ziJOYe8ANAkA.woff2
```
```
+10
www.google.com
3,3
css
https://fonts.googleapis.com/css?family=Itim
```
```
+10
www.google.com
3,1
image
https://www.google.com/logos/2023/boba/rc3/preclick-sprite.png
```
```
+10
www.google.com
3,3
script
https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js
```
```
+10
www.google.com
3,1
xhr
https://www.google.com/logos/2023/boba/rc3/messages.fr.nocache.json
```
```
+10
www.google.com
3,1
xhr
https://www.google.com/async/ddllog?async=_fmt%3Ajspb%2Cdoodle%3A253312689%2Cslot%3A0%2Ctype%3A3%2Ccta%3A1%2Cntp%3A1
```
```
+10
www.google.com
3,1
image
https://www.google.com/logos/2023/boba/rc3/cta.png
```
```
+10
www.google.com
3,1
script
https://www.google.com/logos/2023/boba/rc3/boba.js
```
```
+0
www.deezer.com
0,3
xhr
https://cdnt-proxy-3.dzcdn.net/media/1/cc6ce4892309689b0275a208dc8c3f9127b26c809246b5e23067a7e37fed9f486b58b33fa80d354c710adb2698c61b700723fec25a85020df5bef5e07ea09b48b7932288e3c32a05cb615d4eec42e012?hdnea=exp=1675085524~acl=/media/1/cc6ce4892309689b0275a208dc8c3f9127b26c809246b5e23067a7e37fed9f486b58b33fa80d354c710adb2698c61b700723fec25a85020df5bef5e07ea09b48b7932288e3c32a05cb615d4eec42e012*~data=user_id=22110492~hmac=d51c990f0b12a8edfb34fb02f6c497c96915e65cfc0472253cf095a7236bb653#8df8d48c-9937-44e9-b672-3c79116ab84c
```
```
+0
www.deezer.com
0,1
xhr
https://media.deezer.com/v1/get_url
```
</details>
