### ISSUE TITLE
egy.best shows Anti Ad-block within player.

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#6019] opened 2019-07-29 17:38 UTC
### URL(s) where the issue occurs

`https://www.egy.best/movie/avengers-endgame-2019/?ref=home-new`

### Describe the issue

whenever I try to open player it shows ad-block targeted message that written in Russian and prevent me from playing the video, you will see it if you try to press the play button, also I have to click multiple times to get to this message.

### Screenshot(s)

https://imgur.com/LBeUSq5

### Versions

- Browser/version: Google chrome Version 75.0.3770.142 (Official Build) (64-bit)
- uBlock Origin version: v1.21.6

**Comment by krystian3w** [comment] 2019-07-29 18:38
https://github.com/NanoAdblocker/NanoFilters/issues/376

**Comment by mapx-** [comment] 2019-11-12 09:46
dead site

**Comment by lain566** [comment] 2019-11-12 10:35
The site is not dead, it has only changed domain, they may use it again as in the past https://github.com/uBlockOrigin/uAssets/issues/2280#issuecomment-512922459

**Comment by mapx-** [comment] 2019-11-12 10:37
Can you reproduce any of the issues on the new sites ? for example:
`https://best.egbest2.com/`

**Comment by lain566** [comment] 2019-11-12 10:41
Everything seems to work fine for me

**Comment by Iaycomand** [comment] 2019-11-12 10:44
It still detect my ublock origin

**Comment by lain566** [comment] 2019-11-12 10:51
Do you mean the player?
if you are lucky, the popup window will close after 1 second, and you won't get the anti adblock message.

**Comment by Iaycomand** [comment] 2019-11-12 11:04
> Do you mean the player?
> if you are lucky, the popup window will close after 1 second, and you won't get the anti adblock message. That's the best I can do.

I meant the site itself it shows a directed message and hide it's content if l don't turn the extension off.

**Comment by mapx-** [comment] 2019-11-12 11:09
provide the link
`https://www.egy.best` => redirects to some crapware for me

**Comment by Iaycomand** [comment] 2019-11-12 11:13
> provide the link
> `https://www.egy.best` => redirects to some crapware for me

Try this domain instead:
> `https://poly.egybest.me/`

**Comment by Iaycomand** [comment] 2019-11-12 11:14
I noticed that they has changed their domian consistently.

**Comment by lain566** [comment] 2019-11-12 11:18
> I meant the site itself it shows a directed message and hide it's content if l don't turn the extension off.

What is that message? If I disable uBO, the page is the same

**Comment by Iaycomand** [comment] 2019-11-12 11:21
Sorry, l can't provide any screenshots at current moment, will do as soon as l get home.

**Comment by mapx-** [comment] 2019-11-12 11:27
`poly.egybest.me` redirects to `http://www.greatdexchange.com/jump/next.php?r=2260331&ref=egy.best` on my side

**Comment by lain566** [comment] 2019-11-12 11:31
@mapx- I am using a VPN, Mexico location

**Comment by Iaycomand** [comment] 2019-11-12 11:36
Kindly try this link: `https://tena.egybest.cz/` @mapx-

**Comment by mapx-** [comment] 2019-11-12 11:39
yes, indeed ... I used now a swedish vpn and I got it working

for example `http://poly.egybest.me/movie/danger-close-2019/?ref=home-new` still same crap popups / anti adb

![image](https://user-images.githubusercontent.com/10303732/68668890-80cea800-0549-11ea-8eed-f38b350a7d04.png)

**Comment by mapx-** [comment] 2019-11-12 11:41
same for `egybest.cz`

**Comment by lain566** [comment] 2019-11-12 11:45
I don't get anti adblock message

![Anotación 2019-11-12 124338](https://user-images.githubusercontent.com/27441315/68669199-4285b880-054a-11ea-969f-b1fa6ae3d1b9.png)

**Comment by mapx-** [comment] 2019-11-12 11:56
@lain566 try this:
`vidstream.to/embed/9YkEIaYF5Y/?vclid=420c951a020022931494f05c2d4af159e9f8594b91668adc4181e8a9SVVVXrPYVXViVXKGTEXVBNSSXSzOpfVoaeXiXVXPQcVXViVXStGoaeSBQsVXiXVXWTSCXViVXfGjSelmYISSTHSDsSistLVXVL`

**Comment by mapx-** [comment] 2019-11-12 11:57
3-4 clicks => popups then the anti adb msg

**Comment by lain566** [comment] 2019-11-12 12:03
Yes, It is what I said before https://github.com/uBlockOrigin/uAssets/issues/6019#issuecomment-552841535

I'm lucky that the popup window closes 1 second later for me

![Anotación 2019-11-12 125827](https://user-images.githubusercontent.com/27441315/68670038-36025f80-054c-11ea-8cf9-7c51d4abd432.png)

**Comment by mapx-** [comment] 2019-11-12 12:04
it seems they are testing if the `&ref=egy.best` popups windows are opened

**Comment by okiehsch** [comment] 2019-11-12 21:47
Probably similar to https://github.com/NanoAdblocker/NanoFilters/issues/377#issuecomment-514010862

**Comment by prateekrastogi** [comment] 2020-01-26 14:59
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by Iaycomand** [comment] 2020-03-05 17:13
the site became responsive and having no issue with it `https://feta.egybest.cheap/` except for the russian server itself still detect the adblocker `https://vidstream.to/`
![image](https://user-images.githubusercontent.com/39984795/76006625-6f087a80-5f15-11ea-9f29-21dd8234dcc7.png)

**Comment by krystian3w** [comment] 2020-03-05 17:52
Need allow pop-ups or new scriplets.

**Comment by lain566** [comment] 2020-03-06 10:50
Actually this issue is fixed with an **uBlock-user** scriptlet, I mean block popups and play the video without any anti-adblock warning, but I don't think Gorhill is going to add it.

**Comment by mapx-** [comment] 2020-03-06 12:20
> Actually this issue is fixed with an **uBlock-user** scriptlet, I mean block popups and play the video without any anti-adblock warning, but I don't think Gorhill is going to add it.

You could try to propose it in the internal discussions, for now we have no other chance to fix such issues.
but .. where is fixed ? or are you saying is fixable using some scriptlet (add-iframe maybe ?)

**Comment by lain566** [comment] 2020-03-06 12:28
> or are you saying is fixable using some scriptlet (add-iframe maybe ?)

Yes, I wanted to say that it is fixable with that scriptlet `add-iframe`

**Comment by uBlock-user** [comment] 2020-03-06 12:29
> Actually this issue is fixed with an uBlock-user scriptlet

Which one ?

**Comment by uBlock-user** [comment] 2020-03-06 12:29
> with that scriptlet add-iframe

How many iframes did you had to create for the fix ?

**Comment by lain566** [comment] 2020-03-06 12:30
only one

**Comment by lain566** [comment] 2020-03-06 12:34
Tested with these filters, works for me

```
vidstream.*##+js(set, open, trueFunc)
vidstream.*##+js(add-iframe, 1, id, /cv.php)
```

Test link
`https://vidstream.kim/v/C7w7ZC6344`

**Comment by uBlock-user** [comment] 2020-03-06 12:40
Speaking of add-iframe, it also fixes the [aeonax.com](https://github.com/uBlock-user/Anti-Circumvention-Filterlist/blob/master/acf.txt#L60) anti-adblock issue without having to resort to creating an exception filter for `googleadsyndication.com`

**Comment by Iaycomand** [comment] 2020-03-06 14:38
I just hope that there's a fix within ublock origin without any additional manual scripts? unfortunately I'm a regular user :0

**Comment by mapx-** [comment] 2020-03-06 15:04
It's easy:
click the gear button (going in advanced settings):
![image](https://user-images.githubusercontent.com/10303732/76095044-e563b600-5fc3-11ea-8863-e7955a881774.png)

on the last row add the url like this:
`userResourcesLocation` `https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.txt`

![image](https://user-images.githubusercontent.com/10303732/76095175-21971680-5fc4-11ea-9c62-b93b6e3695ea.png)

Now add the 2 filters above to your "my filters"

**Comment by Iaycomand** [comment] 2020-03-06 15:53
I add the script above but the site load html after that for some reason
![image](https://user-images.githubusercontent.com/39984795/76099128-53fc4000-5fd3-11ea-8b1b-f361c0c93565.png)

**Comment by Iaycomand** [comment] 2020-03-06 15:58
but unironically that script fixed some other site issues, thanks! I used that method before but with a link related to "nanodefender.txt" instead of "scriptlet.txt" hopefully it will be more efficient.

**Comment by Iaycomand** [comment] 2020-03-06 16:00
the test failed for me after I added the two filters did I missed anything?
![image](https://user-images.githubusercontent.com/39984795/76099794-54490b00-5fd4-11ea-9841-f8f687c86fbf.png)
![image](https://user-images.githubusercontent.com/39984795/76099837-65921780-5fd4-11ea-9e50-31b9337b3ce5.png)

**Comment by mapx-** [comment] 2020-03-06 16:02
use the links here:
![image](https://user-images.githubusercontent.com/10303732/76099969-3a0b2f00-5fcc-11ea-820b-85bea03a7b11.png)

**Comment by Iaycomand** [comment] 2020-03-06 16:19
the html only issue solve itself, I got no issue with downloading now, but what about live streaming?

**Comment by mapx-** [comment] 2020-03-06 16:23
You mean clicking the blue buttons does not work for you ?
The vidstream tab should open, wait until the real player is ON

**Comment by lain566** [comment] 2020-03-06 16:28
These filters are for embedded video, 
```
egybest.*##+js(set, open, trueFunc)
egybest.*##+js(add-iframe, 1, id, /cv.php)
```

The problem is that `##+js(set, open, trueFunc)`  it's too generic and breaks those buttons.

**Comment by Iaycomand** [comment] 2020-03-06 16:50
both blue buttons and embedded video still detect adblocker even after I add filters above

**Comment by krystian3w** [comment] 2020-03-06 16:54
Wait 30 seconds?

Or disable non default lists?

**Comment by Iaycomand** [comment] 2020-03-06 17:14
uhhh I don't get "non default lists" how I achieve that?

**Comment by krystian3w** [comment] 2020-03-06 17:21
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists and disable any non-stock (non-default).

**Comment by Iaycomand** [comment] 2020-03-06 17:56
Done, but still didn't do the trick for me :(
![image](https://user-images.githubusercontent.com/39984795/76109141-8d897700-5fe4-11ea-937f-378ef51585d7.png)

**Comment by Iaycomand** [comment] 2020-03-06 17:59
But the external links get resolved that's a progress 👍 
still the embedded video detects adblocker

**Comment by Iaycomand** [comment] 2020-03-21 18:43
update: I made a default resitting for ublock and resubscribe to nano filters; that cause the embedded video to work and having no issues now except that russian server open a new tap but closes at instant which is still much better than the original issue.

**Comment by lain566** [comment] 2020-04-01 11:54
This has been fixed in uBO dev version, the filter I added doesn't work with the uBO stable version.

**Comment by gwarser** [comment] 2020-05-03 18:43
Download is broken? https://www.reddit.com/r/uBlockOrigin/comments/gcfsaf/ublockorigin_does_not_work_with_a_sitek_with_a/

**Comment by lain566** [comment] 2020-05-03 19:33
Fixed.

**Comment by gwarser** [comment] 2020-06-06 08:54
https://www.reddit.com/r/uBlockOrigin/comments/gwnk00/anti_adblock/fsx1eun/

**Comment by krystian3w** [comment] 2020-06-06 11:47
Still works in Firefox.

**Comment by lain566** [comment] 2020-06-06 12:22
@gwarser Does not work due to this directive `frame-ancestors 'none'`



![Anotación 2020-06-05 105459](https://user-images.githubusercontent.com/27441315/83943832-47b89680-a7ff-11ea-9403-c8acc189d591.png)


Do you think something can be done?

**Comment by gwarser** [comment] 2020-06-06 13:58
AAhhh, that's why AdGuard uses `<object>`.

**Comment by krystian3w** [comment] 2020-06-06 14:02
https://www.w3schools.com/tags/tag_embed.asp - if website detect fake iframe or object?

**Comment by gwarser** [comment] 2020-06-06 14:12
One more https://www.reddit.com/r/uBlockOrigin/comments/gxq3he/problem_with_specific_website/

**Comment by lain566** [comment] 2020-06-06 14:55
So the new `window.open-defuser` enhancement needs to be updated `iframe` to `embed`
@gorhill What do you think about it?

**Comment by llacb47** [comment] 2020-06-06 15:04
See: 
https://github.com/NanoAdblocker/NanoFilters/issues/376 https://github.com/NanoAdblocker/NanoFilters/issues/377
List of domains: https://github.com/NanoMeow/QuickReports/issues/2511

**Comment by gorhill** [comment] 2020-06-06 15:16
> AAhhh, that's why AdGuard uses `<embed>`.

I was not aware `embed` creates a separate window context.

**Comment by AdamWr** [comment] 2020-06-06 15:24
It seems that it doesn't (or at least it's not possible to use `contentWindow` from what I can see), but `object` tag do and it seems that it would be better to use it instead of `embed` tag.
https://github.com/AdguardTeam/AdguardFilters/commit/b6c42cad817b9a0bb53d68a42dcaefcf528a0e93

**Comment by gorhill** [comment] 2020-06-06 15:55
Right, I couldn't make it work with `embed`. However, even if using `object`, I feel it's just a matter of short time before the site adds a CSP directive `object-src 'none'`.

**Comment by uBlock-user** [comment] 2020-06-06 16:24
>  before the site adds a CSP directive object-src 'none'.

How about a procedural action operator 'create' ?

**Comment by gorhill** [comment] 2020-06-06 17:10
Did the site just went back to not forbid `iframe`?

**Comment by krystian3w** [comment] 2020-06-26 19:18
Still problem on Chrome: https://github.com/NanoMeow/QuickReports/issues/4197

**Comment by ghajini** [comment] 2020-07-30 15:53
`neel.egybest.asia/movie/deep-blue-sea-3-2020/#download`
![Screenshot (286)](https://user-images.githubusercontent.com/20338483/88944871-e8c94800-d2aa-11ea-85f1-5fd76248b638.png)


Antiadblock
opera browser
ublock origin 1.28.5b9

**Comment by krystian3w** [comment] 2020-07-30 15:56
Opera = chromium = CSP restrictions...

**Comment by Iaycomand** [comment] 2020-08-01 09:27
I think the moderators of this site following ublock github submissions 🤷

**Comment by krystian3w** [comment] 2020-08-01 15:36
`Egy.best` mods? IDTS...

**Comment by minanagehsalalma** [comment] 2020-08-10 21:46
> I think the moderators of this site following ublock github submissions 🤷 

there is one way to found out  [chatzy.com online private chat room](https://us20.chatzy.com/17923140142461)

@llacb47 theirs works perfectly also about the vid stream site you can click watch first then download then it will go back to the first page again and the download button will work just fine 

@mapx-  what do you think ? also it still detects the ublock.

**Comment by minanagehsalalma** [comment] 2020-08-10 21:51
> I think the moderators of this site following ublock github submissions 🤷

@Iaycomand lol i think we caught them 

https://forum.adguard.com/index.php?members/egybest.26321/

**Comment by llacb47** [comment] 2020-08-16 17:25
https://github.com/gorhill/uBlock/commit/071b15cf9436dc5caacb9552856ca3f881fcb1b3

**Closed** 2020-08-24 07:15 UTC
