### ISSUE TITLE
fmovies.to: detection

### ISSUE THREAD

**Issue by thebrowncoatali** [uBlockOrigin/uAssets#10605] opened 2021-11-25 18:13 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than three (3) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists ([here is how to do this](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://fmovies.to/`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/75099123/143486840-a41c1f3d-1a67-4952-927e-4428d7c46119.png)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/75099123/143486820-ae4d4a08-7524-4acf-8da2-ebbe2526e90f.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 79022
  cosmetic: 39228
  scriptlet: 16172
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30298-27, 2d.23h.19m
    ublock-badware: 3425-1, 2d.23h.16m
    ublock-privacy: 182-0, 2d.2h.1m
    ublock-abuse: 70-0, 2d.1h.59m
    ublock-unbreak: 1701-0, 2d.1h.57m
    easylist: 60994-541, 2d.1h.53m
    easyprivacy: 26306-475, 2d.1h.55m
    urlhaus-1: 9538-0, 18h.49m
    plowe-0: 3699-3, 1d.16h.45m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 243
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment] 2021-11-25 18:19
Duplicate of #10547

**Closed by uBlock-user** 2021-11-25 18:19 UTC
