### ISSUE TITLE
mackolik.com: breakage

### ISSUE THREAD

**Issue by asd674** [uBlockOrigin/uAssets#17464] opened 2023-04-06 16:42 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mackolik.com/canli-sonuclar`

### Category

breakage

### Description

When ublock origin is enabled on the Maçkolik site, the click places on the site do not work.
Whenever I disable the plugin the problem goes away.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 91013
  cosmetic: 48775
  scriptlet: 18837
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 12152-11, 1d.8h.4m
    easylist: 65121-64, 1d.8h.27m
    easyprivacy: 30787-1182, 1d.8h.28m
    plowe-0: 3751-937, 9d.19h.33m
    ublock-abuse: 78-0, 12d.5h.10m
    ublock-badware: 6244-124, 1d.8h.3m
    ublock-filters: 33275-104, 1d.8h.6m
    ublock-privacy: 293-2, 12d.4h.41m
    ublock-quick-fixes: 471-16, 3h.11m
    ublock-unbreak: 1947-42, 1d.8h.5m
    urlhaus-1: 7165-0, 3h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 241 ms (selfie)
  maxAssetCacheWait: 116 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    mackolik.com: 1
    admost.mobi: 3
    doubleclick.net: 2
    gemius.pl: 1
    google.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
    nesine.com: 1
    twitter.com: 1
```
</details>

**Comment by gorhill** [comment] 2023-04-06 17:36
What does "click places" mean? Click where exactly?

**Comment by asd674** [comment] 2023-04-06 20:06
![D59ABE04-FE80-481F-8733-55B33883C0D8](https://user-images.githubusercontent.com/88928376/230483243-cb4a1c6c-6024-438f-a94c-e11d4bc3f577.jpeg)
for example when I try to click here nothing happens. It fixes itself when I close the plugin.

**Comment by gorhill** [comment] 2023-04-06 20:59
Can't reproduce, when I click on a score, a new related tab opens. Maybe another extension is closing that new tab.

**Comment by mapx-** [comment] 2023-04-07 08:47
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Closed by mapx-** 2023-04-07 08:47 UTC
Labels: unable to reproduce, Waiting for feedback
