### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Shaggyndaisy** [uBlockOrigin/uAssets#19189] opened 2023-07-27 18:48 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=2uzgv3Oz2gw&list=RDMY7SFFEamYI&index=14`

### Category

ads

### Description

Ads lack video but still play audio unless the ad is usually skippable the ad cannot be skipped. Clicking on the advertisement doesn't pause it, which typically is what would happen when clicking on the ad's center. This is consistent across all/most youtube videos as of 7/27/2023. I have not seen any other reports of this happening yet.

### Other extensions used

Norton Safe Web (Not an ad blocker)

### Screenshot(s)

<details>
<summary>Screenshot of ad</summary>

![But The Earth Was Determined  (Battle Against a True Hero Remix) - YouTube and 9 more pages - Personal - Microsoft​ Edge 7_27_2023 12_40_51 PM](https://github.com/uBlockOrigin/uAssets/assets/54784572/178a6c30-8326-4224-aaf9-f57204d08309)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 97675
 cosmetic: 39506
 scriptlet: 18120
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69092-9, now
  easyprivacy: 33354-62, now
  plowe-0: 3720-1071, now
  ublock-badware: 7586-142, now
  ublock-filters: 34150-219, now
  ublock-privacy: 443-7, now
  ublock-quick-fixes: 282-86, now
  ublock-unbreak: 2100-34, now
  urlhaus-1: 6353-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 809 ms (selfie)
 maxAssetCacheWait: 250 ms
popupPanel:
 blocked: 666
 network:
  youtube.com: 390
  doubleclick.net: 18
  google.com: 241
  googleadservices.com: 2
  googlesyndication.com: 15
 extended:
  ###player-ads
  ###merch-shelf
  ##.ad-showing > .html5-video-container
  ##.ytd-action-companion-ad-renderer
  ##.ytd-companion-slot-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
```
</details>

**Comment by okiehsch** [comment] 2023-07-27 19:06
Duplicate of [#](https://github.com/uBlockOrigin/uAssets/issues/7636)

**Closed by okiehsch** 2023-07-27 19:06 UTC
