### ISSUE TITLE
play.max.com: detection

### ISSUE THREAD

**Issue by Jellyghost26** [uBlockOrigin/uAssets#18244] opened 2023-05-25 23:56 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.max.com/video/watch/89a56d8c-95e8-47ce-b12b-89f6b0974950/7ec83847-df33-48ca-8b55-fd6387b5bf4c`

### Category

detection

### Description

```adb
||hbo.yspsvc-na.net/csm/*&caid=$xhr,removeparam=caid,domain=play.hbomax.com

and

||yspsvc-*.net^$3p
```

filters did not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93943
 cosmetic: 38910
 scriptlet: 17574
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  ublock-filters: 34086-151, 9m
  ublock-badware: 7153-0, 9m
  ublock-privacy: 420-0, 9m
  ublock-abuse: 69-69, 9m
  ublock-unbreak: 2028-2, 9m
  ublock-quick-fixes: 345-0, 9m
  easylist: 66390-560, 9m
  easyprivacy: 31812-652, 9m
  urlhaus-1: 6912-1, 9m
  plowe-0: 3735-3, 9m
filterset (user): [array of 2 redacted]
hostRuleset: 
 added: [array of 4 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 970 ms
 maxAssetCacheWait: 3 ms
popupPanel: 
 blocked: 32
 network: 
  max.com: 19
  app.link: 3
  brightline.tv: 1
  cookielaw.org: 2
  demdex.net: 1
  googletagmanager.com: 1
  gstatic.com: 1
  litix.io: 4
```
</details>

**Comment by stephenhawk8054** [comment] 2023-05-26 02:15
Since this issue requires a subscribed account to reproduce, if you are willing to share the crendentials of your account, I will provide an email for you.

**Comment by stephenhawk8054** [comment] 2023-05-26 06:55
Can you test this filter?

```adb
play.max.com##+js(json-prune, ssaiInfo fallback.ssaiInfo manifest.url)
```

**Comment by Jellyghost26** [comment] 2023-05-26 13:30
Hey, sorry for the late response, this seems to have worked! Thanks so much!

**Comment by stephenhawk8054** [comment] 2023-05-28 04:02
Since the filter above can remove other sections of a video (recaps, previews, behind-the-scenes...) and with xpath support in [uBO's latest dev build](https://github.com/gorhill/uBlock/releases), these filters might work without removing those sections:

```adb
play.max.com##+js(json-prune, ssaiInfo fallback.ssaiInfo)
play.max.com##+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="SegmentTimeline"])]), , .mpd)
```

**Comment by stephenhawk8054** [comment] 2023-05-29 06:29
The filters are added for dev versions now. I think we can close it until further feedbacks.

**Closed by stephenhawk8054** 2023-05-29 06:29 UTC
Labels: account required, ongoing
