### ISSUE TITLE
bianity.net: detection

### ISSUE THREAD

**Issue by reaksiproton** [uBlockOrigin/uAssets#14864] opened 2022-09-16 10:36 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bianity.net/`

### Category

detection

### Describe the issue

already use custom picker but cannot scroll but if i use enter element picker mode from icon, one by one it working. but after changing the page.... as i use element picker, then i should enter element mode again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 84458
  cosmetic: 40789
  scriptlet: 17896
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 125-1, never
    easylist: 63850-52, 1d.10h.28m
    easyprivacy: 30577-1171, 1d.10h.27m
    plowe-0: 3671-856, 10d.21h.30m
    ublock-abuse: 76-0, 11d.22h.14m
    ublock-badware: 4245-105, 1d.10h.26m
    ublock-filters: 32699-130, 1d.10h.25m
    ublock-privacy: 241-1, 11d.22h.12m
    ublock-quick-fixes: 444-1, 23h.7m
    ublock-unbreak: 1850-41, 1d.10h.24m
    urlhaus-1: 7879-0, 23h.6m
filterset (user): [array of 125 redacted]
trustedset: 
  added: [array of 21 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 877 ms (selfie)
  maxAssetCacheWait: 422 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 3
```
</details>

**Comment by mapx-** [comment] 2022-09-16 10:45
Which is your real issue ? ads ? other ?

I didn't understand the element picker issue - steps ?

**Comment by Yuki2718** [comment] 2022-09-16 12:16
@ryanbr Singup-modal with scroll locked, you have to wait for a second.

**Comment by Yuki2718** [comment] 2022-09-16 12:24
@reaksiproton Fixed in Adguard Annoyances, will be fixed in Fanboy Annoyance too.

**Comment by reaksiproton** [comment] 2022-09-21 10:18
> Which is your real issue ? ads ? other ?
> 
> I didn't understand the element picker issue - steps ?

forgive me for my bad english
can you open the site then you use right click then block the notification ?

**Comment by reaksiproton** [comment] 2022-09-21 10:21
> @reaksiproton Fixed in Adguard Annoyances, will be fixed in Fanboy Annoyance too.

can you explain more about this ? im new user. not understand about Adguard Annoyances and Fanboy Annoyance

**Comment by Yuki2718** [comment] 2022-09-21 16:32
@reaksiproton What do you mean? I don't see the popup with AdGuard Annoyances enabled. Check if you didn't accidentaly disabled cosmetic filtering on the page:

![cosm](https://user-images.githubusercontent.com/58900598/191560551-3a6b8ac7-2b0c-48e6-8390-62c04cd7a707.png)

**Comment by reaksiproton** [comment] 2022-09-22 15:27
the option enable.. and when i enter ##.bianityAdBlock
the scroll is missing...

**Comment by reaksiproton** [comment] 2022-09-22 15:40
![image](https://user-images.githubusercontent.com/112498069/191791685-d4eeea9d-89a3-4250-a1c4-96c63b60f501.png)

**Comment by reaksiproton** [comment] 2022-09-22 16:02
sorry oot: what is lable unable to reproduce ?

**Closed** 2022-09-23 08:13 UTC
Labels: unable to reproduce

**Comment by Yuki2718** [comment] 2022-09-23 16:45
@mapx- Do you see anti-adb?

**Comment by mapx-** [comment] 2022-09-23 16:46
No anti adb on my side

**Comment by Yuki2718** [comment] 2022-09-23 16:50
> sorry oot: what is lable unable to reproduce ?

Simply measn we can't reproduce the anti-adb issue.

**Comment by reaksiproton** [comment] 2022-09-24 00:45
> > sorry oot: what is lable unable to reproduce ?
> 
> Simply measn we can't reproduce the anti-adb issue.

that mean... failed? / no solution ?

if i disable the javascript all running good... nevermind. it just small site... low traffic too lol

**Comment by stephenhawk8054** [comment] 2022-09-24 00:50
> that mean... failed? / no solution ?
> 
> if i disable the javascript all running good... nevermind. it just small site... low traffic too lol

Yes, in order to "fix" some issues, we need to reproduce them. If everything runs normally for us, we do not know what and how to "fix".
