### ISSUE TITLE
Blocking web-RTC

### ISSUE THREAD

**Issue by nanastasija** [uBlockOrigin/uAssets#5885] opened 2019-06-28 13:51 UTC
### URL(s) where the issue occurs

`P2P TURN server IP address (don't want to share publicly) `

### Describe the issue

I am writing to complain about your ungrounded blocking of web-rtc turn requests that we used for P2P system. We recently noticed our P2P TURN servers have been blocked by uBlock. Millions of users are affected because they are not related to some particular domain, but for all. Instead of domains, TURN servers must be used by IP address, maybe due to this TURN requests are stopped. Web-rtc requests shouldn't be blocked, they don't contain any ads or harmful data, it simply consists of signaling data in order to establish communication. In order to solve the problem, please contact me on `nikolovska.anastasija@gmail.com`. I consider your tech should unblock our IP address. Best Regards

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [ Google Chrome 75.0.3770.100]
- uBlock Origin version: [1.20.0]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[filter is: $webrtc,domain]

**Comment by mapx-** [comment] 2019-06-28 13:59
- uBo does not support `$webrtc` (`$webrtc` is used by easylist list hence supported by adblock, ABP, ublock clone)
- maybe you are talking about ublock clone / spam version ?
- we need real test pages to check your issue

**Comment by krystian3w** [comment] 2019-06-28 20:05
maybe mistaken with `$websocket`?

https://github.com/uBlockOrigin/uAssets/search?q=%24websocket&type=Code

**Comment by uBlock-user** [comment] 2019-06-30 08:47
`$websocket` doesn't block IP address or webrtc connections, so no.

**Comment by mapx-** [comment] 2019-06-30 08:50
missing feedback, closing

@nanastasija if you still want to provide the necessary info, write here: `axis.trivia@gmail.com`

**Comment by gwarser** [comment] 2019-06-30 09:09
Maybe it's about [Prevent WebRTC from leaking local IP addresses](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address)?

**Comment by mapx-** [comment] 2019-06-30 09:11
She's specifically talking about `filter is: $webrtc,domain`

**Comment by nanastasija** [comment] 2019-07-01 10:26
Sorry for the late response. This error occurs only when uBlock Origin is turned on.
![image](https://user-images.githubusercontent.com/26957617/60429405-4a783800-9bfb-11e9-86b7-63b999f6df1c.png)
In addition I send you the URl, where the issue occurs when the uBlock is on --> http://test.maksolution.net/test/miki/test_janjua.html

**Comment by gwarser** [comment] 2019-07-01 10:46
https://github.com/uBlockOrigin/uAssets/commit/d20120f8aab5ec396d022e74064ba69810d39efa

**Comment by mapx-** [comment] 2019-07-01 10:49
@nanastasija 
you used previously the webrtc channels to push popups => this is the reason on blocking those requests. 
https://forums.lanik.us/viewtopic.php?f=62&t=43060

Have you definitely dropped out the malicious use of web rtc requests ?

**Comment by mapx-** [comment] 2019-07-01 10:59
If you are positive on the last point above we can update our list.
Sure, you should also report at easylist repository 
https://github.com/easylist/easylist/issues

**Comment by okiehsch** [comment] 2019-07-01 11:08
`http://test.maksolution.net/test/miki/test_janjua.html`
what is broken?

**Comment by mapx-** [comment] 2019-07-01 11:11
I guess it's about their `P2P system`  (they now are not able anymore to use a p2p network and the users are using directly their centralized server)

**Comment by perosr** [comment] 2019-07-01 12:14
Hi All, 

I'm writing in behalf of Vidict Media Server.
The problem is not just at janjua.tv domains, we have this issue on other domains where janjua.tv domain is not added in $webrtc filter. Further more, you write above that uBlock do not use filter $webrtc. We can put another domain, which is not blocked by filter $webrtc, but we have the same problem.

The error is on WEb-RTC side, when RTCPeerConnection is trying to connect to server to get connection ICE candidates.  We are using simple peer WEb-RTC implementation.

Best Regards
Pero Gjuzelov

**Comment by mapx-** [comment] 2019-07-01 12:17
Without real pages, what is broken, how to reproduce the issue .. we cannot help.

**Comment by mapx-** [comment] 2019-07-01 12:21
If there is no specific webrtc / nowebrtc filter, could be it's about using the uBo option `Prevent WebRTC from leaking local IP addresses`

**Comment by krystian3w** [comment] 2019-07-01 12:22
@perosr what you see logo addon in your Browser:

uBlock 0.9.5.16 | uBlock Origin 1.20
--- | ---
![](https://lh3.googleusercontent.com/QgseuLnb2K1edhzIs59ivsxAXPgKoTeD2aSdXi5z8ZlA60x8Zf4yLmvzI8_sp-HictozrJYEkis=w128-h128-e365) | ![](https://lh3.googleusercontent.com/uwCFi5hZM9GcRUbd3y7X3yqJRJrrts7aucQDq3-0ESze2Ma7WSevcpG5iGahTBu-czDZuIxHZg=w128-h128-e365)

**Comment by perosr** [comment] 2019-07-01 12:30
> 
> 
> @perosr what you see logo addon in your Browser:
> uBlock 0.9.5.16 	uBlock Origin 1.20
> ![](https://camo.githubusercontent.com/5f438fffb7914847e388807047d141a97dc66bfc/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f51677365754c6e62324b316564687a4973353969767378415850674b6f546544326153645869357a385a6c41363078385a6634794c6d767a49385f73702d486963746f7a724a59456b69733d773132382d683132382d65333635) 	![](https://camo.githubusercontent.com/61543ab5779a4789d0f9e162f4d238c7f0ebc201/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f757743466935685a4d39476352556264337937583379714a524a7272747337617563514471332d3045537a65324d61375753657663704735694761685442752d637a445a754978485a673d773132382d683132382d65333635)

![image](https://user-images.githubusercontent.com/44429408/60436644-c29b2980-9c0c-11e9-9510-ea9aff046f32.png)

**Comment by perosr** [comment] 2019-07-01 12:31
> uce the issue .. we

there is working link.

Here is another link from domain that is not inside $web-rtc filter. What you mean by fully working link?

http://test.maksolution.net/test/miki/test_ucaster.html

**Comment by mapx-** [comment] 2019-07-01 12:46
ucaster is blocked too by uBo scriptlet
`ucaster.xyz##+js(nowebrtc.js)`

**Comment by mapx-** [comment] 2019-07-01 12:53
The fact is how could you convince not only us (uBo) but also easylist authors that you will use web rtc channels only for legitimate use (p2p streaming) and not for pushing crap on the same infrastructure ?!

@gorhill what do you think .. ?


 |  
-- | --

**Comment by mapx-** [comment] 2019-07-01 12:56
> What you mean by real page?

I mean not test pages (where you present us clean stuff and not  - eventually - a mix of legitimate use + malicious use as I explained above)

**Comment by perosr** [comment] 2019-07-01 13:05
> resent us clean stuff and not - eventually - a mix of legiti

the embedded iframe is real, and you can see the error there. The problem is on all of our supporting domains (just yesterday on all domains where we have p2p, we had 22Millions visits). I can easily block embed script for blockers (ad block, uBlock and etc), but first I want to try to solve the issue - in meaning what shell we change on both side so to avoid blocking (which is the easiest do be done)

**Comment by perosr** [comment] 2019-07-01 13:09
> 
> 
> ucaster is blocked too by uBo scriptlet
> `ucaster.xyz##+js(nowebrtc.js)`
> 
> all these filters (`nowebrtc` scriptlet or ABP-like `$webrtc` option) born due to malicious use of webrtc channels - pushing all kind of popups / popunders crap

this doesn't mean that services used by such websites (ucaster.xyz and similar) are also malicious . We are not owners of mention domains above, they just use our services (in this case vidict Peer - www.vidict.net). I understand your point that malicious use should be stopped, but why to block services that is just used by some malicious website?

**Comment by krystian3w** [comment] 2019-07-01 13:10
Other method to earn money - "paywall" / "pro" paid account?

**Comment by krystian3w** [comment] 2019-07-01 13:13
You can create filterlist with

`#@#+js(nowebrtc.js)` for visitors?

**Comment by mapx-** [comment] 2019-07-01 13:14
If I understand correctly, you provide a service used by ucaster, janjua etc ? (which then are using web rtc too - but separately from your approach - for pushing popups / other crap) 

In this case, probably @gorhill could tell us if the basic / legitimate service / server could be whitelisted and block only the malicious ones.

**Comment by perosr** [comment] 2019-07-01 14:10
Hi mapx,
I'm not sure if janjua, ucaster and etc are using WEB-RTC for malicious usage (I think ad companies are doing that and they do have ads in order to support their free streaming services), but even with web-rtc used by js.script not hosted in their websites, the issue still exists. Here is such link:

http://test.maksolution.net/test/miki/test_ucaster_uBlock.html

On this link, vidictPeer.js (where we are making signalling requests) is hosted on vidict.net and still there are same issue with RTC connections

**Comment by mapx-** [comment] 2019-07-01 14:28
yeah, the current implementation will kill any web rtc request used by `ucaster`.
(however, even whitelisting that filter `ucaster.xyz#@#+js(nowebrtc.js)` I see no `vidictPeer.js` element )

Only gorhill could tell us what could be done to refine such blockage.

**Comment by gorhill** [comment] 2019-07-01 15:27
Isn't this a resource abuse case? To me it looks like it's an attempt to use visitor's bandwidth without their knowledge to serve streaming data to other users.

**Comment by perosr** [comment] 2019-07-01 15:56
> 
> 
> Isn't this a resource abuse case? To me it looks like it's an attempt to use visitor's bandwidth without their knowledge to serve (pirated?) streaming data to other users.

in vidict terms, we have stated that. We are not use the system differently then peer5 (million dollar company) or Strive. The principle is same everywhere, we are not bouncing out of regular terms and conditions as others. Also, WEB-RTC is under chrome terms as well, so when you decide to use chrome, you give total rights of WEB-RTC as well.

**Comment by mapx-** [comment] 2019-07-01 16:32
@perosr  for now (I see no popups delivered by webrtc from ucaster + janjua) I'll comment those filters (waiting to have a fix from uBo creator to flexibilly distinguish between good / bad guys)

Are there other such servers using vidict which are blocked (and so also vidict requests) ?

**Comment by mapx-** [comment] 2019-07-01 16:38
Easylist is blocking (for AB / ABP) janjua, perhaps @ryanbr could remove the `$webrtc` filter

**Comment by uBlock-user** [comment] 2019-07-01 16:53
> so when you decide to use chrome, you give total rights of WEB-RTC as well.

There's no such thing as "giving rights", it's illogical and completely biased from a particular person pov.

**Closed** 2019-07-03 06:06 UTC
