### ISSUE TITLE
hulu.com: ads

### ISSUE THREAD

**Issue by mufffffin56** [uBlockOrigin/uAssets#15761] opened 2022-11-23 03:31 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hulu.com/watch/8bc5df55-1e04-4437-b95f-961c217d55af`

### Category

ads

### Describe the issue

showing ads only skips sometimes how can i fix this 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91690
  cosmetic: 38512
  scriptlet: 16746
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64728-53, 1d.7h.8m
    easyprivacy: 30854-1171, 4d.22h.54m
    plowe-0: 3668-869, 4d.5h.6m
    ublock-abuse: 77-0, 1d.2h.57m
    ublock-badware: 4008-109, 1d.22h.13m
    ublock-filters: 31278-119, 1d.11h.10m
    ublock-privacy: 258-1, 1d.2h.58m
    ublock-quick-fixes: 584-12, 1h.21m
    ublock-unbreak: 1896-43, 1d.11h.9m
    urlhaus-1: 12135-0, 5h.22m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4798 ms
  maxAssetCacheWait: 2844 ms
popupPanel: 
  blocked: 401
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    hulu.com: 186
    ads-twitter.com: 1
    adsafeprotected.com: 1
    adsrvr.org: 1
    conviva.com: 39
    demdex.net: 17
    doubleclick.net: 1
    facebook.com: 2
    google-analytics.com: 2
    imrworldwide.com: 1
    omtrdc.net: 103
    sc-static.net: 1
    scorecardresearch.com: 40
    tealiumiq.com: 4
    tiktok.com: 1
    yimg.com: 1
```
</details>

**Comment by mapx-** [comment] 2022-11-23 06:06
duplicate of [#12407](https://github.com/uBlockOrigin/uAssets/issues/12407)

**Closed by mapx-** 2022-11-23 06:06 UTC
