### ISSUE TITLE
These 5 websites are detecting uBlockOrigin

### ISSUE THREAD

**Issue by WeberAlex** [uBlockOrigin/uAssets#8954] opened 2021-04-23 10:14 UTC
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://courseboat.com/tutorials/`
`https://coursehulu.com/tutorials/`
`https://coursewikia.com/tutorials/`
`https://devcourseweb.com/tutorials/`
`https://freecourseweb.com/tutorialsv4/`

### Describe the issue

All the URLs above (related websites) detect uBlockOrigin when I open any of their tutorial pages, see: screenshot below. 

### Screenshot(s)

![SCR_20210423_190334](https://user-images.githubusercontent.com/28292190/115856635-b29aac80-a467-11eb-9f18-753e5c719c40.png)

### Versions

- Browser/version: [Chrome 90]
- uBlock Origin version: [1.34.0]

**Comment by uBlock-user** [comment] 2021-04-23 10:26
`courseboat` and `coursehulu` fixed, the other three are already fixed in uBO.

**Closed** 2021-04-23 10:25 UTC

**Comment by WeberAlex** [comment] 2021-04-23 10:36
Thanks. The fix for the other three is automatic, or do I need to update a list manually?

**Comment by uBlock-user** [comment] 2021-04-23 10:39
The other three were fixed long ago, I can't reproduce any anti-adblock there.

**Comment by WeberAlex** [comment] 2021-04-23 10:45
I used this download link

`https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm`

I have the default settings, and all the URLs above display the BlockAdblock warning (see: my screenshot).

Do I need to install a specific list?

**Comment by uBlock-user** [comment] 2021-04-23 10:47
Do you have any other extension enabled with uBO ?

**Comment by WeberAlex** [comment] 2021-04-23 10:49
Bitwarden, MetaMask and Screencastify.

**Comment by uBlock-user** [comment] 2021-04-23 10:51
Disable them all except uBO and test again. Disable Chrome's built-in ad filterer too if needed.

**Comment by okiehsch** [comment] 2021-04-23 11:05
If you go to `https://devcourseweb.com/tutorials/` does your logger show this 
![image](https://user-images.githubusercontent.com/16838044/115862411-684c0800-a434-11eb-8b2b-4349ab286161.png)

If you don't know how to check that https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by WeberAlex** [comment] 2021-04-23 11:18
I don't see a **Details** tab when I open the logger. I see the table as in the URL provided (@okiehsch thanks for the link)

I have disabled all the add-on & the built-in filter without effect. I enclose more 2 screenshots. So, I am the only one to experienced this?

![SCR_20210423_200401](https://user-images.githubusercontent.com/28292190/115863765-e0382380-a470-11eb-8cff-9ad4b287329d.png)

![SCR_20210423_200614](https://user-images.githubusercontent.com/28292190/115863792-ea5a2200-a470-11eb-997b-2cc50035b34f.png)

**Comment by okiehsch** [comment] 2021-04-23 11:20
What about `https://devcourseweb.com/tutorials` do ypu get the same message there?

**Comment by okiehsch** [comment] 2021-04-23 11:24
> t. I enclose more 2 screenshots. So, I am the only one to experienced this?

No the domains in your screenshots had those messages present but after you update your `uBO-filters` list the messages should be gone.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

The rest of the domains you posted should not have those ad block messages, that's why I ask for a screenshot of those domains.

**Comment by okiehsch** [comment] 2021-04-23 11:29
> I see the table as in the URL provided (@okiehsch thanks for the link) I don't know what row to look at to open the Details tab

https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates

**Comment by WeberAlex** [comment] 2021-04-23 11:40
BlockAdblock message (after updating `uB0-filters`)

`https://coursehulu.com/tutorials`
`https://courseboat.com/tutorials`

Fixed

`https://coursewikia.com/tutorials/`
`https://devcourseweb.com/tutorials/`
`https://freecourseweb.com/tutorialsv4`

But the 3 URLs still display the huge popup

![SCR_20210423_203537](https://user-images.githubusercontent.com/28292190/115865762-bc2a1180-a473-11eb-9039-3624d867d478.png)

I am reading the Wiki about the logger to have more insight. I need some time.

**Comment by WeberAlex** [comment] 2021-04-23 12:02
Purge all cache & Update all did the trick! Thanks to everyone for the pointers and help.

**Comment by krystian3w** [comment] 2021-04-23 18:06
Pop-up should block Fanboy Annoyance or AdGuard Annoyance (pop-up don't lock scroll - I'm right?).

**Comment by okiehsch** [comment] 2021-04-23 22:54
> Pop-up should block Fanboy Annoyance or AdGuard Annoyance

@krystian3w We decided to fix the popup overlay in the main list because it appears after **every** reload and it's a full page overlay, so you have to dismiss it every time.
That's more than an annoyance imo.
