### ISSUE TITLE
Report: erosyndc.com

### ISSUE THREAD

**Issue by unknowboy1991** [uBlockOrigin/uAssets#6310] opened 2019-09-16 08:03 UTC
### URL(s) where the issue occurs

`https://nudogram.com/ ("NSFW")`

### Describe the issue

Upon click, webpage redirects to this url, then a new tab with the current (`nudogram.com`) domain opens:
```
https://erosyndc.com/blog.html?q=1540416
```

### Screenshot(s)

Chrome returns `HTTP ERROR 404`, no need for screenshots

### Versions

Same as #6296

### Settings

Same as #6296

### Notes

This seems to be a recurring issue with this NSFW site. Can I continue to report domains as I encounter them?

**Comment by okiehsch** [comment] 2019-09-16 08:26
I can't reproduce any redirection at `https://nudogram.com/` with an up to date `uBO-filters` list.

**Comment by mapx-** [comment] 2019-09-16 08:28
it should be fixed by this filter (in uBo filters)
`nudogram.com##+js(aopr, decodeURI)`

**Comment by unknowboy1991** [comment] 2019-09-16 15:02
@mapx- This seems to be a good idea. Will it also take effect on the inline scripts in the page?
It doesn't seem that any useful scripts on that website uses `decodeURI()`, so I believe it won't break the page.

Can you also add domain-level rules for the redirect destinations?

**Comment by mapx-** [comment] 2019-09-16 15:03
all the filters are already in uBo list so just update it in your uBo, then test again

**Closed by mapx-** 2019-09-16 15:03 UTC
