### ISSUE TITLE
[nsfw] youtube.com: ads

### ISSUE THREAD

**Issue by NGJKO** [uBlockOrigin/uAssets#10956] opened 2021-12-17 08:27 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

it always shows the advertisment that i don't wish to sees

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77518
  cosmetic: 39741
  scriptlet: 16345
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61827-8, 22h.43m
    easyprivacy: 26501-17, 22h.41m
    plowe-0: 3687-809, 5d.5m
    ublock-abuse: 81-0, 22h.39m
    ublock-badware: 3569-61, 22h.37m
    ublock-filters: 29987-132, 22h.35m
    ublock-privacy: 188-2, 22h.33m
    ublock-unbreak: 1715-39, 22h.30m
    urlhaus-1: 7261-0, 18h.28m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1706
  launchFromSelfie: true
popupPanel: 
  blocked: 13
```
</details>

**Comment by uBlock-user** [comment] 2021-12-17 08:43
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2021-12-17 08:43 UTC

**Comment by iam-py-test** [comment] 2021-12-17 18:42
@NGJKO please check for redundant issues before opening a new one. A quick search for _YouTube.com_ shows a ton of other duplicate issues and (if you scroll down a tiny bit) #7636

**Comment by krystian3w** [comment] 2021-12-17 19:12
Maybe better exclude found in only closed issues.

**Comment by iam-py-test** [comment] 2021-12-17 19:13
> Maybe better exclude found in only closed issues.

Well, closed issues still can be relevant.
