### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by vaasuaggarwal** [uBlockOrigin/uAssets#14350] opened 2022-08-11 06:46 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=A8DkzGMSuJU`

### Category

ads

### Describe the issue

showing ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80022
  cosmetic: 45102
  scriptlet: 17493
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69327-51, 1h.41m
    easyprivacy: 27323-123, 1h.40m
    plowe-0: 3640-777, 7d.16h.53m
    ublock-abuse: 76-0, 9d.9h.21m
    ublock-badware: 4176-92, 1h.44m
    ublock-filters: 32402-100, 1h.43m
    ublock-privacy: 226-3, 10d.11h.40m
    ublock-unbreak: 1855-43, 1h.42m
    urlhaus-1: 4947-0, 1h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 941 ms (selfie)
  maxAssetCacheWait: 328 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    doubleclick.net: 3
    google.co.in: 1
    google.com: 1
    googlesyndication.com: 5
    youtube.com: 19
```
</details>

**Comment by MasterKia** [comment] 2022-08-11 07:24
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Please read and follow the Prerequisites **_carefully_**.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-11 07:24 UTC
