### ISSUE TITLE
[NSFW] popunder in xhamster

### ISSUE THREAD

**Issue by LoreJon** [uBlockOrigin/uAssets#8067] opened 2020-10-22 17:45 UTC
`https://xhamster.com/categories/beach/newest`

### Describe the issue

a new popunder
### Versions

- Browser/version: [firefox 82]
- uBlock Origin version: [1.36]

### Settings

-

### Notes
see https://github.com/easylist/easylist/issues/5842#issuecomment-714435351

**Comment by LoreJon** [comment] 2020-10-22 17:48
try in private mode.

**Comment by mapx-** [comment] 2020-10-22 18:15
Did you update uBO filters list ?

added today:
`*$popunder,domain=xhamster.*`

**Comment by LoreJon** [comment] 2020-10-22 19:30
`*$popunder,domain=xhamster.*` does not block popunder.
try default filters without Peter Lowe’s Ad and tracking server list.

with Peter Lowe’s `https://xhamster.com/videos/blonde-bikini-slut-washes-pussy-xhsSp24` is blocked. you have to reload.
`||tsyndicate.com^`

with `xhamster.*##+js(window.open-defuser)` no popunder but "next" is broken.

https://user-images.githubusercontent.com/16089271/96866845-95633200-1474-11eb-9a09-d8849db8eae0.png

**Comment by uBlock-user** [comment] 2020-10-22 19:38
How about `xhamster.*##+js(window.open-defuser, !xhamster)`

**Comment by LoreJon** [comment] 2020-10-22 19:43
with `xhamster.*##+js(window.open-defuser, !xhamster)` you get a popunder.

**Comment by mapx-** [comment] 2020-10-22 20:12
@LoreJon does it work using Peter Lowe’s ? (it's part of the default setup)

**Comment by uBlock-user** [comment] 2020-10-22 20:17
@LoreJon try `||xhamster.*^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation`

**Comment by mapx-** [comment] 2020-10-22 20:18
@uBlock-user no. does not work, I tried ALL the tricks today

**Comment by mapx-** [comment] 2020-10-22 20:19
I mean is blocking much more sandbox filter

**Comment by LoreJon** [comment] 2020-10-22 20:47
With Peter Lowe’s there's no popunder.
but I get

![pic](https://user-images.githubusercontent.com/16089271/96928116-c701ea80-14c0-11eb-8b25-5c86d0186c3d.png)

and you need to reload the page.

try it a few times in private window.

**Comment by mapx-** [comment] 2020-10-22 20:54
I get that strict-blocking (tsyndicate) only without `*$popunder,domain=xhamster.*`

Are you sure your lists are updated ?

**Comment by LoreJon** [comment] 2020-10-22 20:55
The lists are updated.

**Comment by mapx-** [comment] 2020-10-22 20:59
click the eye icon for uBO filters list and check if `*$popunder,domain=xhamster.*` is inside it

**Comment by LoreJon** [comment] 2020-10-22 21:03
![pic](https://user-images.githubusercontent.com/16089271/96929586-029db400-14c3-11eb-9753-1bb2f2596a0c.png)

Private window.
`https://xhamster.com/categories/beach/newest`
click a video.

**Comment by LoreJon** [comment] 2020-10-22 21:04
close firefox and open again in private.

**Comment by mapx-** [comment] 2020-10-22 21:07
yeah, as I said it works perfectly on my side, did you allow uBO for "Run in Private Windows" ?

![image](https://user-images.githubusercontent.com/10303732/96929947-3f65ad00-14bb-11eb-9ac8-4ad59b632385.png)

**Comment by LoreJon** [comment] 2020-10-22 21:08
yes.

**Comment by mapx-** [comment] 2020-10-22 21:10
You should reset uBO to the default settings, "purge all caches", "update now", test again.
If you are using some other blocking addons just disable them all

**Comment by mapx-** [comment] 2020-10-22 21:12
my privacy section in FF

![image](https://user-images.githubusercontent.com/10303732/96930445-ff52fa00-14bb-11eb-8f46-f49f817d164d.png)

**Comment by LoreJon** [comment] 2020-10-22 21:16
> You should reset uBO to the default settings, "purge all caches", "update now", test again.

done.

> If you are using some other blocking addons just disable them all

No other blocking addons.

> my privacy section in FF

I have the same settings.

**Comment by LoreJon** [comment] 2020-10-22 21:18
again, I get the strict-blocking (tsyndicate) only on the first try to play a video after opening a private window.

**Comment by mapx-** [comment] 2020-10-22 21:19
As you saw above the popunder is fixed by that new filter in my case. 
antivirus shields impacting your browser ? other security software ?

**Comment by LoreJon** [comment] 2020-10-22 21:21
> antivirus shields impacting your browser ?

No.

**Comment by mapx-** [comment] 2020-10-22 21:23
I'm using the last dev build of uBO: `1.30.7b2`

**Comment by LoreJon** [comment] 2020-10-22 21:24
I'm using 1.30.6.

**Comment by uBlock-user** [comment] 2020-10-22 21:25
Also add `*$popup,domain=xhamster.*`  and try with that ?

**Comment by LoreJon** [comment] 2020-10-22 21:32
> Also add *$popup,domain=xhamster.* and try with that

Same result.
With Peter Lowe’s I get  the strict-blocking.
Without Peter Lowe’s I get a popunder.

**Comment by mapx-** [comment] 2020-10-22 21:37
@LoreJon are you using some mobile emulator ?

**Comment by LoreJon** [comment] 2020-10-22 21:37
No.

**Comment by uBlock-user** [comment] 2020-10-22 21:40
Well the issue is on your end, you will have to investigate this by yourself.

**Comment by mapx-** [comment] 2020-10-22 21:40
add & test 

`xhamster.com##^script:has-text(window.initials)`

**Comment by LoreJon** [comment] 2020-10-22 21:46
> xhamster.*##^script:has-text(window.initials)

the same.

> Well the issue is on your end, you will have to investigate this by yourself.

ok.

**Comment by mapx-** [comment] 2020-10-22 21:47
The fact is I get the popunder but only in mobile emulation, so I'll add it.

**Closed** 2020-10-22 21:48 UTC
Labels: unable to reproduce

**Comment by Yuki2718** [comment] 2020-10-24 12:30
The added HTML filter breaks video on their desktop site.

**Comment by mapx-** [comment] 2020-10-24 12:41
already modified as

```
!#if env_mobile
xhamster.*##^script:has-text(window.initials)
!#endif
```
