### ISSUE TITLE
microcenter.com: detection

### ISSUE THREAD

**Issue by avarner9** [uBlockOrigin/uAssets#23235] opened 2024-04-09 16:40 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.microcenter.com//store/ReviewSubmission.aspx?bvproductid=0655780&bvauthenticateuser=true`

### Category

detection

### Description

On microcenter.com leaving a review for a product gives the error message "Ad blockers prevented your review submission. Please disable ad blockers from this page, then resubmit your review."

(The config below shows I have custom filters enabled, and "Unbreak" disabled, but I verified with both of those changed. It still happens.)

### Other extensions used

Buster: Captcha solver for humans
User-Agent switcher

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/129697655/4c3caaeb-47c6-4639-910a-225c33c2d383)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 124
filterset (summary):
 network: 28001
 cosmetic: 11334
 scriptlet: 18558
 html: 1679
listset (total-discarded, last-updated):
 removed:
  ublock-unbreak: null
  easylist: null
  easyprivacy: null
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, now
 default:
  user-filters: 245-8, never
  ublock-filters: 37556-241, now
  ublock-badware: 8333-15, now
  ublock-privacy: 783-77, now
  ublock-quick-fixes: 237-0, now
  urlhaus-1: 8950-5, now
  plowe-0: 3758-10, now
filterset (user): [array of 245 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  about-scheme
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1542 ms (selfie)
 maxAssetCacheWait: 72 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  googletagmanager.com: 2
  iesnare.com: 1
  wisepops.com: 1
 extended:
  ##.alert-cookie-policy.alert
```
</details>

**Comment by avarner9** [comment] 2024-04-11 16:34
Sorry, I thought it was default already. I updated uBO to 1.57.2 and enabled the two lists you asked for. It still detects an adblocker, and refuses to post a review.

I tested disabling a few lists at a time, and discovered that it is necessary to disable both **EasyPrivacy** and **Peter Lowe's Ad and tracking server list** to get it to work.

Here is a new log, with the two filters enabled that you asked for.

```
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 128841
 cosmetic: 45906
 scriptlet: 18977
 html: 1752
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, now
 default:
  ublock-filters: 37581-108, 1h.26m Δ
  ublock-badware: 8400-15, 1h.26m Δ
  ublock-privacy: 782-78, 1h.26m Δ
  ublock-unbreak: 2298-2, now
  ublock-quick-fixes: 136-34, 1h.26m Δ
  easylist: 84910-268, now
  easyprivacy: 50464-60, now
  urlhaus-1: 8975-10, now
  plowe-0: 3759-1182, now
filterset (user): [array of 245 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1399 ms
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  agilone.com: 2
  bazaarvoice.com: 2
  clarity.ms: 1
  convertexperiments.com: 2
  criteo.com: 2
  datadome.co: 1
  digicert.com: 1
  facebook.net: 1
  flix360.com: 2
  flix360.io: 1
  google-analytics.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 4
  iesnare.com: 2
  redditstatic.com: 1
  sellpoint.net: 1
  syndigo.cloud: 1
  usabilla.com: 1
  zendesk.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(set-constant, rwt, noopFunc)

```

**Comment by gorhill** [comment] 2024-04-11 17:10
>     hostRuleset:
>      added: [array of 6 redacted]

You still have rules which might be causing more blocked network requests than when using just default setup.

Be sure that the issue is not outside uBO, i.e. also test with uBO wholly disabled.

**Comment by ItsProfessional** [comment] 2024-04-12 07:41
>```yml
>filterset (user): [array of 245 redacted]
>```

You are using a heavily customized configuration of uBO. We can't help such users. Reset uBO *completely*, with the button in uBO settings.

**Comment by avarner9** [comment] 2024-04-12 15:28
> > ```yaml
> > filterset (user): [array of 245 redacted]
> > ```
> 
> You are using a heavily customized configuration of uBO. We can't help such users. Reset uBO _completely_, with the button in uBO settings.

Doesn't disabling the "My filters" checkbox disable these 245 filters? If not, what does that even do?

I've already spent several hours of testing here, and I've already narrowed it down to both **EasyPrivacy** and **Peter Lowe**.

If you still won't accept my bug report, unless I irreversibly delete all of my extensive configuration, then there's no way I can continue here. My custom rules have been developed over several years to catch all the things that uBO misses. I'm not just going to delete all that.

Why don't you set up some sort of easily deployed virtual machine? That way, you can test websites in your highly specialized test environment that you demand. For you to set up such a system would take less time than I've already invested in this bug report (several hours). Once it's created, using it would produce a screenshot and log of the error in less than 5 minutes.

**Comment by gorhill** [comment] 2024-04-12 15:54
> I've already narrowed it down to both EasyPrivacy and Peter Lowe

Which filter(s) in EasyPrivacy/Peter Lowe's? The logger will tell from which filter list(s) a filter is found: <https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates>

**Comment by gorhill** [comment] 2024-04-12 15:58
> Why don't you set up some sort of easily deployed virtual machine?

We are on the receiving end of all these reports, investing our own personal time, so spending time trying to mimic everybody's configuration is not going to happen.

> I've already spent several hours of testing here

This does not take hours: open the logger, see what is being blocked when you submit the review, share the filter causing the blocking.

**Comment by avarner9** [comment] 2024-04-12 16:48
I'm not asking you to mimic everybody's configuration. I said that you could set up a virtual machine to mimic your own highly specific configuration that you require bug reporters to have, and then use that VM to test the URL in question.

Regardless of how easy you believe your software to be, I have taken hours to do tests on the URL and narrow it down to two individual filters.

The filters are **EasyPrivacy** and **Peter Lowe**. I can't give more precision than that, because uBO has no line item veto for filter lists.

**Comment by gorhill** [comment] 2024-04-12 17:06
> your own highly specific configuration

It's not highly specific, it's the default one at install time.

Since the issue won't further progress as per your own statement, closing.

**Closed by gorhill** 2024-04-12 17:06 UTC
Labels: account required
