### ISSUE TITLE
Submitting 30 entries from my lists

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5136] opened 2019-03-15 15:38 UTC
Much in the style of #5030, here's my newest batch of entries for various uAssets lists, submitted from three of my lists, including the entirety of *[List for the Freedom of Technological Diversity](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/TechnologicalDiversity.txt)*.

Once again, you guys are free to determine whether to add an entry to Annoyances, Main, Malware, or not at all.

```
! Download links to "optimalisation" tools that no one needs

// Fixed in Badware risks
! — ReImagePlus links —
! https://windowsreport.com/extend-windows-laptop-battery-life/
windowsreport.com##.code-block
! https://appuals.com/fix-error-0x800701e3-on-windows-7-8-1-10/
appuals.com##.info.box
appuals.com##.appua-reimage-top
! https://ugetfix.com/ask/how-to-fix-windows-store-error-0x8000ffff/
ugetfix.com,sauguspc.lt,wyleczpc.pl,sichernpc.de,pcseguro.es##div.attention-button-box-green
ugetfix.com,sauguspc.lt,wyleczpc.pl,sichernpc.de,pcseguro.es##.sidebar_download_inner
ugetfix.com,sauguspc.lt,wyleczpc.pl,sichernpc.de,pcseguro.es##.primary_download
ugetfix.com,sauguspc.lt,wyleczpc.pl,sichernpc.de,pcseguro.es##.download_button_info_texts
ugetfix.com,sauguspc.lt,wyleczpc.pl,sichernpc.de,pcseguro.es##.js-download_button_additional_links
! https://www.thewindowsclub.com/fix-windows-update-error-0xc1900130-on-windows-10
thewindowsclub.com##.entry-content > div > strong:has-text(find & fix Windows error)
! https://www.majorgeeks.com/files/details/patch_my_pc.html
majorgeeks.com##b:has(a[target^="reimage"])
||www.majorgeeks.com/images/icons/red_icon_18x17px.png$image
// Fixed in Badware risks

! — ScanUtilities links —
! https://www.bynarycodes.com/fix-windows-10-update-error-0x80070006/
bynarycodes.com##div[class^="bynar-content_"]
bynarycodes.com##.panel:has-text(a[href*="scanutilities.com"])

// Declined
! — Self-promoting but still somewhat annoying links —
fileinfo.com##.fv
fileinfo.com##.top:has(a[href*="/windows_file_viewer"])
// Declined

! —————————————————————————————————————————————————————————
// Out of scope
! "You MUST download Adobe Reader" nags

! https://www.asrock.com/mb/Intel/Z390%20Phantom%20Gaming%209/index.asp#Manual
asrock.com###Manual > .Notice
! https://www.jal.co.jp/en/footer/browser.html
jal.co.jp##.mgt20:has-text(is necessary to view or print PDF)
! http://www.jal.com/en/press/2004/090801/090801.html
jal.com##body > font:has-text(have Adobe Reader)
! https://www.yadvashem.org/yv/en/downloads/name_reading_ceremonies.asp
yadvashem.org##.text_and_menu_block > p:has-text(need to download Adobe Acrobat)
yadvashem.org##p:has-text(start your Acrobat Reader)
! https://www.gigabyte.com/Motherboard/Z390-M-GAMING-rev-10#support-manual
gigabyte.com##div.target-container.desc:has-text(PDF files with Acrobat )
! https://www.supermicro.com/about/sitemap/
supermicro.com##.boxHome.textA:has([href*="products/acrobat/"])
// Out of scope

! —————————————————————————————————————————————————————————
// Already fixed in Fanboy's Annoyance
! Removes pre-push-prompt banners
! https://iptvstreaming.org/canali/sky/guarda-k2-in-streaming-online
###propush-dialogbox
! https://windowsreport.com/kb4489868-kb4489886-bugs/
##.sendpulse-prompt
// Already fixed in Fanboy's Annoyance

! —————————————————————————————————————————————————————————

! Removes browsing-obstructing banners

! Facebook Mobile/Touch
! https://m.facebook.com/Sonic/
! https://touch.facebook.com/Sonic/
!! Removes the login bars
OPTION 1 (Removes bottom login banner only): m.facebook.com,touch.facebook.com,m.beta.facebook.com,touch.beta.facebook.com,m.facebookcorewwwi.onion##div[style^="background: none;"]:has(#mobile_login_bar)
! Removes the remnants of the bottom login banner
m.facebook.com,touch.facebook.com,m.beta.facebook.com,touch.beta.facebook.com,m.facebookcorewwwi.onion###u_0_25._4b-b

// Declined
OPTION 2 (Removes both top and bottom login banners, potentially making it hard to log in): m.facebook.com,touch.facebook.com,m.beta.facebook.com,touch.beta.facebook.com,m.facebookcorewwwi.onion###mobile_login_bar
// Declined

// Fixed
! Bēhance
! https://github.com/DandelionSprout/adfilt/issues/30
! Removes a small login modul in the lower right
behance.net##body > div[class]:last-child:has(> div > div > .js-adobeid-signup)
// Fixed

// Fixed
! Zulily
! https://www.zulily.com/e/sew-on-and-sew-forth-338868.html
!! Aims to remove the forced login overlay, without breaking the login button in the upper right
zulily.com###loginModal[aria-hidden="false"]:not([aria-describedby="subtitle-signin"])
// Fixed

// Can't reproduce
! YouTube
! https://github.com/DandelionSprout/adfilt/issues/32
! Removes a rarely occuring login nag module with an octopus and a treasure chest when not logged in
youtube.com##paper-dialog:has(ytd-mealbar-promo-renderer)
// Can't reproduce

// Already fixed in AdGuard Annoyances
! InvestingCOM
! https://github.com/DandelionSprout/adfilt/issues/33
! Removes a login popup that shows up the first time the site is visited
investing.com###PromoteSignUpPopUp
// Already fixed in AdGuard Annoyances
```

**Comment by okiehsch** [comment] 2019-03-15 23:37
`zulily.com###loginModal[aria-hidden="false"]:not([aria-describedby="subtitle-signin"])`
breaks the "Become a Member" button.

`behance.net` your filter does not work on my end.
`behance.net##.Popup-popup-T3F` works for me.

**Comment by DandelionSprout** [comment] 2019-03-16 08:00
Thanks for the feedback. I'll update my source lists accordingly right away (having just woke up this morning).

**Comment by okiehsch** [comment] 2019-03-18 03:26
I think the `Adobe Reader` part is out of scope, I don't see them as annoying they are just links to adobe-reader in the context of opening pdf-files.
![image](https://user-images.githubusercontent.com/16838044/54504868-d78dce80-4935-11e9-9b9d-74267a51f62d.png)

@mapx- what do you think?

**Comment by mapx-** [comment] 2019-03-18 08:10
I agree, could be a useful info.

**Comment by okiehsch** [comment] 2019-03-18 08:17
There are more proposed filters I had no time looking at.
I marked the ones I already looked at in the first post with comments like `Fixed`, `Already fixed` ....

**Comment by DandelionSprout** [comment] 2019-03-18 09:17
I've been thinking that it's wrong of websites to claim that Adobe Reader is mandatory to open static PDF files, since it's possible in the year 2019 to open PDF files directly in web browsers or in other PDF programs like SumatraPDF. Adobe's tendency to attempt to include McAfee in program updates, has also made me considerably salty towards Adobe.

But I suppose it was a long shot of me to get those entries included in uAssets to begin with, so fair enough.

**Comment by okiehsch** [comment] 2019-03-18 09:41
The `Download links to "optimalisation" tools that no one needs` part is not an annoyance but advertisement for crapware in my opinion
See
````
https://forums.malwarebytes.com/topic/194200-removal-instructions-for-reimage-repair/
````

**Comment by DandelionSprout** [comment] 2019-03-18 09:43
Does that make those links a candidate for the Main or Badware Risks lists instead?

**Comment by okiehsch** [comment] 2019-03-18 09:49
Not sure, @gorhill what do you think?
I would put them in `Badware risks`

**Comment by mapx-** [comment] 2019-03-18 10:01
imo me it's for `Badware risks`

**Comment by okiehsch** [comment] 2019-03-20 03:11
`fileinfo.com` is self advertising and I personally don't see any thing annoying about it, so I will decline.

The `ScanUtilities` part looks like simple advertising to me, you may say that no one needs optimalisation tools - and I would agree with you - but that is true for many products I can think of.
Now having said all that your second filter does not block anything on my end.
![image](https://user-images.githubusercontent.com/16838044/54656380-acd28000-4ac5-11e9-9c91-eeb37ed9d23e.png)

Seems to me that all that is needed is your first filter
`bynarycodes.com##div[class^="bynar-content_"]`
so I would suggest that this should be fixed in `EasyList` because no extended syntax is necessary to hide the advert.

**Comment by DandelionSprout** [comment] 2019-03-20 11:53
I've never tried to make an entry submission to EasyList before, so I think I could need a quick shakedown on how to best do so, to be honest.

**Comment by okiehsch** [comment] 2019-03-21 01:07
@ryanbr
Test link: 
`https://www.bynarycodes.com/fix-windows-10-update-error-0x80070006`
Proposed filter:
`bynarycodes.com##div[class^="bynar-content_"]`
![image](https://user-images.githubusercontent.com/16838044/54728364-bd463180-4b7d-11e9-8ddc-2f554c21e631.png)

Do you see this issue as advertising or as an annoyance?

**Comment by okiehsch** [comment] 2019-03-21 23:53
I can't reproduce the youtube issue.

I will add option 1 of the faceobool issue, can you provide a screensot of the "remant of the login box"?
I can't see anything obvious on my end.

**Comment by DandelionSprout** [comment] 2019-03-21 23:58
There used to be a thin white line above where the bottom login banner would've been, but all of a sudden I can't reproduce it in a hurry anymore, so I guess we'll skip that.

**Comment by okiehsch** [comment] 2019-03-22 00:03
OK, that means all issues raised by you  have been looked at as far as I can see, so I will close the issue with the facebook commit.

**Closed** 2019-03-22 00:08 UTC
