### ISSUE TITLE
accuweather detects blocking & broken videos

### ISSUE THREAD

**Issue by RedactedCode** [uBlockOrigin/uAssets#6434] opened 2019-10-15 10:18 UTC
### URL(s) where the issue occurs

`https://www.accuweather.com/`

### Describe the issue

going to any page on accuweather triggers a message from the website 

> You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.

### Screenshot(s)

![accublock](https://user-images.githubusercontent.com/31665276/66822720-b7aaa180-ef3c-11e9-8822-d4008ba49e18.png)

### Versions

- Browser/version: 

Vivaldi   2.8.1664.40 (Stable channel) (32-bit)
Revision:  3ceb1e00616d447249d27368e347561bc737a2e0
OS: Linux

- uBlock Origin version: 
uBlock Origin v1.22.4

### Settings

- [None]

### Notes

Can right-click on message block & block elements, but message appears again when reloading website

**Comment by mapx-** [comment] 2019-10-15 11:53
I cannot reproduce the warning using the default settings

**Comment by llacb47** [comment] 2019-10-15 14:05
https://github.com/NanoMeow/QuickReports/issues/1622#issuecomment-517969430

**Comment by mapx-** [comment] 2019-10-15 14:10
`||fundingchoicesmessages.google.com^` is already in `easyprivacy`

**Comment by krystian3w** [comment] 2019-10-15 18:41
IMO `acis` is good solution.

**Comment by krystian3w** [comment] 2019-10-15 18:43
Try reproduce with Opera - maybe.

**Comment by RedactedCode** [comment] 2019-10-15 22:02
Reset my settings to default to make sure, yep, still see it.

**Comment by okiehsch** [comment] 2019-10-15 22:12
I can only reproduce if I disable `uBO-filters`using Chromium/Chrome or Firefox, mabye it only does not work using Vivaldi.
Does adding 
`accuweather.com##+js(acis, atob, googlefc)`
to your filter list works for you?

**Comment by llacb47** [comment] 2019-10-15 22:35
I couldn't reproduce in Nano Adblocker Chrome or Firefox with default settings, or with `contributor.google.com` blocked. I'm not sure why. 

Here's a site with this type of anti-adblock on default settings: `https://www.newschoolers.com` It can be fixed with  `newschoolers.com##+js(acis, atob, googlefc)`.

**Comment by okiehsch** [comment] 2019-10-15 22:40
> I couldn't reproduce in Nano Adblocker Chrome or Firefox with default settings, or with contributor.google.com blocked. I'm not sure why.

The reason is `@@||accuweather.com^$generichide` in `uBO-filters`.
If you add `@@||newschoolers.com^$generichide` to your filter list that issue would also be fixed.

I will add your filter, thanks.

**Comment by llacb47** [comment] 2019-10-16 00:11
Another site: `https://www.richmond.com/news/trending/the-acts-nominated-for-the-rock-and-roll-hall-of/collection_e0ba87f0-155d-534b-94e9-181c8e35ca68.html`

**Comment by llacb47** [comment] 2019-10-16 01:06
@okiehsch I updated the filter in https://github.com/uBlockOrigin/uAssets/issues/6434#issuecomment-542455288

**Comment by llacb47** [comment] 2019-10-16 01:28
One more owned by BH Media Group: `tulsaworld.com`


Looks like it's on all Lee Enterprises (`https://en.wikipedia.org/wiki/Lee_Enterprises`) sites as well. 🙄

Domains: `auburnpub.com,azdailysun.com,beatricedailysun.com,billingsgazette.com,bismarcktribune.com,chippewa.com,columbustelegram.com,cumberlink.com,dailyjournalonline.com,democratherald.com,elkodaily.com,fremonttribune.com,gazettetimes.com,globegazette.com,hanfordsentinel.com,helenair.com,herald-review.com,jg-tc.com,journalstar.com,journaltimes.com,kenoshanews.com,lacrossetribune.com,lompocrecord.com,madison.com,magicvalley.com,missoulian.com,mtstandard.com,muscatinejournal.com,napavalleyregister.com,nwitimes.com,pantagraph.com,poststar.com,qconline.com,qctimes.com,rapidcityjournal.com,ravallirepublic.com,santamariatimes.com,siouxcityjournal.com,stltoday.com,tdn.com,thesouthern.com,thetandd.com,theworldlink.com,trib.com,tucson.com,wcfcourier.com,winonadailynews.com,wiscnews.com`

**Comment by okiehsch** [comment] 2019-10-16 01:31
Most ot those domains should already be fixed.
![image](https://user-images.githubusercontent.com/16838044/66880942-4d8a0f00-efc5-11e9-8331-d14574077d44.png)

**Comment by llacb47** [comment] 2019-10-16 01:41
@okiehsch I updated https://github.com/uBlockOrigin/uAssets/issues/6434#issuecomment-542470629

**Comment by uBlock-user** [comment] 2019-10-16 10:22
> Reset my settings to default to make sure, yep, still see it.
> Update all my lists (including easyprivacy) - still see it.

Do a full reload of the page bypassing cache.

**Comment by krystian3w** [comment] 2019-10-16 12:58
Or new profile on Vivaldi 2.4+.

**Comment by mapx-** [comment] 2019-10-16 13:50
@krystian3w  why are you talking about opera, vivaldi ? can you reproduce the issue using the default settings ? 
I tried vivaldi 2.8, still nothing.

**Comment by NubN** [comment] 2019-10-16 13:59
similar case in `abc.es` ( solved in **uBlock filters – Annoyances**​)

I tried in a thousand ways but it didn't make the videos work.

```
https://www.accuweather.com/en/videos/
https://www.accuweather.com/es/videos/experts/uyJvgset
```

no anti adblock notice for me in `accuweather.com`

**Comment by mapx-** [comment] 2019-10-16 14:56
adding too
```
@@||accuweather.com^$script,1p
@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=accuweather.com
```

the delay is gone for me

**Comment by mapx-** [comment] 2019-10-17 09:20
missing feedback, closing

**Closed by mapx-** 2019-10-17 09:20 UTC
Labels: unable to reproduce

**Comment by llacb47** [comment] 2020-01-11 23:02
Videos seem to work without delay without requiring any of the existing whitelists.  
Test (to override unbreak and easylist whitelists)
```
@@||accuweather.com^$script,1p,badfilter
||accuweather.com/bundles/prebid.$script,important
||amazon-adsystem.com/aax2/apstag.js$domain=accuweather.com,important
||doubleclick.net/gpt/pubads_impl_$script,domain=accuweather.com,important
||g.doubleclick.net/tag/js/gpt.js$script,domain=accuweather.com,important
```

**Comment by okiehsch** [comment] 2020-01-12 04:42
Thanks for pointing that out.
I can reproduce, it works fine on my end as well.

**Comment by NubN** [comment] 2020-05-08 01:58
the delay is back

`https://www.accuweather.com/en/videos`

**Comment by llacb47** [comment] 2020-05-08 02:13
I get no delay.

**Comment by NubN** [comment] 2020-05-08 02:26
it happens to me when I delete cookies. 

after trying to play some videos, the delay disappears..

but if i delete again the cookies, the delay come back.  🙄

**Comment by krystian3w** [comment] 2020-05-08 05:42
Maybe you clear cache with cookies and all website slow down.
