### ISSUE TITLE
Spotify Ad Filter Not Working

### ISSUE THREAD

**Issue by CR4BBYR0N1N** [uBlockOrigin/uAssets#14395] opened 2022-08-14 08:58 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://open.spotify.com/`

### Describe the issue

Spotify ad blocking the next song on playing as it get's stuck in the current song that ended

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80481
  cosmetic: 45258
  scriptlet: 17604
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69331-51, 3d.3h.26m
    easyprivacy: 27324-123, 3d.3h.24m
    plowe-0: 3629-776, 1d.46m
    ublock-abuse: 76-0, 3d.3h.27m
    ublock-badware: 4176-92, 3d.3h.25m
    ublock-filters: 32402-100, 2d.23h.23m
    ublock-privacy: 231-3, 3d.7h.28m
    ublock-quick-fixes: 390-1, 20h.45m
    ublock-unbreak: 1858-43, 16h.42m
    urlhaus-1: 5283-0, 20h.44m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 329 ms (selfie)
  maxAssetCacheWait: 299 ms
```
</details>

**Comment by MasterKia** [comment] 2022-08-14 09:01
> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14231

**Closed by MasterKia** 2022-08-14 09:01 UTC
