### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by thanhle0132** [uBlockOrigin/uAssets#13022] opened 2022-04-29 19:36 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

still have ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![asdsed](https://user-images.githubusercontent.com/104651777/166058013-565adec5-1fa3-486b-8e41-af8c2ab97bf2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82362
  cosmetic: 43800
  scriptlet: 16794
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1978-0, 1h.30m
    easylist: 66580-57, 2d.2h.25m
    easyprivacy: 26907-126, 2d.2h.24m
    plowe-0: 3679-805, 2d.11h.17m
    ublock-abuse: 74-0, 4d.4h.57m
    ublock-badware: 4104-93, 2d.2h.23m
    ublock-filters: 30965-115, 2d.2h.22m
    ublock-privacy: 212-2, 4d.4h.58m
    ublock-unbreak: 1765-42, 2d.2h.26m
    urlhaus-1: 8087-0, 1h.29m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1651 ms (selfie)
  maxAssetCacheWait: 1242 ms
popupPanel: 
  blocked: 9
  no-scripting: true
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 5
```
</details>

**Comment by okiehsch** [comment] 2022-04-29 19:46
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by okiehsch** 2022-04-29 19:46 UTC
