### ISSUE TITLE
callofwar.com: ads

### ISSUE THREAD

**Issue by torohangupta** [uBlockOrigin/uAssets#12634] opened 2022-04-06 17:52 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.callofwar.com/play.php?bust=1&uid=42727887&gameID=5119134&source=browser-desktop`

### Category

ads

### Describe the issue

I can tell uBlock is trying to block the ads- they start to dissapear and then come back, and have tried to use the element picker to block them myself as well, however this keeps making it through and I can't figure out how to disable the ads on the website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="462" alt="image" src="https://user-images.githubusercontent.com/75713762/162036990-a86388e4-11db-4ffe-93a5-e25492edf1d1.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 84869
  cosmetic: 42238
  scriptlet: 16409
  html: 631
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/fanboy-social-no-cosmetic.txt: 3900-0, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admaven-domains.txt: 64-0, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admeasures-domains.txt: 220-1, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/bt-contentza-domains.txt: 8-0, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/cdn-filter-list.txt: 68-0, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/combined-filters.txt: 1582-713, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/cryptomining-domains.txt: 228-228, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/freecounterstat-domains.txt: 13-0, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/getadmiral-domains.txt: 641-641, 21m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/hilltopads-domains.txt: 62-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/istripper-domains.txt: 10-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/kitty-domains.txt: 31-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/macupload-domains.txt: 41-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/popads-domains.txt: 81-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/propellerads-domains.txt: 68-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/toradvertising-domains.txt: 1-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/unknown-domains.txt: 13-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/videoadex-domains.txt: 7-0, 20m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/volumedata-domains.txt: 1-0, 19m
  default: 
    user-filters: 35-1, never
    ublock-filters: 31061-47, 3d.18h.23m
    ublock-badware: 4006-3, 3d.18h.22m
    ublock-privacy: 211-0, 3d.40m
    ublock-abuse: 72-1, 2d.58m
    ublock-unbreak: 1741-0, 3d.18h.21m
    easylist: 65165-785, 3d.18h.20m
    easyprivacy: 26744-911, 3d.18h.19m
    urlhaus-1: 8132-0, 2h.58m
    plowe-0: 3690-380, 5d.14h.29m
    ublock-quick-fixes: 124-5, 2h.57m
filterset (user): [array of 35 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 194 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 8
  no-popups: true
  blockedDetails: 
    callofwar.com: 4
    bytro.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    rubiconproject.com: 1
```
</details>

**Comment by krystian3w** [comment] 2022-04-06 22:15
Duplicate of #12463

**Closed** 2022-04-07 06:34 UTC
Labels: duplicate
