### ISSUE TITLE
uBlock is stoping YouTube videos from loading. 

### ISSUE THREAD

**Issue by V7I0SeventhSector** [uBlockOrigin/uAssets#14514] opened 2022-08-24 03:25 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.youtube.com/watch?v=PNraGYXihT4
https://www.youtube.com/watch?v=-Ctpa4T1eYc 

### Describe the issue

im using Firefox on Windows 10 
i only have 4 add-ons and i tested to make sure it is ONLY uBlock that's causing this problem
running on ver. 1.44.0

so,  i will try and watch a video on YouTube and randomly a video will not load. . like at all, it will stay on the black screen with the loading circle but never load, ill refresh the page, and nothing! i can watch other videos just fine but the ones that it refuses to load will NEVER load with uBlock. . 
this started a few months ago and i only now figured out what was causing it. . 

i know next to nothing about the settings and have not touched anything from the time i downloaded it to now. . 

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 80207
  cosmetic: 44671
  scriptlet: 17700
  html: 734
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33218-129, 1m
    ublock-badware: 4223-0, 1m
    ublock-privacy: 263-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1851-0, 1m
    ublock-quick-fixes: 395-0, 1m
    easylist: 68950-493, 1m
    easyprivacy: 27411-595, 1m
    urlhaus-1: 4681-0, 1m
    plowe-0: 3633-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1453 ms
  maxAssetCacheWait: 189 ms
```
</details>

**Comment by MasterKia** [comment] 2022-08-24 03:46
> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-24 03:46 UTC

**Comment by mii-pabortdom** [comment] 2022-08-24 13:01
@MasterKia It is not technically a duplicate, but I understand you guys want to keep all YT-related stuff on that long thread?

**Comment by V7I0SeventhSector** [comment] 2022-08-31 00:44
> Indeed, more people are subscribed to that YouTube thread. Besides, we have got 200+ YouTube issues by now.

ohh. . sorry, was confused as to why I was flagged for being the same as when I looked into it, that one was not the same but that makes more sense!
