### ISSUE TITLE
centrisfcu.org: breakage

### ISSUE THREAD

**Issue by chrisbaber** [uBlockOrigin/uAssets#16321] opened 2023-01-13 14:40 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.centrisfcu.org/`

### Category

breakage

### Description

login button does not open login dialog.  I have manually allowed -all globally, and this did not resolve the issue.  if i completely disable uBlock Origin, the site works properly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 114855
  cosmetic: 183733
  scriptlet: 24075
  html: 982
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware-url: 885-5, 1d.36m
    block-lan: 44-0, 1d.34m
    curben-phishing: 17726-2, 23h.18m
    curben-pup: 194-0, 23h.18m
    adguard-annoyance: 62348-4775, 23h.18m
    adguard-social: 19557-1080, 23h.18m
    fanboy-thirdparty_social: 68-0, 23h.18m
    fanboy-annoyance: 84968-68982, 23h.18m
    fanboy-cookiemonster: 44777-238, 1d.34m
    fanboy-social: 23492-28, 23h.18m
    ublock-annoyances: 4688-4, 1d.34m
  default: 
    user-filters: 28-2, never
    ublock-filters: 32399-56, 2d.14h.23m
    ublock-badware: 4296-0, 10h.46m
    ublock-privacy: 307-0, 9d.11h.39m
    ublock-abuse: 77-0, 9d.11h.38m
    ublock-unbreak: 1936-1, 1d.36m
    ublock-quick-fixes: 479-2, 1h.28m
    easylist: 61690-649, 4d.11h.22m
    easyprivacy: 30891-1747, 4d.11h.21m
    urlhaus-1: 6868-0, 1h.27m
    plowe-0: 3671-2, 8d.57m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 67 redacted]
  removed: 
    about-scheme
hostRuleset: 
  added: [array of 13 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 464 ms (selfie)
  maxAssetCacheWait: 515 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    centrisfcu.org: 4
    crazyegg.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    myfonts.net: 2
    omappapi.com: 7
    siteimproveanalytics.com: 1
    translate.googleapis.com: 1
```
</details>

**Comment by okiehsch** [comment] 2023-01-13 15:06
Fixed by adding
`@@||centrisfcu.org/wp-content/plugins/popup-maker/assets/js/*$script,1p`

It's caused by `Adguard Annoyances`.
@Yuki2718

**Closed** 2023-01-13 15:09 UTC
Labels: fixable by Easylist / Adguard lists
