### ISSUE TITLE
uBO causing some RTÉ Player videos to freeze/not play

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#5111] opened 2019-03-11 14:40 UTC
### URL(s) where the issue occurs
Examples of a few videos where uBO freezes the video
`https://beta.rte.ie/player/series/my-money-and-me/SI0000001158?epguid=IP000061394`
`https://beta.rte.ie/player/series/magic-city/SI0000002830?epguid=PL000000512`
`https://beta.rte.ie/player/series/home-and-away/SI0000000756?epguid=AQ000242317`

It doesn't happen on ALL videos, only some. Example of a video where uBO works perfectly:
`https://beta.rte.ie/player/series/capsule/SI0000004328?epguid=PL000000897`

### Describe the issue

Some videos on the RTÉ Player don't load and freeze, showing two pause icons on the video. This only happens on some videos.

### Screenshot(s)

`https://gfycat.com/ringeduniquebeagle`

### Versions

- Browser/version: [Google Chrome is up to date Version 72.0.3626.121 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock Origin v1.18.4]

### Settings

- []

### Notes

[Tried with only uBO extension on. Still happens.]

**Comment by mapx-** [comment] 2019-03-11 14:43
the first 3 videos rediret to `https://beta.rte.ie/player/404`

**Comment by germaloney11** [comment] 2019-03-11 14:47
They might be geo-locked. Do you have access to an Irish IP?

**Comment by mapx-** [comment] 2019-03-11 14:54
I'll try again in few hours (and if hola provide some irish ip). 
Or it's about having an account for that site ?

**Comment by germaloney11** [comment] 2019-03-11 15:00
No you don't need to be signed in. Some videos I think are restricted to Ireland only as opposed to worldwide.

**Comment by mapx-** [comment] 2019-03-11 21:25
well, now - even using an Irish ip, I get (for all 3 links)

> This programme cannot be streamed due to rights restrictions

**Comment by germaloney11** [comment] 2019-03-11 21:50
No idea why, but all 3 of those links are working fine now. They were working earlier without uBO enabled so I'm pretty sure it was a uBO issue. Very strange. Thanks for trying. `https://gfycat.com/pitifulforthrightgelding`

**Comment by mapx-** [comment] 2019-03-11 21:52
> all 3 of those links are working fine now

so, false alarm

**Comment by germaloney11** [comment] 2019-03-13 15:47
This is still happening on the "Home and Away" videos. `https://beta.rte.ie/player/series/home-and-away/SI0000000756`


The videos can be played normally with ads when uBO is off.

Example: `https://gfycat.com/MintyDistantBluebreastedkookaburra`

**Comment by mapx-** [comment] 2019-03-13 19:18
getting same restrictions message, cannot help

**Comment by germaloney11** [comment] 2019-03-13 19:59
Can you try a different VPN? Hola seems to be your problem.

**Comment by mapx-** [comment] 2019-03-13 20:24
well, it seems to be impossible (yeah, I tried different proxies, no chance)
https://thevpn.guru/get-rte-player-uk-outside-ireland/

**Comment by germaloney11** [comment] 2019-03-13 21:03
Can you reopen the issue then as it is still persistent

**Comment by ghajini** [comment] 2019-03-15 17:23
Only remote teamviewer to author computer  will help here , as site is disabling  access to VPN softwares, anonymous proxy servers......

**Comment by Jap2-0** [comment] 2019-03-17 18:26
It redirects me as well, but view-source: still appears to work.
@germaloney11 does the following work?

`beta.rte.ie##+js(bab-defuser.js)`

**Comment by bogachenko** [comment] 2019-03-18 02:11
@mapx- 

>well, now - even using an Irish ip, I get (for all 3 links)
>This programme cannot be streamed due to rights restrictions

I am currently using VPN Japan. No geolocation lock found.

@germaloney11 

In their filters I signed on filters which remove all (almost all) tracking. However, if I disable the psychopath list (and use only the default settings), then your site opens without any problems at all. Look.

![twitch](https://user-images.githubusercontent.com/8535285/54502153-12d1d280-4921-11e9-920c-8d4e978cc4fc.gif)
turn off your filters (leave only default) and try again.

**Comment by germaloney11** [comment] 2019-03-18 15:52
It seems to be back to normal now, but it will change back again. Every week or so it happens and then sorts itself out, it is always the Home & Away episodes that it happens on. I guess it can be marked closed now, I'll let you know when it happens again. Thanks for yer help.

**Comment by germaloney11** [comment] 2019-03-25 20:56
@bogachenko Can you check the link again please, the problem has reoccured as it usually does after a few days.
You can click on any of the episodes here and when you press play it looks as though it is loading the video but it just freezes and pauses with "Commercial break" written on the bottom right of the player.
`https://beta.rte.ie/player/series/home-and-away/SI0000000756`

**Comment by Jap2-0** [comment] 2019-03-25 21:48
@germaloney11 does adding `beta.rte.ie##+js(bab-defuser.js)` to your custom filters fix it for you?

**Comment by bogachenko** [comment] 2019-03-26 01:45
@germaloney11 

https://imgur.com/a/22YItNc

I don't have an Ireland ip now. if you give me an Irish ip. i can try with Irish-ip. I took Britain's ip. I can't click on your links. I have a 404 error, I also can't find your series or what you gave me - Home and Away. I have his stupidly there is no. Other videos are played without ads.

Is it possible to block by ip without notification. I do not believe in that. Always write "_Content is available only for a specific country, come to us and watch it_."

**Comment by bogachenko** [comment] 2019-03-26 02:06
@germaloney11 Okay, I take it back. It seems Ireland does not write for whom the content is available. Now I have the IP of Ireland. But I can't play it.
![1](https://user-images.githubusercontent.com/8535285/54966305-c3685380-4f6b-11e9-8f9c-3c0001872dad.gif)

**Comment by germaloney11** [comment] 2019-03-31 12:37
> beta.rte.ie##+js(bab-defuser.js)

Yes, that fixed it. Thank you so much!

**Comment by germaloney11** [comment] 2019-04-20 19:53
@Jap2-0 Seems to be happening again 😥

Seems to happen when clicking play on different episodes and also it restarts the entire episode sometimes when you skip/watch passed the ad in the middle of the videos.

**Comment by germaloney11** [comment] 2019-04-30 19:33
Can you reopen please as the original issue is still persistent

**Comment by mapx-** [comment] 2019-05-22 13:10
@germaloney11  if you are still able to reproduce the issue, select from the logger only the blocked elements and post them here (as text lists but as image too). 
Otherwise => we should close the issue.

**Closed** 2019-05-24 19:11 UTC
Labels: geo lock
