### ISSUE TITLE
nsfw hanime.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#4080] opened 2018-11-07 16:47 UTC
### URL(s) where the issue occurs

`https://hanime.tv/inter?r=%2Fhentai-videos%2Fsaimin-gakuen-2018-ep-4`

### Describe the issue

ad-redirection/annoyance

### Screenshot(s)

![2018-11-07-advertising - hanime tv](https://user-images.githubusercontent.com/5884000/48146363-168b8380-e2b5-11e8-9430-e0f73c4e9db8.png)

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by uBlock-user** [comment] 2018-11-07 19:34
That's redirection regardless of whether you whitelist or not. The only way I have found to bypas this is via inserting a cookie which it looks for.

**Comment by okiehsch** [comment] 2018-11-07 19:35
The site seems broken on my end, I don't see any anti-adblock message, but I have to click "Close AD" and then reload for the video to start.

**Comment by uBlock-user** [comment] 2018-11-07 19:39
It's on purpose, not broken, that's ad redirection page, check the address of that page.

**Comment by uBlock-user** [comment] 2018-11-07 19:43
JS plugin - https://cdn.hanime.tv/dist/d2a5d79a7773fd077bc3.js

**Comment by okiehsch** [comment] 2018-11-07 19:46
I don't get the ant-adblock message.
If I go to `https://hanime.tv/inter?r=%2Fhentai-videos%2Fsaimin-gakuen-2018-ep-4`
I see 
![image](https://user-images.githubusercontent.com/16838044/48156579-0a5ff000-e2ce-11e8-8c29-d6d19e5e75b0.png)
after clicking "Close AD" and reloadng the video starts.

**Comment by uBlock-user** [comment] 2018-11-07 19:49
Neither do I, the issue is ad-redirection page.

Do this - 

Remove cookies for that site
Click here https://hanime.tv/hentai-videos/urotsukidoji-new-saga-1
then pick a video under `More from Urotsukidoji series:` and click on it, 
Get greeted with that Close Ad, ad redirection page.

**Comment by okiehsch** [comment] 2018-11-07 19:52
I can reproduce that, I was only wondering that I could not get the message inthe screenshot of the OP, hence me wondering if the site is broken on my end.
Anyway, that can't be fixed in uAssets and it is not an `anti-adblock` issue.

**Comment by uBlock-user** [comment] 2018-11-07 19:53
But it is an annoyance, is there not a scriptlet that can fix this annoyance ?

**Comment by KonoromiHimaries** [comment] 2018-11-07 19:56
@jspenguin2017

**Comment by okiehsch** [comment] 2018-11-07 19:57
We can't set a cookie, so I don't see how, but if somebody can come up with a fix, it can be added to `uBO-annoyances`.

**Comment by uBlock-user** [comment] 2018-11-07 19:59
I'm setting the cookie via my personal cookie scriptlet, but I gorhill would prefer alternative solutions, so I haven't proposed that.

**Comment by okiehsch** [comment] 2018-11-07 20:05
We will not add a scriptlet with the ability to set cookies for security reasons, 
I don't see how to disable the redirection with an existing scriptlet without breaking the core site functionality.

**Comment by uBlock-user** [comment] 2018-11-07 20:06
> without breaking the core site functionality.

yes, that's the issue I'm facing too, all the scriptlets I have used, break some functionality to stop that.

**Comment by jspenguin2017** [comment] 2018-11-07 20:55
Did someone pinged me? 

I do have ways to write cookies with my privileged script snippets, but I rather not deal with these sticky sites...

**Closed** 2018-11-22 10:36 UTC

**Comment by uBlock-user** [comment] 2018-11-22 10:51
Why closed ? Giving up ?

**Comment by mapx-** [comment] 2018-11-22 12:14
If only the cookie-approach seems working, I do not think there is much to do

**Comment by KonoromiHimaries** [comment] 2019-01-07 11:55
new anti adblock

**Comment by KonoromiHimaries** [comment] 2020-06-06 11:04
https://github.com/PolishFiltersTeam/KAD/issues/1387
