### ISSUE TITLE
Instagram Login Popup Filter not working

### ISSUE THREAD

**Issue by darthclide** [uBlockOrigin/uAssets#6524] opened 2019-11-07 10:34 UTC
### URL(s) where the issue occurs

www.instagram.com/*

### Describe the issue

Instagram is forcing users to login to view public profiles, so I am turning to filters to stop this. Either I am missing something, or Instagram has already "patched" your filter.

### Versions

- Browser/version: Chrome 78.0.3904.87
- uBlock Origin version: uBlock Origin version 1.23.0

### Settings

I have tried activating all "annoyances" and I have tried using this code in "my filters"

`instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"])
instagram.com##body:style(overflow-y: scroll !important;)
instagram.com##body[style*="overflow: hidden;"] .XQXOT:style(width: calc(100% - 12px) !important; padding-right: 0 !important;)`

### Notes

As stated before, I am guessing Instagram is constantly patching your patches and it is why opening Instagram in incognito mode does not let me get past the login popup.

**Comment by yourduskquibbles** [comment] 2019-11-07 13:43
Unable to reproduce on US IP in Chrome & Firefox standard test profiles with uBO Default settings + `uBlock Filters - Annoyances` list enabled.

Do you have cosmetic filtering disabled for `instagram.com`? Does popup panel for Instagram look like 
![No Cosmetic Filtering Enabled](https://user-images.githubusercontent.com/585534/46021299-62d88680-c0ae-11e8-8280-5dcbf7019c85.png)? [uBO wiki - Per site switches - No cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering).  

Can also check `My rules` in uBlock Dashboard for `no-cosmetic-filtering: www.instagram.com true` rule or under `My filters` that cosmetic filtering is not globally turned off?

If you can verify those are not the case are you able to provide additional details such as country connecting from and profile page not working?

**Comment by darthclide** [comment] 2019-11-07 16:50
You can delete this thread. It is all of a sudden working now. Very weird... It wasn't working when I went to bed, but now it is. Sorry for wasting your time :(

**Comment by llacb47** [comment] 2019-11-07 16:52
Close the issue

**Comment by darthclide** [comment] 2019-11-07 16:56
I was hoping a mod would delete this thread. So as to not confuse anyone.

**Closed** 2019-11-07 16:56 UTC
