### ISSUE TITLE
App promotional annoyance at reddit.com on mobile

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4022] opened 2018-11-04 07:39 UTC
### URL(s) where the issue occurs

`reddit.com`

### Describe the issue

Sticky footer at the bottom of page on mobile, promoting app usage.

### Versions

- Browser/version: Firefox for Android 63.0
- uBlock Origin version: 1.17.2

### Settings

Annoyances filter

### Notes

On first load, there's a big `www.reddit.com##.nightmode.amp.SnackBar`.

On subsequent loads, there's a small `www.reddit.com##.XPromoPill`.

**Comment by okiehsch** [comment] 2018-11-04 20:43
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/3971

**Closed by okiehsch** 2018-11-04 20:43 UTC
