### ISSUE TITLE
iqiyi.com [Anti adblock]

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#4291] opened 2018-12-11 03:37 UTC
URL : https://www.iqiyi.com/v_19rqswah0s.html
![image](https://user-images.githubusercontent.com/45059308/49776889-fe39d900-fd38-11e8-9176-831671348a69.png)

My Settings bakcup : 
[my-ublock-backup_2018-12-11_11.36.46.txt](https://github.com/uBlockOrigin/uAssets/files/2665849/my-ublock-backup_2018-12-11_11.36.46.txt)

**Comment by discusssth** [comment] 2018-12-11 03:46
If you can't reproduce it at once, you can try switching more videos. This ad doesn't appear every time.

**Comment by discusssth** [comment] 2018-12-11 03:57
@@||t7z.cupid.iqiyi.com/show$script,first-party
I manually added this rule to the custom list, still appear anti-adblock prompt ,
you can try switching more videos

**Comment by okiehsch** [comment] 2018-12-11 04:08
The message in your screenshot 
![image](https://user-images.githubusercontent.com/16838044/49777844-7638dc80-fd02-11e8-8b84-0e061cc9017a.png)
is fixed with the filter on my end. It does not appear even if I switch videos.

**Comment by okiehsch** [comment] 2018-12-11 04:10
I have enabled the two chinese filter lists and btw, I would suggest that you open these issues in their tracker. They can atleast read the characters.

**Comment by accountforadg** [comment] 2018-12-11 04:16
http://www.iqiyi.com/u/2014291207
still anti adblock

I re-cleaned the browser cache to make sure my test results were correct.
To ensure the correct results, I also used a VPN in the United States.

Can you try it with my profile?
[my-ublock-backup_2018-12-11_12.14.37.txt](https://github.com/uBlockOrigin/uAssets/files/2665930/my-ublock-backup_2018-12-11_12.14.37.txt)

**Comment by discusssth** [comment] 2018-12-11 04:17
@okiehsch 
http://www.iqiyi.com/u/2014291207
still anti adblock

I re-cleaned the browser cache to make sure my test results were correct.
To ensure the correct results, I also used a VPN in the United States.

Can you try it with my profile?
my-ublock-backup_2018-12-11_12.14.37.txt

**Comment by okiehsch** [comment] 2018-12-11 04:19
No, but if somebody wants to have a go at it ....

**Comment by discusssth** [comment] 2018-12-11 04:43
@okiehsch  Can you come over and debug remotely? I have a teaviewer.

**Comment by jspenguin2017** [comment] 2018-12-11 15:45
https://github.com/NanoAdblocker/NanoFilters/issues/172
EasyList can't really handle ads timers.

**Comment by discusssth** [comment] 2019-02-26 01:43
@LiCybora need help

**Comment by LiCybora** [comment] 2019-02-26 03:20
Add this:
`iqiyi.com##+js(nano-setInterval-booster.js)`

**Comment by discusssth** [comment] 2019-02-26 03:27
@LiCybora    thank you ,   works for me!!

**Closed** 2019-02-26 07:26 UTC

**Comment by discusssth** [comment] 2019-08-02 05:12
@LiCybora   

> iqiyi.com##+js(nano-setInterval-booster.js)
not work... now

**Comment by discusssth** [comment] 2019-08-14 04:30
need help

**Comment by discusssth** [comment] 2019-08-14 04:30
problem still exist.

**Comment by jspenguin2017** [comment] 2019-08-15 00:54
I can't reproduce. I recommend you to open a new issue with updated details.
