### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by giribonilorenzo** [uBlockOrigin/uAssets#14631] opened 2022-09-01 17:21 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/luidematos`

### Category

twitch ads

### Describe the issue

the stream is exibithing a commercial break with ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 83946
  cosmetic: 45901
  scriptlet: 17973
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 67065-51, 2d.19h.6m
    easyprivacy: 27442-126, 2d.19h.5m
    plowe-0: 3633-776, 11d.15h.18m
    spa-1: 4605-77, 2d.19h.7m
    ublock-abuse: 76-0, 2d.19h.9m
    ublock-badware: 4162-96, 2d.19h.4m
    ublock-filters: 32471-133, 2d.19h.3m
    ublock-privacy: 241-3, 2d.19h.8m
    ublock-quick-fixes: 405-4, 13h.32m
    ublock-unbreak: 1845-42, 2d.19h.2m
    urlhaus-1: 7339-0, 13h.31m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 385 ms
  maxAssetCacheWait: 112 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
    sentry.io: 1
```
</details>

**Comment by MasterKia** [comment] 2022-09-01 17:26
- [X] I verified that the issue has not already been reported (use this button to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-09-01 17:26
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-09-01 17:26 UTC
