### ISSUE TITLE
fandom.com - Sponsered Search Items

### ISSUE THREAD

**Issue by 0button1** [uBlockOrigin/uAssets#10051] opened 2021-09-21 10:22 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
```

https://quake.fandom.com/wiki/Quake_Wikia
https://masseffect.fandom.com/wiki/Mass_Effect_Wiki
https://halo.fandom.com/wiki/Halo_Alpha

```
### Describe the issue

When using the search box, a sponsored URL appears at the top. It's malignant, and every time I've tried to kill it, another has taken it's place. This happens across ALL fandom.com sites, three of which I'll be using as examples.

### Screenshot(s)

<img width="737" alt="Screenshot 2021-09-21 201544" src="https://user-images.githubusercontent.com/91125526/134154150-cefaa2c2-f727-460e-85a7-7a83d9fbe527.png">

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0 (64 Bit)

### Settings

A hell of a lot of lines in the custom blocking list

**Comment by uBlock-user** [comment] 2021-09-21 10:35
was fixed in https://github.com/uBlockOrigin/uAssets/issues/9607

**Comment by ExtremelyCool** [comment] 2021-09-22 22:12
@uBlock-user I have encountered with a US IP.

**Comment by uBlock-user** [comment] 2021-09-23 05:04
@ExtremelyCool Come up with a filter and I will add it.

**Closed by uBlock-user** 2021-09-23 05:04 UTC
Labels: unable to reproduce

**Comment by okiehsch** [comment] 2021-09-23 07:25
I can't reproduce the ads in your screenshot with a US IP.

**Comment by ExtremelyCool** [comment] 2021-09-23 21:03
> @ExtremelyCool Come up with a filter and I will add it.
^ @uBlock-user 


Is `##[href^="https://bridge.lga1.ap01.net/ct"]` good enough?

@ryanbr could you take a look?

**Comment by ExtremelyCool** [comment] 2021-09-23 21:45
Also, is should connections to `45tu1c0.com` be blocked?

**Comment by ExtremelyCool** [comment] 2021-09-23 22:02
@uBlock-user What about
```
fandom.com##.instant-suggestion
||45tu1c0.com^
```

**Comment by uBlock-user** [comment] 2021-09-23 22:03
Not seeing any connections to that domain in ever, whether I'm logged in or not.

**Comment by ExtremelyCool** [comment] 2021-09-23 22:06
With a US IP?

**Comment by uBlock-user** [comment] 2021-09-23 22:08
Neither.

**Comment by ExtremelyCool** [comment] 2021-09-23 22:10
So, do you type anything?

**Comment by ExtremelyCool** [comment] 2021-09-23 22:10
Have you tried typing "Amazon"?

**Comment by ExtremelyCool** [comment] 2021-09-23 22:11
Have you tried typing "amazon"?

**Comment by ExtremelyCool** [comment] 2021-09-23 22:12
![image](https://user-images.githubusercontent.com/90566652/134590918-d9b9352d-ed70-4a04-8b55-fc4dba530636.png)

**Comment by uBlock-user** [comment] 2021-09-23 22:14
tried wtih singular letters like `e` and `a` and now `amazon`, nothing.

**Comment by ExtremelyCool** [comment] 2021-09-23 22:16
![image](https://user-images.githubusercontent.com/90566652/134591243-2f5f68ec-4336-42d9-a51a-3690ae1e429e.png)

**Comment by ExtremelyCool** [comment] 2021-09-23 22:16
https://user-images.githubusercontent.com/90566652/134591304-da5f1870-b148-4377-b101-6ed9de2eb46b.mp4

**Comment by ExtremelyCool** [comment] 2021-09-23 22:36
@Yuki2718 @yourduskquibbles @mapx-

**Comment by uBlock-user** [comment] 2021-09-24 05:59
Added as suggested, but this hasn't been tested as no-one here can reproduce it.
