### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by theairbend3r** [uBlockOrigin/uAssets#7035] opened 2020-03-01 05:30 UTC
### URL(s) where the issue occurs

`https://www.linkedin.com/feed/`

### Describe the issue

The images, video, and a few other things on the page do not load. They load once I disable uBlockOrigin. But when I disable it, the ADs start showing too. 

### Screenshot(s)

NA

### Versions

- Browser/version: [Firefox/73.0.1 (64-bit)]
- uBlock Origin version: [1.25.0]

### Settings

No changes to default settings.

### Notes

I switched off other extensions to test if it's happening because of uBlockOrigin. It is. I think uBlock stops some URLs which are responsible for loading images/videos on LinkedIn.

**Comment by okiehsch** [comment] 2020-03-01 05:52
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7012
Already fixed, update your filter lists.

**Closed by okiehsch** 2020-03-01 05:52 UTC
