### ISSUE TITLE
portal.afterpay.com: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16856] opened 2023-02-20 09:32 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://portal.afterpay.com/au/login-email`

### Category

breakage

### Description

With uBlock enabled, the login doesn't appear.
With uBlock disabled, it works like it should.
![Afterpay](https://user-images.githubusercontent.com/20948631/220066991-bec1c31b-672c-4e23-a70a-75b6637ff833.png)
![Good`](https://user-images.githubusercontent.com/20948631/220066995-fb4ad273-7158-4871-9267-572cdf22799b.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 268476
  cosmetic: 218663
  scriptlet: 38601
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38481-3629, 2d.11h.14m
    https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 92163-0, 3m
    https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt: 63690-252, 2d.11h.14m
    https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt: 38006-37544, 2d.11h.14m
    adguard-annoyance: 64174-61186, 2d.11h.14m
    adguard-generic: 68249-1215, 2d.11h.14m
    adguard-social: 19847-835, 2d.11h.14m
    block-lan: 44-0, 2d.11h.14m
    curben-phishing: 36073-39, 5m
    curben-pup: 193-0, 4m
    dpollock-0: 11396-171, 2d.11h.14m
    fanboy-annoyance: 83970-6681, 2d.11h.14m
    fanboy-thirdparty_social: 69-20, 2d.11h.14m
    ublock-annoyances: 4834-243, 2d.11h.14m
  default: 
    user-filters: 10-0, never
    easylist: 61924-1129, 2d.11h.14m
    easyprivacy: 30981-12399, 2d.11h.14m
    plowe-0: 3675-1347, 2d.11h.14m
    ublock-abuse: 79-0, 2d.11h.14m
    ublock-badware: 4368-321, 2d.11h.14m
    ublock-filters: 32732-4018, 2d.11h.14m
    ublock-privacy: 274-58, 2d.11h.14m
    ublock-quick-fixes: 175-22, 2m
    ublock-unbreak: 1900-114, 2d.11h.14m
filterset (user): [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7152 ms (selfie)
  maxAssetCacheWait: 755 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    afterpay.com: 4
    amplitude.com: 13
    cdndex.io: 2
    facebook.com: 1
    fbot.me: 9
    google-analytics.com: 1
    googletagmanager.com: 2
    launchdarkly.com: 10
    sentry.io: 9
    zdassets.com: 1
```
</details>

**Comment by krystian3w** [comment] 2023-02-20 10:18
Bad filter is in custom subscribed list:

<details>

> ```yml
>  added: 
>     https://filters.adtidy.org/extension/ublock/filters/3.txt: 38481-3629, 2d.11h.14m
>     https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 92163-0, 3m
>     https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt: 63690-252, 2d.11h.14m
>     https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt: 38006-37544, 2d.11h.14m
>     adguard-annoyance: 64174-61186, 2d.11h.14m
>     adguard-generic: 68249-1215, 2d.11h.14m
>     adguard-social: 19847-835, 2d.11h.14m
>     block-lan: 44-0, 2d.11h.14m
>     curben-phishing: 36073-39, 5m
>     curben-pup: 193-0, 4m
>     dpollock-0: 11396-171, 2d.11h.14m
>     fanboy-annoyance: 83970-6681, 2d.11h.14m
>     fanboy-thirdparty_social: 69-20, 2d.11h.14m
>     ublock-annoyances: 4834-243, 2d.11h.14m
> ```

</details>

**Comment by krystian3w** [comment] 2023-02-20 10:34
BTW you should remove:
```yml
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
```

both are duplicate of `https://filters.adtidy.org/extension/ublock/filters/` where correctly works exclusion "`!+ PLATFORM`".

**Comment by krystian3w** [comment] 2023-02-20 10:49
https://github.com/easylist/easylist/issues/10782 https://github.com/easylist/easylist/issues/7619

**Comment by TesterMan247** [comment] 2023-02-20 11:23
> BTW you should remove:
> 
> ```yaml
> https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
> https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
> ```
> 
> both are duplicate of `https://filters.adtidy.org/extension/ublock/filters/3.txt` and `adguard-annoyance` where correctly works exclusion "`!+ PLATFORM`" - More than 100 filters are not tested how they work with uBO (e.g., dedicated for iOS or intentionally excluded from uBO) when you use the raw version from github.

Thanks for the advise and the fix.
I removed the two filters you suggested I remove.

**Comment by ghajini** [comment] 2023-02-20 14:13
@ryanbr

**Closed by ghajini** 2023-02-20 14:13 UTC
