### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by KaiGrove** [uBlockOrigin/uAssets#12981] opened 2022-04-27 11:38 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=aJKynbTap1w`

### Category

ads

### Describe the issue

ads apeared with u block on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 84114
  cosmetic: 46150
  scriptlet: 16739
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5637-0, 37m
    easylist: 66365-57, 3d.50m
    easyprivacy: 26862-132, 3d.49m
    plowe-0: 3682-805, 7d.1h.53m
    ublock-abuse: 74-0, 7d.1h.51m
    ublock-badware: 4098-93, 3d.48m
    ublock-filters: 30888-118, 3d.47m
    ublock-privacy: 212-2, 7d.1h.47m
    ublock-quick-fixes: 181-0, 36m
    ublock-unbreak: 1766-43, 3d.46m
    urlhaus-1: 8643-0, 35m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 309 ms (selfie)
  maxAssetCacheWait: 179 ms
popupPanel: 
  blocked: 143
  blockedDetails: 
    youtube.com: 100
    doubleclick.net: 9
    google.com: 15
    google.de: 1
    googlesyndication.com: 16
    googlevideo.com: 2
```
</details>

**Comment by krystian3w** [comment] 2022-04-27 12:38
Duplicate of #7636

**Closed** 2022-04-27 13:19 UTC
Labels: duplicate
