### ISSUE TITLE
cocomanga.com: detection

### ISSUE THREAD

**Issue by chew85** [uBlockOrigin/uAssets#11095] opened 2021-12-27 20:49 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.cocomanga.com/21971/1/3.html`

### Category

detection

### Describe the issue

Website detected AdBlock app

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 96
filterset (summary): 
  network: 80014
  cosmetic: 21703
  scriptlet: 16233
  html: 603
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30435-196, 21h.40m
    ublock-badware: 3633-1, 21h.39m
    ublock-privacy: 181-1, 21h.38m
    ublock-abuse: 72-0, 21h.37m
    ublock-unbreak: 1696-0, 21h.35m
    adguard-mobile: 7014-170, 21h.45m
    easylist: 62259-24115, 21h.34m
    easyprivacy: 26553-489, 21h.33m
    urlhaus-1: 8152-0, 21h.30m
    plowe-0: 3679-3, 14h.31m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 352 ms (selfie)
popupPanel: 
  blocked: 29
```
</details>

**Comment by gorhill** [comment] 2021-12-27 20:57
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/11090>.

**Closed by gorhill** 2021-12-27 20:57 UTC
