### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by mcemka** [uBlockOrigin/uAssets#14661] opened 2022-09-03 19:30 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=VuYYaZDNJXc&list=RDX89yw3J-a_s&index=19`

### Category

ads

### Describe the issue

randomly starts to play ads while i am focused on some other task 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82640
  cosmetic: 41894
  scriptlet: 17782
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65652-51, 2h.54m
    easyprivacy: 27454-126, 2h.53m
    plowe-0: 3671-813, 2h.52m
    ublock-abuse: 76-0, 2h.50m
    ublock-badware: 4202-101, 2h.48m
    ublock-filters: 32490-110, 2h.47m
    ublock-privacy: 241-1, 2h.45m
    ublock-quick-fixes: 413-4, 2h.44m
    ublock-unbreak: 1846-41, 2h.43m
    urlhaus-1: 7674-0, 2h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4248 ms
  maxAssetCacheWait: 508 ms
popupPanel: 
  blocked: 1589
  blockedDetails: 
    youtube.com: 1287
    doubleclick.net: 11
    google.com: 270
    googleadservices.com: 6
    googlesyndication.com: 6
    googlevideo.com: 9
```
</details>

**Comment by MasterKia** [comment] 2022-09-04 01:19
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by MasterKia** [comment] 2022-09-04 01:19
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by MasterKia** 2022-09-04 01:19 UTC
