### ISSUE TITLE
senda.pl: detection

### ISSUE THREAD

**Issue by mailing12** [uBlockOrigin/uAssets#16728] opened 2023-02-13 10:49 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Anti-adblock modal (looks as soft but on every refresh)

### URL(s) where the issue occurs.

`https://senda.pl/`

### Screenshot(s)

https://user-images.githubusercontent.com/122281951/218439486-ef04818e-ad94-4dee-ab02-d370e35c5aea.jpg

### uBO version

1.46.0

### Browser name and version

Firefox 109 / Chrome 109

### Settings

enabled:
- POL-0
- POL-2
- uBo Annoyances

### Notes

Based on generic `/utep_ad`

So works simple:
```adb
@@||senda.pl/ads/utep_ad.js$script,domain=senda.pl
```
newbie method match modal:

```adb
senda.pl##.modal[style*="background"]
```

Also can by disabled by one of four scriptlets:

```adb
senda.pl##+js(set, adBlockDetected, noopFunc)
senda.pl##+js(acis, adBlockDetected)
senda.pl##+js(aopr, adBlockDetected)
senda.pl##+js(aopr, importFAB)
```

mirror for @olegwukr: https://github.com/MajkiIT/polish-ads-filter/issues/21444

**Comment by mailing12** [comment] 2023-02-13 10:50
#16295

**Comment by garry-ut99** [comment] 2023-02-13 12:52
I can reproduce, but it doesn't change the fact, that it's a duplicate of https://github.com/uBlockOrigin/uAssets/issues/16295, the form was abused.

> To rule out invalid issues, confirm and check each one of the checkboxes.
> * [ ]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.

**Closed** 2023-02-13 12:53 UTC
