### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by kidgrit** [uBlockOrigin/uAssets#14419] opened 2022-08-17 18:47 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

breakage

### Describe the issue

Basically before you could click on shuffle or loop to break out of the ad pause and continue listening to music but now that doesnt work and there's no way to listen to music without listening to the ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80566
  cosmetic: 45321
  scriptlet: 17652
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69506-51, 19h.23m
    easyprivacy: 27348-127, 19h.22m
    plowe-0: 3634-776, 7d.12h.17m
    ublock-abuse: 76-0, 8d.7h.25m
    ublock-badware: 4233-92, 19h.21m
    ublock-filters: 32513-120, 19h.20m
    ublock-privacy: 231-3, 8d.7h.24m
    ublock-quick-fixes: 389-37, 19h.18m
    ublock-unbreak: 1858-43, 19h.19m
    urlhaus-1: 5167-0, 19h.17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 307 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 2
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 1
    spotifycdn.com: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-17 18:54
> - [X]  I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")

Do it twice and test again.

https://github.com/uBlockOrigin/uAssets/issues/14231

**Comment by 0x416c69** [comment] 2022-08-18 20:20
@okiehsch It's been working fine since changing to 1s noop sound but now it's broken again:

![chrome_2022-08-19_00-31-06](https://user-images.githubusercontent.com/10671711/185486344-93cb613a-1b83-42c1-9309-ad2f8f5307a1.png)

This is a bit hard to reproduce, spotify doesn't always play the same amount of ads and tends to play different amount of ads based on the time of day, also don't forget to hard refresh before trying to reproduce this.

**Comment by z-aki** [comment] 2022-08-20 17:00
Steps to redo:
- Open your liked songs playlist or any other long one.
- keep skipping songs. Every 15th song, there will be an ad.
- First two ads will be skipped fine by uBO and next track will automatically start playing. 
- on the third case however (i.e ~45th song ) a mute audio will play for the length of the ad.
  -  The skip buttons won't work
  - after 30s, nothing will change, ad banner will be there, no audio will be playing, audio slider will be at 30s, next track will not be played
  - Double clicking on the song in the playlist will restart the ad audio again, muted still.
  - Only way to break out is to refresh the page, but now the song position is lost and you have to scroll down to find which one you were playing.

I have this version of filter list
```
! Last modified: Sat, 20 Aug 2022 13:21:21 +0000
```
```
! https://github.com/uBlockOrigin/uAssets/issues/448
! https://github.com/uBlockOrigin/uAssets/issues/724
! https://github.com/uBlockOrigin/uAssets/issues/14231
||spotify.com/storage-resolve/files/audio/interactive/*$xhr,domain=open.spotify.com
||akamaized.net/audio/*$media,redirect=noopmp4-1s,domain=open.spotify.com
||scdn.co/audio/*$media,redirect=noopmp4-1s,domain=open.spotify.com
open.spotify.com##[href^="https://adclick.g.doubleclick.net/"]
! https://github.com/uBlockOrigin/uAssets/issues/7620
open.spotify.com###leaderboard-ad-element
```

**Comment by okiehsch** [comment] 2022-08-20 17:32
> on the third case however

I can reproduce, can you test
`||spotify.com/storage-resolve/files/audio/interactive/$badfilter,xhr,domain=open.spotify.com`
 by adding it to your filter list and reload a playlist, it appears to be working on my end.

**Comment by z-aki** [comment] 2022-08-20 17:36
> > on the third case however
> 
> I can reproduce, can you test `||spotify.com/storage-resolve/files/audio/interactive/$badfilter,xhr,domain=open.spotify.com` by adding it to your filter list and reload a playlist, it appears to be working on my end.

Yes it's fixed!

**Comment by okiehsch** [comment] 2022-08-20 17:37
Ok, I pushed the fix, if you update `uBlock filters` list in a few minutes you can remove the mentioned filter from your list.

**Closed by okiehsch** 2022-08-20 17:37 UTC
Labels: unable to reproduce

**Comment by kidgrit** [comment] 2022-08-21 01:40
> > * [x]   I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")
> 
> Do it twice and test again.
> 
> #14231

I did this and it's fixed. I apologize for any waste of time I might have caused. Thank you - Next time I will do this double purge before posting.
