### ISSUE TITLE
genius.com ad placeholders

### ISSUE THREAD

**Issue by kah0922** [uBlockOrigin/uAssets#10385] opened 2021-11-03 17:17 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://genius.com/Slipknot-wait-and-bleed-lyrics`

### Describe the issue

Various placeholders for ads are placed with random names when browsing a mobile page on genius.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9474213/140142174-56dcbac3-8b5e-4f34-9f02-9df3441a6caf.png)

### uBlock Origin version

1.386

### Browser name and version

Firefox Nightly

### Settings

N/A

### Notes

`genius.com##div[class*="Admobile"]`
`genius.com##div[class*="Ad__"]`

Should fix this.

**Comment by felix-22** [comment] 2021-11-03 17:31
### 1

A duplicate of https://github.com/uBlockOrigin/uAssets/issues/9446

> kah0922 :
> ### Prerequisites
> [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is:issue+is:open+sort:updated-desc) to avoid opening a duplicate issue

Really? How? Simply typing `genius.com` in tracker search results proves there is already the same thread with sme title: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+genius.com

### 2

> kah0922 :
> `genius.com##div[class*="Admobile"]`
> `genius.com##div[class*="Ad__"]`
>
> Should fix this.

Filters which don't require uBO advanced syntax should be reported at EasyList issue tracker, as advised: 
- in the thread you just have duplicated: https://github.com/uBlockOrigin/uAssets/issues/9446#issuecomment-864603760
- in the readme https://github.com/uBlockOrigin/uAssets#readme which  you most likely have not even read...:
> The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html), also taking into account whether a filter requires uBO's extended filter syntax.
> 
> If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

**Closed** 2021-11-03 17:34 UTC

**Comment by uBlock-user** [comment] 2021-11-03 17:36
@ryanbr
