### ISSUE TITLE
Youtube videos unable to play with ublock on

### ISSUE THREAD

**Issue by ZeroXSEED** [uBlockOrigin/uAssets#11132] opened 2021-12-30 00:47 UTC
### Prerequisites

- [ ] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [ ] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

www.youtube.com

### Describe the issue

I don't remember when it started but likely somewhere last week, but after updating my firefox browser to 91.4.1 esr ublock would block ALL Youtube videos, making it impossible to watch.
ublock use these setting and no additional filters.
Browser profile is default

### Screenshot(s)

![2021-12-30 07_36_22-The Insane Scooter for European Executives_ Suzuki Burgman 650 - YouTube — Mozil](https://user-images.githubusercontent.com/96850135/147712988-5280fd42-b7b9-4a86-be32-5f9254305cff.jpg)
![2021-12-30 07_37_54-The Insane Scooter for European Executives_ Suzuki Burgman 650 - YouTube — Mozil](https://user-images.githubusercontent.com/96850135/147712991-0759b5a7-3252-4b60-a476-a7e54151c54d.jpg)
![2021-12-30 07_43_54-uBlock₀ — Dashboard — Mozilla Firefox](https://user-images.githubusercontent.com/96850135/147713042-377d16d6-a0bc-40aa-8995-d744089bd25e.jpg)
![2021-12-30 07_43_31-uBlock₀ — Dashboard — Mozilla Firefox](https://user-images.githubusercontent.com/96850135/147713044-c42ad127-0578-4d1a-9031-723b6b367c11.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 91
filterset (summary): 
  network: 74843
  cosmetic: 0
  scriptlet: 16381
  html: 612
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1035-0, 6d.11h.36m
  default: 
    ublock-filters: 30631-7271, 39m
    ublock-badware: 3635-400, 1d.20h.36m
    ublock-privacy: 181-12, 1d.20h.34m
    ublock-abuse: 81-4, 1d.20h.35m
    ublock-unbreak: 1721-210, 1d.21h.36m
    easylist: 56709-31995, 2d.9h.8m
    easyprivacy: 26553-815, 2d.21h.42m
    urlhaus-1: 8445-0, 37m
    plowe-0: 3679-4, 2d.21h.43m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  parseAllABPHideFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1561 ms (selfie)
```
</details>

**Comment by iam-py-test** [comment] 2021-12-30 01:14
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636
@ZeroXSEED, please check for redundant issues before opening a new issue. This will save everyone involved lots of time and ensure your issue is fixed sooner.

**Closed** 2021-12-30 06:04 UTC

**Comment by iam-py-test** [comment] 2021-12-30 12:50
@ZeroXSEED I can not reproduce:
![image](https://user-images.githubusercontent.com/84232764/147753487-36ac6233-6ce1-4adc-a7cc-2cadfaf52b33.png)
Try disabling all other extensions and DNS adblocking

**Comment by gwarser** [comment] 2021-12-30 13:13
>ublock would block ALL Youtube videos, making it impossible to watch.

But they are clearly visible on your screenshots? 

Do you mean they are not auto-playing? Click the crossed out play button in address bar.

**Comment by iam-py-test** [comment] 2021-12-30 13:18
Well, Firefox blocks autoplay by default. That's the problem

**Comment by gorhill** [comment] 2021-12-30 13:20
There is a difference between both screenshots though, one is buffering (uBO disabled) while the other there is no buffering (uBO enabled). In any case, without @ZeroXSEED participating to this thread, it's a dead end and nothing will happen since nobody can reproduce such issue.

**Comment by uBlock-user** [comment] 2021-12-30 13:20
> Firefox blocks autoplay by default. That's the problem

No, click-to-play is required to block Youtube's autoplay which only occurs when `media.autoplay.default` is set to `5` and `media.autoplay.blocking_policy` is set to `2`

**Comment by iam-py-test** [comment] 2021-12-30 13:21
Hmm...

**Comment by gorhill** [comment] 2021-12-30 13:22
Possibly video downloader extension is interfering, @ZeroXSEED failed to verify as asked that the issue still occurs with only uBO.

**Comment by iam-py-test** [comment] 2021-12-30 13:25
Could https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt interfere or conflict with another extension?

**Comment by gwarser** [comment] 2021-12-30 13:29
I have issues like second screenshot where playback is blocked and clicking on video content does not start it, but I have autoplay blocked like uBlock-user explained above, I'm logged out, and have consent/login dialogs blocked (and more, non-default lists/filters)

I use space button to start such blocked videos. Play button in lower left corner should work too, but it's harder to reach.

**Comment by uBlock-user** [comment] 2021-12-30 13:32
> clicking on video content does not start it, but I have autoplay blocked

Behavioural quirks of click-to-play mode, Firefox team is aware of such breakage.
