### ISSUE TITLE
eksisozluk.com: breakage

### ISSUE THREAD

**Issue by Nonpasaran** [uBlockOrigin/uAssets#14592] opened 2022-08-30 09:00 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eksisozluk.com/`

### Category

breakage

### Describe the issue

There is a button which change site theme; "her zamanki gorunume don" not work when ublock working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Enpedi© - 2022-08-30- 11-54-34](https://user-images.githubusercontent.com/1097289/187394744-f1ee93eb-19e8-416b-acbb-d2235e0a68b7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82239
  cosmetic: 43179
  scriptlet: 17716
  html: 0
listset (total-discarded, last updated): 
  removed: 
    TUR-0: null
  default: 
    user-filters: 0-0, never
    easylist: 67214-51, 1d.13h.49m
    easyprivacy: 27439-126, 1d.13h.48m
    plowe-0: 3635-777, 11d.15h.26m
    ublock-abuse: 76-0, 11d.16h.58m
    ublock-badware: 4162-96, 1d.13h.47m
    ublock-filters: 32492-121, 1d.13h.46m
    ublock-privacy: 231-3, 11d.15h.28m
    ublock-quick-fixes: 398-4, 15h.51m
    ublock-unbreak: 1841-41, 1d.13h.45m
    urlhaus-1: 7021-0, 15h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 624 ms (selfie)
  maxAssetCacheWait: 137 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adform.net: 1
    adrecover.com: 1
    criteo.net: 1
    doubleclick.net: 2
    googleadservices.com: 1
    googletagmanager.com: 1
    nativespot.com: 1
    networkad.net: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-30 10:53
> - [X] I verified that the issue has not already been reported (use this button to find out)

Comment here: https://github.com/uBlockOrigin/uAssets/issues/14464

**Comment by MasterKia** [comment] 2022-08-30 10:53
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14464

**Closed** 2022-08-30 10:54 UTC
Labels: duplicate
