### ISSUE TITLE
fb.com: ads

### ISSUE THREAD

**Issue by DiAnTTA** [uBlockOrigin/uAssets#11181] opened 2022-01-03 01:30 UTC
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`fb.com`→`https://m.facebook.com/`

### Category

ads

### Describe the issue

Sponsored

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![chrome_screenshot_3 thg 1, 2022 08_14_36 GMT+07_00](https://user-images.githubusercontent.com/74956696/147894331-5deb06e2-d547-4310-afdc-00863b81751f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium Mobile: 98
Kiwi Browser: 98.0.4758.29
filterset (summary): 
  network: 80442
  cosmetic: 46936
  scriptlet: 16461
  html: 0
listset (total-discarded, last updated): 
  default: 
    VIE-1: 2351-0, 12m
    adguard-mobile: 7028-19, 12m
    easylist: 62467-225, 10m
    easyprivacy: 26582-30, 9m
    plowe-0: 3682-905, 8m
    ublock-abuse: 76-0, 8m
    ublock-badware: 3644-65, 7m
    ublock-filters: 30130-157, 8m
    ublock-privacy: 185-3, 8m
    ublock-unbreak: 1714-39, 8m
    urlhaus-1: 7568-0, 8m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1701 ms
popupPanel: 
  blocked: 1
```
</details>

**Comment by uBlock-user** [comment] 2022-01-03 05:53
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/3367

**Closed by uBlock-user** 2022-01-03 05:53 UTC

**Comment by iam-py-test** [comment] 2022-01-03 16:10
@DiAnTTA please check for redundant issues _before_ opening a new one
