### ISSUE TITLE
repubblica.it: breakage

### ISSUE THREAD

**Issue by MilosBranko** [uBlockOrigin/uAssets#15483] opened 2022-10-31 09:12 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.repubblica.it/podcast/audioarticoli?pubdate=2022-10-29`

### Category

breakage

### Describe the issue

Nothing of this page content (video icons and descriptions) appears in the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 94050
  cosmetic: 45886
  scriptlet: 16596
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31841-60, 2m
    ublock-badware: 3957-0, 2m
    ublock-privacy: 288-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1888-0, 2m
    ublock-quick-fixes: 447-0, 2m
    easylist: 62631-633, 2m
    easyprivacy: 30832-1709, 2m
    urlhaus-1: 11029-0, 1m
    plowe-0: 3669-3, 1m
    ITA-0: 13233-1, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1188 ms (selfie)
  maxAssetCacheWait: 1534 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    repubblica.it: 1
    admantx.com: 1
    chartbeat.com: 2
    gedidigital.it: 3
    google.com: 5
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    imrworldwide.com: 1
    iubenda.com: 1
    kataweb.it: 1
    opecloud.com: 4
    viafoura.co: 1
    wbtrk.net: 1
    wt-safetag.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-10-31 09:15
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/15482

**Closed** 2022-10-31 09:14 UTC
Labels: duplicate
