### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by soymadip** [uBlockOrigin/uAssets#14428] opened 2022-08-19 06:11 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=O3E5hScmSwo`

### Category

ads

### Describe the issue

when youtube is installed as PWA, it shows ads(also when as browser window but it shows more as PWA.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 181567
  cosmetic: 216968
  scriptlet: 37838
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt: 244-44, 1h.6m
    adguard-annoyance: 56479-80, 1h.7m
    adguard-generic: 67046-699, 1h.6m
    adguard-mobile: 8154-58, 1h.6m
    adguard-social: 18227-868, 1h.6m
    adguard-spyware: 26471-1047, 1h.6m
    adguard-spyware-url: 718-1, 1h.6m
    block-lan: 43-0, 1h.6m
    curben-phishing: 43914-0, 1h.6m
    dpollock-0: 11381-256, 1h.6m
    fanboy-annoyance: 79568-4638, 1h.6m
    fanboy-cookiemonster: 40174-40174, 1h.6m
    ublock-annoyances: 4524-238, 1h.6m
  default: 
    user-filters: 18-0, never
    easylist: 69582-1396, 1h.6m
    easyprivacy: 27390-9642, 1h.6m
    plowe-0: 3635-1317, 1h.6m
    ublock-abuse: 76-0, 1h.6m
    ublock-badware: 4243-330, 1h.6m
    ublock-filters: 32527-3923, 1h.6m
    ublock-privacy: 231-44, 1h.6m
    ublock-quick-fixes: 409-48, 1h.6m
    ublock-unbreak: 1829-105, 1h.5m
    urlhaus-1: 4611-1, 1h.5m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3047 ms (selfie)
  maxAssetCacheWait: 1154 ms
popupPanel: 
  blocked: 51
  blockedDetails: 
    youtube.com: 43
    doubleclick.net: 1
    google.co.in: 1
    google.com: 2
    googlesyndication.com: 1
    googlevideo.com: 3
```
</details>

**Comment by MasterKia** [comment] 2022-08-19 07:02
> - [X] I verified that the issue has not already been reported (use this button to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-19 07:02 UTC

**Comment by MasterKia** [comment] 2022-08-19 07:04
You don't need to use the "adguard-mobile" list on the desktop.
