### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by alphanightshift** [uBlockOrigin/uAssets#13692] opened 2022-06-13 16:16 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

https://www.youtube.com/watch?v=DX5H9xq1pxk&t=443s
https://www.youtube.com

### Category

ads

### Describe the issue

Occasionally when I use YouTube, these ads still bypass the filters (these are grayed since I used element picker and only that part). I also tried to delete browser data, used new user, the EasyList solutions etc, but it will return after couple hours/days. I'm using Vivaldi latest version.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-06-13 23 04 25 www youtube com 16f3768e58bb](https://user-images.githubusercontent.com/89926147/173397805-5b1869be-1c04-4a85-a30f-04a50178ce9e.png)
![2022-06-13 23 06 00 www youtube com 4e440ad36967](https://user-images.githubusercontent.com/89926147/173397860-af0f928f-c003-442f-8139-6c82b01840cf.png)

</details>

### Configuration

uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 214851
  cosmetic: 195227
  scriptlet: 55275
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-136, 1h.19m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25164-207, 1d.3h.37m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-1, 3d.13h.35m
    https://www.i-dont-care-about-cookies.eu/abp/: 24981-13502, 1h.10m
    CHN-0: 29097-1174, 3d.14h.36m
    IDN-0: 8931-3553, 3d.13h.34m
    JPN-1: 7237-134, 3d.13h.33m
    KOR-1: 1840-73, 1h.18m
    RUS-0: 41670-940, 1h.20m
    THA-0: 1028-8, 1d.3h.38m
    VIE-1: 1764-35, 1h.17m
    adguard-annoyance: 54017-2692, 3d.13h.32m
    adguard-generic: 64682-2422, 3d.13h.31m
    adguard-mobile: 7838-140, 3d.13h.30m
    adguard-social: 17654-1959, 3d.13h.29m
    adguard-spyware: 26196-935, 3d.13h.28m
    adguard-spyware-url: 627-13, 3d.13h.27m
    block-lan: 43-0, 3d.4h.3m
    curben-phishing: 21376-1, 1h.17m
    curben-pup: 231-0, 1h.17m
    [7 lists not shown]: [too many]
  default: 
    user-filters: 15-2, never
    easylist: 68106-25314, 3d.13h.26m
    easyprivacy: 27180-10591, 3d.13h.24m
    plowe-0: 3639-1316, 6d.1h.30m
    ublock-abuse: 75-6, 7d.2h.27m
    ublock-badware: 4171-307, 3d.13h.21m
    ublock-filters: 31805-6723, 3d.13h.20m
    ublock-privacy: 222-49, 6d.13h.40m
    ublock-unbreak: 1798-111, 3d.13h.19m
    urlhaus-1: 7519-1, 1h.17m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 239 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2543 ms (selfie)
  maxAssetCacheWait: 2035 ms

**Comment by okiehsch** [comment] 2022-06-13 17:04
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by okiehsch** 2022-06-13 17:04 UTC
