### ISSUE TITLE
cocomanga.com: detection

### ISSUE THREAD

**Issue by superbot1229** [uBlockOrigin/uAssets#13003] opened 2022-04-28 14:17 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cocomanga.com/22359/1/115.html`

### Category

breakage

### Describe the issue

thx

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 42113
  cosmetic: 18586
  scriptlet: 16835
  html: 643
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
  default: 
    user-filters: 6-0, never
    ublock-filters: 31550-30, 2d.23h.10m
    ublock-badware: 4108-3, 2d.23h.9m
    ublock-privacy: 217-0, 7d.23h.49m
    ublock-abuse: 74-0, 7d.23h.49m
    ublock-unbreak: 1779-0, 2d.23h.8m
    ublock-quick-fixes: 183-0, 12m
    urlhaus-1: 8492-0, 21h.18m
    plowe-0: 3682-3, 7d.23h.48m
    CHN-0: 28318-111, 2d.23h.11m
filterset (user): [array of 6 redacted]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 228 ms (selfie)
  maxAssetCacheWait: 106 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by huizichin** [comment] 2022-04-29 10:43
Ublock origin is detected, and says the following:
The browser blocks the display of important components, please make sure that no small plug-ins are enabled, which will affect page loading! If it doesn't work, please change your browser! Edge Chrome Firefox etc.

The log is as following:
`<details><summary>Logger output</summary>

```
+2
www.cocomanga.com
1
image
https://www.cocomanga.com/favicon.png
```
```
+2
##.mlad
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+2
@@||cocomanga.com^$xmlhttprequest,1p
++
www.cocomanga.com
1
xhr
https://www.cocomanga.com/js/a_d/ad2.js
```
```
+2
www.cocomanga.com
1
xhr
https://www.cocomanga.com/template/vfed/asset/img/icon-ext.png
```
```
+2
www.cocomanga.com
1
xhr
https://www.cocomanga.com/template/vfed/asset/img/loading-2.gif
```
```
+2
www.cocomanga.com
1
xhr
https://www.cocomanga.com/template/vfed/asset/img/loading-0.gif
```
```
+2
www.cocomanga.com
1
xhr
https://www.cocomanga.com/template/vfed/asset/img/icon.png
```
```
+2
www.cocomanga.com
1
xhr
https://www.cocomanga.com/template/vfed/asset/img/loading-1.gif
```
```
+2
googletagmanager_gtm.js
<<
www.cocomanga.com
3
script
https://www.googletagmanager.com/gtag/js?id=G-T0HJJCQMVV
```
```
+2
||googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js
--
www.cocomanga.com
3
script
https://www.googletagmanager.com/gtag/js?id=G-T0HJJCQMVV
```
```
+2
||googletagmanager.com^
--
www.cocomanga.com
3
script
https://www.googletagmanager.com/gtag/js?id=G-T0HJJCQMVV
```
```
+2
www.cocomanga.com
1
css
https://www.cocomanga.com/template/vfed/asset/css/layer.css?v=
```
```
+2
www.cocomanga.com
1
xhr
https://www.cocomanga.com/counting
```
```
+1
www.cocomanga.com
1
other
https://www.cocomanga.com/18150/1/2.html
```
```
+1
www.cocomanga.com
1
image
https://www.cocomanga.com/static/website.png
```
```
+1
www.cocomanga.com
1
xhr
https://www.cocomanga.com/static/loading.gif
```
```
+1
www.cocomanga.com
1
script
https://www.cocomanga.com/template/vfed/asset/js/global.js
```
```
+1
www.cocomanga.com
1
script
https://www.cocomanga.com/template/vfed/asset/js/jquery.js
```
```
+1
||cocomanga.com/js/dynamicjs.js$script
--
www.cocomanga.com
1
script
https://www.cocomanga.com/js/dynamicjs.js
```
```
+1
www.cocomanga.com
1
css
https://www.cocomanga.com/common/css/website.css
```
```
+1
www.cocomanga.com
1
css
https://www.cocomanga.com/template/vfed/asset/css/style.css
```
```
+1
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+1
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+1
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+1
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+1
www.cocomanga.com
1
doc
https://www.cocomanga.com/18150/1/1.html
```
```
+1
https://www.cocomanga.com/18150/1/1.html
```
```
+0
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+0
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+0
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
```
+0
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/18150/1/1.html
```
</details>
`

**Comment by JobcenterTycoon** [comment] 2022-04-29 10:52
Ok i get this too @Yuki2718

**Comment by huizichin** [comment] 2022-04-29 10:53
Seem to be fixed by creating an exception for this script
![image](https://user-images.githubusercontent.com/16850884/165931347-ef1cf76a-eeda-4343-acbe-aa770acbcc2c.png)

**Comment by huizichin** [comment] 2022-04-29 11:18
As for mobile, additional exception seem to be needed
`@@||www.cocomanga.com/js/a_d/pic1.png$image,domain=www.cocomanga.com`

So temporary solution is to add these into the filter `@@||www.cocomanga.com/js/dynamicjs.js$script,domain=www.cocomanga.com
@@||www.cocomanga.com/js/a_d/pic1.png$image,domain=www.cocomanga.com`

**Comment by Yuki2718** [comment] 2022-04-30 17:33
> As for mobile, additional exception seem to be needed `@@||www.cocomanga.com/js/a_d/pic1.png$image,domain=www.cocomanga.com`
> 

Couldn't confirm

**Closed** 2022-04-30 17:33 UTC

**Comment by superbot1229** [comment] 2022-05-01 15:50
it's work now. thx.
![image](https://user-images.githubusercontent.com/104577204/166153700-64c25d8d-13dc-4359-a42c-891884d94a92.png)
![image](https://user-images.githubusercontent.com/104577204/166153720-ae6e1f87-37c8-4743-8f67-619d378cc063.png)
@Yuki2718 @huizichin @JobcenterTycoon  thank you

**Comment by leonborin** [comment] 2022-07-09 19:42
The issue just come back even with latest Ublock filters, Ublock annoyance and Adguard Chinese. Tried clearing all site data from browser settings.

<details><summary>Logger output</summary>

```
+910
www.cocomanga.com
1
image
https://www.cocomanga.com/favicon.ico
```
```
+881
www.cocomanga.com
1
xhr
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/cv/result/72837d9a1e8c38a5
```
```
+881
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
www.cocomanga.com
1
script
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/scripts/pica.js
```
```
+881
www.cocomanga.com
1
script
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js?ts=1657382400
```
```
+881
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+881
www.cocomanga.com
1
doc
https://www.cocomanga.com/15636/1/110.html
```
```
+881
https://www.cocomanga.com/15636/1/110.html
```
```
+880
www.cocomanga.com
1
xhr
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/flow/ov1/0.1750414697106287:1657394386:jSW1x3kWKYhiyIE60_0-n_6G8FUGs9bAsSMrP26jfK8/72837d8e0df03907/6e352aa39860712
```
```
+880
www.cocomanga.com
1
xhr
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/pat/72837d8e0df03907/1657395197474/406564b9c9f30920b5c96f9be59f7382f0af775a82cd417433ee00f88ee6200a/WgZpHppkDFQwBrl
```
```
+880
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+880
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+880
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+880
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+880
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+880
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+880
www.cocomanga.com
1
image
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/img/72837d8e0df03907/1657395197468/DXHwDvIvwe0lEqn
```
```
+879
www.cocomanga.com
1
xhr
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/flow/ov1/0.1750414697106287:1657394386:jSW1x3kWKYhiyIE60_0-n_6G8FUGs9bAsSMrP26jfK8/72837d8e0df03907/6e352aa39860712
```
```
+879
##.cookie-warning
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html?__cf_chl_rt_tk=1mDLlr3UPU6oZTqnMoEId5HxzIQ8XJHcg8VyQI87ot8-1657395197-0-gaNycGzNCeU
```
```
+879
www.cocomanga.com
1
image
https://www.cocomanga.com/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=72837d8e0df03907
```
```
+879
www.cocomanga.com
1
image
https://www.cocomanga.com/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=72837d8e0df03907
```
```
+879
www.cocomanga.com
1
script
https://www.cocomanga.com/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=72837d8e0df03907
```
```
+879
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+879
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+879
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+879
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+879
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+879
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+879
www.cocomanga.com
1
doc
https://www.cocomanga.com/15636/1/110.html
```
```
+879
https://www.cocomanga.com/15636/1/110.html
```
```
+877
www.cocomanga.com
1
image
https://www.cocomanga.com/favicon.ico
```
```
+852
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+852
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+852
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+852
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+852
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+852
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+852
www.cocomanga.com
1
doc
https://www.cocomanga.com/15636/1/110.html
```
```
+852
https://www.cocomanga.com/15636/1/110.html
```
```
+400
www.cocomanga.com
1
image
https://www.cocomanga.com/favicon.ico
```
```
+400
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+400
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+400
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+400
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+400
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+400
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+400
www.cocomanga.com
1
doc
https://www.cocomanga.com/15636/1/110.html
```
```
+400
https://www.cocomanga.com/15636/1/110.html
```
```
+396
www.cocomanga.com
1
other
https://www.cocomanga.com/15636/1/110.html
```
```
+212
www.cocomanga.com
1
popup
https://www.cocomanga.com/dynamic/getaccessip
```
```
+212
www.cocomanga.com
1
popup
https://www.cocomanga.com/dynamic/getaccessip
```
```
+110
www.cocomanga.com
1
image
https://www.cocomanga.com/favicon.ico
```
```
+110
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+110
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+110
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+110
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+110
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+110
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+110
www.cocomanga.com
1
doc
https://www.cocomanga.com/15636/1/110.html
```
```
+110
https://www.cocomanga.com/15636/1/110.html
```
```
+95
odfafepnkmbhccpbejgmiehpchacaeak.chrome-extension-scheme
0,3
xhr
https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt?_=5
```
```
+94
odfafepnkmbhccpbejgmiehpchacaeak.chrome-extension-scheme
0,3
xhr
https://ublockorigin.github.io/uAssets/filters/filters-2022.txt?_=5
```
```
+94
odfafepnkmbhccpbejgmiehpchacaeak.chrome-extension-scheme
0,3
xhr
https://ublockorigin.github.io/uAssets/filters/filters-2021.txt?_=5
```
```
+94
odfafepnkmbhccpbejgmiehpchacaeak.chrome-extension-scheme
0,3
xhr
https://ublockorigin.github.io/uAssets/filters/filters-2020.txt?_=5
```
```
+94
odfafepnkmbhccpbejgmiehpchacaeak.chrome-extension-scheme
0,3
xhr
https://ublockorigin.github.io/uAssets/filters/filters.txt?_=5
```
```
+92
odfafepnkmbhccpbejgmiehpchacaeak.chrome-extension-scheme
0,3
xhr
https://filters.adtidy.org/extension/ublock/filters/14.txt?_=5
```
```
+0
www.cocomanga.com
1
image
https://www.cocomanga.com/favicon.ico
```
```
+0
##+js(addEventListener-defuser, load, popMagic)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+0
##+js(addEventListener-defuser, contextmenu)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+0
##+js(no-setTimeout-if, checkSiteNormalLoad)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+0
##+js(set-constant, __jsadsuccess, true)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+0
##+js(set-constant, NativeAd, noopFunc)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+0
##+js(no-setTimeout-if, loadErrorTip)
www.cocomanga.com
dom
https://www.cocomanga.com/15636/1/110.html
```
```
+0
www.cocomanga.com
1
doc
https://www.cocomanga.com/15636/1/110.html
```
```
+0
https://www.cocomanga.com/15636/1/110.html
```
</details>

**Comment by Yuki2718** [comment] 2022-07-10 11:49
You mean detection? I can't reproduce.

**Comment by leonborin** [comment] 2022-07-10 20:58
Not detection per se but more like 403 forbidden error that says use "normal" browsers. After clearing site data and waiting for a while, I can access it again in the same browser.

If the 403 error still persists then I use another type of browser to access the site. Perhaps due to cloudflare implementation in the site.
