### ISSUE TITLE
kiassanime.ru anti-adblock

### ISSUE THREAD

**Issue by tjanke42** [uBlockOrigin/uAssets#2789] opened 2018-07-06 06:36 UTC
You're probably already aware of this, but I didn't see the issue listed, so...

### URL(s) where the issue occurs

all `kissanime.ru/Anime/*`  - i.e. `kissanime.ru/Anime/Shingeki-no-Bahamut-Virgin-Soul`

### Describe the issue

Accessing any page under `kissanime.ru/Anime/*` leads to a brief view of a webpage complaining about using an ad-blocker, then your ip is banned "for a few days".  Sometimes there is a short delay before being banned, sometimes it's immediate.

### Screenshot(s)

![croppercapture 170](https://user-images.githubusercontent.com/1124476/42360066-29ae98fc-809b-11e8-9e33-1ef776a3afce.png)

### Versions

- Browser/version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- uBlock  version:
  Nano Adblocker v1.0.0.55
     Based on uBlock Origin Version/1.16.12 Commit/3093846 UserCSS/disabled
  Nano Defender v15.0.0.5

### Settings

- [List here all the changes you made to uBO's default settings]
none

### Notes

[Add here the result of whatever investigation work you have done:  investigate the issues you report -- this prevents burdening other volunteers. This is especially  for issues arising from settings which are  different from default ones.]

I updated all my filters, and checked

**Comment by uBlock-user** [comment] 2018-07-06 07:34
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2719

**Comment by okiehsch** [comment] 2018-07-06 20:31
Add
`kissanime.ru##script:inject(abort-current-inline-script.js, $, elem.hide)`
to your filter list, if you are banned you have to change your IP.

**Closed** 2018-07-06 20:32 UTC
Labels: duplicate
