### ISSUE TITLE
arctic.de: breakage

### ISSUE THREAD

**Issue by b1k3rdude** [uBlockOrigin/uAssets#23286] opened 2024-04-13 08:49 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.arctic.de/`

### Category

breakage

### Description

If I use element zapper to remove the annoying cookie consent popup, the website blocks/disables page scrolling.

### Other extensions used

Related/Relevent extensions - 

- Consent-o-Matic, 
- Consent Blocker, formerly Google Consent
- Global Consent Manager, GDPR consent dialogs
- Darkreader
- CookieBro

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![arctic-de](https://github.com/uBlockOrigin/uAssets/assets/12858109/08983771-68f1-456e-a583-fed4a06b2742)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 256941
 cosmetic: 187724
 scriptlet: 40950
 html: 1755
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/ansul1001/Ansul-s-Ad-Filters/master/Ansul's%20Ad%20Filters: 35-0, now
  adguard-generic: 80702-5562, now
  adguard-mobile: 9241-19, now
  adguard-spyware-url: 1493-107, now
  adguard-spyware: 104174-33243, now
  block-lan: 61-0, now
  curben-phishing: 14152-4, now
  adguard-social: 22783-868, now
  adguard-popup-overlays: 27072-1616, now
  adguard-mobile-app-banners: 5139-1093, now
  adguard-other-annoyances: 14137-294, now
  adguard-widgets: 2466-1, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 638-36, never
  ublock-filters: 37552-438, 1h.31m Δ
  ublock-badware: 8078-0, 1h.31m Δ
  ublock-privacy: 789-0, 1h.31m Δ
  ublock-unbreak: 2303-0, 1h.31m Δ
  ublock-quick-fixes: 152-0, 1h.31m Δ
  easylist: 85183-880, 1h.31m Δ
  easyprivacy: 50481-1082, 1h.31m Δ
  urlhaus-1: 11610-0, now
  plowe-0: 3739-83, now
filterset (user): [array of 639 redacted]
trustedset:
 added: [array of 32 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 241 ms (selfie)
 maxAssetCacheWait: 123 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  facebook.net: 1
  googletagmanager.com: 1
 extended:
  ##.scroll-up-button
  ##.modal-lg.modal-dialog-centered.modal-dialog > .modal-content
  ##.show.fade.modal-backdrop
  ##.show-tablet.show-mobile.linked-banner.nds-banner
  ###confirmDeleteAccountModal > .modal-dialog-centered.modal-dial…
```
</details>

**Comment by garry-ut99** [comment] 2024-04-13 12:03
You don't need to fix the cookie message by yourself because it's already fixed in uBO built-in filter lists: 
**EasyList/uBO – Cookie Notices** or/and **AdGuard/uBO – Cookie Notices**. 
You can enable them in uBO "Filter lists" pane >> Cookie notifications.

But if for some reason you don't want to use uBO cookie filters, and want to fix only this one site, then your question:

> b1k3rdude : If I use element zapper to remove the annoying cookie consent popup, the website blocks/disables page scrolling.

is a duplicate of:
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2501

**Comment by mapx-** [comment] 2024-04-13 12:23
enable EasyList/uBO – Cookie Notices

**Closed by mapx-** 2024-04-13 12:23 UTC

**Comment by b1k3rdude** [comment] 2024-04-13 13:11
Thank you both, I wasnt aware that UBO had an existing Cookie filter list. Enabled and issue is no longer present!

**Comment by garry-ut99** [comment] 2024-04-13 13:42
> the reason that was turned off was because having it, 'AdGuard/uBO – Cookie Notices' and 'uBlock filters – Annoyances' enabled/ticked - breaks facebook.com to the point the page is stuck in a reload loop.

Instead of disabling cookie lists, you can report breakages to issue tracker.
For facebook issues you can write a comment in the cummulative thread:
`https://github.com/uBlockOrigin/uAssets/issues/3367`

> But in wateforx on a frsh install of UBO with all filter lists enabled FB is fine, so more checking or a fresh install of UBO is required.

You use uBO `1.56`, on a fresh profile most likely you have installed `1.57.2`, maybe that's the difference which fixed the facebook issue.

**Comment by b1k3rdude** [comment] 2024-04-13 13:44
I did a fresh install of UBO  and they did indeed upgrade me from 1.56 to 1.57.2. But removed and reinstall UBO on FF and enabled all the filters as I did in WF and FB broken. So will log the issue as per your suggestion.

**Comment by garry-ut99** [comment] 2024-04-15 15:24
> b1k3rdude :
> * [x]  I have verified that other extensions are not causing the issue.

> b1k3rdude : https://github.com/uBlockOrigin/uAssets/issues/3367#issuecomment-2054197662 :
> Disabling/Removing the 'Consent Blocker' addon, resolved the issue
