### ISSUE TITLE
fmovies.to: ads

### ISSUE THREAD

**Issue by Agent-324** [uBlockOrigin/uAssets#12018] opened 2022-03-03 05:55 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/movie/the-matrix-resurrections-j2w63/1-full`

### Category

ads

### Describe the issue

The vidstream video player shows an ad every time you pause it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-03-03 112435](https://user-images.githubusercontent.com/98957297/156504940-a2496d73-74bb-4dee-93cd-2280d88bc4bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 79802
  cosmetic: 41322
  scriptlet: 16469
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 15-0, never
    easylist: 64083-12, 17h.39m
    easyprivacy: 26634-122, 17h.39m
    plowe-0: 3673-805, 17h.39m
    ublock-abuse: 72-0, 17h.39m
    ublock-badware: 3899-85, 17h.39m
    ublock-filters: 30230-156, 17h.39m
    ublock-privacy: 204-2, 17h.39m
    ublock-unbreak: 1720-39, 17h.39m
    urlhaus-1: 8437-0, 17h.39m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 211 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 382 ms (selfie)
  maxAssetCacheWait: 209 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    fmovies.to: 1
    addthis.com: 1
    amung.us: 1
    dealtsowbite.com: 2
    disqus.com: 1
    makespram.com: 3
    rlcdn.com: 1
    venetrigni.com: 1
    vizcloud2.ru: 1
    zap.buzz: 18
```
</details>

**Comment by uBlock-user** [comment] 2022-03-03 06:06
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/12008

**Closed by uBlock-user** 2022-03-03 06:06 UTC

**Comment by Agent-324** [comment] 2022-03-03 06:27
thanks
