### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by defoxxa** [uBlockOrigin/uAssets#14285] opened 2022-08-06 13:55 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/playlist/37i9dQZF1DWWY64wDtewQt`

### Category

breakage

### Describe the issue

ads ended but it wont skip, need to reload web everytime it happens.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110730154/183251854-5d559797-950b-435c-bba3-75740ba91de1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 81939
  cosmetic: 45162
  scriptlet: 17562
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69102-51, 2d.8h.30m
    easyprivacy: 27479-123, 2d.8h.29m
    plowe-0: 3639-777, 4d.11h.19m
    ublock-abuse: 76-0, 5d.11h.16m
    ublock-badware: 4171-92, 2d.8h.28m
    ublock-filters: 32443-122, 2d.8h.27m
    ublock-privacy: 226-3, 5d.11h.15m
    ublock-quick-fixes: 356-24, 9h.32m
    ublock-unbreak: 1851-42, 2d.8h.26m
    urlhaus-1: 6721-0, 9h.31m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 287 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 39
  blockedDetails: 
    doubleclick.net: 27
    scdn.co: 9
    sentry.io: 3
```
</details>

**Comment by okiehsch** [comment] 2022-08-06 15:09
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14231

**Closed by okiehsch** 2022-08-06 15:09 UTC
