### ISSUE TITLE
visortmo.com: breakage

### ISSUE THREAD

**Issue by franfac** [uBlockOrigin/uAssets#24065] opened 2024-06-12 06:58 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://visortmo.com/
```

### Description

The website does not work correctly with the ad blocker and I have to deactivate it to be able to browse the website. 
I would like to continue using my ad blocker on the website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![11111](https://github.com/uBlockOrigin/uAssets/assets/11486621/6c60bd24-04e2-4b28-88a7-36381fe19d9b)

![22222](https://github.com/uBlockOrigin/uAssets/assets/11486621/9bb69dcd-d1b7-476a-8a5f-f1bbdb21022c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 139696
 cosmetic: 53202
 scriptlet: 21494
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86770-616, 6m Δ
  easyprivacy: 51046-651, 6m Δ
  plowe-0: 3555-0, 5m
  spa-0: 4064-3, 5m
  spa-1: 5751-187, 5m
  ublock-badware: 9199-0, 6m Δ
  ublock-filters: 38399-287, 6m Δ
  ublock-privacy: 929-0, 6m Δ
  ublock-unbreak: 2338-4, 6m Δ
  urlhaus-1: 14245-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 186 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1236 ms (selfie)
 maxAssetCacheWait: 628 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment] 2024-06-12 07:10
Caused by `visortmo.com#@#.book` in EL

cc @Yuki2718 This site constantly circumvents the filters. I think better to handle in our quick list or regional lists?

**Comment by Yuki2718** [comment] 2024-06-12 13:58
Ads already fixed by regional list

**Closed** 2024-06-12 13:58 UTC
Labels: geo specific, broken by EasyList, fixed
