### ISSUE TITLE
Yandex Image Search Ads

### ISSUE THREAD

**Issue by beakwood** [uBlockOrigin/uAssets#14456] opened 2022-08-20 14:26 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://yandex.com/images/search`

### Describe the issue

The issue I'm having is, I'm blocking the cosmetic filter of the ads on the image search and when I scroll down or refresh the page. The ads are still being shown.  

These are all I've blocked so far. 
<details>
    <summary>Filters</summary>

```
! 2022-08-19 https://yandex.com
yandex.com###SerpDirect-OArYlNt > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArYpsa > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArYvWA > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArYxAc > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArY-a- > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArY_2r > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArZ2Vc > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArZ36x > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
yandex.com###SerpDirect-OArYkIW > .SerpDirect_type_between.SerpDirect > .DirectInline > .SerpDirect-Container.DirectInline-PCodeContainer
```
</details>
### Screenshot(s)

https://user-images.githubusercontent.com/43938224/185751028-a337bc0f-78dc-48be-b2a4-80511694ffa7.png

### uBlock Origin version

1.44.0

### Browser name and version

Firefox Nightly 105.0a1 (2022-08-18) (64-bit)

### Settings

DEFAULT SETTINGS

**Comment by dimisa-RUAdList** [comment] 2022-08-20 14:46
The rules for this site are contained in [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt&title=RU%20AdList%20for%20uBO%20only) and [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters). In addition, for browsers of the Firefox family, you will need to install [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor), for Firefox Quantum - [scriptlet-doctor-quantum](https://github.com/JustOff/scriptlet-doctor/releases/download/1.2.5/scriptlet-doctor-quantum-1.2.5.xpi).

**Comment by MasterKia** [comment] 2022-08-20 15:04
> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14371 https://github.com/uBlockOrigin/uAssets/issues/14299

**Closed by MasterKia** 2022-08-20 15:04 UTC
