### ISSUE TITLE
Welt.de

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#4116] opened 2018-11-15 01:38 UTC
### URL(s) where the issue occurs

`https://www.welt.de/debatte/kommentare/article183830806/Hoechstes-deutsches-Gericht-Merkels-Mann-fuer-Karlsruhe-ist-der-richtige.html`

### Describe the issue

Ads appear at top center and right scrolling when you scroll. Also background when you visit any other than the homepage of this site. Please note that it takes up to 5 seconds after site load before ads appear. Started to happen since less than 5 hours after creating this report.

### Screenshot(s)

https://imgur.com/a/EEm1exs

### Versions

- Browser/version: FF 63.0.1
- uBlock Origin version: 1.17.2

### Settings

- Assigned to German lists (EasyList Germany)

**Comment by okiehsch** [comment] 2018-11-15 01:40
Update your filter list and try again, I added a fix 20 minutes ago.

**Comment by okiehsch** [comment] 2018-11-15 01:42
Actually forget what I said, the added fix does not work with Firefox on my end too.

**Comment by Symbai** [comment] 2018-11-15 14:56
Confirmed, it does not. Can you reopen this issue then or is there a reason why it remains closed?

**Comment by mapx-** [comment] 2018-11-15 15:57
@okiehsch  added a filter (see "closed this in 7acdf80" ), did you update the list ?

**Comment by Symbai** [comment] 2018-11-15 17:28
I now purged the filters and updated them. At the main site the ads are gone but on this page I still receive ads:

`https://www.welt.de/finanzen/immobilien/article183878020/Bundesbank-sieht-im-Immobilienboom-ein-Stabilitaetsrisiko.html`

Screenshot: https://imgur.com/a/Ni2qpb0

**Comment by okiehsch** [comment] 2018-11-15 17:37
They changed the code again it again after I added the fix, to be sure that it works for you at the moment, add 
`welt.de##^script:has-text(uabp)`
to your filter list.
Does it work for you, it deos n my end.

**Comment by sp00n** [comment] 2018-11-16 12:12
Adding `welt.de##^script:has-text(uabp)` didn't work for me, neither in 1.17.2 nor in 1.17.3b8.

I'm also seeing these kind of ads on multiple other sites now, e.g. transfermarkt.de or kicker.de (both times right on the home page).

**Comment by mapx-** [comment] 2018-11-16 12:14
@sp00n  that filter is only for firefox.

**Comment by mapx-** [comment] 2018-11-16 12:17
Did you update ublock filters list ? I get no ad on `transfermarkt` using chrome

**Comment by kirchwitz** [comment] 2018-11-16 12:22
These new ads now appear on a lot of german web sites, e.g. welt.de, morgenpost.de, heise.de/ix.de, golem.de, tagesspiegel.de, just to name a few. The rule <name-of-site>##^script:has-text(uabp) seems to work on all of them (at least until they change that common name).

**Comment by okiehsch** [comment] 2018-11-16 17:56
> These new ads now appear

They are not new, they used these ads for years they showed up because they modified theirad-reinsertion script.
https://github.com/gorhill/uBlock/issues/1100 is the first time someone brought up those kind of ads I think.

**Comment by rugk** [comment] 2018-11-17 17:45
Can also reproduce the same on Golem.de, e.g. on https://www.golem.de/news/bentgate-ipad-pro-2018-soll-leicht-verbiegen-1811-137777.html it looks like https://www.golem.de/news/bentgate-ipad-pro-2018-soll-leicht-verbiegen-1811-137777.html then:

![](https://screenshots.firefox.com/QRnQjZbRdsC4m0tj/www.golem.de)

**Closed** 2018-11-20 19:53 UTC
