### ISSUE TITLE
imdb.com

### ISSUE THREAD

**Issue by Keith94** [uBlockOrigin/uAssets#740] opened 2017-10-05 09:59 UTC
### URL(s) where the issue occurs

http://www.imdb.com/title/tt2250912/

### Describe the issue

Background/other elements don't appear correctly.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/5490615/31221308-143f31ca-a978-11e7-8fa8-015652a1e12b.png)

### Versions

- Browser/version: Nightly 58.0a1
- uBlock Origin version: 1.14.10

### Settings

Default settings

### Notes

Issue may be caused by the following 3rd-party filter in the "Filters optimized for uBlock"

>! https://www.reddit.com/r/uBlockOrigin/comments/6sg6hl/internet_movie_database_ads/ imdb.com##body#styleguide-v2:style(background-color: #e3e2dd !important; background-image: none !important;)

**Comment by gorhill** [comment] 2017-10-05 12:02
This is caused by that filter:

    imdb.com#@#script:inject(abort-current-inline-script.js, doWithAds)

Which was added to solve:

    https://www.reddit.com/r/uBlockOrigin/comments/6sg6hl/internet_movie_database_ads/dlka4ug/

Fixed by removing above filter and adding:

    imdb.com###injected_navstrip_wrapper

**Comment by gorhill** [comment] 2017-10-05 12:05
Force an update of "uBlock filters" and please provide feedback that site renders all fine.

**Closed** 2017-10-05 12:04 UTC

**Comment by Keith94** [comment] 2017-10-05 12:10
That fixed it, thanks!
