### ISSUE TITLE
civilization.fandom.com: ads

### ISSUE THREAD

**Issue by teethpasta** [uBlockOrigin/uAssets#11821] opened 2022-02-21 04:43 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://civilization.fandom.com/wiki/Maneuver_(Civ6)`

### Category

ads

### Describe the issue

Big video ad plays at the top

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox Mobile: 97
filterset (summary): 
  network: 79947
  cosmetic: 22993
  scriptlet: 16395
  html: 620
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2d.12h.21m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 30870-264, 4d.34m
    ublock-badware: 3969-3, 4d.52m
    ublock-privacy: 201-1, 3d.23h.47m
    ublock-abuse: 77-0, 3d.23h.36m
    ublock-unbreak: 1733-0, 4d.26m
    adguard-mobile: 7232-169, 4d.15m
    easylist: 63691-24415, 3d.23h.59m
    easyprivacy: 26576-578, 2d.12h.19m
    plowe-0: 3675-2, 4d.1h.54m
    urlhaus-1: 7518-0, 20h.38m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2599 ms (selfie)
  maxAssetCacheWait: 2136 ms
popupPanel: 
  blocked: 60
  blockedDetails: 
    fandom.com: 1
    ad.gt: 2
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    durationmedia.net: 1
    facebook.net: 1
    fastly-insights.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imrworldwide.com: 1
    jwpcdn.com: 1
    jwpltx.com: 9
    moatads.com: 1
    nocookie.net: 1
    ntv.io: 1
    quantserve.com: 1
    scorecardresearch.com: 2
    wikia-services.com: 29
```
</details>

**Comment by uBlock-user** [comment] 2022-02-21 06:55
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11821

**Closed by uBlock-user** 2022-02-21 06:55 UTC
