### ISSUE TITLE
Anti-adblock stickies on the bottom of many websites

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#7691] opened 2020-07-22 01:26 UTC
### URL(s) where the issue occurs

```
https://madensverden.dk/frikadeller/
https://bornholm.nu/
https://newsbreak.dk/drenge-faengslet-for-overfald-med-pistol-og-kniv/
https://gaffa.dk/
https://stiften.dk/
https://www.bilgalleri.dk/
https://www.recordere.dk/
https://kendte.dk/opdatering-v1-taarevaedet-kanye-west-begynder-valgkamp-med-kaotisk-moede/
https://www.gizmodo.jp/2020/07/216985.html
```

### Describe the issue

An English-language anti-adblock message sticky with Google-hosted image files, are shown on the bottom a lot of websites. It seems to be `||fundingchoicesmessages.google.com^$3p` in the main *uBlock Filters* list that is causing this, but I've had oddly much problems with verifying that it is the case.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/88123006-4d5d1680-cbca-11ea-97da-a4442a4ed6b8.png)

### Versions

- Browser/version: Chrome 84.0.4147.89 x64 for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201

### Settings

![image](https://user-images.githubusercontent.com/22780683/88123071-6ebe0280-cbca-11ea-87ae-cb343d164108.png)
![image](https://user-images.githubusercontent.com/22780683/88123108-7f6e7880-cbca-11ea-9ada-1226cbbec954.png)

### Notes

Thankfully enough, the message overlays uses very similar `[style]` values, meaning that a generic non-advanced hiding rule to simply remove the banners should be pretty possible on paper. From the `bornholm.nu` example page:
![image](https://user-images.githubusercontent.com/22780683/88123269-d7a57a80-cbca-11ea-9ba7-1f7a5f771777.png)
I know that the `width:` percentage changes from site to site, varying from `101%` to `107%`. The rest of the values don't seem to change very often that I'm personally aware of.

I've added a makeshift specific entry in my Nordic list for the Danish example sites, so you may or may not want to turn the Nordic list *off* on your PCs while testing this, for simplicity's sake.

**Comment by okiehsch** [comment] 2020-07-22 01:33
>It seems to be `||fundingchoicesmessages.google.com^$3p` in the main uBlock Filters list that is causing this

That is a known issue.
See https://github.com/uBlockOrigin/uAssets/commit/08958cacab69ae2682248dee8c6df063b6a707a7 for a deep dive. 😉

**Comment by okiehsch** [comment] 2020-07-22 01:36
For the sites of your regional list you can try
`example.com##+js(nostif, f.parentNode.removeChild(f), 100)`
to fix the issue.

**Comment by llacb47** [comment] 2020-07-22 01:36
I can't reproduce on any of these sites using a US IP.

**Comment by okiehsch** [comment] 2020-07-22 01:38
I only tried `gizmodo.jp` and I can't reproduce with a EU IP but his screenshot of the site shows the typical google contributor message.

**Comment by DandelionSprout** [comment] 2020-07-22 01:39
I've used `newsbreak.dk,kendte.dk,madensverden.dk,gaffa.dk,stiften.dk,bilgalleri.dk,recordere.dk,bornholm.nu##div[style*=" fixed; width: 10"]` thus far, which worked far better than it had any right to do.

The AdGuard team does however believe I should bring it up with you guys as per https://github.com/AdguardTeam/AdguardFilters/issues/59738#issuecomment-661818488, so that's what I've done now.

**Comment by llacb47** [comment] 2020-07-22 01:39
Why would the sites geo-target anti-adblock though? Seems weird

**Comment by okiehsch** [comment] 2020-07-22 01:44
@DandelionSprout 
Can you test if `gizmodo.jp##+js(nostif, f.parentNode.removeChild(f), 100)`
works for you, I can't reproduce the issue.

**Comment by okiehsch** [comment] 2020-07-22 01:45
@llacb47 I don't get any google contributor requests, so it seems those sites don't use it at all in some regions.

**Comment by DandelionSprout** [comment] 2020-07-22 01:46
The suggested entry doesn't seem to work as far as I can tell.

I didn't expect this issue report to be replied to as quickly as this, so give me some minutes to come up with something clever without the report being closed or anything like that.

**Comment by okiehsch** [comment] 2020-07-22 01:53
Don't worry I won't close it.
The usual fix for google contributor is 
`##+js(nostif, f.parentNode.removeChild(f), 100)`
or
`example.com^$ghide`

You can try

**Comment by okiehsch** [comment] 2020-07-22 01:56
Weird, I can't reproduce with a norwegian IP.
@DandelionSprout have you relocated. 😁

**Comment by okiehsch** [comment] 2020-07-22 01:59
@Yuki2718 can you reproduce the anti adblock message at `https://www.gizmodo.jp/2020/07/216985.html`?

**Comment by DandelionSprout** [comment] 2020-07-22 01:59
This is generally a pretty weird situation. Because on Chrome, I can't seem to prevent the message from showing up *even when `fundingchoicesmessages.google.com` is whitelisted.*

There's definitely some witchcraft that Google is doing here.

In the event that more people are able to reproduce the issue on whatever site (Doesn't necessarily have to be the example sites I used for this), I propose adding `##div[style^="bottom: 0px; left: 0px; position: fixed; width: 10"][style$=" display: flex; justify-content: center; font-family: Roboto, Arial;"]` as a generic entry.

**Comment by llacb47** [comment] 2020-07-22 01:59
> 
> 
> Don't worry I won't close it.
> The usual fix for google contributor is
> `##+js(nostif, f.parentNode.removeChild(f), 100)`
> or
> `example.com^$ghide`

Sometimes there is a different letter than `f`. It is usually in an inline script. @DandelionSprout can you copy and paste the source code of one of the pages where you see this message and share it here in a gist or pastebin?

**Comment by DandelionSprout** [comment] 2020-07-22 02:15
I have a new theory, but I'll have a very hard time confirming that one as well:

It turns out that *I Don't Care About Cookies* is also blocking `fundingchoicesmessages.google.com`, as well as `fundingchoices.google.com`.

I'm still trying to figure out why my Vivaldi alternate setup isn't trying to load either of those two domains at all. I'm indeed beginning to suspect that cookies could be a big factor.

(To llacb47) The div elements aren't showing up *at all* in the resulting text when I use "Show page source", sadly.

**Comment by llacb47** [comment] 2020-07-22 02:23
I'm not talking about the div elements,... I would like to see the inline script that is causing it.

**Comment by okiehsch** [comment] 2020-07-22 02:28
@DandelionSprout to illustrate go to `view-source:https://www.spiele-umsonst.de/` and search for `googlefc`
![image](https://user-images.githubusercontent.com/16838044/88127396-c876fa80-cbd3-11ea-85c4-1d413ec539a8.png)

**Comment by DandelionSprout** [comment] 2020-07-22 02:33
I can confirm that there is no such script on my end. https://pastebin.com/xyL6S1Rr

And in the DOM tree I could only find iframes that had `name=googlefcPresent`.

**Comment by DandelionSprout** [comment] 2020-07-22 02:41
I have finally found a solution! Which is also pretty bizarre, and probably paints me in a bad light for not being keen on using privacy lists...

It turns out that blocking `/gtm.js^`, which is done by *uBlock Filters - Privacy*, prevents the sites from trying to load `fundingchoicesmessages.google.com` at all.

**Comment by okiehsch** [comment] 2020-07-22 02:54
Yes, after allowing gtm.js at `gizmodo.jp` I can reproduce.
I still can't reproduce at `https://www.bilgalleri.dk` but if it works for you with a default setup the issue can be closed I supppose.

**Comment by okiehsch** [comment] 2020-07-22 02:57
For anybody who is curious or who has `uBO-privacy` disabled 
`gizmodo.jp##+js(nostif, g.parentNode.removeChild(g), 100)`
fixes the issue. 😉

**Comment by DandelionSprout** [comment] 2020-07-22 03:02
I've now replaced the makeshift entry in my own list, at least. Hopefully this means it shouldn't become a problem on Danish sites anymore.

I do however think there's legitimate grounds to simply move `||googletagmanager.com/gtm.js^` from uAssets Privacy to the uAssets main list, now that the entry is established to have successful anti-anti-adblocking abilities.

**Comment by okiehsch** [comment] 2020-07-22 03:15
> simply move ||googletagmanager.com/gtm.js^ from uAssets Privacy to the uAssets main list, now that the entry is established to have successful anti-anti-adblocking abilities.

"Google Tag Manager is a free tool that allows you manage and deploy marketing tags (snippets of code or tracking pixels) on your website (or mobile app) without having to modify the code."

It is a privacy issue, the anti adblock message is caused by the fundingchoice message script being blocked.

**Comment by mapx-** [comment] 2020-07-22 08:25
well, we can close it, right ? maybe @DandelionSprout you could test using the default setup in the future

**Closed by mapx-** 2020-07-22 08:25 UTC
Labels: unable to reproduce

**Comment by DandelionSprout** [comment] 2020-07-22 09:14
How was I possibly supposed to know that one entry in a privacy list would also fix anti-adblock problems? Removing those anti-adblock messages shouldn't have to depend on using lists that are solely dedicated to blocking trackers.

**Comment by okiehsch** [comment] 2020-07-22 09:31
Nobody says that you should have known that the issue is also fixed by blocking a tagmanager.
We always test with a default setup, so if there are problems to reproduce it is kind of important to know if we are all on the same page so to speak.
You have provided a screenshot of your settings, but your setup is rather convoluted, no offence.
It is easier for you to test with a default setup then for us to recreate that setup imo.

**Comment by DandelionSprout** [comment] 2020-07-22 11:40
Typically my main Chrome setup is very convolutes and has around 35 lists (75 if the subfiles loaded by my own private list is counted), whereas my test Vivaldi setup is usually using the default setup. Therefore I've usually assumed in cases like this that it's browser- or cookie-specific instead of "Default lists or not"-specific. 😅
