### ISSUE TITLE
Acronis.com - Weird anti-adblock issue

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#4660] opened 2019-01-17 23:17 UTC
### Affected site:
`https://www.acronis.com/`

### Issue:
The site seems to use some type of anti-adblock mechanism, which prevents certain elements from loading.

### Example:
`https://www.acronis.com/en-us/support/contact-us/`

### Screenshot:

![filterissue-acronis](https://user-images.githubusercontent.com/9382674/51355109-4f668680-1ab6-11e9-92cd-c5cfa3ce07b8.jpg)

### Possible fix:
`@@||acronis.com^$generichide`

### Other fixes (annoyances) of possible interest (UNRELATED):
```
acronis.com##.cookies-notification
acronis.com##.social
acronis.com##.social-icons-sticky
acronis.com###back-to-top
acronis.com###backtotop
```

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.3.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.6 (XUL)

**Comment by okiehsch** [comment] 2019-01-17 23:54
I can't reproduce, with a default setup +  adding
````
acronis.com##.cookies-notification
acronis.com##.social
acronis.com##.social-icons-sticky
acronis.com###back-to-top
acronis.com###backtotop
````
![image](https://user-images.githubusercontent.com/16838044/51356531-24326600-1abb-11e9-8c4f-a2971edbacea.png)

**Comment by THEtomaso** [comment] 2019-01-18 05:53
I gave it a try with '**SRWare Iron**', and I couldn't reproduce either.
Seems like either Chromium browsers, or the WebExtensions version of uBlock Origin, is unaffected by this particular issue.

To reproduce, use Pale Moon + uBO Legacy.
You'll find portable builds of Pale Moon here (scroll down a bit):
`http://www.palemoon.org/download.shtml`

BTW; the fixes that I posted under "Other fixes" are completely unrelated to this issue.
Those are just some unattended annoyances that I discovered when browsing the site.
I thought perhaps someone would be interested in adding them to their annoyances filters.

**Comment by mapx-** [comment] 2019-01-18 20:48
tested same versions `Pale Moon + uBO Legacy` (default setup), no issue here, closing.

**Closed by mapx-** 2019-01-18 20:48 UTC
Labels: unable to reproduce

**Comment by THEtomaso** [comment] 2019-01-18 23:01
@mapx- + @okiehsch :

I've run further tests now, and after some messing around, I finally found the culprit..

The issue is caused by the following rule (found in the '**I don't care about cookies**' filter):
`###cookie:not(body):not(html):not([href*="cookieclicker"])`

The reason why I didn't notice it before, is that this rule does NOT show up in uBO's logger, when using the Legacy version!
It's not the first time that I've encountered this problem.
Here's another example:
`https://github.com/DandelionSprout/adfilt/issues/7/#issuecomment-421023471`

Guess there's a bug in the Legacy version that needs to be addressed?

Also, why does `@@||acronis.com^$generichide` fix the problem?
Is it really ment to cancel out those type of cosmetic rules?

**Comment by mapx-** [comment] 2019-01-18 23:06
`###cookie:not(body):not(html):not([href*="cookieclicker"])` is a generic filter => `$generichide` will "kill" it

**Comment by okiehsch** [comment] 2019-01-18 23:09
If I add 
`##cookie:not(body):not(html):not([href*="cookieclicker"])`
the site is broken using Chromiuim/Chrome, so this is not a  bug in the Legacy version.

**Comment by THEtomaso** [comment] 2019-01-18 23:10
I'm talking about the fact that the rule doesn't show up in the Legacy version's logger.

**Comment by okiehsch** [comment] 2019-01-18 23:14
Sorry, I missed that part in your comment.
You can ask gorhill if he thinks that should be fixed in the legacy version, or hope that somebody using Pale Moon investigates and opens a pull request.

**Comment by krystian3w** [comment] 2019-01-19 00:00
@kiboke try fix generic filter

**Comment by kiboke** [comment] 2019-01-30 08:09
Thank you, the related rule will be removed from IDCAC in the next version.

**Comment by krystian3w** [comment] 2019-01-30 08:18
`##body > .rcc-panel.group:not(body):not(html)`

`.rcc-panel.group` no have choice to become body or html.

**Comment by kiboke** [comment] 2019-01-30 08:37
Good catch, thanks!

**Comment by krystian3w** [comment] 2019-02-24 19:11
@kiboke:

```
###cookie_info_startpage ~ #white_layer:not(body):not(html)
```

`#white_layer` should  no have choice to become `<html>`.

**Comment by kiboke** [comment] 2019-02-25 06:29
> @kiboke:
> 
> ```
> ###cookie_info_startpage ~ #white_layer:not(body):not(html)
> ```
> 
> `#white_layer` should no have choice to become `<html>`.

Unless someone puts #cookie_info_startpage before BODY and gives BODY id white_layer. I've seen all kinds of stupid solutions :)

**Comment by krystian3w** [comment] 2019-02-25 09:32
That is not html filtering - browser should parsed element inside to body.
