### ISSUE TITLE
poki.com: ads

### ISSUE THREAD

**Issue by umar-skh** [uBlockOrigin/uAssets#12431] opened 2022-03-25 10:24 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poki.com/en/g/combat-online`

### Category

ads

### Describe the issue

the site has a pop-up by firefox that says `An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:
Script error.`
even happens when adblock is disabled
The ad block used to work when the error wasnt there

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 95
filterset (summary): 
  network: 80163
  cosmetic: 41911
  scriptlet: 16577
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31056-29, 2d.1h.23m
    ublock-badware: 3929-3, 2d.1h.22m
    ublock-privacy: 206-0, 2d.1h.21m
    ublock-abuse: 72-0, 2d.1h.20m
    ublock-unbreak: 1747-0, 2d.1h.18m
    easylist: 64600-542, 2d.1h.17m
    easyprivacy: 26716-577, 2d.1h.16m
    urlhaus-1: 8466-0, 22h.18m
    plowe-0: 3690-2, 2d.1h.14m
    ublock-quick-fixes: 115-4, 22h.17m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 677 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    poki.com: 2
    2mdn.net: 1
    amazon-adsystem.com: 2
    doubleclick.net: 3
    googlesyndication.com: 6
    jsdelivr.net: 1
    poki.io: 3
    unity3d.com: 2
```
</details>

**Comment by stephenhawk8054** [comment] 2022-03-25 10:57
Hmmm... Anyone has better solution than this? 🤔 

```
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=poki.com|poki-gdn.com
```

**Comment by mapx-** [comment] 2022-03-25 11:07
the site is working fine after closing that alert window, right ?

`poki-gdn.com##+js(aopr, alert)`

**Comment by okiehsch** [comment] 2022-03-25 11:07
No.

**Comment by mapx-** [comment] 2022-03-25 11:08
I was able to click play etc, what's broken ?

**Comment by okiehsch** [comment] 2022-03-25 11:09
> the site is working fine after closing that alert window, right ?

If that's the case your filter works.
I thought the issue involved some site breakage too.

**Comment by okiehsch** [comment] 2022-03-25 11:10
My "no" was in response to @stephenhawk8054 question.

**Comment by mapx-** [comment] 2022-03-25 11:11
ok .. let's see the feedback

**Comment by stephenhawk8054** [comment] 2022-03-25 11:13
> the site is working fine after closing that alert window, right ?
> 
> `poki-gdn.com##+js(aopr, alert)`

Ah right, confirm it works on my end too.

**Closed** 2022-03-25 12:12 UTC

**Comment by umar-skh** [comment] 2022-03-27 12:52
the JS error doesnt happen anymore and i see no ads, i didnt do anything
maybe the site updated

**Comment by mapx-** [comment] 2022-03-27 12:55
I added a fix, maybe that is the real reason ?!

**Comment by umar-shk** [comment] 2022-04-01 07:34
its still does show ads, but no JS error this time

**Comment by umar-shk** [comment] 2022-04-01 07:35
no ads in the panel with all the game icons, but they are there while playing a game

**Comment by mapx-** [comment] 2022-04-01 07:50
> its still does show ads

still what ? it's new, your issue was about that js error.

What ads are you talking about ? Provide a screenshot, explain better

**Comment by umar-shk** [comment] 2022-04-01 08:02
@mapx-  there you go
![Screenshot from 2022-04-01 13-31-16](https://user-images.githubusercontent.com/101381794/161221415-4396eda8-269a-44dd-b2e8-b6843aafba68.png)

**Comment by umar-shk** [comment] 2022-04-01 08:13
this is what i meant by the panel ads
[Screenshot 2](https://user-images.githubusercontent.com/101381794/161223262-f0c7b3ef-1389-4642-8ce2-3d87e7199a35.png)

**Comment by mapx-** [comment] 2022-04-01 08:23
> this is what i meant by the panel ads

I get no such ads (prime video for example)

Are you sure you are using only the default settings / lists ? No other exceptions in your "my filters" ?

**Comment by umar-shk** [comment] 2022-04-01 08:30
> Are you sure you are using only the default settings / lists ? No other exceptions in your "my filters" ?

100%, i just installed the extension from firefox on my new linux mint una and everything is on default

**Comment by okiehsch** [comment] 2022-04-01 08:34
Can't reproduce.

**Comment by stephenhawk8054** [comment] 2022-04-01 08:48
> @mapx- there you go [Screenshot](https://user-images.githubusercontent.com/101381794/161221415-4396eda8-269a-44dd-b2e8-b6843aafba68.png)

How long have you played until facing the ads?

**Comment by umar-shk** [comment] 2022-04-01 09:50
> How long have you played until facing the ads?
4-5 days id say
