### ISSUE TITLE
https://jovempan.uol.com.br ADBACK

### ISSUE THREAD

**Issue by SHJordan** [uBlockOrigin/uAssets#5306] opened 2019-04-07 16:02 UTC
### URL(s) where the issue occurs

`https://jovempan.uol.com.br/entretenimento/musica/rock-in-rio-tera-tati-quebra-barraco-e-mc-carol-no-espaco-favela.html`

### Describe the issue

[Screen get dimmed, can't scroll nor close the anti-adblocker w/o clicking on the ad banner]

### Screenshot(s)

[![image](https://user-images.githubusercontent.com/884602/55686255-3cd15000-5935-11e9-9239-efc76ab6b75b.png)]

### Versions

- Browser/version: Microsoft Edge
- uBlock Origin version: 1.15.24

### Settings

- Default filters and settings.

**Comment by mapx-** [comment] 2019-04-07 16:17
- still working for me FF / chrome / edge
- check if the defaulted lists in uBo are still enabled

**Comment by okiehsch** [comment] 2019-04-07 22:06
I added the fix for the site 2 days ago, so maybe the filters of the OP have not updated yet.
@SHJordan can you try again after manually updating the `uBO-filers list`.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Comment by SHJordan** [comment] 2019-04-07 22:29
> I added the fix for the site 2 days ago, so maybe the filters of the OP have not updated yet.
> @SHJordan can you try again after manually updating the uBO-filers list.
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

Still getting those on my machine.
![image](https://user-images.githubusercontent.com/884602/55690688-3067ea00-596b-11e9-978a-4a2bf7aab5aa.png)
![image](https://user-images.githubusercontent.com/884602/55690695-3eb60600-596b-11e9-8357-ba0fedc79528.png)

Custom lists are:
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
https://secure.fanboy.co.nz/fanboy-problematic-sites.txt
https://www.i-dont-care-about-cookies.eu/abp/

**Comment by okiehsch** [comment] 2019-04-07 22:42
Sorry, I can't test with Edge, it works fine with Chromium/Firefox on my end.

**Comment by mapx-** [comment] 2019-04-07 22:45
@SHJordan 
- remove aak list, outdated, could generate issues
- reset uBo to the default settings and test again 
or
disable not-default lists 1 by 1 to get the "bad" one

**Comment by bogachenko** [comment] 2019-04-07 22:49
@SHJordan 

like this?
```
jovempan.uol.com.br##+js(abort-on-property-read.js, window.adback_wording)
jovempan.uol.com.br##+js(abort-on-property-read.js, window.abStyle)
```

**Comment by SHJordan** [comment] 2019-04-07 22:55
> @SHJordan
> 
> remove aak list, outdated, could generate issues
> reset uBo to the default settings and test again
> or
> disable not-default lists 1 by 1 to get the "bad" one

what should i use instead of AAK then?

**Comment by mapx-** [comment] 2019-04-07 22:57
Nothing. Anti - adb stuff is directly addressed in uBo lists.

**Comment by SHJordan** [comment] 2019-04-07 23:06
> Nothing. Anti - adb stuff is directly addressed in uBo lists.

So i should keep away from stuff like Nano Defender and such?

Btw, after resetting uBO and disabling privacy lists and enabling the ad ones + malware one's it seems to have did the trick.

**Comment by okiehsch** [comment] 2019-04-07 23:10
> So i should keep away from stuff like Nano Defender and such?

Nano Defender is actively maintained, the AAK List has been abandoned for a few years now.

**Comment by SHJordan** [comment] 2019-04-07 23:14
> So i should keep away from stuff like Nano Defender and such?
> 
> Nano Defender is actively maintained, the AAK List has been abandoned for a few years now.
> https://github.com/reek/anti-adblock-killer/wiki#notice

Is there a Edge port of it? or should i wait for Edge Chromium to be released?

**Comment by okiehsch** [comment] 2019-04-07 23:21
@jspenguin2017 should be able to answer that.

**Comment by jspenguin2017** [comment] 2019-04-08 00:48
Not yet, looks like Microsoft won't accept more legacy extensions anymore. So you'll have to wait for the Chromium-based Edge.

**Comment by jspenguin2017** [comment] 2019-04-08 01:11
Actually, I might build a lite version for the new Edge. There's tons of legacy code from AAK in ND and I want to start to dump them out.

**Comment by okiehsch** [comment] 2019-04-08 01:37
The issue is resolved.

**Closed by okiehsch** 2019-04-08 01:37 UTC
Labels: unable to reproduce
