### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by Numiah** [uBlockOrigin/uAssets#10825] opened 2021-12-08 18:12 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/feed/subscriptions`

### Category

breakage

### Describe the issue

Subscription page only slowly fills up with grey bars, see screenshot.
Site works when Ublock is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/5675550/145261221-714a6970-7901-449c-b3b9-a34ad1733a29.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78731
  cosmetic: 40304
  scriptlet: 16242
  html: 0
listset (total-discarded, last updated): 
  default: 
    NLD-0: 1104-0, 1d.41m
    easylist: 61349-6, 20h.35m
    easyprivacy: 26464-17, 20h.33m
    plowe-0: 3695-809, 11d.7h.41m
    ublock-abuse: 72-0, 20h.31m
    ublock-badware: 3539-60, 20h.28m
    ublock-filters: 29856-127, 20h.26m
    ublock-privacy: 192-5, 20h.24m
    ublock-unbreak: 1705-38, 20h.37m
    urlhaus-1: 8445-0, 1d.39m
filterset (user): [array of 63 redacted]
trustedset: 
  added: [array of 39 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  dynamicFilteringEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 729
  launchFromSelfie: true
popupPanel: 
  blocked: 22
```
</details>

**Comment by uBlock-user** [comment] 2021-12-08 18:26
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2021-12-08 18:26 UTC

**Comment by iam-py-test** [comment] 2021-12-08 23:35
@Numiah please check for duplicate issues before opening a new one
That will save everyone - including you - time and effort
