### ISSUE TITLE
[nsfw] securly.com: popups

### ISSUE THREAD

**Issue by sweeperdeed** [uBlockOrigin/uAssets#11552] opened 2022-02-02 19:00 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.securly.com/blocked?useremail=aarnold@madison.k12.wi.us&reason=policyblacklist&categoryid=BL&policyid=11&keyword=&url=c2l0ZXMuZ29vZ2xlLmNvbS92aWV3LzJwbGF5ZXJnYW1ldW5ibG9ja2Vk&ver=2.98.25&listType=BL`

### Category

popups

### Describe the issue

annoying

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 77731
  cosmetic: 40829
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62546-9, 1d.2h.7m
    easyprivacy: 26691-18, 1d.2h.6m
    plowe-0: 3680-817, 1d.2h.9m
    ublock-abuse: 77-0, 2h.7m
    ublock-badware: 3831-70, 1d.2h.5m
    ublock-filters: 30175-146, 2h.6m
    ublock-privacy: 194-2, 1d.2h.4m
    ublock-unbreak: 1692-39, 1d.2h.2m
    urlhaus-1: 7406-0, 1d.2h.1m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  collapseBlocked: false
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 729 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by Procyon-b** [comment] 2022-02-02 21:03
Isn't `securly.com` related to a firewall/filtering system?

**Comment by uBlock-user** [comment] 2022-02-02 21:05
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11381

**Closed by uBlock-user** 2022-02-02 21:05 UTC
