### ISSUE TITLE
[nsfw] cocomanga.com: detection

### ISSUE THREAD

**Issue by Anyucikad** [uBlockOrigin/uAssets#11141] opened 2021-12-30 18:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.cocomanga.com/15791/1/73.html`

### Category

detection

### Describe the issue

After a few second the page detects the adblocker and shows a message, hiding the pages contents.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78219
  cosmetic: 40139
  scriptlet: 16377
  html: 610
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30604-29, 3d.23h.4m
    ublock-badware: 3633-1, 3d.23h.3m
    ublock-privacy: 179-0, 3d.23h.2m
    ublock-abuse: 81-0, 3d.23h.1m
    ublock-unbreak: 1719-0, 3d.23h
    easylist: 62259-560, 3d.22h.59m
    easyprivacy: 26552-499, 3d.22h.58m
    plowe-0: 3709-3, 10d.17h.33m
    urlhaus-1: 7743-0, 1d.1m
filterset (user): [array of 120 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 867 ms (selfie)
popupPanel: 
  blocked: 21
```
</details>

**Comment by uBlock-user** [comment] 2021-12-30 18:29
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11095

**Comment by gorhill** [comment] 2021-12-30 18:30
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/11140>.

**Closed by uBlock-user** 2021-12-30 18:29 UTC
