### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Noegenes** [uBlockOrigin/uAssets#11825] opened 2022-02-21 14:05 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Ads are half visible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://cdn.upload.systems/uploads/wyIv9CXD.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 79493
  cosmetic: 47648
  scriptlet: 16728
  html: 617
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30829-27, 32m
    ublock-badware: 3969-3, 3d.20h.14m
    ublock-privacy: 200-0, 3d.20h.16m
    ublock-abuse: 77-0, 3d.20h.18m
    ublock-unbreak: 1726-0, 31m
    easylist: 63742-607, 3d.20h.15m
    easyprivacy: 26574-575, 3d.20h.17m
    urlhaus-1: 6613-0, 30m
    plowe-0: 3670-2, 33m
    TUR-0: 8545-90, 1d.18h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 810 ms (selfie)
  maxAssetCacheWait: 167 ms
popupPanel: 
  blocked: 88
  blockedDetails: 
    youtube.com: 70
    doubleclick.net: 5
    google.com: 1
    google.com.tr: 1
    googlesyndication.com: 8
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by uBlock-user** [comment] 2022-02-21 14:11
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2022-02-21 14:11 UTC
