### ISSUE TITLE
Website detects adblocker (online-fix.me)

### ISSUE THREAD

**Issue by harrywon2020** [uBlockOrigin/uAssets#8668] opened 2021-03-05 22:37 UTC
`https://online-fix.me/` - Main site

`https://online-fix.me/games/shooter/16326-predator-hunting-grounds-po-seti.html` - Direct link to where the it detects ublock while logged in.

The website detects the adblocker and hides the download links

**Comment by okiehsch** [comment] 2021-03-06 00:13
@dimisa-RUAdList can you take a look?

I have no clue where the download links are.

**Comment by harrywon2020** [comment] 2021-03-06 01:35
> @dimisa-RUAdList can you take a look?
> 
> I have no clue where the download links are.

https://imgur.com/a/5OKR4jT

this appears while the ublock is active on this page https://online-fix.me/games/shooter/16326-predator-hunting-grounds-po-seti.html while logged in!

**Comment by okiehsch** [comment] 2021-03-06 01:38
> while logged in!

**Comment by wout-codes** [comment] 2021-03-06 01:45
@okiehsch Can you convert this to uBO's Syntax? `online-fix.me#%#//scriptlet("prevent-setTimeout", "fadeIn", "1110")

And then tell him to try that above rule.

**Comment by okiehsch** [comment] 2021-03-06 01:49
@wout-codes thx.

@harrywon2020 does it work if you add
`online-fix.me##+js(nostif, fadeIn, 1110)`
to your filter list?

**Comment by harrywon2020** [comment] 2021-03-06 02:05
> online-fix.me##+js(nostif, fadeIn, 1110)

Works perfectly, download links (https://imgur.com/a/b3dasiK) now show with ublock active!

**Comment by wout-codes** [comment] 2021-03-06 02:07
@okiehsch You can add it and I will address it to AdGuard Russian Filter.

**Comment by okiehsch** [comment] 2021-03-06 02:10
The regional russian list we use ` RU AdList` also adds uBO-syntax filters.
I will close after the issue is fixed in that list. I already pinged the maintainer.

**Comment by harrywon2020** [comment] 2021-03-06 02:11
> The regional russian list we use ` RU AdList` also adds uBO-syntax filters.
> I will close after the issue is fixed in that list. I already pinged the maintainer.

How do i add this AdGuard Russian Filter to my ublock origin filter list?

**Comment by wout-codes** [comment] 2021-03-06 02:11
Just keep it in your `My Filters`

**Comment by harrywon2020** [comment] 2021-03-06 02:17
> Just keep it in your `My Filters`

ok

**Comment by okiehsch** [comment] 2021-03-06 02:21
@harrywon2020 you should have enabled `RU AdList`.
 After the maintainer indicates here that he fixed the issue update that list and you can remove the filters from `My Filters`.

**Comment by harrywon2020** [comment] 2021-03-06 02:32
> er the maintainer indicates here that he

ok thanks. cheers for resolving this

**Comment by dimisa-RUAdList** [comment] 2021-03-06 10:41
RU AdList fix: https://github.com/easylist/ruadlist/commit/43ee8ee52e8edfb46f4806a41c52d6438281cef0

**Closed** 2021-03-06 10:45 UTC
Labels: account required
