### ISSUE TITLE
MakoTV (False Positive)

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#1492] opened 2018-02-07 14:17 UTC
`https://www.mako.co.il/mako-vod?partner=NavBar`
(You need EasyList Hebrew)

Please remove _mako.co.il_ from:
`101greatgoals.com,allthetests.com,ancient-origins.net,biology-online.org,calcalist.co.il,convert-me.com,diffen.com,eurweb.com,globes.co.il,grammarist.com,jerusalemonline.com,mako.co.il,nysun.com,reshet.tv,roadracerunner.com,textsfromlastnight.com,trifind.com,walla.co.il,x17online.com,yad2.co.il,ynet.co.il,yocore.com##script:inject(abort-on-property-write.js, upManager) `
and add:
`mako.co.il##script:inject(nowebrtc.js)`

Thanks

**Comment by mapx-** [comment] 2018-02-07 15:07
Which is the issue ?

**Comment by IsraeliUser** [comment] 2018-02-07 19:28
I get a blank page on Firefox.

**Comment by okiehsch** [comment] 2018-02-07 20:24
What does the filter `mako.co.il##script:inject(nowebrtc.js)` achieve?

I will remove `mako.co.il##script:inject(abort-on-property-write.js, upManager`.

**Comment by IsraeliUser** [comment] 2018-02-08 08:42
They use WebRTC to serve ads.
There are commercials before the videos.

**Comment by IsraeliUser** [comment] 2018-02-14 11:08
Same issue (blank page) with `mako.co.il##script:inject(nowebrtc.js)`, and sometimes ads slips trough (outside MakoTV).

Please readd _mako.co.il_ to:
`101greatgoals.com,allthetests.com,ancient-origins.net,biology-online.org,calcalist.co.il,convert-me.com,diffen.com,eurweb.com,globes.co.il,grammarist.com,jerusalemonline.com,nysun.com,reshet.tv,roadracerunner.com,textsfromlastnight.com,trifind.com,walla.co.il,x17online.com,yad2.co.il,ynet.co.il,yocore.com##script:inject(abort-on-property-write.js, upManager)`
and remove:
`mako.co.il##script:inject(nowebrtc.js)`
until we find a better solution.

Thanks

**Comment by IsraeliUser** [comment] 2018-02-20 13:19
Do you have any idea how to fix it? MakoTV works fine on Chrome. But I get a blank page on Firefox.
Please open this issue.

**Comment by gorhill** [comment] 2018-02-20 14:59
Ok, I added a hidden setting to control whether scriptlets are injected through stream filtering or not, and the page renders fine if scriptlets are injected as with Chrome (though late), but it does not work if they are injected using stream filtering. I have no idea why at this point. I will continue investigating.

**Comment by gorhill** [comment] 2018-02-20 15:04
Ok I think I know why: the page has a HTML error inside the last `noscript` tag on the page (`<ul>` instead of `</ul>`), and this causes the following `script` tags (which are responsible for the page loading properly) to end up being inside the `noscript` tag after serializing back the document. End result: the needed `script` tags at the end are not being seen by Firefox.

**Comment by gorhill** [comment] 2018-02-20 15:52
For now I am going to push an update which causes scriptlets to be injected the "slow" way -- just as before, and just as is done in Chromium. There is no obvious way to work around the issue here which is caused by an HTML error in the page: the `DOMParser` object  used internally by uBO does not ignore `noscript` tags as opposed to the browser internal parser, and I have no way to force DOMParser to ignore `noscript` tags. So for now I need to roll back scriptlet injection through stream filtering. This will also address other (unrelated) issue <https://github.com/gorhill/uBlock/issues/3526>.

**Comment by gorhill** [comment] 2018-02-20 16:16
This is the part of [the `DOMParser` spec](https://w3c.github.io/DOM-Parsing/#the-domparser-interface) which causes issue here (my emphasis):

> `script` elements get marked unexecutable and **the contents of `noscript` get parsed as markup**.

**Comment by mapx-** [comment] 2018-02-22 22:33
uBo/ FF issue, closing

**Closed by mapx-** 2018-02-22 22:33 UTC
