### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by justanormaluserguy** [uBlockOrigin/uAssets#15409] opened 2022-10-25 19:06 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.derstandard.at/`

### Category

detection

### Describe the issue

Biggest News Website in Austria can't read content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 89399
  cosmetic: 42186
  scriptlet: 18199
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    DEU-0: 5990-0, 13h.10m
    easylist: 62279-58, 13h.12m
    easyprivacy: 30777-1182, 13h.13m
    plowe-0: 3671-866, 13h.14m
    ublock-abuse: 76-0, 8d.1h.20m
    ublock-badware: 4394-110, 3d.22h.22m
    ublock-filters: 33113-159, 13h.9m
    ublock-privacy: 257-1, 8d.1h.21m
    ublock-quick-fixes: 428-32, 13h.11m
    ublock-unbreak: 1876-43, 13h.8m
    urlhaus-1: 9527-0, 13h.7m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 85 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 448 ms (selfie)
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 9
  no-cosmetic-filtering: true
  blockedDetails: 
    cleverpush.com: 1
    cxense.com: 1
    googletagmanager.com: 1
    iocnt.net: 1
    npttech.com: 1
    sentry.io: 2
    staticfiles.at: 2
```
</details>

**Comment by okiehsch** [comment] 2022-10-25 20:15
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/15404

**Closed by okiehsch** 2022-10-25 20:15 UTC
Labels: duplicate
