### ISSUE TITLE
anime-odcinki (old o-a.ninja)

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6362] opened 2019-09-28 19:55 UTC
`anime-odcinki.pl##+js(nofab.js)`

users after logout still have broken sliders.

---

I cannot push this into `polskie filtry anty-adblock` - PR is blocked/rejected (protection of anyone against Polish legal regulations on interference in software).

Also I cannot push into `Polskie filtry reklamowe` - Eyeo protection no recommend this...

**Comment by mapx-** [comment] 2019-09-28 20:04
I added those filters to uBo list, now the sliders are ok for me.
Explain (write in polish or use directly DeepL to have a good translation) how to get the broken stuff (provide the steps, eventually a test account and how to log in).

**Comment by gwarser** [comment] 2019-09-28 20:32
This is ridiculous - one of anime-odcinki moderators come to [polish-ads-filter/issues](https://github.com/MajkiIT/polish-ads-filter/issues/14768) to complain about thumbnails being displayed in three rows instead of two-row carousel :) This seems to be caused by FuckAdblock script being blocked by few filters from EasyList.

AntiAdblock is fixed by generichide in uBlock filters.

Allowing FuckAdblock fixes carousel:

    @@||anime-odcinki.pl/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js$script

`nofab.js` also works, can be added instead of above exception.

**Comment by mapx-** [comment] 2019-09-28 20:43
We already have in uBo list  `@@||anime-odcinki.pl^$script,1p`

**Comment by mapx-** [comment] 2019-09-28 20:48
ok, I replaced the filter using `nofab`

**Closed by mapx-** 2019-09-28 20:48 UTC
