### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by simonli92** [uBlockOrigin/uAssets#6436] opened 2019-10-15 22:49 UTC
msn.com page is blank because it blocks `Object.getOwnPropertyDescriptor`

### URL(s) where the issue occurs

https://www.msn.com/en-us/news/politics/democratic-hopefuls-debate-in-ohio/sl-AAIMbAT

### Describe the issue

The page is blank.

### Screenshot(s)

Not needed.

### Versions

- Browser/version: Microsoft Edge 'Canary' (chromium) / Version 79.0.301.0 (Official build)
- uBlock Origin version: Using latest Nano Adblocker.

### Settings

No.

### Notes

`Uncaught TypeError: d is not a function
    at t (hoist-non-react-statics.cjs.js:89)
    at t (hoist-non-react-statics.cjs.js:73)
    at t (hoist-non-react-statics.cjs.js:73)
    at t (hoist-non-react-statics.cjs.js:73)
    at manage-jss.js:22
    at Object.xDbA (index.js:10)
    at o (bootstrap:84)
    at Object.BlQW (GridBase.inspector.ts:1)
    at o (bootstrap:84)
    at Object.+27C (experience.97cc3063c8e1771a8004.js:1)`

In `hoist-non-react-statics.cjs.js`, it uses `getOwnPropertyDescriptor` which is blocked by [filters in line 9180](https://github.com/uBlockOrigin/uAssets/blob/1dec9f94b3b57c1419599606422f9115a1476e03/filters/filters.txt#L9180).

`hoist-non-react-statics` is a common library used by various react library.

**Comment by okiehsch** [comment] 2019-10-15 23:19
The problem is that all other articles are getting Instart Logic redirections on my end if I remove that filter and I can't reproduce the breakage anywhere else other than the link you provided.
For now add 
`msn.com#@#+js(aopw, Object.getOwnPropertyDescriptor)`
to your filter list.
@gorhill should I remove the filter even if that would lead to the whole `msn.com` domain becomming very slow due to the Instart Logic redirection?

**Comment by okiehsch** [comment] 2019-10-15 23:27
@simonli92 I commented the filter out for the moment, so if you update the `uBO-filters` list the issue should be solved.
I will leave this thread open for all users who will complain that they now see ads at `msn.com`.
Add 
`msn.com##+js(aopw, Object.getOwnPropertyDescriptor)`
 to your filter list to get rid of the ads.

**Comment by llacb47** [comment] 2019-10-15 23:29
Does 

```
*$media,redirect=noop.txt,domain=msn.com,3p
@@||eus-streaming-video-msn-com.akamaized.net^$media,domain=msn.com
```

still work for `msn.com`?

**Comment by okiehsch** [comment] 2019-10-15 23:36
Not for me. Without uBO-extra the site takes forever to load with ads.
![image](https://user-images.githubusercontent.com/16838044/66877279-288da000-efb5-11e9-9ca2-bc71820f3a7d.png)

With uBO-extra the site is broken.
![image](https://user-images.githubusercontent.com/16838044/66877318-4a872280-efb5-11e9-9a2d-98a3c6a56d1d.png)

**Comment by simonli92** [comment] 2019-10-15 23:59
@okiehsch Thanks for the fast response. Another example is https://www.msn.com/en-us/news/politics/hunter-biden-interview/sl-AAIPcV4. Currently I didn't see any ads elsewhere. Because this is a native javascript method, I'm not sure why it got blocked in the first place.

**Comment by llacb47** [comment] 2019-10-16 00:01
@okiehsch I just tested `msn.com` on a fresh uBO install on a new Chrome profile and added the three filters in https://github.com/uBlockOrigin/uAssets/issues/6436#issuecomment-542446323. I did not get any ads or redirects to `g00` stuff.

**Comment by okiehsch** [comment] 2019-10-16 00:27
> I'm not sure why it got blocked in the first place.

It was not about blocking `hoist-non-react-statics.cjs.js`. It was and is about Instart Logic redirections.
![image](https://user-images.githubusercontent.com/16838044/66878813-e6b42800-efbb-11e9-9cea-9c1d56b05bd9.png)
For more information about Instart Logic see https://github.com/gorhill/uBO-Extra#purpose

If you can't reproduce the redirection it may be because of your geo-location  I can reproduce with a US IP.
@llacb47 you can reproduce the redirection if you don't add your filters right?

**Comment by okiehsch** [comment] 2019-10-16 00:35
@llacb47 I tried a fresh profile and you are correct, my bad.
I will add your filters and close the issue.

**Closed** 2019-10-16 00:37 UTC
