### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by paulkeng199x** [uBlockOrigin/uAssets#12017] opened 2022-03-03 01:58 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=_PBhl3sxgfE`

### Category

ads

### Describe the issue

Grammarly's ad still shows

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/31581336/156481652-6d8ad66d-a94b-4579-a4bf-e2ddb0dce27c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 79748
  cosmetic: 41288
  scriptlet: 16494
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63978-9, 2d.19h.52m
    easyprivacy: 26628-122, 2d.19h.51m
    plowe-0: 3672-804, 6d.23h.13m
    ublock-abuse: 72-0, 2d.19h.50m
    ublock-badware: 3899-84, 2d.19h.49m
    ublock-filters: 30294-157, 2d.19h.48m
    ublock-privacy: 202-2, 2d.19h.47m
    ublock-unbreak: 1718-39, 2d.19h.46m
    urlhaus-1: 8437-0, 19h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 303 ms (selfie)
  maxAssetCacheWait: 206 ms
popupPanel: 
  blocked: 115
  blockedDetails: 
    youtube.com: 100
    doubleclick.net: 7
    google.com: 2
    google.com.vn: 1
    googlesyndication.com: 1
    googlevideo.com: 3
    yandex.ru: 1
```
</details>

**Comment by uBlock-user** [comment] 2022-03-03 06:07
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2022-03-03 06:07 UTC
