### ISSUE TITLE
aniwave.to: ads

### ISSUE THREAD

**Issue by A-British** [uBlockOrigin/uAssets#19457] opened 2023-08-24 21:42 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aniwave.to/watch/one-piece.ov8/ep-778`

### Category

ads

### Description

add shows when pausing 

### Other extensions used

nhone

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/46797200/709f43e7-f75c-4afa-9e9d-1a8a368b60e9)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98405
 cosmetic: 39303
 scriptlet: 18256
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35221-88, now
  ublock-badware: 7779-1, now
  ublock-privacy: 569-0, now
  ublock-unbreak: 2164-0, now
  ublock-quick-fixes: 232-0, now
  easylist: 69633-692, 1h.58m
  easyprivacy: 33309-715, 1h.59m
  urlhaus-1: 6007-0, now
  plowe-0: 3726-1, now
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 167 ms (selfie)
 maxAssetCacheWait: 76 ms
popupPanel:
 blocked: 10
 network:
  amung.us: 1
  banquetunarmedgrater.com: 1
  bidgear.com: 6
  disqus.com: 2
 extended:
  ##.adx
  ##+js(abort-on-property-read, AaDetector)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
  ##+js(abort-on-property-read, zfgstorage)
  ##+js(no-setInterval-if, break)
  ##+js(remove-attr, data-img|data-target, , stay)
  ##+js(no-window-open-if, !api?call=, 10, obj)
```
</details>

**Comment by RustyLovecraft** [comment] 2023-08-24 22:17
duplicate of #19448
update filter lists (worked for me)

**Closed** 2023-08-25 03:18 UTC
