### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by scarface6000** [uBlockOrigin/uAssets#18872] opened 2023-07-07 14:43 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

adds still pop up when using your website 

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1m
Chromium: 114
filterset (summary):
 network: 96848
 cosmetic: 39403
 scriptlet: 17928
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67971-10, now
  easyprivacy: 33402-62, now
  plowe-0: 3739-1073, now
  ublock-badware: 7509-138, now
  ublock-filters: 33855-147, now
  ublock-privacy: 426-3, now
  ublock-quick-fixes: 278-15, now
  ublock-unbreak: 2064-33, now
  urlhaus-1: 6568-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 421 ms
 maxAssetCacheWait: 154 ms
popupPanel:
 blocked: 17
 network:
  amazon-adsystem.com: 4
  d2v02itv0y9u9t.cloudfront.net: 1
  imrworldwide.com: 5
  scorecardresearch.com: 6
  serving-sys.com: 1
 extended:
  ##+js(window.open-defuser, amazon-adsystem)
```
</details>

**Comment by gorhill** [comment] 2023-07-07 14:48
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/5184>.

**Closed by gorhill** 2023-07-07 14:48 UTC
