### ISSUE TITLE
facebook.com public business web pages

### ISSUE THREAD

**Issue by odeminan** [uBlockOrigin/uAssets#17931] opened 2023-05-04 15:48 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When viewing a public business web page on mobile facebook.com, a pop up overlay opens advertising to log in or sign up for facebook. After closing it, a second pop up overlay opens and tells viewer they are not logged in. It is a persistent pop-up.

### URL(s) where the issue occurs.

`https://m.facebook.com/BrownSheepCompany/`
`https://m.facebook.com/prettylittlequiltshop/`

### uBO version

1.49.2

### Browser name and version

Firefox 108.2.0

### Settings

- default settings

### Notes

Attempted to use element picker to remove pop-up, but overlay still exists. Difficult to select all functionality of the pop-up to resume original page view.

**Comment by okiehsch** [comment] 2023-05-04 16:22
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/3367

**Closed by okiehsch** 2023-05-04 16:22 UTC
