### ISSUE TITLE
rediff.com | Tracking

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4138] opened 2018-11-16 15:42 UTC
### URL(s) where the issue occurs

`https://www.rediff.com`

### Describe the issue

Most, if not all, links (articles, categories, etc.) on the site have some suspicious tracking enabled.

### Versions

- Browser/version: Firefox 63.0.3
- uBlock Origin version: 1.17.2

### Settings

Privacy filter, Annoyances filter, Dan Pollock’s hosts file, hpHosts’ Ad and tracking servers

### Notes

Each link has a mysterious and unnecessary `onclick="trackURL('https://track.rediff.com/click?url=...');return false;"` tracking snippet besides the normal `href`. The two hosts filters listed above warn about and block such links.

**Comment by okiehsch** [comment] 2018-11-16 17:51
Works on my end.

**Comment by in4u** [comment] 2018-11-16 18:52
@mapx- Can you please roll back this fix? It's breaking the site. This generic filter is causing all javascript based buttons and functionality to stop working (e.g. close button on dialogs, settings, widget features, email tools, etc.).

There's a need to restrict the filter to only those links which have tracking enabled, e.g. `trackURL('https://track.rediff.com/click?url=...');return false;` and not everything else. Please re-open this issue until a better solution is found.

**Comment by okiehsch** [comment] 2018-11-16 19:29
The easy fix is to add
`||track.rediff.com^` to `uBO-privacy`

**Comment by in4u** [comment] 2018-11-16 20:05
I am not very familiar with uBO's extended syntax but is there any way to fine-tune the original fix or build a related one by tweaking certain parameters to apply only if `onclick` contains the tracking URL `track.rediff.com` or something like that? The initial fix worked very well, just that it worked a little too much!

**Comment by mapx-** [comment] 2018-11-16 20:07
You mean the second filter ?
`rediff.com##+js(remove-attr.js, onclick)`

**Comment by mapx-** [comment] 2018-11-16 20:12
@okiehsch  do you see something blocked using that network filter ^

**Comment by in4u** [comment] 2018-11-16 20:16
>You mean the second filter ?

Yes, if the second filter can be constrained that way, maybe it'll work. Worth testing I'd say.

**Comment by mapx-** [comment] 2018-11-16 20:18
https://github.com/gorhill/uBlock/wiki/Resources-Library#remove-attrjs-

```
Parameters:
required, attribute or list of attributes joined by |
optional, CSS selector, specifies nodes from which attributes will be removed
```

**Comment by okiehsch** [comment] 2018-11-16 20:20
`CSS selector` which is what in this case ?

**Comment by okiehsch** [comment] 2018-11-16 20:23
`rediff.com##+js(remove-attr.js, onclick, .img)` maybe.

**Comment by okiehsch** [comment] 2018-11-16 20:35
Add
````
rediff.com##+js(remove-attr.js, onclick, .img)
rediff.com##+js(remove-attr.js, onclick, .black)
````
 and click on any picture or the text under the picture. It works on my end.

**Comment by okiehsch** [comment] 2018-11-16 20:43
OK,how about
````
rediff.com##+js(remove-attr.js, onclick, .colbox)
rediff.com##+js(remove-attr.js, onclick, .colboxR)
````

**Comment by mapx-** [comment] 2018-11-16 20:46
It works for me (removing onclick on the first page):
`rediff.com##+js(remove-attr.js, onclick, .black)`

**Comment by mapx-** [comment] 2018-11-16 20:48
Let's see if still blocks something useful @in4u  and eventually all the cases still with tracking

**Comment by okiehsch** [comment] 2018-11-16 20:50
You are right 
`rediff.com##+js(remove-attr.js, onclick, .black)` makes `rediff.com##+js(remove-attr.js, onclick, .img)`
redundant.

**Comment by mapx-** [comment] 2018-11-16 20:53
I searched the page and I found other different classes
for example `curhand`

but also cases without an anchor class
`<a href="https://www.rediff.com/movies" onclick="trackURL('https://track.rediff.com/click?url=___https://www.rediff.com/movies___&amp;cmp=mov1_nav&amp;lnk=mov1_nav&amp;nsrv1=ushome');return false;"><div class="n_tabnormal">Movies</div></a>`

**Comment by mapx-** [comment] 2018-11-16 20:54
maybe the syntax could be modified to use a text part (like `trackURL`) @gorhill

**Comment by okiehsch** [comment] 2018-11-16 20:55
`rediff.com##+js(remove-attr.js, onclick, ##[href*=".rediff.com/"])` also works I think.

**Comment by in4u** [comment] 2018-11-16 20:59
Wow, if only that function also had a parameter allowing to search for string. This could have been an open and shut case then!

Okay guys, I will test the filter `rediff.com##+js(remove-attr.js, onclick, .black)`. Let me know if `rediff.com##+js(set-constant.js, onclick, noopFunc)` is also required along with it?

**Comment by okiehsch** [comment] 2018-11-16 21:01
Actually I made a mistake while testing, @mapx- add  `||track.rediff.com^` to your list to easily see if you still get redirected.
Now add
`rediff.com##+js(remove-attr.js, onclick, .black)`
and click any picture, I get the warning message.

**Comment by mapx-** [comment] 2018-11-16 21:06
right, needing  `.img` too, I was testing only clicking the text part ..

**Comment by mapx-** [comment] 2018-11-16 21:09
well, @in4u you could use

```
||track.rediff.com^
rediff.com##+js(remove-attr.js, onclick, .img)
rediff.com##+js(remove-attr.js, onclick, .black)
rediff.com##+js(remove-attr.js, onclick, .curhand)
```
the first 1 to detect other places still to be fixed

**Comment by okiehsch** [comment] 2018-11-16 21:14
`rediff.com##+js(remove-attr.js, onclick, .curhand)` does not work for me.
 I tried `rediff.com##+js(remove-attr.js, onclick, .icondiv)` that earlier and got confused, I still don't understand why this does not work for
![image](https://user-images.githubusercontent.com/16838044/48647674-f498ac00-e9ec-11e8-93ac-e3f607834b9a.png)

**Comment by mapx-** [comment] 2018-11-16 21:17
No ...curhand is breaking the login

**Comment by mapx-** [comment] 2018-11-16 21:18
maybe you can not use the parent lass / div

**Comment by in4u** [comment] 2018-11-16 21:43
I already have that `.curhand` filter enabled along with the 3 other rules you shared previously. I am noticing that only the article images and links got clean but topic headings, more stories, trending now links, moneywiz live links, track my order, etc. all still have tracking enabled.

**Comment by okiehsch** [comment] 2018-11-16 21:50
With
````
rediff.com##+js(remove-attr.js, onclick, .img)
rediff.com##+js(remove-attr.js, onclick, .black)
rediff.com##+js(remove-attr.js, onclick, .curhand)
````
you have no broken functionality, so we can add those filters ?

**Comment by in4u** [comment] 2018-11-16 22:09
Haven't come across anything broken yet.

**Comment by okiehsch** [comment] 2018-11-16 22:09
````
rediff.com##+js(remove-attr.js, onclick, .img)
rediff.com##+js(remove-attr.js, onclick, .black)
rediff.com##+js(remove-attr.js, onclick, .curhand)
rediff.com##+js(remove-attr.js, onclick, [href*=".rediff.com/"])
rediff.com##+js(remove-attr.js, onclick, ##[href="http://money.rediff.com"])
`````
is best I can come up with, how does that look for you.

**Comment by gwarser** [comment] 2018-11-16 23:17
`rediff.com##+js(remove-attr.js, onclick, [onclick^="track"])`

Does not work for reinserted content ("Recommended Products For You") because is executed only once on page load.

I also see `trackAppURL` and some code in `onmousedown`.

**Comment by mapx-** [comment] 2018-11-17 07:38
well, those filters of @gwarser  seem to do the job, especially:
`rediff.com##+js(remove-attr.js, onclick, [onclick^="track"])`

**Comment by mapx-** [comment] 2018-11-17 07:53
@gwarser  maybe we should add use cases for these scriptlets
https://github.com/gorhill/uBlock/wiki/Resources-Library#remove-attrjs-

**Comment by in4u** [comment] 2018-11-17 09:00
@mapx- 1st and 3rd filters seem to work without breaking anything yet. But the 2nd case needs to be dealt with by some other function or way to replace the tracking link with target link extracted from it. This may be accomplished by injecting custom javascript, I guess. Does uBO's extended syntax support that?

Oh and yes, please include examples and use cases in the wiki for not only this but other scriptlets too. It'd be easier for me then to wrap my head around them!

**Comment by mapx-** [comment] 2018-11-17 09:07
@in4u  for the second filter => what is broken ? where / which page ?

**Comment by mapx-** [comment] 2018-11-17 09:14
I got it on gadgets, well in this case uBo cannot help, see above an extension (firefox) which can deal with such cases.

Well, I'll add the first and third filters to the privacy list.

**Comment by mapx-** [comment] 2018-11-17 09:32
maybe uBo could implement $rewrite option (ABP's idea)

see about rewrite:
https://github.com/uBlockOrigin/uAssets/issues/1905

see also about rewrite here
https://adblockplus.org/filters

**Comment by mapx-** [comment] 2018-11-17 09:35
https://adblockplus.org/development-builds/rewriting-url-instead-of-blocking

**Comment by gorhill** [comment] 2018-11-17 10:35
> maybe uBo could implement `$rewrite` option

The way the filter was designed is flawed in my opinion, I won't be implemented the way it has been defined in ABP.

In any case, the issue here is not a good basis to justify such feature, from what I read here, it's first-party tracking, and foiling it won't accomplish anything useful, because when you load a new page in your browser, the server will still know this through just its plain logs.

**Comment by okiehsch** [comment] 2018-11-17 21:56
> In any case, the issue here is not a good basis to justify such feature, from what I read here, it's first-party tracking, and foiling it won't accomplish anything useful, because when you load a new page in your browser, the server will still know this through just its plain logs. This is not a case for uBO's filter lists.

**Closed by okiehsch** 2018-11-17 21:56 UTC

**Comment by in4u** [comment] 2018-11-18 08:37
I accept this closure, not particularly for the reason quoted but because the fixes implemented were the best possible given the current feature set of uBO. Whether or not the issue had valid privacy concerns, it sure had nuisance / annoyance value, at least for me. Besides, if the intended tracking could be done via logs then there's no real need for the site to go an extra mile and unnecessarily use resources or bloat pages.

Anyways, this was an insightful thread where I also learned a few things. So, an extra thanks to you guys!

**Comment by okiehsch** [comment] 2018-11-18 08:46
I added the quote to emphasize that the non-fixed parts of your issue will not be fixed by any new scriptlet, which was the reason to close the issue.

**Comment by uBlock-user** [comment] 2018-11-18 12:13
> But the 2nd case needs to be dealt with by some other function or way to replace the tracking link with target link extracted from it.

What you're asking for is link cleaner. There are dedicated extensions for that. I doubt scriptlet can take care of this.

**Comment by ghajini** [comment] 2019-03-01 20:41
1st party ads `shopping.rediff.com`, @mapx- would you suggest the filter, i categorise as annoyance being 1st party

**Comment by mapx-** [comment] 2019-03-01 21:13
well, we should remove that filter in ublock privacy

for 1. add:
```
||imshopping.rediff.com^
rediff.com##[href^="http://shopping.rediff.com/"], [id^="bdeal"]
```

**Comment by ghajini** [comment] 2019-03-01 21:19
leftover after adding your filter `shopping ......`

**Comment by mapx-** [comment] 2019-03-01 21:21
does this work ?
`rediff.com###div_advt_right`

**Comment by ghajini** [comment] 2019-03-01 21:23
nope
`https://www.rediff.com/news` still multiple `shopping.....`

**Comment by mapx-** [comment] 2019-03-01 21:29
`rediff.com##.outborder:has-text(/shopping/i)`

**Comment by mapx-** [comment] 2019-03-01 21:30
maybe if it's about strict blocking

**Comment by ghajini** [comment] 2019-03-01 21:34
yeah strict blocking because it is scrambled between news articles , i would have liked those shopping thing if they have kept at page sidebar

**Comment by krystian3w** [comment] 2022-08-29 00:45
@[mapx-](https://github.com/mapx-) mapx- added the[ SSAI ](https://github.com/uBlockOrigin/uAssets/labels/SSAI)label [on 7 Apr 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1562292997)
@[jspenguin2017](https://github.com/jspenguin2017) [jspenguin2017](https://github.com/jspenguin2017) mentioned this issue on 9 May 2018
[Ads] cwtv.com NanoAdblocker/NanoFilters#25
Closed
@jspenguin2017 jspenguin2017 mentioned this issue on 3 Jun 2018
nbc.com #2409
Closed
@[okiehsch](https://github.com/okiehsch) okiehsch changed the title Cwtv video ads Websites using SSAI (server side ad injection) [on 3 Jun 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1659832690)
This was referenced on 3 Jun 2018
Viceland Video Ads #1541
Closed
uBO on Chrome not blocking fox.com #772
Closed
abc7.com #794
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 22 Jul 2018
[Anti-adblock] investigationdiscovery.com #2966
Closed
@[SkeletalDemise](https://github.com/SkeletalDemise) SkeletalDemise mentioned this issue on 22 Jul 2018
anti Adblocker on discovery.com sciencechannel.com #2931
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 2 Sep 2018
Ads Loading gorhill/uBO-Extra#76
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 15 Sep 2018
Ads while watching shows on FOX #3486
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 27 Oct 2018
Midroll Ads Aren't being blocked CityTV.com #3847
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 17 Nov 2018
rediff.com | Tracking #4138
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 23 Nov 2018
Fails to Block Ads on The CW - http://thecwtv.com #4179
Closed
@[stoically](https://github.com/stoically) stoically mentioned this issue on 20 Mar 2019
ALL twitch.tv issues #5184
Open
@[okiehsch](https://github.com/okiehsch) okiehsch mentioned this issue on 11 Jun 2019
https://www.brighteon.com/ #5803
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 17 Jun 2019
discovery.com videos not working easylist/easylist#3636
Closed
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment from [prateekrastogi](https://github.com/prateekrastogi) [on 26 Jan 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-2979959103)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user added the[ can't fix ](https://github.com/uBlockOrigin/uAssets/labels/can%27t%20fix)label [on 17 Jun 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-3453347081)
@[nebchan](https://github.com/nebchan) nebchan mentioned this issue on 29 Sep 2020
Twitch TV now injecting ads #7968
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 1 Nov 2020
Add queryprune filters to deal with SSAI #8131
Merged
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 16 Aug 2021
pluto.tv: Ads not being blocked #9764
Closed
6 tasks
@[subby2006](https://github.com/subby2006) subby2006 mentioned this issue on 1 Sep 2021
sbs.com.au ondemand has a new player and it detects ublock #7836
Closed
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 20 Jan
@uBlock-user
[update](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-394129540
[eb9148f](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a)
This was referenced on 21 Jan
go.tlc.com: ads #11419
Closed
go.discovery.com: ads #11420
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user closed this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/ac8860312f726292bd3e7c2f34a82f6d20614dbe [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035560189)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user reopened this [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035564682)
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 9 Feb
@uBlock-user
[append](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-1033865488
[fe89b1b](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 17 Feb
discovery plus italy showing ads #11772
Closed
6 tasks
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment [on 9 Mar](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6207603084)
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 25 Mar
hulu.com: ads #12407
Closed
8 tasks
This was referenced on 27 Mar
philo.com: ads #12469
Closed
player.stv.tv: ads #12513
Closed
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 Apr
mech-plus.com: ads #12589
Closed
8 tasks
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 May
amc.com: ads #13065
Closed
8 tasks
This was referenced on 4 Jul
primevideo.com: ads #13906
Closed
animalplanet.com: ads #13969
Closed
tvbanywherena.com: video ads #13978
Closed
This was referenced 23 days ago
vix.com: ads #14213
Closed
discoveryplus.com: ads #10870
Closed
discoveryplus.com: ads #14365
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue 6 days ago
go.tlc.com: ads #14451
Closed
8 tasks
@[MasterKia](https://github.com/MasterKia) MasterKia mentioned this issue 5 days ago
primevideo.com: ads #14512

**Comment by mapx-** [comment] 2023-11-24 18:44
use the element picker, if you find a good filter paste it here (I have no account on rediff)
