### ISSUE TITLE
[nsfw] detection

### ISSUE THREAD

**Issue by rafalohaki** [uBlockOrigin/uAssets#14579] opened 2022-08-29 02:00 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://koushoku.org/`

### Category

detection

### Describe the issue

detects adblock and ban if not disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 104784
  cosmetic: 59406
  scriptlet: 23264
  html: 737
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
  added: 
    curben-phishing: 80253-3, 5m
    curben-pup: 187-0, 5m
    adguard-annoyance: 56782-460, never
    ublock-annoyances: 4558-155, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 33177-38, 3d.10h.29m
    ublock-badware: 4223-0, 3d.10h.28m
    ublock-privacy: 247-0, 11d.4h.39m
    ublock-abuse: 76-0, 11d.4h.38m
    ublock-unbreak: 1850-0, 3d.10h.27m
    ublock-quick-fixes: 402-0, 53m
    urlhaus-1: 7101-0, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 747 ms (selfie)
  maxAssetCacheWait: 1536 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment] 2022-08-29 03:16
> - [X] I verified that the issue has not already been reported (use this button to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14477

**Comment by MasterKia** [comment] 2022-08-29 03:17
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14477

**Closed by MasterKia** 2022-08-29 03:16 UTC

**Comment by MasterKia** [comment] 2022-08-29 03:18
> removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null

You should keep these filters enabled.

**Comment by rafalohaki** [comment] 2022-08-29 03:23
> > removed:
> > easylist: null
> > easyprivacy: null
> > plowe-0: null
> 
> You should keep these filters enabled.

still the same: Adblocker detected

**Comment by MasterKia** [comment] 2022-08-29 04:01
> still the same

I'm aware, but those filter lists should be enabled regardless.
