### ISSUE TITLE
www.tv-tokyo.co.jp | aka-secure-img.uliza.jp/Player

### ISSUE THREAD

**Issue by fireattack** [uBlockOrigin/uAssets#5455] opened 2019-04-27 08:23 UTC
### URL(s) where the issue occurs

`https://www.tv-tokyo.co.jp/anime/anireco/`

### Describe the issue

The video player on this page is broken (no play button) by the rule
`-google-analytics.$third-party` in uBlock filters – Unbreak .

It filters out `https://aka-secure-img.uliza.jp/Player/js/ulizahtml5-google-analytics.min.v1.9.1.js` which is essential for this video player to work.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/4130991/56847013-bce73780-689b-11e9-96c8-1febbbd2a9a6.png)

### Versions

- Browser/version: Google Chrome 74.0.3729.108
- uBlock Origin version: v1.18.16

### Settings

All default

**Comment by okiehsch** [comment] 2019-04-27 08:41
I don't think that script is essential for the video player, if I add
````
@@||uliza.jp/IF/RequestVideoTag.aspx$script,domain=www.tv-tokyo.co.jp
||uliza.jp/Player/js/*-google-analytics$script,redirect=noopjs,domain=tv-tokyo.co.jp
````
the video works fine on my end.

**Comment by fireattack** [comment] 2019-04-27 08:56
I agree, but that's the only rule I saw that was triggered when I check the log.

**Comment by okiehsch** [comment] 2019-04-27 08:57
So, the issue is also fixed on your end with the updated filter list?

**Comment by fireattack** [comment] 2019-04-27 08:58
Yeah, it works after I added them to `myfilters`

**Comment by okiehsch** [comment] 2019-04-27 09:00
You can remove the filters and manually update `uBO-unbreak`, I added them to that list.

**Closed by okiehsch** 2019-04-27 09:00 UTC
