### ISSUE TITLE
lookmovie2.to: ads

### ISSUE THREAD

**Issue by JackGreenEarth** [uBlockOrigin/uAssets#21848] opened 2024-01-08 18:46 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lookmovie2.to/shows/play/1690174185-avatar-the-last-airbender-2005`

### Category

ads

### Description

It shows both popups asking for premium, and a 'wait 10 seconds' thing when watching any video

### Other extensions used

Dinosuar Game for Firefox
Text Translations
Bitwarden
Snowflake
Consent-o-matic
WebXR API Emulator
Return Youtube dislike
Bing Chat
GNOME Shell integration
Unpaywall
Yandex Evolution
Firefox DEVTools ADB Extension
Terms of Service; Didn't read

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 115874
 cosmetic: 44209
 scriptlet: 18635
 html: 2006
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  ublock-filters: 37046-190, now
  ublock-badware: 7773-11, now
  ublock-privacy: 946-0, now
  ublock-unbreak: 2233-0, now
  ublock-quick-fixes: 207-1, now
  easylist: 76901-618, now
  easyprivacy: 43399-823, now
  urlhaus-1: 10225-0, now
  plowe-0: 3784-1, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1309 ms (selfie)
 maxAssetCacheWait: 178 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(set-constant, Yii2App.playbackTimeout, 0)
```
</details>

**Comment by huyszn** [comment] 2024-01-08 21:12
This is a duplicate of #21071 and it was mentioned it won't be fixed because it is a paywall

**Closed** 2024-01-08 21:14 UTC
Labels: duplicate
