### ISSUE TITLE
pixiv user page

### ISSUE THREAD

**Issue by pl0okm9ijn** [uBlockOrigin/uAssets#8313] opened 2020-12-03 06:13 UTC
### Versions

- Browser/version: [win10computer Firefox83.0 (64 bit)&GoogleChrome 87.0.4280.88（Official Build） （64 bit）]
- uBlock Origin version: [1.31.0]

**Comment by ZaphodBeebblebrox** [comment] 2020-12-03 06:15
Duplicate of #8311 

Update your filter lists.

**Closed by ZaphodBeebblebrox** 2020-12-03 06:15 UTC
