### ISSUE TITLE
remove youtube redirects to links in the description and instead access the clean full link

### ISSUE THREAD

**Issue by RustoMCSpit** [uBlockOrigin/uAssets#19257] opened 2023-08-01 19:56 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

,

### URL(s) where the issue occurs.

,

### Screenshot(s)

,

### uBO version

newest

### Browser name and version

friefox, latest

### Settings

.

### Notes

.

**Comment by okiehsch** [comment] 2023-08-01 20:16
> remove youtube redirects to links in the description and instead access the clean full link

The only thing I can decipher from this description is that it has some connection  with youtube.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by okiehsch** 2023-08-01 20:16 UTC

**Comment by RustoMCSpit** [comment] 2023-08-01 20:34
> > remove youtube redirects to links in the description and instead access the clean full link
> 
> The only thing I can decipher from this description is that it has some connection with youtube.
> 
> Duplicate of #7636

i thought it was self-explantory, youtube makes redirect tracker links to any links in the description of a youyube video but hides them under the plain text that appears to shpw a differeng link

**Comment by okiehsch** [comment] 2023-08-01 20:37
> youtube makes redirect tracker links to any links in the description of a youyube video but hides them under the plain text that appears to shpw a differeng link

I am not an avid youtube user, so I never noticed that behaviour but that description I understand, still it's a youtube issue and all youtube issues are in https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by iam-py-test** [comment] 2023-08-02 19:41
@RustoMCSpit Try this filter and see if it works:
```adblock
youtube.com##+js(href-sanitizer,a[href*="https://www.youtube.com/redirect"], ?q)
```

**Comment by RustoMCSpit** [comment] 2023-08-02 19:42
> @RustoMCSpit Try this filter and see if it works:
> 
> ```
> youtube.com##+js(href-sanitizer,a[href*="https://www.youtube.com/redirect"], ?q)
> ```

ngl wouldnr know how

**Comment by iam-py-test** [comment] 2023-08-02 19:49
Add to your My Filters: https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters
