### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Allu71** [uBlockOrigin/uAssets#13553] opened 2022-06-04 11:34 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/shadybunny`

### Category

ads

### Describe the issue

Got 2 separate ads while watching a stream

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83650
  cosmetic: 45366
  scriptlet: 17181
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    FIN-0: 1789-1, 21m
    easylist: 67950-51, 21m
    easyprivacy: 27150-123, 21m
    plowe-0: 3638-781, 21m
    ublock-abuse: 75-0, 21m
    ublock-badware: 4166-91, 21m
    ublock-filters: 31636-91, 21m
    ublock-privacy: 222-2, 21m
    ublock-quick-fixes: 203-10, 21m
    ublock-unbreak: 1825-40, 21m
    urlhaus-1: 8893-0, 21m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 735 ms (selfie)
  maxAssetCacheWait: 236 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 4
    google-analytics.com: 1
    imrworldwide.com: 1
    scorecardresearch.com: 32
    sentry.io: 11
```
</details>

**Comment by mapx-** [comment] 2022-06-04 11:39
see https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/


Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by mapx-** 2022-06-04 11:39 UTC

**Comment by MasterKia** [comment] 2022-06-04 12:31
> #5184

`This conversation has been locked and limited to collaborators.`
Is this intended?

**Comment by mapx-** [comment] 2022-06-04 14:15
unlocked
