### ISSUE TITLE
(Contains NSFW content) Submitting 57 entries from my own lists

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5030] opened 2019-02-28 03:26 UTC
As I've now slowly realised that none of my non-Nordic lists would be added to uBO anytime soon, I figured that I could just as well submit a bunch of entries from *Browsing Websites Without Logging In* and *Anti-'Notification pre-prompt banners' List.txt* to uAssets.

These entries predominantly take care of removing obtrusive (or even uncloseable) login prompts for non-logged-in users, as well as a few that remove large signin banners or prompts that ask if you if you want to receive a browser notification prompt.

I did not feel certain if it was issue reports or pull requests that were taken care of most quickly in this repo, and I'm also not certain whether they'd all be *uBlock Filters - Annoyances* material or if a few of them were more suitable for the main *uBlock Filters* list. I also presumed that you guys would potentially be keen on testing out the new entries first. Therefore I've made this as an issue report for now. I can attempt to turn this into a pull request if it'd be needed of me to do so.

I also decided to go easy on it to begin with, by not (yet?) submitting entries that manages to bypass outright paywalls, as I've managed to do on a small handful of sites including `experts-exchange.com` and `study.com`, among others.

Submitted entries, example pages, explanations of what they remove, and usage notes:

```
! https://en-gb.facebook.com/Sonic/ (When not logged in)
!! Removes the main login prompt when browsing an account's timeline
facebook.com##._5hn6
!! Attempts to remove the "Not logged in" dialog window that shows up further down on the timelinw
facebook.com##.generic_dialog_modal.pop_dialog

! https://mobile.twitter.com/italiancomments (When not logged in)
!! Aims to remove the login overlay prompt when browsing down an account's timeline
mobile.twitter.com##.rn-13w96dm
mobile.twitter.com##div[data-focusable="true"] > div > div > div:has(div > div > div > div > div > div > div > div > div > div > div > div[role="button"] > div)
mobile.twitter.com##.rn-1kihuf0.rn-1awozwy
!! Making it easier to loose up the swipe-scrolling
mobile.twitter.com##body:style(overflow-y: visible !important; overscroll-behaviour-y: inherit !important)

// Fixed
! https://pinterest.com/pin/440156563573544264/ (When not logged in)
! Important note: Even with these entries, non-logged-in people who wish to browse Pinterest freely, will still have to use "Open in new tab" very liberally.
!! Removes the login prompt when browsing down on a page
pinterest.*##div[data-test-id="giftWrap"]
!! Removes the login prompts when opening the "Full page modal scroller" (Which was very hard to do without removing the intentional login prompt)
pinterest.*##div[class="Closeup__wrapper"] > div > div[style^="cursor: default"]
pinterest.*##.Hsu.iyn.zI7:nth-of-type(2) > div > .FullPageModal__scroller
pinterest.*##div:nth-of-type(2) > div > div > div > .Hsu.iyn.zI7 > div.Hsu.iyn.zI7:nth-of-type(2) > div
!! Removes the "Open" overlay on images, so that their raw versions can more easily be opened
pinterest.*##.GrowthUnauthPinImage > a > div[class^="Jea"]:has(button[class^="noButtonStyles "])
pinterest.*##div[class="GrowthUnauthPinImage__imageDim"]
! Removing the blurring of random Pinterest images
pinterest.*##div[style^="filter:"]:style(filter: none !important)
// Fixed.

// Will not be added
! https://www.pixiv.net/member_illust.php?mode=medium&illust_id=53406591 (When not logged in) (Example page is NSFW)
!! Removes the login buttons that block the (blurred) view of R-18 images
pixiv.net##.r18-image.front-centered
// Will not be added

! Quora for phone browsers (When not logged in) (Requires a mobile user agent, presumably one for Android) (May require clicking around between a few pages for up to 2min to reproduce)
! https://www.quora.com/What-was-the-windows-briefcase-used-for
! Important note: It may or may not break the "intended" login button in the upper right... if not for how that button appears to have been made non-functional by Quora anyway. For comparison, the button also appears to be broken in desktop mode when using `uBlock Filters`
quora.com##.new_signup_dialog.modal_bg
quora.com##._DialogSignupForm
quora.com##.signup_wall_prevent_scroll .PageWrapper:style(filter: none !important)
quora.com##.signup_wall_prevent_scroll:style(position: unset !important)

// Fixed.
! https://addons.opera.com/ (While using a non-Opera browser)
!! Removes fullscreen prompt about installing Opera
addons.opera.com###overlay
// Fixed

// Already fixed
! https://github.com/DandelionSprout/adfilt (When not logged in)
!! Removes login banner
github.com##.signup-prompt
// Already fixed

// Fixed
! https://www.deezer.com/no/playlist/4419236002 (Start a song preview, then click pause) (When not logged in)
!! Removes login prompt
deezer.com##.modal-wrapper
deezer.com##.modal-backdrop
// Fixed

// Fixed
! https://www.instagram.com/explore/tags/lalaloopsy/ (When not logged in)
! Removes the bottom login banner
instagram.com##.ZUqME:has(a[href^="/accounts/emailsignup/"])
// Fixed.

// Fixed
! https://weili.ooopic.com/weili_16580578.html (When not logged in)
!! Removes uncloseable login prompt
ooopic.com###public-mask-login
// Fixed

// Fixed
! https://superuser.com/questions/836988/how-to-move-old-gmail-attachments-to-google-drive (When not logged in)
!! Removes the "Here's how it works" banner at the top
stackexchange.com,askubuntu.com,serverfault.com,superuser.com,mathoverflow.net,stackapps.com#?#.js-dismissable-hero:-abp-contains(Sign up)
// Fixed

// Fixed
! https://www.mrfood.com/
!! Removes an uncloseable newsletter prompt
mrfood.com###newsletterSignUpDivAnime
mrfood.com###viewportGreyout
mrfood.com##.in-content-container-coverage
// Fixed

//  Fixed
! https://www.theclever.com
!! Removes a large (and on my end invisible) banner that prevents clicking on most of the page
theclever.com###overlay_search
//  Fixed

! https://nijie.info/view.php?id=286170 (When not logged in) (Example page is NSFW)
!! Removes the login prompt above the images
nijie.info##.nijie_regist
nijie.info##.warning_illust
nijie.info##.twit-button
!! Removes the blur from the images
nijie.info##.ngtag.mozamoza:style(-webkit-filter: none !important)

// Fixed
! https://thredup.com/ (When not logged in)
!! Removes uncloseable login prompt that randomly appears after browsing between 2 or 3 pages
thredup.com##.modal-underlay
thredup.com##.redux-modal
// Fixed

// Fixed
! https://quizlet.com/217459103/einkaufen-german-diagram/ (When not logged in)
!! Makes all the flashcards on the vertical list visible
quizlet.com##.SignupWallInline-overlay
quizlet.com##.SetPageTerm:style(display: block !important) 
// Fixed

// Fixed
! https://www.feedspot.com/infiniterss.php?q=site:https%3A%2F%2Fwww.youtube.com%2Ffeeds%2Fvideos.xml%3Fuser%3Dkinoyuu0204 (When not logged in)
!! Removes an uncloseable login prompt
feedspot.com##.blackout
feedspot.com##.regoverlay
feedspot.com##.mfp-container
feedspot.com##.fadeIn.animated
feedspot.com##.fixedBar
// Fixed

// Fixed
! https://www.volunteermatch.org/search/?l=Trondheim,%20Norway (When not logged in)
!! Removes an uncloseable login prompt
volunteermatch.org###window_overlay
volunteermatch.org###req_login_reg_interrupt
// Fixed

// Fixed
! https://www.beprobeproud.org/profession/plumber (When not logged in)
!! Removes a login prompt that for some reason takes you back to the top of the page if you try to click on its X button
beprobeproud.org##.movement-popup
// Fixed

// Fixed
! https://www.prestashop.com/forums/topic/947407-prestashop-1750-is-available/ (When not logged in)
!! Removes the "Create an account (...)" banner at the bottom
prestashop.com##.cTopicPostArea:has(> div > .cGuestTeaser)
// Fixed

// Fixed
! https://seekingalpha.com/article/3975358-dhx-medias-dhxm-ceo-dana-landry-q3-2016-results-earnings-call-transcript?page=2 (When not logged in)
!! Makes certain shareholder meeting transcripts entirely readable on a single page, bypassing a block on going past page 2 or using the "Single page view" button without logging in.
seekingalpha.com##.in.fade.modal
seekingalpha.com##.modal-dialog
seekingalpha.com##.p:style(display: block !important)
seekingalpha.com##.blured:style(opacity: 1.0 !important)
seekingalpha.com##body:style(overflow: auto !important;)
// Fixed

// Fixed
! https://www.bookbub.com/blog/2018/08/28/best-fantasy-books-2018 (When not logged in)
!! Makes it possible to read all entries in their most popular blog articles
bookbub.com##.post-section:style(filter: none !important; -webkit-filter: none !important; pointer-events: all !important)
bookbub.com##.blur.signup-gate
// Fixed

! ——————————————————————————

// Non-critical, as it seems to have been fixed in an included list, namely that of Peter Lowe.
! Pre-notification prompts that ask you if you want to be asked to receive pretty bad browser notifications
! https://sysla.no/, https://tomshardware.co.uk, https://mashable.com/, among other sites.
||cdn.onesignal.com
// Non-critical, as it seems to have been fixed in an included list, namely that of Peter Lowe.

// Fixed
! https://www.ndtv.com/
! (It may take up to a minute before the pre-prompt shows up.)
###___ndtvpushdiv
// Fixed
```

### Versions

- Browser/version: Chrome 72.0.3626.119 64-bit
- uBlock Origin version: Nano Adblocker 1.0.0.89 + Nano Defender 15.0.0.102

### Settings

The new entries were tested alongside these lists:
![image](https://user-images.githubusercontent.com/22780683/53538998-19361100-3b10-11e9-9e88-e56b759dbf19.png)

### Notes

None in particular that I haven't mentioned above already.

**Comment by adranger** [comment] 2019-02-28 21:25
You should've checked these entries one by one before posting them here. For instance, the Instagram login annoyance was fixed last week: https://github.com/uBlockOrigin/uAssets/issues/4985

**Comment by okiehsch** [comment] 2019-02-28 21:33
To be precise, the uBO-annoyance list is meant for issues that can't be fixed in `Adguard Annoyances` and `Fanboy's Annoyance` list.
https://github.com/uBlockOrigin/uAssets/blob/6edc7f594acbda43af5090dc44205b9412914af8/filters/annoyances.txt#L2-L3

Your github filter is part of both of those lists.

**Comment by okiehsch** [comment] 2019-02-28 21:37
Also about your `onesignal` filters, are they necessary if `cdn.onesignal.com` requests are blocked?

Those requests are blocked with a default setup but I can see that you have disabled `Peter Lowe's` list.

**Comment by okiehsch** [comment] 2019-02-28 23:12
Quora I can't reproduce is this not alread fixed by https://github.com/uBlockOrigin/uAssets/commit/3a05afbb919c0fc0139af665212d83d51a2929de ?

**Comment by okiehsch** [comment] 2019-02-28 23:18
I will not add the `pixiv.net` filter, I consider it to be of use to site visitors, so they can see what they have to do to get an unblurred picture.

**Comment by okiehsch** [comment] 2019-02-28 23:21
Fixed `addons.opera.com` with
`addons.opera.com##+js(setTimeout-defuser.js, showOverlay)`

**Comment by okiehsch** [comment] 2019-02-28 23:27
@adranger I can reproduce the instagram issue and thoe proposed filter works onmy end.

**Comment by DandelionSprout** [comment] 2019-03-01 00:18
>Make sure to also enable the `Adguard Annoyances` list. uBlock Origin only adds rules that can't or won't be fixed by the third-party options offered
>To be precise, the uBO-annoyance list is meant for issues that can't be fixed in `Adguard Annoyances` and `Fanboy's Annoyance` list.

Ah. That explains a few things. I usually don't use "Annoyances*-themed lists fulltime, so in fact I didn't even begin to use *uBlock Filters - Annoyances* until yesterday, as I felt I had to test my entries at the very least against the list(s) that I was submitting them to.

>I will not add the `pixiv.net` filter, I consider it to be of use to site visitors, so they can see what they have to do to get an unblurred picture.

Fair point.

I'll try to double-check the `cdn.onesignal.com` and Quora entries within an hour; I just need to eat a bit of supper and check some E-mail-related stuff first.

**Comment by DandelionSprout** [comment] 2019-03-01 01:08
`cdn.onesignal.com` works splendidly on my end, and you have my gratitude for telling about it to me.

Somewhere down the line, while I was looking up and testing the OP's entries for 4 hours, I forgot to mention that the Quora entries applied to **phone browsers**. 😅 You have my apologies for this mistake if it's needed, and I'll update the OP list accordingly.

**Comment by DandelionSprout** [comment] 2019-03-01 01:34
Here's how the Quora mobile signup banner should look like when its triggered: 
![image](https://user-images.githubusercontent.com/22780683/53610243-8312f100-3bca-11e9-97f3-0ebc2d184fa7.png)

**Comment by DandelionSprout** [comment] 2019-03-01 01:41
>You should've checked these entries one by one before posting them here.

I tested all entries on a by-site basis (although not by-entry, except on Facebook, Twitter Mobile, and Pinterest), as I also needed to try to remember which things the entries were blocking, which I had not previously written down in my own lists.

**Comment by okiehsch** [comment] 2019-03-01 01:57
````
!! Removes the blur from the images
nijie.info##.ngtag.mozamoza:style(-webkit-filter: none !important)
````
That filter does not work on my end.

**Comment by okiehsch** [comment] 2019-03-01 02:09
````
! https://www.theclever.com
!! Removes a large (and on my end invisible) banner that prevents clicking on most of the page
theclever.com###overlay_search
````

I can't reproduce.

**Comment by DandelionSprout** [comment] 2019-03-01 02:18
>That filter does not work on my end.

Strange, because I am very confident that it works on my end. Does `nijie.info##img:style(filter: none !important)` work any better?

>I can't reproduce.

Double-checking it, it seems to only be triggered if the windows size is above a certain height that is around 1600px. Here's when the window is 1700px tall: 
![image](https://user-images.githubusercontent.com/22780683/53611951-9d4fcd80-3bd0-11e9-848b-f9985c64e44d.png)

**Comment by okiehsch** [comment] 2019-03-01 02:30
> Strange, because I am very confident that it works on my end. Does `nijie.info##img:style(filter: none !important)` work any better for you?

No.
![image](https://user-images.githubusercontent.com/16838044/53612317-274c6600-3bd2-11e9-8b8a-8a0588e286f0.png)


> Double-checking it, it seems to only be triggered if the window's size is above a certain height that is around 1600px.

I can reproduce and will add your filter.

**Comment by DandelionSprout** [comment] 2019-03-01 02:33
>No.

In that case I'm stumped, because both of those entries work on my end: ![image](https://user-images.githubusercontent.com/22780683/53612456-b9546e80-3bd2-11e9-80e8-8979fe683feb.png)

**Comment by okiehsch** [comment] 2019-03-01 02:35
Let's wait and see if others can reproduce maybe it is a quirk with my setup,

**Comment by adranger** [comment] 2019-03-01 03:30
Please add `NSFW` when you're going to post porn cartoons in the middle of threads.

**Comment by DandelionSprout** [comment] 2019-03-01 03:31
Okay, sure thing, I guess.

**Comment by okiehsch** [comment] 2019-03-01 23:18
> ! `https://seekingalpha.com/article/3975358-dhx-medias-dhxm-ceo-dana-landry-q3-2016-results-earnings-call-transcript?page=2` (When not logged in)
!! Removes an uncloseable login prompt when going beyond page 2 on certain shareholder meeting transcripts
seekingalpha.com##.in.fade.modal
seekingalpha.com##.modal-dialog
seekingalpha.com##.p:style(display: block !important)
seekingalpha.com##.blured:style(opacity: 1.0 !important)

A simpler fix in my end is 
`seekingalpha.com##+js(setTimeout-defuser.js, Widgets.Popup, 5000)`
Does this also work for you?

**Comment by DandelionSprout** [comment] 2019-03-01 23:22
Unfortunately not.

**Comment by DandelionSprout** [comment] 2019-03-01 23:24
I also forgot to write in the OP that my entries technically doesn't allow going beyond page 2 either, which I probably should've realised before, but it does at least show the entire article.

**Comment by okiehsch** [comment] 2019-03-01 23:36
Weird, looking at the source on my end it it should work.
Does
`seekingalpha.com##+js(setTimeout-defuser.js, Widgets.Popup)`
work?
If it does not I will simply add your filters.

**Comment by DandelionSprout** [comment] 2019-03-01 23:40
I admit to be feeling a little confused right now. How exactly would `seekingalpha.com##+js(setTimeout-defuser.js, Widgets.Popup)` or `seekingalpha.com##+js(setTimeout-defuser.js, Widgets.Popup, 5000)` make the rest of the article readable, let alone making the *Next* and *Single page view* buttons on that page lead to their intended target pages?

**Comment by DandelionSprout** [comment] 2019-03-01 23:43
Okay, so I did originally mess up in the OP: The problem wasn't only about the banner, but also about making the entire articles readable, if that helps resolve any potential confusion.

**Comment by okiehsch** [comment] 2019-03-01 23:48
You misunderstand, the filter
`seekingalpha.com##+js(setTimeout-defuser.js, Widgets.Popup)`
does not make the Next and Single page view buttons on that page lead to their intended target pages.

What it does, atleast on my end, is preventing the site at
````
https://seekingalpha.com/article/3975358-dhx-medias-dhxm-ceo-dana-landry-q3-2016-results-earnings-call-transcript?page=2
````
from opening the `Widgets.Popup`.

![image](https://user-images.githubusercontent.com/16838044/53672826-8b2f6700-3c84-11e9-8224-123552989ee4.png)

If I add the filter
![image](https://user-images.githubusercontent.com/16838044/53672888-d184c600-3c84-11e9-82bb-e5c283d691e4.png)

**Comment by DandelionSprout** [comment] 2019-03-01 23:51
Ah, thanks for the clarification.

I understand those screencaps as such that it prevents the banner from showing up when opening the page. My suggested entries take care of removing the banner under all circumstances, as well as making the articles fully readable. So I'd recommend using my entries instead, if you want to use them.

**Comment by okiehsch** [comment] 2019-03-01 23:54
> as well as making the articles fully readable.

My bad, I missed that rather noticable difference somehow.

**Comment by okiehsch** [comment] 2019-03-02 00:00
A problem with your filters
````
seekingalpha.com##.in.fade.modal
seekingalpha.com##.modal-dialog
seekingalpha.com##.p:style(display: block !important)
seekingalpha.com##.blured:style(opacity: 1.0 !important)
````
is that I "lose" the scroll bar and hence the abilty to scroll after 5-10 seconds.

**Comment by DandelionSprout** [comment] 2019-03-02 00:13
Despite testing for 10min, I was unable to replicate your scrolling problems. I also struggled to find any problematic element CSS values on that page, so unless `seekingalpha.com##.modal-open:style(overflow: visible !important)` works for you, then I'm stumped.

**Comment by DandelionSprout** [comment] 2019-03-02 00:14
Oh. Looks like you found a fix for it in the meantime, which I only saw now. 🎉

**Comment by okiehsch** [comment] 2019-03-02 00:15
Yes, sorry I  was busy with some different issue and forgot to mention that it works on my end if I add
`seekingalpha.com##body:style(overflow: auto !important;)`
I could reproduce the problem with Chromium and Firefox.

**Closed** 2019-03-02 09:57 UTC

**Comment by okiehsch** [comment] 2019-03-02 09:58
@DandelionSprout Thank you.

**Comment by DandelionSprout** [comment] 2019-03-02 12:50
Just to round this off, are there any norms and customs I should know about if I were to want to submit 10~20 more entries to uAssets at some or another future point in time?

**Comment by DandelionSprout** [comment] 2019-03-02 13:17
Oh, and I also realised only *now* why the Nijie entry didn't work: The adblocker-syntax entries I had wrote for it, depended on [a particular entry](https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/DandelionSproutRedirectorList.json#L498) I had written for another extension called Redirector, which took care of replacing the page's intended very-low-quality image with the original-quality image.

I probably overworked myself during the 4 hours I spent on Friday morning trying to find example pages and entry explanations for all the entries in the OP, so there was no small amount of mistakes that slipped through in the process, is seems...

**Comment by okiehsch** [comment] 2019-03-02 21:45
>  are there any norms and customs I should know about if I were to want to submit 10~20 more entries to uAssets at some or another future point in time?

No.

> I probably overworked myself during the 4 hours I spent on Friday morning trying to find example pages and entry explanations for all the entries in the OP

You can open issues for one site at a time that way you don't have to find examples for dozens of pages in one go, there is no need to rush.

**Comment by yourduskquibbles** [comment] 2019-03-04 17:36
Question for @okiehsch @mapx- and maybe @gorhill 

I noticed a number of modal / overlay and overflow (site scrollbar) re-enabling filters from @DandelionSprout were integrated into uAssets Annoyances list in response to this issue so I am wondering if it make sense for me to take the time and submit filters from the [Web Annoyances modal filter sublist](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/modal_filters.txt) for inclusion into uAssets as well? Are these types of filters something that are in scope for uAssets Annoyances list even if not all require extended syntax? 

For example see the following examples of the `##.modal` class of filters that are used on multiple domains that I have in my list below (I have combined domains & filters where appropriate for each site) 

```
artsy.net,bestvpn.com,change.org,cryptocompare.com,discordbots.org,economist.com,franchisehelp.com,galoremag.com,goodreads.com,justanswer.co.uk,justanswer.com,konbini.com,legalist.com,nytimes.com,seattletimes.com,thehackernews.com,thenation.com,vogue.com##.modal
abcstores.com,activejunky.com,betterhelp.com,blooom.com,bourbonblog.com,callername.com,carefirst.com,cigarbid.com,coronacigar.com,dccouncil.us,dividend.com,everydaydishes.com,fee.org,fermatslibrary.com,gardenweb.com,govtrack.us,hooktube.com,infantino.com,interestingengineering.com,law360.com,lowes.com,michaels.com,mississippi.gov,movieshype.com,otakustream.tv,paper.li,patch.com,pbs.org,photobucket.com,reviewmeta.com,ripple.com,sapling.com,streamingonline.desi,techwalla.com,washingtontimes.com##.modal-backdrop
alexa.com,amctheatres.com,atlasobscura.com,bestbuy.com,brit.co,businessoffashion.com,citizensforethics.org,climatechangenews.com,deskbright.com,digg.com,everycaller.com,getweeklyupdate.com,goodrx.com,greatnonprofits.org,huckberry.com,kraftrecipes.com,mnn.com,movieflix.to,myajc.com,nordvpn.com,searchenginewatch.com,seekingalpha.com,thisiswhyimbroke.com,underarmour.com,washingtonpost.com,weeklystandard.com##.modal, .modal-backdrop
atimes.com,ifixit.com,mic.com,narrative.ly,pedestrian.tv,timesofisrael.com##.modal-overlay
```

The above filters alone don't require extended syntax but in many cases, they need to be paired with a companion filter that uses extended syntax to re-enable site scrolling function with one of the following two filters 

```
99bitcoins.com,africacheck.org,alexa.com,amctheatres.com,betterhelp.com,breitbart.com,brioni.com,buckscountycouriertimes.com,burlingtoncountytimes.com,businessinsider.com,change.org,china-underground.com,chron.com,cigarinspector.com,citylab.com,coinstaker.com,dewalt.com,discovermagazine.com,eastbaytimes.com,ew.com,fair.org,filmcomment.com,forzieri.com,geniuskitchen.com,hackernoon.com,hindustantimes.com,iphonelife.com,jcutrer.com,kerbalspaceprogram.com,leaf.tv,lightstalking.com,mamapedia.com,medium.com,mongodb.com,motor-talk.de,newsbtc.com,newseum.org,otakustream.tv,paper.li,publicdomainreview.org,rankedboost.com,readfrontier.org,revisionisthistory.com,searchenginewatch.com,seekingalpha.com,shopstyle.com,slamonline.com,spiceworks.com,syfy.com,techwalla.com,thedailybeast.com,thedailybell.com,theintell.com,themefoxx.com,thespoon.tech,toptal.com,trefiel.com,usatoday.com,washingtonmonthly.com,watchpro.com,williams-sonoma.com,yodalearning.com##html:style(overflow-x: hidden !important; overflow-y: scroll !important;)
aboutamazon.com,activejunky.com,alternet.org,atlasobscura.com,avclub.com,becauseofthemwecan.com,bestbuy.com,blooom.com,bostonglobe.com,breakingdefense.com,camelcamelcamel.com,carefirst.com,citizensforethics.org,cjr.org,cnet.com,coronacigar.com,couponcabin.com,cryptodisrupt.com,dailydot.com,dariusforoux.com,daveramsey.com,defenseone.com,denverpost.com,deskbright.com,digg.com,dispatch.com,ehow.com,ello.co,fatherly.com,fermatslibrary.com,flair.co,foreignpolicy.com,freedomnode.com,gazettextra.com,getweeklyupdate.com,golfchannel.com,goodreads.com,goodrx.com,greatnonprofits.org,healthline.com,ifixit.com,indiegogo.com,infantino.com,interestingengineering.com,jacobinmag.com,lareviewofbooks.org,littlepassports.com,mercurynews.com,metacafe.com,myajc.com,nextgov.com,nikkei.com,nytimes.com,patch.com,pbs.org,reviewjournal.com,reviewmeta.com,sephora.com,slickdeals.net,smarteranalyst.com,sophos.com,splinternews.com,statnews.com,summerinfant.com,thebaffler.com,theladders.com,trycosmo.com,tucson.com,underarmour.com,usnews.com,utah.com,utilitydive.com,venturebeat.com,victoriassecret.com,wagwalking.com,wisegeek.com##body:style(overflow-x: hidden !important; overflow-y: scroll !important;)
```
Please note: the companion filters above don't only apply to the `##.modal` example domains which is why you will see domains that are not in the 4 examples above however if you search a domain you should find another filter that is included in my modal list that requires the companion filter scrolling fix. 

Also of note, whether the overflow should be applied to ##body or ##html depends on site-by-site case otherwise you can end up with multiple scroll bars if it is applied to the wrong element.

The only hiccup I see with merging my list into uAssets is that my list contains a lot more entries than @DandelionSprout submitted and I don't keep the same note style as uAssets or put inline comments with my list so wondering what your thoughts are on that. **Is it better to just keep maintaining my own modal list or is it worth the time/energy to try and integrate into uAssets?**

If it were to be integrated, would you want me to start opening issues for each site and submit pull request and or suggested filter? I have noticed with modals there is a lot of reuse of the same syntax between sites so opening a new issue seems like it may be a lot of work/clutter the issue tracker.

**Comment by okiehsch** [comment] 2019-03-04 22:05
> The above filters alone don't require extended syntax but in many cases, they need to be paired with what I call a companion filter that uses uBO extended syntax to re-enable site scrolling function with one of the following two filters

If the filters need to paired with a `:style` filter to reenabe scrolling they can be added to `uBO-annoyances`.
Looking through your list  - `https://github.com/yourduskquibbles/webannoyances` - I would not be opposed to add it to the stock annoyances section, because you actually use extended syntax extensively in contrast to many other lists.

**Comment by okiehsch** [comment] 2019-03-04 23:12
@yourduskquibbles would you be interested to get commit rights to `uAsset`?
You could then add filters to `uBO-annoyances` as you see fit.

**Comment by Hrxn** [comment] 2019-03-05 00:47
I usually agree with regard to those stuff on the web, so adding more filters into `uBO-annoyances` (via commit rights) is something I tend to get behind with, but shouldn't we try to figure out what the established consensus would look like beforehand?

Just for example: scrolling/floating header bars, GitHub has those as well on issue pages, like right on this one here. In this case, I'd see them as useful and not annoying (Status, Title, Opener etc.).
And I'm also not so sure about social buttons. I don't particularly like them and do not use them at all, and they are not necessary even for users of one of those specific social networks etc., but other users might see this differently.

**Comment by okiehsch** [comment] 2019-03-05 01:03
This issue and **yourduskquibbles** comment was mainly about login prompts via modal/overlays and overflows and I think most users would agree that they are annoying.
I am not suggesting that all `https://github.com/yourduskquibbles/webannoyances` filters should be added to `uBO-annoyances`.

**Comment by Hrxn** [comment] 2019-03-05 01:12
Ah, yes, that makes a tad bit more sense. And please don't mistake my comment as speaking in opposition to the proposal, that was not my intention. More of a casual reminder to be wary of overzealous filter lists, to not do any harm by overblocking.

**Comment by DandelionSprout** [comment] 2019-03-05 01:20
You have a point in my eyes, Hrxn. I generally avoid using Fanboy's and AdGuard's annoyances lists because they can be too broadly covering, leading to them removing elements that a fair few people may actually want to use; so I made this issue thread for `uBlock Filters - Annoyances` because the list seemed small and narrow enough that it wouldn't cause such problems to occur (as well due to the ease of making issues/pulls to uAssets, and that I felt that many novice uBO users would try to get the "true" uBO experience by activating all `uBlock Filters` lists).

**Comment by DandelionSprout** [comment] 2019-03-05 01:30
A quick look at yourduskquibbles' list, without having tested any of his list's entries yet, tells me that it blocks all types of modals and overlays in general, incl. ones for newsletters, while I've tended to focus more on ones that are uncloseable.

He seems like a talented filter writer to me, but I feel that example pages or images for some or most of the entries could've given us clarity in which kinds of modals that his list is blocking, just to feel certain about it. Unless of course the uAssets core team were to want to block all modal overlays, in which case you can forget I wrote this comment.

**Comment by okiehsch** [comment] 2019-03-05 01:40
>  I feel that example pages or images for some or most of the entries could've given us clarity in which kinds of modals that his list's entries are blocking, just to feel certain about it.

Every filter added to `uAssets` has a reference to an issue or a short explanation of why it was added, that won't change.

**Comment by yourduskquibbles** [comment] 2019-03-05 03:14
> 
> 
> @yourduskquibbles would you be interested to get commit rights to `uAsset`?
> You could then add filters to `uBO-annoyances` as you see fit.

Sure you could, but before I were to add anything I would want to confirm what is in scope for the list so I don't overbloat the uAssets list or commit out of project scope items.

Just for clarity, I am not proposing merging any filters from my other sublists as I know those are mostly out of scope. I am only suggesting portions of the modal sublist, specifically filters for sites with modal splash elements  that take over the **entire page** and/or remove scrolling. In many cases these are subscription/signup nags or newsletter/coupon enrollment but they can also be used to hide content.

>
>Every filter added to uAssets has a reference to an issue or a short explanation of why it was added, that won't change.
>

That's fine with me but also a pretty big undertaking to document all the suggested filters that could be added so would prefer to have a solid OK before proceeding. Luckily, most of the modal screen overlays are usually relatively easy to trigger by visiting a site with no previously set site cookies and scrolling up/down. 


>
>Looking through your list - https://github.com/yourduskquibbles/webannoyances - I would not be opposed to add it to the stock annoyances section, because you actually use extended syntax extensively in contrast to many other lists.
>

This could be an alternative to adding just the modal filters to uAssets but I know gorhill is sensitive to adding new lists. The potentially confusing problem for users is that with my CSS Style Filters list I change site design (for the better, I think) but users wouldn't necessarily know that is the main purpose of the list and one man's treasure could be another man's trash.

**Comment by okiehsch** [comment] 2019-03-05 03:23
> sure you could, but before I were to add anything I would want to confirm what is in scope for the list so I don't overbloat the uAssets list or commit out of project scope items.

I will send you an invite and if you accept you will have access to [team discussions](https://help.github.com/en/articles/about-team-discussions), so if yo are not sure about adding a filter we can discuss it before you commit.

> This could be an alternative to adding just the modal filters to uAssets but I know gorhill is sensitive to adding new lists.

It was actually gorhill who first suggested giving you commit rights as an alternative to add a new list. ;)

**Comment by yourduskquibbles** [comment] 2019-03-05 03:30
Just as an example of the type of modals I would typically remove in my modals list. 

This is from a site I just encountered today `https://thunderbolttechnology.net/`  

![thunderbolt](https://user-images.githubusercontent.com/22258847/53778956-84933080-3ecc-11e9-8905-9b31b65de8ef.png)


Would this this be considered in-scope for uAssets to remove? It presents what I think is pretty useless information and splashes the entire page and adds a background overlay, but doesn't take away the scroll bar. I could see as being an edge case for removal but then again it doesn't need an overflow fix and maybe someone thinks that information is useful and something the person landing on the page wouldn't want to have blocked?


The modal element can be removed with the following two filters, and will be added to my modal list but no extended syntax is needed.

`thunderbolttechnology.net###lightbox, #lightbox2-overlay`

**Comment by okiehsch** [comment] 2019-03-05 03:41
> but no extended syntax is needed.

For the annoyance list we never have been very strict about the use of extended syntax. In fact this issue has a handful of fixes that don't use extended syntax.

>  I could see as being an edge case for removal but then again it doesn't need an overflow fix and maybe someone thinks that information is useful and something the person landing on the page wouldn't want to have blocked?

You will always find someone who finds such a thing annoying and someone who doesn't.
I personally find full page overlays annoying, so I would consider your example a valid issue but others may disagree,

**Comment by krystian3w** [comment] 2019-03-05 19:14
https://github.com/DandelionSprout/adfilt/commit/0687840523d6b6306090e0cc8abc42d3850f4546 - report by new issue or to rare show it to block in uBO Annoyance?

**Comment by mapx-** [comment] 2019-03-05 21:10
@DandelionSprout 
bad filter for pinterest (I commented it for now but it's kind of ugly and easily generating page breakage ):
`pinterest.*##div:nth-of-type(2) > div > div > div > .Hsu.iyn.zI7 > div.Hsu.iyn.zI7:nth-of-type(2) > div`

see https://github.com/uBlockOrigin/uAssets/issues/2044#issuecomment-469846596

**Comment by mapx-** [comment] 2019-04-03 07:47
@DandelionSprout  see
https://www.reddit.com/r/uBlockOrigin/comments/b8sg46/the_compose_popup_on_mobiletwittercom_is_blocked/

bad filter
`mobile.twitter.com##div[data-focusable="true"] > div > div > div:has(div > div > div > div > div > div > div > div > div > div > div > div[role="button"] > div)`

**Comment by mapx-** [comment] 2019-04-03 07:50
removed the filters for mobile.twitter
https://github.com/uBlockOrigin/uAssets/commit/e160fd22eb9db0bbc597b06444fec1e2997082bd

**Comment by DandelionSprout** [comment] 2019-04-03 08:32
Twitter Mobile is among the two hardest websites in the world to write entries (alongside Pinterest), so I suppose that the chances of a bad filter was pretty big. I'll try to think of a better entry when I have time.

**Comment by mapx-** [comment] 2019-05-23 15:38
`deezer`, breaking edit playlist
https://github.com/uBlockOrigin/uAssets/issues/5649

**Comment by mapx-** [comment] 2019-08-05 16:50
`seekingalpha` broken on signing in

**Comment by mapx-** [comment] 2019-08-05 16:53
https://github.com/uBlockOrigin/uAssets/commit/ca128e9f5d23200c8957113ebafd78831f21be30

**Comment by yourduskquibbles** [comment] 2019-10-25 12:57
`pinterest.com` scroll bar broken when scrolling down on example page `https://www.pinterest.com/search/pins/?q=Halloween%20Costumes&rs=typed` after the blocked login to continue modal is loaded.

**Comment by krystian3w** [comment] 2021-01-23 15:24
Breakage: 

> https://github.com/uBlockOrigin/uAssets/blob/bfef3606af9191b804810d7db64cda9d9e14ccc2/filters/annoyances.txt#L1602

see https://github.com/uBlockOrigin/uAssets/issues/8500
