### ISSUE TITLE
shop.app: breakage

### ISSUE THREAD

**Issue by benklop** [uBlockOrigin/uAssets#18331] opened 2023-05-31 20:00 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shop.app/checkout/57549062178/c/181fd089e391db2d291204c68a092f37/shoppay?_ga=undefined&redirect_source=checkout_automatic_redirect&tracking_unique=ba5aabe8-2127-4ca2-97f6-fe0cb2d8a4d0&tracking_visit=e5c63eb2-2883-45de-9575-046bbf850856`

### Category

breakage

### Description

No matter what address is entered it is shown as not a valid address, and shipping cannot be selected. This is a shopify site, and I think blocking of a fewe shopify URLs is likely to blame.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94550
 cosmetic: 39045
 scriptlet: 17661
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66654-49, 1d.14h.53m
  easyprivacy: 31738-52, 1d.3h.1m
  plowe-0: 3735-945, 7d.4h.23m
  ublock-abuse: 69-0, 3h.10m
  ublock-badware: 7117-130, 1d.14h.20m
  ublock-filters: 33459-106, 1d.14h.3m
  ublock-privacy: 380-74, 3h.9m
  ublock-quick-fixes: 184-20, 5h.11m
  ublock-unbreak: 2020-34, 1d.13h.45m
  urlhaus-1: 7463-0, 5h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 257 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel: 
 blocked: 76
 network: 
  shop.app: 6
  bugsnag.com: 1
  otsurplus.com: 1
  shopifysvc.com: 68
```
</details>

**Comment by mapx-** [comment] 2023-05-31 20:06
clicking the url above redirects me to 
`https://otsurplus.com/`

Provide all the steps to reproduce your issue, what to click etc
Is it an account required ?

**Comment by mapx-** [comment] 2023-05-31 20:14
Which is the start address ?

**Comment by benklop** [comment] 2023-05-31 20:15
Correction, I do see now i was logged in with a 'shop' account, which is free, but makes it default to using shopify's payment system instead of providing the option to use paypal / gpay / others

**Comment by benklop** [comment] 2023-05-31 20:16
https://otsurplus.com/ is the correct start address. I beleive this would be an issue for other shopify shops too.

**Comment by benklop** [comment] 2023-05-31 20:18
Just want to be sure that small businesses don't pay the price for using an adblocker by having their ability to make sales impacted

**Comment by mapx-** [comment] 2023-05-31 20:20
I typed a random address and a suggestion appeared

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/b2676497-1e2b-4073-91c2-04ccc19b038e)

**Comment by mapx-** [comment] 2023-05-31 20:24
No error, but as I said I'm still on otsurplus  page.

**Comment by benklop** [comment] 2023-05-31 20:24
![Monosnap Checkout - onethiefsurplus 2023-05-31 13-18-54](https://github.com/uBlockOrigin/uAssets/assets/2729824/06df7af0-053a-448d-8875-e72a861489ca)

**Comment by mapx-** [comment] 2023-05-31 20:26
You are on another page, maybe because you are logged in with some provider / account.
If you do not explain exactly what to do I cannot help you.

**Comment by benklop** [comment] 2023-05-31 20:30
i initially thought i did not have an account, but i was incorrect.

**Comment by mapx-** [comment] 2023-05-31 20:33
Nothing to do: `Enter your mobile number to sign up.`

If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by benklop** [comment] 2023-05-31 20:34
yes

**Comment by mapx-** [comment] 2023-05-31 20:34
send it here: `axis.trivia@gmail.com`

**Comment by benklop** [comment] 2023-05-31 20:56
sorry for the difficulty getting this the testing steps for this. It appears to differ depending on several factors.

**Comment by mapx-** [comment] 2023-05-31 21:01
well, if you didn't follow all the steps I forwarded you, just start again.

**Comment by mapx-** [comment] 2023-05-31 21:14
I'll close it for now. Just comment here if you find the issue's reason.

**Closed by mapx-** 2023-05-31 21:14 UTC
