### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by mey223** [uBlockOrigin/uAssets#14541] opened 2022-08-26 19:12 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

No longer works. Ads show on all twitch channels.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 83005
  cosmetic: 43599
  scriptlet: 17719
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 46-1, never
    easylist: 68048-51, 1h.9m
    easyprivacy: 27425-126, 1h.8m
    plowe-0: 3633-776, 1h.7m
    ublock-abuse: 76-0, 1h.5m
    ublock-badware: 4162-96, 1h.3m
    ublock-filters: 32480-121, 1h.2m
    ublock-privacy: 241-3, 1h.1m
    ublock-quick-fixes: 394-5, 1h
    ublock-unbreak: 1839-41, 59m
    urlhaus-1: 7355-0, 58m
filterset (user): [array of 64 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 294 ms
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    doubleverify.com: 1
    google-analytics.com: 1
    imrworldwide.com: 5
    scorecardresearch.com: 5
    sentry.io: 2
    serving-sys.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-08-26 19:14
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by okiehsch** 2022-08-26 19:14 UTC

**Comment by MasterKia** [comment] 2022-08-27 03:27
@okiehsch The twitch-videoad filter is disabled.
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L4952

**Comment by okiehsch** [comment] 2022-08-27 06:04
And you can reproduce the ads?

**Comment by MasterKia** [comment] 2022-08-27 07:43
I haven't checked but I mean there is nothing (no filters) left to **stop** the ads unless twitch has changed and the scriptlet is no longer needed.

**Comment by okiehsch** [comment] 2022-08-27 07:49
I don't see any ads on my end.

**Comment by mey223** [comment] 2022-08-28 04:09
The ads are always shown now, at the beginning of the stream. Lots of
users' latest reviews reporting it no longer work as Twitch apparently
changed how the initial ads appear before accessing the live stream.

**Comment by MasterKia** [comment] 2022-08-28 06:08
@mey223 Add this to "My filters" and test again:
`twitch.tv##+js(twitch-videoad)`

**Comment by mey223** [comment] 2022-08-28 14:49
Yes I've already had twitch.tv##+js(twitch-videoad)
<http://twitch.tv/#%23+js(twitch-videoad)> in my filters. That does not
resolve the issue that all users are having unfortunately.

**Comment by mey223** [comment] 2022-08-28 14:52
Two pictures attached. One where its attempting to block pre-roll ads but
its just a black screen that never goes away.
The other picture is an actual ad. Again, all filters are in place.

**Comment by MasterKia** [comment] 2022-08-28 14:57
No pictures came.

**Comment by mey223** [comment] 2022-08-28 15:01
Re-attached in a zip file. Also included the popular blue screen ad
that Twitch now has for pre-roll when using the ad blocker.

**Comment by MasterKia** [comment] 2022-08-28 15:02
Please send it using the GitHub interface:
https://github.com/uBlockOrigin/uAssets/issues/14541

**Comment by mey223** [comment] 2022-08-28 15:08
Zip file attached of 3 examples of ads shown or attempting to block ads (black screen) with all filters applied
[ad_screenshots.zip](https://github.com/uBlockOrigin/uAssets/files/9439914/ad_screenshots.zip)
.
