### ISSUE TITLE
now.gg: detection

### ISSUE THREAD

**Issue by thamidrayhan943** [uBlockOrigin/uAssets#17963] opened 2023-05-06 16:41 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://now.gg/`
 

### Category

detection

### Description

uBlock is not working on now.gg
I have uBlock Origin installed on my Chromebook, and when I try to play any games in now.gg I get an error message. I tried turning it off and it worked, but then when I turned it back on the same error message appeared. I tried multiple times and the same thing happens. 

some extra information about now.gg, it's a cloud gaming platform that allows users to play mobile games on any device,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93994
 cosmetic: 40411
 scriptlet: 17476
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66942-46, 30m
  easyprivacy: 32241-46, 30m
  plowe-0: 3743-936, 30m
  ublock-abuse: 70-0, 30m
  ublock-badware: 7142-129, 30m
  ublock-filters: 33231-81, 30m
  ublock-privacy: 394-74, 30m
  ublock-quick-fixes: 229-20, 30m
  ublock-unbreak: 2010-36, 30m
  urlhaus-1: 7400-1, 30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4618 ms
 maxAssetCacheWait: 131 ms
popupPanel: 
 blocked: 15
 network: 
  now.gg: 1
  bugsnag.com: 3
  dn0qt3r0xannq.cloudfront.net: 2
  google.com: 6
  googletagmanager.com: 1
  googletagservices.com: 1
  quantserve.com: 1
```
</details>

**Comment by krystian3w** [comment] 2023-05-06 17:26
https://github.com/uBlockOrigin/uAssets/labels/account%20required or can be skipped by demo panel?

**Comment by krystian3w** [comment] 2023-05-06 17:28
Also you can try open page in Firefox Mobile form APK (ARM CPU) or GNU/Linux from "flatpak" (x86-x64 CPU).

**Comment by gorhill** [comment] 2023-05-06 22:13
Unable to reproduce any issue.

> - [x] I did not answer truthfully to ALL the above checkpoints.

I suggest you go through all the prerequisite steps and this time check and answer truthfully -- these are there to ensure that the issue is not caused by something else than uBO.

**Comment by krystian3w** [comment] 2023-05-06 23:07
Without login test is pointless IMO.

**Comment by gorhill** [comment] 2023-05-06 23:12
I could reproduce yesterday, <https://github.com/uBlockOrigin/uAssets/issues/17953>, this was fixed in EasyPrivacy less than a day ago.

**Comment by gorhill** [comment] 2023-05-06 23:13
Closing as duplicate of <https://github.com/uBlockOrigin/uAssets/issues/17797>.

**Closed by gorhill** 2023-05-06 23:13 UTC
Labels: unable to reproduce
