### ISSUE TITLE
Adblock detected

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#7596] opened 2020-06-24 19:54 UTC
Hello, good afternoon.

First of all **excuse my English level**, I am with the help of the google translator. 

I hope I can write the message correctly, **I don't understand well** the explanatory notes indicated in the text box. **I don't remember how to write an adult url** so that when you click on it you don't enter it. I would appreciate it if you could tell me so that I don't fall into the error next time.

### URL(s) where the issue occurs

```
https://vidcorn.tv/
https://tutorialesenlinea.es/
https://milapercia.com/
https://www.thenekodark.com/
http://www.artesacro.org/
https://brazzers3x.org/
```

### Describe the issue
[Detection anti adblock.]

`https://vidcorn.tv/`
When you click on the Register button, the notice appears.

`https://tutorialesenlinea.es`

Example -->
`https://tutorialesenlinea.es/1852-como-usar-rkill-para-terminar-programas-sospechosos.html`

It appears both on the home page and when you open any post. The warning appears shortly after you are browsing, you have to wait a few seconds.

`https://milapercia.com/`

Example --> 
`https://milapercia.com/glary-utilities-pro-5-125-0-150-activado`

It appears both on the home page and when you open any post. Also when you click on the download button.

`https://www.thenekodark.com`

Example --> 
`https://www.thenekodark.com/revo-uninstaller-pro-serial-elimina-contenido-no-deseado/`

When I click on Download (at the bottom of the page) a tab opens to continue the download process, which displays the Adblocker warning detected.
The option to Disable or Disable for that page does not work, it has to be disabled completely from the complements page.

`http://www.artesacro.org/`

Example -->
`http://www.artesacro.org/Noticia.asp?idreg=33246`

The notice appears indistinctly when the home page is opened like any other news item.

`https://brazzers3x.org`
The warning appears directly on opening, you have to wait a little. The warning still appears even if you disable uBlock.]

### Screenshot(s)
[See note (last section)]

### Versions

- Browser/version: [Firefox Browser 64-Bit v77.0.1]
- uBlock Origin version: [v1.27.10]

### Settings

https://user-images.githubusercontent.com/44229110/85620799-95892780-b664-11ea-9db1-799d1441dd44.PNG

https://user-images.githubusercontent.com/44229110/85620912-bc475e00-b664-11ea-9037-34b25abc924f.PNG

https://user-images.githubusercontent.com/44229110/85620935-c5382f80-b664-11ea-9752-092cc5234913.PNG

**Comment by llacb47** [comment] 2020-06-24 20:16
Why do you have easylist and easyprivacy disabled?

**Comment by mapx-** [comment] 2020-06-24 20:44
@llacb47 he added `fanboy+easylist-merged`

**Comment by mapx-** [comment] 2020-06-25 06:36
for vidcorn try:
`vidcorn.tv#@#+js(acis, document.createElement, 'meta')`

I cannot reproduce any issue on `thenekodark` => what do you click, which is the landing page ?

**Comment by Jose1971AB** [comment] 2020-06-25 08:02
@llacb47 

> Why do you have easylist and easyprivacy disabled?

Hello @llacb47 good morning.

I have them disabled because they are included in the Fanboy+Easylist-Merged Complete List filter

![Fanboy's Complete List](https://user-images.githubusercontent.com/44229110/85680678-cf8d1480-b6ca-11ea-89a3-0b0fc925a378.jpg)

**Comment by Jose1971AB** [comment] 2020-06-25 09:08
Hello @mapx- good morning.... **thank you very much for answering**

> 
> 
> for `vidcorn` try:
> `vidcorn.tv#@#+js(acis, document.createElement, 'meta')`
> 
> I cannot reproduce any issue on `thenekodark` => what do you click, which is the landing page ?

**1) Excuse me, but** `vidcorn.tv#@#+js(acis, document.createElement, 'meta')` **Do I have to add it somewhere in uBlock?... maybe in the section of My filters?...** excuse my ignorance please

**2) Regarding [https://www.thenekodark.com] what happens is the following...**

[https://www.thenekodark.com] is a program download page. If I enter any section and click on the Download button to download a program a tab opens to continue the download process where it shows the Adblocker warning detected.

Also, if I disable uBlock for that site or it generally doesn't work, I have to disable uBlock from the Firefox options add-on page

**Please look at this...**
![1](https://user-images.githubusercontent.com/44229110/85688775-5a254200-b6d2-11ea-8a6c-1e257e482ba3.jpg)

![2](https://user-images.githubusercontent.com/44229110/85688833-6ad5b800-b6d2-11ea-943c-58b65ae7bdf9.png)

By the way... are the other pages already fixed?...

Greetings, my friend.

**Comment by mapx-** [comment] 2020-06-25 09:15
1. yes, add it to "my filters" and test again
2. no such anti adb warning here: `urlpay.net` => you should reset uBO to default (don't add any other custom list), then click `Purge all caches` , then click `Update now` => test again 
- use the normal easylist, easyprivacy, no advantage using fanboy-easylist merged
3. As you can see all the others were fixed so after forcing an update you can test all them

**Comment by Jose1971AB** [comment] 2020-06-25 12:03
Hello @mapx- 

I would appreciate it if you would give me a little time to do the tests, I am not very experienced in these matters.

I'll get back to you as soon as possible.

Greetings again.

**Comment by Jose1971AB** [comment] 2020-06-25 13:05
Hi @mapx- , I'm back... I tell you...

**These pages are solved**
[https://tutorialesenlinea.es/
https://milapercia.com/
http://www.artesacro.org/
https://brazzers3x.org/]

**As for** [https://vidcorn.tv/] **and** [https://www.thenekodark.com/] **I'll tell you...**

I think I've done the tests well, I detail them for you.

**1 Test** 
I disable Fanboy+Easylist-Merged Complete List, purge cache and test

For [https://www.thenekodark.com/] --> It's solved

For [https://vidcorn.tv/] --> I added the script you indicated in My filters but I don't really know if it works because two things happen...

A) Most of the time "Loading" appears and it stays there for a while. See screenshot

![3 vidcorn](https://user-images.githubusercontent.com/44229110/85723503-99b05600-b6f3-11ea-9d71-73958fb82dda.png)

B) Other times, very rarely, the registration box appears

**2 Test**
Disabled Fanboy+Easylist-Merged Complete List and enabled EasyList and EasyPrivacy, purge cache and test

It's the same as the first test

**3 Test**
I put uBlock by default and add in My filters `vidcorn.tv#@#+js(acis, document.createElement, 'meta')` (If I leave it completely by default, obviously, it wouldn't work for [https://vidcorn.tv/])

It's the same as the first test

**4 Test** (on my own)
I disable uBlock Origin completely, from the Firefox Add-ons section.

Same as previous tests

**My conclusions are...**

That for [https://www.thenekodark.com/] it is solved disabling Fanboy+Easylist-Merged Complete List but for [https://vidcorn.tv/] it seems that the notice does not appear but it stays "Loading" and the registration box does not appear.

What could be happening now with [https://vidcorn.tv/]?...

A friend greeting.

**Comment by mapx-** [comment] 2020-06-25 13:17
if `vidcorn` has the same behaviour even disabling uBO => site issue

**Closed by mapx-** 2020-06-25 13:17 UTC
