### ISSUE TITLE
The entire .tk TLD

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#6235] opened 2019-09-02 09:09 UTC
### URL(s) where the issue occurs

Large portions of the internet (See the suggested entry below for more info).

### Describe the issue

By now, the .tk TLD has been one of the very biggest TLDs in the world for a decade. However, after I've looked on and off for some months now into which sites it is that *actually* use that TLD, I've concluded that there's less than 50 legitimate⁽¹⁾ .tk sites in existence, and that the other tens of millions of them are pretty much solely malware/ad/tracking pushers. They also tend to clog up Google search results, with a bunch of "results" that just consist of garbled word salads.

I know that blocking entire TLDs has been considered by adblocking community members who are older than me (in their 30s-50s) to be a worrying practice, but I now believe there are for the first time enough evidence against a TLD to seriously consider doing such a thing in a mainstream list.

My suggested entry is `||.tk^$doc,domain=~coolcmd.tk|~budterence.tk|~google.tk|~c0d3c.tk|~anonytext.tk|~tokelau-info.tk|~fakaofo.tk|~nukunonu.tk|~loljp-wiki.tk|~ninetail.tk|~goshujin.tk|~graph.tk|~dot.tk`. Sure, it may or may not need a few additional whitelistings before the entry can go live, but this is the very best effort I could do.

If we are to go extra ballistic and remove their Google search results as well, to make them less cluttered, I suggest `google.*##.rc:has(a[href*=".tk/"]:not([href*="coolcmd.tk"]):not([href*="budterence.tk"]):not([href*="google.tk"]):not([href*="c0d3c.tk"]):not([href*="anonytext.tk"]):not([href*="tokelau-info.tk"]):not([href*="fakaofo.tk"]):not([href*="nukunonu.tk"])):not([href*="loljp-wiki.tk"]):not([href*="ninetail.tk"]):not([href*="goshujin.tk"]):not([href*="graph.tk"]):not([href*="dot.tk"])`

⁽¹⁾ = Includes non-virus NSFW sites (e.g. ninetail.tk), but excludes link shorteners (e.g. c8owk.tk) and non-main domain versions (e.g. transportinfo.tk).

### Screenshot(s)

Not applicable.

### Versions

- Browser/version: Chrome 76.0.3809.132 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.124 + Nano Defender 15.0.0.166

### Settings

Not applicable that I'm aware of.

### Notes

https://domaintyper.com/top-websites/most-popular-websites-with-tk-domain/ lists 632 domains with the `.tk` domain within the top 1mill of whichever ranking system. Only **5** of which I could confirm as being legitimate.

**Comment by okiehsch** [comment] 2019-09-02 09:28
> I know that blocking entire TLDs has been considered by adblocking community members who are older than me (in their 30s-50s) to be a worrying practice

I am not sure if this is a dig at me but I can tell you that I am indeed against blocking an entire TLD by default because it is clearly out of scope in my opinion.
Users are free to add such a filter th their own lists ar enable filter lists that include such filters.

**Comment by spirillen** [comment] 2019-09-02 09:29
This sounds like a very bad idea, yes I'm in the agegroup 40+ :smile: there are a lot more legit domains than you ~50 domains that you refer to in your post.

1. Who should curate such a whitelist?
1. This would, to me, looks more like censuring, than protecting against malicious domains
1. This will make all with a .tk tld guilty until proven innosent, which is reworsed democratic approach (unless your a Trump voter).
1. How would you categories a tk domain like `https://mypdns.tk/` ?
1. The link you refer to in your post is all about, and only .tk

**Closed by okiehsch** 2019-09-02 09:28 UTC

**Comment by DandelionSprout** [comment] 2019-09-02 09:37
No, this is not a dig at you (okiesch), it's just that multiple people who've been in this community before I joined it in 2017, seemed to be confused by the notion of doing so. 😅 Plus that I believe that almost every major list maker except me, Kowith, and maybe 1 or 2 others, have previously been in security or data-geek forums. 

(To spirillen) I accept points 1 and 3. As for №2, I've attempted to whitelist as many genuine sites as feasibly possible to avoid random censorship, trying to focus my blockade aim on insubstantial ad/malware sites. As for №4, as the page doesn't seem to load, I consider it pre-emptively non-legitimate as it can be very easily snapped up by malware pushers.

Nevertheless, I'll concede defeat for now.

**Comment by spirillen** [comment] 2019-09-02 10:52
@DandelionSprout 
> As for №4, as the page seems (upon a 2nd attempt) to redirect to an .org domain, I consider it a non-main domain version, for lack of another shorthand way to describe it.

Your almost right :smile: It's a domain I have secured for not being turned into a malicious domain used by evil people, as typo-squatting or and other confusing stuff. 

And yes that is an acknowledge of the issue with the free domain .tk

PS. Thx for confirming the rewrite works as intended :smiling_imp:

**Comment by DandelionSprout** [comment] 2019-09-02 11:00
That's possibly the best ever way you could've proved your point, to the point that I congratulate you for it.
