### ISSUE TITLE
w.ynet.co.il: breakage

### ISSUE THREAD

**Issue by robert777robert777** [uBlockOrigin/uAssets#20110] opened 2023-10-16 14:18 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://w.ynet.co.il/news/attackingaza?externalurl=true`

### Category

breakage

### Description

easylist il blocks the loading of:
https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js
the page loads only paritaly because jquery is needed...

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 123519
 cosmetic: 62128
 scriptlet: 20123
 html: 0
listset (total-discarded, last-updated):
 added:
  ISR-0: 1791-0, now
  RUS-0: 39997-10, now
 default:
  user-filters: 2-0, never
  easylist: 71842-38, now
  easyprivacy: 33187-156, now
  plowe-0: 3729-1073, now
  ublock-badware: 7264-133, now
  ublock-filters: 34968-172, now
  ublock-privacy: 561-7, now
  ublock-quick-fixes: 226-91, now
  ublock-unbreak: 2137-31, now
  urlhaus-1: 11930-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 46 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 912 ms (selfie)
 maxAssetCacheWait: 224 ms
popupPanel:
 blocked: 2
 network:
  clarity.ms: 1
  googletagmanager.com: 1
 extended:
  ##+js(abort-on-property-write, upManager)
  ##+js(no-setTimeout-if, offsetHeight)
```
</details>

**Comment by liamengland1** [comment] 2023-10-16 14:52
Caused by `||cloudfront.net^$script,domain=ynet.co.il` in Israel regional list and `||cloudfront.net^$third-party,domain=ynet.co.il` in Adguard Base

@Hebrew-uBO-User @alex302

Not a uAssets issue though

**Comment by Alex-302** [comment] 2023-10-16 18:54
Fixed in AdGuard filter.

**Closed** 2023-10-16 18:57 UTC
Labels: broken by other list

**Comment by Hebrew-uBO-User** [comment] 2023-10-16 23:51
Fixed in EasyList Hebrew.
