### ISSUE TITLE
peliculasveo.gratis [ADS] [Fake Button] [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2030] opened 2018-04-19 20:21 UTC
URL(s) where the issue occurs

`http://www.peliculasveo.gratis/Ver-el-hombre-de-las-mil-caras-2016-a-r-Online/`

Describe the issue

![](https://i.imgur.com/sRFcZPL.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment] 2018-04-19 20:32
```
||amgload.net^$xmlhttprequest,redirect=nooptext,domain=peliculasveo.gratis
||piguiqproxy.com^$xmlhttprequest,redirect=nooptext,domain=peliculasveo.gratis
peliculasveo.gratis##script:inject(abort-current-inline-script.js, atob, tabunder)
```

**Comment by okiehsch** [comment] 2018-04-19 20:36
`peliculasveo.gratis##script:inject(abort-current-inline-script.js, atob, tabunder)`
I do not get such a popup, I do get one caused by admaven and fixed by 
`peliculasveo.gratis##script:inject(abort-on-property-write.js, Fingerprint2)`
can you show me the popup call in your logger?

**Closed** 2018-04-19 20:37 UTC

**Comment by zaphodbeebblebrox** [comment] 2018-04-19 20:39
![image](https://user-images.githubusercontent.com/22801430/39017031-206ea454-43f0-11e8-8684-55e242b3d394.png)

**Comment by okiehsch** [comment] 2018-04-19 20:40
That is an admaven call and should be fixed by 
`peliculasveo.gratis##script:inject(abort-on-property-write.js, Fingerprint2)`

**Comment by KiLL4FuNK** [comment] 2018-08-09 16:04
Fake Button Pop-up

**Comment by KiLL4FuNK** [comment] 2019-01-10 00:32
Pop-up
