### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by VolitiveGoblin** [uBlockOrigin/uAssets#14554] opened 2022-08-27 15:52 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/dimoriae`

### Category

ads

### Describe the issue

Still shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 80432
  cosmetic: 45242
  scriptlet: 17653
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69310-176, never
    easyprivacy: 27312-133, never
    plowe-0: 3634-779, never
    ublock-abuse: 76-0, never
    ublock-badware: 4233-0, never
    ublock-filters: 32512-138, never
    ublock-privacy: 231-0, never
    ublock-quick-fixes: 389-0, never
    ublock-unbreak: 1858-0, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1632 ms
  maxAssetCacheWait: 91 ms
popupPanel: 
  blocked: 83
  blockedDetails: 
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 4
    doubleverify.com: 2
    google-analytics.com: 1
    imrworldwide.com: 30
    scorecardresearch.com: 41
    serving-sys.com: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-27 15:53
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-08-27 15:53
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-08-27 15:53 UTC

**Comment by MasterKia** [comment] 2022-08-27 15:55
@VolitiveGoblin Add this to "My filters" and test again:
`twitch.tv##+js(twitch-videoad)`

**Comment by krystian3w** [comment] 2022-08-27 18:33
worse if custom list added disabling by `#@#`

ten even works:

   twitch.tv##+js(twitch-videoad, foo, bar)
