### ISSUE TITLE
Advanced Adblock detector problem

### ISSUE THREAD

**Issue by CyberMan571** [uBlockOrigin/uAssets#9608] opened 2021-07-20 06:26 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.kanald.com.tr/canli-yayin
https://s1.kanald.com.tr/scripts/video-page.bundle.js
```

### Describe the issue

The web page has advanced AdBlock detector, and  it has been blocked all bypass method!
I want you to make anti AdBlock Detector  for all types!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30759335/126269050-3dc62436-879a-4bf9-b568-6c9209989c4f.png)
>-------
![image](https://user-images.githubusercontent.com/30759335/126269178-a196b547-9e52-4be9-839c-23cdd862ea40.png)

>------
Additional: I found  wrong  a filter line
![image](https://user-images.githubusercontent.com/30759335/126269641-12e7bd23-778e-49ec-91c5-984e83b1191e.png)

### uBlock Origin version

1.36.2

### Browser name and version

Firefox 68.8.0esr

### Settings

![image](https://user-images.githubusercontent.com/30759335/126269855-f015a0b6-f863-4f39-b35a-91a24b71fdc6.png)
they inside image

**Comment by okiehsch** [comment] 2021-07-20 07:51
The video play fine on my end.
![image](https://user-images.githubusercontent.com/16838044/126282816-586517e9-654a-4286-9ff4-dd7173219b2c.png)

**Comment by CyberMan571** [comment] 2021-07-20 07:59
```js
{
    window.frameElement.style.height = document.querySelector("html").offsetHeight + "px"
}
}, {
    key: "getMediaContentData",
    value: function getMediaContentData(e) {
        var t = new URLSearchParams(window.location.search).get("token"),
            n = {
                id: e.getAttribute("data-id"),
                p: e.getAttribute("data-part"),
                pc: e.getAttribute("data-part-count")
            };
        t && (n.token = t);
        var r = Object.keys(n).map(function(e) {
            return e + "=" + n[e]
        }).join("&");
        return fetch("/actions/media?" + r).then(function(e) {
            return e.json()
        }).then(function(e) {
            return e.data
        })
    }
}, {
    key: "getCountryCode",
    value: function getCountryCode() {
        return fetch("https://geoloc.subservis.com/getcountrycode").then(function(e) {
            return e.json()
        }).then(function(e) {
            var t = "";
            return e && e.hasOwnProperty("country") && (t = e.country), t
        })
    }
},
Adblock  Detector has been appeared after this
```
https://geoloc.subservis.com/getcountrycode
```

**Comment by okiehsch** [comment] 2021-07-20 08:01
So, you are trying to access that video from Germany?

**Comment by CyberMan571** [comment] 2021-07-20 08:03
> The video play fine on my end.
> ![image](https://user-images.githubusercontent.com/16838044/126282816-586517e9-654a-4286-9ff4-dd7173219b2c.png)

Have you done any changes?
Advertise for TR is available

**Comment by okiehsch** [comment] 2021-07-20 08:04
I used a default setup and a turkish IP.
Can you post a screenshot of the anti adblock message you see on your end?

**Comment by CyberMan571** [comment] 2021-07-20 08:06
![image](https://user-images.githubusercontent.com/30759335/126284813-ad6923ac-9937-4fd7-92c5-ad8d73155fd9.png)

**Comment by okiehsch** [comment] 2021-07-20 08:10
Thanks, I tried with different browser and I can't reproduce that message.
I have to use a VPN because the site geoblocks me but I don't get blocked because of adblock usage.

**Comment by okiehsch** [comment] 2021-07-20 08:12
I will remove `@@||kanald.com.tr^$script,1p`.

**Comment by CyberMan571** [comment] 2021-07-20 09:08
CNAME:
https://yk0i9vu08ojw.merlincdn.net/scripts/video-page.bundle.js
a bit odd
I don't change cnameuncloak:true  What is wrong?

**Comment by mapx-** [comment] 2021-07-20 09:17
it seems fixed by adguard list

![image](https://user-images.githubusercontent.com/10303732/126295908-8bea284a-4592-400a-95a1-dda464160add.png)

**Comment by CyberMan571** [comment] 2021-07-20 09:26
I tried,  however again

**Comment by mapx-** [comment] 2021-07-20 09:44
tested in FF + adguard turkish, turkish ip / european ip => no issue, the video is running well

**Comment by mapx-** [comment] 2021-07-20 09:46
be sure your antivirus software has no web shields enabled and your FF enhanced tracking protection is not blocking too much

**Comment by CyberMan571** [comment] 2021-07-20 10:27
> tested in FF + adguard turkish, turkish ip / european ip => no issue, the video is running well

Only, I want  random u-block UUID for advanced AdBlock protection, why?   Not do detecting ad blocker

**Comment by uBlock-user** [comment] 2021-07-20 13:16
Reset to default settings + update to Firefox 78 ESR.

**Closed by uBlock-user** 2021-07-20 13:16 UTC
Labels: unable to reproduce

**Comment by CyberMan571** [comment] 2021-07-20 22:55
less effort  more simpleness!
Can you develop ublock protection for anti adblock?

**Comment by krystian3w** [comment] 2021-07-23 20:27
No possible, webmaster can detect `redirect=` and hide by CSS:

`:style(visibility: hidden !important; height: 1px !important; width: 1px !important;)`
`:style(opacity: .0001 !important; height: 1px !important; width: 1px !important;)`

**Comment by CyberMan571** [comment] 2021-07-24 16:45
Thanks,
Yes, I have  planned in the future for this!
Firstly; To gather necessary info.
