### ISSUE TITLE
www.ferrarilamborghininews.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7237] opened 2020-04-14 16:11 UTC
### URL(s) where the issue occurs

`https://www.ferrarilamborghininews.com/blog-entry-17319.html`
Firefox Android only (no desktop browser or Brave Android)

### Describe the issue

Anti-adblock

### Screenshot(s)

![ferrarilamborghininews](https://user-images.githubusercontent.com/58900598/79247306-521c7b00-7eb5-11ea-91ec-72f5135ad62c.png)

### Versions

- Browser/version: Firefox Android 68.7.0
- uBlock Origin version: 1.26.0

### Settings

- Reproduced with default on Firefox 75.0 Desktop + responsive mode

### Notes

`ferrarilamborghininews.com##+js(acis, document.addEventListener, google_ad_client)`
didn't work, also it only appears on Firefox Android on my end so I suggest
`!#if env_mobile`
`ferrarilamborghininews.com##^script:has-text(antiblock)`
`!#endif`

**Comment by uBlock-user** [comment] 2020-04-14 16:18
Can't reproduce, was fixed in https://github.com/uBlockOrigin/uAssets/commit/fd23beecdd6b3e7486db56b0722f39b477d619ec

**Comment by Yuki2718** [comment] 2020-04-14 16:21
> 
> 
> Can't reproduce, was fixed in [fd23bee](https://github.com/uBlockOrigin/uAssets/commit/fd23beecdd6b3e7486db56b0722f39b477d619ec)

Okay, I'll test with default setting on Firefox Android Beta.

**Comment by mapx-** [comment] 2020-04-14 16:32
reproduced, fixed

**Closed** 2020-04-14 16:32 UTC

**Comment by mapx-** [comment] 2020-04-14 16:34
reproduced using not "responsive FF mode" but this add-on: `Mobile View Switcher`

**Comment by uBlock-user** [comment] 2020-04-14 16:36
must be serving a different version of the page with mobile UA then, the anti-adblock script itself is not present in the desktop version.

**Comment by Yuki2718** [comment] 2020-04-16 10:43
I assumed responsive mode automatically changes UA accordingly, but also set mobile UA via `general.useragent.override` just in case, this may be the reason.
