### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by SupernaturalGamer** [uBlockOrigin/uAssets#14207] opened 2022-08-02 08:19 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://e.mail.ru/inbox/`

### Category

ads

### Describe the issue

Recently, ads have started to appear on the right side of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110454692/182326660-38436b65-298c-483e-8942-976e5aef62fc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98133
  cosmetic: 67142
  scriptlet: 17543
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 40343-9, 20h.44m
    easylist: 68917-66, 22h.56m
    easyprivacy: 27463-223, 22h.55m
    plowe-0: 3640-784, 9d.1h.37m
    ublock-abuse: 76-1, 22h.57m
    ublock-badware: 4221-92, 1d.10h.20m
    ublock-filters: 32403-144, 22h.53m
    ublock-privacy: 225-3, 10d.18h.59m
    ublock-quick-fixes: 347-65, 22h.51m
    ublock-unbreak: 1851-42, 1d.10h.19m
    urlhaus-1: 4929-0, 22h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 54347 ms (selfie)
  maxAssetCacheWait: 2003 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    mail.ru: 12
```
</details>

**Comment by MasterKia** [comment] 2022-08-02 08:20
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Please read and follow the Prerequisites carefully.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14206

**Closed** 2022-08-02 08:51 UTC
