### ISSUE TITLE
scan-manga.com: breakage

### ISSUE THREAD

**Issue by Dugur32** [uBlockOrigin/uAssets#11559] opened 2022-02-02 22:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.scan-manga.com/lecture-en-ligne/The-Lazy-Prince-Becomes-a-Genius-Chapitre-25-FR_208749.html`

### Category

breakage

### Describe the issue

![Capture d’écran 2022-02-02 232419](https://user-images.githubusercontent.com/98802501/152247724-00f9556e-56dc-43fd-a1d0-f237811e677d.png)

the pages do not appear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 94279
  cosmetic: 22992
  scriptlet: 16538
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26168-3257, now
    easylist: 62756-23707, now
    easyprivacy: 26693-343, now
    plowe-0: 3680-825, now
    ublock-abuse: 77-1, now
    ublock-badware: 3831-78, now
    ublock-filters: 30186-519, now
    ublock-privacy: 194-3, now
    ublock-unbreak: 1696-39, now
    urlhaus-1: 7496-0, now
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 179 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by uBlock-user** [comment] 2022-02-02 22:26
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11557

**Closed by uBlock-user** 2022-02-02 22:26 UTC

**Comment by Dugur32** [comment] 2022-02-02 22:27
it's not the same problem

**Comment by uBlock-user** [comment] 2022-02-02 22:32
So explain the problem, anyways no need to open any new thread again, post it there.

**Comment by Dugur32** [comment] 2022-02-02 22:34
ok sorry, before the site made me a white page with uB
and now the steps are not displayed on the site knowing that I have updated the filters

**Comment by Dugur32** [comment] 2022-02-02 22:35
page

**Comment by uBlock-user** [comment] 2022-02-02 22:35
@AdamWr

**Comment by uBlock-user** [comment] 2022-02-03 09:40
https://github.com/AdguardTeam/AdguardFilters/commit/aa821427ec7005bebc2ef30547a07c8876118439
