### ISSUE TITLE
realclearpolitics.com: breakage

### ISSUE THREAD

**Issue by paguilarRCP** [uBlockOrigin/uAssets#18039] opened 2023-05-11 15:47 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

There is an issue with our page that is happening when ublock is active, the page is realclearpolitics.com and the issue is that when we active ublock our script that contain this url:
 `https://www.realclearpolitics.com/esm/cache/all.js`
is been blocked so our page is not been able to load correctly, we found two specific issues with ublock the first one is our main menu and the second one is our comment section, I will add a before and after using ublock in our page.

https://github.com/uBlockOrigin/uBlock-issues/assets/101362183/61bd4593-782f-42c1-8a8a-68cf19442b74

https://github.com/uBlockOrigin/uBlock-issues/assets/101362183/9e703df2-b9a3-413e-9ada-5262a77d51a3

https://github.com/uBlockOrigin/uBlock-issues/assets/101362183/4838c0f3-5427-44a7-9c49-bc4b013ccc10

https://github.com/uBlockOrigin/uBlock-issues/assets/101362183/683a5b65-0e1d-4307-86c9-4851517ae7ab

### A specific URL where the issue occurs.

`https://www.realclearpolitics.com/`

### Steps to Reproduce

just go to the site and active ublock

### Expected behavior

We would like to see our main menu and our comment system working with ublock active
https://github.com/uBlockOrigin/uBlock-issues/assets/101362183/b57baffb-6e40-4607-ba16-4104b796fe06

### Actual behavior

This is happening with ublock active
https://github.com/uBlockOrigin/uBlock-issues/assets/101362183/2c63cfa1-c05f-41f8-8ca8-e7e53bac3bfc

### Configuration

This issue is happening with the normal configuration of ublock

**Comment by peace2000** [comment] 2023-05-11 16:32
No issues on my end either. How did you verify that script is being blocked? If you can verify that, can you also verify what rule or list blocks it?

**Comment by gorhill** [comment] 2023-05-11 17:03
> try uninstall or return ublock to the default settings

Filter lists are updated after a few minutes upon new install, the issue was fixed with <https://github.com/uBlockOrigin/uAssets/issues/17997>, so at most the site is broken following a new install when visiting the site before the lists update, which takes at most a minute. After this the site works fine.

**Comment by gorhill** [comment] 2023-05-11 17:03
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/17997>.

**Closed by gorhill** 2023-05-11 17:03 UTC
Labels: Waiting for feedback
