### ISSUE TITLE
Microsoft Answers breaks

### ISSUE THREAD

**Issue by thany** [uBlockOrigin/uAssets#8987] opened 2021-04-30 20:47 UTC
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://answers.microsoft.com/en-us/newthread

### Describe the issue

 

When trying to select a category, the submit button goes disabled, and that's the end of that. Disable uBlock, and it works fine. Since uBlock doesn't provide a way to whitelist filters for a specific site, it's not possible for me to check which one it is, but it must be one of the ones enabled with default settings.

### Screenshot(s)

| Before | After with uBlock | After without uBlock |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/152227/116751799-d9775680-aa04-11eb-9c53-c571d59ea6c0.png) | ![image](https://user-images.githubusercontent.com/152227/116751819-e2682800-aa04-11eb-869f-ef3ec6ef8e7a.png) | ![image](https://user-images.githubusercontent.com/152227/116751900-f744bb80-aa04-11eb-9aec-545c615dba98.png) |

### Versions

- Browser/version: Firefox 88
- uBlock Origin version: 1.35.0

### Settings

(Not relevant, since it also goes wrong on default settings)

### Notes

The problem goes away when disabling the EasyPrivacy filterlist, so that one *might* be the culprit. I just disabled filterlists one by one, starting at the bottom, in a new browser profile with uBlock as the only extension with otherwise default settings.

**Comment by uBlock-user** [comment] 2021-04-30 20:57
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/8985

**Closed by uBlock-user** 2021-04-30 20:57 UTC
