### ISSUE TITLE
linkbucks.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#255] opened 2017-01-01 03:50 UTC
#### URL(s) where the issue occurs

```
http://www.linkbucks.com/AYNZ
http://www.zytpirwai.net/AYNZ
```

#### Describe the issue

Unblocked popups.

#### Versions

- Browser/version: 

![http://i.imgur.com/xmXSoZ2.png](http://i.imgur.com/xmXSoZ2.png)

- uBlock Origin version: 

![http://i.imgur.com/okaHmSt.png](http://i.imgur.com/okaHmSt.png)

#### Settings

![http://i.imgur.com/65yZT6p.png](http://i.imgur.com/65yZT6p.png)

![http://i.imgur.com/27IyofE.png](http://i.imgur.com/27IyofE.png)

#### Screenshot(s)

![http://i.imgur.com/UeNZcAC.png](http://i.imgur.com/UeNZcAC.png)

**Comment by gorhill** [comment] 2017-01-01 13:43
I could reproduce.

**Comment by ghajini** [comment] 2017-01-01 13:48
could reproduce popups plus some malware redirects and trojans
![screenshot 103](https://cloud.githubusercontent.com/assets/20338483/21581403/20f22aee-d057-11e6-8543-adb56e1f668b.png)

**Comment by ghajini** [comment] 2017-01-01 14:37
sorry for that....but i am really got infected...

**Comment by gorhill** [comment] 2017-01-01 14:41
Report to malware list maintainers whatever site you think infected you.

**Comment by gorhill** [comment] 2017-01-01 15:26
The site opens a first popup `about:blank`, then opens a second popup _through_ that first one, then closes the first one. The closing of the first popup by the site itself causes uBO to fail to find the tab which opened the second popup (which contains the nasty ads) -- and thus the popup filtering code fails to execute for that second popup.

**Comment by gorhill** [comment] 2017-01-01 16:54
I have two flavor of a fix:
1. Both popups are closed (including the `about:blank` one).
1. Only non-`about:blank` popups are closed.

I checked with FF+ABP, and the behavior is solution 2. @SMed79, do you know if this is the intended behavior from ABP or if this should be considered an issue given the filter `*$popup`?

**Comment by SMed79** [comment] 2017-01-01 23:08
Sorry i have no idea.

**Closed** 2017-01-02 15:50 UTC

**Comment by Betsy25** [comment] 2017-01-02 20:19
Just FYI, there are a lot of site specific "solutions" at [github.com/adsbypasser/adsbypasser](https://github.com/adsbypasser/adsbypasser/tree/master/src/sites)

**Comment by nando30010** [comment] 2017-01-02 20:53
Hey, which you are using?
