### ISSUE TITLE
Anti Adblock issue

### ISSUE THREAD

**Issue by HookemAZ** [uBlockOrigin/uAssets#5613] opened 2019-05-18 02:43 UTC
### URL(s) where the issue occurs

`https://metabattle.com/wiki/MetaBattle_Wiki`

### Describe the issue

Anti ad-blocker prevents site from fully loading.

### Screenshot(s)

https://imgur.com/a/4Ck8qNu

### Versions

- Browser/version: Chrome 74.0.3729.157 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.19.2

### Settings

Just standard Nano Defender setup.

### Notes

Never had an issue with this site before. As of today I am unable to bypass the anti-adblock no matter what I try.

**Comment by okiehsch** [comment] 2019-05-18 03:19
> Anti ad-blocker prevents site from fully loading.

What part is not loading?
I ask because if the issue is only about the message in your screenshot and site functionality is the same with or without an adblocker then this will be fixed in `uBO-annoyances`.

**Comment by HookemAZ** [comment] 2019-05-18 03:22
I think you are correct. My apologies. Now that I have messed with it, the site is functioning again and it's just the annoyances. Thanks so much for the reply.

**Comment by okiehsch** [comment] 2019-05-18 03:23
I will fix the message in `uBO-anoyances`.

**Comment by HookemAZ** [comment] 2019-05-18 03:23
Thank you sir.

**Closed** 2019-05-18 03:25 UTC
