### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Nived151** [uBlockOrigin/uAssets#10926] opened 2021-12-15 15:02 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/watch?v=1uDfnHoPq3w`

### Category

ads

### Describe the issue

A lot of ads are showing up lately on youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77741
  cosmetic: 39706
  scriptlet: 16273
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61773-8, 22h.38m
    easyprivacy: 26484-17, 3d.23h.48m
    plowe-0: 3687-809, 2d.21h.32m
    ublock-abuse: 72-0, 3d.23h.46m
    ublock-badware: 3565-61, 3d.23h.43m
    ublock-filters: 29878-131, 3d.23h.41m
    ublock-privacy: 189-2, 3d.23h.39m
    ublock-unbreak: 1709-39, 3d.23h.37m
    urlhaus-1: 7553-0, 10h.37m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1196
  launchFromSelfie: true
popupPanel: 
  blocked: 38
```
</details>

**Comment by uBlock-user** [comment] 2021-12-15 15:23
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2021-12-15 15:23 UTC
