### ISSUE TITLE
Multiup.*

### ISSUE THREAD

**Issue by dhana-exe** [uBlockOrigin/uAssets#7897] opened 2020-09-11 02:20 UTC
```
https://multiup.org/en/mirror/bfb44d260f4f3908e5cb057c2fec0fb6/Koikatu-All-In-One-Re-Pack.rar.rar
https://multiup.eu/en/mirror/bfb44d260f4f3908e5cb057c2fec0fb6/Koikatu-All-In-One-Re-Pack.rar.rar
```

if you click download... like on googledrive button... it redirect to ads website.... can u guys do that?
block that ads?

**Comment by ghajini** [comment] 2020-09-11 04:43
It will addressed as per @gorhill decision

This is discussed many times
https://github.com/uBlockOrigin/uAssets/issues/5435

Use this userscript in violentmonkey

`document.querySelectorAll("form>button[link]").forEach(b => {
  b.addEventListener("click", ev => {
    ev.preventDefault();
    location.href = b.getAttribute("link");
  }, true);
});`

**Comment by Dhanamerdeka** [comment] 2020-09-11 05:29
@ghajini amazing... this work like a charm....
but can i ask?
how do i can copy the link like googledrive with right click?
the link can't be copy... can you help me?

**Comment by ghajini** [comment] 2020-09-11 06:03
Wait for gorhill

**Comment by Dhanamerdeka** [comment] 2020-09-11 08:28
ok i will wait. :)

**Comment by krystian3w** [comment] 2020-09-11 11:29
No possible safe repair right click on `gdrive` (Google also for disk use html5 menu) / `google search` = possible break completly google maps.

**Comment by Dhanamerdeka** [comment] 2020-09-11 11:48
@krystian3w  ummm i mean... on multiup... if u click "download" they now can automatically go to googledrive without go to ads web... but what i ask... i want to copy those link without go to that link...
so i mean... i need something to make me onlu just do "right click > copy link"

**Comment by mapx-** [comment] 2020-09-11 11:54
You have to use `inspect` (right click on element then `inspect`) and you'll find the wanted link

**Comment by krystian3w** [comment] 2020-09-11 11:55
This would require another script which, on the basis of the button code ("html `<button>`"), will paste a link to the page ("html `<a>`").

**Comment by uBlock-user** [comment] 2020-09-11 12:01
This is a can't fix case as you need a dedicated [scriptlet](https://github.com/uBlockOrigin/uAssets/issues/5435#issuecomment-544169204) for this.

**Comment by Dhanamerdeka** [comment] 2020-09-11 12:03
@mapx- i know what inspect element... but i need something that direct... so i dont have to open that thing.... :(

**Comment by Dhanamerdeka** [comment] 2020-09-11 12:04
@krystian3w i not too good when it come to this type of things....
but how to use that?

**Comment by Dhanamerdeka** [comment] 2020-09-11 12:06
@uBlock-user ummm i already done with this problem with code from @ghajini but...
can you solve my second problem above?
(btw i using tampermonkey for that and as far this work quite good....)

**Comment by uBlock-user** [comment] 2020-09-11 12:07
>  can you solve my second problem above?

What second problem ?

**Comment by krystian3w** [comment] 2020-09-11 12:12
> What second problem ?

Change/duplicate `button` into/as `a` - because button do not have in right click menu option "copy this URL":

`<button type="submit" namehost="drive.google.com" link="https://drive.google.com/uc?export=download&amp;id=1jqUW6wPUsdtMAfb_CuuZoLM3F5icU94h"`
⬇️ 
`<a href="...">`

or show `link` value into `input` or `textarea`.

**Comment by uBlock-user** [comment] 2020-09-11 12:16
> Change/duplicate button into/as a - because button do not have in right click menu option "copy this URL":

Not possible, also requires a scriptlet to do that.

**Comment by Dhanamerdeka** [comment] 2020-09-11 12:19
> > Change/duplicate button into/as a - because button do not have in right click menu option "copy this URL":
> 
> Not possible, also requires a scriptlet to do that.

scriptlet......what?
u mean like.... earlier code that i tested on tampermoney? that is scriptlet?
sorry my brain was too slow... i not expert on this :) maybe i came here is right decision... so i can steal knowledge from you all :D

**Comment by uBlock-user** [comment] 2020-09-11 12:21
Yes a scriptlet that swaps elements( `button` -> `a`) and its containing attributes. Someone on GitHub did this. I can't recall which repo though.

**Comment by krystian3w** [comment] 2020-09-11 12:21
maybe @ghajini can copy element, paste into DOM with change type of element into `<a>` with changed `atrrib` link to `href`.

**Comment by Dhanamerdeka** [comment] 2020-09-11 12:22
i hope i get that link soon...
my brain.exe stopped working right now LOL

**Comment by Mennaruuk** [comment] 2021-08-21 20:08
I don't see any more redirecting to ads.

https://user-images.githubusercontent.com/52135169/130333679-01db87dc-3caf-463e-9078-2661cb798983.mp4

**Comment by Dhanamerdeka** [comment] 2021-08-22 00:44
> I don't see any more redirecting to ads.
> 
>  3dNzvNymrC.mp4

![Screenshot (3090)](https://user-images.githubusercontent.com/29838157/130338306-bdb1b32c-bff3-42d0-90e6-310406c70588.png)
![Screenshot (3091)](https://user-images.githubusercontent.com/29838157/130338308-d84465c8-4d93-4c95-bae1-db409770cfc0.png)

still there....
https://multiup.org/download/9fd4093c5c4940aebe317f1ad447c603/%5BAnime%20Time%5D%20Peter%20Grill%20to%20Kenja%20no%20Jikan%20%28Peter%20Grill%20and%20the%20Philosopher_s%20Time%29%20%28Season%201%29%20%5BUncensored%5D%5BBD%5D%5BDual%20Audio%5D%5B1080p%5D%5BHEVC%2010bit%20x265%5D%5BAAC%5D%5BEng%20Sub%5D.rar

chrome lastest update i belive
and ublock lastest with default setting

**Comment by krystian3w** [comment] 2021-08-22 11:06
scam link "usnet" is again visible?

**Comment by Dhanamerdeka** [comment] 2021-09-15 04:11
> scam link "usennet" is again visible?
> 
> ```
> ##section b:has-text(/Usennet.nl/i):upward(section):upward(div[class*="col"])
> ```
> 
> Also in Firefox possible open aliexpress instead download "files" link. Page like open pop-unders.

no... i mean the DOWNLOAD redirect to ads again,

**Comment by krystian3w** [comment] 2021-09-15 05:45
I only reproduce load aliexpress instead link to video download.

So aliexpress are not  third party advert (rather self-promo)?

**Comment by Dhanamerdeka** [comment] 2021-09-15 07:48
> I only reproduce load aliexpress offers instead link to video/file download (PC/mobile).
> 
> * And on mobile I see fake button into `usennet.nl` - race conditions on cosmetic procedural filtering....?
> 
> So aliexpress are not third party advert (rather self-promo then multiup.* is built by China shoper/seller)?

maybe this is some type of ads that works like.... redirect to ads page... like Popads, but it trigger by click download button
and also they earn something if visitor do activity on there

**Comment by uBlock-user** [comment] 2021-10-09 14:48
`multiup.*##div.text-center:has(a[class="btn btn-success"][href^="abp:subscribe"])` still works.

**Comment by CyberMan571** [comment] 2021-10-09 15:06
@uBlock-user 
you look at `i/e.fn.magnificPopup https://multiup.eu/build/610.15f042f0.js:1:559194` AdBlock issue in this

**Comment by Dhanamerdeka** [comment] 2021-10-10 04:34
i think fake button is not important.... after all we all understand that those button is fake... and never works if we need the files...
all we need is click download and redirected to destination

until now. what we click will came to ads before we came to destination links.....
that's all what i need and maybe other people too....

**Comment by krystian3w** [comment] 2021-10-10 18:16
Someone made "risky" `scritplet` to change any attribute with `href=` to omit "Ajax transfer" technology. So can by fixed without addon "click ads moneiner defender".

**Comment by CyberMan571** [comment] 2021-10-10 18:27
> I don't see any more redirecting to ads.
> 3dNzvNymrC.mp4

Yeah,  it has  access to some IP
![image](https://user-images.githubusercontent.com/30759335/136708607-de0b1a4e-d9d6-4be1-b5f9-0920aa3fa06c.png)
Lanet Olasi!
damm it!
I look fake or diffirent dns ip

**Comment by uBlock-user** [comment] 2021-10-10 18:29
This cannot be fixed without a dedicated scriptlet like this one -- 

```
/// multiup.js
/// alias mtu.js
// example.com##+js(mtu, form[action], button[link], action, link)
(() => {
		'use strict';
		const selector = '{{1}}';
		if ( selector === '' || selector === '{{1}}' ) { return; }
		const selector2 = '{{2}}';
		if ( selector2 === '' || selector2 === '{{2}}' ) { return; }
		const multiup = ev => {
						if (ev) { window.removeEventListener(ev.type, multiup, true); }
						try {
							const elem = document.querySelectorAll(selector);
							const elem2 = document.querySelectorAll(selector2);
							for (let i = 0; i < elem.length; i++) {
								elem[i].setAttribute('{{3}}', elem2[i].getAttribute('{{4}}'));
							}
						} catch { }
		};
		if (document.readyState === 'loading') {
		    	    window.addEventListener('DOMContentLoaded', multiup, true);
	   	} else {
		    	    multiup();
	   	}
})();
```

@Dhanamerdeka You can use that as userScript or add it as a custom scriptlet.

**Comment by CyberMan571** [comment] 2021-10-10 20:06
@Dhanamerdeka
Maybe, off-topic however useful: Please you can use Jdownloader
you can try  this without effort, without blocking ads. If you want.
`https://multiup.org/download/9fd4093c5c4940aebe317f1ad447c603/%5BAnime%20Time%5D%20Peter%20Grill%20to%20Kenja%20no%20Jikan%20%28Peter%20Grill%20and%20the%20Philosopher_s%20Time%29%20%28Season%201%29%20%5BUncensored%5D%5BBD%5D%5BDual%20Audio%5D%5B1080p%5D%5BHEVC%2010bit%20x265%5D%5BAAC%5D%5BEng%20Sub%5D.rar`

**Comment by CyberMan571** [comment] 2021-10-10 20:27
I found the Problem that big reCAPTCHA!
I will add an image downloading file.

**Comment by mapx-** [comment] 2023-03-09 14:41
for the initial issue

```
multiup.org##+js(ra, type, [type="hidden"], stay)
multiup.org##+js(ra, action, , stay)
```

You'll see the wanting link as text, just select it, right click, go to ...
No more redirecting to ad-page

**Comment by ghajini** [comment] 2023-03-13 13:54
@gorhill 
workaround https://github.com/uBlockOrigin/uAssets/issues/7897#issuecomment-1462177108 
was added https://github.com/uBlockOrigin/uAssets/commit/63b077434882148f19daabf21007ece1828af140
since at least no more ads redirection with this fix

please complete fix when you have time

**Closed** 2023-09-01 22:15 UTC
Labels: can't fix
