### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by Compare11** [uBlockOrigin/uAssets#15485] opened 2022-11-01 00:23 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/commerce/listing/5739697622735188/?media_id=4&ref=share_attachment`

### Category

ads

### Describe the issue

sorry for my bad english

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-01 005514](https://user-images.githubusercontent.com/117129335/199132851-5117512e-df82-4980-ab2d-2ccc0f668050.jpg)

![Screenshot 2022-11-01 005514](https://user-images.githubusercontent.com/117129335/199132933-c3885843-d66c-4f17-be1d-7b3eb6abca50.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 90339
  cosmetic: 42157
  scriptlet: 16589
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31855-63, 2d.13h.3m
    ublock-badware: 3947-0, 2d.13h.2m
    ublock-privacy: 288-0, 2d.12h.55m
    ublock-abuse: 76-0, 2d.12h.54m
    ublock-unbreak: 1888-0, 2d.12h.53m
    ublock-quick-fixes: 459-0, 10h.30m
    easylist: 62414-631, 2d.12h.51m
    easyprivacy: 30822-1717, 2d.12h.50m
    urlhaus-1: 11029-0, 10h.29m
    plowe-0: 3669-3, 2d.12h.48m
    DEU-0: 6007-2, 12h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 427 ms (selfie)
  maxAssetCacheWait: 147 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by gorhill** [comment] 2022-11-01 12:20
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/3367>.

**Closed by gorhill** 2022-11-01 12:20 UTC
