### ISSUE TITLE
fmovies.to: detection

### ISSUE THREAD

**Issue by minT2Sky** [uBlockOrigin/uAssets#10627] opened 2021-11-27 07:31 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://fmovies.to/?6`

### Category

detection

### Describe the issue

new problems

### Screenshot(s)

![image](https://user-images.githubusercontent.com/56858010/143672589-95c37eca-a0cf-4b88-acd7-7108c8df84bd.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80007
  cosmetic: 39202
  scriptlet: 16087
  html: 598
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/Sorrow-San/9anime-adblock-filters/-/blob/9e61e685aaa966aff3813f3ab6868ea364aea7c9/9Anime%20filter%20list.txt: 0-0, never
  default: 
    ublock-filters: 30195-27, 3d.17h.18m
    ublock-badware: 3430-1, 3d.17h.18m
    ublock-privacy: 183-0, 3d.17h.18m
    ublock-abuse: 70-0, 3d.17h.18m
    ublock-unbreak: 1701-0, 3d.17h.18m
    easylist: 60988-532, 3d.17h.18m
    easyprivacy: 26306-484, 3d.17h.18m
    urlhaus-1: 10514-0, 12h.10m
    plowe-0: 3699-3, 3d.17h.18m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 226
  launchFromSelfie: true
```
</details>

**Comment by ntnguyen1234** [comment] 2021-11-27 07:53
Have you forced update the lists as written in Prerequisites?

```
I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")
```
since it looks like the last update of your list was from 3 days ago.

**Comment by uBlock-user** [comment] 2021-11-27 08:00
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10547

**Closed by uBlock-user** 2021-11-27 08:00 UTC
