### ISSUE TITLE
deezer.com: ads

### ISSUE THREAD

**Issue by nappfun** [uBlockOrigin/uAssets#22440] opened 2024-02-11 09:11 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deezer.com/fr/profile/29206981/loved`

### Category

ads

### Description

De façon aléatoire, le visuel en bas de page marque "publicité" laissant penser qu'il y'en avait effectivement une, on ne l'entend pas, mais tout se bloque. Ca reste bloqué sur "publicité" et la musique ne continue plus. 
Obligé de rafraichir la page pour recommencer la lecture 

### Other extensions used

Aucune

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.1b27
Chromium: 121
filterset (summary):
 network: 141681
 cosmetic: 52356
 scriptlet: 20626
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 26760-39, now
  easylist: 80707-272, now
  easyprivacy: 50188-283, now
  plowe-0: 3783-1193, now
  ublock-badware: 7847-155, now
  ublock-filters: 37222-416, now
  ublock-privacy: 999-6, now
  ublock-quick-fixes: 256-26, now
  ublock-unbreak: 2212-36, now
  urlhaus-1: 7330-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms (selfie)
 maxAssetCacheWait: 176 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 157
 network:
  doubleclick.net: 8
  dzcdn.net: 15
  googletagmanager.com: 1
  gvt1.com: 8
  hubvisor.io: 7
  sentry.io: 112
  storage.googleapis.com: 2
  streamtheworld.com: 4
 extended:
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)
```
</details>

**Comment by ItsProfessional** [comment] 2024-02-11 09:13
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/22189, continue there.

**Closed by ItsProfessional** 2024-02-11 09:13 UTC
