### ISSUE TITLE
hotmovs.com + hclips.com [NSFW]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#4081] opened 2018-11-07 19:21 UTC
### URL(s) where the issue occurs

`[hotmovs.com + hclips.com]`

### Describe the issue

[both will open a new tab when clicking the play button on a video.]

### Versions

- Browser/version: [latest chrome version]
- uBlock Origin version: [1.17.0]

### Settings

- [default]

**Comment by okiehsch** [comment] 2018-11-07 19:40
I can't reproduce.

**Comment by gidgudmate** [comment] 2018-11-07 19:52
The popup is blocked for me but it starts like out.tubecorporate.com. there's a giant script for it in the html code dunno how to block it.

**Comment by okiehsch** [comment] 2018-11-07 19:53
I tried a few videos and I don't get any blocked popups, can you give an example link, so we are sure to talk about the same page.

**Comment by gidgudmate** [comment] 2018-11-07 20:02
Strange now I can't get it to pop anymore.

**Comment by gidgudmate** [comment] 2018-11-07 20:08
Seems the only way I can reproduce efficiently is if I use mobile. Suppose it can be closed if there's nothing appearing then.

**Comment by okiehsch** [comment] 2018-11-07 20:09
`out.tubecorporate.com` that popup is fixed by an existing filter and that giant script is an ExoLoader script and disabled by `hotmovs.com##+js(abort-on-property-read.js, ExoLoader)`.

**Comment by gidgudmate** [comment] 2018-11-07 20:11
Alright if it's blocked already guess this can be closed.

**Comment by okiehsch** [comment] 2018-11-07 20:14
You can close your own issue :)

**Closed by okiehsch** 2018-11-07 20:14 UTC
Labels: unable to reproduce
