### ISSUE TITLE
economictimes.indiatimes.com | Interstitial ad page

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4151] opened 2018-11-19 11:25 UTC
### URL(s) where the issue occurs

`https://economictimes.indiatimes.com`

### Describe the issue

An interstitial ad page `https://economictimes.indiatimes.com/configspace/etmain_static/content/defaultinterstitial.html` stays for a few seconds before redirecting to the actual homepage. This doesn't happen every time. I think it checks for cookies before triggering this interstitial page. But not sure if that's the only thing it checks for because strangely, at times, this may not be easy to reproduce even in private browsing mode. Also, sometimes, the interstitial comes on despite loading the site back to back with cookies enabled.

### Versions

- Browser/version: Firefox 63.0.3
- uBlock Origin version: 1.17.2

### Settings

Default ad filter, Annoyances filter

**Comment by uBlock-user** [comment] 2018-11-19 19:09
`economictimes.indiatimes.com##+js(abort-on-property-read.js, intsFequencyCap)` works for me.

**Comment by okiehsch** [comment] 2018-11-19 20:31
I can't reproduce, maybe it depends on the geo-location, but if it works fine for both of you and does not break anything I will add it to `uBO-annoyances`.

**Comment by in4u** [comment] 2018-11-19 20:38
@okiehsch Yes, please close it for now. If I see that page again, then this issue may be re-opened.

**Comment by ghajini** [comment] 2018-11-20 07:17
Present on 
`timesofindia.indiatimes.com`

**Comment by uBlock-user** [comment] 2018-11-20 07:41
@ghajini try - `timesofindia.indiatimes.com##+js(abort-on-property-read.js, istial)`

**Comment by ghajini** [comment] 2018-11-20 08:36
@uBlock-user , the filter breaks page(undisclosed things, one of them 
is )commentss
 doesn't load at all

**Comment by uBlock-user** [comment] 2018-11-20 08:53
They're using `window.location.replace` to caue a redirection, and that property can't be modified, so this is the only one I know.

**Comment by in4u** [comment] 2018-11-20 11:58
>the filter breaks page(undisclosed things, one of them is) comments doesn't load at all

I tested again and noticed similar problem with original fix, .e.g. on `https://economictimes.indiatimes.com/wealth/save/banks-continue-mis-selling-financial-products-heres-what-you-must-know-to-protect-yourself/articleshow/66664488.cms`. But in my case, it's not easy to reproduce and the behaviour is erratic. Like sometimes the comment button requires to be clicked twice while at times comments don't load at all despite multiple clicks, but mostly the comments load just fine. Weird!

On `timesofindia.indiatimes.com`, this problem is much easier to reproduce with @uBlock-user's `timesofindia.indiatimes.com##+js(abort-on-property-read.js, istial)` filter. @ghajini Perhaps you should open a separate issue for that site.

Or maybe this issue can be re-opened to see if a common problem-free workaround could be found since both these sites have similar issues and belong to the same parent group?

**Comment by ghajini** [comment] 2018-11-20 12:09
Yes they all belong to times India network

**Comment by uBlock-user** [comment] 2018-11-20 12:15
Another option is insert cookies which are being looked up, so that would bypass the interstitial, but that's not gonna happen, so the only option left is a doublededged sword filter.

**Comment by mapx-** [comment] 2018-11-20 12:56
So, should we remove the filter due to breaking commenting system ?

**Comment by ghajini** [comment] 2018-11-20 13:01
Filter committed by okiehsch works, no need to remove filter.......only if I add filter suggested by ublock user for timesofindia , comments breaks

**Comment by uBlock-user** [comment] 2018-11-20 13:31
https://timesofindia.indiatimes.com/videos/jquery_1_11_0_min/version-14,minify-1.cms

That's the script if you want to take a stab at it.

**Closed** 2018-11-29 08:51 UTC

**Comment by PIZZA90** [comment] 2022-05-03 22:18
`https://economictimes.indiatimes.com/topic/football`

something annoying here.. The site detected that you are going to leave it and popup appears, if you move the mouse-cursor out of the website 🤣🤣

You can close the popup but.. scrolling down or top of the page .. appears again moving the cursor to the browser ( see picture in green )

![Captu123ra](https://user-images.githubusercontent.com/33556647/166574762-1c2228fb-db4e-4b1d-b59a-b6d934567c8e.PNG)

**Comment by ghajini** [comment] 2022-05-04 02:22
it's site content
