### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by jiuyuezhihou** [uBlockOrigin/uAssets#10648] opened 2021-11-28 17:57 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.bilibili.com/video/BV1H3411b7GF?spm_id_from=333.851.b_7265636f6d6d656e64.1`

### Category

breakage

### Describe the issue

把评论都给拦截了，不显示评论

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 96886
  cosmetic: 49133
  scriptlet: 16228
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 26772-86, 5h.39m
    easylist: 61199-11, 9h.56m
    easyprivacy: 26372-43, 9h.54m
    plowe-0: 3685-811, 13d.1h.13m
    ublock-abuse: 74-0, 9h.52m
    ublock-badware: 3468-58, 9h.50m
    ublock-filters: 29678-141, 9h.47m
    ublock-privacy: 189-1, 9h.45m
    ublock-unbreak: 1698-39, 9h.43m
    urlhaus-1: 10443-0, 5h.36m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
  triggered: 
    no-csp-reports: * true
modifiedUserSettings: 
  contextMenuEnabled: false
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 265
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment] 2021-11-28 18:12
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10641

**Closed by uBlock-user** 2021-11-28 18:12 UTC

**Comment by gorhill** [comment] 2021-11-28 18:19
> - [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)

**Comment by iam-py-test** [comment] 2021-11-28 18:54
@jiuyuezhihou please search for related issues before opening a new one
