### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by sk42git** [uBlockOrigin/uAssets#14129] opened 2022-07-25 16:08 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

Completely breaks mouseover/hover menus on comments. (The element looks like 3 vertically-stacked dots, and appears in the upper-right of every comment's content frame on mouseover). The element is non-interactive with uBO enabled. Still happens on fresh, unmodified installs of FF/WF running nothing but stock uBO; tested on 2 systems.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 78
filterset (summary): 
  network: 79979
  cosmetic: 46240
  scriptlet: 20381
  html: 707
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4505-4, 1d.20h.13m
  default: 
    user-filters: 23-1, never
    ublock-filters: 32890-47, 3d.15h.33m
    ublock-badware: 4208-0, 3d.15h.32m
    ublock-privacy: 232-0, 12d.14h.56m
    ublock-abuse: 76-0, 12h.35m
    ublock-unbreak: 1849-0, 3d.15h.31m
    ublock-quick-fixes: 246-0, 16h.29m
    easylist: 68713-572, 3d.15h.30m
    easyprivacy: 27432-594, 3d.15h.29m
    urlhaus-1: 4880-0, 22h.8m
    plowe-0: 3645-3, 3d.15h.34m
filterset (user): [array of 23 redacted]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 1266 ms (selfie)
  maxAssetCacheWait: 297 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    youtube.com: 9
    doubleclick.net: 2
    google.com: 1
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by Procyon-b** [comment] 2022-07-25 16:29
Works for me. Please update your filter lists. Some of them are more than 3 days old.
Open ublock's dashboard, go to "Filter lists" tab, click "Purge all caches", then click "Update now". Retry yt.

**Comment by mapx-** [comment] 2022-07-25 16:53
> Firefox: 78

@sk42git you should try a more updated browser

**Comment by krystian3w** [comment] 2022-07-25 17:27
Duplicate of #7636

**Comment by krystian3w** [comment] 2022-07-25 17:28
Also start test with disable 1 by 1 these scriptlets: https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1193821774

**Comment by Procyon-b** [comment] 2022-07-25 17:38
@sk42git I've just tested with a clean (latest) FF profile, and the 3-dot menu on comments works for me.
I suppose that you're logged in when you try to see the menu?

**Comment by MasterKia** [comment] 2022-07-26 08:18
> ... did neither of you read my issue report?

Did _you_ read the **Prerequisites**?

> * [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

ALL youtube.com issues => `https://github.com/uBlockOrigin/uAssets/issues/7636`

**Closed** 2022-07-26 10:05 UTC
Labels: unable to reproduce
