### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by RebornTGW** [uBlockOrigin/uAssets#18367] opened 2023-06-02 17:58 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

Advert on twitch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 112618
 cosmetic: 48013
 scriptlet: 17771
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  FRA-0: 28591-33, 2d.23h.21m
  easylist: 66666-436, 2d.23h.21m
  easyprivacy: 31617-338, 2d.23h.21m
  plowe-0: 3724-959, 2d.23h.21m
  ublock-abuse: 69-1, 2d.23h.20m
  ublock-badware: 7180-146, 2d.23h.20m
  ublock-filters: 33470-189, 2d.23h.20m
  ublock-privacy: 380-74, 2d.23h.20m
  ublock-quick-fixes: 184-20, 54m
  ublock-unbreak: 2023-38, 2d.23h.20m
  urlhaus-1: 6942-0, 54m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1580 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel: 
 blocked: 3
 network: 
  amazon-adsystem.com: 3
```
</details>

**Comment by iam-py-test** [comment] 2023-06-02 18:50
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by mapx-** [comment] 2023-06-02 18:52
see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts

**Closed** 2023-06-02 18:51 UTC
