### ISSUE TITLE
https://www.interpals.net/

### ISSUE THREAD

**Issue by kolor33** [uBlockOrigin/uAssets#7876] opened 2020-09-05 14:26 UTC
Hi what I will block this information after I reload page the information back.How to block this script.
=================
You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.
=================

**Comment by uBlock-user** [comment] 2020-09-05 14:27
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7874

Already fixed, force update uBlock Filters in few mins.

**Closed by uBlock-user** 2020-09-05 14:27 UTC
