### ISSUE TITLE
motobanda.pl

### ISSUE THREAD

**Issue by F4z** [uBlockOrigin/uAssets#71] opened 2016-06-28 10:46 UTC
Google Chrome 51.0.2704.106 m (64-bit)
uBlock Origin 1.7.6

Is there any way to skip/remove/block ads before video on this website? - `http://motobanda.pl/motocyklista-uderza-w-jelenia-na-drodze`

To reproduce, click play button on video and you will see ads.

![image](https://cloud.githubusercontent.com/assets/11742596/16411105/c77f317e-3d25-11e6-94ca-659cc4478306.png)

I tried this rule `||motobanda.pl/uploads/avid/*.mp4$media,` but it does not work, because with this rule video does not play.

I observed that after ads, this element `id="mvideo"` changes `z-index` from `-1` to `1`.
So it would be nice if uBlock had an option to change style for elements on websites, something like Adguard has - https://adguard.com/en/filterrules.html#cssInjection

With Adguard I can change style for this element using this rule - `motobanda.pl#$#body #mvideo { z-index: 1!important; }` 
and I can watch video on this website without ads.

With this it would be also possible to skip timer on some other websites, for example here - `http://gahe.pl/graonline,17859,boom-bad-piggies-wysadzanie-%C5%9Bwi%C5%84`
Now I must wait 20 seconds to play a game.
![image](https://cloud.githubusercontent.com/assets/11742596/16411404/2bfc478a-3d27-11e6-8653-1eb5b45ec87d.png)
If it would be possible to change style for elements, I could play a game immediately.
As an example again rule for Adguard - `gahe.pl#$#body #flashgame { display: block!important; }`

and here - `http://alltube.tv/film/minionki-the-minions-2015/27966`
I must wait about 10 seconds to watch video.
![image](https://cloud.githubusercontent.com/assets/11742596/16411716/c502c87c-3d28-11e6-9c9b-4ecf54b98285.png)
With this rule I can skip this - `alltube.tv#$#body #iframe-container { display: block!important; }`

and here -  `http://www.vipfullhdfilmizle.org/13-saat-bingazinin-gizli-askerleri-turkce-dublaj-izle/2/`
I must wait about 6 seconds to skip ads.
![image](https://cloud.githubusercontent.com/assets/11742596/16411944/f598aca8-3d29-11e6-8a87-067d11fc6a75.png)
With these rules I can skip this:
`vipfullhdfilmizle.org###VideOnrekLam`
`||savoy.storage.cubecdn.net/bm/vipfullhdfilmizle/*.mp4`
`vipfullhdfilmizle.org#$#body #kendisi{ display: block!important; }`

So it would be nice if uBlock Origin had an option to change css style for elements on websites.
Or maybe someone have an idea how to skip/remove/block ads/timer using uBlock Origin on these websites without changing css style?

**Comment by gorhill** [comment] 2016-06-28 11:57
> With Adguard I can change style for this element using this rule - `motobanda.pl#$#body #mvideo { z-index: 1!important; }` and I can watch video on this website without ads.

I wonder if removing the DOM element containing the ad would be better approach -- I have been pondering offering a syntax extension to remove DOM node for the next release. If you remove the DOM element related to the ad using your browser inspector, does it seem to give good result?

**Comment by F4z** [comment] 2016-06-28 12:17
Thank you for answer.
If I remove this element `class="avideo pointer video-js vjs-default-skin special-image"` I can not play video, because is not clickable.

![image](https://cloud.githubusercontent.com/assets/11742596/16414753/d630d182-3d39-11e6-94fa-325cf48d46e8.png)

![image](https://cloud.githubusercontent.com/assets/11742596/16414886/a5c907e8-3d3a-11e6-812f-ad9fcd2912a0.png)

But if I change `id="mvideo"` to `id=""` or any other, for example `id="video"` I can watch video without ads.

**Comment by gorhill** [comment] 2016-06-28 12:41
>  I can not play video, because is not clickable.

Yes, because the `z-index` is -1, which I suppose send the element behind everything on the page. So a good solution for this specific case would be:

- Ability to remove the video ad-related DOM element (to prevent it from playing even from behind other DOM elements).
- Ability to re-style the main video content as AdGuard does. I have an [opened issue to support this](https://github.com/gorhill/uBlock/issues/781), and it maybe just be the time to implement this given the syntax extension I added for the next release. I probably won't officially adopt AdGuard's syntax (I prefer `:style()`-like because this fits better uBO's internals), but I will surely make uBO able to compile AdGuard filters.

**Comment by F4z** [comment] 2016-06-28 14:31
It sounds great, so I am waiting for this.

I have one more question, because I have problem to block element on this website - `http://www.purepc.pl/`

Default filter lists + Anti-Adblock Killer | Reek +  POL: polskie filtry do Adblocka i uBlocka‎

I want to block background ads (you must wait about 5 seconds to see this):
![image](https://cloud.githubusercontent.com/assets/11742596/16418311/876a631e-3d49-11e6-8565-a6b7c4e496b8.png)

I added these rules:
`||purepc.pl/themes/2k14/b64.php`
`purepc.pl##a[href^="http://www.purepc.pl/redir.php"]`

and I do not see background image, but after I reload website and wait about 5 seconds, left and right side is still clickable.
So it looks like that this element `##a[href^="http://www.purepc.pl/redir.php"]` is again visible after about 5 seconds.

I think, in this case changing style for element will be also useful, for example:
`a[href^="http://www.purepc.pl/redir.php"] { height: 0px!important; }`
or maybe you have idea how to block this elemnt without changing style?

**Comment by gorhill** [comment] 2016-06-28 14:42
> So it looks like that this element `##a[href^="http://www.purepc.pl/redir.php"]` is again visible after about 5 seconds.

Yes, the site revisit the element's style to force `display: block;`. Being able to remove or re-style the node would solve this one.

**Comment by gorhill** [comment] 2016-06-28 14:45
Is `purepc.pl` a high traffic site? I can see the site is working hard to counter blocker, there is even some code in there which sound like it's specifically made for uBO (`ubo_fix`). For such site, injecting a scriptlet to defuse the bad js might be what is needed.

**Comment by F4z** [comment] 2016-06-28 15:10
> Is purepc.pl a high traffic site?

This site is on 1,202 position in Poland in Alexa Traffic Ranks - `http://www.alexa.com/siteinfo/purepc.pl`, so I think it is a popular website.

**Comment by gorhill** [comment] 2016-06-28 15:23
Also, the Polish filter list maintainer should add the following exception cosmetic filter: `purepc.pl#@#.reklama`. The other one (`purepc.pl#@#[class*="reklama"]`) in the "Anti Adblock Rules" section does is not enough.

**Comment by F4z** [comment] 2016-06-28 15:42
Polish filter list maintainer sends all "anti adblock" rules to reek - https://github.com/reek/anti-adblock-killer/issues/1309
So he probably forgot to delete this rule.

**Comment by gorhill** [comment] 2016-06-29 22:05
With 1.7.7b4, the following filters work:

    motobanda.pl#$##mvideo { z-index: 1 !important; }
    motobanda.pl##.avideo

**Comment by F4z** [comment] 2016-06-29 22:05
Great, thank you for the new beta version with "Support cosmetic filters with explicit style properties".
I have question, because I observed that if I add two style rules only one works (the latest added).
For example here - `http://motobanda.pl/motocyklista-uderza-w-jelenia-na-drodze`
I added these rules:
`motobanda.pl###mvideo:style(z-index: 1!important)`
`motobanda.pl##body:style(background: black!important)`
So is it by desing or a bug?

**Comment by gorhill** [comment] 2016-06-29 22:08
It's a bug, will fix asap.

**Comment by F4z** [comment] 2016-06-29 22:10
Ok, thank you.

**Comment by gorhill** [comment] 2016-06-29 22:15
Fixed in 1.7.7b5.

**Comment by F4z** [comment] 2016-06-29 22:20
Yes, now it works properly, thank you again :smiley:

**Comment by gorhill** [comment] 2016-07-04 16:34
Did `motobanda.pl` change their site? I am trying to reproduce the issue there, and I don't see it anymore despite not having the re-styling filters above.

**Comment by F4z** [comment] 2016-07-05 13:12
I am on vacation and I do not have access to my computer (I have only smartphone), so I can not check this. I will be back in two weeks and then I check this and answer for your question.

**Comment by F4z** [comment] 2016-07-18 10:58
Ok, I came back.
Yes, `motobanda.pl` changed their website, no ads before video now.

By the way, can you readd [noopmp4](https://github.com/uBlockOrigin/uAssets/commit/b818a79105a75c55e3dc4286662b49ed02f6bee3), because I want to test something, please?

**Comment by F4z** [comment] 2016-08-07 13:52
Hi, these ads are again - `http://motobanda.pl/honda-nsr-125r-1996-2001`
so, can you add this rule `motobanda.pl###mvideo:style(z-index: 1!important;)` to "uBlock filters‎", or maybe should I only add this to "My filters"?

**Closed** 2016-08-07 13:57 UTC

**Comment by F4z** [comment] 2016-08-07 13:59
Thank you.
