### ISSUE TITLE
Tab closes when clicking on Link

### ISSUE THREAD

**Issue by MuenchenSued** [uBlockOrigin/uAssets#8124] opened 2020-10-31 10:57 UTC
### URL(s) where the issue occurs
`https://xhamster.com/hd` (Adult website)

### Describe the issue
When you start at this page and click one video with middle mouse button, this video is sent to a new tab. Now go to the bottom of the first page without changing the tab and click the NEXT button. Instead of opening the next page, this tab closes. Maybe you've to try it twice.

### Versions
- Browser/version: Firefox 82.0
- uBlock Origin version: v1.30.6

### Settings
I made some private filters but removed them for this test.
All five uBlock filters are enabled.
The effect is gone after disabling uBlock filters and comes back again when enabled.

### Notes
I can send you logs, if necessary, but unfortunately the protocol seems not to show important messages. It could also be possible, that the other uBlock filters (Badware, Privacy, Unbreak) are involved, because when I only enable the first uBlock filter, I was not able to reproduce this issue.

**Comment by uBlock-user** [comment] 2020-10-31 11:02
try `*$popunder,domain=xhamster.*,badfilter`

**Comment by MuenchenSued** [comment] 2020-10-31 11:03
![Settings](https://user-images.githubusercontent.com/71550657/97777476-c2989a00-1b70-11eb-960a-44fd966e33ba.png)

**Comment by uBlock-user** [comment] 2020-10-31 11:11
Why close it ? The issue hasn't been addressed yet.

**Comment by MuenchenSued** [comment] 2020-10-31 11:55
I don't intended to close this issue, just to cancel a reply. But unfortunately there is no cancel button available and I did not understand, what "Close with comment" meant - no I got it. Thanks for re-opening.
I entered your text in my personal filters and the first tries look good. Thank's for the quick support.

**Comment by uBlock-user** [comment] 2020-10-31 12:48
fixed, force update uBlock Filters list.

**Comment by MuenchenSued** [comment] 2020-10-31 13:05
Looks good.

**Comment by ghajini** [comment] 2020-10-31 14:11
@uBlock-user popups on mirror `https://xhamster5.desi/hd`

**Closed** 2020-10-31 14:43 UTC

**Comment by dportvine** [comment] 2024-06-21 06:12
I have another problem.

Search on Google - erotic xhamster, then open any link in a new tab.

Rule `*$popunder,3p,from=xhamster.*` from ~> **uBlock filters – Ads**, closes the Google tab.

<details>
<summary>Screen</summary>

![2024-06-21_085918](https://github.com/uBlockOrigin/uAssets/assets/111344219/a9aaa577-bb3f-4813-8edc-59f22c3498f0)
</details>

<details>
<summary>Video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/46af3212-347b-4134-a718-0e8e43356a6d
</details>

**Comment by stephenhawk8054** [comment] 2024-06-21 06:30
@gorhill I can reproduce on chromium incognito when accessing `https://www.google.com/search?q=erotic+xhamster` directly. Looks like it happens when I scroll down right after opening in new tab, and the URL changes to `https://www.google.com/search?q=erotic+xhamster#ip=1` (with `#ip=1` added).

I'm not really sure what happens as this is the 1st time I see it, `popunder` affects the current active tab with another tab loading in background?

**Comment by gorhill** [comment] 2024-06-21 15:21
I guess the code should ignore changes in `hash` part of the URL.
