### ISSUE TITLE
pks.raenonx.cc: detection

### ISSUE THREAD

**Issue by Zexxx** [uBlockOrigin/uAssets#21353] opened 2023-12-11 21:23 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pks.raenonx.cc/en`

### Category

detection

### Description

The new update brought the large, heavy banners back with a delay this time. 
A nuisance popup at the bottom of the page is also timed before it lowers itself. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![msedge_RCn50pk09t](https://github.com/uBlockOrigin/uAssets/assets/21136842/9364acec-2ae9-4ad0-8494-4e90c666f937)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104526
 cosmetic: 43995
 scriptlet: 19491
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75374-16, now
  easyprivacy: 33094-65, now
  plowe-0: 3777-1148, now
  ublock-badware: 7606-138, now
  ublock-filters: 35889-181, now
  ublock-privacy: 935-12, now
  ublock-quick-fixes: 185-13, now
  ublock-unbreak: 2157-31, now
  urlhaus-1: 10745-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 287 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(no-setTimeout-if, adsFound)
```
</details>

**Comment by JobcenterTycoon** [comment] 2023-12-11 21:50
A note: you don’t need to open duplicates. Just write a comment here when you get a issue with this site again, we will get a notification.

**Comment by Zexxx** [comment] 2023-12-20 20:11
New detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>



![cw2ZXrBQ](https://github.com/uBlockOrigin/uAssets/assets/21136842/f77410e3-fd95-43fe-ab8e-b4346997aeb7)


</details>


### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 121
filterset (summary):
 network: 106532
 cosmetic: 44178
 scriptlet: 19728
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76117-16, now
  easyprivacy: 33123-65, now
  plowe-0: 3782-1151, now
  ublock-badware: 7648-138, now
  ublock-filters: 36458-345, now
  ublock-privacy: 951-12, now
  ublock-quick-fixes: 103-5, now
  ublock-unbreak: 2176-32, now
  urlhaus-1: 11990-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 272 ms (selfie)
 maxAssetCacheWait: 104 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##div[class^="relative w-full overflow-hidden"]:has(> .absolute …
  ##ins.adsbygoogle
  ##div[class="flex flex-col w-full info-section-opaque fixed bott…
  ##+js(no-setTimeout-if, adsFound)
  ##+js(no-setInterval-if, isBlocked)```

**Comment by JobcenterTycoon** [comment] 2023-12-20 20:41
I moved the filter to the annoyance list.

**Comment by Zexxx** [comment] 2023-12-21 22:47
This solution has drawbacks that can become visually jarring due to a rapid flicker due to the detection script creating the element again and then uBO deleting the element again.
This will be more noticeable on slower browsers or slower devices due to the element flicker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>



msedge

![flicker](https://github.com/uBlockOrigin/uAssets/assets/21136842/29381029-4d6b-4ed7-b8fe-f7e0640ccb15)

Firefox stable

https://github.com/uBlockOrigin/uAssets/assets/21136842/165aebd6-4254-4992-bdba-33a3192a04f1



</details>

### Configuration

<details>
msedge

```yaml
uBlock Origin: 1.54.0
Chromium: 121
filterset (summary):
 network: 105853
 cosmetic: 45909
 scriptlet: 24105
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6373-11, now
 default:
  user-filters: 0-0, never
  easylist: 76196-16, now
  easyprivacy: 33136-65, now
  plowe-0: 3785-1152, now
  ublock-badware: 7668-138, now
  ublock-filters: 36486-345, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 109-5, now
  ublock-unbreak: 2177-34, now
  urlhaus-1: 10910-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 272 ms (selfie)
 maxAssetCacheWait: 104 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##div[class="flex flex-col w-full info-section-opaque fixed bott…
  ##div[class^="relative w-full overflow-hidden"]:has(> .absolute …
  ##+js(no-setTimeout-if, show)
  ```
  
 Firefox stable
 
```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 105859
 cosmetic: 45834
 scriptlet: 23721
 html: 1346
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6329-11, 4m
 default:
  user-filters: 0-0, never
  ublock-filters: 37374-361, 4m
  ublock-badware: 7672-11, 4m
  ublock-privacy: 948-4, 4m
  ublock-unbreak: 2223-2, 4m
  ublock-quick-fixes: 126-0, 4m
  easylist: 76196-548, 4m
  easyprivacy: 33136-852, 4m
  urlhaus-1: 10910-0, 4m
  plowe-0: 3785-1, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1473 ms
 maxAssetCacheWait: 4 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##div[class="flex flex-col w-full info-section-opaque fixed bott…
  ##div[class*="bg-red-"]:has(> div[class="flex h-full w-full flex…
  ##div[class^="relative w-full overflow-hidden"]:has(> .absolute …
  ##+js(no-setTimeout-if, show)
  ```

**Comment by JobcenterTycoon** [comment] 2023-12-21 23:00
The anti adblock notice is hardcoded now and getting removed when no adblock got detected.

But i can take a look on the next day.

**Comment by JobcenterTycoon** [comment] 2023-12-22 13:58
They changed it back to the old behavior. Pretty sure the web dev was annoyed too.

**Comment by rlpplr** [comment] 2024-03-23 19:20
Anti-adblock notice appears again, tested with clean Chrome profile + clean uBO installation + enabled "uBlock filters - Annoyances"
### Screenshot
<details><summary>Screenshot</summary>
<p>

![Screenshot_20240323_200224](https://github.com/uBlockOrigin/uAssets/assets/55020069/62c9a5a4-2d70-46fa-8b8b-cc09d152f351)

</p>
</details> 

### Configuration
<details><summary>Details</summary>
<p>

```
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 127125
 cosmetic: 47593
 scriptlet: 25140
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6938-29, 11m
 default:
  user-filters: 0-0, never
  easylist: 83101-16, 11m
  easyprivacy: 50402-8, 11m
  plowe-0: 3763-1182, 11m
  ublock-badware: 8062-146, 11m
  ublock-filters: 37449-363, 11m
  ublock-privacy: 786-5, 11m
  ublock-quick-fixes: 243-39, 11m
  ublock-unbreak: 2248-34, 11m
  urlhaus-1: 8840-0, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 574 ms (selfie)
 maxAssetCacheWait: 109 ms
 cacheBackend: browser.storage.local
```

</p>
</details>

**Comment by wing0718** [comment] 2024-03-26 08:38
They changed again, the page is now blank with #21353 code

**Comment by RaenonX** [comment] 2024-03-27 06:49
I am the nearly-sole (contributed 90% or even more) contributor, and the owner of this website.

First of all, I am not against the uBO devs, so please don't treat me as hostile.

@rlpplr @wing0718 Sorry for the ping, if this disturbed you, but please stop reporting, for both parties benefit. If you guys are open for communication, please check https://pks.raenonx.cc/en/docs/view/site/ads-and-credits for my reasoning. I am open to any further communication, if you guys are open as well. I am fine communicating over this either on here, or in our Discord. Not posting the link here to avoid suspicious promotion, link is available somewhere on the website.

**Comment by JobcenterTycoon** [comment] 2024-03-27 11:19
The developer circumventing filter of a single content blocker from a filterlist which is not even enabled by default so it don’t affect most users at all.

I will monitor the site.

**Comment by Zexxx** [comment] 2024-03-27 22:11
The developer has broken the site for anyone blocking ads ;p

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 127717
 cosmetic: 47687
 scriptlet: 25117
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6935-31, never
 default:
  user-filters: 0-0, never
  easylist: 83920-137, now
  easyprivacy: 50409-10, now
  plowe-0: 3763-1182, now
  ublock-badware: 7987-140, now
  ublock-filters: 37387-359, now
  ublock-privacy: 780-5, now
  ublock-quick-fixes: 247-35, now
  ublock-unbreak: 2247-33, now
  urlhaus-1: 8930-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1116 ms
 maxAssetCacheWait: 6 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
 extended:
  ##+js(prevent-fetch, /doubleclick|ads/, length:10)

```
  </details>
  
 <details>
 <summary>Screenshot</summary>
  
![image](https://github.com/uBlockOrigin/uAssets/assets/21136842/4b7f9c66-2dfc-4906-afed-7020ffa479c2)

</details>

**Comment by JobcenterTycoon** [comment] 2024-03-27 22:24
I know, updated 40 minutes ago already https://github.com/uBlockOrigin/uAssets/commit/cd02b826ddd58c06303dce65e71c9624d0579367. To get the latest filter run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1

**Comment by aradon83** [comment] 2024-04-09 20:49
Can confirm issue has once again appeared with Ublock filter annoyance enabled. Ublock fully updated as well

Screenshot 
![Screenshot 2024-04-09 144631](https://github.com/uBlockOrigin/uAssets/assets/166557469/2e92d875-75b7-4b9f-8260-bd0af8ea1f8e)

**Comment by Zexxx** [comment] 2024-04-12 23:51
New nag bar and popup annoyance due to "detection."

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 120
filterset (summary):
 network: 132071
 cosmetic: 47823
 scriptlet: 25191
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6933-27, 1h.5m Δ
 default:
  user-filters: 0-0, never
  easylist: 85268-438, 1h.5m Δ
  easyprivacy: 50480-2, 1h.5m Δ
  plowe-0: 3739-790, now
  ublock-badware: 8070-0, 1h.5m Δ
  ublock-filters: 37437-409, 1h.5m Δ
  ublock-privacy: 792-2, 1h.5m Δ
  ublock-quick-fixes: 157-0, 2m
  ublock-unbreak: 2246-19, 1h.5m Δ
  urlhaus-1: 11800-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1015 ms
 maxAssetCacheWait: 203 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##div[class^="flex flex-row w-full h-full"]:has(.adsbygoogle)
  ##body > div[class] > [class="flex flex-col w-full"]:has(> butto…
  ##body > div[class] > style:first-child + .w-full:has(> .button-…
  ##ins.adsbygoogle[data-ad-slot]
  ##.adsbygoogle-noablate

```
  </details>
  
 <details>
 <summary>Screenshot</summary>
  
![image](https://github.com/uBlockOrigin/uAssets/assets/21136842/744ca6ef-aa81-41bc-8c3f-50bc9a39e44a)


</details>

**Comment by shorax** [comment] 2024-04-15 12:29
They've now done that if you have nuisances enabled the popups with pokemon in them dont pop up.... rendering the site unsuable.

**Comment by JobcenterTycoon** [comment] 2024-05-10 09:56
Can’t reproduce the breakage, fixed the Ad-Shield one.

**Comment by Anybody368** [comment] 2024-05-12 19:12
Hello, first time here

For the past week or so, navigating on the website has been less than pleasant. After the usual delay, the error message for using uBlock Origin pops up, and get immediately deleted.

But then, it pops back up the very next frame at a different place, and the cycle goes on indefinitely until reloading the page altogether. Otherwise I can still technically browse the website through internal buttons, but scrolling is deactivated. (I never touched uBlock settings such as filter lists or whatever)

![image](https://github.com/uBlockOrigin/uAssets/assets/159350615/946325e9-f1b7-41fe-8369-4fe76c41ce17)

**Comment by JobcenterTycoon** [comment] 2024-05-12 20:37
Reproduced when i force the anti adblock. Fixed now. https://github.com/uBlockOrigin/uAssets/commit/e7af95af045eb03f75e32dab4d93851b03d4b072

**Comment by Huwarf** [comment] 2024-05-19 06:24
After the recent commit [e7af95a](https://github.com/uBlockOrigin/uAssets/commit/e7af95af045eb03f75e32dab4d93851b03d4b072), the "Add Pokémon"-button is broken after the popup loads once. This happens since both the "Add Pokémon" interface and the popup shares the same elements.
This is a proposed fix for the issue: https://github.com/uBlockOrigin/uAssets/pull/23756

**Comment by JobcenterTycoon** [comment] 2024-05-19 13:36
https://github.com/uBlockOrigin/uAssets/pull/23756 it was the gear button (only relevant if a detection occurs but i can’t reproduce without forcing the anti adblock with `$important` filters)

**Comment by Huwarf** [comment] 2024-05-19 14:00
My apoligies for the unclear description. I'll document this for the future.

In the leftmost menu under "Team" -> "Pokémon Box" there a button called "Add Pokémon", this is the buttom I'm speaking of.
Since you need to login to see this feature I've attached screenshots below.

How to access the "Add Pokémon"-button:
![image](https://github.com/uBlockOrigin/uAssets/assets/170199782/404bdfd4-bbe8-458d-8f02-cf46df99b764)

When you click on it:
![image](https://github.com/uBlockOrigin/uAssets/assets/170199782/6766f688-b3b0-45be-90ed-19c7c3f631e2)

I would like to confirm that it also effected the gear button mentioned above but since that feature is seldom used I didn't notice it.

**Comment by CrystalLuna** [comment] 2024-05-29 17:05
The developer updated their code again:

![raenonx-ads](https://github.com/uBlockOrigin/uAssets/assets/171175055/fefccbfc-f3f2-4dc4-907e-1f15dd999c71)

**Comment by Oqarshi** [comment] 2024-06-05 07:30
Just a note, using adguard + ublock origin + microshield fixes the website and all the function. but there is still this annoying message.
![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/0b2f5027-2bcf-4a51-86b5-074ac9ae79bb)

**Closed** 2024-07-25 23:58 UTC
Labels: ongoing, Ad-Shield

**Comment by Zexxx** [comment] 2024-10-08 02:58
New detection popup, this is random and can simply not appear sometimes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>



![image](https://github.com/user-attachments/assets/ebb9d12a-d354-41c2-8386-0f6229a35b3a)


</details>


### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 151015
 cosmetic: 50151
 scriptlet: 26773
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5987-12, 3m
 default:
  user-filters: 0-0, never
  easylist: 85792-476, 3m
  easyprivacy: 53135-638, 3m
  plowe-0: 3541-0, 3m
  ublock-badware: 11579-6, 3m
  ublock-filters: 40391-364, 3m
  ublock-privacy: 1305-22, 3m
  ublock-quick-fixes: 170-0, 3m
  ublock-unbreak: 2471-20, 3m
  urlhaus-1: 25255-0, 3m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 496 ms
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  nitropay.com: 2
 extended:
  ##div[class="fixed bottom-0 z-anchor w-full bg-slate-500"]:has(>…
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(no-setTimeout-if, error-report.com)```
