### ISSUE TITLE
tii.la: detection

### ISSUE THREAD

**Issue by maximarus** [uBlockOrigin/uAssets#18292] opened 2023-05-29 09:09 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/rS9fp`

### Category

detection

### Description

This website told me "Please disable Adblock to proceed to the destination page."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93849
 cosmetic: 38984
 scriptlet: 17591
 html: 942
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34091-62, 2d.18h.42m
  ublock-badware: 7133-0, 4d.15m
  ublock-privacy: 442-0, 6d.23h.55m
  ublock-abuse: 70-70, 6d.23h.54m
  ublock-unbreak: 2025-2, 4d.14m
  ublock-quick-fixes: 334-0, 9h.53m
  easylist: 66604-665, 18h.9m
  easyprivacy: 31807-606, 3d.22h.13m
  urlhaus-1: 6700-0, 20h.10m
  plowe-0: 3724-3, 5h.51m
filterset (user): [empty]
trustedset: 
 added: [array of 12 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 238 ms (selfie)
 maxAssetCacheWait: 102 ms
popupPanel: 
 blocked: 9
 no-scripting: true
 network: 
  tii.la: 3
  e2ertt.com: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  ophoacit.com: 1
  trustbummler.com: 1
```
</details>

**Comment by okiehsch** [comment] 2023-05-29 09:12
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18268

**Closed by okiehsch** 2023-05-29 09:12 UTC
