### ISSUE TITLE
freemcserver.net

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9522] opened 2021-07-02 17:46 UTC
anti adb

**Comment by uBlock-user** [comment] 2021-07-02 17:49
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/9522

**Closed by uBlock-user** 2021-07-02 17:49 UTC

**Comment by IThinkIAmCool** [comment] 2021-07-02 17:51
Could you test in Opera with its built-in VPN?

**Comment by uBlock-user** [comment] 2021-07-02 17:57
I can reproduce, report there, do not open a new issue everything they change the code to fight us.
