### ISSUE TITLE
Audio PUB not blocked by UBO

### ISSUE THREAD

**Issue by absynteZero** [uBlockOrigin/uAssets#11] opened 2016-04-12 11:00 UTC
### Audio pub not blocked by UblockOrigin in advanced setting and minimal configuration

Url: http://www.one.hiphop/live
      http://www.one.hiphop/top-hip-hop-songs
      http://www.one.hiphop/old-school-hip-hop

my settings:

www.one.hiphop api.one.hiphop \* noop
www.one.hiphop cdn-radiotime-logos.tunein.com \* block
www.one.hiphop cdn.one.hiphop \* noop
www.one.hiphop is3.mzstatic.com \* noop
www.one.hiphop listen.one.hiphop \* noop
www.one.hiphop listen.radionomy.com \* noop
www.one.hiphop stream.radiotime.com \* noop
www.one.hiphop streaming.radionomy.com \* noop
www.one.hiphop tunein.com \* noop
www.one.hiphop www.one.hiphop \* noop

my lists

http://www.noelshack.com/2016-14-1460064364-captureublock.png
- Browser/version: Firefox x64 45.0.1
- uBlock Origin version: 1.6.8

**Comment by publicarray** [comment] 2017-01-27 11:51
I know the issue is a little old, but I can't reproduce it, so I assume this has been fixed in an update. If the issue is still present please comment.

**Comment by okiehsch** [comment] 2017-04-27 04:33
I can't see any issue here.

**Closed by okiehsch** 2017-04-27 04:33 UTC
