### ISSUE TITLE
amazon ads on twitch again

### ISSUE THREAD

**Issue by coronasaurus** [uBlockOrigin/uAssets#8098] opened 2020-10-27 23:09 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

ads playing on twitch streams

### A specific URL where the issue occurs

twitch.tv

### Steps to Reproduce

go on twitch channel with ads

### Expected behavior:

no ads

### Actual behavior:

ads

### Your environment

* uBlock Origin version: 1.30.7.4
* Browser Name and version: firefox 82
* Operating System and version: win10

**Comment by gwarser** [comment] 2020-10-27 23:30
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by gwarser** 2020-10-27 23:30 UTC
