### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Raiiodavida** [uBlockOrigin/uAssets#11640] opened 2022-02-07 13:37 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch`

### Category

detection

### Describe the issue

ad detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79408
  cosmetic: 43502
  scriptlet: 16676
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62940-9, 1d.15m
    easyprivacy: 26707-18, 1d.16m
    plowe-0: 3679-817, 1d.13h.32m
    spa-1: 4211-76, 1d.19h.12m
    ublock-abuse: 77-0, 1d.1h.49m
    ublock-badware: 3841-72, 1d.19h.13m
    ublock-filters: 30190-189, 1d.19h.14m
    ublock-privacy: 194-2, 1d.1h.50m
    ublock-unbreak: 1700-40, 1d.1h.48m
    urlhaus-1: 7422-0, 19h.15m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 20 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 22285 ms (selfie)
popupPanel: 
  blocked: 276
```
</details>

**Comment by uBlock-user** [comment] 2022-02-07 13:47
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2022-02-07 13:47 UTC

**Comment by gwarser** [comment] 2022-02-07 13:50
> ```yaml
> supportStats: 
>   launchToReadiness: 22285 ms (selfie)
> ```

I takes over 20 seconds after browser start for uBO to be working on your machine.

**Comment by iam-py-test** [comment] 2022-02-07 16:44
> I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Please check before opening a new issue. It saves yourself and the uBo team time
