### ISSUE TITLE
MyAnimeList - Profile dropdown button gone, whitelist filter failing

### ISSUE THREAD

**Issue by trigger-death** [uBlockOrigin/uAssets#435] opened 2017-06-02 19:47 UTC
### URLs

https://myanimelist.net/profile/trigger_death

### Issue

Enabling uBlock Origin hides an important button to expand a profile's information section. (There is also one further down in the favorites section.) Filters to whitelist the element don't seem to work.

### Screenshots

[Picture of the Issue](http://i.imgur.com/F1n8zj9.png)

### Versions

**uBlock Origin Version:** 1.12.4
**Browser Version:** Firefox 53.0.3 (32-bit)
**OS Version:** Windows 7 SP1 (64-bit)

### Settings

[3rd-Party Filters](http://i.imgur.com/i5GbXOr.png)

### Notes

* `myanimelist.net#@#.js-btn-truncate.btn-truncate` as a filter does not fix the issue even when other filters following the same format do work for the site.
* I have tried reversing the filter as a block and it has correctly showed up in the CSS rules.
* This issue started in the last few days. It may be MAL's attempt to deter adblockers.
* Each `.btn-truncate` has a unique randomized code added to the element: e.g. `swbwj9y=""`. This is one of the items blocked by the filters.
* Each button uses `data-height` to function. This is also targeted by the filters.

**Comment by okiehsch** [comment] 2017-06-02 19:59
I can not reproduce with uBO default seettings and filters, tested with Chrome 58  and Firefox 53.0.3.
The button is visible
![anim](https://cloud.githubusercontent.com/assets/16838044/26742601/afb421de-47de-11e7-986f-5fefc066fe4c.JPG)
and I can expand the information section.
![anime](https://cloud.githubusercontent.com/assets/16838044/26742615/bce60f3e-47de-11e7-8890-e9478fc05f21.JPG)

**Comment by trigger-death** [comment] 2017-06-02 20:05
Huh, did you enable the specified 3rd party filters I used? I tried reproducing it with being logged off and it still occurs.

The rules blocking them are `:root [RANDOM CODE HERE][hidden]` and `:root div[style][data-height]`.

**Comment by trigger-death** [comment] 2017-06-02 20:08
The rule for at least `:root div[style][data-height]` comes from `Fanboy’s Enhanced Tracking List` and `Fanboy+Easylist-Merged Ultimate List`.

**Comment by okiehsch** [comment] 2017-06-02 20:09
I did not because only issues which can be reproduced with default settings and filters will be fixed.

> For whatever issue, help will be provided on a voluntary basis, but whatever filter solves the issue, it will be added to uBO's filters only if the issue exists with default filter lists.
https://github.com/uBlockOrigin/uAssets/issues/423#issuecomment-305553681

**Comment by trigger-death** [comment] 2017-06-02 20:11
Ah fair enough. Sorry for the trouble. Would someone be able to explain why an exception filter doesn't work though?

**Comment by okiehsch** [comment] 2017-06-02 20:17
If I add  `Fanboy’s Enhanced Tracking List` and `Fanboy+Easylist-Merged Ultimate List` I can reproduce your issue and `myanimelist.net#@#div[style][data-height]` fixes it on my end.

**Comment by trigger-death** [comment] 2017-06-02 20:25
Okay so the correct way to make an exception is to make the opposite of the block filter? How would that work for the other one where the code blocking it is different everytime. Somehow or another the filter blocking that weird code has every code that it ever randomly uses.

**Comment by okiehsch** [comment] 2017-06-02 20:32
The correct way to make an exception is to cancel the filter causing the issue, for
network filters you use `@@||example.com` and for cosmetic filters `example.com#@#whatever`
If more than one filter causes your issue because of some random code, than you have to cancel all of them.

**Comment by trigger-death** [comment] 2017-06-02 20:35
Alright. After doing some more research on hiding other elements. It seems that the code filters are part of the default lists. **However**, they only seem to show up and act as a rule if another rule is also blocking the element. So it seems they can safely be ignored. Thanks again.

**Comment by okiehsch** [comment] 2017-06-02 20:37
No problem.

**Closed by okiehsch** 2017-06-02 20:37 UTC
