### ISSUE TITLE
[Anti-adblock] mp4upload.com

### ISSUE THREAD

**Issue by LegitLlama** [uBlockOrigin/uAssets#7336] opened 2020-05-09 17:52 UTC
Hi,

### URL(s) where the issue occurs

Random example: `https://www.mp4upload.com/embed-d7ji72unbblr.html`

### Describe the issue

Once loaded, you might need a click to get the screenshot below to appear in up to a couple seconds. If it doesn't, try reloading. Either way, the video won't start.

### Screenshot(s)

![Screenshot_2020-05-09 https www mp4upload com](https://user-images.githubusercontent.com/53050597/81480913-2e322800-921c-11ea-80b7-50927d7afd3a.png)

### Versions

- Browser/version: Firefox 76 64-bit on Windows 7
- uBlock Origin version: 1.26.2

### Settings

- All filter lists enabled except the language specific ones. In language filters, the French list.
- A few other settings that should be irrelevant (I don't remember the defaults, but if you can't reproduce easily I'll provide full details)

### Notes

uBO logs show that both of the following filters are hit, but that doesn't appear to be enough. Unfortunately I have trouble tracking down the new JS variable that must be made to `abort-on-property-read`, if that's the issue. I'd be glad to look into a tutorial/guide if there's one.

    mp4upload.com##+js(abort-on-property-read, runAdblock)
    mp4upload.com##+js(abort-on-property-read, absda)

**Comment by uBlock-user** [comment] 2020-05-09 18:03
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7330

**Closed by uBlock-user** 2020-05-09 18:03 UTC

**Comment by LegitLlama** [comment] 2020-05-09 18:22
Sorry, I missed it. I updated my filters with no result, found no open issue and missed the closed one. Turns out uMatrix was still blocking `apus.tech`.

Thanks!
