### ISSUE TITLE
photopea.com: detection

### ISSUE THREAD

**Issue by Zaword** [uBlockOrigin/uAssets#20233] opened 2023-10-22 22:38 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.photopea.com/`

### Category

detection

### Description

Photopea website detects ublock origin: after a few seconds the website completely stops working, while a warning message appears "Alert: Sorry, we do not provide any service to people with ad blockers."

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![photopeascreen](https://github.com/uBlockOrigin/uAssets/assets/43016094/6d60f212-9263-4b6d-afb7-0221efd26cca)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 110729
 cosmetic: 92549
 scriptlet: 25413
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48683-216, now
  ublock-annoyances: 5609-56, now
 default:
  user-filters: 1-0, never
  ITA-0: 10524-17, now
  easylist: 72119-22, now
  easyprivacy: 33105-64, now
  plowe-0: 3727-1074, now
  ublock-badware: 7257-132, now
  ublock-filters: 35246-169, now
  ublock-privacy: 589-6, now
  ublock-quick-fixes: 243-208, now
  ublock-unbreak: 2132-35, now
  urlhaus-1: 11600-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 25 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1330 ms
 maxAssetCacheWait: 327 ms
popupPanel:
 blocked: 3
 network:
  google.com: 1
  googlesyndication.com: 1
  uniconsent.com: 1
 extended:
  ##[href*=".ivank.net"]
  ##div[style] > a[href*="photopea.com"][href*="ads"]:upward(1)
  ##+js(set-constant, console.clear, noopFunc)
```
</details>

**Comment by gorhill** [comment] 2023-10-22 22:46
Duplicate of #20232.

**Closed by gorhill** 2023-10-22 22:46 UTC

**Comment by gwarser** [comment] 2023-10-23 07:27
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19697
