### ISSUE TITLE
dragontea.ink: detection

### ISSUE THREAD

**Issue by V3z000** [uBlockOrigin/uAssets#12075] opened 2022-03-06 11:13 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/`

### Category

detection

### Describe the issue

You are on site and you are getting information about detection of adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 96
filterset (summary): 
  network: 82634
  cosmetic: 30423
  scriptlet: 16685
  html: 638
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30952-304, 4d.9m
    ublock-badware: 3903-3, 4d.10m
    ublock-privacy: 208-1, 3d.23h.59m
    ublock-abuse: 72-0, 3d.20h.21m
    ublock-unbreak: 1737-0, 3d.20h.22m
    adguard-mobile: 7280-169, 4d.8m
    easylist: 64084-24278, 3d.20h.20m
    easyprivacy: 26634-579, 4d.11m
    urlhaus-1: 8437-0, 10h.29m
    plowe-0: 3673-2, 7d.9h.38m
    POL-0: 7779-143, 10h.30m
    POL-2: 1276-17, 17h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 584 ms (selfie)
  maxAssetCacheWait: 396 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googlesyndication.com: 5
    googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment] 2022-03-06 11:29
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/12073

Update your filter lists.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Closed by okiehsch** 2022-03-06 11:29 UTC
