### ISSUE TITLE
threenow.co.nz: ads

### ISSUE THREAD

**Issue by CoderThomasB** [uBlockOrigin/uAssets#11391] opened 2022-01-20 08:19 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.threenow.co.nz/live-tv-guide/three`

### Category

ads

### Describe the issue

AD segments in the video viewer are not blocked.

### Screenshot(s)

<details>

![Screenshot 2022-01-20 at 21-16-08 Live TV Guide Three](https://user-images.githubusercontent.com/47554072/150299795-4f690a8f-6e27-48d2-a0a6-6e6dbff10efc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79097
  cosmetic: 40535
  scriptlet: 16418
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30735-30, 2d.11h.22m
    ublock-badware: 3728-1, 2d.11h.21m
    ublock-privacy: 187-0, 2d.11h.20m
    ublock-abuse: 76-0, 2d.11h.19m
    ublock-unbreak: 1694-0, 2d.11h.18m
    easylist: 63093-587, 2d.11h.17m
    easyprivacy: 26627-480, 2d.11h.16m
    urlhaus-1: 8093-0, 6h.52m
    plowe-0: 3684-2, 9d.7h.41m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 188 ms (selfie)
popupPanel: 
  blocked: 183
```
</details>

**Comment by uBlock-user** [comment] 2022-01-20 09:06
`threenow.co.nz##+js(set, ADB, {})` works ?

**Comment by uBlock-user** [comment] 2022-01-20 09:13
I don't see the ad video as depicted in the ss. Just the ads that're part of the Live TV broadcast.

**Comment by CoderThomasB** [comment] 2022-01-20 09:20
> I don't see the ad video as depicted in the ss. Just the ads that're part of the Live TV broadcast.

This issue discusses the ads that are in the Live TV broadcast. The text "Advertisement" will show in the top right when these ads are being played.

**Comment by uBlock-user** [comment] 2022-01-20 09:25
Ads part of the live TV broadcast are pausable and  player control/s appears, in your ss none of that is present.

> The text "Advertisement" will show in the top right when these ads are being played.

That never happens in my tests.

**Comment by uBlock-user** [comment] 2022-01-20 09:28
Indeed, ads which are part of the Live TV broadcast stream cannot be blocked.

**Comment by CoderThomasB** [comment] 2022-01-20 09:30
> Indeed, ads which are part of the Live TV broadcast stream cannot be blocked.

If that is the case should I close this issue?

**Comment by uBlock-user** [comment] 2022-01-20 09:32
Can you see the player controls like pause/play button when the ads are playing ?

**Comment by CoderThomasB** [comment] 2022-01-20 09:33
> Can you see the player controls like pause/play button when the ads are playing ?

Yes, if I hover over the video player with my mouse the controls appear.

**Comment by uBlock-user** [comment] 2022-01-20 09:47
> The text "Advertisement" will show in the top right when these ads are being played.

I still don't understand how that appears. Test on default settings/lists + all other extensions disabled if that helps.

**Comment by CoderThomasB** [comment] 2022-01-20 09:53
> > The text "Advertisement" will show in the top right when these ads are being played.
> 
> I still don't understand how that appears. Test on default settings/lists + all other extensions disabled if that helps.

I don't see it now! Maybe it's a regulatory thing that advertisements must be labelled at certain times? Maybe try looking for it during the daylight hours of New Zealand time.

**Comment by uBlock-user** [comment] 2022-01-20 09:55
> Maybe it's a regulatory thing that advertisements must be labelled at certain times? Maybe try looking for it during the daylight hours of New Zealand time.

Lets wait for @ryanbr 's findings. He's from NZ and can offer perhaps a specific insight on this.

**Comment by ryanbr** [comment] 2022-01-20 10:48
Watched for an hour of livetv, with streaming ads. The usual Jenny Craig, Pak'n'Save, ANZ, Rexona, Samsung ads, Noel Leemings.. but given its all liveTV, it can't be blocked.

**Comment by uBlock-user** [comment] 2022-01-20 10:49
@ryanbr what about non-live videos ?

**Comment by ryanbr** [comment] 2022-01-20 10:59
Okay could reproduce pre-roll via akamai/brightcove. These are possibly stitched into the stream

**Comment by uBlock-user** [comment] 2022-01-20 11:04
@ryanbr link for the non-live video ?

**Comment by ryanbr** [comment] 2022-01-20 11:05
https://www.threenow.co.nz/shows/the-block-australia/season-17-ep-36/S1542-593/M52434-457

**Comment by uBlock-user** [comment] 2022-01-20 11:23
No video ads anywhere.

<details>

![Capture](https://user-images.githubusercontent.com/21290713/150329531-36916af2-b5b6-4da1-ad20-4696f881e165.PNG)

</details>

**Comment by ryanbr** [comment] 2022-01-20 11:39
Just checked that `||edge.api.brightcove.com^$xmlhttprequest,removeparam=ad_config_id,domain=9now.com.au|threenow.co.nz` fixes it. Safe to close this report.

**Closed** 2022-01-20 11:48 UTC
Labels: unable to reproduce, geo specific, account required

**Comment by gorhill** [comment] 2022-01-20 13:05
> Just checked that ... fixes it

Heh, we were watching The Block NZ on that channel months ago, hence why I added that filter. OP probably subscribed to extra lists or had other extension(s) interfering since he reported it worked fine after being asked to test with default lists/settings. Would be nice to know what was interfering.
