### ISSUE TITLE
[nsfw] i-polls.com: ads

### ISSUE THREAD

**Issue by adsdestroyer** [uBlockOrigin/uAssets#15232] opened 2022-10-12 07:30 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ppd.phsensei.com/2BNc`

### Category

ads

### Describe the issue

ad block detected!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-10-12 at 07-29-04 8 Interesting Reasons Why Your Jeep Compass Won't Start But Has Power - Causes and How to Fix Them - i-Polls](https://user-images.githubusercontent.com/109018577/195278164-5c336f82-cde8-4a8a-b20e-04eb3f337130.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86303
  cosmetic: 39075
  scriptlet: 18060
  html: 783
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33838-45, 3d.20h.15m
    ublock-badware: 4363-0, 3d.20h.15m
    ublock-privacy: 274-0, 3d.20h.15m
    ublock-abuse: 76-0, 3d.20h.15m
    ublock-unbreak: 1881-1, 3d.20h.15m
    ublock-quick-fixes: 346-0, 4h.10m
    easylist: 62491-620, 3d.20h.15m
    easyprivacy: 30695-1705, 3d.20h.15m
    urlhaus-1: 9118-0, 4h.9m
    plowe-0: 3671-3, 3d.20h.15m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 165 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 663 ms (selfie)
  maxAssetCacheWait: 242 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    connatix.com: 2
    doubleclick.net: 1
    ezodn.com: 1
    ezoic.net: 8
    googlesyndication.com: 1
    googletagmanager.com: 1
    quantserve.com: 1
```
</details>

**Comment by krystian3w** [comment] 2022-10-12 07:43
#15224

**Comment by okiehsch** [comment] 2022-10-12 08:19
> I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

![image](https://user-images.githubusercontent.com/16838044/195289150-249c9b14-f254-4a4b-991d-1145e1039ddd.png)

How exactly did you verify that the issue has not been already reported? 

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/15224#issuecomment-1275517167

**Closed by okiehsch** 2022-10-12 08:19 UTC

**Comment by mapx-** [comment] 2022-10-12 08:35
https://github.com/uBlockOrigin/uAssets/commit/39b95da739dc736334536ccfbd81ecba953f2751
