### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by clearwaterbrewer** [uBlockOrigin/uAssets#11978] opened 2022-03-01 13:01 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

blank body when enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79909
  cosmetic: 41258
  scriptlet: 16496
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63942-9, 3d.5h.8m
    easyprivacy: 26624-122, 3d.5h.7m
    plowe-0: 3673-805, 57m
    ublock-abuse: 77-0, 3d.5h.6m
    ublock-badware: 4025-83, 3d.5h.5m
    ublock-filters: 30335-157, 3d.5h.4m
    ublock-privacy: 202-2, 3d.5h.3m
    ublock-unbreak: 1718-39, 3d.5h.2m
    urlhaus-1: 8437-0, 16h.58m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 626 ms (selfie)
  maxAssetCacheWait: 251 ms
popupPanel: 
  blocked: 76
  blockedDetails: 
    google.com: 76
```
</details>

**Comment by okiehsch** [comment] 2022-03-01 13:06
>  ublock-filters: 30335-157, 3d.5h.4m

This means your ublock filters have last been updated three days ago.

![image](https://user-images.githubusercontent.com/16838044/156174161-49b5e347-2bff-4ce2-9b0f-67d23c39da0e.png)
Here you are telling us that you updated your filter lists before youn opened this issue.
Can you see the contradiction?

**Comment by okiehsch** [comment] 2022-03-01 13:07
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906

**Closed by okiehsch** 2022-03-01 13:06 UTC
