### ISSUE TITLE
eu.community.samsung.com: breakage

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#24597] opened 2024-07-22 20:25 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eu.community.samsung.com/t5/community-newsroom/galaxy-unpacked-july-2024-what-was-announced/ba-p/10223958`

### Category

breakage

### Description

Cookies notice is still blocking the page after dismissing it (by e.g. clicking on the “Accept All”/“Continue without accepting” button).

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7711c4b1-cab9-4199-95d5-c0becc66e4f3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 140172
 cosmetic: 47504
 scriptlet: 20375
 html: 1871
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39450-119, now Δ
  ublock-badware: 9528-2, 1m
  ublock-privacy: 1053-4, now Δ
  ublock-unbreak: 2450-2, 1m
  ublock-quick-fixes: 165-2, 1m
  easylist: 87198-171, now Δ
  easyprivacy: 52853-67, 1m
  urlhaus-1: 15185-0, 1m
  plowe-0: 3547-989, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1644 ms
 maxAssetCacheWait: 893 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  samsung.com: 1
  adobedtm.com: 2
  demdex.net: 2
  googletagmanager.com: 1
  trustarc.com: 19
```
</details>

**Comment by D4niloMR** [comment] 2024-07-22 21:52
Can be fixed by `@@||www.googletagmanager.com/gtm.js$script,3p,domain=eu.community.samsung.com`

Or we can hide/accept/block that cookie banner in default lists to not allow the GTM.

**Comment by stephenhawk8054** [comment] 2024-07-23 00:33
I can't reproduce it. After clicking on the cookie buttons and refreshing the page, I don't see the cookie popup appear again.

**Comment by D4niloMR** [comment] 2024-07-23 00:48
The site should refreshed through googletagmanager:

![image](https://github.com/user-attachments/assets/16b02141-d5c1-487a-a8e8-327e89ee692c)

**Comment by stephenhawk8054** [comment] 2024-07-23 00:53
Hmm... I can see it now when I use VPN to other locations

**Comment by stephenhawk8054** [comment] 2024-07-23 00:59
We don't address cookie banner issues in default lists so need to unblock `googletagmanager.com`

**Closed** 2024-07-23 01:11 UTC
