### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by UblockAntiAdblock** [uBlockOrigin/uAssets#11386] opened 2022-01-20 01:46 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=AQDkQXr6Qc4`

### Category

breakage

### Describe the issue

sometimes when i'm on youtube, when i spend a good time the title of the video and other elements disappear, this is solved by reloading the page but it's very annoying. it happens with any video but not always
note: can be very difficult to reproduce
screenshot: https://imgur.com/a/1kW7UMx

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 162039
  cosmetic: 197245
  scriptlet: 51976
  html: 626
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 27116-72, 35m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5359-5, 2d.5h.55m
    adguard-generic: 61948-5405, 2d.5h.55m
    adguard-mobile: 7083-227, 2d.5h.55m
    adguard-spyware: 25619-11358, 2d.5h.55m
    adguard-annoyance: 49164-4237, 2d.5h.55m
    adguard-social: 15509-25, 2d.5h.55m
    fanboy-thirdparty_social: 68-0, 2d.5h.55m
    fanboy-annoyance: 63152-48166, 2d.5h.55m
    fanboy-cookiemonster: 21539-140, 2d.5h.55m
    fanboy-social: 23149-1084, 2d.5h.55m
    ublock-annoyances: 4366-4, 2d.5h.55m
    dpollock-0: 10347-1757, 2d.5h.55m
    mvps-0: 8730-388, 2d.5h.55m
    TUR-0: 9078-199, 2d.5h.55m
    adguard-spyware-url: 443-3, 2d.5h.55m
    block-lan: 44-0, 2d.5h.55m
    curben-phishing: 11815-4, 34m
    curben-pup: 382-1, 33m
  default: 
    ublock-filters: 30735-3358, 2d.5h.56m
    ublock-badware: 3728-1, 2d.5h.56m
    ublock-privacy: 187-36, 2d.5h.56m
    ublock-abuse: 76-65, 2d.5h.56m
    ublock-unbreak: 1694-0, 2d.5h.56m
    easylist: 63093-1188, 2d.5h.55m
    easyprivacy: 26627-42, 2d.5h.55m
    urlhaus-1: 8152-0, 37m
    plowe-0: 3682-803, 2d.5h.55m
    spa-0: 3694-5, 36m
    spa-1: 4188-120, 2d.5h.55m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
hostRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 299 ms (selfie)
popupPanel: 
  blocked: 15
```
</details>

**Comment by uBlock-user** [comment] 2022-01-20 06:08
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2022-01-20 06:08 UTC

**Comment by gorhill** [comment] 2022-01-20 13:12
You have too many filter lists and custom filters/rules, in such case test with default settings/lists, or investigate which list/filter/rules is causing your issue, given how you heavily customized uBO, you are the best placed person to do this.
