### ISSUE TITLE
supremacy1914.com: nuisance

### ISSUE THREAD

**Issue by goodthedog** [uBlockOrigin/uAssets#12969] opened 2022-04-26 19:10 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.supremacy1914.com/game.php?bust=1`

### Category

nuisance

### Describe the issue

Ads Panel wont remove after refresh and there a black panel after removing the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82515
  cosmetic: 42763
  scriptlet: 16787
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-1, never
    easylist: 66518-51, 2h.38m
    easyprivacy: 26902-121, 2h.37m
    plowe-0: 3678-805, 3d.13h.28m
    ublock-abuse: 74-0, 3d.13h.27m
    ublock-badware: 4104-93, 2h.36m
    ublock-filters: 30990-108, 2h.35m
    ublock-privacy: 212-2, 3d.13h.26m
    ublock-quick-fixes: 180-0, 12h.17m
    ublock-unbreak: 1767-43, 2h.34m
    urlhaus-1: 9017-0, 12h.16m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 231 ms (selfie)
  maxAssetCacheWait: 81 ms
popupPanel: 
  blocked: 8
  no-cosmetic-filtering: true
  blockedDetails: 
    supremacy1914.com: 1
    bytro.com: 6
    helpshift.com: 1
```
</details>

**Comment by krystian3w** [comment] 2022-04-26 20:36
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11620

**Comment by krystian3w** [comment] 2022-04-26 20:42
releated: https://github.com/uBlockOrigin/uAssets/issues/12634, https://github.com/uBlockOrigin/uAssets/issues/12463

**Comment by stephenhawk8054** [comment] 2022-04-27 01:27
I can't see any ads panel with the link you give. Can you screenshot and describe the steps to reproduce in more details?

**Comment by krystian3w** [comment] 2022-04-27 09:52
Maybe this is bug with load page before uBo can read network requests: 

https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded
https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-27 19:29
account required, i use google.
<details>
<summary>скрин</summary>

![2022-04-27_222340](https://user-images.githubusercontent.com/104250631/165604905-f71a3612-6dc6-4f32-9fdb-62fcffc89dd6.png)
</details>

**Comment by krystian3w** [comment] 2022-04-27 20:33
Gone after reload page ~10 minutes after chrome was started?

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-29 09:03
@stephenhawk8054 

account required, i use google.
<details>
<summary>скрин</summary>

![2022-04-29_120039](https://user-images.githubusercontent.com/104250631/165915353-107c9ae8-c2b2-4371-84f0-5350204a885f.png)
</details>

**Comment by stephenhawk8054** [comment] 2022-04-29 09:42
> @stephenhawk8054
> 
> account required, i use google.
> скрин

I still couldn't reproduce it, even after logging in and playing the game. Not sure if it's geo-related or there should be any other steps to do.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/165921265-ee7a0aca-aab0-4c2e-97d7-cbfc0f481b71.png)

</details>

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-29 11:34
@stephenhawk8054 
If I post a snapshot of the page and the har file will it help?

**Comment by stephenhawk8054** [comment] 2022-04-29 11:36
> @stephenhawk8054 If I post a snapshot of the page and the har file will it help?

I'm not very experienced with HAR file, so I'll let it for someone else. Can you post your troubleshooting information first?

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-29 11:39
<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 97175
  cosmetic: 118779
  scriptlet: 22310
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 30421-30, 28m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1416-25, 28m
    fanboy-cookiemonster: 31836-267, 28m
    ublock-annoyances: 4363-36, 28m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30920-41, 28m
    ublock-badware: 4125-3, 28m
    ublock-privacy: 213-8, 28m
    ublock-abuse: 75-0, 28m
    ublock-unbreak: 1766-9, 28m
    ublock-quick-fixes: 184-0, 28m
    easylist: 66239-219, 28m
    easyprivacy: 26914-457, 28m
    RUS-0: 41287-275, 28m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  uiFlavor: classic
supportStats: 
  allReadyAfter: 806 ms (selfie)
  maxAssetCacheWait: 677 ms

```
</details>

**Comment by krystian3w** [comment] 2022-04-29 11:39
Also try use fake/tmp account and backup important cookies/localStorage (someone can try steal data from your har file - AdGuard recommend send har via e-mail).

**Comment by krystian3w** [comment] 2022-04-29 11:42
Renable helps:
```yaml
  removed: 
    urlhaus-1: null
    plowe-0: null
```

But in older issues both was active?

**Comment by stephenhawk8054** [comment] 2022-04-29 11:48
Yeah sorry I still can't reproduce it, even when testing with your configurations.

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-29 11:53
@mapx-

**Comment by krystian3w** [comment] 2022-04-29 11:58
May unable reproduce on 🇷🇴 IP, then can help instructions how create HAR and send to own private mail.

Maybe dimisa can reproduce and bought profesional VPN (not detectable for most pages).

**Comment by krystian3w** [comment] 2022-04-29 12:06
Risky filter to remove node:

supremacy1914.*,callofwar.com##iframe ~ div[id]:not([class]):has(img):remove()

If generate placeholder then will be better scriptlet, network filtering and at last `:style` to resize main content to 100%.

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-29 12:37
Works for me: `supremacy1914.com##+js(acis, document.querySelector, inGameAdsContainer)`
<details>
<summary>screen</summary>

![2022-04-29_152802](https://user-images.githubusercontent.com/104250631/165944392-f2739389-9f62-4178-9a70-eac04eb91087.png)
</details>

@dimisa-RUAdList 
You can check?

**Comment by stephenhawk8054** [comment] 2022-04-29 12:41
I wonder why there are no blocked number in uBO's icon. For me, it's always at least 3 there.

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-04-29 12:43
> I wonder why there are no blocked number in uBO's icon. For me, it's always at least 3 there.

showIconBadge: false

**Comment by stephenhawk8054** [comment] 2022-04-29 12:47
Ah, didn't realize you turned off that.

**Comment by krystian3w** [comment] 2022-04-29 13:55
Test included disable useage `suspendUntilReady` after open game as homepage/lnk or .url file path?

**Comment by stephenhawk8054** [comment] 2022-04-30 02:21
> Works for me: `supremacy1914.com##+js(acis, document.querySelector, inGameAdsContainer)`

@P-o-R-t-v-i-n-e Can you copy the scripts that has `inGameAdsContainer` to here? If they are just used for injecting ads at some points, I think we can add it.

@goodthedog Can you check if adding above filter works for you? Add in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes` and Ctrl + F5 to reload the page.

**Comment by goodthedog** [comment] 2022-04-30 08:23
@stephenhawk8054 cant tell now as their server crash and reset the ads they have not add in yet
working fine without the script but i will add in anyways.

**Comment by stephenhawk8054** [comment] 2022-04-30 09:57
> @stephenhawk8054 cant tell now as their server crash and reset the ads they have not add in yet working fine without the script but i will add in anyways.

Can you test without the script first? If ads appear again, you can add it later to see if it works or not.

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-05-01 18:37
@stephenhawk8054 
only this rule works stable
`||bytro.com/fileadmin/$image,domain=www.supremacy1914.com|www.callofwar.com` https://github.com/uBlockOrigin/uAssets/issues/12634

checked with the support of: @dimisa-RUAdList

**Comment by stephenhawk8054** [comment] 2022-05-02 00:27
> @stephenhawk8054 only this rule works stable `||bytro.com/fileadmin/$image,domain=www.supremacy1914.com|www.callofwar.com` #12634
> 
> checked with the support of: @dimisa-RUAdList

@goodthedog Can you test this filter?

**Comment by krystian3w** [comment] 2022-05-02 07:06
Block images recover 100% of width?

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-05-03 14:09
@goodthedog ?

**Closed** 2022-05-03 18:27 UTC
Labels: information required, No Feedback => closing

**Comment by P-o-R-t-v-i-n-e** [comment] 2022-05-04 16:04
@mapx- 
Maybe you add this rule?
`||bytro.com/fileadmin/$image,domain=www.supremacy1914.com|www.callofwar.com`
