### ISSUE TITLE
tr.investing.com: detection

### ISSUE THREAD

**Issue by titanmk2** [uBlockOrigin/uAssets#10935] opened 2021-12-16 05:17 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://tr.investing.com/currencies/usd-try?__cf_chl_jschl_tk__=X6oMNAkleGTVZACPvewNvG9WeU4t.eIFS0ZGIHGhi.4-1639631432-0-gaNycGzNDqU`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 79591
  cosmetic: 46568
  scriptlet: 16733
  html: 607
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 7h.24m
  default: 
    ublock-filters: 30569-46, 3h.20m
    ublock-badware: 3573-3, 3h.16m
    ublock-privacy: 184-1, 3h.14m
    ublock-abuse: 81-0, 3h.12m
    ublock-unbreak: 1715-0, 3h.22m
    easylist: 61638-566, 4d.2h.40m
    easyprivacy: 26499-480, 3h.18m
    plowe-0: 3697-0, 9d.7h.17m
    TUR-0: 9421-98, 3h.10m
    urlhaus-1: 7463-0, 7h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1449
  launchFromSelfie: true
popupPanel: 
  blocked: 24
```
</details>

**Comment by MasterKia** [comment] 2021-12-16 05:21
Similar to https://github.com/uBlockOrigin/uAssets/issues/10924

**Comment by uBlock-user** [comment] 2021-12-16 06:26
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10924

**Closed by uBlock-user** 2021-12-16 06:26 UTC
Labels: duplicate
