### ISSUE TITLE
chip.de: ads

### ISSUE THREAD

**Issue by DrDustwolf** [uBlockOrigin/uAssets#20624] opened 2023-11-12 09:55 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chip.de/news/Anmelden-bei-Amazon-und-Co-wird-sich-veraendern-EU-erzielt-Einigung_185021351.html`

### Category

ads

### Description

On chip.de there are still some ads. Look at the screenshots for more details.

My system:
Phone: Shift6mq
OS: LineageOS for microG: 20-20231102-microG-axolotl
Browser: Iceraven: 2.12.1

### Other extensions used

- Dark Background and Light Text
- Firefox Multi-Account Containers
- Read Aloud: A Text to Speech Voice Reader
- User-Agent Switcher
- Cookie Quick Manager
- Smart HTTPS
- LocalCDN
- Flagfox
- Web Archives
- Redirect AMP to HTML
- ClearURLs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
The image isn’t adult or NSFW. I just had no posibility for the usage of drag and drop.

</details>
- http://bayimg.com/nAfdCAaBP
- http://bayimg.com/nAfDaaabp

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 316182
 cosmetic: 244602
 scriptlet: 48423
 html: 1359
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 15h.25m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94520-94432, 7d.21h.56m
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 76-0, 19h.47m
  https://winhelp2002.mvps.org/hosts.txt: 8729-325, 2d.19h.6m
  adguard-generic: 79407-7908, 3d.16h.51m
  adguard-spyware-url: 1306-88, 3d.16h.49m
  block-lan: 54-0, 7d.21h.56m
  curben-phishing: 77794-32, 15h.30m
  adguard-social: 22003-2309, 3d.16h.48m
  fanboy-thirdparty_social: 69-1, 7d.21h.56m
  fanboy-cookiemonster: 48841-19827, 19h.53m
  fanboy-social: 16190-11766, 19h.52m
  [21 lists not shown]: [too many]
 default:
  user-filters: 109-3, never
  ublock-filters: 36429-832, 2d.19h.9m
  ublock-badware: 7428-5, 2d.19h.8m
  ublock-privacy: 661-77, 19h.54m
  ublock-unbreak: 2186-3, 2d.19h.7m
  ublock-quick-fixes: 173-7, 1m
  adguard-mobile: 8835-185, 3d.16h.50m
  easylist: 75167-17164, 1d.21h.5m
  easyprivacy: 32854-1146, 1d.21h.4m
  urlhaus-1: 10825-0, 15h.31m
  plowe-0: 3720-1, 7d.21h.56m
  DEU-0: 7156-413, 15h.29m
filterset (user): [array of 109 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 577 redacted]
hostRuleset:
 added: [array of 167 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1566 ms (selfie)
 maxAssetCacheWait: 1078 ms
popupPanel:
 blocked: 3
 no-scripting: true
 network:
  chip.de: 2
  vgwort.de: 1
 extended:
  ###R1C3[role="complementary"]
  ###R1C1[role="complementary"]
  ##.Ad:not([style^="display:block;"]):not(.Ad.align)
  ###contentad-top-adsense-1
  ##.app_nexus_banners_common
  ##.StickyAd
  ##.FC.mt-md-so[role="complementary"]
  ###footer-white-global
  ###CR:not(.Downloads-Detail) .Ad-hor-height
  ##.Ad-hor-height:not([id])
  ##.app_nexus_banners_common[id]:not([style^="display:block;"])
  ###R1C2[role="complementary"]:not(:has(> .Hero))
  ##.FC__Container.min-height-250px-mu:style(max-height: 0.1px !im…
  ##:root:style(--topbanner-height-min:unset!important;--topbanner…
  ##+js(set-constant, TfmediaExtFolEngineLoaded, true)
  ##+js(json-prune, enabled, force_disabled)
  ##+js(abort-current-script, navigator, /propertyIsEnumerable.*wi…
```
</details>

**Comment by gorhill** [comment] 2023-11-12 17:04
I don't see the ad in your second screenshot when using default settings/lists. The first screenshot is just the site's telling you something, it's not an ad.

You have tons of customizations, did you really:

> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

If we can't reproduce, nothing will be fixed, and you will have to investigate on your side the issue.

**Closed** 2023-11-13 08:43 UTC
Labels: unable to reproduce
