### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by mod098** [uBlockOrigin/uAssets#17337] opened 2023-03-29 23:17 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.instagram.com/`

### Category

breakage

### Description

scrolling through the page becomes buggy every 4-5 posts.

the only fix i found is to disable cosmetic filtering, but then the ads will show up :(

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 88661
  cosmetic: 22601
  scriptlet: 17459
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware-url: 958-2, 2d.1h.28m
  default: 
    user-filters: 17-0, never
    easylist: 64765-16895, 2d.1h.28m
    easyprivacy: 30729-1177, 2d.1h.28m
    plowe-0: 3751-934, 2d.1h.28m
    ublock-abuse: 78-0, 2d.1h.28m
    ublock-badware: 5411-114, 2d.1h.28m
    ublock-filters: 33074-301, 2d.1h.28m
    ublock-privacy: 295-5, 2d.1h.28m
    ublock-quick-fixes: 423-9, 1d.1h.10m
    ublock-unbreak: 1939-43, 2d.1h.28m
    urlhaus-1: 6938-0, 1d.1h.9m
filterset (user): [array of 17 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 97 ms (selfie)
  maxAssetCacheWait: 54 ms
popupPanel: 
  blocked: 44
  blockedDetails: 
    instagram.com: 43
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment] 2023-03-30 06:40
> scrolling through the page becomes buggy every 4-5 posts.

meaning very slow navigation ?

**Comment by mod098** [comment] 2023-03-30 08:02
> meaning very slow navigation ?

no, scrolling down will jump up the same photo instead for multiple times. i found same problem on [reddit](https://www.reddit.com/r/uBlockOrigin/comments/yo0hl4/ublock_messes_instagram_page/) with no fix still other than disable cosmetic filtering

**Comment by mapx-** [comment] 2023-03-30 08:25
follow all these steps, see if helps:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by gorhill** [comment] 2023-03-30 13:51
> the only fix i found is to disable cosmetic filtering, but then the ads will show up :(

Investigate whether it's cause by one or more of your own 17 filters.

**Comment by mod098** [comment] 2023-03-30 16:12
> Investigate whether it's caused by one or more of your own 17 filters. Also, you are using a non-standard configuration as you disabled generic cosmetic filtering.

i've reinstalled ubo to default settings and it still happens. i used other browser (brave) to test and it has same problem around this gap 
![image](https://user-images.githubusercontent.com/114498272/228898303-56099c24-ebfb-4ea2-92bf-59b507ff4271.png)



> follow all these steps, see if helps:

i tried all the steps, but still buggy around here:
![image](https://user-images.githubusercontent.com/114498272/228899014-053234d2-64e1-49a3-9a5d-d91b47b155f0.png)

**Comment by mod098** [comment] 2023-03-30 22:10
> Where do you access the site from?

ms edge , windows 11

**Comment by mapx-** [comment] 2023-03-31 05:17
I mean what country

**Comment by mod098** [comment] 2023-03-31 06:20
> I mean what country

singapore

**Comment by mapx-** [comment] 2023-03-31 07:04
closing for now as we cannot reproduce your issue

**Closed by mapx-** 2023-03-31 07:04 UTC
Labels: unable to reproduce, Waiting for feedback

**Comment by LinAGKar** [comment] 2023-06-24 12:04
I'm also seeing this issue, in Firefox on Android in Sweden. Same on m.facebook.com

**Comment by pordini** [comment] 2023-07-29 06:21
Seeing the same on Firefox in the Netherlands. 
Tested via VPN to Argentina, same issue.

**Comment by pordini** [comment] 2023-07-29 09:48
edit 2: Didn't solve it, jumping back up when scrolling happened again.
