### ISSUE TITLE
olx.ua

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#7858] opened 2020-09-01 11:38 UTC
###URL(s) where the issue occurs

`https://www.olx.ua/uk/`

### Describe the issue

Subsections don't work
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js` - **uBlock filters – Privacy**

### Screenshot(s)

Gif - https://i.imgur.com/Wdmm1LC.gif

### Versions

- Browser/version: Opera|Stable
- uBlock Origin version: 1.29.2

### Settings
![2020-09-01_143041](https://user-images.githubusercontent.com/57287308/91844260-c9358e80-ec5f-11ea-970d-01926b447c07.png)

**Comment by uBlock-user** [comment] 2020-09-01 12:02
Add `||googletagmanager.com^$script,redirect-rule=none,domain=olx.ua/uk` and report back

**Comment by krystian3w** [comment] 2020-09-01 12:02
Fixed in `EasyPrivacy` by:

`@@||googletagmanager.com/gtm.js$script,domain=olx.ua`

But you using non-default `AdGuard Tracking Protection`.

---

@adamwr / @alex-302 / @BlazDT can we check add exception for uBO version list? Maybe also needed for all AdGuard environment.

---


On the part of uAssets it will be rather difficult to collect domains where `redirect`/`redirect-rule` does not help.

https://github.com/uBlockOrigin/uAssets/search?q=%7C%7Cgoogletagmanager.com%2Fgtm.js%24script%2Credirect%3Dgoogletagmanager.com%2Fgtm.js&unscoped_q=%7C%7Cgoogletagmanager.com%2Fgtm.js%24script%2Credirect%3Dgoogletagmanager.com%2Fgtm.js

**Comment by krystian3w** [comment] 2020-09-01 12:04
> `domain=olx.ua/uk`

@uBlock-user when uBO added support "folders" for `domain=`? Or uBO omit "folder/catalog" `/uk`

**Comment by uBlock-user** [comment] 2020-09-01 12:04
typo fixed

**Comment by P0Rtvine** [comment] 2020-09-01 12:07
> Add `||googletagmanager.com^$script,redirect-rule=none,domain=olx.ua` and report back

Yes, it work.

**Comment by krystian3w** [comment] 2020-09-01 12:10
Must "works".

Now it is up to `uAssets` to decide whether it is right to get a fix in the EP (instead of in `privacy.txt`/`unbreak.txt`).

**Comment by uBlock-user** [comment] 2020-09-01 12:27
Seems Chromium specific, I can't reproduce this on Firefox.

**Comment by uBlock-user** [comment] 2020-09-01 12:51
Currently closing because of the exception present in EasyPrivacy.

**Closed by uBlock-user** 2020-09-01 12:51 UTC

**Comment by P0Rtvine** [comment] 2020-09-02 08:20
@uBlock-user 
Please add a rule` ||googletagmanager.com^$script redirect-rule=none,domain=olx.ua`

**Comment by P0Rtvine** [comment] 2021-01-15 09:44
@uBlock-user 
The same problem on : `https://www.olx.bg/`  `https://www.olx.pl/` `https://www.olx.ro/` `https://www.olx.uz/`

**Comment by krystian3w** [comment] 2021-01-15 10:39
Added similar - so if you using uBO legacy recommend is follow this:

https://github.com/gorhill/uBlock-for-firefox-legacy/issues/236

or change environment to more modern browser.

**Comment by P0Rtvine** [comment] 2021-06-22 12:38
`||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js`

### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/122925578-a3ed4a80-d36f-11eb-82bc-e2e531ed6e65.gif)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.36.0

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by uBlock-user** [comment] 2021-06-22 13:13
@P0Rtvine try with `@@||google-analytics.com/analytics.js$script,redirect-rule,domain=olx.*`

**Comment by krystian3w** [comment] 2021-06-22 13:15
Try with:

`||google-analytics.com/analytics.js$redirect=noop.txt:10, important`

If works then bug in resource.

**Comment by P0Rtvine** [comment] 2021-06-22 13:23
@uBlock-user
@krystian3w
These rules works separately
`@@||google-analytics.com/analytics.js$script,redirect-rule,domain=olx.*`
`||google-analytics.com/analytics.js$redirect=noop.txt:10,important`

**Comment by uBlock-user** [comment] 2021-06-22 13:41
@krystian3w you don't need `:10` if you append `important`, don't use both, use either of them.

**Comment by krystian3w** [comment] 2021-06-22 13:52
A little luck that some custom list added `:9` and `,important`.

**Comment by P0Rtvine** [comment] 2021-06-23 05:19
@uBlock-user 
>The problem appeared after updating uBO.
>I don't see any connection request to googleanalytics on Chrome 91 + latest uBO only.

As I said, the problem appeared after upgrading to version 1.36.0
### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/123039758-62a27c80-d3fb-11eb-8eb1-bec2fde3d58a.gif)
</details>

**Comment by uBlock-user** [comment] 2021-06-23 05:23
Possibly related to https://github.com/gorhill/uBlock/commit/8cd2a1d263a96421487b39040c1d23eb01169484, @gorhill ?

**Comment by gorhill** [comment] 2021-06-23 12:50
I can't reproduce the issue shown in the GIF image -- and I see no connection to `google-analytics.com` in the logger.

**Comment by krystian3w** [comment] 2021-06-23 13:09
Try too with RU :Ru: / UA :ukraine: VPN.

On Polish version of page can by found request, but redirect or older dislabler is enoug to fix (I mean Poland no need commit https://github.com/uBlockOrigin/uAssets/commit/b3d5f98526ec866b92463088b96d9357335becb0).

**Comment by gorhill** [comment] 2021-06-23 13:51
I tried `https://www.olx.ua/uk/` with a Ukraine VPN and still can't reproduce -- using default lists (including RU-ADList).

**Comment by gorhill** [comment] 2021-06-23 13:59
@P0Rtvine Can you see if there are errors reported in the dev console? I can't reproduce on my side but I would like to go to the bottom of this -- there really should not be a regression from 1.35.2.

**Comment by P0Rtvine** [comment] 2021-06-23 15:06
@gorhill
Works in 1.35.2 witout **EasyPrivacy**
Don't work in 1.36.0 witout **EasyPrivacy**
### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/123120514-0e27ed00-d44d-11eb-9624-a1594f4b5443.gif)
</details>

`/js/tracking/*` ~> **EasyPrivacy**
`https://static.olx.ua/static/olxua/naspersclassifieds-regional/olxeu-atlas-web/static/js/tracking/ninja.js`

Not needed, with `/js/tracking/` 
>@@||google-analytics.com/analytics.js$script,redirect-rule,domain=olx.*,badfilter
>@@||googletagmanager.com^$script,redirect-rule,domain=olx.*,badfilter
### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/123120834-51825b80-d44d-11eb-9bd4-04fe0d83da28.gif)
</details>

@dimisa-RUAdList
`/js/tracking/*` can be added to **RU AdList: Counters**

**Comment by gorhill** [comment] 2021-06-23 15:26
Ok I can reproduce, when disabling EasyPrivacy and using the following filter to disable the filter which was added to prevent the breakage:

    @@||google-analytics.com/analytics.js$script,redirect-rule,domain=olx.*,badfilter

Investigating.

**Comment by gorhill** [comment] 2021-06-23 16:20
Ok it's because the site overload GTM's `dataLayer.push()` to execute custom code, and uBO's neutered script prevents the overload to occur. So in such case the proper fix is a filter, not a code issue.

However EasyPrivacy is meant to be used along with "uBlock filters -- Privacy", should we really add unbreak-ing filters for a configuration which is atypical and disable default filter lists?

**Comment by uBlock-user** [comment] 2021-06-23 16:25
> should we really add unbreak-ing filters for a configuration which is atypical and disable default filter lists?

```
@@||googletagmanager.com^$script,redirect-rule,domain=olx.*
@@||google-analytics.com/analytics.js$script,redirect-rule,domain=olx.*

```

Are these both not needed on Chromium with all default lists enabled ?

**Comment by gorhill** [comment] 2021-06-23 16:37
Those exceptions are not needed with default lists, as pointed out by @P0Rtvine, the filter `/js/tracking/*` in EasyPrivacy prevent `googletagmanager.com` and `google-analytics.com` from being fetched in the first place.

**Comment by dimisa-RUAdList** [comment] 2021-06-24 09:30
This solves all of the above problems: https://github.com/easylist/ruadlist/commit/6fec176c0642c4c75a544e5e83d1714c31dae511
