### ISSUE TITLE
Twitch.tv ads

### ISSUE THREAD

**Issue by furai** [uBlockOrigin/uAssets#3428] opened 2018-09-08 07:58 UTC
### URL(s) where the issue occurs

`https://www.twitch.tv/cohhcarnage` and any other live stream

### Describe the issue

Ads on Twitch get inserted for me on every Twitch stream I'm watching, right at the beginning. They are played, I think, inside the same data stream as the actual stream. They cover the actual steam window.
To reproduce this issue you'll have to have Twitch account, be logged in, don't have any subscriptions on twitch (so no Twitch prime/turbo or be subscribed to the streamer you're watching).
It won't also happen for new accounts right away as apparently Twitch sets some cookie with ID and keeps track of it so new users won't be spammed with ads right away.

### Versions

- Browser/version: Firefox Developer Edition 63.0b4 (Build ID 20180906162647)
- uBlock Origin version: uBlock Origin v1.16.20

### Settings

- I've only enabled extended list for my country. All the rest is set to the defaults after the installation.

### Notes

https://www.reddit.com/r/uBlockOrigin/comments/9d6ytl/ads_on_twitch/ << reddit topic with other people experiencing the issue. 
It started happening recently in Europe in general because Twitch haven't rolled out that feature there yet. It might happen right now only in European countries. At least that's what I heard but don't quote me anywhere on this.

**Comment by kasper93** [comment] 2018-09-08 11:00
> It started happening recently in Europe in general because Twitch haven't rolled out that feature there yet.

To make it clear this feature has been rolled out in 2016... 

uBO has been blocking those inserted ads for quite some time see https://github.com/uBlockOrigin/uAssets/issues/719 it is just now that twitch inserts ads also without "bread" parameters present in some cases. All depends on region, channel and ad provider.

**Comment by uBlock-user** [comment] 2018-09-08 18:58
Only the ones who login with accounts are suffering from this, someone with an account will need to investigate.

**Comment by furai** [comment] 2018-09-08 19:06
Most likely if you have a cookie with id that is old enough for Twitch to notice you'll get ads as well without being logged in. I believe users like that gets ads as well, else they would deprive themselves or more than a half of ads revenue. Though it's just common sense. I don't have anything to back it up.

**Comment by uBlock-user** [comment] 2018-09-08 19:09
> you'll get ads as well without being logged in

I don't have an account and I never get ads as a guest whatsoever. I have tested on several and several streams, video plays as expected.

**Comment by uBlock-user** [comment] 2018-09-08 19:28
Logged in with a disposable account, no ads either. can't reproduce.

> if you have a cookie with id that is old enough for Twitch to notice

I purge all cookies every month, is that old enough ?

**Comment by furai** [comment] 2018-09-08 19:45
The only details I have are form the top comment on reddit linked in OP.

**Comment by ZaphodBeebblebrox** [comment] 2018-09-08 19:51
Does the filter `twitch.tv##+js(cookie-remover.js, unique_id)` work for you?

**Comment by furai** [comment] 2018-09-09 06:32
Right now for some reason I'm not getting ads either with uBO enabled or disabled. Haven't changed anything. When I'll start getting ads again I'll try that filter.

**Comment by furai** [comment] 2018-09-11 09:17
Ok, tested it. I've applied the filter (added the `twitch.tv##+js(cookie-remover.js, unique_id)` to my filters list, saved it and refreshed the page). It does not work. I'm still getting ads.

**Comment by Gorshum** [comment] 2018-09-11 14:37
From doing a bit of research and tinkering around with the HTML I've found the culprit behind it but I couldn't tell you how to stop it. The issue seems to be 

<script async="" src="https://c.amazon-adsystem.com/aax2/apstag.js"></script>event

**Comment by uBlock-user** [comment] 2018-09-12 05:54
@furai Try with `||twitch.tv^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' wss: blob: *.twitch.tv www.google.com www.gstatic.com *.jtvnw.net *.ttvnw.net *.twitchcdn.net recaptcha.net`

**Comment by furai** [comment] 2018-09-12 05:59
Nope, didn't work. Just added it in 'my filters' tab. Saved, restarted browser, went to Twitch and first thing I got after checking out one of the steams was amazon ad.

**Comment by uBlock-user** [comment] 2018-09-12 06:01
> got after checking out one of the steams
Link ? Do a cache-free reload, if the ad was already cached, the filter won't have any effect.

**Comment by furai** [comment] 2018-09-12 06:03
https://www.twitch.tv/summit1g (It would happen on any first steam I visit, literally. Just gave you the one it happened for me.)
I'm going to test more.

**Comment by uBlock-user** [comment] 2018-09-12 06:17
Cant reproduce with/without an account. Video plays as expected. With that filter any 3rd party which is not mentioned in the filter won't be able to connect, which helps narrow down the source of the ads, so if you're still facing ads, it must be from inside the twitch network.

**Comment by furai** [comment] 2018-09-12 06:28
Hmm, so because of that FFZ (FrankerFazeZ) extension stopped working. I was wondering as to why. It has to contact their CDN to get the newest version.  https://github.com/FrankerFaceZ/FrankerFaceZ https://ffzap.com/ https://www.frankerfacez.com/ (These last 2 are the add-on I use for Twitch).
I have some stream in the background playing and after that filter was applied - I got some weird sound stuttering.

**Comment by uBlock-user** [comment] 2018-09-12 06:31
Twitch extensions can also pull ads, so it goes without saying to disable all extensions except for uBO when testing filters.

**Comment by furai** [comment] 2018-09-12 06:35
They're not really from Twitch just fan add-ons. But noted.

**Comment by furai** [comment] 2018-09-13 07:57
So, I've had this filter on all the time. Started up stream today - got an ad. https://www.twitch.tv/anthony_kongphan

**Comment by verlain3** [comment] 2018-09-18 19:14
someone made an extension to solve this: https://github.com/instance01/Twitch-HLS-AdBlock maybe it serves as a source on how this could be fixed with uBlock

**Comment by SW1FT** [comment] 2018-09-19 22:34
@svnhddbst probably coincidence, I stopped getting ads today for some reason

**Comment by tomkel** [comment] 2018-10-03 06:19
Looks like the ads are coming down from `https://video-weaver.***.hls.ttvnw.net/` (where *** is the closest edge on the cdn) in the form of HLS.
Here's a line from the HLS that has some telling data, maybe the response data could be inspected by ublock?
`#EXT-X-DATERANGE:ID="stitched-ad-1538546979-30186999985",CLASS="twitch-stitched-ad",START-DATE="2018-10-03T06:09:39.352Z",DURATION=30.187,X-TV-TWITCH-AD-URL="https://www.twitch.tv/primevideo"`

**Closed** 2018-11-12 22:48 UTC

**Comment by krystian3w** [comment] 2020-09-29 17:36
#5184
