### ISSUE TITLE
Anti-adblock and ads spaces not removed

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#9011] opened 2021-05-03 21:16 UTC
It's impossible to make anything unless ublock/others are disabled in the site below.

`https://sorcerers.net/index_infinity_engine_modding.php`

In the site below ads are blocked but their spaces in the top/bottom of the page arent removed.

`https://www.myabandonware.com/browse/genre/role-playing-rpg-5/popular/page/7/`

**Comment by uBlock-user** [comment] 2021-05-03 21:24
> https://sorcerers.net/index_infinity_engine_modding.php

can't reproduce, already fixed by `@@||sorcerers.net^$ghide` present in uBlock filters. Test on default settings + all other extensions disabled.

**Comment by Felipefpl** [comment] 2021-05-03 21:28
> 
> 
> > `https://sorcerers.net/index_infinity_engine_modding.php`
> 
> can't reproduce, already fixed by `@@||sorcerers.net^$ghide` present in uBlock filters. Test on default settings + all other extensions disabled.

i see, i dont use ublock filters, only fanboy's ultimate list (since it's 7 lists into 1), thanks for the reply.

**Comment by uBlock-user** [comment] 2021-05-03 21:29
As for leftover ads --

```
myabandonware.com##.j503
myabandonware.com##.j503st
myabandonware.com###screentabs > [href^="/visual/r-2/"] // on https://www.myabandonware.com/game/shadowlands-1i5
```

**Closed** 2021-05-03 21:29 UTC
