### ISSUE TITLE
tii.la: detection

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#17261] opened 2023-03-22 18:15 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/DyRaQU`

### Category

detection

### Description

Detects adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 86794
  cosmetic: 39126
  scriptlet: 17053
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64106-44, 3d.20h.23m
    easyprivacy: 31065-1172, 1d.16h.48m
    plowe-0: 3756-931, 11d.23h.13m
    ublock-abuse: 78-0, 3d.16h.20m
    ublock-badware: 5099-114, 3h
    ublock-filters: 32016-84, 3d.20h.25m
    ublock-privacy: 293-1, 3h.1m
    ublock-quick-fixes: 421-7, 2h.59m
    ublock-unbreak: 1931-39, 3d.20h.24m
    urlhaus-1: 6769-0, 2h.58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3423 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    arsnivyr.com: 1
    e2ertt.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    iclickcdn.com: 1
    trustbummler.com: 1
```
</details>

**Comment by garry-ut99** [comment] 2023-03-22 18:53
>  * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

No, a duplicate of https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+tii.la%3A+detection


> * [x]  I did not answer truthfully to **ALL** the above checkpoints.

Yes.

**Closed** 2023-03-23 19:45 UTC
Labels: unable to reproduce
