### ISSUE TITLE
Android 11 - Firefox mobile - Youtube ads under video STILL not being blocked

### ISSUE THREAD

**Issue by Candlemass** [uBlockOrigin/uAssets#11808] opened 2022-02-19 21:24 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Almost every youtube video.

### Describe the issue

Massive ad under the player isn`t being blocked.

### Screenshot(s)

https://postimg.cc/cKFnZkzV

### uBlock Origin version

1.41.2

### Browser name and version

Firefox 68.8

### Settings

Default.

### Notes

I was previoisly told that the issue was due to the "parse and enforce cosmetic filters" option being disabled. Upon initially enabling the option and clicking the apply checkmark on the top left corner of the filters menu  the problem appeared resolved. However after closing the browser the problem still remains upon opening it for use again.

Opening the filters menu and selecting any other filter and clicking the checkmark again temporarily fixes the problem but only for that session only. As soon as the browser is closed and reopened again the ads also return.

**Comment by uBlock-user** [comment] 2022-02-20 06:15
> using a new, unmodified browser profile

Create a new profile and only install uBO on it.

**Comment by uBlock-user** [comment] 2022-02-20 06:32
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11711

**Closed by uBlock-user** 2022-02-20 06:32 UTC

**Comment by gwarser** [comment] 2022-02-20 09:37
It's the https://github.com/uBlockOrigin/uBlock-issues/issues/1978

**Comment by Candlemass** [comment] 2022-02-21 00:15
I will try the suggestions there and provide feedback accordingly.
