### ISSUE TITLE
identi.li Unblocked Pop-up #2

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#1683] opened 2018-03-09 04:15 UTC
**### URL(s) where the issue occurs**

`http://www.identi.li
`

**### Describe the issue**

There are two instances of the same popup which shows up every now and then (according to cookies' state) right after doing a click anywhere on the site.

The destination address of the popup:

`http://www.navegacom.com/protect/redirect4.php
`

The cookies have a "BetterJsPop0" and "BetterJsPop1" names.

**### Screenshot(s)**

`https://i.imgur.com/lGyjh89.png
`

**### Versions**

Browser/version: [Firefox ESR v52.6.0 x64]
uBlock Origin version: [1.15.6]

**### Settings**

No changes but updating the default filters' list.

**### Notes**

This issue is very similar to this one #874, but they added a new annoying script source, which produce the same undesired effect than the previous one.

I can block "`musicatorrents.com`" with "NoScript", "uMatrix", etc., but at the expense of losing that button's functionality.

The new script seems to be this:

`http://musicatorrents.com/wp-content/themes/Alexis/js/license.js`

Thanks.

**Comment by okiehsch** [comment] 2018-03-09 04:48
`||musicatorrents.com/*/license.js$script,domain=identi.li` should work, but as already mentioned in
https://github.com/uBlockOrigin/uAssets/issues/874 the button works only after I reload the site one time.
If the filter also works for you without breaking anything, I will add it.

**Comment by KiLL4FuNK** [comment] 2018-03-09 15:36
works well it works fine you can add it   `||musicatorrents.com/*/license.js$script,domain=identi.li`

**Comment by KiLL4FuNK** [comment] 2018-03-09 15:37
@okiehsch  works well it works fine you can add it   `||musicatorrents.com/*/license.js$script,domain=identi.li`

**Comment by elsy04** [comment] 2018-03-09 16:20
I tested it, but it works erratically over here. I mean, sometimes it doesn't matter how many times I refresh the main site, the button will not work.

This is what the logger shows after a refresh:

`https://i.imgur.com/HmIqa0r.png`

The weird thing is that, even when I try it with uBlock being disabled and the popups were triggered, that erratic issue still happens.

Thanks.

**Comment by KiLL4FuNK** [comment] 2018-03-09 23:27
that are waiting to add the filter is annoying Pop-up @mapx-

||musicatorrents.com/*/license.js$script,domain=identi.li

**Comment by okiehsch** [comment] 2018-03-09 23:29
I was about to add it, how about some patience, the issue is less than 24 hours old a working filter has already been proposed and you complain, gie me a break.

**Comment by okiehsch** [comment] 2018-03-09 23:39
@elsy04 

> The weird thing is that, even when I try it with uBlock being disabled and the popups were already triggered, that erratic issue still happens.

Well, that sounds like a site issue, nothing uBlock can do about that.
The problem with this issue is that there are only two ways to fix the popup with no or minimal site breakage.

- `||musicatorrents.com/*/license.js$script,domain=identi.li` , the only "breakage" I can reproduce is the button works only after reloading one time.

- `||navegacom.com^$popunder`, this will not prevent the popunder but close it and you do not have to reload one time for the button to work.

**Comment by elsy04** [comment] 2018-03-10 10:36
I added the first filter you proposed into a firefox's profile different from that "fresh" one I use before to test it, and for some weird reason, that issue isn't happening anymore; not even once so far now and without even having to refresh the site. :) I'd been trying to figure out how that could be possible, and I think I already know it.

**Closed** 2018-03-10 10:50 UTC

**Comment by elsy04** [comment] 2018-04-06 14:40
Just for the record:

Since today, the button ceased to work once again, and I found out that the problem is being caused by some "Easy List Spanish" filter. But this time it seems it's not enough to add a "badfilter" tag to the presumably problematic filters, and thus avoiding the whole list disabling. I added these ones:

```
||identi.li/cacho/license*.js$script,badfilter
||musicatorrents.com/wp-content/themes/*/js/script.js,badfilter
||musicatorrents.com^$script,third-party,badfilter
```
But I still have to disable the whole list, so the button keeps working fine using the  relevant @okiehsch filter from this thread.

`https://forums.lanik.us/viewtopic.php?p=134423#p134423`
