### ISSUE TITLE
youtube.com: ads crashig. Don't work fine.

### ISSUE THREAD

**Issue by latoto** [uBlockOrigin/uAssets#17465] opened 2023-04-06 16:48 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=lT72sXOXFiU`

### Category

ads

### Description

youtube.com: ads crashig. Don't work fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 91766
  cosmetic: 45261
  scriptlet: 17849
  html: 941
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 34237-206, 3h.28m
    ublock-badware: 6297-10, 3h.27m
    ublock-privacy: 343-0, 8d.7h.52m
    ublock-abuse: 78-0, 8d.7h.51m
    ublock-unbreak: 1970-2, 3h.26m
    ublock-quick-fixes: 477-0, 23h.35m
    easylist: 65110-657, 1d.22h.1m
    easyprivacy: 30766-1785, 4d.10m
    urlhaus-1: 7056-0, 23h.34m
    plowe-0: 3752-2, 6d.16h.23m
    spa-0: 3561-1, 23h.36m
    spa-1: 5156-141, 3h.29m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 196 ms (selfie)
  maxAssetCacheWait: 62 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    doubleclick.net: 2
    youtube.com: 14
```
</details>

**Comment by gorhill** [comment] 2023-04-06 17:44
Duplicate of #7636

**Closed by gorhill** 2023-04-06 17:44 UTC
