### ISSUE TITLE
primevideo.com: ads / breakage

### ISSUE THREAD

**Issue by Little-kinder** [uBlockOrigin/uAssets#14512] opened 2022-08-23 23:15 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.primevideo.com/detail/0I9WIZH5APM3UJADMTTEIR9QGS/ref=atv_hm_hom_1_c_cjm7wb_5_1`

### Category

ads

### Describe the issue

ads between videos on prime video, any chance you could block then or auto click the skip button?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 100804
  cosmetic: 54356
  scriptlet: 17620
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 37-8, never
    FRA-0: 30469-23, 2d.8h.57m
    easylist: 69604-118, 2d.8h.55m
    easyprivacy: 27396-429, 2d.8h.54m
    plowe-0: 3629-784, 10d.9h.24m
    ublock-abuse: 76-1, 10d.9h.25m
    ublock-badware: 4259-106, 2d.8h.53m
    ublock-filters: 32537-269, 2d.8h.56m
    ublock-privacy: 231-3, 11d.12h.32m
    ublock-unbreak: 1838-41, 14h.34m
    urlhaus-1: 4707-0, 10h.33m
filterset (user): [array of 37 redacted]
trustedset: 
  added: [array of 22 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 250 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 125
  blockedDetails: 
    primevideo.com: 12
    amazon.com: 113
```
</details>

**Comment by MasterKia** [comment] 2022-08-24 03:51
[They're using](https://github.com/uBlockOrigin/uAssets/issues/13906#issuecomment-1173444368) server side ad injection (SSAI).

SSAI issues: https://github.com/uBlockOrigin/uAssets/issues/1905

**Comment by krystian3w** [comment] 2022-08-29 00:53
@[mapx-](https://github.com/mapx-) mapx- added the[ SSAI ](https://github.com/uBlockOrigin/uAssets/labels/SSAI)label [on 7 Apr 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1562292997)
@[jspenguin2017](https://github.com/jspenguin2017) [jspenguin2017](https://github.com/jspenguin2017) mentioned this issue on 9 May 2018
[Ads] cwtv.com NanoAdblocker/NanoFilters#25
Closed
@jspenguin2017 jspenguin2017 mentioned this issue on 3 Jun 2018
nbc.com #2409
Closed
@[okiehsch](https://github.com/okiehsch) okiehsch changed the title Cwtv video ads Websites using SSAI (server side ad injection) [on 3 Jun 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1659832690)
This was referenced on 3 Jun 2018
Viceland Video Ads #1541
Closed
uBO on Chrome not blocking fox.com #772
Closed
abc7.com #794
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 22 Jul 2018
[Anti-adblock] investigationdiscovery.com #2966
Closed
@[SkeletalDemise](https://github.com/SkeletalDemise) SkeletalDemise mentioned this issue on 22 Jul 2018
anti Adblocker on discovery.com sciencechannel.com #2931
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 2 Sep 2018
Ads Loading gorhill/uBO-Extra#76
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 15 Sep 2018
Ads while watching shows on FOX #3486
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 27 Oct 2018
Midroll Ads Aren't being blocked CityTV.com #3847
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 17 Nov 2018
rediff.com | Tracking #4138
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 23 Nov 2018
Fails to Block Ads on The CW - http://thecwtv.com #4179
Closed
@[stoically](https://github.com/stoically) stoically mentioned this issue on 20 Mar 2019
ALL twitch.tv issues #5184
Open
@[okiehsch](https://github.com/okiehsch) okiehsch mentioned this issue on 11 Jun 2019
https://www.brighteon.com/ #5803
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 17 Jun 2019
discovery.com videos not working easylist/easylist#3636
Closed
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment from [prateekrastogi](https://github.com/prateekrastogi) [on 26 Jan 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-2979959103)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user added the[ can't fix ](https://github.com/uBlockOrigin/uAssets/labels/can%27t%20fix)label [on 17 Jun 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-3453347081)
@[nebchan](https://github.com/nebchan) nebchan mentioned this issue on 29 Sep 2020
Twitch TV now injecting ads #7968
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 1 Nov 2020
Add queryprune filters to deal with SSAI #8131
Merged
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 16 Aug 2021
pluto.tv: Ads not being blocked #9764
Closed
6 tasks
@[subby2006](https://github.com/subby2006) subby2006 mentioned this issue on 1 Sep 2021
sbs.com.au ondemand has a new player and it detects ublock #7836
Closed
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 20 Jan
@uBlock-user
[update](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-394129540
[eb9148f](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a)
This was referenced on 21 Jan
go.tlc.com: ads #11419
Closed
go.discovery.com: ads #11420
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user closed this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/ac8860312f726292bd3e7c2f34a82f6d20614dbe [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035560189)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user reopened this [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035564682)
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 9 Feb
@uBlock-user
[append](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-1033865488
[fe89b1b](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 17 Feb
discovery plus italy showing ads #11772
Closed
6 tasks
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment [on 9 Mar](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6207603084)
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 25 Mar
hulu.com: ads #12407
Closed
8 tasks
This was referenced on 27 Mar
philo.com: ads #12469
Closed
player.stv.tv: ads #12513
Closed
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 Apr
mech-plus.com: ads #12589
Closed
8 tasks
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 May
amc.com: ads #13065
Closed
8 tasks
This was referenced on 4 Jul
primevideo.com: ads #13906
Closed
animalplanet.com: ads #13969
Closed
tvbanywherena.com: video ads #13978
Closed
This was referenced 23 days ago
vix.com: ads #14213
Closed
discoveryplus.com: ads #10870
Closed
discoveryplus.com: ads #14365
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue 6 days ago
go.tlc.com: ads #14451
Closed
8 tasks
@[MasterKia](https://github.com/MasterKia) MasterKia mentioned this issue 5 days ago
primevideo.com: ads #14512

**Comment by Yuki2718** [comment] 2023-05-19 09:33
Recent fix in AG: https://github.com/AdguardTeam/AdguardFilters/commit/1ba6e0700e1bc3a2f26f3312cef11cd4d59d5152
But https://github.com/AdguardTeam/AdguardFilters/issues/148543#issuecomment-1549769106

**Comment by mapx-** [comment] 2023-05-19 09:55
maybe is translated as

```
amazon.com##+js(xml-prune, Period:\has([value="Ad"]), , .mpd)
amazon.com##+js(json-prune, cuepointPlaylist)
```

?

**Comment by stephenhawk8054** [comment] 2023-05-19 09:57
Although it's not related to Prime account, but Amazon has some videos to watch free with ads (only need an Amazon account). I do see the XML file with `Period` that has ads in it, but somehow 

```adb
amazon.com##+js(json-prune, cuepointPlaylist)
amazon.com##+js(xml-prune, Period, , .mpd)
```

or any selectors related to `Period` does not work for me. I have tested and similar `xml-prune` filters work on discoveryplus-sites.

**Comment by krystian3w** [comment] 2023-05-19 09:59
Just wait ~60 minutes and the AdGuard script will upload translations for uBo:

> ![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/cbf262d1-b461-4ffc-bf58-6b3195835148)

**Comment by stephenhawk8054** [comment] 2023-05-19 10:05
Yep, usually for SSAI sites, when I use `xml-prune` or `m3u-prune`, I have to find a `json-prune` to cut off their "cuepoints". Using former will make navigation bar not working, and using latter will make timer wrong with ads still play instead.

> Now I can't test as I used up free test preod of Prime.

With the link OP has in recent amazon thread, you can watch free with normal account I think. Given the filters Adguard had, and what I found in the XML file, I think the structure are quite the same: https://pastebin.grey.pw/?0e687eb39fd70196#D4B5uLG8Sp3ckPnMnBxQym5Bu2MGHBnyMgH8oEuJrktt

**Comment by mapx-** [comment] 2023-05-19 10:23
using a normal amazon account + us vpn => I see no ads

**Comment by Little-kinder** [comment] 2023-05-19 10:33
Will try to watch in Canada if I can help

Le ven. 19 mai 2023, 06:30, stephenhawk8054 ***@***.***> a
écrit :

**Comment by mapx-** [comment] 2023-05-19 10:39
The problem is I see no cuepoints or ads even disabling those filters, so .. it's difficult to say if works or not

**Comment by stephenhawk8054** [comment] 2023-05-19 10:41
Did you see a short countdown at the beginning, like an ad intro?

**Comment by mapx-** [comment] 2023-05-19 10:51
I see only the normal "skip intro"

**Comment by stephenhawk8054** [comment] 2023-05-19 10:53
I see. Looks like they serve different contents depending on account I guess.

**Comment by Little-kinder** [comment] 2023-05-19 10:54
Yep. Let me know if I can help by testing anything.

Le ven. 19 mai 2023, 06:53, stephenhawk8054 ***@***.***> a
écrit :

**Comment by stephenhawk8054** [comment] 2023-05-19 10:56
@Little-kinder Can you test the filters in this comment? https://github.com/uBlockOrigin/uAssets/issues/14512#issuecomment-1554325057

**Comment by stephenhawk8054** [comment] 2023-05-28 07:01
So with latest update of `xml-prune`, these filters work for me:

```adb
amazon.com##+js(json-prune, cuepointPlaylist)
amazon.com##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="SupplementalProperty"][@value="Ad"]]), , .mpd)
```

**Comment by Yuki2718** [comment] 2023-07-16 14:38
json-prune/xml-prune no more works, nothing is logged. For AG I'm going to readd https://github.com/AdguardTeam/AdguardFilters/commit/cb4900805ad9972c99cee421bacf825906c49ef5 which still works. Will we support trusted-click-element?

**Comment by stephenhawk8054** [comment] 2023-07-16 14:44
@Yuki2718 Do you have any free link?

**Comment by Yuki2718** [comment] 2023-07-16 14:48
I don't, I temp subscirbed Prime.

**Comment by stephenhawk8054** [comment] 2023-07-16 14:53
I found one here (with US IP): `https://www.amazon.com/gp/video/detail/B086HX1N45`. But I don't know where the ads is (even when disabling scriptlets).

**Comment by Yuki2718** [comment] 2023-07-16 14:59
I don't have an `amazon.com` account so can't test.

**Comment by stephenhawk8054** [comment] 2023-07-16 15:04
Hmmm... I tested with another link that has ads, and the ads are blocked as expected for me.

Can you check in the network devtools if there are any xml / mpd / m3u8 connections and copy paste here if there is?

**Comment by Yuki2718** [comment] 2023-07-16 15:10
Maybe on Slack or internal discussion, as it's my real account.

**Comment by Yuki2718** [comment] 2023-07-16 15:13
Oh, wait... I again made very elementary mistake. I used a rule for `amazon.com` despite mine is `co.jp`. Have to recheck.

**Comment by Yuki2718** [comment] 2023-07-16 15:21
The rules in https://github.com/uBlockOrigin/uAssets/issues/14512#issuecomment-1565946605 are working fine for `amzon.co.jp`. I'll remove the click rule from AG and exapnd domain. Probably we can adopt the same.

**Comment by Yuki2718** [comment] 2023-07-16 15:22
Also I certainly see `xmlPrune: Element.Period removed`

![amazon](https://github.com/uBlockOrigin/uAssets/assets/58900598/e6ade3a1-83c7-4d5d-afdf-aef1e5b14513)

**Comment by D4niloMR** [comment] 2023-11-27 22:55
> So with latest update of `xml-prune`, these filters work for me:
> 
> ```
> www.amazon.com##+js(json-prune, cuepointPlaylist)
> www.amazon.com##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] | //*[name()="Period"]/@start), [value="Ad"], .mpd)
> ```

@stephenhawk8054 

Those filters works for me, but in `www.primevideo.com` can primevideo be add to this filter?

The content here is displayed in primevideo, not amazon
<details><summary>Screenshot</summary>
<p>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/db11bb42-4d63-40ae-8720-812ec4c427da)

</p>
</details> 
<hr>

I remember trying those 2 before, maybe I tested wrong.

**Comment by punisher018** [comment] 2024-12-14 17:51
I have the same subtitle synchronization problem. Not always but sometimes, probably when it tries to open a commercial video. The subtitle is delayed for about 10 - 15 seconds. When I close uBlock, it gets better. 
@stephenhawk8054 I can send you my account credentials.

**Comment by stephenhawk8054** [comment] 2024-12-15 02:10
@punisher018 Thanks, can you send to this email: `stephenhawk8054@protonmail.com`

**Comment by stephenhawk8054** [comment] 2024-12-15 10:33
@punisher018 Can you test this filter:

```adb
primevideo.com##+js(json-prune, vodPlaybackUrls.result.playbackUrls.cuepoints)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by punisher018** [comment] 2024-12-15 10:44
Looks like it's fixed. I have opened more than 10 videos without any synchronization problems. Thanks @stephenhawk8054

**Closed** 2024-12-15 10:56 UTC
Labels: SSAI, geo specific, account required
