### ISSUE TITLE
myshows.me: ads

### ISSUE THREAD

**Issue by YWxvbmU** [uBlockOrigin/uAssets#15178] opened 2022-10-07 02:20 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myshows.me/profile/`

### Category

ads

### Describe the issue

you must be logged in to see the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/115200742/194452363-fd6a1820-d474-496f-84b8-c5c3b779d24e.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b9
Chromium: 104
filterset (summary): 
  network: 104881
  cosmetic: 61280
  scriptlet: 19401
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1526-0, 22m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 22m
  default: 
    user-filters: 1-0, never
    RUS-0: 40658-60, 22m
    easylist: 62498-84, 22m
    easyprivacy: 30694-1799, 22m
    plowe-0: 3672-870, 22m
    ublock-abuse: 76-5, 22m
    ublock-badware: 4341-105, 22m
    ublock-filters: 33077-161, 22m
    ublock-privacy: 249-1, 22m
    ublock-quick-fixes: 313-12, 22m
    ublock-unbreak: 1866-43, 22m
    urlhaus-1: 8841-0, 22m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1267 ms (selfie)
  maxAssetCacheWait: 198 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    myshows.me: 15
    adfox.ru: 1
    clickiocdn.com: 1
    googletagmanager.com: 1
    yandex.ru: 5
```
</details>

**Comment by mapx-** [comment] 2022-10-07 07:05
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment] 2022-10-07 08:07
When I log into my account, I do not see ads on the stated link. And on the screenshot of the issue-starter, advertising is also not displayed.

**Comment by YWxvbmU** [comment] 2022-10-07 13:48
I don't know why, but this problem persists only in development build

**Comment by mapx-** [comment] 2022-10-07 13:53
closing for now, if you are able to provide specific steps for reproduce the ads just comment here again

**Closed by mapx-** 2022-10-07 13:53 UTC
Labels: unable to reproduce, account required, to be fixed by regional list

**Comment by dimisa-RUAdList** [comment] 2022-10-07 18:32
I think I figured out what's going on: https://github.com/gorhill/uBlock/commit/a71b71e4c8a2037fc68970bc8912a76732edaade

The problem is repeated exactly in the version: uBlock Origin development build 1.44.5b9

<details>
<summary>Screenshot(s)</summary>

![](https://user-images.githubusercontent.com/20126984/194625765-3688cf43-6563-4516-a567-19af3b6aab35.jpg)

</details>

And it looks like the problematic rule is contained in uBlock filters.

In uBlock Origin development build 1.44.5b11 this problem is gone.
