### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by minivanman591** [uBlockOrigin/uAssets#18224] opened 2023-05-24 23:42 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.facebook.com/marketplace

### Category

ads

### Description

"Sponsored" ads appeared today. Forced an update and refreshed the page. It did not resolve the issue. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94047
 cosmetic: 38954
 scriptlet: 17540
 html: 943
listset (total-discarded, last-updated): 
 default: 
  user-filters: 5-0, never
  ublock-filters: 34019-39, 1d.2h.41m
  ublock-badware: 7169-0, 1d.2h.41m
  ublock-privacy: 444-0, 12d.1h
  ublock-abuse: 70-70, 12d.59m
  ublock-unbreak: 2032-0, 1d.2h.41m
  easylist: 66390-668, 1h.1m
  easyprivacy: 31825-29, 4d.8h.18m
  urlhaus-1: 7012-1, 1h
  plowe-0: 3742-590, 13d.3h.19m
  ublock-quick-fixes: 367-41, 9h.48m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 27178 ms (selfie)
 maxAssetCacheWait: 507 ms
popupPanel: 
 blocked: 13
 network: 
  facebook.com: 1
  doubleclick.net: 3
  fbcdn.net: 7
  google.com: 1
  googleadservices.com: 1
 cosmetic: 
  ##.AdBox
  ##.post-ads
  ##.ob-hover
  ##.xl405pv.x19991ni.x1d8287x.x13vifvy.x17qophe.x10l6tqk.xl56j7k.xdt5ytf.xds687c.x78zum5.x9f619.x1ey2m1c.xjb1437.x6s0dn4
```
</details>

**Comment by gorhill** [comment] 2023-05-25 00:46
> - [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+sort%3Aupdated-desc+%22facebook.com%22+in%3Atitle

Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/3367>.

**Closed by gorhill** 2023-05-25 00:46 UTC
