### ISSUE TITLE
[nsfw] tech24us.com: ads

### ISSUE THREAD

**Issue by ZakieMax** [uBlockOrigin/uAssets#15469] opened 2022-10-29 18:36 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tech24us.com/`

### Category

ads

### Describe the issue

in past ublock was blocking all time timer in this website but at present it's not blocking the countdown timer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Screenshot_20221030_003404](https://user-images.githubusercontent.com/72064945/198847560-ba089517-e55c-4943-9541-c9eda7eeae7a.png)

![Screenshot_20221030_003417](https://user-images.githubusercontent.com/72064945/198847561-4510d258-3c85-4908-822e-8b3da784ff4a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88496
  cosmetic: 38304
  scriptlet: 17745
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62309-53, 3d.9h.3m
    easyprivacy: 30811-1170, 3d.9h.2m
    plowe-0: 3675-865, 11d.1h.32m
    ublock-abuse: 76-0, 11d.1h.30m
    ublock-badware: 4352-109, 2d.5h.49m
    ublock-filters: 32277-130, 2d.5h.48m
    ublock-privacy: 257-1, 11d.1h.22m
    ublock-quick-fixes: 435-21, 1d.2h.57m
    ublock-unbreak: 1872-42, 2d.5h.47m
    urlhaus-1: 11029-0, 12h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 982 ms (selfie)
  maxAssetCacheWait: 466 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    doubleclick.net: 1
    googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment] 2022-10-29 21:56
Can you give original link that redirects to that page?

**Comment by stephenhawk8054** [comment] 2022-10-31 09:01
Please give exact URL

**Comment by stephenhawk8054** [comment] 2022-10-31 09:58
Ah ok I understand now.

@iSmokeMid69 Sorry I thought you were OP and I was lost with the unformatted comment.

**Comment by stephenhawk8054** [comment] 2022-11-01 00:31
I can only reproduce the `tech24us.com` and `namemeaningbengali.com` domains but as the button on `namemeaningbengali.com` is already on the top, I think we don't need to use `others()` there.

**Comment by stephenhawk8054** [comment] 2022-11-01 02:43
So I guess the issue is solved? If yes we can close this thread.

**Closed** 2022-11-01 02:59 UTC

**Comment by ZakieMax** [comment] 2022-11-03 16:51
yeah i got the solution.. Thanks for you kind consideration
