### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by Mystery9-6** [uBlockOrigin/uAssets#20419] opened 2023-11-02 21:23 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aternos.org/server/`

### Category

detection

### Description

aternos detects ublock, seeing as it can push anti-youtube filters quickly, it should be no problem

might also be worth noting that the last update on this was months ago.

### Other extensions used

tampermonkey for anti-antiadblock userscript

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 104723
 cosmetic: 40325
 scriptlet: 18811
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 22-6, now
  easylist: 72285-15, now
  easyprivacy: 32852-64, now
  plowe-0: 3729-1070, now
  ublock-badware: 7421-138, now
  ublock-filters: 35126-145, now
  ublock-privacy: 641-6, now
  ublock-quick-fixes: 227-133, now
  ublock-unbreak: 2133-32, now
  urlhaus-1: 11180-0, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 33 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 428 ms (selfie)
 maxAssetCacheWait: 140 ms
popupPanel:
 blocked: 13
 network:
  aternos.org: 1
  ad-delivery.net: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  exelator.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  quantcast.com: 1
  script.ac: 1
  upapi.net: 1
  venatusmedia.com: 1
  vntsm.com: 1
```
</details>

**Comment by gorhill** [comment] 2023-11-02 22:54
> - [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Duplicate of #13144

**Closed by gorhill** 2023-11-02 22:54 UTC
