### ISSUE TITLE
WashingtonPost.com anti-adblock

### ISSUE THREAD

**Issue by michaelchany** [uBlockOrigin/uAssets#7224] opened 2020-04-13 00:09 UTC
### URL(s) where the issue occurs

`https://www.washingtonpost.com/science/2020/04/12/storm-inside/?arc404=true`

### Describe the issue

It doesn't happen all the time, but occasionally the "we've noticed you're blocking ads" script will appear.  There is a filter on the main ublock filters list, starting on line 17956, that appears to be meant to filter it out, but perhaps there are recent changes on the website side.

### Screenshot(s)

![Screenshot_2020-04-12 The storm inside](https://user-images.githubusercontent.com/22213879/79082861-f5fffe00-7cde-11ea-80ec-1809351d6634.jpg)

### Versions

- Browser/version: FF 75.0
- uBlock Origin version: v1.26.0

### Settings

- (Is there any easy way to export all settings into text for GitHub reports?)

NanoBlocker installed

uBlock: main list, badware, privacy, abuse, and unbreak
AdGuard Base
Malware Domains List, malware domains, Spam404
AdGuard Annoyances, AdGuard Social Media; Fanboy Annoyances; uBlock filters - annoyances
Dan Pollock's hosts file, Peter Lowe's ad/tracking list
Adblock Warning Removal List
Filter unblocking search ads/self-promotion
Malvertising filter list (by Disconnect)
Nano Defender integration, filters, filters - whitelist

### Notes

[Issue 6339](https://github.com/uBlockOrigin/uAssets/issues/6339) discussed this issue back in September 2019.

**Comment by mapx-** [comment] 2020-04-13 06:40
It was repeatedly reported at Nano repository but nobody can reproduce the issue.
Try a fresh setup of Nano / uBO

**Comment by uBlock-user** [comment] 2020-04-13 06:45
I repro'd it only the first time I visited that link after that, back to normal.

**Comment by okiehsch** [comment] 2020-04-13 06:54
Looks like https://www.washingtonpost.com/science/2020/04/12/storm-inside/?arc404=true to me.

**Comment by okiehsch** [comment] 2020-04-13 06:57
I can reproduce on the first page load if I copy/paste
````
washingtonpost.com/science/2020/04/12/storm-inside/?arc404=true
````
If I paste
````
https://www.washingtonpost.com/science/2020/04/12/storm-inside/?arc404=true
````
I can't reproduce.

**Comment by uBlock-user** [comment] 2020-04-13 07:05
Sounds like a race condition, shouldn't occur because we're using an HTML filter.

**Comment by uBlock-user** [comment] 2020-04-13 07:07
Okay I reproed it again via `washingtonpost.com/science/2020/04/12/storm-inside/?arc404=true` seems the bug is not completely fixed.

**Comment by okiehsch** [comment] 2020-04-13 07:08
Yes, if you paste `washingtonpost.com/science/2020/04/12/storm-inside/?arc404=true`
our HTML filter does not appear in the logger, it never gets applied, if you then reload the filter appears and the issue is gone.

**Comment by uBlock-user** [comment] 2020-04-13 07:10
Sent feedback - https://bugzilla.mozilla.org/show_bug.cgi?id=1623921#c12

**Comment by okiehsch** [comment] 2020-04-13 07:12
According to the bug tracker it is fixed in Firefox 77.

**Comment by uBlock-user** [comment] 2020-04-13 07:14
I'm reproducing it on Nightly.

**Comment by gwarser** [comment] 2020-04-13 13:12
washingtonpost.com##^script:has-text(adblocker)


I cannot reproduce. I see script with many "adblocker" words in view-source, but not in DOM. Do you see this screen on first load?

![image](https://user-images.githubusercontent.com/886325/79122850-13919e00-7d99-11ea-8c0c-4921afc63313.png)

**Comment by gwarser** [comment] 2020-04-13 13:34
Can be tested with:

    https://httpbin.org/redirect-to?url=https%3A%2F%2Fgorhill.github.io%2FuBlock%2Ftests%2Fprocedural-html-filters.html&status_code=302

Just change `status_code=302`.

**Comment by uBlock-user** [comment] 2020-04-13 13:48
Yes, I reported that status-code at BMO.

**Closed** 2020-04-14 07:46 UTC
Labels: external
