### ISSUE TITLE
[nsfw] lover92.net: detection

### ISSUE THREAD

**Issue by mepho6** [uBlockOrigin/uAssets#14529] opened 2022-08-25 16:41 UTC

**Comment by MasterKia** [comment] 2022-08-25 18:12
@piquark6046

Maybe:
```
lover92.net##+js(ra, oncontextmenu|ondragstart|onselectstart, body, complete)
||tistory1.daumcdn.net/tistory/*/skin/images/mainsite.js^$script,domain=lover92.net
||tistory1.daumcdn.net/tistory/*/skin/images/bl1.js^$script,domain=lover92.net
||cdn.tapioni.com/vast-im.js^$script,redirect=noop.js,domain=lover92.net
```

**Comment by piquark6046** [comment] 2022-08-25 18:17
@MasterKia The website changes its domain regularly.
Please wait...

**Comment by MasterKia** [comment] 2022-08-25 18:17
Instead of the last one, this should work but I don't know why it doesn't: `##script[onerror]:remove()`

**Comment by piquark6046** [comment] 2022-08-25 18:27
It has a history falsification script.
@MasterKia Does any uAssets filter list block it?

**Comment by piquark6046** [comment] 2022-08-25 18:29
<details>
<summary>screenshot</summary>

![Screenshot from 2022-08-25 18-28-20](https://user-images.githubusercontent.com/98787049/186741440-e5e24b34-7a27-43ae-a966-4084a04e4a6d.png)

</details>

**Comment by okiehsch** [comment] 2022-08-25 18:38
@MasterKia I can't reproduce.

**Comment by MasterKia** [comment] 2022-08-25 18:41
Could you test on this page?
`https://lover92.net/index.php?mid=link1&document_srl=21359`

**Comment by MasterKia** [comment] 2022-08-25 18:42
@piquark6046 No.
Why they do this?

**Comment by piquark6046** [comment] 2022-08-25 18:44
> Why they do this?

I don't know.

> No uAssets filter removes that.

@JobcenterTycoon said "a history falsification can be fixed by uAssets filter list"

**Comment by MasterKia** [comment] 2022-08-25 18:46
You said: "Does any uAssets filter list [currently] block it?
And I said no.

**Comment by MasterKia** [comment] 2022-08-25 18:47
@piquark6046 Your filter list has `js` rules so why don't you add `lover92.net##+js(acis, history)` assuming it works?

**Comment by piquark6046** [comment] 2022-08-25 18:48
List-KR blocks only anti-adblock and advertisement as description of List-KR repo.

**Comment by MasterKia** [comment] 2022-08-25 18:49
And why does the arbitrary definition doesn't include tracking or annoyance? Just curios.

**Comment by piquark6046** [comment] 2022-08-25 18:52
> And why does the arbitrary definition doesn't include tracking or annoyance? Just curios.

Because I contribute to AdguardFilters to resolve tracker and annoyance.
https://github.com/AdguardTeam/AdguardFilters/pulls?q=is%3Apr+author%3Apiquark6046

**Comment by MasterKia** [comment] 2022-08-25 18:54
So now the user has to enable _two_ additional lists to benefit from all Korean related filters.

**Closed** 2022-08-28 11:25 UTC
Labels: ongoing, to be fixed by regional list
