### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by qq221934320** [uBlockOrigin/uAssets#14242] opened 2022-08-04 02:13 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

breakage

### Describe the issue

The page contained broadcasts flashed frequently. It needs to be fixed as soon as possible. Thank you.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/50503500/182747808-1d19250d-23ed-4780-8ddc-58eae3f74fb6.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98417
  cosmetic: 55394
  scriptlet: 17662
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-5, never
    CHN-0: 28965-92, 3d.8h.18m
    easylist: 68909-73, 3d.8h.22m
    easyprivacy: 27463-149, 3d.8h.24m
    plowe-0: 3640-781, 10d.57m
    ublock-abuse: 76-0, 20h.25m
    ublock-badware: 4221-92, 3d.8h.23m
    ublock-filters: 32352-134, 3d.8h.20m
    ublock-privacy: 230-3, 20h.23m
    ublock-quick-fixes: 344-2, 1d.32m
    ublock-unbreak: 1851-43, 3d.8h.12m
    urlhaus-1: 4957-0, 1d.31m
filterset (user): [array of 7 redacted]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 691 ms (selfie)
  maxAssetCacheWait: 349 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    bilibili.com: 33
    hdslb.com: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-04 02:22
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

> - [X] I did not answer truthfully to **all** the above checkpoints

Please read and answer the Prerequisites carefully instead of **_blindly ticking them_**.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14210 https://github.com/uBlockOrigin/uAssets/issues/14232 https://github.com/uBlockOrigin/uAssets/issues/14236

Force update the filter lists and test again:
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Closed** 2022-08-04 08:01 UTC
