### ISSUE TITLE
digiday.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#447] opened 2017-06-09 04:51 UTC
Hi,

**Versions**

uBlock Origin 1.12.5.17 / Chromium 58 (64-bit)

**Settings**

Default settings

**URL**

`https://digiday.com/marketing/wtf-ads-txt/`

**Describe the issue**

Advertorial.

**Screenshots**

http://i.imgur.com/ra2qDyp.png

**Suggested filter**

`digiday.com###ipu_article_article`

**Note**

Reported 2 months ago https://forums.lanik.us/viewtopic.php?f=62&t=36252

**Comment by okiehsch** [comment] 2017-06-09 19:00
@gorhill in principle I will only add a filter if 
1.  It is a uBO specific filter i.e. redirect, procedural cosmetic filters etc.
2.  If a non uBO specific filter is needed to circumvent some anti-adblock mechanism, which prohibits
the use of the website and which has not been fixed by Easylist after it was reported some time ago.

Are you in favour of adding non uBO specific filters with cases like `digiday.com`?

**Comment by gorhill** [comment] 2017-06-09 19:23
About point 2, I changed my view on this, now I add without delay and we can remove it whenever the it's solved in EasyList -- after all I just want users to have the best experience and adding to uBO's filters make sure the issue is fixed ASAP.

**Comment by okiehsch** [comment] 2017-06-09 19:47
That makes sense , but what about this `digiday.com###ipu_article_article`  issue, it doesn't circumvent some anti-adblock mechanism that prohibits the use of the website , it simply hides an ad.

**Comment by gorhill** [comment] 2017-06-09 21:56
> it simply hides an ad. 

Then it should be added to uBlock filters, and removed at some point when it's in EasyList.

Eventually maybe I will find the time to create an online tool to find duplicates between two lists so we could just use that once in a while to remove those filters that were also added to EasyList afterward.

**Closed** 2017-06-09 22:27 UTC

**Comment by SMed79** [comment] 2017-06-10 03:01
> I will find the time to create an online tool to find duplicates between two lists

From time to time this how i check for redundancy filters between EL an FR/AR list.

`awk 'NR==FNR{lines[$0]++; next} $1 in lines' easylist.txt liste_fr.txt > duplicates.txt`

I also use Famlam script https://arestwo.org/famlam/redundantRuleChecker.html
