### ISSUE TITLE
einthusan.tv: ads

### ISSUE THREAD

**Issue by dineshk-l** [uBlockOrigin/uAssets#11361] opened 2022-01-18 11:30 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://einthusan.tv/adblocker/`

### Category

ads

### Describe the issue

detects adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 94
filterset (summary): 
  network: 79567
  cosmetic: 41852
  scriptlet: 19191
  html: 624
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4364-4, 17h.49m
  default: 
    ublock-filters: 30734-31, 17h.52m
    ublock-badware: 3728-1, 17h.52m
    ublock-privacy: 187-0, 17h.52m
    ublock-abuse: 76-0, 17h.52m
    ublock-unbreak: 1693-0, 17h.52m
    easylist: 63067-591, 17h.52m
    easyprivacy: 26627-480, 17h.52m
    urlhaus-1: 8337-0, 17h.52m
    plowe-0: 3682-2, 17h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1800 ms (selfie)
popupPanel: 
  blocked: 19
  no-cosmetic-filtering: true
```
</details>

**Comment by uBlock-user** [comment] 2022-01-18 11:47
> I verified that the issue has not already been reported (use this button to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11351

**Closed by uBlock-user** 2022-01-18 11:47 UTC
