### ISSUE TITLE
nytimes.com detects private browsing

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#5677] opened 2019-05-27 03:14 UTC
### URL(s) where the issue occurs

`https://www.nytimes.com/2019/05/23/science/spacex-launch.html`

### Describe the issue

A few seconds after the page loads, the site will detect that you're visiting it in private browsing mode and will hide all of the content.

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: 1.19.6

### Settings

- All defaults

### Notes

`nytimes.com##+js(abort-on-property-read.js, window.indexedDB)` fixes it for me, but interestingly, `nytimes.com##+js(set-constant.js, window.indexedDB, undefined)` does not.

**Comment by okiehsch** [comment] 2019-05-27 03:20
I can't reproduce.
![image](https://user-images.githubusercontent.com/16838044/58393453-14b1c380-803f-11e9-9f40-c75c3a1f2ff7.png)

**Comment by josephcsible** [comment] 2019-05-27 03:22
Hmm, I can reproduce it on my Linux box but not my Windows box (both same browser and uBO versions). I'll poke around a bit to try to figure out why.

**Comment by josephcsible** [comment] 2019-05-27 03:27
I created a completely new profile in Windows, installed uBO without doing anything else, then went there in private browsing mode, and then I could reproduce it there.

**Comment by okiehsch** [comment] 2019-05-27 03:32
I can't reproduce with Linux or Windows on my end.

**Comment by josephcsible** [comment] 2019-05-27 03:33
Did you try with a fresh profile?

**Comment by okiehsch** [comment] 2019-05-27 03:35
With Firefox, I only use it to test filters anyway, so it is a default installation + uBO.

**Comment by okiehsch** [comment] 2019-05-27 03:37
Let's wait and see if other users can reproduce,

**Comment by josephcsible** [comment] 2019-05-27 03:38
I think they might be doing some kind of A/B testing or something, where not every request has the malicious code. I just opened my original Windows Firefox profile again (the one that I didn't repro on before), and now I do repro there.

**Comment by josephcsible** [comment] 2019-05-30 18:14
This is definitely still happening. Can it be reopened?

**Comment by yourduskquibbles** [comment] 2019-05-30 19:04
I could reproduce on Test Firefox profile on Windows 10 with only uBO & stock filters.

**Comment by mapx-** [comment] 2019-05-30 19:10
does the OP filter fixes the issue ?
`nytimes.com##+js(abort-on-property-read.js, window.indexedDB)`

**Comment by okiehsch** [comment] 2019-05-30 19:26
I still can't reproduce.
When the private browsing mode of Firefox is enabled, the IndexedDB throws an InvalidStateError because it is not available in private browsing mode, so the mentioned filter probably works.

**Comment by yourduskquibbles** [comment] 2019-05-30 23:37
@josephcsible `nytimes.com##+js(abort-on-property-read.js, window.indexedDB)` partially works for me and allows the article to load but it also seems to break embedded objects within the page with that filter as well.

I see a broken twitter embed, a missing youtube video and a missing [nytimes.com embedded frame](https://www.nytimes.com/interactive/2019/admin/100000005344693.embedded.html?) in the article page with that filter. Are you getting those page embedding breaking issues as well?

**Comment by okiehsch** [comment] 2019-05-30 23:52
Interestingly nothing is broken on my end with that filter, I see the youtube video, is it always broken on your end with that filter in place or only if the private browsing detection kicks in?

**Comment by yourduskquibbles** [comment] 2019-05-31 01:30
> 
> 
> Interestingly nothing is broken on my end with that filter, I see the youtube video, is it always broken on your end - with that filter in place - or only if the private browsing detection kicks in?

Yes broken for me on regular or private browsing with `nytimes.com##+js(abort-on-property-read.js, window.indexedDB)` as my only filter besides stock filters.

Below is a screenshot from a non-private browsing session with logger & example link side by side. The `nytimes.com##+js(abort-on-property-read.js, window.indexedDB)` filter looks like it is being applied against the `nytimes.com` embeded frame first on my side which then maybe cripples the twitter and youtube embed as well? 

![nonprivate](https://user-images.githubusercontent.com/22258847/58675379-0c4cd780-8322-11e9-9a0f-11c3859ad4da.png)


The page looks the same with broken embeds in private browsing mode as well but doesn't break the embeds when I remove `nytimes.com##+js(abort-on-property-read.js, window.indexedDB)`

**Comment by spirillen** [comment] 2019-06-02 23:57
Mostly a note....

I was trying to reproduce this issue, but couldn't, however I coulnd't help myself from noting that out of 77 queries the 37 (~50%) of them is tracking / spam ....  Shouldn't `nytimes.com` be a "newspaper" protecting democracy? or is it just me as a European who have misunderstood the concept of "_American_" democracy!!

**Comment by Jap2-0** [comment] 2019-06-04 22:10
I can reproduce on both Firefox and chrome on Windows 7.  I'm attempting to work on a filter to get around it, but it's going rather slowly.

*note: I'm using more than stock filters

**Comment by nsuchy** [comment] 2019-06-07 20:34
Happens for me in Brave Browser (Chromium fork)

<img width="1280" alt="Screen Shot 2019-06-07 at 4 33 52 PM" src="https://user-images.githubusercontent.com/8227641/59132035-11251300-8942-11e9-935b-dc485c8431e7.png">

**Comment by in4u** [comment] 2019-06-23 12:05
Same issue using Firefox 67.0.4 on 64-bit Windows 10 as well as Windows 7. Tested both filters shared by @josephcsible.

Tried `nytimes.com##+js(set-constant.js, window.indexedDB, undefined)` first and it worked just one time and never again.

Tried `nytimes.com##+js(abort-on-property-read.js, window.indexedDB)` and it's been working so far.

However, the embedded video and twitter feed also gets hidden as a side effect. With the filter enabled, this happens in both normal as well as private browsing mode. Without filter, the embedded items don't get hidden in normal mode.

**Comment by gorhill** [comment] 2019-07-07 21:43
Disabling JavaScript works fine if you just want to read an article.

**Comment by numbermaniac** [comment] 2019-07-10 02:07
I can reproduce this both with uBO turned off, and while it is on.

![SpaceX](https://user-images.githubusercontent.com/5206120/60934861-32936900-a30b-11e9-9763-d9ba41afe14c.png)

Firefox 67.0.4, uBO 1.20.0

**Comment by okiehsch** [comment] 2019-07-10 02:15
Does
`nytimes.com##^script:has-text(NYTD.Abra)`
work for you?

**Comment by numbermaniac** [comment] 2019-07-10 02:22
@okiehsch Yes, that fixed it for me.

**Comment by okiehsch** [comment] 2019-07-10 02:32
@numbermaniac  just a heads up if you add
`nytimes.com##^script:has-text(NYTD.Abra)`
to your filter list it will also cause some site breakage, for example it breaks the youtube video at 
`https://www.nytimes.com/2019/05/23/science/spacex-launch.html`
and embedded tweets will not show up.
The filter is only meant to be used if you just want to read an article in incognito mode.

**Comment by llacb47** [comment] 2019-07-20 22:05
May be of interest:

**Comment by numbermaniac** [comment] 2019-07-22 04:52
Bypassing anti-incognito would be anti-anti-incognito. Does that mean fixing this Chrome bug would be anti-anti-anti-incognito?

**Comment by llacb47** [comment] 2019-07-30 17:22
Here's the code the NYT uses to detect private browsing -- from `webpack:///./src/shared/utils/privateBrowsingDetect.js`. I can reproduce in Chrome and Firefox.

```
/* eslint-disable consistent-return */

let on;
let off;

const isSafari = () => {
  if (Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0) {
    return true;
  }

  if (
    // eslint-disable-next-line no-undef
    (!window.safari || safari.pushNotification).toString() === '[object SafariRemoteNotification]'
  ) {
    return true;
  }

  try {
    return window.localStorage && /Safari/.test(window.navigator.userAgent);
  } catch (e) {
    return false;
  }
};

const isMozilla = () => 'MozAppearance' in document.documentElement.style;

const Webkit = () => {
  if (window.webkitRequestFileSystem) {
    window.webkitRequestFileSystem(window.TEMPORARY, 1, off, on);
    return true;
  }
};

const Mozilla = () => {
  if (isMozilla()) {
    const db = indexedDB.open('test');
    db.onerror = on;
    db.onsuccess = off;
    return true;
  }
};

const Safari = () => {
  if (isSafari()) {
    // iOS 11
    // Origin: https://gist.github.com/cou929/7973956#gistcomment-2272103
    try {
      window.openDatabase(null, null, null, null);
    } catch (e) {
      on();
      return true;
    }

    // Older Safari
    try {
      if (localStorage.length) off();
      else {
        localStorage.x = 1;
        localStorage.removeItem('x');
        off();
      }
    } catch (e) {
      // Original gist: https://gist.github.com/jherax/a81c8c132d09cc354a0e2cb911841ff1

      // Safari only enables cookie in private mode
      // if cookie is disabled then all client side storage is disabled
      // if all client side storage is disabled, then there is no point
      // in using private mode
      navigator.cookieEnabled ? on() : off(); // eslint-disable-line no-unused-expressions
    }

    return true;
  }
};

const IE10Edge = () => {
  if (!window.indexedDB && (window.PointerEvent || window.MSPointerEvent)) {
    on();
    return true;
  }
};

export const checkPrivate = (onCb, offCb) => {
  on = onCb || (() => {});
  off = offCb || (() => {});
  Webkit() || Mozilla() || Safari() || IE10Edge() || off(); // eslint-disable-line no-unused-expressions
};

export const checkPrivateWhitelist = (onCb, offCb) => {
  const whitelistOn = onCb || (() => {});
  const whitelistOff = offCb || (() => {});

  const privateButAllowed = [
    'FBAV',
    'FBAN',
    'FBIOS',
    'FBBV',
    'FBDV',
    'FBMD',
    'FBSN',
    'FBSV',
    'FBSS',
    'FBCR',
    'FBID',
    'FBLC',
    'FBOP',
    'Twitter for iPhone',
    'TwitterAndroid',
    'nytios',
    'nytiphone',
    'nytipad',
    'nyt-android',
    'AppleNews',
    'Flipboard',
  ];

  const re = new RegExp(privateButAllowed.join('|'), 'i');
  if (re.test(navigator.userAgent)) {
    whitelistOn();
    return true;
  }

  whitelistOff();
  return false;
};
```

**Comment by llacb47** [comment] 2019-07-30 17:29
I can reproduce Washington Post private mode detection `https://www.washingtonpost.com/business/2019/07/30/trump-backpedals-china-threats-trade-deal-shows-signs-slipping-away/` in Chrome, but not Firefox.
WaPo's private mode detection code is obfuscated...
```
"condition_isPM": function() {
    return new Promise(function(_0x5c8e98) {
        var _0x3054d7 = !![];
        if (navigator[_0x2ec0("0x1a")]["indexOf"](_0x2ec0("0x1b")) >
            -1) return (new Promise(function(_0x5c8e98) {
            var _0x36aeee = window["RequestFileSystem"] || window[_0x2ec0("0x1c")];
            if (_0x36aeee) _0x36aeee(window[_0x2ec0("0x1d")], 100, function() {
                _0x3202b0["pv"] = ![];
                _0x5c8e98({
                    "type": "pv",
                    "result": _0x3202b0["pv"],
                    "overlay": _0x3054d7
                })
            }, function() {
                _0x3202b0["pv"] = !![];
                _0x5c8e98({
                    "type": "pv",
                    "result": _0x3202b0["pv"],
                    "overlay": _0x3054d7
                })
            })
        }))["then"](function(_0x48925e) {
            _0x5c8e98(_0x48925e)
        });
        else if (navigator[_0x2ec0("0x1a")][_0x2ec0("0x1e")]("Safari") > -1) try {
                var _0x50cda8 =
                    _0x2ec0("0x1f");
                window[_0x2ec0("0x20")][_0x2ec0("0x21")](_0x50cda8, _0x2ec0("0x22"));
                window[_0x2ec0("0x20")][_0x2ec0("0x23")](_0x50cda8);
                window[_0x2ec0("0x24")][_0x2ec0("0x21")](_0x50cda8, _0x2ec0("0x22"));
                window["localStorage"][_0x2ec0("0x23")](_0x50cda8);
                window[_0x2ec0("0x25")](null, null, null, null);
                _0x3202b0["pv"] = ![]
            } catch (_0x151b90) {
                _0x3202b0["pv"] = !![]
            } else if (navigator[_0x2ec0("0x1a")][_0x2ec0("0x1e")](_0x2ec0("0x26")) > -1) _0x3202b0["pv"] = !navigator[_0x2ec0("0x27")];
            else if (window[_0x2ec0("0x28")] ||
            window[_0x2ec0("0x29")]) _0x3202b0["pv"] = !window[_0x2ec0("0x2a")];
        else _0x3202b0["pv"] = ![];
        _0x5c8e98({
            "type": "pv",
            "result": _0x3202b0["pv"],
            "overlay": _0x3054d7
        })
    })
}
```

**Comment by llacb47** [comment] 2019-07-30 18:07
Since the WaPo anti-adblock and private mode detection are both in the same inline script, this filter takes care of both. `washingtonpost.com##+js(abort-current-inline-script, Promise.all, adblocked)` from https://github.com/uBlockOrigin/uAssets/commit/f0ade04a56a09472c2715e4525f19598c3490a9f

**Comment by llacb47** [comment] 2019-07-30 19:16
These filters work but they mess up fonts:
```
nytimes.com##+js(abort-current-inline-script.js, NYTD.Abra, indexedDB)
nytimes.com##+js(set-constant.js,NYTD.Abra,noopFunc)
```

**Comment by okiehsch** [comment] 2019-07-30 22:38
https://chromereleases.googleblog.com/2019/07/stable-channel-update-for-desktop_30.html

Fixes the issue for Chrome users.

`nytimes.com##+js(set-constant.js, webkitRequestFileSystem, noopFunc)`
works on my end using Firefox.

**Comment by llacb47** [comment] 2019-07-30 22:52
Will filters to fix this still be added? Not everyone who uses uBO has an up-to-date Chrome.

**Comment by llacb47** [comment] 2019-07-31 03:03
So this issue will not be fixed in older Chrome versions?

**Comment by numbermaniac** [comment] 2019-07-31 04:03
Is there a reason you're not updating Chrome?

**Comment by okiehsch** [comment] 2019-07-31 04:06
With Chrome 76+ the issue fixes itself.

**Comment by llacb47** [comment] 2019-07-31 19:32
I have an old version of Chromium to avoid a redesign, but at some point I will probably upgrade due to security concerns. However, not everyone uses the latest version of Chrome, and if a filter can be added for that, that would be appreciated.

**Comment by llacb47** [comment] 2019-07-31 23:35
The filter `nytimes.com##+js(set-constant.js, webkitRequestFileSystem, noopFunc)` works in Firefox and Chrome. This filter doesn't break anything in either browser, as `webkitRequestFileSystem` is only used for private mode and third party cookie detection by `nytimes.com`. Please remove the pre-processing directive `!#if env_firefox ... !#endif`.

**Comment by josephcsible** [comment] 2019-08-10 04:48
On Chrome 76.0.3809.100 and uBO 1.21.6, I still get caught by this, even with the change made in commit 18955b6.

**Comment by okiehsch** [comment] 2019-08-10 05:02
Yes, they changed it again to circumvent the https://chromereleases.googleblog.com/2019/07/stable-channel-update-for-desktop_30.html and our filter will also not work anymore.

**Comment by okiehsch** [comment] 2019-08-10 05:11
`nytimes.com##+js(set-constant.js, NYTD.Abra, trueFunc)`
works if you just want to read the articles.
It will break the homepage.

**Comment by krystian3w** [comment] 2019-08-10 10:48
Install chrome 76 and test again?

- https://nakedsecurity.sophos.com/2019/07/22/chrome-76-blocks-websites-from-detecting-incognito-mode/
- https://www.ghacks.net/2019/06/14/chrome-76-blocks-sites-from-detecting-incognito-mode/
- https://www.bleepingcomputer.com/news/software/chrome-76-released-with-blocked-flash-incognito-detection-fix/

**Comment by okiehsch** [comment] 2019-08-10 11:11
> Install chrome 76 and test again?

![Unbenannt](https://user-images.githubusercontent.com/16838044/62821145-5cd98000-bb70-11e9-8fdb-39053b85b436.JPG)

**Comment by llacb47** [comment] 2019-08-10 17:07
`https://mishravikas.com/articles/2019-07/bypassing-anti-incognito-detection-google-chrome.html`

**Comment by josephcsible** [comment] 2019-08-10 23:08
Yep, that's what they're doing. Here's the new malicious code snippet:
```javascript
/* eslint-disable consistent-return */

let on;
let off;

/**
 * Quota for an incognito Chrome window is a fraction (10%) of the device memory with an upper limit of 120MB.
 * More info: https://mishravikas.com/articles/2019-07/bypassing-anti-incognito-detection-google-chrome.html
 */
export const INCOG_MAX_QUOTA = 120;
export const MB_IN_BYTES = 2 ** 20;

const isSafari = () => {
  if (Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0) {
    return true;
  }

  if (
    // eslint-disable-next-line no-undef
    (!window.safari || safari.pushNotification).toString() === '[object SafariRemoteNotification]'
  ) {
    return true;
  }

  try {
    return window.localStorage && /Safari/.test(window.navigator.userAgent);
  } catch (e) {
    return false;
  }
};

const isMozilla = () => 'MozAppearance' in document.documentElement.style;

const Webkit = () => {
  if (window.webkitRequestFileSystem) {
    window.webkitRequestFileSystem(window.TEMPORARY, 1, off, on);
    return true;
  }
};

const Mozilla = () => {
  if (isMozilla()) {
    const db = indexedDB.open('test');
    db.onerror = on;
    db.onsuccess = off;
    return true;
  }
};

const Safari = () => {
  if (isSafari()) {
    // iOS 11
    // Origin: https://gist.github.com/cou929/7973956#gistcomment-2272103
    try {
      window.openDatabase(null, null, null, null);
    } catch (e) {
      on();
      return true;
    }

    // Older Safari
    try {
      if (localStorage.length) off();
      else {
        localStorage.x = 1;
        localStorage.removeItem('x');
        off();
      }
    } catch (e) {
      // Original gist: https://gist.github.com/jherax/a81c8c132d09cc354a0e2cb911841ff1

      // Safari only enables cookie in private mode
      // if cookie is disabled then all client side storage is disabled
      // if all client side storage is disabled, then there is no point
      // in using private mode
      navigator.cookieEnabled ? on() : off(); // eslint-disable-line no-unused-expressions
    }

    return true;
  }
};

const IE10Edge = () => {
  if (!window.indexedDB && (window.PointerEvent || window.MSPointerEvent)) {
    on();
    return true;
  }
};

export const Chrome = () => {
  return Promise.resolve()
    .then(() => {
      if (navigator.storage && navigator.storage.estimate) {
        return navigator.storage.estimate();
      }
      return undefined;
    })
    .then(estimate => {
      if (estimate && estimate.quota) {
        const { quota } = estimate;
        const limit = INCOG_MAX_QUOTA * MB_IN_BYTES;
        if (quota <= limit) {
          return true;
        }
      }
      return false;
    })
    .catch(() => false);
};

export const checkPrivate = (onCb, offCb) => {
  on = onCb || (() => {});
  off = offCb || (() => {});

  Chrome().then(isPrivate => {
    if (isPrivate) {
      return on();
    }
    return Webkit() || Mozilla() || Safari() || IE10Edge() || off();
  });
};

export const checkPrivateWhitelist = (onCb, offCb) => {
  const whitelistOn = onCb || (() => {});
  const whitelistOff = offCb || (() => {});

  const privateButAllowed = [
    'FBAV',
    'FBAN',
    'FBIOS',
    'FBBV',
    'FBDV',
    'FBMD',
    'FBSN',
    'FBSV',
    'FBSS',
    'FBCR',
    'FBID',
    'FBLC',
    'FBOP',
    'Twitter for iPhone',
    'TwitterAndroid',
    'nytios',
    'nytiphone',
    'nytipad',
    'nyt-android',
    'AppleNews',
    'Flipboard',
  ];

  const re = new RegExp(privateButAllowed.join('|'), 'i');
  if (re.test(navigator.userAgent)) {
    whitelistOn();
    return true;
  }

  whitelistOff();
  return false;
};
```

**Comment by josephcsible** [comment] 2019-08-10 23:13
Adding this rule fixes it for me: `nytimes.com##+js(set-constant.js, navigator.storage.estimate, undefined)`

**Comment by okiehsch** [comment] 2019-08-10 23:48
Thanks, that works on my end.

**Closed** 2019-08-10 23:49 UTC

**Comment by krystian3w** [comment] 2019-09-17 16:11
https://github.com/AdguardTeam/AdguardFilters/issues/39685

**Comment by Yuki2718** [comment] 2020-03-06 08:08
It seems only one of the two rules is enough to avoid detection on each platform like like https://github.com/uBlockOrigin/uAssets/issues/7058
i.e. 
`##+js(set-constant.js, navigator.storage.estimate, undefined)`
for Chromium and
`nytimes.com##+js(set-constant.js, webkitRequestFileSystem, noopFunc)`
for Firefox.

**Comment by Yuki2718** [comment] 2020-03-06 08:10
Not sure if it should be addressed in uBlock Annoyances but if you access the site on Android (with the Annoyances filter enabled) you'll see leftover of modal popup only for several seconds.

![nytimes](https://user-images.githubusercontent.com/58900598/76064548-3926cd00-5fcd-11ea-8d70-6de8953d4bd0.png)

SS was taken on PC for convenience.

**Comment by krystian3w** [comment] 2020-03-06 13:09
Locked scroll?

PS. `trojmiasto.pl` also detect private mode in browser

**Comment by Yuki2718** [comment] 2020-03-07 01:27
> 
> 
> Locked scroll?
> 
> PS. `trojmiasto.pl` also detect private mode in browser

Yeah, scroll is locked but I'm not sure whether a style rule is necessary as the scroll recovers just 2-3 seconds after page load.
Why don't you create a new issue for that?

**Comment by krystian3w** [comment] 2020-03-07 12:18
Because you haven't separated into a new one with a locked-up pop-up rewind (scroll).

And this thread could be changed to "private mode detection pages".

**Comment by Yuki2718** [comment] 2020-03-08 00:38
Ah, I'm still not sure if that leftover should be addressed in uBlock Annoyances as it doesn't require uBO syntax. Given @okiehsch didn't add this I guess it's not.

Personally I agree, but since we don't have such thread as "pages with right-click disabled", maybe we're still required to report them one by one with each URL.

**Comment by okiehsch** [comment] 2020-03-08 00:44
> Given @okiehsch didn't add this I guess it's not.

I can't reproduce.

**Comment by Yuki2718** [comment] 2020-03-08 00:51
> 
> 
> > Given @okiehsch didn't add this I guess it's not.
> 
> I can't reproduce.

Okay, will make a new issue. I'm currently a bit busy so may be late.

**Comment by llacb47** [comment] 2020-03-08 01:05
Is this the modal? Reproduced with Firefox emulating Android. Just like you said (`only for several seconds`) the modal goes away after a few seconds.

![image](https://user-images.githubusercontent.com/16567977/76154710-e7ef0a00-60ae-11ea-882f-e0236f727e61.png)

**Comment by llacb47** [comment] 2020-03-08 01:11
This filter gets rid of that: `nytimes.com##.ReactModalPortal:has(.welcomeAd)`

I assume this fits the criteria for annoyances.

Here's the full DOM structure of the popup, it's hard to look at since it is removed from the DOM after a few seconds: `https://pastebin.com/hFG45Jqt`

**Comment by Yuki2718** [comment] 2020-03-08 02:22
@llacb47 ty for confirmation and more, yeah, that one! I found I see that one on default settings rather than the leftover I posted on medium mode settings.
![nytimes(1)](https://user-images.githubusercontent.com/58900598/76155412-009f0480-612f-11ea-9853-be890f12597c.png)
