### ISSUE TITLE
1fichier.com

### ISSUE THREAD

**Issue by Francois-dag** [uBlockOrigin/uAssets#2612] opened 2018-06-19 18:43 UTC
https://1fichier.com/?bff4jq2q0lfs6qz5alhu

**La publicité est indispensable à la fourniture de l'offre gratuite d'essai.
Pour continuer, vous devez désactiver tout blocage publicitaire**

### Versions

- Browser/version: [ firefox ESR 60.0.2]
- uBlock Origin version: [1.16.10]

**Comment by okiehsch** [comment] 2018-06-19 19:33
Nope, still can't reproduce, after I follow your points, I get
![image](https://user-images.githubusercontent.com/16838044/41619865-1082562e-7408-11e8-80ff-df55dcd90f60.png)


If I click download
![unbenannt1](https://user-images.githubusercontent.com/16838044/41619912-4ff839fe-7408-11e8-9a55-c46eccdb4182.JPG)
If I then click "Click here too download the file" the download starts on my end.

**Comment by Francois-dag** [comment] 2018-06-19 19:40
Yes you are right, >due to activation of protectio  against tracking within firefox ...

**Comment by okiehsch** [comment] 2018-06-19 19:42
So, if you deactivate the tracking protection the issue is fixed on your end?

**Comment by Francois-dag** [comment] 2018-06-19 19:46
Yes, many thanx for our help !

**Comment by okiehsch** [comment] 2018-06-19 19:50
No problem.

**Closed by okiehsch** 2018-06-19 19:50 UTC
Labels: unable to reproduce
