### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by xXMontesumaXx** [uBlockOrigin/uAssets#18177] opened 2023-05-22 06:12 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/`

### Category

ads

### Description

No rompe completamente los anuncios, se para la música y el anuncio aun que se congela, molesta

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 97853
 cosmetic: 44524
 scriptlet: 17730
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 65652-47, 5d.23h.5m
  easyprivacy: 32265-46, 5d.23h.6m
  plowe-0: 3735-937, 1d.6h.53m
  spa-0: 3680-11, 49m
  spa-1: 5229-211, 1d.22h.5m
  ublock-abuse: 70-0, 4d.5h.39m
  ublock-badware: 7099-127, 3d.1h.57m
  ublock-filters: 33018-123, 3d.1h.56m
  ublock-privacy: 392-73, 4d.5h.38m
  ublock-quick-fixes: 360-26, 8h.23m
  ublock-unbreak: 2016-43, 3d.1h.55m
  urlhaus-1: 8396-1, 48m
filterset (user): [array of 1 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 565 ms (selfie)
 maxAssetCacheWait: 89 ms
popupPanel: 
 blocked: 5
 network: 
  audio-ak-spotify-com.akamaized.net: 1
  doubleclick.net: 3
  googletagmanager.com: 1
```
</details>

**Comment by dportvine** [comment] 2023-05-22 06:31
Forced an update of filter lists.

**Comment by okiehsch** [comment] 2023-05-22 06:54
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18148

**Closed by okiehsch** 2023-05-22 06:54 UTC
