### ISSUE TITLE
linkvertise.com [NSFW]

### ISSUE THREAD

**Issue by Samwisegee90** [uBlockOrigin/uAssets#6989] opened 2020-02-22 23:14 UTC
### URL(s) where the issue occurs

All links to site, example (NSFW):
`https://linkvertise.com/72834/D0r4soft`
`https://linkvertise.com/72834/M00nfrmatn`
### Describe the issue

Site tries to get you to click various buttons before allowing you to continue i.e. Add Add-on, Activate Notifications, etc

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 73.0.1 (64-bit)
- uBlock Origin version: 1.24.4

### Settings

- default with Adblock warning removal list
### Notes

Don't judge me

**Comment by llacb47** [comment] 2020-02-22 23:41
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/6065

**Closed** 2020-02-23 08:41 UTC
