### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by mey223** [uBlockOrigin/uAssets#14616] opened 2022-09-01 03:00 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

Pre stream and mid roll ads no longer blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82614
  cosmetic: 42661
  scriptlet: 17741
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 66784-51, 17m
    easyprivacy: 27449-126, 17m
    plowe-0: 3634-777, 17m
    ublock-abuse: 76-0, 17m
    ublock-badware: 4177-99, 17m
    ublock-filters: 32431-107, 17m
    ublock-privacy: 241-3, 17m
    ublock-quick-fixes: 404-4, 17m
    ublock-unbreak: 1846-41, 17m
    urlhaus-1: 7339-0, 17m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 13 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 524 ms (selfie)
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    amazon-adsystem.com: 2
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 4
    scorecardresearch.com: 4
    serving-sys.com: 1
```
</details>

**Comment by MasterKia** [comment] 2022-09-01 03:06
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Comment here: https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-09-01 03:07
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed** 2022-09-01 03:06 UTC
