### ISSUE TITLE
UBlock Filters Block entire content on Pixiv User's Page

### ISSUE THREAD

**Issue by thakyZ** [uBlockOrigin/uAssets#8321] opened 2020-12-04 15:50 UTC
### URL(s) where the issue occurs
https://www.pixiv.net/en/users/1521349 **(NSFW)**
And any other users as well

### Describe the issue

The filter that blocks dom content via:
```
pixiv.net##div[class^="sc-"]:has(:scope > div[style] > iframe[width="728"][height="90"])
```
ends up blocking all of the content on a user's page.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/950594/101184297-6ad4cf00-3605-11eb-824b-2f5eab2b101f.png)

As you can see no scrollbar on the right.

### Versions

- Browser/version: Firefox 83.0 (64-bit)
- uBlock Origin version: 1.31.0

### Settings

- Enable cloud support
- I am an advanced user
- Disable prefetching
- Disable Hyperlink Auditing

**Comment by uBlock-user** [comment] 2020-12-04 15:54
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/8311

force update uBlock Filters.

**Closed by uBlock-user** 2020-12-04 15:54 UTC
