### ISSUE TITLE
kamigame.jp: ads

### ISSUE THREAD

**Issue by Spare-279** [uBlockOrigin/uAssets#11071] opened 2021-12-26 06:45 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://kamigame.jp/dbd/page/106876368628744199.html`

### Category

ads

### Describe the issue

![スクリーンショット 2021-12-26 153557](https://user-images.githubusercontent.com/96656938/147401074-654fd01a-af4b-4d15-9599-f294aa617c67.jpg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![スクリーンショット 2021-12-26 153557](https://user-images.githubusercontent.com/96656938/147401065-89eab0ad-badc-4dd5-b856-28c528b23ba8.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 176450
  cosmetic: 198847
  scriptlet: 33593
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 23h.37m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/280-patch.txt: 2756-2, 2d.20h.29m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances-plus.txt: 30-0, 2d.4h.12m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances.txt: 4918-4, 2d.20h.33m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 38510-2415, 2d.20h.31m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-paranoid.txt: 439-3, 2d.2h.37m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-social.txt: 2097-2, 2d.20h.35m
    adguard-annoyance: 48683-1362, 3d.3h.56m
    adguard-generic: 62293-2986, 3d.3h.56m
    adguard-mobile: 7021-157, 3d.1h.19m
    adguard-social: 15235-990, 3d.3h.56m
    adguard-spyware: 24699-2030, 3d.1h.15m
    adguard-spyware-url: 404-12, 3d.3h.56m
    block-lan: 44-14, 50m
    curben-phishing: 13036-0, 16h.2m
    curben-pup: 383-0, 16h.2m
    dpollock-0: 16947-374, 4d.21h.1m
    fanboy-annoyance: 59267-4058, 50m
    fanboy-cookiemonster: 20670-20670, 50m
    fanboy-social: 23179-23145, 3d.3h.56m
    fanboy-thirdparty_social: 68-21, 50m
    mvps-0: 8730-1847, 5d.2h.9m
    ublock-annoyances: 4341-354, 3d.3h.56m
  default: 
    JPN-1: 5591-3487, 3d.1h.17m
    easylist: 62255-5571, 7h.32m
    easyprivacy: 26543-12853, 3d.3h.56m
    plowe-0: 3709-1659, 5d.16h.21m
    ublock-abuse: 81-4, 3d.3h.56m
    ublock-badware: 3629-1801, 3d.3h.56m
    ublock-filters: 30127-7716, 1d.8h.15m
    ublock-privacy: 191-96, 1d.8h.11m
    ublock-unbreak: 1735-224, 1d.8h.13m
    urlhaus-1: 8168-4, 16h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1763
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by Spare-279** [comment] 2021-12-26 06:45
広告の消し残り有り

**Comment by hirorpt** [comment] 2021-12-26 07:51
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/104484

**Comment by hirorpt** [comment] 2021-12-26 08:16
@Spare-279
Please respect our prerequisites and  force update filter-lists before reporting any issues. According to your configuration, you have subscribed to Yuki's uBlock Japanese filters, which has already fixed this issue.

> I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")

**Closed** 2021-12-26 10:04 UTC

**Comment by gorhill** [comment] 2021-12-26 12:23
Duplicate of #11070.
