### ISSUE TITLE
dragontea.ink: detection

### ISSUE THREAD

**Issue by Conall53** [uBlockOrigin/uAssets#16083] opened 2022-12-21 09:24 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/`

### Category

detection

### Describe the issue

This site detects ad-block on the loading screen which is shown for every page.

This page not only violates human decency and ad-sense policy with the amounts of ads-shown in loading, pop-ups, pop-over, between content and everywhere, but also lied about implementing a paid subscription which would not show ads. I tried creating an account and seeing if you maybe only see it then but there was nothing. Also it is a giant PITA to navigate on mobile, because of the disgusting loading screen with adds and full size pop-ups it is just a bit short of unusable.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/62668788/208870049-8c5aac26-5c08-4e92-b3fc-3fe52801b1cf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 87938
  cosmetic: 38705
  scriptlet: 16608
  html: 848
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 32313-40, 20h.48m
    ublock-badware: 4211-0, 20h.47m
    ublock-privacy: 301-0, 2d.20h.54m
    ublock-abuse: 77-0, 2d.20h.53m
    ublock-unbreak: 1931-1, 20h.46m
    easylist: 63024-627, 4d.21h.2m
    easyprivacy: 30983-1739, 4d.21h.1m
    plowe-0: 3671-3, 1d.20h.50m
    urlhaus-1: 10154-0, 12h.45m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 19 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1111 ms (selfie)
  maxAssetCacheWait: 404 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adlightning.com: 1
    ampproject.org: 4
    doubleclick.net: 2
    google-analytics.com: 1
    googlesyndication.com: 5
    googletagmanager.com: 1
    stpd.cloud: 2
```
</details>

**Comment by JobcenterTycoon** [comment] 2022-12-21 09:37
Not fully fixable at the moment.

**Comment by JobcenterTycoon** [comment] 2022-12-21 21:25
@Conall53 add to your filter

```
@@||dragontea.ink^$ghide
dragontea.ink##+js(nosiif, _0x)
dragontea.ink##+js(ra, style, body > div, stay)
dragontea.ink##html, body:style(overflow: visible !important;)
dragontea.ink##iframe[id^="google_ads_iframe"]
```

**Comment by Zhongli0401** [comment] 2023-04-06 06:02
> 

for me it fixed it thanks

**Comment by mapx-** [comment] 2023-04-18 15:15
```
@@||dragontea.ink^$ghide
@@*$image,domain=dragontea.ink
dragontea.ink#@#+js(aeld, DOMContentLoaded, Adblock)
!||dragontea.ink^$csp=script-src
||dragontea.ink^$csp=style-src *
```

**Comment by peace2000** [comment] 2023-04-22 15:12
> ```
> @@||dragontea.ink^$ghide
> @@*$image,domain=dragontea.ink
> dragontea.ink#@#+js(aeld, DOMContentLoaded, Adblock)
> ||dragontea.ink^$csp=style-src *
> ```

@mapx- 

Those filters work for 25 seconds, then the site goes broken (graphical issues).

https://user-images.githubusercontent.com/17256841/233792603-5202cb33-babe-430a-a563-5178c5bc7abe.png

**Comment by mapx-** [comment] 2023-04-22 15:18
I know but the page wont disappear and the "story" can still be read / seen

**Comment by peace2000** [comment] 2023-05-21 09:51
> @Conall53 add this to your filter (it will fix all ads and the anti adblock)
> 
> ```
> @@||dragontea.ink^$ghide
> dragontea.ink##+js(nosiif, _0x)
> dragontea.ink##+js(ra, style, body > div, stay)
> dragontea.ink##html, body:style(overflow: visible !important;)
> dragontea.ink##iframe[id^="google_ads_iframe"]
> ```

Is there a reason why this filterset can't be accepted as a solution?

I noticed that "Show more" button on Summary section doesn't work but are there other issues?

**Comment by peace2000** [comment] 2023-05-21 10:09
Replacing this:

`dragontea.ink##+js(ra, style, body > div, stay)`

With:

`dragontea.ink##body > div[style]:not([id]):style(position: static !important; background-color: rgba(0, 0, 0, 0) !important)`

Lessens the time how long the loading screen appears.

**Comment by JobcenterTycoon** [comment] 2023-05-21 12:28
When you add the filter they will be not last long. I know no other filter thats why i only posted them here for the users.

**Comment by big-cat-loaf** [comment] 2023-06-15 18:24
To you all, please do not use the fliters AdGuard – Ads when you go on this Site because the answer for the issue: https://github.com/AdguardTeam/AdguardFilters/issues/135575 was stpd.cloud and securepubads.g.doubleclick.net to completely to exclud which is of privacy reasons not recommanded.

**Comment by logan-kling** [comment] 2023-07-25 05:22
Can anyone explain why the rules provided by @JobcenterTycoon work? Especially when the one's [here](https://github.com/uBlockOrigin/uAssets/commit/1cea2a33778cf5620e5fc3ba90b18127f8042c2c) don't. I want to understand these rules well enough to modify them to work for the built in adblocker on Brave now that they just seem to cause the site to stay on its loading screen forever. These rules did work for me on Brave about a month ago. Though you can see the navigation of the site at this loading screen. So, I think this loading screen might be different from the initial verifying loading screen that I'm assuming @peace2000 was talking about about.

What are `nosiif` and `nostif`?
The second and third rules look like they're modifying js files, but I'm then confused by the third rule having CSS selectors.
The fourth rule looks like it would block way too much by blocking the entire webpage.
And the fifth rule looks like it cancels out the first rule from my layman's perspective.

**Comment by big-cat-loaf** [comment] 2023-07-25 08:56
The website change something, now the pictures don't appear not any longer.

**Comment by JobcenterTycoon** [comment] 2023-07-25 09:13
The rules from https://github.com/uBlockOrigin/uAssets/issues/16083#issuecomment-1362103717 working fine for me.

**Comment by big-cat-loaf** [comment] 2023-07-25 09:19
with uBlock Origin: 
![Screenshot 2023-07-25 105307](https://github.com/uBlockOrigin/uAssets/assets/100969549/33a57f4a-a147-44e7-b2e2-c0d487de2e87)
without  uBlock Origin:
![Screenshot 2023-07-25 105325](https://github.com/uBlockOrigin/uAssets/assets/100969549/51794b4d-86d8-46ca-99eb-ef777023b3b6)

**Comment by JobcenterTycoon** [comment] 2023-07-25 09:36
Ok can reproduce. I added a fix to uBO now https://github.com/uBlockOrigin/uAssets/commit/bcd0121e30d09b30cdf6cb330290e1e105aea182 but dragontea.ink is a known circumventor so maybe the filter will not last long.

**Comment by big-cat-loaf** [comment] 2023-07-25 09:44
works

**Comment by big-cat-loaf** [comment] 2023-07-25 09:53
sorry just found a new issue with the code, to trigger this event you must scroll a minute or two 

![Screenshot 2023-07-25 115137](https://github.com/uBlockOrigin/uAssets/assets/100969549/70adf481-fc6d-4232-b198-c9bc14200d70)

**Comment by JobcenterTycoon** [comment] 2023-07-25 10:31
Works fine for me. Be sure no other adblocker/trackingblocker is enabled.

**Comment by big-cat-loaf** [comment] 2023-07-25 12:47
Hier is Viedo as prove of my bug. Sorry I must use a 3rd party Video host because of 10 Mb limit. 
https://streamable.com/1xbs4v ( Video is only 2 days online)

**Comment by JobcenterTycoon** [comment] 2023-07-25 14:31
@MasterKia can you reproduce? For me it still works perfectly.

**Comment by big-cat-loaf** [comment] 2023-07-26 12:13
I think I know why the sceen is only showes up on my side. I tested it out without a adblocker and two 4 different browsers and it turns out the website owner hate me specifically. The propretly block my defice :(

**Comment by SatoshiHP** [comment] 2023-07-27 16:40
> sorry just found a new issue with the code, to trigger this event you must scroll a minute or two
> 
> ![Screenshot 2023-07-25 115137](https://user-images.githubusercontent.com/100969549/255862133-70adf481-fc6d-4232-b198-c9bc14200d70.png)

Website loads fine but after about 15 seconds browsing I get the same screen

**Comment by CambaCambaCambaCambaCambaCamba** [comment] 2023-07-27 17:53
if i remove everything dragontea in "my filters" theres no blue anti-adblocker showing but as soon as i add a cosmetic filter like removing the footer, the blue anti-adblocker shows

**Comment by JobcenterTycoon** [comment] 2023-07-27 18:24
Please test

```
@@||dragontea.ink^$ghide
dragontea.ink##+js(nosiif, _0x)
dragontea.ink##+js(ra, style, body > div, stay)
dragontea.ink##html, body:style(overflow: visible !important;)
dragontea.ink##iframe[id^="google_ads_iframe"]
dragontea.ink##+js(rpnt, script, "}});,  "}}); window.setTimeout(function(){let t=document.querySelectorAll(".reading-content .page-break.no-gaps img");for(let e=0;e<t.length;e++){let a=t[e].getAttribute("id").toString();entschluesselteid=CryptoJSAesJson.decrypt(a\,"releasethestormy888")\,t[e].setAttribute("id"\,a)\,a=t[e].getAttribute("data-src").toString()\,t[e].setAttribute("data-src"\,CryptoJSAesJson.decrypt(a\,"releasethestormy888"))\,t[e].classList.add("wp-manga-chapter-img")\,t[e].classList.add("img-responsive")\,t[e].classList.add("lazyload")\,t[e].classList.add("effect-fade")}}\,1e3);)
```

**Comment by SatoshiHP** [comment] 2023-07-27 19:45
> Please test

Works for me, thanks.

**Comment by big-cat-loaf** [comment] 2023-07-27 19:59
to the Quick fixes?

**Comment by JobcenterTycoon** [comment] 2023-07-27 20:03
Added. Force update the filterlist to get the fix directly (will be avaiable in 5-10 minutes).

**Comment by SatoshiHP** [comment] 2023-07-27 20:17
Sorry. On further inspection it seems that while the website does load, the images are now in the wrong order.

**Comment by big-cat-loaf** [comment] 2023-07-27 20:43
I can confirm @SatoshiHP Statment. Yes the images are in wrong order.

**Comment by JobcenterTycoon** [comment] 2023-07-27 22:14
Fixed now. The images are unsorted by default which i didn’t saw.

**Comment by CambaCambaCambaCambaCambaCamba** [comment] 2023-08-02 04:25
site is messed up again

**Comment by ItsADevAgain** [comment] 2023-08-02 14:52
Hello. I don't mind you guys privately sharing filters, I don't even patch those. But publicly deploying circumventions to encryption and such will be patched immediately, as @JobcenterTycoon knows from last year.

- You're aiding content scraping bots and DDOSers, by doing their coding work for them. They're the scourge of the internet.
- You're aiding shitty apps that use bots to leech off the hard work translation groups to steal the ad revenue.
- We have a membership service rolling out soon and your public circumventions might help people bypass the paywall in some ways, but most of that will be server side.
- I'd rather not resort to server-side ad authentication and decryption for regular site users and cause high server loads. But I will eventually if you keep publicly circumventing our site security.
- DT translators take all the ad revenue, and their server costs are high. You're only increasing the chance they stop translating altogether by aiding their competitors with public security circumvention. Isn't that shit against your ToS anyway? If not, it should be.

If you keep filters private I'll even code you a proper back door. Up to you guys, @JobcenterTycoon knows I'll patch anything publicly deployed daily.

**Comment by SatoshiHP** [comment] 2023-08-02 16:11
Yes, I can also confirm the website seems to be broken again. I hope it could be fixed on a more permanent basis, but it seems this will just start another war between the adblocker and the developer. We can not expect the volunteers of this amazing project to continuously create filters to bypass the ads on one fringe website. I want to thank the people who have worked countless hours to help circumvent these ads for their work, and if any testing needs to be done I would be glad to help.

On another note, and I hope this is not considered too much off-topic, I've contacted TappyToons, Tapas and Webnovel about DT's making money of publishing their licensed works through these ads and donations. Furthermore, I've notified ko-fi about DT's making use of their service to make money using somebody else's licensed work and have have also contacted DT's registrar, GoDaddy, about this abuse. I'm also in the proces of contacting MangaToon and Webcomics and plan to contact the original publishers like Acqq, BiliBiliI, qiyi and KuaiKan, and their ad agency if possible of course.

Again, I'd like to thank you for your hard work, and if this is too off-topic, feel free to remove it. I wouldn't want to stand in the way of your work.

**Comment by JobcenterTycoon** [comment] 2023-08-02 16:22
Thr site working fine for me with the lastest filter (for now).

> I hope it could be fixed on a more permanent basis

Could be but only with private filter.

**Comment by SatoshiHP** [comment] 2023-08-02 16:34
It indeed works with the latest filter, thanks. After about 15 to 20 seconds the page reloads quickly when reading a chapter, but it works fine after that. Too bad a more long term fix is not possible without private filters. Thanks again.

**Comment by ItsADevAgain** [comment] 2023-08-02 19:31
@SatoshiHP Every single translation group out there finances the translations with ads and donations. Are you going to report every group? Or are you just salty that DT have a developer who patches uBlock when you circumvent scraper security?

DT respects DMCA and publishers are well aware of the thousands of translation groups out there. I don't know why you care I patched your encryption circumvention? I explained why, and said I don't mind at all if you filter privately (and won't patch those) as long as the filters aren't published, and even offered you an ad-free backdoor in the code. All I care about is blocking the thousands of DDOS bots, aggregator site bots, and manger reader app bots that plague the site.

If you find translation groups so egregious for wanting a tiny amount of financial compensation for the hours they spend translating comics (they barely make anything for their time), then shouldn't you find all the aggregator sites and reader apps that just steal smaller groups' translations and monetise those even more egregious? If you were being morally genuine?

Hope you understand. Let me know if you want an ad free back door.

Cheers.

**Comment by thu2468** [comment] 2023-08-02 20:08
I believe it broken again

**Comment by ItsADevAgain** [comment] 2023-08-02 22:45
@JobcenterTycoon if you make them a simple filter that sets an URL param, global JS var, cookie or cache storage to ubloc = true, then post it here, I'll have it disable all scripting so anyone with the private filter can just use the standard ublock rules on Dragontea.

Then you can just give it out to anyone complaining about security on Reddit or Github. I'll leave it open as long as it isn't published in the app (and doesn't get spammed by bots).

**Comment by ItsADevAgain** [comment] 2023-08-03 10:42
@JobcenterTycoon Or we can just waste each other's time with several patches a day. I'd rather not bring back the honeypot iframes and ad images. You know they made you give up last year, and know you have no filters that I can't patch around. The only place another war is heading is me eventually decrypting the site images server-side via ad server callbacks, which you won't be able to filter at all.

Your patches don't provide a stable user experience on DT anyway, so if I'm offering uBlock users a private filter to browse DT ad free, what's the point of us wasting time? A war doesn't help your users. And it doesn't help DT users as it will slow the server.

I am paid to patch you. So why don't we just make peace and reach a compromise?

**Comment by ItsADevAgain** [comment] 2023-08-03 11:30
By the way, you had ads loading in your last filter set. A targeted ad refresh via GPT glitches your injected CSS. I could have just reflowed the entire page and loaded every advert. But I patched you the normal way because I'm nice. Shall we keep going back and forth or just make these people a filter to browse ad-free?

**Comment by peace2000** [comment] 2023-08-03 13:51
@ItsADevAgain The idea of this topic is how to block ads for `dragontea.ink`. Please don't post off-topic comments here.

**Comment by ItsADevAgain** [comment] 2023-08-03 14:03
@peace2000 I am on topic because you can't block adverts on a site with a professional developer actively patching all public filters, usually within an hour, to prevent scraper bots and DDOSers. You especially can't block ads if I move the decrypt auth server-side. 

"The idea of this topic is how to block ads for dragontea.ink" - I'm offering a custom filter that blocks all adverts as long as it's pasted as a custom filter. That's on topic, isn't it?

**Comment by JobcenterTycoon** [comment] 2023-08-07 19:48
I updated the private filter https://github.com/uBlockOrigin/uAssets/issues/16083#issuecomment-1362103717

**Comment by gwarser** [comment] 2024-02-21 09:39
This makes the Cloudflare check page blank:

    ##html:not(:has(link[href="https://dragontea.ink/xmlrpc.php"], link[href="/cdn-cgi/styles/challenges.css"])) > body:not(.page-template)

**Closed** 2024-03-30 16:39 UTC
