### ISSUE TITLE
watch.globaltv.com: breakage

### ISSUE THREAD

**Issue by Githubjohn2021** [uBlockOrigin/uAssets#12498] opened 2022-03-30 01:49 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://watch.globaltv.com/series/2893de5a-f2cc-11ea-9089-0242ac110003/episode/GLOB0056561600000300/?action=play`

### Category

breakage

### Describe the issue

error this video file cannot be played error code 241001

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 104129
  cosmetic: 131361
  scriptlet: 31230
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63165-671, 24m
    fanboy-annoyance: 66149-231, 24m
    ublock-annoyances: 4282-112, 24m
  default: 
    user-filters: 2-0, never
    easylist: 64994-845, 25m
    easyprivacy: 26734-234, 25m
    plowe-0: 3690-820, 25m
    ublock-abuse: 72-0, 25m
    ublock-badware: 3984-258, 25m
    ublock-filters: 30467-3082, 25m
    ublock-privacy: 205-10, 25m
    ublock-quick-fixes: 135-16, 25m
    ublock-unbreak: 1741-87, 25m
    urlhaus-1: 7657-0, 25m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2796 ms
  maxAssetCacheWait: 1141 ms
popupPanel: 
  blocked: 268
  blockedDetails: 
    globaltv.com: 1
    corus.ca: 1
    demdex.net: 6
    facebook.net: 1
    googletagmanager.com: 1
    hotjar.com: 1
    jwpcdn.com: 1
    jwpltx.com: 53
    omtrdc.net: 161
    permutive.app: 1
    scorecardresearch.com: 41
```
</details>

**Comment by mapx-** [comment] 2022-03-30 07:18
@Githubjohn2021 Do you get that error disabling uBO ?

**Comment by Githubjohn2021** [comment] 2022-03-30 10:44
Disabling uBO it works fine (with ads).
The show played for a out 20 minutes before showing the error with it enabled.  So not every ad is causing the error.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stephenhawk8054** [comment] 2022-03-30 11:41
Can you test if adding these works for you?

```
@@||edge.permutive.app^$script,domain=watch.globaltv.com
@@||api.permutive.com/v*/geoip$xhr,domain=watch.globaltv.com
```

**Comment by Githubjohn2021** [comment] 2022-03-30 12:43
Ill try it and report back. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Githubjohn2021** [comment] 2022-03-30 20:02
I spoke too soon.  Same error occured. Attached pic (sorry for all the glare)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stephenhawk8054** [comment] 2022-03-31 00:12
> I spoke too soon. Same error occured. Attached pic (sorry for all the glare)

Since I can't access your link above as it needs signing in, can you check if the free video link of the same series (the link with `Available for x days`) works for you with the above filters?

`https://watch.globaltv.com/series/2893de5a-f2cc-11ea-9089-0242ac110003`

**Comment by Githubjohn2021** [comment] 2022-03-31 01:10
Will do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Githubjohn2021** [comment] 2022-03-31 02:50
Still produced an error.  It seems some shows produce more errors than others.  We use the same login for several other channels ctv.ca cbc.ca etc, that all work fine.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stephenhawk8054** [comment] 2022-03-31 02:58
> Still produced an error. It seems some shows produce more errors than others. We use the same login for several other channels ctv.ca cbc.ca etc, that all work fine.

That's weird, I used VPN to Canada and can watch the video fine with those 2 filters above. Are you using any:

- Other extensions
- Browser's built-in content blocker (like on Edge, Firefox...)
- DNS blocking methods
- Other blocking softwares outside browser
- OS' hosts file for blocking

?

**Comment by Githubjohn2021** [comment] 2022-03-31 03:05
None of those. Only the windows virus protection one but nothing linked to the browser.  Im using chrome btw, I've tried firefox in the past and had the same error.
It might even just be on some shows.  I forget what we watched this morning, where I thought it was working.  But later we tried to watch "911"  It doesnt produce the error on what would be the first ad.  It usually happens more towards the end of the show, which is usually where the most ads are.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stephenhawk8054** [comment] 2022-03-31 03:13
Can you open [The logger pane](https://github.com/gorhill/uBlock/wiki/The-logger), go to `filter logger content` space, click on `Block` and `Allow`, open `https://watch.globaltv.com/series/2893de5a-f2cc-11ea-9089-0242ac110003` then open the video. Wait a bit for it to load, go back to The logger pane and screenshot it?

**Comment by Githubjohn2021** [comment] 2022-03-31 03:20
Yeah it'll have to be in the morning. Thanks for the help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mapx-** [comment] 2022-04-05 06:08
@stephenhawk8054 no feedback here, you should add those 2 filters and close it

**Closed** 2022-04-05 06:27 UTC
Labels: geo specific, No Feedback => closing

**Comment by Githubjohn2021** [comment] 2022-10-11 08:41
It worked! Thank you very much

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Githubjohn2021** [comment] 2022-10-11 09:15
[cid:919fc1b0-d5ae-415b-bfde-f2e4a2b90e66]
________________________________

**Comment by garry-ut99** [comment] 2023-02-02 22:43
Ad placeholders caused by `ghide` from "uBlock Filters":
Main page: `https://www.globaltv.com/` : [SCREENSHOOT 1](https://user-images.githubusercontent.com/72945564/216466283-b7bd4a6f-8a5b-494e-844d-d64a690332fa.png)
Example subpage `https://www.globaltv.com/shows/csi-vegas/` : [SCREENSHOOT 2](https://user-images.githubusercontent.com/72945564/216466290-9f9385d8-b52b-4757-b130-6411d071662f.png)

**Comment by garry-ut99** [comment] 2023-02-03 10:57
Not fixed at all.
