### ISSUE TITLE
www.dailymail.co.uk: nuisance

### ISSUE THREAD

**Issue by TotalImportance8529** [uBlockOrigin/uAssets#20344] opened 2023-10-28 18:44 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

Pop up

### URL(s) where the issue occurs.

`https://www.dailymail.co.uk/news/article-11480517/Schoolies-stunt-leaves-teenage-boy-unconscious-leaping-roof-table-SA.html`

### Screenshot(s)

![Screenshot_20231029-023547_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/146954135/5f00a13b-a4da-4d25-8aff-8c75db768687)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 199791
 cosmetic: 121758
 scriptlet: 25618
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22383-12, 1d.2h.36m
  https://get.letsblock.it/list/10ed17c7-db36-40f6-86d0-00cad74ab372.txt: 82-0, 3h.3m
  adguard-spyware-url: 1291-5, 2d.3h.50m
  block-lan: 54-0, 2d.3h.50m
  curben-phishing: 75507-20, 3h.2m
  easylist-annoyances: 4017-32, 2d.3h.50m
  easylist-chat: 143-0, 2d.3h.50m
  easylist-newsletters: 6584-15, 2d.3h.50m
  easylist-notifications: 2960-82, 4h.13m
  fanboy-cookiemonster: 48656-220, 2d.3h.50m
  fanboy-social: 16303-13, 2d.3h.50m
  ublock-annoyances: 5651-81, 2d.3h.50m
  [1 lists not shown]: [too many]
 default:
  user-filters: 14-0, never
  easylist: 72225-20, 2d.3h.50m
  easyprivacy: 32940-163, 2d.3h.50m
  plowe-0: 3727-1075, 2d.3h.50m
  ublock-badware: 7330-145, 2d.3h.50m
  ublock-filters: 35299-178, 2d.3h.50m
  ublock-privacy: 614-85, 2d.3h.50m
  ublock-quick-fixes: 184-123, 1m
  ublock-unbreak: 2131-37, 2d.3h.50m
  urlhaus-1: 11530-2, 3h.2m
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoCommentFilterTemplate: none
supportStats:
 allReadyAfter: 7421 ms
 maxAssetCacheWait: 3128 ms
```
</details>

**Comment by mapx-** [comment] 2023-10-29 06:31
I cannot reproduce it using various emulation stuff.
If you can provide a way to reproduce it (without a real tablet), just comment here.
Closing for now.

**Closed by mapx-** 2023-10-29 06:31 UTC

**Comment by TotalImportance8529** [comment] 2023-10-29 06:58
1. Set to Galaxy Tab S4 
2. visit home page: `https://www.dailymail.co.uk`
3. Click any news

**Comment by mapx-** [comment] 2023-10-29 07:22
Test

`dailymail.co.uk##+js(trusted-set-cookie, AndroidExpiry, AndroidExpiry, 1year)`

**Comment by TotalImportance8529** [comment] 2023-10-29 07:25
It works

**Comment by mapx-** [comment] 2023-10-29 07:29
Enable `uBlock filters – Annoyances`
