### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by MackaG** [uBlockOrigin/uAssets#12685] opened 2022-04-10 09:49 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=DW3w4Y8cooA`

### Category

ads

### Describe the issue

Video  ads are not removed by ublock. Other photo-type ads are sucessfully removed by ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81287
  cosmetic: 49706
  scriptlet: 16619
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7794-8, 2d.16h.34m
    POL-2: 1273-13, 4d.15h.54m
    easylist: 65541-76, 2d.16h.36m
    easyprivacy: 26761-121, 2d.16h.35m
    plowe-0: 3690-819, 11d.2h.45m
    ublock-abuse: 74-0, 14h.20m
    ublock-badware: 4032-90, 14h.19m
    ublock-filters: 30483-128, 14h.18m
    ublock-privacy: 206-2, 6d.16h.7m
    ublock-quick-fixes: 125-4, 2d.16h.33m
    ublock-unbreak: 1733-43, 6d.16h.6m
    urlhaus-1: 7364-0, 2d.16h.32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2536 ms
  maxAssetCacheWait: 1205 ms
popupPanel: 
  blocked: 80
  blockedDetails: 
    youtube.com: 58
    doubleclick.net: 3
    google.com: 2
    google.pl: 1
    googleadservices.com: 2
    googlesyndication.com: 14
```
</details>

**Comment by JobcenterTycoon** [comment] 2022-04-10 10:16
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

try the solutions here: https://github.com/easylist/easylist/wiki/Youtube-Issues

**Closed by JobcenterTycoon** 2022-04-10 10:16 UTC

**Comment by iam-py-test** [comment] 2022-04-10 14:26
I can't reproduce the issue.
Please:
- Update ALL your filterlists (Click _Purge all caches_ and then _Update now_)
- Disable ALL other extensions in your browser
- Clear your cache and cookies (ATTENTION: You will be logged out of all websites. Be sure you know how to get back in to them, i.e. the password is stored in a password manager)
Retest. If you still see an issue, then post on https://github.com/uBlockOrigin/uAssets/issues/7636 with:
- More detailed steps to reproduce
- A screenshot of the ads
- A screenshot of the uBo Logger while reproducing.

**Comment by ghajini** [comment] 2022-04-11 17:51
video thumbnail hidden,any youtube video
eg
`https://m.youtube.com/watch?v=N_vWiuPNUXw`
