### ISSUE TITLE
jpost.com

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#251] opened 2016-12-30 16:27 UTC
### URL(s) where the issue occurs

`http://www.jpost.com/International/Putin-weighs-response-as-US-Russian-tensions-boil-over-477013`

### Describe the issue

`jpost.com` pushes ads by using WebRTC.
### Screenshot(s)

Ads
![jp](https://cloud.githubusercontent.com/assets/16838044/21568269/73698808-ceb3-11e6-9d61-c1272bb05345.JPG)

WebRTC
![jp](https://cloud.githubusercontent.com/assets/16838044/21568318/deef1e12-ceb3-11e6-93b3-b80b12703264.PNG)

### Versions

- Browser/version: Chrome 55
- uBlock Origin version: 1.10.4

### Settings

- default

### Notes

`jpost.com` pushes the ads inspite of the filter
`jpost.com##script:inject(nowebrtc.js)`, which is already part of  `uBlock filters`‎
I added `jpost.com` to the contentscript in `uBlock Origin Extra 2.3`.
That solves the issue.

**Comment by gorhill** [comment] 2016-12-30 17:02
I am going to experiment to find a better solution. I believe it's possible to leverage a filter such as `*$websocket,domain=...` to also decide whether or not WebRTC should disabled. If this works, I will consider adding such solution to uBO itself, and that mean it would be possible to filter out such WebRTC abuse with existing filter syntax.

**Comment by uBlock-user** [comment] 2016-12-30 18:31
Do webrtc connections talk to webRequest API ?

**Comment by gorhill** [comment] 2016-12-30 19:26
Fix in <https://github.com/gorhill/uBO-Extra/releases/tag/2.4rc0>.

**Comment by okiehsch** [comment] 2016-12-30 20:16
With `uBlock Origin Extra 2.4`  ` jpost.com` still pushes ads using WebRTC, the two screenshots
above are still valid.

`*$websocket,domain=jpost` is part of `Easylist`
![jpost3](https://cloud.githubusercontent.com/assets/16838044/21571912/21a882aa-ced4-11e6-9363-95334a5b7502.PNG)


Console
![jpost1](https://cloud.githubusercontent.com/assets/16838044/21571863/b40a8432-ced3-11e6-81bf-bf2309084738.PNG)

The `Uncaught TypeErrors` are all caused by `jpost.com##script:inject(nowebrtc.js)`

**Comment by gorhill** [comment] 2016-12-30 20:22
Can't reproduce (with updated filter lists):

![a](https://cloud.githubusercontent.com/assets/585534/21572105/a20faa76-cea3-11e6-93b9-d329ae9d1c8b.png)

Notice the violation re. `ws://www.jpost.com/`, this is caused by the attempt to create a WebRTC connection.

**Comment by okiehsch** [comment] 2016-12-30 20:50
I see in your screenshot that you block cookies. 
Does it also work if you allow them?
Because if I block cookies there are no WebRTC connections on `jpost.com`-
Even if I don't use `uBlock Origin Extra` at all.
![jpost6](https://cloud.githubusercontent.com/assets/16838044/21572492/b914c14e-ced9-11e6-8829-865b1bd489b1.JPG)

My logger output is different though.
![jost](https://cloud.githubusercontent.com/assets/16838044/21572511/fb85e814-ced9-11e6-8541-23744d576b1d.PNG)

**Comment by gorhill** [comment] 2016-12-30 21:46
The warning `ws://www.jpost.com/` should be in there, it's not, as if you are not running uBO-Extra 2.4.

**Comment by gorhill** [comment] 2016-12-30 21:49
Never mind, I can reproduce with Chromium 53, but not Chrome 57. I need to investigate.

**Comment by gorhill** [comment] 2016-12-30 21:54
Ok, with current Chromium, RTCPeerConnection is called webkitRTCPeerConnection.

**Comment by gorhill** [comment] 2016-12-30 22:10
Fixed in latest release: <https://github.com/gorhill/uBO-Extra/releases>. Sorry for the trouble.

**Comment by okiehsch** [comment] 2016-12-30 22:12
Works, after your comment I already tried with a modiefied  contentscript thanks.

**Closed** 2016-12-30 22:46 UTC

**Comment by gorhill** [comment] 2016-12-31 16:57
Will use in uBO-Extra doc:

![a](https://cloud.githubusercontent.com/assets/585534/21578491/5f238ad6-cf50-11e6-9d27-a46e5e4673db.png)

**Comment by rjkpa** [comment] 2017-01-01 18:15
What if the filter is of type `||$websocket` ? Will all webrtc connections still be severed  or do I need to mention domain name ?

**Comment by okiehsch** [comment] 2017-01-01 18:37
A blanket block `*$websocket` will block all `WebRTC` connections , if you use `uBlockO Extra`.
If a site legitimately needs WebRTC, you can use 
`@@*$websocket,domain=example.com`

**Comment by rjkpa** [comment] 2017-01-01 18:48
> A blanket block *$websocket will block all WebRTC connections , if you use uBlockO Extra.

Tested. It doesn't. 

Steps to Reproduce.

Add `||$websocket` to `My Filters`
Remove any filters pertaining to `crackberry.com` in regards to webrtc and deactivate `uBlock Filters` since the patch has been added there now,
Visit `crackberry.com`, connection will created within next few seconds.

**Comment by rjkpa** [comment] 2017-01-01 18:59
Yes that appears in the console too.

However, check `chrome://webrtc-internals` and then the website(scroll if need to).

**Comment by okiehsch** [comment] 2017-01-01 19:06
I am sorry, but `chrome://webrtc-internals` is and remains entry regardless of any scrolling, or randomly
clicking on any article.
Can you upload a screenshot of your console output and corresponding `chrome://webrtc-internal`?

**Comment by rjkpa** [comment] 2017-01-01 19:15
My apologies, when I removed all my filters pertaining to `crackberry.com`, I mistakenly also removed `||$websocket`, and then ran the test, which caused me to question why it wasn't working. That removal caused the connection to appear in `chrome://webrtc-internals` logs which led me to believe that it wasn't working. So my test was wrong. 

Anyways, you're right, blanket blocking websockets also blanket blocks webrtc's too. Thanks for your time.

**Comment by okiehsch** [comment] 2017-01-02 22:31
Back to WebRTC ads with `jpost.com`, sigh.
This time caused by `Easylist`, which for reasons unknown removed basically every `jpost.com` relevant
network/websocket filter.
`https://hg.adblockplus.org/easylist/rev/840904249495`
`https://hg.adblockplus.org/easylist/rev/3a736c5b1c43`
Adding `*$websocket,domain=jpost.com` gets us back to blocking WebRTC.

**Comment by uBlock-user** [comment] 2017-01-03 09:49
I suppose this was done in response to this - https://forums.lanik.us/viewtopic.php?f=64&t=34782

**Comment by gorhill** [comment] 2017-01-03 13:31
I did check with ABP before the EasyList removals when that post was first made on Dec 26, and the video player was broken with EasyList, but this did not happen with uBO. I have no clue why and I did not investigate further though I am curious of the explanation (a cautious assumption is that if that issue can happen to ABP, it can happen o uBO).
![a](https://cloud.githubusercontent.com/assets/585534/21609123/9b0a6a3e-d18e-11e6-8c96-0a8231cc4f70.png)

**Comment by okiehsch** [comment] 2017-01-03 17:34
>  I am curious of the explanation

I could reproduce with ABP. The reason ironically appears to be the filter,
`*$websocket,domain=jpost.com`

If you restore the whole deleted filterset without `*$websocket,domain=jpost.com`, the videos play
fine, with it you get the error in the screenshot.
Console output
![adblo](https://cloud.githubusercontent.com/assets/16838044/21616798/4b55182c-d1e3-11e6-8e75-9c29484db935.PNG)

**Comment by gorhill** [comment] 2017-01-03 19:32
> I could reproduce with ABP. The reason ironically appears to be the filter, `*$websocket,domain=jpost.com`

Well this narrow the issue quite a lot. I can confirm the issue is caused by the use of the `child-src` CSP directive, whereas uBO uses the `frame-src` instead (which will cause a warning at the console that it is being deprecated). If I use `child-src` in uBO's code, the error appears.

**Comment by gorhill** [comment] 2017-01-03 19:39
> (which will cause a warning at the console that it is being deprecated).

Wait, never mind, <https://w3c.github.io/webappsec-csp/#directive-child-src>:

> The `child-src` model has been substantially altered:
> 
> The `frame-src` directive, which was deprecated in CSP Level 2, has been undeprecated, but continues to defer to `child-src` if not present (which defers to `default-src` in turn).
> A `worker-src` directive has been added, deferring to `script-src` if not present (which likewise defers to `default-src` in turn).
> `child-src` is now deprecated.
> Dedicated workers now always inherit their creator’s policy.

**Comment by Khrin** [comment] 2017-01-04 12:35
When I checked on December 26th, for me it was the filter `|blob:$domain=jpost.com` that blocked the video up there and I haven't seen any other ways to solve the problem than removing the exception. @gorhill, be careful that also the comments section present in almost every article uses websockets. Possibly also the Brightcove player uses websockets, but I'm unsure about.

**Comment by gorhill** [comment] 2017-01-04 14:08
> for me it was the filter `|blob:$domain=jpost.com` that blocked the video up there

The worker is launched as a blob-based script, so that filter would have the same effect as a `child-src` directive not allowing blob. Chrome webRequest API won't be passed requests from blob or data, hence that `|blob:` filter won't be hit with uBO.

> be careful that also the comments section present in almost every article uses websockets

From my end, the comment sections seem to work fine.

**Comment by Khrin** [comment] 2017-01-04 15:01
> From my end, the comment sections seem to work fine.
Good to know, then disregard what I said.

**Comment by okiehsch** [comment] 2017-01-31 02:35
> it's possible to leverage a filter such as *$websocket,domain=... to also decide whether or not WebRTC should disabled.

`veteranstoday.com` is somehow able to establish a WebRTC connection with a filter 
*$websocket present and uBO-Extra 2.8 or 2.9 enabled,

*$websocket
![vet](https://cloud.githubusercontent.com/assets/16838044/22450277/d950939e-e765-11e6-894f-ea1299d8926a.PNG)

WebRTC
![vet2](https://cloud.githubusercontent.com/assets/16838044/22450313/093a149a-e766-11e6-9d62-afc9298564b0.PNG)

Console
![vet3](https://cloud.githubusercontent.com/assets/16838044/22450341/2f9e8e68-e766-11e6-9e61-345be8932b5e.PNG)

**Comment by gorhill** [comment] 2017-02-01 18:30
> `veteranstoday.com`, another `uponit` site, is able to establish a WebRTC connection

This also affects Firefox. I know why this happens. I do have a scriplet-based solution, but given that this also affects Firefox, I have been thinking about what could be done to solve the issue and similar such issues without the need for uBO-Extra, and I've been tinkering and still need to tinker more with an idea about how to inject scriptlet code before anything else executes in a web page.<sup>[1]</sup>

[1] Chrome API/Firefox allows content script code to execute before anything else, however uBO requires a roundtrip to the main process to fetch the scriptlets for the current web page, which means it's impossible to guarantee that the scriptlet code will run before anything else -- but there might be a way..

**Comment by okiehsch** [comment] 2017-02-04 22:38
Works well, I now can use `script:inject(upmanager-defuser.js)` on sites like 
`allthetests.com` to prevent them trying to establish a websocket connection in the first place and 
that didn't work before the fix.
