### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by VernonStow** [uBlockOrigin/uAssets#3046] opened 2018-07-26 21:55 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`www.msn.com`

### Describe the issue

Anti-adblock message or completely blocked page

### Screenshot(s)

![screenshot-2018-07-26-15-26-54](https://user-images.githubusercontent.com/15573459/43290434-ee71b0f0-90e2-11e8-89dd-3e850d68c778.png)
![screenshot-2018-07-26-15-27-41](https://user-images.githubusercontent.com/15573459/43290449-f3d51e9c-90e2-11e8-891b-7fe3439fc4fe.png)

### Versions

- Browser/version: Chromium Version 69.0.3496.0 (Official Build) (32-bit)

- uBlock Origin version: 1.16.14

### Settings

- Default
- (Also did not work with my custom msn.com filter list, attached) 
[MSN filters.txt](https://github.com/uBlockOrigin/uAssets/files/2233701/MSN.filters.txt)

### Notes

The issue occurs only with latest Chromium 69 build, not with Firefox or Chromium 67, and occurs whether or not I disable my custom msn.com filter list (which I developed to prevent ad reinstertion). The page behaves normally only if uBO is disabled.

**Comment by okiehsch** [comment] 2018-07-26 22:11
Maybe an Instart Logic issue ? 
I can't reproduce, do you have [uBO-extra](https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful) installed?

**Comment by VernonStow** [comment] 2018-07-26 23:02
Yes, I'm on Windows 7. I tried it both with and without uBlock Origin Extra enabled -- no difference.

**Comment by okiehsch** [comment] 2018-07-26 23:06
I can't reproduce with Linux or Windows 10.
![image](https://user-images.githubusercontent.com/16838044/43293207-46251d54-9139-11e8-9889-cc5f7b5633db.png)

**Comment by VernonStow** [comment] 2018-07-26 23:18
A little more info: if I visit the site with only stock uBO filters AND with uBO Extra turned off, it will display the content but uses a lot of RAM (running the CPU fan very hard) and shows multiple rows of "sponsored content" as one scrolls down the page. If I enable either my custom filters, the Adguard Annoyances Filter, or uBO Extra, the page shows an error.

**Comment by VernonStow** [comment] 2018-07-27 00:39
Update: With my list (and Adguard Annoyances filter and uBO Extra) enabled, I can get the content to appear normally by whitelisting the following:

`@@||*.g00.msn.com^$subdocument,domain=www.msn.com`
`@@||*.g00.msn.com/*/$$xmlhttprequest,domain=www.msn.com`
`@@||*.g00.msn.com/g00/*$xmlhttprequest,domain=*.g00.msn.com`

I noticed that on each page load, "g00" appears briefly in the address bar and seems to serve as a check for ad blocking.

**Comment by okiehsch** [comment] 2018-07-27 00:49
What filter list is blocking those requests?

**Comment by okiehsch** [comment] 2018-07-27 01:29
The g00 requests are from `Instart Logic`. There should not be any if `uBO-Extra` is enabled.

Can you update your `EasyList` filters, they changed 
`||g00.msn.com^$other,subdocument,xmlhttprequest,domain=msn.com`
to
`||g00.msn.com^$other,domain=msn.com`

**Comment by VernonStow** [comment] 2018-07-27 01:43
Updated Easy List filter, deleted my "g00" whitelist filter.

Pages now showing all content again, but with many new "sponsored ads" appearing and causing excessive RAM and fan usage, even with latest uBO-Extra 2.74 enabled.

**Comment by VernonStow** [comment] 2018-07-27 01:48
FWIW, my MSN Filter, updated to block the latest sponsored content:

[MSN filters.txt](https://github.com/uBlockOrigin/uAssets/files/2234102/MSN.filters.txt)

**Comment by okiehsch** [comment] 2018-07-27 01:48
I can't reproduce with uBO-Extra enabled, so let's wait and see if gorhill can reproduce.

**Comment by smed79** [comment] 2018-07-27 03:15
> do you get any g00-requests with uBO-Extra enabled?

**ONLY** if i disable "uBO-Extra" https://streamable.com/e/x1y8v

**Comment by VernonStow** [comment] 2018-07-27 04:14
With Google Chrome Portable and uBO and uBO-Extra, there are no sponsored ads on MSN homepage or within the articles. However, with a brand new profile on Chromium Portable (both 68 archive and 69 Portable Nik build) and the same completely default uBO (updated to the latest filters) and uBO-Extra, the sponsored ad mess appears. It would appear that uBO-Extra is not working in Chromium as it does on Chrome.

**Comment by gorhill** [comment] 2018-07-27 11:41
I can't reproduce with neither Chromium 67 or Chrome 69, with uBO-Extra enabled.

I can reproduce when uBO-Extra is not enabled.

**Comment by okiehsch** [comment] 2018-07-27 19:15
Closing, `g00-requests` issue can only be fixed by using `uBO-Extra`.

If that does not work the proper place to discuss any further is [uBO-Extra](https://github.com/gorhill/uBO-Extra)

**Closed by okiehsch** 2018-07-27 19:15 UTC
Labels: unable to reproduce
