### ISSUE TITLE
[Auto pop-up & block saving images] 699pic.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9634] opened 2021-07-26 08:56 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://699pic.com/tupian-401953471.html`

### Describe the issue

1. The page will automatically pop up a login box, but you can't simply block the login box because it will prevent the user from logging in(You may need to refresh two or more times)
2. This page will prevent users from saving images(Right click)
Thanks!

### Screenshot(s)

![2021-07-26_16-49-49](https://user-images.githubusercontent.com/66902050/126962271-fb247a8b-8bca-4cb4-8d7b-0adae56731c7.gif)

![2021-07-26_16-54-43](https://user-images.githubusercontent.com/66902050/126962253-63f79a3e-0f13-49c0-84ba-5cc506f1fb73.gif)

### uBlock Origin version

v1.36.2

### Browser name and version

Microsoft Edge 91.0.864.70

### Settings

No need

**Comment by avotoko** [comment] 2021-07-26 10:19
1. Wouldn't the [login | register (登录 | 注册)] button in the upper right corner of the page do the same function if the dialog overlapping the image was removed?
2. If you click on the image, only the image will appear in a new tab, where you can save it.

**Comment by shenzhiming88** [comment] 2021-07-26 10:47
> 1. Wouldn't the [login | register (登录 | 注册)] button in the upper right corner of the page do the same function if the dialog overlapping the image was removed?
> 2. If you click on the image, only the image will appear in a new tab, where you can save it.

Hello!

1. It is not a pop-up window overlaid on the image, but a login box that pops up automatically after refreshing several times, you can check the GIF image
2. but the right click is disabled, in which case I need to click more than once

**Comment by avotoko** [comment] 2021-07-26 11:52
The following filter will hide the popup shown below.
```
699pic.com##.viewLimit
```
![popup](https://user-images.githubusercontent.com/53560467/126983192-2c4637cf-57ce-40e9-8bfb-9c8de5d1f538.jpg)
Does this work the way you want it to?

And I can't think of a way to enable right-clicking.

**Comment by shenzhiming88** [comment] 2021-07-26 11:57
> The following filter will hide the popup shown below.
> 
> ```
> 699pic.com##.viewLimit
> ```
> 
> ![popup](https://user-images.githubusercontent.com/53560467/126983192-2c4637cf-57ce-40e9-8bfb-9c8de5d1f538.jpg)
> Does this work the way you want it to?
> 
> And I can't think of a way to enable right-clicking.

Thanks. Actually, I have created a pull request for it https://github.com/easylist/easylist/pull/8433 , and what I actually want to remove is the automatic login box, you can see the GIF screenshot above, after the second refresh, the login box pops up automatically, but you can't just block that element, because then you can't login

**Comment by avotoko** [comment] 2021-07-26 13:08
Finally, I understand. In my environment, the login box never appears automatically unless I click the login button.  
I apologize that I did not understand your original description correctly.
I'm sorry I couldn't be of more help to you.

**Comment by shenzhiming88** [comment] 2021-07-26 13:09
> Finally, I understand. In my environment, the login box never appears automatically unless I click the login button.
> I apologize that I did not understand your original description correctly.
> I'm sorry I couldn't be of more help to you.

Okay, that's fine, thanks for your help!

**Comment by uBlock-user** [comment] 2021-07-26 13:17
@shenzhiming88 `699pic.com###new-login-mask` takes care of the login popup.

**Comment by shenzhiming88** [comment] 2021-07-26 13:20
> @shenzhiming88 `699pic.com###new-login-mask` takes care of the login popup.

Hello!
However, it will prevent the user from logging in

**Comment by uBlock-user** [comment] 2021-07-26 13:21
login popup appears whrn I click the logiin button

**Comment by shenzhiming88** [comment] 2021-07-26 13:25
> login popup appears whrn I click the logiin button

Hello!
But on my computer, after two refreshes it automatically pops up

**Comment by shenzhiming88** [comment] 2021-07-26 13:57
@uBlock-user OK, so both of them can't be solved? Thanks!

**Comment by uBlock-user** [comment] 2021-07-26 13:59
`document.getElementById('photo').oncontextmenu` and `document.getElementById('photo').onmousedown` cannot be set by any uBO scriptlets. I don't know about login popup.

**Comment by shenzhiming88** [comment] 2021-07-26 15:56
@avotoko Hello!
I'm using privacy mode so I can reproduce this pop-up consistently
So the filter rules you provided will work?
Thank you!

**Comment by shenzhiming88** [comment] 2021-07-27 06:59
@uBlock-user It works
```txt
699pic.com##+js(nosiif, clearInterval(loginReady))
```
Thanks @avotoko !

**Comment by shenzhiming88** [comment] 2021-07-27 07:02
@uBlock-user 
Hello!
This doesn't seem to work https://github.com/uBlockOrigin/uAssets/commit/5de6242786134b49dae6711aea402f4a7e9db6e5
Right-click on the picture and still no menu appears

**Comment by uBlock-user** [comment] 2021-07-27 07:03
@shenzhiming88 incomplete fix, see - https://github.com/uBlockOrigin/uAssets/issues/9634#issuecomment-886728368

**Comment by shenzhiming88** [comment] 2021-07-27 07:04
Fine. Thank you @uBlock-user

**Comment by uBlock-user** [comment] 2021-07-27 07:06
Keep it open, I have asked about that to gorhill in team discussions.

**Comment by CyberMan571** [comment] 2021-07-29 01:51
![image](https://user-images.githubusercontent.com/30759335/127417754-6ea571bc-ef16-4add-8379-53ad92220b8e.png)
699pic.com##.viewLimit

**Comment by CyberMan571** [comment] 2021-07-29 02:02
<details><summary>Logger output</summary>

```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/downjsV3/detail.v5.8.12.tj.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/js/activity/vipStation98.v3.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/v2.0/fix/v2.4/common-js.v2.4.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/downjsV3/article.v5.9.7.photo.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!jquery.flex-images.min.1.0.4.js,common/verify.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/v2.0/detail/detail-fixedtop.v2.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/v2.0/plugin/udeskApi.js?time=1627523634214
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/agent/agent_right_nav.v3.3.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/v2.0/fix/v2.4/jfsc/daily-sign.v7.js
```
```
+4
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/js/home/loginBox.v2.3.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/downjsV3/detail.v5.8.12.tj.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/js/activity/vipStation98.v3.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/v2.0/fix/v2.4/common-js.v2.4.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/downjsV3/article.v5.9.7.photo.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!jquery.flex-images.min.1.0.4.js,common/verify.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/v2.0/detail/detail-fixedtop.v2.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/agent/agent_right_nav.v3.3.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/v2.0/fix/v2.4/jfsc/daily-sign.v7.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/js/base/base_search20201221.v5.2.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!common/login.v4.8.js,common/reg.v4.0.js,common/verify.js?v=1
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/base.v7.3.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!jquery.cookie.js,utils.v1.1.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/!!v2.0/module/public-base-search-v11.2.js?v=2.0
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/js/home/loginBox.v2.3.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://static.699pic.com/js/base/base_search20201221.v5.2.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!common/login.v4.8.js,common/reg.v4.0.js,common/verify.js?v=1
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/base.v7.3.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!jquery.cookie.js,utils.v1.1.js
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/!!v2.0/module/public-base-search-v11.2.js?v=2.0
```
```
+1
699pic.com * 1p-script block
--
699pic.com
1
script
https://js.699pic.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
```
```
+0
https://699pic.com/tupian-401953471.html
```
</details>
  Context menu  blocker code lines(or statements), inside 1p-scripts

**Comment by shenzhiming88** [comment] 2021-07-29 02:28
> Logger output
> 
> Context menu blocker code lines(or statements), inside 1p-scripts
> Hey Friends, can look at these?
> 
> also add it to my-filter
> `699pic.com##.viewLimit:remove()`

Ok, I will try it later. Thanks!

**Comment by CyberMan571** [comment] 2021-07-29 03:34
If, has not blocked  in 1p-script or CNAME 3p-script
shows this:
![image](https://user-images.githubusercontent.com/30759335/127423555-85262570-7cf1-4cf1-a441-30bdcc90219d.png)

**Comment by CyberMan571** [comment] 2021-07-29 03:42
<details><summary>Logger output</summary>

```
+6
699pic.com https://sheyingtu-js.b0.aicdn.com/js/!!common/ script  block
--
699pic.com
3
script
https://sheyingtu-js.b0.aicdn.com/js/!!common/login.v4.8.js,common/reg.v4.0.js,common/verify.js?v=1
aliasURL=https://js.699pic.com/js/!!common/login.v4.8.js,common/reg.v4.0.js,common/verify.js?v=1
```
```
+6
699pic.com https://sheyingtu-js.b0.aicdn.com/js/!!common/ script  block
--
699pic.com
3
script
https://sheyingtu-js.b0.aicdn.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
aliasURL=https://js.699pic.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
```
```
+2
699pic.com https://sheyingtu-js.b0.aicdn.com/js/!!common/ script  block
--
699pic.com
3
script
https://sheyingtu-js.b0.aicdn.com/js/!!common/login.v4.8.js,common/reg.v4.0.js,common/verify.js?v=1
aliasURL=https://js.699pic.com/js/!!common/login.v4.8.js,common/reg.v4.0.js,common/verify.js?v=1
```
```
+2
699pic.com https://sheyingtu-js.b0.aicdn.com/js/!!common/ script  block
--
699pic.com
3
script
https://sheyingtu-js.b0.aicdn.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
aliasURL=https://js.699pic.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
```
```
+0
https://699pic.com/tupian-401953471.html
```
</details>

**Comment by shenzhiming88** [comment] 2021-07-29 12:44
@CyberMan571 Hello!
That Pull Request has been merged, but I don't think the blocking of that element should be directly related to the disabling of the right click, and I don't really understand the rules of advanced filtering, sorry!

**Comment by shenzhiming88** [comment] 2021-07-29 12:50
@CyberMan571 Hello!
You are right. Once this Pull Request is merged, I can save the image using the right click
![image](https://user-images.githubusercontent.com/66902050/127494767-0d252176-4bad-4b38-aa47-59ea35d0993b.png)
@uBlock-user I think you can close this issue now

**Comment by CyberMan571** [comment] 2021-07-29 12:51
@shenzhiming88 
Yes, Advanced filtering is difficult!
No don't close I look it

**Comment by uBlock-user** [comment] 2021-07-29 12:52
> Once this Pull Request is merged, I can save the image using the right click

@shenzhiming88 what pull request ?

**Comment by shenzhiming88** [comment] 2021-07-29 12:52
@uBlock-user https://github.com/easylist/easylist/pull/8466

**Comment by shenzhiming88** [comment] 2021-07-29 12:56
> @shenzhiming88
> Yes, advanced filtering is difficult!
> No, don't close! I look it

Fine. Thank you for your help!

**Comment by uBlock-user** [comment] 2021-07-29 12:56
That PR has already been merged. Force update Fanboy Annoyances list.

**Comment by CyberMan571** [comment] 2021-07-29 16:11
```js
document.getElementById('photo').oncontextmenu = function(){ return false; }
document.getElementById('photo').onmousedown = function(){ return false; }
$('.tags a.kw_noid').on('click',function(){
    window.env.search($(this).html());
});
```
```js
<script>
    function renderRightClick(vip) {
        $('#photo').off("contextmenu");
        var tempRightClick = false;
        $("body").on("contextmenu", ".photo-img img", function(e) {
            var scrollTop = $(window).scrollTop();
            var getClickX = e.clientX - $(".photo-img").offset().left;
            var getClickY = e.clientY - $(".photo-img").offset().top + scrollTop;
            // 是否有图片套餐
            var rightClickStr = '';
            window.event.returnValue = false;
            $(".rightclick-pop").empty();
            if(vip == 'hasvip') {
                rightClickStr = '<div class="rightclick-pop-left fl"><i class="iconfont icon-xiaolian"></i></div>'+
                '<div class="rightclick-pop-right fl">'+
                    '<p>此素材受到版权保护，如需使用</p>'+
                    '<p class="rightclick-pop-info">请下载图片获取授权</p>'+
                '</div>';
            } else {
                rightClickStr = '<a href="/vip/index?click_type=705" target="_blank">'+
                    '<div class="rightclick-pop-left fl"><i class="iconfont icon-xiaolian"></i></div>'+
                    '<div class="rightclick-pop-right fl">'+
                        '<p>此素材受到版权保护，如需使用</p>'+
                        '<p class="rightclick-pop-info">请加入VIP，下载高清无水印大图</p>'+
                    '</div>'
                '</a>';
            }
            $(".rightclick-pop").append(rightClickStr);
            $(".rightclick-pop-bg").css({"top": getClickY + 'px', "left": getClickX + 'px'}).fadeIn(300);
            tempRightClick = true;
            return false;
        })
        $("body").on("mousemove", function(e) {
            if(tempRightClick && !$(e.target).is($("img")) && !$(e.target).parents().is($(".photo-img"))) {
                $(".rightclick-pop-bg").fadeOut(300);
                tempRightClick = false;
            }
        })
    }
    // 点击右键
    renderRightClick($(".rightclick-pop-bg").attr('data-hasvip'))
</script>
```
`
https://js.699pic.com/js/!!common/jquery-1.7.1.min.js,jquery.flex-images.min.1.0.4.js,jquery.lazyload.min.js
`
If blocked this above, shows context menu!
 

I  search a similar option:
/bootstrap.min.js##+js(block something or disable lines), domain=example.TLD

**Comment by shenzhiming88** [comment] 2021-07-30 13:26
@uBlock-user Please reopen it, I found that I enabled a third party script in Tampermonkey to make the right click menu pop up properly

**Comment by uBlock-user** [comment] 2021-07-30 13:27
@shenzhiming88 didn't that work, as you suggested before ?

**Comment by shenzhiming88** [comment] 2021-07-30 13:29
> @shenzhiming88 didn't that work, as you suggested before ?

No, because I enabled a script at that time and forgot to close it, sorry
`https://greasyfork.org/scripts/391193`

**Comment by uBlock-user** [comment] 2021-07-30 13:32
@shenzhiming88 Enable Fanboy Annoyances list and try again. Works for me.

**Comment by shenzhiming88** [comment] 2021-07-30 13:35
@uBlock-user Hello! I have forced the update of Fanboy's Annoyance List to version 202107301300, but the right click still does not work
This is the rule I subscribed to
![image](https://user-images.githubusercontent.com/66902050/127660813-21a49706-b8f1-43f2-8e4f-6532a1f7fa57.png)

**Comment by uBlock-user** [comment] 2021-07-30 13:41
Strangely it worked that day, but the cause mentioned in https://github.com/uBlockOrigin/uAssets/issues/9634#issuecomment-886728368 is back, must have been a fluke.

**Comment by shenzhiming88** [comment] 2021-07-30 13:47
According to what @CyberMan571 said, is it possible to disable a script to achieve the result that the right-click menu appears?

**Comment by uBlock-user** [comment] 2021-07-30 13:55
@shenzhiming88 Test `699pic.com##+js(aost, document.getElementById, photo)`

**Comment by shenzhiming88** [comment] 2021-07-30 13:57
@uBlock-user Works. Thank you for your help!
![image](https://user-images.githubusercontent.com/66902050/127663855-32b74ce8-64b0-4948-8a8c-04a699902f77.png)

**Closed** 2021-07-30 14:02 UTC

**Comment by CyberMan571** [comment] 2021-07-30 15:47
@shenzhiming88   you have the chance to choose  although hard way
You can also learn programming language and web development, including me!

Simple and best speedy way!
`https://addons.mozilla.org/en-US/firefox/addon/absolute-enable-right-click/`

**Comment by uBlock-user** [comment] 2021-07-30 15:51
> `https://addons.mozilla.org/en-US/firefox/addon/absolute-enable-right-click/`

or just toggle `dom.event.contextmenu.enabled` to `false` in about:config for Firefox.

**Comment by CyberMan571** [comment] 2021-07-30 16:07
also, `dom.event.clipboardevents.enabled` 

good choice
`https://gist.github.com/0XDE57/fbd302cef7693e62c769` 
Get to be careful

```
plugins.enumerable_names = blank
Disable site reading installed plugins.
```
can protect ublock detection? I will test

**Comment by CyberMan571** [comment] 2021-07-30 16:25
`dom.event.clipboardevents.enabled` is false mean  
it must  `dom.event.clipboardevents.enable:false`

**Comment by CyberMan571** [comment] 2021-07-30 16:44
@uBlock-user 
abort-on-stack-trace scriptlet is missing in wiki Resources-Library! update missing them? can you do?

**Comment by uBlock-user** [comment] 2021-10-21 15:17
Did you disable `699pic.com##+js(aost, document.getElementById, photo)` before adding the new filter ?

**Comment by uBlock-user** [comment] 2021-10-21 16:12
Without shift-right-click, contextmenu never appears for me.

**Comment by gorhill** [comment] 2021-10-21 16:59
> without clicking the photo

You can't. Sometimes you have to accept the little workarounds. You could file an issue with Chrome to support Firefox's way to restore context menu -- surely pressing <kbd>Shift</kbd> should not be seen as a burden?
