### ISSUE TITLE
ytlarge.com: detection

### ISSUE THREAD

**Issue by mohitmeanslove** [uBlockOrigin/uAssets#22425] opened 2024-02-10 07:58 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [x] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://ytlarge.com/youtube/monetization-checker
```

### Description

Adblock detected. Below are the steps to reproduce
1) Open website : `https://ytlarge.com/youtube/monetization-checker`
2) Put any youtube video link in box
3) Enter Captcha and press enter. Wait for 5 seconds, It will show this below adblock warning.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![11](https://github.com/uBlockOrigin/uAssets/assets/84594515/e2c113e6-8d0d-4205-9765-354628853626)

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 107485
 cosmetic: 115857
 scriptlet: 23652
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  plowe-0: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance.txt: 79722-179, 2h.35m
 default:
  easylist: 80577-41, 2h.30m Δ
  easyprivacy: 50147-174, 2h.30m Δ
  ublock-filters: 37190-228, 2h.35m
filterset (user): [empty]
trustedset:
 added: [array of 19 redacted]
userSettings:
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 autoUpdatePeriod: 10
supportStats:
 allReadyAfter: 229 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: browser.storage.local
```yaml


```
</details>

**Comment by mohitmeanslove** [comment] 2024-02-11 05:15
@mapx-  It's not working. Please reproduce the same steps which i have mentioned it earlier.

**Comment by ItsProfessional** [comment] 2024-02-11 06:39
Keep this open, the site updates it's anti-adb frequently (it was handled in the quick list long before this issue)

**Comment by codex1001** [comment] 2024-02-11 18:17
problem solved. Thanks.

**Comment by mohitmeanslove** [comment] 2024-02-11 22:51
Problem not solved . Please tell me that what should i add in ''My Filter'' tab in Ublock origin

**Comment by mohitmeanslove** [comment] 2024-02-11 22:55
@ItsProfessional @mapx- Problem not solved . Please tell me that what should i add in ''My Filter'' tab in Ublock origin

**Comment by Daxy7** [comment] 2024-02-12 01:44
what about
```
@@||googleads.g.doubleclick.net/pagead/ads$frame,removeparam=/^(?:correlator|f[cr-w]|p[e-sv]|u_|ga_|url|dt|adk)/,domain=ytlarge.com
@@||googleads.g.doubleclick.net/pagead/ads$frame,domain=ytlarge.com
```
is there ads?

**Comment by mohitmeanslove** [comment] 2024-02-13 12:08
@mapx @ItsProfessional @Daxy7 

Please Add this code in uBO filters. It will work. 

```
@@||ytlarge.com^$script,~third-party
@@||fundingchoicesmessages.google.com^$domain=ytlarge.com
@@||pagead2.googlesyndication.com^$domain=ytlarge.com
@@||tpc.googlesyndication.com^$domain=ytlarge.com
@@||googleads.g.doubleclick.net/pagead/html/*/zrt_lookup_fy2021.html$domain=ytlarge.com
@@||googleads.g.doubleclick.net/pagead/ads?client=ca-pub-*&adk=$~xmlhttprequest,~script,~image,domain=ytlarge.com
```

**Comment by ItsProfessional** [comment] 2024-02-13 12:14
@mohitmeanslove Stop closing the issue, I said earlier:

Keep this open, the site updates it's anti-adb frequently

**Comment by jamesbuttler1999** [comment] 2024-03-15 17:43
- The issue isn't YouTube, Facebook, or Twitch-related.
- Confirm understanding of valid filter issue policies.
- Check for duplicate issues.
- Keep default filter lists intact.
- Verify the problem persists without additional lists or custom filters.
- Avoid using uBlock Origin with other blockers.
- Ensure the web browser's built-in blocker or DNS blocking isn't the cause.
- Other extensions aren't interfering.
- If it's a breakage or detection issue, confirm uBlock Origin's involvement and not a site problem. Provide the URL(s) experiencing the issue for targeted assistance.

**Comment by codex1001** [comment] 2024-03-22 00:38
There are gaps for ads. and the page gets longer. when I turn off ublock, it returns to normal. can you remove these gaps for blocked ads. 
![cw467](https://github.com/uBlockOrigin/uAssets/assets/135052551/a26161c2-aebd-402f-aac3-b32a8c0d88a0)

**Comment by codex1001** [comment] 2024-05-16 22:45
Hello, the ads are blocked, it's nice, but there are gaps. 
Can you remove these spaces? The site looks very bad and is slipping.
https://ytlarge.com/youtube/monetization-checker
![cw625](https://github.com/uBlockOrigin/uAssets/assets/135052551/02eece63-59a0-47b7-b247-bcaf21e23aec)

**Comment by codex1001** [comment] 2024-05-19 16:53
yes?

**Comment by codex1001** [comment] 2024-05-21 14:10
??????

**Comment by stephenhawk8054** [comment] 2024-05-29 06:36
https://github.com/uBlockOrigin/uAssets/commit/597e31483be5e50d9606ad60fe63597f23bd2ec1

**Closed by stephenhawk8054** 2024-05-29 06:36 UTC
Labels: ongoing

**Comment by codex1001** [comment] 2024-05-29 14:14
> [597e314'nın sohbeti ](https://github.com/uBlockOrigin/uAssets/commit/597e31483be5e50d9606ad60fe63597f23bd2ec1)

It made the site unworkable!
