### ISSUE TITLE
player.twitch.tv: ads

### ISSUE THREAD

**Issue by maximofrank39** [uBlockOrigin/uAssets#15459] opened 2022-10-28 17:12 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://player.twitch.tv/?channel=auronplay&parent=twitch.tv`

### Category

ads

### Describe the issue

I open the external Twitch player and I get the announcements

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 92
filterset (summary): 
  network: 90760
  cosmetic: 43437
  scriptlet: 17982
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62416-53, 1h.24m
    easyprivacy: 30816-1170, 1h.25m
    plowe-0: 3675-865, 8d.20h.26m
    spa-0: 3352-11, 1h.19m
    spa-1: 4817-179, 1h.20m
    ublock-abuse: 76-0, 8d.20h.28m
    ublock-badware: 3943-105, 1h.23m
    ublock-filters: 32282-173, 1h.22m
    ublock-privacy: 257-1, 8d.20h.29m
    ublock-quick-fixes: 423-21, 1h.17m
    ublock-unbreak: 1873-44, 1h.21m
    urlhaus-1: 11031-0, 1h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1545 ms (selfie)
  maxAssetCacheWait: 1079 ms
popupPanel: 
  blocked: 17
  no-large-media: true
  blockedDetails: 
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 14
```
</details>

**Comment by okiehsch** [comment] 2022-10-28 17:15
We closed the last issue you opened because it was a duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

If you open it again it is still a duplicate, all twitch related issues can be posted in https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by okiehsch** 2022-10-28 17:15 UTC
