### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by jberger-well** [uBlockOrigin/uAssets#11970] opened 2022-02-28 23:49 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

The body of the email message in Gmail does not display when uBlockOrigin is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 78145
  cosmetic: 41257
  scriptlet: 16499
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63931-9, 3d.4h.2m
    easyprivacy: 26620-122, 3d.4h.1m
    plowe-0: 3670-803, 7d.8h.33m
    ublock-abuse: 77-0, 3d.4h
    ublock-badware: 4025-83, 3d.3h.59m
    ublock-filters: 30347-157, 3d.3h.58m
    ublock-privacy: 202-2, 3d.3h.57m
    ublock-unbreak: 1715-39, 3d.3h.56m
    urlhaus-1: 6682-0, 1d.2h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3528 ms (selfie)
  maxAssetCacheWait: 3189 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    google.com: 7
```
</details>

**Comment by mark05e** [comment] 2022-03-01 00:24
Got the same issue. Following the thread.

**Comment by llacb47** [comment] 2022-03-01 00:39
https://github.com/uBlockOrigin/uAssets/issues/11906

**Comment by gwarser** [comment] 2022-03-01 00:41
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906

**Closed by gwarser** 2022-03-01 00:41 UTC

**Comment by iam-py-test** [comment] 2022-03-01 00:57
@jberger-well please 
- Check for other issues
- And update your filterlists
BEFORE reporting a new issue
