### ISSUE TITLE
Adblock Dedected on dropgalaxy.com

### ISSUE THREAD

**Issue by um488** [uBlockOrigin/uAssets#18078] opened 2023-05-14 19:59 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblock being detected again on dropgalaxy.com and its proxy sites.

### URL(s) where the issue occurs.

[dropgalaxy.com](https://dropgalaxy.com/drive/x4jjt4z8icbv)

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/112172426/4a739ca4-fe07-443e-a7e6-31905668064c)

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Firefox 114.0b3 (64-bit) and Chrome Version 114.0.5735.26 (Official Build) beta (64-bit)

### Settings

Enabled RU Adlist

**Comment by gorhill** [comment] 2023-05-14 20:24
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/17571>.

**Closed by gorhill** 2023-05-14 20:24 UTC

**Comment by JobcenterTycoon** [comment] 2023-05-14 21:40
There is a newer issue https://github.com/uBlockOrigin/uAssets/issues/18036

i added a new fix but they are known for their aggresive anti adblock.
