### ISSUE TITLE
Youtube bypassed ad blocker

### ISSUE THREAD

**Issue by cdodders** [uBlockOrigin/uAssets#10107] opened 2021-10-01 09:50 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

youtube.com

### Describe the issue

Youtube showed ads when watching video with adblock enabled

### uBlock Origin version

1.37.2

### Browser name and version

Chrome Version 94.0.4606.61

### Settings

Auto update filter lists

**Comment by gwarser** [comment] 2021-10-01 10:00
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by gwarser** 2021-10-01 10:00 UTC
