### ISSUE TITLE
tech.madshiba.fun: detection

### ISSUE THREAD

**Issue by kalabski** [uBlockOrigin/uAssets#14214] opened 2022-08-02 16:17 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tech.madshiba.fun/post/greatest-internet-internet-hosting-ideas`

### Category

detection

### Describe the issue

I was browsing this website and this suddenly pops up I can't block it because the whole website will not function, so I need your help guys to resolve this because I always browse this website and it irritates me all the time. thank you!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://snipboard.io/H8C5oK.jpg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 88540
  cosmetic: 115749
  scriptlet: 22034
  html: 721
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 77367-342, 1d.42m
    ublock-annoyances: 4523-4, never
  default: 
    user-filters: 2198-9, never
    ublock-filters: 33031-80, 2d.8h.8m
    ublock-badware: 4225-0, 2d.8h.7m
    ublock-privacy: 242-0, 2d.8h.6m
    ublock-abuse: 76-0, 2d.8h.5m
    ublock-unbreak: 1864-4, 2d.8h.4m
    ublock-quick-fixes: 351-1, 2h.23m
    easylist: 68906-599, 2d.8h.2m
    easyprivacy: 27460-581, 2d.8h.1m
    urlhaus-1: 4957-0, 2h.22m
    plowe-0: 3639-3, 2d.7h.59m
filterset (user): [array of 1997 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 18236 ms (selfie)
  maxAssetCacheWait: 3600 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    adskeeper.co.uk: 2
    aso1.net: 2
    d3u598arehftfk.cloudfront.net: 2
    googlesyndication.com: 1
    h12-media.com: 2
    orquideassp.com: 21
    quiziizz.github.io: 2
    surfe.pro: 9
```
</details>

**Comment by MasterKia** [comment] 2022-08-02 16:22
I can't reproduce.

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> added: 
    fanboy-annoyance: 77367-342, 1d.42m
    ublock-annoyances: 4523-4, never

Could you test with _**only the default filters**_?

**Comment by Procyon-b** [comment] 2022-08-02 16:32
I can't reproduce either. Can you test without your user filters?
Open ublock's dashboard, go to the "Filter lists" tab, deselect "My filters", click "Apply changes".
Test again. (and don't forget to reenable "My filters" afterwards)

**Comment by JobcenterTycoon** [comment] 2022-08-02 16:43
Reproduced on the startpage `https://madshiba.fun/`

**Comment by kalabski** [comment] 2022-08-10 18:52
Thank you guys for the quick response to this, but unfortunately this website detected uBlock again. Here's a screenshot right now https://snipboard.io/OHGwXc.jpg

**Comment by JobcenterTycoon** [comment] 2022-08-10 19:29
I get no anti adblock

**Comment by MasterKia** [comment] 2022-08-10 19:39
@kalabski Force update your lists and test again.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by ghajini** [comment] 2022-08-10 21:31
@kalabski 
it looks page is intermediate site so can you tell original site from where you landed on this page?

**Comment by kalabski** [comment] 2022-08-11 03:55
> @kalabski Force update your lists and test again. https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

I already did this, but it is the same. I tested it also from a different browser that this website usually doesn't detect but now it also detected uBlock.

**Comment by MasterKia** [comment] 2022-08-11 04:03
> this website

Please tell us the exact websites you're going through to get to the final destination.

**Comment by kalabski** [comment] 2022-08-11 04:05
> @kalabski it looks page is intermediate site so can you tell original site from where you landed on this page?

So I usually encounter this website from different shortlinks (usually birdurls.com) that redirects me to 
that website. If you guys wanted to test it, I can drop that shortlink here so you can try it.

**Comment by MasterKia** [comment] 2022-08-11 04:06
Send the shortlink.

**Comment by kalabski** [comment] 2022-08-11 04:07
> > this website
> 
> Please tell us the exact websites you're going through to get to the final destination.

This is the shortlink https://birdurls.com/fMQe 

> Send the shortlink.

Here's the shortlink https://birdurls.com/fMQe

**Closed** 2022-08-11 07:46 UTC
