### ISSUE TITLE
euw.op.gg: breakage

### ISSUE THREAD

**Issue by Ultraviolently** [uBlockOrigin/uAssets#12898] opened 2022-04-22 11:48 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://euw.op.gg/summoners/euw/TRASH%20PL%C3%84YER`

### Category

breakage

### Describe the issue

The website breaks when I use the new interface and try to check my match history, when I try to expand on the match history, it breaks and it becomes blank.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![1](https://user-images.githubusercontent.com/104204645/164708747-83176f7c-c589-4612-b34e-8d28aa6ab15a.PNG)
![2](https://user-images.githubusercontent.com/104204645/164708764-d0642a5e-fb4a-49e4-b588-fbed0fcbe584.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 94
filterset (summary): 
  network: 166595
  cosmetic: 184729
  scriptlet: 35375
  html: 646
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 21h.54m
    https://winhelp2002.mvps.org/hosts.txt: 8730-5, 21h.54m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 21h.54m
    adguard-generic: 64001-5209, 21h.55m
    adguard-mobile: 7595-217, 21h.54m
    adguard-spyware: 26250-1359, 21h.54m
    adguard-annoyance: 52126-3623, 21h.54m
    fanboy-annoyance: 69267-30619, 21h.54m
    fanboy-cookiemonster: 30410-95, 21h.54m
    ublock-annoyances: 4349-8, 21h.54m
    dpollock-0: 10364-1657, 21h.54m
    ara-0: 2566-0, 21h.54m
    adguard-spyware-url: 570-4, 21h.54m
    block-lan: 43-0, 21h.54m
    curben-phishing: 13717-3, 21h.54m
    curben-pup: 275-0, 21h.54m
  default: 
    user-filters: 5-0, never
    ublock-filters: 31295-93, 21h.55m
    ublock-badware: 4098-3, 21h.55m
    ublock-privacy: 217-0, 21h.55m
    ublock-abuse: 74-0, 21h.55m
    ublock-unbreak: 1774-1, 21h.55m
    easylist: 66265-1051, 21h.54m
    easyprivacy: 26858-10816, 21h.54m
    urlhaus-1: 7728-1, 21h.54m
    plowe-0: 3682-349, 21h.54m
    ublock-quick-fixes: 167-0, 21h.54m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1942 ms (selfie)
  maxAssetCacheWait: 1544 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    casalemedia.com: 1
    datadoghq-browser-agent.com: 1
    doubleclick.net: 1
    google-analytics.com: 3
    googletagmanager.com: 1
    gstatic.com: 4
    helpscout.net: 1
    jsdelivr.net: 2
    riotgames.com: 1
    vntsm.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-04-22 11:58
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/12887

**Closed by okiehsch** 2022-04-22 11:58 UTC

**Comment by JobcenterTycoon** [comment] 2022-04-22 12:00
Force update the filter lists
