### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by hauhui** [uBlockOrigin/uAssets#18925] opened 2023-07-10 13:44 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/`

### Category

detection

### Description

detection even updated all the lists
[log.txt](https://github.com/uBlockOrigin/uAssets/files/12002564/log.txt)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![capture](https://github.com/uBlockOrigin/uAssets/assets/66862737/a8d20101-2395-436e-980d-11e6c91148ef)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 31d.5h.20m
Chromium: 114
filterset (summary):
 network: 120597
 cosmetic: 193098
 scriptlet: 23305
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26280-29, 17m
  adguard-mobile-app-banners: 4407-10, 15m
  adguard-other-annoyances: 13062-9, 15m
  adguard-popup-overlays: 22931-62, 15m
  adguard-social: 20876-877, 15m
  adguard-widgets: 2196-3, 15m
  easylist-annoyances: 3892-285, never
  easylist-chat: 129-9, never
  easylist-newsletters: 6268-354, never
  easylist-notifications: 2636-1397, never
  fanboy-cookiemonster: 47713-3803, never
  fanboy-social: 16100-689, never
 default:
  user-filters: 0-0, never
  CHN-0: 24466-117, 17m
  easylist: 68127-124, 17m
  easyprivacy: 33422-142, 17m
  plowe-0: 3739-1077, 17m
  ublock-badware: 7536-139, 17m
  ublock-filters: 33893-537, 17m
  ublock-privacy: 428-5, 17m
  ublock-quick-fixes: 342-84, 17m
  ublock-unbreak: 2069-33, 17m
  urlhaus-1: 6426-1, 17m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 547 ms (selfie)
 maxAssetCacheWait: 302 ms
popupPanel:
 blocked: 18
 network:
  investing.com: 2
  ad-score.com: 4
  adnxs.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 1
  facebook.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  outbrain.com: 2
  pbxai.com: 1
  scorecardresearch.com: 1
 extended:
  ##.dfpAdUnitContainer
  ###hpAdVideo
  ##.OUTBRAIN
  ##.rightColumnAd
  ###Side_Block_Facebook
  ##.socialContainer
  ###sideNotificationZone
  ###ad1
  ###ad2
  ###ad3
  ###findABroker
  ##.generalOverlay
  ##.midHeader
  ##.sponsoredArticle
  ##.promo-strip-wrapper
  ##body:style(overflow: auto !important)
  ##+js(remove-class, has-ads-free-promo-header, body)
  ##+js(set-constant, window.google_ad_status, 1)
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by okiehsch** [comment] 2023-07-10 13:53
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18917#issuecomment-1628571176

>   I verified that this issue is not a duplicate,

Really?

**Closed as completed by okiehsch** 2023-07-10 13:53 UTC
Labels: duplicate

**Comment by hauhui** [comment] 2023-07-10 14:26
no, it's fixed last time, but today it happed again, and I tried as instruction you provided last time and falied.
















At 2023-07-10 21:53:45, "okiehsch" ***@***.***> wrote:

Duplicate of #18917 (comment)

I verified that this issue is not a duplicate,

Really?

**Comment by stephenhawk8054** [comment] 2023-07-10 14:50
@hauhui You can continue commenting on close issues. All collaborators are notified with new comments, no need to open new duplicated issue.

**Comment by hauhui** [comment] 2023-07-10 14:50
got,thank you.
















在 2023-07-10 22:50:11，"stephenhawk8054" ***@***.***> 写道：

@hauhui You can continue commenting on close issues. All collaborators are notified with new comments, no need to open new duplicated issue.

**Comment by okiehsch** [comment] 2023-07-10 15:03
> it's closed 3/7, ok?

I was refering to https://github.com/uBlockOrigin/uAssets/issues/18917 not https://github.com/uBlockOrigin/uAssets/issues/18791.

Anyway I did not realize you already mentione an issue about the site earlier, if I had I had simply closed it as a duplicate without any remark.
