### ISSUE TITLE
uBO issue when attempting to install a script on GreasyFork

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#567] opened 2017-07-22 16:48 UTC
uBO 1.13.8 / Firefox ESR 52.2.1 (64-bit) / Windows 7 (64-bit)

Tested on several script installs at GreasyFork.
Example : https://greasyfork.org/en/scripts/6850-flickr-all-images-size
Clicking on _Install this script_, then either _Cancel_ either _proceed_, leads to uBO apparently frozen, as if I had added greasyfork.org to uBO's whitelist, but I haven't!

Landing on https://greasyfork.org/en/scripts/6850-flickr-all-images-size:

![greenshot-2017-07-22-175543](https://user-images.githubusercontent.com/16312589/28492983-feed459a-6f0d-11e7-914b-63596a2147da.jpg)

After having clicked on Install this script, then Cancel:

![greenshot-2017-07-22-175709](https://user-images.githubusercontent.com/16312589/28492986-1eed61ea-6f0e-11e7-86df-f4e90f8f3a4f.jpg)

I've tried to find a culprit on my side but unsuccessfully. never encountered this before.

**Comment by gorhill** [comment] 2017-07-22 17:27
uBO is not "frozen".

uBO is receiving a "close window" event from [nsIWindowMediator](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWindowMediator), thus it removes all of the internal data structures related to the tabs the window contains. With a simple refresh of a tab, uBO will recreate the internal data structure for that tab.

The issue is receiving a "close window" event from Firefox API despite the window not being closed.

**Comment by zymase** [comment] 2017-07-22 17:41
Not frozen indeed, only a naive description to express more a feeling than a fact.
Not frozen since clicking on the uBO enable/disable for this site button works and works so well that this is what I had done first, whitelisting de facto greasyfork.org when I believed to unwhitelist it after the first surprise. I then mentioned the issue here, realized afterwards greasyfork.org was whitelisted, and removed my thread ... being realizing what had happened.

Good to know a simple page reload fixes it. I should have figured that out. Surprise remains, never encountered before. Maybe uBO 1.13.8 specific? Otherwise Greasyfork will have modified something ...

**Comment by gorhill** [comment] 2017-07-22 17:46
I suspect the event is fired as a result of closing the modal dialog, which is probably a child of the window internally. I need to find out if uBO can, from the event, distinguish that the actual window is not really being closed.

**Comment by zymase** [comment] 2017-07-22 17:56
OK. i've changed the title accordingly, even if issue is perhaps a too strong word. Please corrct as you feel it, gorhill.

This is neither the place nor the moment but thanks again for this amazing uBlockorigin, for its quality far above all others, for your work, time, commitment.

**Closed** 2017-07-22 21:07 UTC
