### ISSUE TITLE
fourtoutici.info

### ISSUE THREAD

**Issue by smed79** [uBlockOrigin/uAssets#4952] opened 2019-02-19 21:08 UTC
anti adb
```
fourtoutici.*##+js(abort-on-property-read.js, adblockDetected)
```

http:\/\/www\.fourtoutici\.info/
http:\/\/www\.fourtoutici\.pro/

**Comment by okiehsch** [comment] 2019-02-19 22:53
I can't reproduce, 
````
  | /**
  | * Callback executed if adblock is installed
  | **/
  | function adblockDetected(){
  | alert("Bonjour, désolé de vous déranger avec cette fenêtre.\nMais nous avons détecté un bloqueur de publicité.\nJe ne pense pas que les publicités sur notre site soit intrusives (contrairement a cette fenêtre...).\nAuriez-vous la gentillesse de désactiver votre bloqueur?\nMerci d’avance");

  | * Verify adblock
  | **/
  | if(typeof blockAdBlock === "undefined"){
  | adblockDetected();
  | }else{
  |  
  | blockAdBlock.onDetected(adblockDetected);
  |  
  | blockAdBlock.onNotDetected(adblockDisabled);
````
is already fixed by 
![image](https://user-images.githubusercontent.com/16838044/53053359-69262f80-34a1-11e9-8c05-c7ac575db9b1.png)
on my end.

Does this not work for you?

**Closed** 2019-02-20 07:56 UTC
