### ISSUE TITLE
e.mail.ru: [unknown]

### ISSUE THREAD

**Issue by eprstreget** [uBlockOrigin/uAssets#14336] opened 2022-08-10 03:47 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

[`https://e.mail.ru/newsletters/`](https://e.mail.ru/inbox/)

### Category

[unknown]

### Describe the issue

right margin is not blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![2022-08-10_08-45-26](https://user-images.githubusercontent.com/110957631/183808584-5bfc87c2-53bc-474d-a78f-4f4ef5337e4f.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 98302
  cosmetic: 67250
  scriptlet: 17574
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 30-3, never
    ublock-filters: 33094-36, 1d.23h.39m
    ublock-badware: 4175-1, 1d.23h.38m
    ublock-privacy: 242-0, 10d.23h.12m
    ublock-abuse: 76-0, 10d.23h.11m
    ublock-unbreak: 1867-0, 1d.23h.37m
    easylist: 69296-594, 1d.23h.36m
    easyprivacy: 27300-693, 1d.23h.35m
    plowe-0: 3639-3, 10d.23h.9m
    RUS-0: 40352-44, 1d.23h.34m
    urlhaus-1: 4968-0, 20h.7m
    ublock-quick-fixes: 355-1, 20h.6m
filterset (user): [array of 30 redacted]
trustedset: 
  added: [array of 29 redacted]
  removed: 
    about-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 274 ms (selfie)
  maxAssetCacheWait: 93 ms
popupPanel: 
  blocked: 59
  blockedDetails: 
    mail.ru: 59
```
</details>

**Comment by MasterKia** [comment] 2022-08-10 04:35
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Please read and follow the Prerequisites carefully.

https://user-images.githubusercontent.com/17685483/183816559-04260e6b-491d-42ac-a989-091b8fd19bd1.png

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14332

> - [X] I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Do it again.

**Closed by MasterKia** 2022-08-10 04:35 UTC
