### ISSUE TITLE
bild.de cosmetic issue

### ISSUE THREAD

**Issue by manuallypure** [uBlockOrigin/uAssets#9615] opened 2021-07-23 14:52 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bild.de`

### Describe the issue

Since a week or so there are these gaps on bild.de which dont appear with deactivated ublock filters:

https://i.imgur.com/wD4suNQ.png

### Screenshot(s)

https://i.imgur.com/wD4suNQ.png

### uBlock Origin version

uBlock Origin v1.36.2

### Browser name and version

Firefox 90.0.2

### Settings

no changes

**Comment by okiehsch** [comment] 2021-07-23 15:11
I can reproduce, it's caused by 
````
bild.de##+js(abort-on-property-read, SmartAdServerASMI)
````

Example link: 
`https://www.bild.de/politik/inland/politik-inland/corona-spanien-wieder-hochinzidenzgebiet-aber-mallorca-urlaub-ist-sicher-77167122.bild.html`

That filter disables the anti adblock wall, we can't remove it.

**Comment by uBlock-user** [comment] 2021-07-23 15:25
@okiehsch Chrome ? I don't see it on Firefox.

**Comment by okiehsch** [comment] 2021-07-23 15:27
You mean the "gaps" the OP mentioned?

**Comment by manuallypure** [comment] 2021-07-23 15:40
the issue started after the Akamai error from yesrerday. is there a way to fix this somehow?

**Comment by okiehsch** [comment] 2021-07-23 15:50
Not without trigggering the anti adblock wall as far as I can see.

**Comment by uBlock-user** [comment] 2021-07-24 15:12
@okiehsch `bild.de##+js(set, SmartAdServerASMI, null)` works ?

**Comment by okiehsch** [comment] 2021-07-24 15:14
The gaps are still there.

**Comment by okiehsch** [comment] 2021-07-24 15:15
By the way, the site is not broken it's a minor cosmetic issue.

**Comment by uBlock-user** [comment] 2021-07-24 15:19
Site doesn't fully load with that filter, you're just seeing because thats the only visual breakage, but breakage is there.

**Comment by uBlock-user** [comment] 2021-07-24 15:23
`bild.de##+js(set, SmartAdServerASMI, [])` works ?

**Comment by okiehsch** [comment] 2021-07-24 15:23
I don't see a difference, what's not loading.

**Comment by okiehsch** [comment] 2021-07-24 15:24
> `bild.de##+js(set, SmartAdServerASMI, [])` works ?

You get the anti adblock message after  seconds

**Comment by uBlock-user** [comment] 2021-07-24 15:24
I meant page is not successfully loading with the current filter, but if there's no alternative we can close this as `wontfix`

**Comment by okiehsch** [comment] 2021-07-24 15:26
We can leave it open for now, maybe someone can come up with a working fix.

**Comment by avotoko** [comment] 2021-07-25 03:37
Seems to work.
```
bild.de##.main-nav .utilities > li:style(margin-left:-0.5px !important)
```

**Closed** 2021-07-25 06:52 UTC
Labels: help wanted
