### ISSUE TITLE
reddit.com tracking

### ISSUE THREAD

**Issue by Zirientis** [uBlockOrigin/uAssets#2125] opened 2018-04-29 08:05 UTC
### URL(s) where the issue occurs
`https://www.reddit.com`
`https://old.reddit.com`
Note: Reddit seems to be trialing a new design. Some users will get the 'New Reddit', which does not have the problem. In that case, clicking on the link to go to the 'Old Reddit' will bring you to the site with the problem.

### Describe the issue

When clicking on links on Reddit, the `href` is rewritten by a tracking script.
Outbound link example: `https://out.reddit.com/t3_8fo8fw?url=https%3A%2F%2Fimgur.com%2FPAhCc5a&token=[TOKEN]&app_name=reddit.com`
Internal link example: `https://www.reddit.com/r/gifs/comments/8fn2i7/lava_wash/?utm_content=comments&utm_medium=best&utm_source=reddit&utm_name=frontpage`

### Versions

- Browser/version: Firefox 59.0.2 (64-bit)
- uBlock Origin version: 1.16.2

### Settings

- Tested on a fresh profile with only uBlock Origin installed with default settings/filterlists.

### Notes

On links to posts, the `<a>` tag has a `data-outbound-url` or `data-inbound-url` attribute containing the tracking URL, while the attribute `data-href-url` contains the unmangled destination. Deleting the `data-{outbound,inbound}-url` attribute stops the rewriting.

In addition, the "trending subreddits" bar at the top has the tracking URL baked in. In this case, we fix this by cutting out the query string.

This scriptlet fixes the problem:

Add `reddit.com##script:inject(reddit-links.js)` to `filters/privacy.txt` (does this work on subdomains?)

```javascript
reddit-links.js application/javascript
(function() {
	var links = document.getElementsByClassName('may-blank');
	for (var i = 0; i < links.length; i++) {
		var e = links.item(i);
		e.removeAttribute('data-inbound-url');
		e.removeAttribute('data-outbound-url');
	}
	try {
		var trends = document.getElementsByClassName('trending-subreddits-content').item(0).getElementsByTagName('a');
		for (var i = 0; i < trends.length; i++) {
			var sr = trends.item(i);
			var href = sr.getAttribute('href');
			if (href) {
				// remove the query string
				var pos = href.indexOf('?');
				if (pos >= 0) {
					sr.setAttribute('href', href.substring(0, pos));
				}
			}
		}	
	} catch(err) { }
})();
```

**Comment by gwarser** [comment] 2018-04-29 08:58
You should use specialized extenstion to deal with UTM links https://addons.mozilla.org/firefox/search/?q=utm&type=extension and disable tracking in reddit settings https://www.reddit.com/personalization

**Comment by gorhill** [comment] 2018-04-29 10:57
Duplicate of <https://github.com/gorhill/uBlock/issues/1485>.

**Closed by gorhill** 2018-04-29 10:57 UTC
