### ISSUE TITLE
[nsfw] pccdirect.site: ads

### ISSUE THREAD

**Issue by achuka889** [uBlockOrigin/uAssets#17947] opened 2023-05-05 09:28 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pccdirect.site/?srv_id=@9190b9427260b210e62a4d9002d703@&visitor_id=22c5351ffbf533e6239ff5c4a5f84db7&utm_source=NG&utm_campaign=nkmngd%7CtavAdsterra%7Cpop&utm_medium=14379457%7C548493`

### Category

ads

### Description

The page is an unwanted ad that pops up when browsing other sites it refuses to close or go away

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium Mobile: 110
filterset (summary): 
 network: 95636
 cosmetic: 30545
 scriptlet: 17589
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  adguard-mobile: 8726-32, 23m
  easylist: 66561-16892, 23m
  easyprivacy: 32235-52, 23m
  plowe-0: 3743-1017, 23m
  ublock-abuse: 70-0, 22m
  ublock-badware: 7105-126, 22m
  ublock-filters: 33626-350, 22m
  ublock-privacy: 394-74, 22m
  ublock-quick-fixes: 228-23, 22m
  ublock-unbreak: 2012-38, 22m
  urlhaus-1: 7828-2, 22m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 8893 ms
 maxAssetCacheWait: 106 ms
popupPanel: 
 blocked: 3
 network: 
  rtmark.net: 1
  simplewebanalysis.com: 1
  youtube.com: 1
```
</details>

**Comment by gorhill** [comment] 2023-05-05 12:33
> pops up when browsing other sites

What was the other site(s)? If we know from which site(s) the popup spawned, we can prevent these sites from opening the popup in the first place.

**Comment by achuka889** [comment] 2023-05-05 12:42
Waploaded.com, stagatv.com

Also they don't always pop up anytime you go to these sites

**Comment by gorhill** [comment] 2023-05-05 12:52
Where exactly on those sites? What were you doing that triggered the popups? You clicked a link? If so which one? Bottomline is we can't fix if we can't reproduce, and if we can't reproduce we will have to close the issue without further action.

**Comment by achuka889** [comment] 2023-05-05 12:55
Try to download a movie, as u navigate in the website it pops up

**Comment by stephenhawk8054** [comment] 2023-05-06 00:25
I have fixed `stagatv.com`, but cannot find how to reproduce on `waploaded.com`

**Comment by dportvine** [comment] 2023-05-06 05:27
@stephenhawk8054 
Maybe you will add `stagatvfiles.com##+js(aopr, window.open)`

<details>
<summary>Screen</summary>

![2023-05-06_082225](https://user-images.githubusercontent.com/111344219/236601974-a1615680-ec2a-45be-8b2a-3110959d6a80.png)
![2023-05-06_082210](https://user-images.githubusercontent.com/111344219/236601977-a5deaba2-acfd-4699-a3f7-c8da84b6edc9.png)
![2023-05-06_082257](https://user-images.githubusercontent.com/111344219/236601980-1315bb4e-a021-48e8-8a00-4712bb285ae3.png)
</details>

**Comment by stephenhawk8054** [comment] 2023-05-06 05:28
```adb
stagatvfiles.com##button[onclick^="window.open"]:remove-attr(onclick)
```

doesn't work on your side?

**Comment by dportvine** [comment] 2023-05-06 05:32
What i see [Gif](https://imgur.com/Ecehi1O)

**Comment by stephenhawk8054** [comment] 2023-05-06 05:39
I see. It behaves differently on firefox.

**Comment by stephenhawk8054** [comment] 2023-05-06 07:25
> It Doesnt Work For Me In Chrome Either

With new update?

**Comment by stephenhawk8054** [comment] 2023-05-06 08:14
> @stephenhawk8054 Isn't this that bug with `##body:remove-attr()` on Chromium? The `remove-attr` scriptlet should work fine.

Ah you're right, I forgot about that.

**Comment by ghajini** [comment] 2023-05-07 18:40
considered fixed

**Closed by ghajini** 2023-05-07 18:40 UTC
Labels: mobile

**Comment by huyszn** [comment] 2024-01-16 10:19
`https://ww1.stagatv.com/watch/the-last-thing-he-told-me-season-1-episode-1/`
`https://stagatvfiles.com/videos/file/6438edb95aa45/The-Last-Thing-He-Told-Me-S01E01-STAGATV-COM-mp4`

I get an ad in the middle of the page on `stagatv.com` after waiting a few seconds and it also appears on the `stagatvfiles.com` download link.
