### ISSUE TITLE
somniumspace.medium.com: nuisance

### ISSUE THREAD

**Issue by systox** [uBlockOrigin/uAssets#19314] opened 2023-08-09 19:15 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://somniumspace.medium.com/somnium-vr1-headset-development-update-%EF%B8%8Foptics-%EF%B8%8Fproduction-design-materials-fov-4dedf0b80101`

### Category

nuisance

### Description

Huge banner at bottom of page advertising membership to "Medium".

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1617" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/50300640/ad52bb10-a93d-43f7-8445-79843c9fa404">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 105100
 cosmetic: 136647
 scriptlet: 25307
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26552-29, now
  adguard-popup-overlays: 23292-39, now
  easylist-annoyances: 3887-122, 1h.3m
  easylist-newsletters: 6322-370, 1h.2m
  easylist-notifications: 2639-188, 1h.1m
  fanboy-cookiemonster: 63034-18769, 1h
  ublock-annoyances: 5359-179, 59m
 default:
  user-filters: 35-2, never
  easylist: 69777-46, now
  easyprivacy: 33265-172, now
  plowe-0: 3715-1069, now
  ublock-badware: 7675-146, now
  ublock-filters: 34187-262, now
  ublock-privacy: 446-7, 58m
  ublock-quick-fixes: 271-27, now
  ublock-unbreak: 2105-37, now
  urlhaus-1: 6108-0, now
filterset (user): [array of 35 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 497 ms (selfie)
 maxAssetCacheWait: 110 ms
popupPanel:
 blocked: 18
 network:
  medium.com: 3
  app.link: 3
  cloudflareinsights.com: 1
  doubleclick.net: 2
  googletagmanager.com: 1
  youtube.com: 8
 extended:
  ##html:style(overflow-y: visible!important;)
  ##.ytp-ad-progress-list
  ##.ytp-pause-overlay
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
```
</details>

**Comment by gorhill** [comment] 2023-08-09 21:09
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/18854>.

**Closed by gorhill** 2023-08-09 21:09 UTC
