### ISSUE TITLE
devuploads.com: detection

### ISSUE THREAD

**Issue by tabtomi8** [uBlockOrigin/uAssets#18038] opened 2023-05-11 14:48 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://devuploads.com/p2zpkjzkqhun`

### Category

detection

### Description

The website detects ad-blockers again. I know this is a duplicate. I also tried using only the built in filters, but it still doesn't work. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-05-11-16-31-31-54_4d38fce200f96aeac5e860e739312e76](https://github.com/uBlockOrigin/uAssets/assets/59199402/39e29da4-6225-41ba-865e-96d2582c119a)
![Screenshot_2023-05-11-16-46-28-27_4d38fce200f96aeac5e860e739312e76](https://github.com/uBlockOrigin/uAssets/assets/59199402/a1f73b12-2223-41ea-8f4e-af91b9dbd4e4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium Mobile: 112
filterset (summary): 
 network: 96196
 cosmetic: 30711
 scriptlet: 17552
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  HUN-0: 2176-80, 5m
  adguard-mobile: 8734-34, 5m
  easylist: 65548-16905, 5m
  easyprivacy: 32257-65, 5m
  plowe-0: 3742-1022, 5m
  ublock-abuse: 70-0, 5m
  ublock-badware: 7114-129, 5m
  ublock-filters: 33388-363, 33m
  ublock-privacy: 394-75, 5m
  ublock-quick-fixes: 248-12, 19m
  ublock-unbreak: 2017-42, 19m
  urlhaus-1: 7651-1, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 522 ms
 maxAssetCacheWait: 201 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by gorhill** [comment] 2023-05-11 14:54
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/17761>.

**Closed as completed by gorhill** 2023-05-11 14:54 UTC
Labels: duplicate, unable to reproduce

**Comment by gorhill** [comment] 2023-05-11 17:07
I have no issue downloading the resource. I click "generate link", then countdown, then "download now", apk resource downloaded. So, unable to reproduce.

**Comment by gorhill** [comment] 2023-05-11 21:53
> Chromium Mobile: 112

What exact browser is this? We don't explicitly support Chromium-based browsers for Android, we can't guarantee everything works as expected. Whoever can reproduce is welcome to provide a solution, I can't since I can't reproduce.

**Comment by tabtomi8** [comment] 2023-05-12 04:05
I used Kiwi Browser. I tried with Firefox as well, but it still detects it.

### Screenshot

<details>
<summary>Screenshot</summary>

![Screenshot_2023-05-12-05-59-13-27_984e1414ae90666a90f12ff17ec14a7f.jpg](https://github.com/uBlockOrigin/uAssets/assets/59199402/132ff17f-7644-40b5-8152-c1a3a5c468d0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 115
filterset (summary): 
 network: 15085
 cosmetic: 10264
 scriptlet: 17446
 html: 945
listset (total-discarded, last-updated): 
 removed: 
  adguard-mobile: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
  HUN-0: null
 default: 
  user-filters: 0-0, never
  ublock-filters: 34216-306, 2m
  ublock-badware: 7118-0, 2m
  ublock-privacy: 444-1, 2m
  ublock-abuse: 70-70, 2m
  ublock-unbreak: 2028-2, 2m
  ublock-quick-fixes: 252-0, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2183 ms
 maxAssetCacheWait: 408 ms
popupPanel: 
 blocked: 4
 network: 
  doubleclick.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
 cosmetic: 
  ###abgb
  ##.GoogleActiveViewElement:not(:has(> #reward_close_button_widget))
  ##.GoogleActiveViewElement > div:not(#reward_close_button_widget)
  ###abgb
  ##.GoogleActiveViewElement:not(:has(> #reward_close_button_widget))
```
</details>

**Comment by tabtomi8** [comment] 2023-05-12 12:42
> @tabtomi8 Test These
> ```
> @@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=thecubexguide.com|djxmaza.in
> @@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl$script,domain=thecubexguide.com|djxmaza.in
> @@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=thecubexguide.com|djxmaza.in
> *$frame,domain=djxmaza.in|thecubexguide.com,redirect=noopframe
> djxmaza.in,thecubexguide.com#@#iframe
> *$subdocument,redirect-rule=noopframe,domain=djxmaza.in|thecubexguide.com
> *$xmlhttprequest,redirect-rule=nooptext,domain=djxmaza.in|thecubexguide.com
> @@||dev.miuiflash.com^$generichide
> @@||thecubexguide.com^$generichide
> @@||securepubads.g.doubleclick.net/tag/js/$domain=thecubexguide.com
> thecubexguide.com#@$#.download-page center > #featuredimage { visibility: hidden !important; height: 0 !important; }
> @@||djxmaza.in^$generichide
> *$subdocument,redirect-rule=noopframe,domain=financemonk.net|rtxkeeda.com|houseofblogger.com|dropgalaxy.com|djxmaza.in|thecubexguide.com
> *$xmlhttprequest,redirect-rule=nooptext,domain=financemonk.net|rtxkeeda.com|houseofblogger.com|dropgalaxy.com|djxmaza.in|thecubexguide.com
> *$script,redirect-rule=noopjs,domain=financemonk.net|rtxkeeda.com|houseofblogger.com|dropgalaxy.com|djxmaza.in|thecubexguide.com
> *$image,redirect-rule=32x32-transparent.png,domain=financemonk.net|rtxkeeda.com|houseofblogger.com|dropgalaxy.com|djxmaza.in|thecubexguide.com
> thecubexguide.com#@$##featuredimage { height: 0 !important; }
> @@*$domain=djxmaza.in|safeframe.googlesyndication.com|thecubexguide.com|dev.miuiflash.com
> thecubexguide.com###featuredimage:style(height: 10px !important)
> thecubexguide.com##iframe:style(height: 30px !important)
> ```

Thank you, it worked!

**Comment by tabtomi8** [comment] 2023-05-14 10:30
It worked for a day, now it doesn't. 

<details>
<summary>Screenshot</summary>

![Screenshot_2023-05-14-12-28-45-48_984e1414ae90666a90f12ff17ec14a7f.jpg](https://github.com/uBlockOrigin/uAssets/assets/59199402/de9260ba-38d3-4948-b0a8-f47a11fcf6aa)

</details>
