### ISSUE TITLE
Ads on isport.blesk.cz + other sites

### ISSUE THREAD

**Issue by r2308145** [uBlockOrigin/uAssets#824] opened 2017-11-10 13:47 UTC
Ads on these URLS:

https://isport.blesk.cz/
https://zive.cz
https://csfd.cz

Screenshots: https://imgur.com/a/E9LqV

Setup: FF stable + uBlock up to date

**Comment by mapx-** [comment] 2017-11-10 13:56
What's this ? Explain what's the issue, provide specific page, your setup, upload screenshots

**Comment by r2308145** [comment] 2017-11-10 14:21
@mapx sorry, accidentally sent it too early.. will edit

**Comment by mapx-** [comment] 2017-11-10 14:25
I'm not that mapx ... I'm https://github.com/mapx-  (see "-") :)

**Comment by okiehsch** [comment] 2017-11-11 00:16
`isport.blesk.cz` and `zive.cz` are fixed with
````
isport.blesk.cz,zive.cz##script:inject(addEventListener-defuser.js, DOMContentLoaded, cncAd.adlblock)
isport.blesk.cz##.ads-in
````
on my end.

I can't reproduce your `https://csfd.cz/` issue
![unbennnt](https://user-images.githubusercontent.com/16838044/32683601-c9558566-c67c-11e7-9ad5-13e1047fb9fc.JPG)
with default setup + `EasyList Czech and Slovak`.

**Comment by r2308145** [comment] 2017-11-11 09:44
thanks, seems like the filter is working.. it's weird but cant reproduce the csfd.cz issue neither now

**Comment by pepablock** [comment] 2017-11-11 12:21
the only issue with csfd.cz i have is that there is embedded ad in the trailers.

**Comment by r2308145** [comment] 2017-11-11 14:29
another ad appeared on isport.blesk.cz
![screenshot-2017-11-11 - isport cz](https://user-images.githubusercontent.com/33419338/32690317-11a0e130-c6f5-11e7-80b4-58e3e7192336.png)

**Comment by okiehsch** [comment] 2017-11-11 22:26
No new ads at `isport.blesk.cz` on my end.
![unbnnt](https://user-images.githubusercontent.com/16838044/32694109-a4b0c1ce-c737-11e7-9f95-1b1744f2c828.JPG)

**Comment by okiehsch** [comment] 2017-11-12 00:13
@pepablock regarding the pre-roll ads,
`||video.csfd.cz/files/videos/*.webm$media,first-party,redirect=noopmp3-0.1s
works for me.

**Comment by pepablock** [comment] 2017-11-12 08:56
@okiehsch i still can see embedded ads in the trailers. screenshot from the ublock logger.
<img width="1502" alt="01" src="https://user-images.githubusercontent.com/29940017/32697386-afeed41a-c78f-11e7-9e0a-49a28d6750e4.png">

**Comment by okiehsch** [comment] 2017-11-12 18:20
No embedded ads for me.
If you open your logger, filter for `video.csfd.cz/files/videos` and then load a trailer at `csfd.cz`,
what does it say?

I get
![nannt](https://user-images.githubusercontent.com/16838044/32701906-2c2e5d04-c7de-11e7-918a-2d10bf76e70f.PNG)

The `.webm`-request is the ad which is redirected and the trailer starts playing immediately.

**Comment by pepablock** [comment] 2017-11-12 18:41
when i do that the bottom .mp4 is the ad and the second .mp4 is the trailer itself.
<img width="1502" alt="001" src="https://user-images.githubusercontent.com/29940017/32702077-5400f7d0-c7e1-11e7-8559-b8880d8c72c7.png">

**Comment by pepablock** [comment] 2017-11-12 19:07
so i guess the only possible way for me to block the pre-roll ads is via a static filter?

im also seeing ads on some pages for eg. `https://www.csfd.cz/film/555022-prohlidka-filmovych-studii-warner-bros-studios/555025-archiv-rekvizity/videa/?type=4&video=157734008#highlight-video-157734008`

![0001](https://user-images.githubusercontent.com/29940017/32702282-19d1be1a-c7e5-11e7-8b20-5642cff723f7.jpg)
<img width="1680" alt="0002" src="https://user-images.githubusercontent.com/29940017/32702283-19eaaa56-c7e5-11e7-9648-1d8b5eb07170.png">

**Comment by okiehsch** [comment] 2017-11-12 19:18
- You can try to redirect the .mp4 ad, simply blocking it will probably result in breaking the video player, but you can try.
- `https://www.csfd.cz/film/555022-prohlidka-filmovych-studii-warner-bros-studios/555025-archiv-rekvizity/videa/?type=4&video=157734008#highlight-video-157734008`
on my end.
![unbennt](https://user-images.githubusercontent.com/16838044/32702369-8627cb8a-c7e6-11e7-88e9-119e6dd61994.JPG)

**Comment by okiehsch** [comment] 2017-11-12 19:45
@pepablock after reloading a few times I could reproduce some ads at 
`https://www.csfd.cz/film/555022-prohlidka-filmovych-studii-warner-bros-studios/555025-archiv-rekvizity/videa/?type=4&video=157734008#highlight-video-157734008`.
````
csfd.cz##.ad-pmg-leaderboard.ad-pmg
csfd.cz##.ad-pmg-square.ad-pmg
````

**Comment by pepablock** [comment] 2017-11-12 20:42
@okiehsch That would fix the top and the one on the right side. I figured out the one on the bottom is

`csfd.cz##.ad-pmg-rectangle.ad-pmg`

but there is one ad wrapped around the trailer, if I add this it will block it, but also block the video, any work around? `csfd.cz##.ad-pmg-videoplayer-branding.ad-pmg`

**Comment by okiehsch** [comment] 2017-11-12 21:23
Nothing obvious, maybe somebody else can come up with a working filter.

**Comment by pepablock** [comment] 2017-11-13 13:55
I tried `csfd.cz` for a couple times today to see if there are any ads left (since it seems they appear rather random), and I could get one more ad on the right side, it's pretty much the same as above, but instead of `.jpg` it's `.png`. I modified the filter above to:
`||img.csfd.cz/files/images/film/posters/000/006/*/*_*.jpg||png$image`
or
`||img.csfd.cz/files/images/film/posters/000/006/*/*_*.*$image`
Is one prefered over the other?
![001](https://user-images.githubusercontent.com/29940017/32728957-8744bffe-c882-11e7-916a-2de67ecd671b.jpg)

**Comment by gorhill** [comment] 2017-11-13 14:20
All these ads share `.ad-pmg`, so...

    csfd.cz##.ad-pmg

?

**Comment by pepablock** [comment] 2017-11-13 14:35
Oh, that works too, I will report it to the cz/sk filters. Thank you.

**Comment by r2308145** [comment] 2017-11-14 08:04
found new ad on seznam.cz
![screenshot-2017-11-14 seznam - najdu tam co neznam](https://user-images.githubusercontent.com/33419338/32769062-a3434c82-c91a-11e7-8c9f-49a6e95704f6.png)

**Comment by r2308145** [comment] 2017-11-15 17:01
this is getting really ugly (zive.cz)

![screenshot-2017-11-15 diskuze novy firefox quantum slibuje dabelskou rychlost a malou spotrebu ram](https://user-images.githubusercontent.com/33419338/32849294-0563f1c2-ca2f-11e7-8ace-a0f4e921092f.png)

**Comment by gorhill** [comment] 2017-11-15 17:04
Why not report to maintainers of "CZE, SVK: EasyList Czech and Slovak"?

**Comment by r2308145** [comment] 2017-11-15 18:17
I will do it, but the response here is usually faster

**Comment by okiehsch** [comment] 2017-11-18 04:17
Has been fixed in `EasyList Czech and Slovak`.

**Closed by okiehsch** 2017-11-18 04:17 UTC

**Comment by r2308145** [comment] 2017-11-22 08:53
it hasn't for me
