### ISSUE TITLE
sammobile.com: breakage

### ISSUE THREAD

**Issue by RozvM** [uBlockOrigin/uAssets#11077] opened 2021-12-26 13:02 UTC
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.sammobile.com/firmwares/`

### Category

breakage

### Describe the issue

The suggestion/autocomplete list does not work for firmware browsing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock Origin is enabled:
![image](https://user-images.githubusercontent.com/74600479/147408830-f78be1c1-f7b0-47da-b4c9-0a51fa41f322.png)
![image](https://user-images.githubusercontent.com/74600479/147408845-8bcd405a-b362-407f-8a19-a01c05576f11.png)

uBlock Origin is disabled:
![image](https://user-images.githubusercontent.com/74600479/147408863-7f7e730d-007a-48eb-a2b9-71f83ffff985.png)
![image](https://user-images.githubusercontent.com/74600479/147408802-55189b32-6aac-4f25-b775-c050b4b07c7e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78881
  cosmetic: 41680
  scriptlet: 16239
  html: 610
listset (total-discarded, last updated): 
  added: 
    HUN-0: 2137-18, 17h.2m
  default: 
    ublock-filters: 30343-31, 3d.16h.28m
    ublock-badware: 3564-1, 3d.16h.30m
    ublock-privacy: 179-0, 3d.16h.37m
    ublock-abuse: 81-0, 3d.16h.34m
    ublock-unbreak: 1689-0, 3d.16h.32m
    easylist: 62254-571, 17h.3m
    easyprivacy: 26549-502, 17h.4m
    urlhaus-1: 8168-0, 17h.1m
    plowe-0: 3717-3, 3d.19h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 183 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  colorBlindFriendly: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 655 ms (selfie)
popupPanel: 
  blocked: 6
```
</details>

**Comment by gorhill** [comment] 2021-12-26 13:09
Caused by EasyPrivacy's `/newrelic.js`, this fixes the issue:

    @@||sammobile.com^*/newrelic.js$script,1p

**Comment by gorhill** [comment] 2021-12-26 13:13
Alternatively, can be fixed with uBO's syntax:

    ||sammobile.com^*/newrelic.js$script,1p,redirect-rule=noop.js

The blocked script is not really needed, just redirecting to a local empty JS resource also works.

**Comment by RozvM** [comment] 2021-12-26 13:16
Thanks for the fix!

This also seems to solve the problem with the comment section and embedded Trivia content not loading on the site.

**Closed** 2021-12-26 21:46 UTC
Labels: to be fixed by EL / EP / FA

**Comment by RozvM** [comment] 2022-04-10 16:34
Sooo... It broke again but now it's the autocompletion list only.

**Comment by mapx-** [comment] 2022-04-10 16:47
@ryanbr 
EP, needing
`@@||plausible.io/js/plausible.js$script,domain=sammobile.com`
