### ISSUE TITLE
thingiverse.com: breakage

### ISSUE THREAD

**Issue by torin-stephen** [uBlockOrigin/uAssets#11909] opened 2022-02-26 11:09 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thingiverse.com/`

### Category

breakage

### Describe the issue

thingiverse shows "Something went wrong." and nothing else when uBO is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/30649929/155840917-3da98a2c-e281-48f9-b35b-618f6ac200f0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79476
  cosmetic: 41227
  scriptlet: 16446
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.12h.40m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 30-1, never
    easylist: 63775-9, 2d.20h.58m
    easyprivacy: 26609-122, 2d.20h.59m
    plowe-0: 3672-804, 2d.21h.6m
    ublock-abuse: 77-0, 2d.21h.4m
    ublock-badware: 4019-83, 2d.21h.2m
    ublock-filters: 30278-152, 2d.21h.1m
    ublock-privacy: 199-2, 2d.21h
    ublock-unbreak: 1715-39, 2d.21h.5m
    urlhaus-1: 8141-1, 15h.13m
filterset (user): [array of 30 redacted]
trustedset: 
  added: [array of 48 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 973 ms (selfie)
  maxAssetCacheWait: 209 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    thingiverse.com: 1
    amazon-adsystem.com: 1
    googletagmanager.com: 2
    uptime.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-02-26 11:11
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11877

**Closed by okiehsch** 2022-02-26 11:11 UTC
