### ISSUE TITLE
1337x.to: ads

### ISSUE THREAD

**Issue by ronboy1** [uBlockOrigin/uAssets#11986] opened 2022-03-01 15:35 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://1337x.to/`

### Category

ads

### Describe the issue

display ads have recently begun to appear near the top and bottom of many pages:
![image](https://user-images.githubusercontent.com/100703723/156198771-6bb31790-c8fa-4f79-a87c-5c525c64a96c.png)
![image](https://user-images.githubusercontent.com/100703723/156198824-bf02b57f-c885-46b7-9013-9dc4edbd74a9.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79751
  cosmetic: 41286
  scriptlet: 16497
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 63960-9, 2d.8h.14m
    easyprivacy: 26626-122, 2d.8h.13m
    plowe-0: 3672-804, 5d.14h.7m
    ublock-abuse: 77-0, 2d.8h.15m
    ublock-badware: 3863-83, 2d.8h.11m
    ublock-filters: 30348-157, 2d.8h.10m
    ublock-privacy: 202-2, 2d.8h.9m
    ublock-unbreak: 1718-39, 2d.8h.8m
    urlhaus-1: 8437-0, 14h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4642 ms (selfie)
  maxAssetCacheWait: 279 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by uBlock-user** [comment] 2022-03-01 15:42
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11963

**Comment by mapx-** [comment] 2022-03-01 15:43
update the filter lists, already fixed

**Closed by uBlock-user** 2022-03-01 15:42 UTC

**Comment by ronboy1** [comment] 2022-06-11 15:03
The ads are back on 1337x.

**Comment by ghajini** [comment] 2022-06-11 18:57
force update your filter lists
