### ISSUE TITLE
Google developer pages (Android, Google, etc) fail to load fonts

### ISSUE THREAD

**Issue by mastacheata** [uBlockOrigin/uAssets#7121] opened 2020-03-19 19:20 UTC
### Description

All developer docs of Google products including Android, Firebase and the Google platform itself fail to load some fonts and therefore display very strangely formatted headlines and navigation items due to bad/no fallback fonts.

### A specific URL where the issue occurs
```
https://developer.android.com/guide/platform
https://firebase.google.com/docs
```

### Steps to Reproduce

1. Open any of the Google Developer websites (i.e. developer.android.com)
2. Dig into the actual documentation / reference subsites (i.e. click Platform)
3. See that the layout is broken
4. Notice warnings about supposedly blocked CORS-Requests for fetching webfonts associated with the site
5. Greenlight everything (either globally or for that site) and reload
6. See that the problem persists even after you enabled all the different resource domains
7. Disable blocking (blue power button in uBO) and reload
8. See that the problem persists
9. Disable addon in Firefox Addons and reload
10. The site looks as expected
11. Reenable uBO (obviously clearing all settings you might've changed for trial and error)
12. See that the page works just fine again (This is the strangest part)

### Expected behavior:

![image](https://user-images.githubusercontent.com/716261/77105099-5fad2500-6a1d-11ea-81e1-7def6c1b975f.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/716261/77105021-41472980-6a1d-11ea-8cc7-4f39be049274.png)

### Your environment

* uBlock Origin version: v1.25.2
* Browser Name and version: Firefox 74.0
* Operating System and version: Linux 5.4.24-1-lts / ArchLinux (Rolling Release distribution without any version numbers)
Problem exists on Windows 10 with Firefox Developer Edition as well and shows very similar/same problems

**Comment by mapx-** [comment] 2020-03-20 09:16
open the logger, refresh one of the pages in trouble (and give us the exact link), select only the blocked items and post them here

**Comment by mapx-** [comment] 2020-03-21 10:03
no feedback, closing

**Closed by mapx-** 2020-03-21 10:03 UTC
Labels: unable to reproduce

**Comment by mastacheata** [comment] 2020-03-21 15:06
Wow, you really have high standards for those opening an issue. Expecting a response in < 24hrs is hefty. :(

As mentioned in the original issue: There is nothing being blocked. It seems to be a general incompatibility between the uBlockOrigin extension and the Google Developer websites (all of them - see attached screenshots)
The logs are void of anything being blocked, especially when I disable the blocking for the website in question using the blue power button in the extension button popout-menu

I explicitly mentioned two non-functioning URLs in the original issue. These are direct links to non-functioning pages, despite only being the overview page of each section. The steps outlined in the issue are only for reproducing it like any normal human would probably. (You could also see the broken pages by going there from a Search engine, StackOverflow, GitHub or other Link).

This is a very strange issue because it only happens if a) you haven't successfully loaded the fonts before and b) the uBlockOrigin extension is enabled.
If you had the fonts loaded before, it will keep working despite the extension being enabled.

i.e. the following scenario causes the fonts to load properly ever after:
1. Load one of the pages mentioned in the links inside the original issue. (yes you can click the link and it will take you to a problematic page directly, but affects *ALL* Google developer pages using the same documentation layout framework.
1a. Notice the fonts don't load (i.e.: Buttons with text out of place, headlines written top-to-bottom instead of left-to-right, etc)
1b. Try to force reload without cache or clear cache and reload => No change, website still broken.
1c. Disable blocking for this page / power button goes grey, then repeat step 1b => No change, still broken
2. Disable uBlock Origin
3. normally refresh page again => Page still broken
3a. clear cache or reload skipping cache => Page works as expected, Fonts load, no CORS errors in console
4. Reenable uBlock Original (reenable blocking / power button goes blue for that site)
4a. Refresh page normally => everything still fine
4b. Reload page skipping cache or clear cache and reload => everything is still fine

After the fonts were loaded once, the only way to force things to break again is switching to a different browser profile. Which leads me to the conclusion that this is not a filter problem, but a problem with the uBlock Origin Extension itself and the filtering mechanism conflicting with the font loading at Google.

**Comment by mapx-** [comment] 2020-03-21 15:38
The problem is we cannot reproduce the issue or maybe we need some exact steps to get the same behaviour.

**Comment by mapx-** [comment] 2020-03-21 15:41
Did you disable any other addon in FF ?
