### ISSUE TITLE
10play.com.au: ads / breakages / detection

### ISSUE THREAD

**Issue by tamasys** [uBlockOrigin/uAssets#22964] opened 2024-03-18 11:31 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://10play.com.au/ambulance-australia`

### Category

detection

### Description

Error when playing video:
`Looks like you're using an ad blocker!
If you're experiencing playback issues, it may be because you have an ad blocker enabled. Try disabling this and see if that resolves the problem. If not, let us know!`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1253" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/2321397/c22ba5f3-b200-4a18-939d-3b5cbac0564e">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 124957
 cosmetic: 45636
 scriptlet: 20311
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  easylist: 82692-16, 2m
  easyprivacy: 50383-8, 4m
  plowe-0: 3765-1183, 2m
  ublock-badware: 7848-147, 2m Δ
  ublock-filters: 37441-356, 2m
  ublock-privacy: 763-6, 2m Δ
  ublock-quick-fixes: 210-34, 2m
  ublock-unbreak: 2252-33, 2m
  urlhaus-1: 7485-5, 4m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2471 ms (selfie)
 maxAssetCacheWait: 1299 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 23
 network:
  10play.com.au: 1
  adsrvr.org: 1
  appboycdn.com: 1
  bing.com: 1
  branch.io: 1
  doubleclick.net: 2
  facebook.net: 1
  googletagmanager.com: 3
  imrworldwide.com: 2
  moatads.com: 2
  tealiumiq.com: 2
  tiktok.com: 1
  tiqcdn.com: 1
  trackjs.com: 2
  tremorhub.com: 1
  yimg.com: 1
 extended:
  ###adSkinLeft
  ###adSkinRight
  ##.content__ad__content
  ###mpu_top
  ###adhesion
  ##.mrec
  ##+js(m3u-prune, /^https?:\/\/redirector\.googlevideo\.com.*/, /…
  ##+js(json-prune, cuepoints, cuepoints.[].start cuepoints.[].end…
  ##+js(set-constant, moatPrebidApi, {})
  ##+js(set-constant, moatPrebidApi.getMoatTargetingForPage, noopF…
```
</details>

**Comment by stephenhawk8054** [comment] 2024-03-19 02:50
I can't reproduce
![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/0e0c9e4b-9f49-4ee0-910c-38bec20084c6)

**Comment by mapx-** [comment] 2024-03-19 08:34
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by stephenhawk8054** [comment] 2024-09-08 10:35
https://github.com/uBlockOrigin/uAssets/issues/25253

**Comment by stephenhawk8054** [comment] 2024-09-08 10:36
@ThreeeDots Can you go to `chrome://extensions` page (type in URL bar) and screenshot it here?

**Comment by mapx-** [comment] 2024-09-08 11:38
> Issue persists regardless of if uBlock is switched on or not (I.e., I pause it on the site and the site still says "adblocker detected")

this means it's something else in your system blocking the site.

**Comment by Sidewindr** [comment] 2024-09-11 07:50
#25290 is not a duplicate of this issue, this show plays fine .. the Amazing Race Australia however does not ..

**Comment by stephenhawk8054** [comment] 2024-09-11 07:51
JUST CONTINUE IN THIS THREAD

**Comment by mapx-** [comment] 2024-09-11 07:54
@Sidewindr 

even disabling uBO, I get this error:

Error - Video not found
An unexpected error has occurred

**Comment by stephenhawk8054** [comment] 2024-09-11 07:54
Even when I don't use any extensions, I see this:

![image](https://github.com/user-attachments/assets/4c3f6c89-a8c0-4f3c-b477-170eec4aa460)

**Comment by Sidewindr** [comment] 2024-09-11 08:08
I am watching it now with uBO disabled.

**Comment by Sidewindr** [comment] 2024-09-11 08:10
Also ambulance australia works fine with uBO enabled.

**Comment by stephenhawk8054** [comment] 2024-09-11 08:12
Then you'll need to wait for any volunteers who can reproduce it

**Comment by Sidewindr** [comment] 2024-09-11 08:16
Same issue in Firefox with uBo enabled only for The Amazing Race Australia.

https://10play.com.au/the-amazing-race-australia

**Comment by Sidewindr** [comment] 2024-09-18 08:44
Any development on this?  The issue still remains.

**Comment by Sidewindr** [comment] 2024-09-18 08:44
> @Sidewindr
> 
> even disabling uBO, I get this error:
> 
> Error - Video not found An unexpected error has occurred

When this happens you just need to SHIFT-Reload/F5

**Comment by stephenhawk8054** [comment] 2024-09-18 08:51
Still same error for me after Shift + F5

![image](https://github.com/user-attachments/assets/b98e525b-5573-466b-8972-61e20e5627cc)

There's nothing we can do if the video can't play for us. You have to wait for any other volunteers who can reproduce the issue.

**Comment by Sidewindr** [comment] 2024-09-19 01:13
> Still same error for me after Shift + F5
> 
> There's nothing we can do if the video can't play on our sides. You have to wait for any other volunteers who can reproduce the issue.

That's so bizzare .. it works for me in Chrome, Firefox and Edge all with uBo disabled both at work and at home on different machines and with different providers.

**Comment by mapx-** [comment] 2024-09-19 17:06
@Sidewindr 

test

```
@@||pubads.g.doubleclick.net/ondemand/dash/content/*/streams$xhr,domain=10play.com.au
10play.com.au##+js(xml-prune, Period[id*="-roll-"][id*="-ad-"], , pubads.g.doubleclick.net/ondemand)
```

**Comment by Sidewindr** [comment] 2024-09-19 20:59
> @Sidewindr
> 
> test
> 
> ```
> @@||pubads.g.doubleclick.net/ondemand/dash/content/*/streams$xhr,domain=10play.com.au
> 10play.com.au##+js(xml-prune, Period[id*="-roll-"][id*="-ad-"], , pubads.g.doubleclick.net/ondemand)
> ```

That works! 👍

**Closed** 2024-09-20 01:49 UTC
Labels: unable to reproduce, geo specific, account required
