### ISSUE TITLE
newyorker.com detects private browsing

### ISSUE THREAD

**Issue by numbermaniac** [uBlockOrigin/uAssets#7058] opened 2020-03-05 01:49 UTC
### URL(s) where the issue occurs

`https://www.newyorker.com/humor/borowitz-report/tulsi-gabbards-nine-supporters-urge-her-to-drop-out-of-race`

### Describe the issue

The New Yorker detects private browsing mode, and presents you with a popup that blocks visibility. The page is still scrollable, however much of the article's content is suppressed.

### Screenshot(s)

![NewYorker](https://user-images.githubusercontent.com/5206120/75939706-13bb9580-5edf-11ea-90a1-b7c6bebe8769.png)

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.25.0

### Settings

- None

### Notes

```
www.newyorker.com##.incognito-barrier
www.newyorker.com##.paywall-modal--show.paywall-modal > .paywall-modal__overlay
```

Using the "block element" feature, this appears to make the article viewable again. However, only the first paragraph is readable - if you view the webpage in normal browsing mode (not incognito), the full article is visible.

**Comment by llacb47** [comment] 2020-03-05 01:56
```
newyorker.com##+js(set, navigator.storage.estimate, undefined)
newyorker.com##+js(set, webkitRequestFileSystem, noopFunc)
```

First filter for Chromium, second filter for Firefox

**Comment by okiehsch** [comment] 2020-03-05 01:56
> if you view the webpage in normal browsing mode (not incognito), the full article is visible.

Not on my end. I get  
![image](https://user-images.githubusercontent.com/16838044/75940288-e80fbf80-5e8c-11ea-92f7-d57b33809dbf.png)

**Comment by llacb47** [comment] 2020-03-05 01:58
Click the arrow to minimize

**Comment by okiehsch** [comment] 2020-03-05 01:59
???

![image](https://user-images.githubusercontent.com/16838044/75940428-50f73780-5e8d-11ea-9b7d-2e0c4ef4de5b.png)

**Comment by okiehsch** [comment] 2020-03-05 01:59
Do ou see the whole article?

**Comment by llacb47** [comment] 2020-03-05 02:02
That is the whole article, it's short :) , here's another to test `https://www.newyorker.com/news/our-columnists/super-tuesday-was-mainly-about-donald-trump-not-joe-biden`

**Comment by llacb47** [comment] 2020-03-05 02:03
typo in commit https://github.com/uBlockOrigin/uAssets/commit/b0aff9541b9ad6a8a4654cb5ea3183cd6b022438#diff-92ce64631591b876fb9571e6e19a534aR3526

**Comment by okiehsch** [comment] 2020-03-05 02:07
> That is the whole article :)

Well that could have fooled me. ;)

**Comment by okiehsch** [comment] 2020-03-05 02:08
@numbermaniac it has been fixed in `uBO-annoyances`.

**Closed by okiehsch** 2020-03-05 02:08 UTC

**Comment by numbermaniac** [comment] 2020-03-05 02:14
Thank you! 😄

**Comment by Yuki2718** [comment] 2020-03-05 15:20
Applying the filter for Chromium causes a blank page here.
![newyorker](https://user-images.githubusercontent.com/58900598/75995576-fc60c480-5f3f-11ea-8f25-1e862935f580.png)
Brave 1.4.95 w/ uBO 1.24.4 default + uBlock Annoyances, Brave's blocker disabled (the "17" counter in the SS is about HTTPS upgrade, no blockage)

**Comment by Yuki2718** [comment] 2020-03-06 01:23
@llacb47 @mapx- @uBlock-user @okiehsch 
Is the above only me? If not, it's a kind of FP.

**Comment by okiehsch** [comment] 2020-03-06 01:33
![image](https://user-images.githubusercontent.com/16838044/76041402-481c6980-5f52-11ea-8553-6a5bd680729b.png)

I can't reproduce using Chromium/Chrome or Edge.
Have you tried any Chromium based browser besides Brave?
Maybe it's a Brave issue.

**Comment by Yuki2718** [comment] 2020-03-06 02:55
Reproduced on Chrome 80.0.3987.132 (only thing changed from default is enabling uBO in private window)
![newyorker](https://user-images.githubusercontent.com/58900598/76045616-0070fe80-5fa1-11ea-9481-ff709fa07b43.png)

It appears it only occurs if you go to homepage `https://www.newyorker.com/` and not if you directly go to individual news pages.

**Comment by okiehsch** [comment] 2020-03-06 03:05
> It appears it only occurs if you go to homepage

That I can reproduce.

**Comment by llacb47** [comment] 2020-03-06 03:09
Replace with `newyorker.com##+js(acis, navigator.storage.estimate)`

**Comment by okiehsch** [comment] 2020-03-06 03:12
I already have the working fix `newyorker.com##+js(aopr, cns)` which does basically the same thing your filter does.
I was not sure if disabling that script will break site functionality.
Have you checked the site for breakage with that filter in place?

**Comment by Yuki2718** [comment] 2020-03-06 03:14
llacb47's filter seems to work w/out the blank screen, not sure for other functionality.

**Comment by okiehsch** [comment] 2020-03-06 03:20
I can't see any obvious breakage.
