### ISSUE TITLE
il.investing.com: ads

### ISSUE THREAD

**Issue by nissimlahav78** [uBlockOrigin/uAssets#18927] opened 2023-07-10 13:52 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://il.investing.com/indices/major-indices`

### Category

ads

### Description

The website shows ads, after updating all filters, the adds still showing up.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 31d.5h.38m
Chromium: 114
filterset (summary):
 network: 97530
 cosmetic: 40482
 scriptlet: 18021
 html: 0
listset (total-discarded, last-updated):
 added:
  ISR-0: 1737-0, now
 default:
  user-filters: 0-0, never
  easylist: 68143-11, now
  easyprivacy: 33422-66, now
  plowe-0: 3739-1074, now
  ublock-badware: 7536-139, now
  ublock-filters: 33893-145, now
  ublock-privacy: 428-4, now
  ublock-quick-fixes: 346-84, now
  ublock-unbreak: 2070-31, now
  urlhaus-1: 6426-1, now
filterset (user): [empty]
trustedset:
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3527 ms (selfie)
 maxAssetCacheWait: 564 ms
popupPanel:
 blocked: 9
 network:
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  primis.tech: 1
 extended:
  ##.midHeader
  ##div[class^="ad_"]
  ##div[data-test="ad-slot-visible"]
  ##[class*="overlay_overlay"]
  ###__next > .fixed
  ##body:style(overflow: auto !important)
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by okiehsch** [comment] 2023-07-10 13:56
We already have an open investing.com issue.
Opening issues for every regional substies is redundant.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/18917

**Closed by okiehsch** 2023-07-10 13:56 UTC
