### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by pipecortes23** [uBlockOrigin/uAssets#16092] opened 2022-12-22 12:37 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=FSnAllHtG70&list=RDBOKiCNOrkes&index=28`

### Category

ads

### Describe the issue

![Captura de pantalla 2022-12-22 07 36 46](https://user-images.githubusercontent.com/121235806/209135999-c6a20d5b-cd74-41a1-8795-7840cb33964a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 88782
  cosmetic: 44202
  scriptlet: 16996
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61533-52, 2d.23h.16m
    easyprivacy: 31006-1171, 2d.23h.17m
    plowe-0: 3678-903, 9d.22h.58m
    spa-0: 3439-11, 19h.5m
    spa-1: 4893-181, 1d.17h.25m
    ublock-abuse: 77-0, 12d.22h.51m
    ublock-badware: 4045-108, 1d.17h.24m
    ublock-filters: 31524-151, 1d.17h.27m
    ublock-privacy: 260-1, 12d.22h.50m
    ublock-quick-fixes: 457-14, 19h.7m
    ublock-unbreak: 1918-47, 1d.17h.26m
    urlhaus-1: 9956-0, 19h.6m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 227 ms
popupPanel: 
  blocked: 38
  blockedDetails: 
    youtube.com: 32
    doubleclick.net: 2
    google.com: 2
    google.com.co: 1
    googlesyndication.com: 1
```
</details>

**Comment by krystian3w** [comment] 2022-12-22 12:43
Duplicate of #7636

**Closed** 2022-12-22 12:44 UTC
Labels: duplicate
