### ISSUE TITLE
bestseller.si

### ISSUE THREAD

**Issue by mihp** [uBlockOrigin/uAssets#720] opened 2017-09-27 07:34 UTC
### URL(s) where the issue occurs

`https://www.bestseller.si/knjiga/9788883701122/moleskine-large-ruled-notebook`

### Describe the issue

Middle clicking the "POGLEJ IN NAROČI" button opens a new like expected and then closes it right away.
Left  click on the button opens the website as expected in the same tab.

### Screenshot(s)

No screenshot possible to show the issue.

### Versions

- Browser/version: Firefox Nightly 58.0a1 (2017-09-26) (64-bit)
- uBlock Origin version: uBlock Origin 1.14.10

### Settings

No changes.

### Notes

If I turn uBlock Origin off the new tab opens normally as expected.

**Comment by mapx-** [comment] 2017-09-27 07:56
add
`@@||bookdepository.com/book/*/?a_aid=$popup`

**Comment by kasper93** [comment] 2017-09-27 09:02
It should be fixed in latest uBlock, you can try 1.14.11rc3 version. Here is the issue fixed https://github.com/gorhill/uBlock/issues/2919

**Comment by mapx-** [comment] 2017-09-27 09:08
it's a filter issue as I can see

**Comment by kasper93** [comment] 2017-09-27 09:19
Not really, middle clicking should not trigger popup rule. And that is already fixed. We still might want to block `bookdepository.com/book/*/?a_aid=` normal popups. Or maybe not, but there is no testcase so whitelist you proposed in not needed IMHO.

**Comment by gorhill** [comment] 2017-09-27 11:37
Dev build of uBO on AMO: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta

**Comment by okiehsch** [comment] 2017-09-28 01:17
I agree with  @kasper93 , this is not a filter issue and it is fixed on my end with Chrome and Firefox using 1.14.11rc6, so unless there is a legitimate popup blocked because of the filter `/?a_aid=$popup` no exception filter is needed.

**Comment by mapx-** [comment] 2017-09-28 06:35
yep, on chrome still using 1.14.8

**Comment by okiehsch** [comment] 2017-09-28 17:23
@mapx- you are right of course, I lost sight of the issue at hand.
The fact that the issue is fixed in 1.14.11rc6 and  is technically not a filter issue, does not mean it can not be fixed by adding a exception filter until 1.14.12 has been released.

**Closed** 2017-09-28 17:24 UTC
