### ISSUE TITLE
deezer.com: detection

### ISSUE THREAD

**Issue by Robotic-Brain** [uBlockOrigin/uAssets#21293] opened 2023-12-09 10:39 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.deezer.com/en/`

### Description

When hitting on "Play" a popup appears and the site is unable to play any music.

### Other extensions used

NoScript (Disabled for Deezer.com)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4038901/b3e2fde6-2b66-465b-bcad-76a37ce5f631)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 106386
 cosmetic: 48811
 scriptlet: 19291
 html: 1127
listset (total-discarded, last-updated):
 added:
  DEU-0: 7204-3, 11m
 default:
  user-filters: 4-0, never
  ublock-filters: 36732-77, 11m
  ublock-badware: 7593-11, 11m
  ublock-privacy: 923-4, 11m
  ublock-unbreak: 2202-0, 11m
  ublock-quick-fixes: 171-2, 11m
  easylist: 75899-706, 11m
  easyprivacy: 33073-802, 11m
  urlhaus-1: 9795-0, 11m
  plowe-0: 3776-1, 11m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2230 ms (selfie)
 maxAssetCacheWait: 453 ms
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  hubvisor.io: 2
  sentry.io: 2
 extended:
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)

```
</details>

**Comment by Omega-6** [comment] 2023-12-09 10:51
Did you disable firefox's `Enhanched Tracking Protection`?

**Comment by mapx-** [comment] 2023-12-09 10:52
it seems at least in USA (us ip) without a premium account you can listen only 30 seconds.
In Europe the full song.

**Comment by Robotic-Brain** [comment] 2023-12-10 04:38
> Did you disable firefox's `Enhanched Tracking Protection`? Make sure you don't have any forgotten ad / tracker blocker enabled -- `ctrl + shift + a` / `about:addons`

I disabled all other addons and the Enhanced Tracking Protection.

@mapx-  I'll try to reproduce it with a new account and browser profile.

**Comment by Robotic-Brain** [comment] 2023-12-10 06:19
On a completely new account and browser profile everything works. But as soon as i log into my usual account the problem appears again...

I guess that means the account has been "soft banned"? In this case this issue can be closed unless there is a uBlock based workaround I'm not seeing?

**Comment by mapx-** [comment] 2023-12-10 06:30
What happens if you click "accept" ?

**Comment by Robotic-Brain** [comment] 2023-12-10 07:09
> What happens if you click "accept" ?

The page just reloads and displays the popup again.

**Comment by mapx-** [comment] 2023-12-10 07:12
and you get the same problem using the old account in the new profile, right ?

**Comment by Robotic-Brain** [comment] 2023-12-10 07:12
yes

**Comment by mapx-** [comment] 2023-12-10 07:18
other guys have the same issue
https://en.deezercommunity.com/other-devices-49/free-account-cant-listen-to-songs-disabled-adblock-clicked-accept-cookies-still-wont-play-on-firefox-78048

closing for now as I cannot reproduce the issue

**Closed** 2023-12-10 07:19 UTC
Labels: unable to reproduce
