### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by JakobHolkestadMolnes** [uBlockOrigin/uAssets#14030] opened 2022-07-15 18:13 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=xYUzqOHN2WQ`

### Category

breakage

### Describe the issue

When having cosmetic filtering on, the chapter selection menu, don't show up. When turning it off, it shows up again, along with an ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bilde](https://user-images.githubusercontent.com/31732500/179285760-7ec767dc-48bf-4ed0-b1bc-cf052dd566da.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80536
  cosmetic: 46474
  scriptlet: 17397
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 32804-40, 3m
    ublock-badware: 4224-3, 3m
    ublock-privacy: 240-0, 3m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1851-0, 3m
    easylist: 68397-562, 3m
    easyprivacy: 27421-595, 3m
    urlhaus-1: 5032-0, 3m
    plowe-0: 3644-3, 3m
    NOR-0: 2802-10, 3m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 64
  blockedDetails: 
    youtube.com: 47
    doubleclick.net: 3
    google.com: 6
    google.no: 1
    googlevideo.com: 7
```
</details>

**Comment by MasterKia** [comment] 2022-07-15 19:22
> * [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed** 2022-07-15 20:00 UTC
Labels: duplicate

**Comment by gwarser** [comment] 2022-07-15 20:02
www.youtube.com#@#ytd-engagement-panel-section-list-renderer
