### ISSUE TITLE
iwdlive.com: ads

### ISSUE THREAD

**Issue by varjuviktor69** [uBlockOrigin/uAssets#17625] opened 2023-04-16 16:50 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://iwdlive.com/caster/iwd`

### Category

ads

### Description

On this site twitch is embedded and ads are showing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 89242
  cosmetic: 39871
  scriptlet: 17713
  html: 949
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34656-40, 1d.51m
    ublock-badware: 6654-2, 1d.50m
    ublock-privacy: 344-0, 1d.49m
    ublock-abuse: 70-0, 1d.48m
    ublock-unbreak: 1997-5, 1d.47m
    ublock-quick-fixes: 178-22, 1h.43m
    easylist: 64839-610, 1d.46m
    easyprivacy: 30816-1770, 1d.45m
    urlhaus-1: 7092-1, 1h.42m
    plowe-0: 3753-1, 9d.22h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 424 ms (selfie)
  maxAssetCacheWait: 70 ms
popupPanel: 
  blocked: 194
  blockedDetails: 
    amazon-adsystem.com: 1
    cdndex.io: 1
    d2v02itv0y9u9t.cloudfront.net: 1
    doubleclick.net: 4
    google.com: 13
    googletagmanager.com: 1
    imrworldwide.com: 2
    scorecardresearch.com: 47
    youtube.com: 124
```
</details>

**Comment by u-RraaLL** [comment] 2023-04-16 17:13
> * [x]  I did not answer truthfully to **ALL** the above checkpoints.

I  see.

> On this site twitch is embedded and ads are showing.

So ads are showing on twitch? Okay, try https://github.com/pixeltris/TwitchAdSolutions#readme

Duplicate of #5184

**Closed** 2023-04-16 17:15 UTC
Labels: duplicate
