### ISSUE TITLE
[nsfw] gearbest.com: popups

### ISSUE THREAD

**Issue by Ro0h** [uBlockOrigin/uAssets#11767] opened 2022-02-16 23:48 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gearbest.com/promotion-bestseller-special-1308.html?lkid=45687009&cid=517961554097103206`

### Category

popups

### Describe the issue

tab opening with click on another site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 78658
  cosmetic: 43719
  scriptlet: 16621
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63376-9, 2d.3h.11m
    easyprivacy: 26556-120, 2d.3h.7m
    plowe-0: 3673-805, 3d.18h.55m
    spa-1: 4220-76, 2d.3h.12m
    ublock-abuse: 77-0, 3d.22h.58m
    ublock-badware: 3932-76, 3d.22h.57m
    ublock-filters: 30250-177, 2d.3h.10m
    ublock-privacy: 200-2, 2d.3h.9m
    ublock-unbreak: 1716-40, 2d.3h.8m
    urlhaus-1: 6457-0, 11h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 314 ms (selfie)
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    gearbest.com: 2
    googletagmanager.com: 1
    logsss.com: 1
```
</details>

**Comment by Ro0h** [comment] 2022-02-16 23:48
tab opening with click on another site

**Comment by bogachenko** [comment] 2022-02-17 01:04
@Ro0h On which site the redirect occurs, that is, from which site did you get to `gearbest.com` ?


PS: Why did you open 2 identical tickets for this issue https://github.com/uBlockOrigin/uAssets/issues/11766?

**Comment by uBlock-user** [comment] 2022-02-17 05:19
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11766

**Closed by uBlock-user** 2022-02-17 05:19 UTC
