### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Heir-2099** [uBlockOrigin/uAssets#16860] opened 2023-02-20 17:17 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Description

lost one viewport
![未命名](https://user-images.githubusercontent.com/73870509/220167791-d50d2f7d-fd7e-4b50-93b9-9e5ba6b65c1e.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![未命名](https://user-images.githubusercontent.com/73870509/220167465-27f25c1b-ac86-4422-a82d-acba64b4edf2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 101371
  cosmetic: 49055
  scriptlet: 17342
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 5h.37m
  default: 
    user-filters: 0-0, never
    CHN-0: 28160-102, 5h.37m
    easylist: 62104-409, 5h.37m
    easyprivacy: 30988-1194, 5h.37m
    plowe-0: 3671-899, never
    ublock-abuse: 79-0, 5h.37m
    ublock-badware: 4407-121, 5h.37m
    ublock-filters: 32676-172, 5h.37m
    ublock-privacy: 274-1, 5h.37m
    ublock-quick-fixes: 173-19, 5h.37m
    ublock-unbreak: 1901-47, 5h.37m
    urlhaus-1: 5966-0, 5h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2304 ms (selfie)
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    youtube.com: 4
    doubleclick.net: 2
    google.com: 2
    google.com.tw: 1
    ytimg.com: 1
```
</details>

**Comment by krystian3w** [comment] 2023-02-20 17:41
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1221271200

**Comment by krystian3w** [comment] 2023-02-20 17:43
Resize are rejected for first row in uAssets:

https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1221359744

Also hard is rewrite DOM tree by custom scriptlet to generate jumping 5-th rectangle from second row to first row.

**Closed** 2023-02-20 17:46 UTC
Labels: duplicate
