### ISSUE TITLE
blogs.slv.vic.gov.au: breakage

### ISSUE THREAD

**Issue by dannwebb** [uBlockOrigin/uAssets#17647] opened 2023-04-18 02:40 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blogs.slv.vic.gov.au/our-stories/ask-a-librarian/dome-to-catacomb/`

### Category

breakage

### Description

Beneath each of the headings "Hansen Hall", "Silent library", "An inspiring space", and "Ribbon of words" an image does not display when uBO is enabled. When uBO is disabled the images display as expected.

The images are produced by "twentytwenty", a jquery plugin, being used by the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![libpic02](https://user-images.githubusercontent.com/33207304/232656286-9747026e-3eda-4e09-b76e-c36f1cbada34.png)

![libpic01](https://user-images.githubusercontent.com/33207304/232656311-4d07fd07-eabd-4c60-b7d6-08cafe310ff3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 89412
  cosmetic: 39913
  scriptlet: 17716
  html: 947
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34685-63, 3h.11m
    ublock-badware: 6732-0, 3h.10m
    ublock-privacy: 344-0, 7d.3h.14m
    ublock-abuse: 78-0, 7d.3h.13m
    ublock-unbreak: 2000-0, 3h.9m
    easylist: 64984-609, 3h.13m
    easyprivacy: 30858-1772, 3h.12m
    urlhaus-1: 6998-1, 3h.2m
    plowe-0: 3750-2, 6d.23h.4m
    ublock-quick-fixes: 185-5, 3h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3307 ms
  maxAssetCacheWait: 740 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 1
    hotjar.com: 1
    shareaholic.com: 2
    viglink.com: 1
```
</details>

**Comment by stephenhawk8054** [comment] 2023-04-18 02:52
It appears normally for me. Screenshot: https://user-images.githubusercontent.com/66517106/232658281-f261fd18-61e3-496b-9013-a28287c49c63.png

**Comment by dannwebb** [comment] 2023-04-18 03:51
I see it's fine in Chrome. I was in Firefox 112.0.1 (64-bit) and it doesn't show.

**Comment by stephenhawk8054** [comment] 2023-04-18 03:52
I also accessed from Firefox (screenshot above) but the image still shows normally.

**Comment by dannwebb** [comment] 2023-04-18 05:02
Don't know what's going on then. Screen capture shows enabling/disabling, and the image comes and goes. 
https://user-images.githubusercontent.com/33207304/232675737-5c225f59-946a-4db4-8da5-ed84be986384.mp4

**Comment by stephenhawk8054** [comment] 2023-04-18 05:19
Can you click on ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger) on the [popup user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), reload the page where issue happens then click on [the "DOM Inspector" button](https://github.com/gorhill/uBlock/wiki/The-logger#dom-inspector) (`</>` icon) and screenshot it here.

**Comment by mapx-** [comment] 2023-04-18 05:33
Could be some conflict with other addon

You could disable all other addons and test again

**Comment by dannwebb** [comment] 2023-04-18 05:54
Hope this is right: 
![logger](https://user-images.githubusercontent.com/33207304/232683559-b9584b13-4e56-4e74-9955-85aa3a12e4cf.png)

I disabled all addons except uBO, reloaded the page, and the same thing occurs: the image appears/disappears when uBO is disabled/enabled.

**Comment by stephenhawk8054** [comment] 2023-04-18 06:01
I just realized you haven't forced updated the filter lists yet.

Can you do what you ticked on?

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by dannwebb** [comment] 2023-04-18 06:43
I did the forced update again. Same behaviour.

**Comment by stephenhawk8054** [comment] 2023-04-18 06:52
Can you do these steps:

- Click on ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger) on the [popup user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), 
- Reload the page,
- Go to the logger again, [click on search bar and choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output),
- Copy the logger via [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog),
- Paste the logs here

**Comment by dannwebb** [comment] 2023-04-18 07:52
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | \|\|viglink.com^ | -- | blogs.slv.vic.gov.au | 3 | get | script | `https://cdn.viglink.com/api/vglnk.js` |
| +2 | \|\|shareaholic.com/partners.js | -- | blogs.slv.vic.gov.au | 3 | get | script | `https://partner.shareaholic.com/partners.js?location=https%3A%2F%2Fblogs.slv.vic.gov.au%2Four-stories%2Fask-a-librarian%2Fdome-to-catacomb%2F&cl=en-US&id_sync=59ee7b82-db32-44e8-91a0-f47a4c779c00&pvs=35&site=a75ba6147acba5fa8c4ec5ba1e9041e4` |
| +1 | \|\|analytics.shareaholic.com^ | -- | blogs.slv.vic.gov.au | 3 | post | beacon | `https://analytics.shareaholic.com/e` |
| +1 | \|\|hotjar.com^$3p | -- | blogs.slv.vic.gov.au | 3 | get | script | `https://static.hotjar.com/c/hotjar-1508042.js?sv=5` |
| +1 | /fbevents.js | -- | blogs.slv.vic.gov.au | 3 | get | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +1 | googletagmanager_gtm.js | << | blogs.slv.vic.gov.au | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-5FTVNW` |
| +1 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | blogs.slv.vic.gov.au | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-5FTVNW` |
| +1 | \|\|googletagmanager.com^ | -- | blogs.slv.vic.gov.au | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-5FTVNW` |
</details>

**Comment by stephenhawk8054** [comment] 2023-04-18 08:46
Hmmm, yours looks like mine. I'm also not sure what's wrong. Which country are you when accessing the site?

**Comment by gorhill** [comment] 2023-04-18 17:24
You could try a new Firefox profile to be sure it's not caused by some changes in browser settings:

- Navigate to `about:profiles`
- Click _Create a New Profile_, give it a name, click _Next_
- Click _Launch profile in a new browser_
- Install uBO in that new profile, force an update of filter lists
- Navigate to the problematic webpage

See if you still have the issue.

On my side, the provided URL won't load at all, even with an Australia IP address.

**Comment by stephenhawk8054** [comment] 2023-04-19 04:23
Site is back online now. But I can't reproduce with Australia IP either.

**Comment by dannwebb** [comment] 2023-04-19 05:37
Yea the site was down for a while earlier.

I created a new profile as suggested and opened in a new browser. 

The images can be seen no worries. Out of curiosity, I installed uBO in that instance, and the images disappeared. So werid.

**Comment by stephenhawk8054** [comment] 2023-04-19 05:46
Can you test these filters, one-by-one?

```adb
@@||googletagmanager.com/gtm.js$script,domain=blogs.slv.vic.gov.au
@@||static.hotjar.com/c/hotjar$script,domain=blogs.slv.vic.gov.au
@@||partner.shareaholic.com/partners.js$script,domain=blogs.slv.vic.gov.au
@@||cdn.viglink.com/api/vglnk.js$script,domain=blogs.slv.vic.gov.au
```

Add in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page and test again.

Add them one by one, don't add all of them at once, so we can see which causes the issues.

**Comment by dannwebb** [comment] 2023-04-19 06:35
@@||googletagmanager.com/gtm.js$script,domain=blogs.slv.vic.gov.au
**Images appear**
When I press F5 a second time (without Ctrl) the images disappear.

@@||static.hotjar.com/c/hotjar$script,domain=blogs.slv.vic.gov.au
**Images appear**
When I press F5 a second time (without Ctrl) the images disappear.
Repeated F5's (without Ctrl) toggles the images, they appear then disappear with each press.

@@||partner.shareaholic.com/partners.js$script,domain=blogs.slv.vic.gov.au
**Images appear**
When I press F5 a second time (without Ctrl) the images disappear.

@@||cdn.viglink.com/api/vglnk.js$script,domain=blogs.slv.vic.gov.au
**Images appear**
When I press F5 a second time (without Ctrl) the images disappear.

**Comment by stephenhawk8054** [comment] 2023-04-19 09:40
Yeah, it's hard to remote investigate. You might need to use some combinations of those 4 filters to see which one works. Or you'll need to wait for others who can reproduce and investigate it.

**Comment by mapx-** [comment] 2023-04-19 10:15
closing for now, if someone else could reproduce / find a fix => just still commenting here

**Closed by mapx-** 2023-04-19 10:15 UTC
Labels: unable to reproduce

**Comment by dannwebb** [comment] 2023-04-19 12:06
@gorhill Yes I've reloaded this page many many many times over the last few days.
It's specifically the images that are handled by the jQuery twentytwenty plugin that are the issue, the ones with the slider thingy. It doesn't seem to be just a caching thing.

**Comment by gorhill** [comment] 2023-04-19 12:09
Are there any errors reported for the page in dev tools console?

**Comment by dannwebb** [comment] 2023-04-20 02:50
Yes, attached txt file.
[console msgs.txt](https://github.com/uBlockOrigin/uAssets/files/11279380/console.msgs.txt)
