### ISSUE TITLE
telegraph.co.uk [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1882] opened 2018-04-03 14:58 UTC
URL(s) where the issue occurs

`https://www.telegraph.co.uk/news/2018/04/03/teenage-girl-shot-dead-london/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by gorhill** [comment] 2018-04-03 16:51
Can't reproduce. If I toggle off cosmetic filtering though, the adblock-wall appears.

**Comment by mapx-** [comment] 2018-04-03 16:53
it seems already fixed in ublock filters, cannot reproduce

**Comment by KiLL4FuNK** [comment] 2018-04-03 18:30
how weird now do not show anything can close the topic

**Closed** 2018-04-03 18:33 UTC
Labels: unable to reproduce
