### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by darmstadt40** [uBlockOrigin/uAssets#13067] opened 2022-05-03 23:14 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=wT_BgdUl8YA&list=PLyd7WkTi_Fh3OhlADBVMm1qySoxv58WOO`

### Category

ads

### Describe the issue

ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 85017
  cosmetic: 46333
  scriptlet: 16778
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5647-0, 1d.5h.54m
    easylist: 66297-57, 1d.5h.56m
    easyprivacy: 26926-132, 1d.5h.55m
    plowe-0: 3679-806, 7d.2h.20m
    ublock-abuse: 75-0, 5d.1h.44m
    ublock-badware: 4140-92, 1d.5h.58m
    ublock-filters: 30937-98, 1d.5h.59m
    ublock-privacy: 213-3, 5d.1h.45m
    ublock-quick-fixes: 165-0, 1d.5h.52m
    ublock-unbreak: 1773-41, 1d.5h.57m
    urlhaus-1: 9661-0, 1d.5h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 104 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9051 ms (selfie)
  maxAssetCacheWait: 426 ms
popupPanel: 
  blocked: 374
  blockedDetails: 
    youtube.com: 364
    doubleclick.net: 2
    google.com: 4
    google.de: 1
    googlesyndication.com: 1
    googlevideo.com: 2
```
</details>

**Comment by okiehsch** [comment] 2022-05-04 03:52
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by okiehsch** 2022-05-04 03:52 UTC
