### ISSUE TITLE
https://katfile.com/

### ISSUE THREAD

**Issue by maxvlas** [uBlockOrigin/uAssets#6749] opened 2019-12-27 06:21 UTC
### URL(s) where the issue occurs

https://katfile.com/6s32ttvooiw1/Free.YouTube.Download.4.3.6.1220.rar.html
click slow download

### Describe the issue

Here I decided to download. after clicking on the download, I got a window (screenshot below)

### Screenshot(s)

![iISECTYJPu](https://user-images.githubusercontent.com/11572859/71504334-14560100-288a-11ea-80e1-670baaccaaca.gif)

### Versions

- Browser/version: Google Chrome Version 79.0.3945.88 (Official Build), (32 bit)
- uBlock Origin version: uBlock Origin 1.23.0

### Settings

![69560116-48ed4900-0fbc-11ea-9683-e2bf7ef535c8](https://user-images.githubusercontent.com/11572859/71504354-2afc5800-288a-11ea-95f5-d4b4bbfc4ed4.png)

### Notes

The uBlock filters rules for this site are probably outdated and need to be edited.

**Comment by Yuki2718** [comment] 2019-12-27 14:01
Reproduced here:
![KatFile](https://user-images.githubusercontent.com/58900598/71519735-22446a00-28fc-11ea-83fc-cc92a73740c4.png)
`katfile.com##+js(set, adblock, false)` should work; however, once you proceeded to download and accessed again, you'll be kept waiting 120 min for next download, and even worse, major VPN IPs are blocked by the site.

**Comment by llacb47** [comment] 2019-12-27 18:18
That's already in uBlock filters.

**Comment by krystian3w** [comment] 2019-12-27 19:10
@gwarser Can you do anything with the browser cache on `raw.githubusercontent.com`?

This is probably a bug that I still have that I have to manually clean the cache for 1raw.githubusercontent.com1 or open the list from logger with unique attrib "`?_=X`" and refresh it afterwards via `Ctrl+F5`.

**Comment by Yuki2718** [comment] 2019-12-27 19:53
@llacb47 Right, I forgot to make sure filters were up-to-date on the test profile. Now another problem seems to be you can't download the video after CAPTCHA
![kat](https://user-images.githubusercontent.com/58900598/71530536-85022980-292d-11ea-8799-d87079c44790.png), after clicking the send button you should be able to proceed to download, but actual behavior is you'll be brought to:
![kat2](https://user-images.githubusercontent.com/58900598/71530573-b11daa80-292d-11ea-99cb-803ac67ff281.png)
I guess it may be due to
`katfile.com##+js(window.open-defuser)`
but has no time to check now. Firefox's own popup blocker also need to be whitelisted.

**Comment by okiehsch** [comment] 2019-12-28 00:50
>  after clicking the send button you should be able to proceed to download, but actual behavior is you'll be brought to:

I don't understand. if I click "Download" I get the requested file on my end.

**Comment by krystian3w** [comment] 2019-12-28 00:53
@Yuki2718 try click many times?

**Comment by krystian3w** [comment] 2019-12-28 00:54
For my ` katfile.com##+js(window.open-defuser)` generate breakage:

![obraz](https://user-images.githubusercontent.com/35370833/71536894-fe415280-2914-11ea-9931-39857be70f81.png) |
--- |

**Comment by Yuki2718** [comment] 2019-12-28 03:31
@okiehsch @krystian3w One click and nothing happened except a popup was blocked due to `||kerumal.com^$popup` in EL. After the second click, I was again led to the "Downloading too long?". It's likely many clicks triggers that redirect.

**Comment by okiehsch** [comment] 2019-12-28 03:35
> One click and nothing happened except a popup was blocked due to ||kerumal.com^$popup

That is fixed on my end by `katfile.com##+js(window.open-defuser)`.
The first click results in "nothing". The second click works on my end,

**Comment by Yuki2718** [comment] 2019-12-28 03:42
Ah, then sorry again mine was not up-to-date (yet another profile), I tend to assume if "update now" in grey they are up-to-date but hovering on uBlokk filter told me the last update was 3d ago. I'll test w/ updated lists.

**Comment by okiehsch** [comment] 2019-12-28 03:43
The uBO-lists auto update every 4 days. If the button is grey it means that the list has been last updated inside that timeframe.

**Comment by Yuki2718** [comment] 2019-12-28 03:55
> 
> 
> The uBO-lists auto update every 4 days. If the button is grey it means that the list has been last updated inside that time frame.

All right, I'll remember that and make sure to purge and update first to reduce unnecessary confusion.
Now with the filter "updated a minute ago", reproduced. I paste the logs here. Anything else you need?
[log_markdown.txt](https://github.com/uBlockOrigin/uAssets/files/4006688/log_markdown.txt)
![ss](https://user-images.githubusercontent.com/58900598/71538592-147cfc00-2971-11ea-8f4a-ecf5486d0469.png)
![SS2](https://user-images.githubusercontent.com/58900598/71538599-3d9d8c80-2971-11ea-90c1-f77ee9f4c44b.png)

**Comment by okiehsch** [comment] 2019-12-28 04:14
I still don't understand the issue exactly. After solving the captcha and clicking "send". 
I get your first screenshot. If I then click "Download" I get the requested file.
I can't reproduce the "403 Forbidden" errror **krystian3w** mentions  if that is what you mean.

**Comment by Yuki2718** [comment] 2019-12-28 04:29
Whoops! IDK why I thought of clicking that Download button. Maybe because when I accessed w/out blocker for confirmation purpose, the looking was different. Today is terrible day for me and all you guys involved:(

**Closed** 2019-12-29 00:09 UTC
Labels: unable to reproduce

**Comment by doio** [comment] 2020-12-06 03:25
Ad popups are stilling showing

![20201206112342](https://user-images.githubusercontent.com/4461202/101270625-ad3d0e00-37b5-11eb-858b-941b48738713.png)
