### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by enriqueolvera** [uBlockOrigin/uAssets#14710] opened 2022-09-06 21:12 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

ads are not blocked when watching livestreams

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 84807
  cosmetic: 46777
  scriptlet: 18058
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64962-51, 1d.12h.38m
    easyprivacy: 27487-126, 1d.12h.37m
    plowe-0: 3671-814, 1d.12h.39m
    spa-0: 3714-35, 12h.28m
    spa-1: 4612-174, 1d.12h.36m
    ublock-abuse: 76-0, 1d.12h.42m
    ublock-badware: 4217-101, 1d.12h.35m
    ublock-filters: 32534-161, 1d.12h.34m
    ublock-privacy: 241-1, 1d.12h.41m
    ublock-quick-fixes: 420-1, 12h.27m
    ublock-unbreak: 1847-43, 1d.12h.33m
    urlhaus-1: 7527-0, 12h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 280 ms (selfie)
  maxAssetCacheWait: 191 ms
popupPanel: 
  blocked: 53
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 2
    scorecardresearch.com: 44
    sentry.io: 2
```
</details>

**Comment by MasterKia** [comment] 2022-09-07 01:32
> - [X] I verified that the issue has not already been reported (use this button to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-09-07 01:32
Duplicate of: https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-09-07 01:32 UTC
