### ISSUE TITLE
9anime.to: detection

### ISSUE THREAD

**Issue by Anyucikad** [uBlockOrigin/uAssets#10551] opened 2021-11-23 17:58 UTC
### URL address of the web page

`https://9anime.to/`

### Category

detection

### Describe the issue

The site detects the adblocker after a few seconds and shows the message:
AdBlock breaks it!

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 76979
  cosmetic: 39259
  scriptlet: 16184
  html: 598
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.7h.12m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30317-28, 14h.48m
    ublock-badware: 3424-1, 14h.46m
    ublock-privacy: 182-0, 14h.44m
    ublock-abuse: 67-0, 14h.42m
    ublock-unbreak: 1701-0, 14h.39m
    easylist: 60974-541, 14h.37m
    easyprivacy: 26301-474, 14h.35m
    plowe-0: 3699-3, 5h.51m
    urlhaus-1: 7455-0, 20h.40m
filterset (user): [array of 108 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 899
  launchFromSelfie: true
```
</details>

**Comment by okiehsch** [comment] 2021-11-23 18:02
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10549, https://github.com/uBlockOrigin/uAssets/issues/10548 and https://github.com/uBlockOrigin/uAssets/issues/10547

**Closed by okiehsch** 2021-11-23 18:02 UTC
