### ISSUE TITLE
tomshardware.com

### ISSUE THREAD

**Issue by Shonk** [uBlockOrigin/uAssets#7446] opened 2020-05-22 22:30 UTC
### URL(s) where the issue occurs

[www.tomshardware.com]

### Describe the issue

The website uses 1.5 CPU Threads on firefox its fine on chrome

### Versions

Firefox 76.0.1
uBlock Origin v1.27.6

### Settings

Default

### Notes

I have just spent the last few hours tracking down the issue
that has annoyed me for months but have only just got around to finding the issue
any script with responsive.js in its name maxes out 1.5 threads on firefox
its fine on chrome

I have put a temp fix inplace with the following

! 22/05/2020 tomshardware.com
||*responsive.js$script,domain=www.tomshardware.com

If something like this could be added to uBlock filters – Resource abuse that would be great

**Comment by llacb47** [comment] 2020-05-22 22:47
Please read https://github.com/uBlockOrigin/uAssets/issues/7441

**Comment by Shonk** [comment] 2020-05-22 22:58
> 
> 
> Please read #7441
> 
> And test the fixes from this comment [#7441 (comment)](https://github.com/uBlockOrigin/uAssets/issues/7441#issuecomment-631840016) or this comment [#7441 (comment)](https://github.com/uBlockOrigin/uAssets/issues/7441#issuecomment-631860001)

Its not just files hosted on futurecdn they are also on widgets.future-fie.co.uk

**Comment by okiehsch** [comment] 2020-05-23 01:33
> Its not just files hosted on futurecdn they are also on widgets.future-fie.co.uk


I can't reproduce it's the same furturecdn script on my end.
![image](https://user-images.githubusercontent.com/16838044/82718901-ff00c980-9ca5-11ea-9bcc-817ec5248003.png)

Anyway it is a site/browser issue, someone should open a bug report with mozilla.

**Comment by Shonk** [comment] 2020-05-23 02:01
It depends where you are on the website 
on the main page you have to scroll all the way down whilst monitoring for more to show up

![tomshardware3](https://user-images.githubusercontent.com/8131322/82719358-bb0bc580-9ca1-11ea-8d32-11eb7547f4f8.png)

**Comment by okiehsch** [comment] 2020-05-23 02:30
Are you sure that `widgets.future-fie.co.uk` is responsible for a high CPU?

It is not on my end.

**Comment by Shonk** [comment] 2020-05-23 02:57
on one of the review pages i had all the others blocked and still had 100% 
blocked that one and it went to 0% beforei did the catchall

**Comment by Yuki2718** [comment] 2020-05-23 05:41
I can reproduce the CPU spike but `||widgets.future-fie.co.uk/js/w/responsive.js$domain=tomshardware.com` did not change it. `||vanilla.futurecdn.net/tomshardware/*/impact-lazyload-format-responsive.js$domain=tomshardware.com` did the trick.

**Comment by okiehsch** [comment] 2020-05-23 05:56
See
https://github.com/uBlockOrigin/uAssets/issues/7441#issuecomment-631858162

**Comment by Yuki2718** [comment] 2020-05-23 06:03
Okay, and found the same script on subpages.
So
`||vanilla.futurecdn.net/*/media/js/header/impact-lazyload-format-responsive.js$3p`
`||vanilla.futurecdn.net/*/media/js/header/n-format-format-responsive.js$3p`
will be needed. Does adding
`||vanilla.futurecdn.net/*-layout-responsive.js$3p`
cause some problem? It appears this further reduces CPU usage.

**Comment by okiehsch** [comment] 2020-05-24 02:12
@Yuki2718 I don't see any noticable further reduction on my end and I don't see any noticable breakage if I add your additional filter.
Like I said in the other [issue](https://github.com/uBlockOrigin/uAssets/issues/7441#issuecomment-631855423), it's a site/browser issue and should be fixed by the site or Firefox.

**Closed by okiehsch** 2020-05-24 02:12 UTC

**Comment by Yuki2718** [comment] 2020-05-24 12:14
> 
> 
> @Yuki2718 I don't see any noticable further reduction on my end and I don't see any noticable breakage if I add your additional filter.
> Like I said in the other [issue](https://github.com/uBlockOrigin/uAssets/issues/7441#issuecomment-631855423), it's a site/browser issue and should be fixed by the site or Firefox.

All right, thx for testing!

**Comment by gorhill** [comment] 2020-06-19 18:45
I can reproduce undue CPU usage, and @Yuki2718's filter along with a CSP to forbid workers seem to work fto fix this:

    ||tomshardware.com^$csp=worker-src 'none'
    ||vanilla.futurecdn.net/*-layout-responsive.js$3p

**Comment by gorhill** [comment] 2020-07-02 14:29
https://bugzilla.mozilla.org/show_bug.cgi?id=1646799
