### ISSUE TITLE
(Marketplace) facebook.com: ads

### ISSUE THREAD

**Issue by Chillpeng1** [uBlockOrigin/uAssets#12920] opened 2022-04-23 09:55 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/marketplace/?ref=bookmark`

### Category

ads

### Describe the issue

The "Sponsored" section to the left of the marketplace items appears 99% of the time. This did not occur before now.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1184" alt="Screen Shot 2022-04-23 at 7 25 16 AM" src="https://user-images.githubusercontent.com/53358335/164889682-4530a6fd-ece1-465b-9997-46adad464c87.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81612
  cosmetic: 42552
  scriptlet: 16594
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 66123-51, 3d.11h.5m
    easyprivacy: 26861-121, 18h.57m
    plowe-0: 3684-808, 12d.21h.45m
    ublock-abuse: 74-0, 10d.10h.26m
    ublock-badware: 4093-92, 18h.56m
    ublock-filters: 30713-104, 18h.55m
    ublock-privacy: 208-2, 10d.10h.24m
    ublock-quick-fixes: 171-0, 18h.52m
    ublock-unbreak: 1763-42, 18h.54m
    urlhaus-1: 8442-1, 18h.53m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 133 ms (selfie)
  maxAssetCacheWait: 67 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    facebook.com: 1
    doubleclick.net: 3
```
</details>

**Comment by krystian3w** [comment] 2022-04-23 21:20
Duplicate of #3367

**Closed** 2022-04-24 02:50 UTC
Labels: duplicate
