### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by iyy0v** [uBlockOrigin/uAssets#18147] opened 2023-05-20 08:54 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=-sY4ZXhbAkg&list=PLnzaNBZbolap1byxstP6ax5pV8yGGvLMI&index=20`

### Category

breakage

### Description

When watching youtube videos, especially long video (20min +), some parts of the videos don't load and the video gets stuck, until i skip5sec to 10sec then the video continues. But even then, when i get back to the part where it was stuck, it still doesn't load, even if refresh the whole page or come to the video later.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95125
 cosmetic: 38673
 scriptlet: 17321
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 4-0, never
  easylist: 65785-47, 3d.16h.20m
  easyprivacy: 32128-46, 2d.13h.29m
  plowe-0: 3737-938, 4d.10h.59m
  ublock-abuse: 70-0, 10h.51m
  ublock-badware: 7069-127, 3d.16h.19m
  ublock-filters: 33039-97, 2d.15h.19m
  ublock-privacy: 392-73, 10h.50m
  ublock-unbreak: 2015-40, 3d.16h.18m
  urlhaus-1: 8396-1, 21h.59m
filterset (user): [array of 4 redacted]
trustedset: 
 added: [array of 6 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3786 ms (selfie)
 maxAssetCacheWait: 317 ms
popupPanel: 
 blocked: 73
 network: 
  youtube.com: 42
  doubleclick.net: 4
  google.com: 11
  google.dz: 1
  googlevideo.com: 7
  sentry.io: 7
  ytimg.com: 1
 cosmetic: 
  ##.html5-endscreen
  ###masthead-ad
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##.videowall-endscreen
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by stephenhawk8054** [comment] 2023-05-20 10:02
Can you do this?

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by u-RraaLL** [comment] 2023-05-20 10:51
Duplicate of #7636

**Closed by u-RraaLL** 2023-05-20 10:51 UTC
