### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by nabas4** [uBlockOrigin/uAssets#11030] opened 2021-12-21 23:27 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.twitch.tv/nickmercs`

### Category

ads

### Describe the issue

ads are still showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78001
  cosmetic: 40045
  scriptlet: 16390
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62142-8, 33m
    easyprivacy: 26544-17, 31m
    plowe-0: 3717-818, 29m
    ublock-abuse: 72-0, 25m
    ublock-badware: 3616-62, 21m
    ublock-filters: 30073-135, 19m
    ublock-privacy: 192-2, 17m
    ublock-unbreak: 1729-39, 15m
    urlhaus-1: 7576-0, 13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 879
  launchFromSelfie: false
popupPanel: 
  blocked: 74
```
</details>

**Comment by gorhill** [comment] 2021-12-22 00:07
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/10639>.

**Closed by gorhill** 2021-12-22 00:07 UTC

**Comment by PIZZA90** [comment] 2021-12-22 08:15
Months with no ads at least for me with:

`uBO` + `Video Ad-Block, for Twitch`
