### ISSUE TITLE
pub: ads

### ISSUE THREAD

**Issue by bandaid** [uBlockOrigin/uAssets#12549] opened 2022-04-02 01:41 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.pub/movie/doctor-who-zl1qp/1-full`

### Category

ads

### Describe the issue

viewing online video and when paused ads display. this issue occurred previously #12008 several weeks ago and is now back

### Screenshot(s)

<details>
<summary>Screenshot(s), video paused and ads display. this issue occured previously several weeks ago and is now back</summary>

![image](https://user-images.githubusercontent.com/8212255/161360629-c3c56089-e4cd-49be-8447-174fc8cd8feb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 282970
  cosmetic: 317026
  scriptlet: 37916
  html: 737
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30335-74, 5h.23m
    https://github.com/gorhill/httpswitchboard/raw/master/assets/thirdparties/spam404bl.com/spam404scamlist.txt: 4537-0, 5h.23m
    https://mirror1.malwaredomains.com/files/immortal_domains.txt: 0-0, never
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/cryptomining-domains.txt: 228-0, 5h.23m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/fanboy-social-no-cosmetic.txt: 3923-0, 5h.23m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/freecounterstat-domains.txt: 13-0, 5h.23m
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/immortal-domains.txt: 0-0, never
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/istripper-domains.txt: 10-0, never
    https://raw.githubusercontent.com/LanikSJ/ubo-filters/main/filters/volumedata-domains.txt: 1-0, 5h.23m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4460, 5h.23m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-12, 5h.23m
    https://raw.githubusercontent.com/gfmaster/adblock-korea-contrib/master/filter.txt: 1489-8, 5h.23m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6048-39, 5h.23m
    https://raw.githubusercontent.com/gorhill/httpswitchboard/master/assets/thirdparties/mirror1.malwaredomains.com/files/immortal_domains.txt: 2549-0, 5h.23m
    https://raw.githubusercontent.com/gorhill/httpswitchboard/master/assets/thirdparties/mirror1.malwaredomains.com/files/justdomains: 16370-2552, 5h.23m
    https://raw.githubusercontent.com/gorhill/httpswitchboard/master/assets/thirdparties/winhelp2002.mvps.org/hosts.txt: 13625-160, 5h.23m
    https://raw.githubusercontent.com/gorhill/httpswitchboard/master/assets/thirdparties/www.fanboy.co.nz/enhancedstats.txt: 758-4, 5h.23m
    https://raw.githubusercontent.com/gorhill/httpswitchboard/master/assets/thirdparties/www.fanboy.co.nz/fanboy-antifacebook.txt: 55-19, 5h.23m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-14, 5h.23m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-587, 5h.23m
    [54 lists not shown]: [too many]
  default: 
    user-filters: 192-24, never
    ublock-filters: 31067-169, 5h.24m
    ublock-badware: 4005-93, 5h.24m
    ublock-privacy: 211-43, 5h.24m
    ublock-abuse: 72-58, 5h.24m
    ublock-unbreak: 1753-47, 5h.24m
    easylist: 65125-65125, 5h.24m
    easyprivacy: 26743-26740, 5h.24m
    urlhaus-1: 9450-0, 5h.24m
    plowe-0: 3687-2438, 5h.24m
    ublock-quick-fixes: 138-16, 5h.23m
filterset (user): [array of 192 redacted]
trustedset: 
  added: [array of 81 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 433 redacted]
hostRuleset: 
  added: [array of 26 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  uiTheme: dark
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2000 ms (selfie)
  maxAssetCacheWait: 2100 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    fmovies.pub: 1
    addthis.com: 1
    amung.us: 1
    disqus.com: 1
    facebook.net: 1
    vizcloud.online: 1
```
</details>

**Comment by stephenhawk8054** [comment] 2022-04-02 02:17
Force update your filter lists

**Comment by bandaid** [comment] 2022-04-02 03:55
> Force update your filter lists

Prerequisites

**Comment by bandaid** [comment] 2022-04-02 03:59
someone resolved it and failed to note the fix here. it is mandatory.

**Comment by stephenhawk8054** [comment] 2022-04-02 04:14
I can't reproduce your issue. Looks like it's fixed in [https://github.com/uBlockOrigin/uAssets/commit/3397ad8bb0665a9067a4b3fc3050c88a4bf6cd48](https://github.com/uBlockOrigin/uAssets/commit/3397ad8bb0665a9067a4b3fc3050c88a4bf6cd48) hours ago. I see that you are using many custom lists. Can you test with default settings and force update the lists?

**Comment by bandaid** [comment] 2022-04-02 05:03
it cannot be reproduced now because it has been fixed. I've tried all methods previously prior to posting the issue.

**Comment by stephenhawk8054** [comment] 2022-04-02 05:09
As far as I see, it's fixed (8 hours ago) before this issue (3 hours ago) is posted.

**Closed** 2022-04-02 05:15 UTC

**Comment by bandaid** [comment] 2022-04-03 01:29
> 

Again, UPDATES were completed prior to submitting the request. additionally whatever you're talking about "update" 8 hours ago has nothing to do with the current issue. I test on four different browsers and EACH and EVERY browser displayed the identical issue... especially AFTER clearing cache and updating rules. Do not tort with some childish remark how having my multiple rules have something to do with it, since I have been using most all these rules since early 2010 without issue. I think it's better to understand that there are people out there with more experience than yourself.

**Comment by stephenhawk8054** [comment] 2022-04-03 01:57
I mean when you forced update the filter lists, the fix might have not applied yet. But the issue was submitted hours after your filter lists last updated, hence these information in your configuration (the last updates was 5 hours ago):

```yaml
ublock-filters: 31067-169, 5h.24m
ublock-badware: 4005-93, 5h.24m
ublock-privacy: 211-43, 5h.24m
ublock-abuse: 72-58, 5h.24m
ublock-unbreak: 1753-47, 5h.24m
easylist: 65125-65125, 5h.24m
easyprivacy: 26743-26740, 5h.24m
urlhaus-1: 9450-0, 5h.24m
plowe-0: 3687-2438, 5h.24m
ublock-quick-fixes: 138-16, 5h.23m
```

That's why I said it's better to check again before pressing submit button, because someone might have fixed it already and that person could not see and note in this issue because he is not online yet. And when I checked the issue, I could not reproduce your issue, that's why I said "force update the filter lists" to make sure again that it's already fixed recently.
