### ISSUE TITLE
*.efilecabinet.net: breakage

### ISSUE THREAD

**Issue by mw-christensen** [uBlockOrigin/uAssets#16569] opened 2023-01-30 18:40 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In issue [#16385](https://github.com/uBlockOrigin/uAssets/issues/16385) you created a filter for rubex.efilecabinet.net

The fix was on line [4874](https://github.com/uBlockOrigin/uAssets/commit/0db4d5ef6c61a5d5ae1e3da16ebe750e4a14f4f2) of filters/unbreak.txt I found out today that we have several subdomains. Could you please modify "rubex.efilecabinet.net" to be "*.efilecabinet.net"

OR

 it appears that the reason all subdomains are getting blocked is because they are accessing https://js.monitor.azure.com/scripts/b/ext/ai.clck.2.6.2.min.js 
Would it be possible for this to be removed from the EasyPrivacy list so that this is no longer an issue? Alternatively, if there is an explanation as to why this file (ai.clck.2.6.2.min.js) is being blocked, I could let our devs know so they could work on a workaround or fix.
 
 Thank you so much!

### URL(s) where the issue occurs.

`http://account.efilecabinet.net`
`http://beta.efilecabinet.net`
`http://*.efilecabinet.net`

### uBO version

 1.46.0

### Browser name and version

Google Chrome Version 109.0.5414.120

### Settings

- None

**Comment by garry-ut99** [comment] 2023-01-30 19:03
> * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.

- duplicate of https://github.com/uBlockOrigin/uAssets/issues/16385
- broken by EasyPrivacy, so report here: https://github.com/easylist/easylist/issues

**Comment by mapx-** [comment] 2023-01-30 19:17
@ryanbr

**Closed** 2023-01-31 05:50 UTC
Labels: broken by EasyPrivacy
