### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Wilkancis** [uBlockOrigin/uAssets#14648] opened 2022-09-02 18:48 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=z8atGvZGEeo`

### Category

ads

### Describe the issue

advert showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82863
  cosmetic: 42300
  scriptlet: 17757
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66456-51, 1d.31m
    easyprivacy: 27449-126, 1d.30m
    plowe-0: 3634-777, 2d.32m
    ublock-abuse: 76-0, 4d.10h.8m
    ublock-badware: 4202-100, 1d.29m
    ublock-filters: 32458-108, 1d.28m
    ublock-privacy: 241-3, 4d.10h.7m
    ublock-quick-fixes: 414-4, 1d.26m
    ublock-unbreak: 1845-41, 1d.27m
    urlhaus-1: 7511-0, 1d.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 551
  blockedDetails: 
    youtube.com: 457
    doubleclick.net: 14
    google.co.uk: 1
    google.com: 59
    googlesyndication.com: 13
    googlevideo.com: 7
```
</details>

**Comment by MasterKia** [comment] 2022-09-02 18:51
> - [X] I verified that the issue has not already been reported (use this button to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by MasterKia** [comment] 2022-09-02 18:51
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by MasterKia** 2022-09-02 18:51 UTC
