### ISSUE TITLE
Upstream changes silently invalidate unbreak rules

### ISSUE THREAD

**Issue by jayvdb** [uBlockOrigin/uAssets#1511] opened 2018-02-09 04:38 UTC
When imported upstream changes include modifications to a `badfilter` rule, the `badfilter` rule is silently ignored.

https://github.com/uBlockOrigin/uAssets/issues/1510#issuecomment-364309886 explains the problem

The build should fail if there are `badfilter` rules which are discarded.

Either the rule is no longer needed, or the rule needs to be updated.

**Comment by okiehsch** [comment] 2018-02-09 05:08
> Either the rule is no longer needed, or the rule needs to be updated.

Why? Like I said https://github.com/uBlockOrigin/uAssets/issues/1510 is an extremely rare case.
Normally a filter that is clearly a "`badfilter`" won't get modified, at worst it never gets removed, which is the reason why the rule is needed.

**Comment by jayvdb** [comment] 2018-02-09 05:16
Otherwise regressions occur, as has been seen in #1510 .

Unfortunately when they are modified or removed, this is a maintenance task which needs to get done, and build errors ensure they are done to prevent regressions.

**Comment by okiehsch** [comment] 2018-02-09 05:25
By the way, you should open this issue at https://github.com/gorhill/uBlock/issues
This would have to be fixed in uBO proper and not in uAssets.

**Comment by jayvdb** [comment] 2018-02-09 05:58
It is a more generic solution if these regressions are caught in https://github.com/gorhill/uBlock , but that doesnt alter the fact that it is a regression in this project if this repository contains `badfilter` rules which are ignored.

**Comment by okiehsch** [comment] 2018-02-09 06:07
`uAssets`  is only used to add and removes filter rules which are used by the filtering engine in `uBlock`, there is no regression in `uAssets`, the `badfilter` option was [implemented](https://github.com/gorhill/uBlock/commit/a4e20ae3ad869a18f66eeb940273a625d342578e) in `uBlock`.

**Comment by jayvdb** [comment] 2018-02-09 06:58
If/when this repository imports a change from easylist that modifies a line with a `badfilter` that is in `unbreak.txt` , this repository will have another regression.

**Comment by okiehsch** [comment] 2018-02-09 07:09
There is no way to fix this issue, if @gorhill  decides to fix it, inside `uAssets`, the code implementing the `badfilter` rule is inside `uBlock`, of course the filter inside `uAssets` will become obsolete if easylist modifies a line with a badfilter, that does not mean that you can somehow prevent it from happening by changing **anything** inside `uAssets`

**Comment by gorhill** [comment] 2018-02-09 14:03
There is no "build" here, the filter lists are just edited as is --  `badfilter` is enforced in uBO itself. The import of external lists is just so that I can package them with the extension.

@okiehsch Could an exception filter be used instead?

    @@*$websocket,xmlhttprequest,domain=netlify.com

**Comment by okiehsch** [comment] 2018-02-09 19:36
> Could an exception filter be used instead?

I added your filter, this should solve most of the problems but sites that use third-party netlify requests could still have some breakage, so the badfilter-rule will have to be monitored until EasyPrivacy removes netlify.

**Closed** 2018-02-12 18:13 UTC
