### ISSUE TITLE
livescience.com, space.com

### ISSUE THREAD

**Issue by theswany** [uBlockOrigin/uAssets#8079] opened 2020-10-24 18:59 UTC
### URL(s) where the issue occurs
`www.livescience.com`
`www.space.com`

### Describe the issue

A full screen ad blocker message appears.

### Versions

- Browser/version: Chrome/Version 86.0.4240.111
- uBlock Origin version: uBlock Origin v1.30.6

### Settings

No changes made to the default settings.  

### Notes

Turning off JavaScript gets rid of the message in chrome but loses article pictures.  The website works in the most recent version of firefox.

**Comment by mapx-** [comment] 2020-10-24 20:30
It was fixed in easyprivacy. update your lists

**Closed by mapx-** 2020-10-24 20:30 UTC
Labels: unable to reproduce

**Comment by Trung0246** [comment] 2021-01-17 06:01
Apparently EasyPrivacy list is broken again with these site (like livescience, tomshardware,...).

However, I found the root cause which is this problematic obfuscated inline script:
![image](https://user-images.githubusercontent.com/11626920/104832408-b48c1880-5845-11eb-87a6-56809319d7ea.png)

I tried to write a tampermonkey script to prevent this by using Object.defineProperty but it doesn't work so far honestly (due to I'm being stupid 😅): https://gist.github.com/Trung0246/a2d55cc854acca2bb79adbc359037e9c

Any idea?
