### ISSUE TITLE
Comments on Facebook videos are gone.

### ISSUE THREAD

**Issue by Tokega** [uBlockOrigin/uAssets#822] opened 2017-11-09 12:47 UTC
Hi everybody.

### URL(s) where the issue occurs

Facebook.com

### Describe the issue

With comsetic filtering turned on, the comments and related videos section is blank.

### Screenshot(s)

https://i.imgur.com/MW0gdeB.png

### Versions

- Browser/version: Chrome version 61.0.3163.100
- uBlock Origin version: 1.14.16

### Settings

I have made no changes.

### Notes

N/A

**Comment by gorhill** [comment] 2017-11-13 12:12
Unable to reproduce. Closing due to lack of details provided.

**Closed by gorhill** 2017-11-13 12:12 UTC
Labels: unable to reproduce
