### ISSUE TITLE
oko.sh: detection

### ISSUE THREAD

**Issue by superjeng1** [uBlockOrigin/uAssets#17603] opened 2023-04-15 07:31 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://oko.sh/wnVX3R`

### Category

detection

### Description

A notice would appear and prevent access to the "Click here to continue" button.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="403" alt="image" src="https://user-images.githubusercontent.com/33928963/232195898-e383881f-cf82-42d1-ab03-01fe5f63dd41.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 89384
  cosmetic: 41174
  scriptlet: 20746
  html: 1112
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4900-4, 10h.20m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34577-258, 2d.22h.28m
    ublock-badware: 6614-0, 42m
    ublock-privacy: 352-0, 9d.2h.58m
    ublock-abuse: 78-0, 9d.2h.57m
    ublock-unbreak: 1997-2, 41m
    ublock-quick-fixes: 361-0, 4h.44m
    easylist: 64571-622, 12h.45m
    easyprivacy: 30814-1770, 12h.46m
    urlhaus-1: 7236-1, 4h.43m
    plowe-0: 3750-3, 6d.20h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
hostRuleset: 
  added: [array of 342 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 245 ms (selfie)
  maxAssetCacheWait: 53 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    arsnivyr.com: 2
    clk.sh: 1
    forfrogadiertor.com: 1
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    inklinkor.com: 1
    recaptcha.net: 1
    trustbummler.com: 1
```
</details>

**Comment by superjeng1** [comment] 2023-04-15 07:59
@okiehsch I still see the same anti-adblock message after purging all caches and update in uBlock.

**Comment by superjeng1** [comment] 2023-04-15 08:01
Can this issue be reopened? This issue isn't fixed yet.

**Comment by okiehsch** [comment] 2023-04-15 08:03
Hm, it works for me.

**Comment by okiehsch** [comment] 2023-04-15 08:04
Ok, my bad I testred with chromium and the fix works with it, for Firefox a different filter is needed.

**Comment by okiehsch** [comment] 2023-04-15 08:12
````
!#if env_firefox
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=oko.sh
!#endif
````

**Comment by superjeng1** [comment] 2023-04-15 08:19
It makes the message goes away, however after I click that "Click here to continue" button, the captcha seems broken.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/33928963/232200184-8b07b756-6436-4c2a-a42b-f39d84fd81ed.png">

**Comment by superjeng1** [comment] 2023-04-15 08:21
Interesting, when I open the page with your rules in a new Firefox profile, the captcha appears, but the Anti-Adblock message would appear again after like 5 secs.

**Comment by okiehsch** [comment] 2023-04-15 08:24
>  appear again after like 5 secs.

That should be fixed by my first filter, have you made sure that your filter list has been up to date with your new Firefox profile?

The captcha works fine on my end.
I will add the filter and reopen to see if anybody else can reproduce a broken captcha.

**Comment by superjeng1** [comment] 2023-04-15 08:26
I am sorry, in that new Firefox profile, I forgot to update the filter there, it works now. But I am trying to understand why does the captcha not work in my old Firefox profile.

**Comment by superjeng1** [comment] 2023-04-15 08:28
I am seeing this in my network tab, I think it is related to this.
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/33928963/232200772-4a1e412d-e9e9-430a-b45b-b4c0a62dbe08.png">

**Comment by okiehsch** [comment] 2023-04-15 08:29
Well, that seems to unrelated to uBO.

**Comment by superjeng1** [comment] 2023-04-15 08:31
Yup, it's not related. When I visit the page manually, Firefox tells me to restart Firefox to update Firefox. After that, it works. Thanks for your help!

**Closed** 2023-04-15 08:31 UTC
