### ISSUE TITLE
cdc.gov: breakage

### ISSUE THREAD

**Issue by cweagans** [uBlockOrigin/uAssets#14102] opened 2022-07-22 21:59 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cdc.gov/coronavirus/2019-ncov/science/forecasting/hospitalizations-forecasts.html`

### Category

breakage

### Describe the issue

The left sidebar navigation does not function with uBO enabled. It appears that uBO is (correctly) blocking calls to mtrics.cdc.gov, but in a way that causes the page navigation to fail.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![COVID-19 Forecasts: Hospitalizations | CDC 2022-07-22 15-57-27](https://user-images.githubusercontent.com/101590/180574070-5d130b2d-6956-44b3-9cdc-fbd280ac0876.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80149
  cosmetic: 44962
  scriptlet: 17450
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32926-46, 2h.9m
    ublock-badware: 4208-0, 2h.8m
    ublock-privacy: 240-0, 4d.19h
    ublock-abuse: 76-0, 4d.18h.59m
    ublock-unbreak: 1848-0, 2h.6m
    easylist: 68721-585, 2h.7m
    easyprivacy: 27434-580, 2h.10m
    urlhaus-1: 5312-0, 23h.11m
    plowe-0: 3640-3, 2h.11m
    ublock-quick-fixes: 248-0, 23h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 508 ms (selfie)
  maxAssetCacheWait: 440 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cdc.gov: 3
    google-analytics.com: 1
```
</details>

**Comment by Procyon-b** [comment] 2022-07-22 23:40
Try this filter:
```
cdc.gov##+js(set, window.s, undefined)
```

**Comment by cweagans** [comment] 2022-07-23 00:14
Works great!

**Comment by cweagans** [comment] 2022-07-23 00:15
(I also confirmed that there were no network requests to mtrics.cdc.gov after adding that filter)

**Comment by mhnestler** [comment] 2022-08-12 03:49
This fix broke another page entirely: `https://www.cdc.gov/vaccines/vpd/smallpox/hcp/vaccines.html` article content (which actually is an iframe inside that page) is blank. Disabling the `cdc.gov##+js(set, window.s, undefined)` filter fixes it. Although I did not do all the rigorous checks needed for filing a new issue, I encourage the person who created the filter to try it and re-evaluate.

**Comment by MasterKia** [comment] 2022-08-12 07:24
`||cdc.gov/JScript/metrics^` kills the calls to `metrics.cdc.gov/s.gif`.
`cdc.gov##+js(aeld, click, undefined)` solves the links navigation issue but then the collapse/expand buttons (+ -) won't work.

**Comment by Procyon-b** [comment] 2022-08-12 19:42
@MasterKia `aeld click` was my first attempt, but I also notice the unresponsive "+"
To fix the whole issue, allowing these 2 scripts works. And I haven't seen in the logger anything unusual not blocked
```
@@||cdc.gov/JScript/metrics/adobe/launch/*/AppMeasurement.min.js$script,1p
@@||cdc.gov/JScript/metrics/adobe/launch/*/AppMeasurement_Module_ActivityMap.min.js$script,1p
```

**Comment by stephenhawk8054** [comment] 2022-08-13 02:28
Hmm, I'm not sure why but the button `+` works fine for me.

**Comment by MasterKia** [comment] 2022-08-13 03:08
```
||cdc.gov/JScript/metrics^
@@||cdc.gov/JScript/metrics/adobe/launch/*/launch-*.min.js$script,1p
@@||cdc.gov/JScript/metrics/adobe/launch/*/AppMeasurement.min.js$script,1p
@@||cdc.gov/JScript/metrics/adobe/launch/*/AppMeasurement_Module_ActivityMap.min.js$script,1p
```

**Comment by Procyon-b** [comment] 2022-08-13 03:50
@stephenhawk8054 That's because there is no fix anymore: https://github.com/uBlockOrigin/uAssets/commit/b908a5113443de12c9c8ef3df1f1b0674f8d781e
We are back to the original problem: clicking on the menu (the one with the "+") does nothing.

@MasterKia do you need "@@...launch-" too for this to work?

**Comment by stephenhawk8054** [comment] 2022-08-13 03:52
> @stephenhawk8054 That's because there is no fix anymore: [b908a51](https://github.com/uBlockOrigin/uAssets/commit/b908a5113443de12c9c8ef3df1f1b0674f8d781e) We are back to the original problem: clicking on the menu (the one with the "+") does nothing.
> 
> @MasterKia do you need "@@...launch-" too for this to work?

Yeah, I mean I cannot reproduce the original problem (clicking on `+` button) any more. When I click on it, the menu dropdown appears as normal.

**Comment by Procyon-b** [comment] 2022-08-13 03:56
The original problem was clicking on the menu (not the +) doesn't open the document. Using `aeld click` solves the problem but then the "+" doesn't work (and other click events are disabled). My original fix was working until the "vaccines" page where the content is not loaded.

**Comment by MasterKia** [comment] 2022-08-13 04:00
https://github.com/uBlockOrigin/uAssets/issues/14102#issuecomment-1212702720

With `##+js(set, window.s, undefined)` when I right click on the frame and press "Reload frame" then it loads fine.

**Comment by stephenhawk8054** [comment] 2022-08-13 04:01
> The original problem was clicking on the menu (not the +) doesn't open the document. Using `aeld click` solves the problem but then the "+" doesn't work (and other click events are disabled). My original fix was working until the "vaccines" page where the content is not loaded.

Oh I see, I misunderstood. Yeah, your 2 exception filters work for me.

**Comment by MasterKia** [comment] 2022-08-13 04:02
@stephenhawk8054 is right; with `##+js(set, window.s, undefined)` the + buttons work fine.
But when I click on the links they don't work.

**Comment by MasterKia** [comment] 2022-08-13 04:03
> @MasterKia do you need "@@...launch-" too for this to work?

Yes, because I block `||cdc.gov/JScript/metrics^`.

**Comment by okiehsch** [comment] 2022-08-13 09:46
Is this now fixed or is something still not working?

**Comment by stephenhawk8054** [comment] 2022-08-13 09:48
I think both problems are fixed now.

**Closed** 2022-08-13 09:58 UTC
