### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by 6BEsYsd8TUrqB8z** [uBlockOrigin/uAssets#11968] opened 2022-02-28 21:35 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

they're still blocking me

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 91
filterset (summary): 
  network: 79858
  cosmetic: 41240
  scriptlet: 16472
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63882-9, 3d.6h.11m
    easyprivacy: 26620-121, 3d.6h.10m
    plowe-0: 3675-804, 11d.17h.59m
    ublock-abuse: 77-0, 3d.6h.9m
    ublock-badware: 4025-83, 3d.6h.8m
    ublock-filters: 30301-155, 3d.6h.7m
    ublock-privacy: 200-2, 3d.6h.6m
    ublock-unbreak: 1718-39, 3d.6h.4m
    urlhaus-1: 8437-0, 8h.3m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 22 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 17286 ms (selfie)
  maxAssetCacheWait: 1931 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google.com: 1
```
</details>

**Comment by Procyon-b** [comment] 2022-02-28 21:49
> they're still blocking me

What you mean by that? Do you get a message of some sort?

**Comment by iam-py-test** [comment] 2022-02-28 22:41
@6BEsYsd8TUrqB8z do not open duplicate issues just to complain about breakage. You already opened https://github.com/uBlockOrigin/uAssets/issues/11967

**Comment by gwarser** [comment] 2022-02-28 22:57
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11967

**Closed** 2022-02-28 22:57 UTC
