### ISSUE TITLE
HTTPS link to hphosts' ad & tracking servers

### ISSUE THREAD

**Issue by RacerDuke** [uBlockOrigin/uAssets#253] opened 2016-12-31 18:53 UTC
### URL(s) where the issue occurs

Not a major issue really, just an FYI that an HTTPS URL exists for the above mentioned filter list.
https://hosts-file.net/ad_servers.txt

### Describe the issue

The URL included with uBO is not using the secure link.

### Screenshot(s)

![image](https://cloud.githubusercontent.com/assets/11985548/21578863/9a186a12-cf5f-11e6-80cd-a7e2938a9cd3.png)

### Versions

- Browser/version: Waterfox/50.1.0
- uBlock Origin version: 1.10.5b5

### Settings

- Enabled the hphosts' ad and tracking servers list.

### Notes

Noticed the red HTTP label on this list, went to https://hosts-file.net/?s=Download to witness most if not all of their hosts file URLs utilize the HTTPS protocol. :)

**Comment by gorhill** [comment] 2016-12-31 19:04
Duplicate of <https://github.com/gorhill/uBlock/issues/1749>.

**Closed by gorhill** 2016-12-31 19:04 UTC

**Comment by RacerDuke** [comment] 2016-12-31 19:39
Whoops, sorry about that. Figured it was a uAssets issue. I'll be sure to check the main repo in the future. Wanted to thank you for the awesome work you do!
