### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Novato123ss** [uBlockOrigin/uAssets#18931] opened 2023-07-10 22:05 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Hr8SHApgr88`

### Category

detection

### Description

I cant use youtube cause it detects the adblocker

### Other extensions used

Return of youtube dislike button (I know for a fact this one is not the problem)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-07-10 at 16-05-28 Crina's Journey](https://github.com/uBlockOrigin/uAssets/assets/139180148/57cf5cf7-2b19-4d72-9f43-08baa38ec89a)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1h.48m
Firefox: 115
filterset (summary):
 network: 96736
 cosmetic: 39434
 scriptlet: 17912
 html: 991
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34768-65, 1h.48m
  ublock-badware: 7538-0, 1h.48m
  ublock-privacy: 469-0, 1h.48m
  ublock-unbreak: 2108-2, 1h.48m
  ublock-quick-fixes: 291-0, 1h.48m
  easylist: 67969-703, 1h.48m
  easyprivacy: 33417-727, 1h.48m
  urlhaus-1: 6426-1, 1h.48m
  plowe-0: 3739-2, 1h.47m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 140 ms (selfie)
 maxAssetCacheWait: 65 ms
popupPanel:
 blocked: 26
 network:
  youtube.com: 17
  doubleclick.net: 2
  google.com: 6
  google.com.mx: 1
 extended:
  ###player-ads
  ###masthead-ad
  ###merch-shelf
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by gorhill** [comment] 2023-07-10 22:15
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/7636>.

**Closed by gorhill** 2023-07-10 22:15 UTC
