### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Gregwashereandsayshi** [uBlockOrigin/uAssets#18010] opened 2023-05-10 00:18 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=L2btBQu7UCs`

### Category

ads

### Description

Ad audio and skip ad button are not being blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/133067152/a75fd0d4-b456-464c-b931-13714cfbca9e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 83590
 cosmetic: 30786
 scriptlet: 208
 html: 10
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 0-0, 1d.5h.14m
  ublock-badware: 6956-0, 1d.5h.14m
  ublock-privacy: 0-0, 1d.5h.14m
  ublock-abuse: 70-0, 1d.5h.14m
  ublock-unbreak: 2010-0, 1d.5h.13m
  ublock-quick-fixes: 209-1, 10h.54m
  easylist: 65879-176, 1d.5h.13m
  easyprivacy: 30899-1206, 1d.5h.13m
  urlhaus-1: 7286-1, 4h.26m
  plowe-0: 3746-942, 1d.5h.13m
filterset (user): [empty]
trustedset: 
 removed: 
  about-scheme
  moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 23608 ms
 maxAssetCacheWait: 2183 ms
popupPanel: 
 blocked: 76
 network: 
  youtube.com: 55
  doubleclick.net: 6
  google.com: 7
  googlesyndication.com: 6
  googlevideo.com: 2
 cosmetic: 
  ###player-ads
  ###masthead-ad
  ###merch-shelf
  ##.ad-showing > .html5-video-container
  ##.ytd-action-companion-ad-renderer
  ##.ytd-companion-slot-renderer
  ##.ytd-in-feed-ad-layout-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##a[href^=\"https://www.googleadservices.com/pagead/aclk?\"]
```
</details>

**Comment by gothic-bum** [comment] 2023-05-10 00:31
trustedset: 
     removed: 
       about-scheme
       moz-extension-scheme

Why did you remove these? These are default settings and are needed for uBO to function properly.
  
    supportStats: 
     allReadyAfter: 23608 ms

This indicates that it takes uBO over 28 seconds to be ready, when it should take no more than a second or two. So you may have a corrupted uBO installation or browser profile, and/or other browser extensions that are interfering with uBO.
  
Test again after you:
1. Create a new browser profile
2. Install uBO keeping everything at the default settings
3. Do not install any other browser extensions

**Comment by gorhill** [comment] 2023-05-10 00:32
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/7636>.

**Closed by gorhill** 2023-05-10 00:32 UTC
