### ISSUE TITLE
twitch.tv: [unknown]

### ISSUE THREAD

**Issue by warmaku** [uBlockOrigin/uAssets#23237] opened 2024-04-09 21:59 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/flats`

### Category

[unknown]

### Description

still getting ads

### Other extensions used

betterttv dark mode

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/a/Liw2WbJ
![ad proof](https://github.com/uBlockOrigin/uAssets/assets/166559381/c8168b7b-9bc6-412d-a7a3-8ed1162cfb2f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128511
 cosmetic: 45880
 scriptlet: 20335
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84554-546, 54m
  easyprivacy: 50464-831, 54m
  plowe-0: 3758-0, 54m
  ublock-badware: 8331-15, 54m
  ublock-filters: 37455-399, 54m
  ublock-privacy: 786-0, 54m
  ublock-quick-fixes: 133-0, 54m
  ublock-unbreak: 2240-0, 54m
  urlhaus-1: 8950-5, 54m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1306 ms
 maxAssetCacheWait: 319 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 96
 network:
  twitch.tv: 3
  amazon-adsystem.com: 8
  d2v02itv0y9u9t.cloudfront.net: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  mrmserve.com: 9
  scorecardresearch.com: 62
  sentry.io: 7
  serving-sys.com: 1
  ttvnw.net: 3
 extended:
  ##.stream-display-ad__wrapper
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by Oqarshi** [comment] 2024-04-09 23:22
try [TwitchAdSolutions](https://github.com/pixeltris/TwitchAdSolutions)

**Comment by gorhill** [comment] 2024-04-10 00:44
Duplicate of <https://github.com/uBlockOrigin/uAssets/issues/5184>.

**Closed by gorhill** 2024-04-10 00:44 UTC
