### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by RunawayVoices** [uBlockOrigin/uAssets#14380] opened 2022-08-12 23:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=86RL3kRbksQ&list=RDf6JD2sW6zvs&index=11`

### Category

ads

### Describe the issue

ads are playing on youtube again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80403
  cosmetic: 45255
  scriptlet: 17594
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69331-51, 23h.23m
    easyprivacy: 27324-123, 23h.27m
    plowe-0: 3634-776, 6d.20h.43m
    ublock-abuse: 76-0, 7d.20h.28m
    ublock-badware: 4176-92, 23h.26m
    ublock-filters: 32398-107, 23h.25m
    ublock-privacy: 230-3, 8d.8h.19m
    ublock-quick-fixes: 379-1, 19h.21m
    ublock-unbreak: 1855-43, 23h.24m
    urlhaus-1: 5213-0, 19h.22m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 189 ms (selfie)
  maxAssetCacheWait: 122 ms
popupPanel: 
  blocked: 471
  blockedDetails: 
    youtube.com: 420
    doubleclick.net: 6
    google.com: 13
    googleadservices.com: 8
    googlesyndication.com: 22
    googlevideo.com: 2
```
</details>

**Comment by Procyon-b** [comment] 2022-08-12 23:45
Try with "Suspend network activity until all filter lists are loaded" enabled in ublock's dashboard, "Filter lists" tab.

**Comment by MasterKia** [comment] 2022-08-13 03:14
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-13 03:14 UTC
