### ISSUE TITLE
9anime.to: detection

### ISSUE THREAD

**Issue by Abhigaruji** [uBlockOrigin/uAssets#10548] opened 2021-11-23 15:05 UTC
### URL address of the web page

`https://9anime.to/home`

### Category

detection

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 250554
  cosmetic: 210966
  scriptlet: 35154
  html: 703
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 27m
    https://raw.githubusercontent.com/Zelo72/adguard/main/d3host.adblock: 157-0, 1h.6m
    adguard-generic: 61599-5976, 1d.6h.14m
    adguard-spyware: 25750-1244, 1d.6h.56m
    adguard-spyware-url: 381-1, 1d.13h.42m
    block-lan: 44-0, 4d.3h
    adguard-annoyance: 47636-4577, 1d.6h.31m
    adguard-social: 14725-1078, 1d.7h.10m
    fanboy-thirdparty_social: 68-1, 6d.13h.45m
    fanboy-annoyance: 58844-47594, 6d.13h.47m
    fanboy-cookiemonster: 20335-12891, 7d.1h.17m
    fanboy-social: 23201-14051, 1d.7h.1m
    ublock-annoyances: 4315-12, 1d.9h.34m
    dpollock-0: 16965-1955, 23h.33m
    mvps-0: 8730-406, 23h.35m
    ara-0: 2309-232, 1h.54m
    BGR-0: 1116-19, 3d.14h.15m
    CHN-0: 26600-1098, 1d.6h.33m
    CZE-0: 772-44, 1h.46m
    DEU-0: 4938-372, 1h.44m
    EST-0: 443-10, 1h.40m
    FIN-0: 1471-74, 1d.4h.56m
    FRA-0: 25854-3779, 1d.6h.35m
    GRC-0: 1002-20, 2h.1m
    HUN-0: 2135-53, 1h.42m
    IDN-0: 8746-3602, 1d.9h.32m
    IRN-0: 1309-77, 1d.5h.3m
    ISL-0: 187-2, 3d.7h.31m
    ISR-0: 1641-6, 1h.19m
    ITA-0: 12521-475, 1h.21m
    ITA-1: 4995-294, 6d.1h.15m
    JPN-1: 5223-135, 1d.9h.30m
    KOR-1: 7917-577, 1d.9h.38m
    LTU-0: 1155-11, 6d.1h.17m
    LVA-0: 393-4, 1d.6h.37m
    NLD-0: 955-42, 1h.11m
    NOR-0: 2506-168, 1h.13m
    POL-0: 7679-158, 1h.48m
    POL-2: 1276-14, 23h.31m
    ROU-1: 753-29, 1h.50m
    RUS-0: 39947-1309, 23h.29m
    spa-0: 3302-226, 1h.17m
    spa-1: 4136-182, 1d.9h.28m
    SVN-0: 581-14, 1h.56m
    SWE-1: 3971-332, 1d.7h.12m
    THA-0: 982-3, 1h.52m
    TUR-0: 9244-262, 1d.7h.14m
    VIE-1: 2072-32, 35m
    curben-phishing: 23861-4, 1h.9m
    curben-pup: 365-0, 1h.58m
  default: 
    ublock-filters: 30372-574, 1d.5h.53m
    ublock-badware: 3424-2, 1d.5h.7m
    ublock-privacy: 154-1, 1d.5h.1m
    ublock-abuse: 67-0, 1d.4h.58m
    ublock-unbreak: 1706-0, 1d.4h.34m
    adguard-mobile: 6973-232, 1d.9h.36m
    easylist: 60950-24612, 1d.4h.32m
    easyprivacy: 26273-11437, 1d.4h.28m
    urlhaus-1: 9292-3, 1h.15m
    plowe-0: 3685-43, 8d.4h.6m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 8 redacted]
  triggered: 
    no-remote-fonts: * true
    no-remote-fonts: 9anime.to false
modifiedUserSettings: 
  cloudStorageEnabled: true
  firewallPaneMinimized: false
  largeMediaSize: 51
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2970
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment] 2021-11-23 15:10
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/10547

**Closed by uBlock-user** 2021-11-23 15:10 UTC
