### ISSUE TITLE
Brainly.in Site breaking using ublockOrgin

### ISSUE THREAD

**Issue by Legendofallpro** [uBlockOrigin/uAssets#9421] opened 2021-06-12 14:38 UTC
### Prerequisites

- [ No] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ Yes] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [Yes] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ Yes] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://brainly.in/`

### Describe the issue

Site is breaking when using the extension and doesn't break when the extension has been turned off.

![image](https://user-images.githubusercontent.com/85796039/121779374-f5037e80-cbb8-11eb-8fe4-aea586be1c9a.png)

Is not breaking when the Extension has been turned off as seen above in the screenshot
### Screenshot(s)

![image](https://user-images.githubusercontent.com/85796039/121779077-8a9e0e80-cbb7-11eb-8f6b-9390f82a4c62.png)

Site is breaking when Extension is Enabled

### Versions

- Browser/version: [ Google Chrome: 91.0.4472.77]
- uBlock Origin version: [1.35.2]

### Settings

I have made no changes to any of its default settings

### Notes

Maybe because of this?
![image](https://user-images.githubusercontent.com/85796039/121779550-e2d61000-cbb9-11eb-8e6c-815910e75b4f.png)

And this happens only if u have logged in with an account...

**Comment by iam-py-test** [comment] 2021-06-13 11:54
@Legendofallpro does the site work when adding `@@||brainly.in/cdn-cgi/apps/head$script` to the my filters tab?

**Comment by iam-py-test** [comment] 2021-06-13 11:58
@Legendofallpro this is an issue with EasyPrivacy:
```
! cloudflare tracking
/cdn-cgi/apps/body/*$script,~third-party
/cdn-cgi/apps/head/*$script,~third-party
```
You might want to report it here: https://github.com/easylist/easylist/issues

**Comment by uBlock-user** [comment] 2021-06-13 12:05
@iam-py-test Which filter causes the issue is yet to be determined, do not offer suggestions based on OP's assumptions.

**Comment by Legendofallpro** [comment] 2021-06-13 12:15
So cause is not determined yet guys?

**Comment by uBlock-user** [comment] 2021-06-13 12:16
fixed in https://github.com/uBlockOrigin/uAssets/commit/bc829f4070aa1a5c3d21a03f5bd9af689d7b544b

**Closed** 2021-06-13 12:16 UTC
Labels: account required

**Comment by Legendofallpro** [comment] 2021-06-13 12:19
so what do i have to do anything to fix it?

**Comment by Legendofallpro** [comment] 2021-06-13 12:20
because its till the same
![image](https://user-images.githubusercontent.com/85796039/121806985-cdbbb880-cc6f-11eb-8545-25b116d15c66.png)

**Comment by iam-py-test** [comment] 2021-06-13 12:20
@Legendofallpro force update your lists

**Comment by iam-py-test** [comment] 2021-06-13 12:20
Click Purge All Caches on the Filters tab

**Comment by Legendofallpro** [comment] 2021-06-13 12:22
Ohk, works now, everything is working  all right
Thanks guys :)
![image](https://user-images.githubusercontent.com/85796039/121807059-2b500500-cc70-11eb-80b9-6d04eeae8b71.png)
