### ISSUE TITLE
iqiyi.com: ads

### ISSUE THREAD

**Issue by h573767859** [uBlockOrigin/uAssets#20239] opened 2023-10-23 13:12 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.iqiyi.com/v_2emrhbfqc4s.html?vfrm=pcw_dongman&vfrmblk=fcs_4&vfrmrst=fcs_4_p12`

### Category

ads

### Description

Video ads cannot be blocked

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
AdBlock Max - 广告拦截器: 1.0.11
Chromium: 114
filterset (summary): 
 network: 119666
 cosmetic: 50476
 scriptlet: 18959
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 24-1, never
  CHN-0: 25253-134, 2d.4h.31m
  easylist: 71974-25, 3d.13h.47m
  easyprivacy: 33104-77, 21h.40m
  plowe-0: 3729-1072, 7d.16h.46m
  ublock-badware: 7263-132, 21h.39m
  ublock-filters: 35111-161, 21h.36m
  ublock-privacy: 552-6, 4d.40m
  ublock-quick-fixes: 236-86, 23m
  ublock-unbreak: 2130-34, 21h.38m
  urlhaus-1: 11600-0, 21h.35m
filterset (user): [array of 24 redacted]
trustedset: 
 added: [array of 26 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2408 ms (selfie)
 maxAssetCacheWait: 192 ms
popupPanel: 
 blocked: 146
 network: 
  iqiyi.com: 12
  bdstatic.com: 1
  hypers.com.cn: 1
  ipinyou.com: 1
  miaozhen.com: 11
  qy.net: 111
  reachmax.cn: 5
  tmall.com: 2
  xelements.cn: 2
 cosmetic: 
  ##.cupid-panel + div
  ##.qy-plist-ad
  ##:not(.qy-index-page) > div[id^=\"100000\"]
  ##.black-screen[data-cupid=\"adblock-blackscreen\"]
```
</details>

**Comment by gorhill** [comment] 2023-10-23 13:57
Works?

    iqiyi.com##+js(set, QiyiPlayerProphetData.a.data, {})

**Comment by gorhill** [comment] 2023-10-23 13:58
It's a duplicate of <https://github.com/uBlockOrigin/uAssets/issues/20171> but this time I let the ad play, and it took a while but eventually  what seems like to be the content started to play.

**Comment by mapx-** [comment] 2023-10-23 14:16
however OP is using some uBO clone ?!
`AdBlock Max - 1.0.11`

**Comment by gwarser** [comment] 2023-10-23 15:15
@h573767859 are you using Yandex browser? Someone asked on Reddit about broken popup on mobile in Yandex with this add-on https://www.reddit.com/r/uBlockOrigin/comments/17ed2ak/when_popup_windows_of_adblock_max_opened_in/

**Comment by gorhill** [comment] 2023-10-23 15:45
Should close once it's fixed in regional list, just to confirm it's not forgotten.

**Comment by Alex-302** [comment] 2023-10-23 15:56
We have the working rules in AdGuard Popups/Annoyances filter (don't ask why **:harold.jpg:**).

**Closed** 2023-10-23 16:19 UTC
Labels: to be fixed by regional list

**Comment by stephenhawk8054** [comment] 2023-10-24 02:38
Didn't know they have that regulation 👀

**Comment by gorhill** [comment] 2023-10-24 03:21
Forgot about this, I think webstores including AMO are forbidden to host uBO. Don't know about other blockers.
