### ISSUE TITLE
music.youtube.com: ads

### ISSUE THREAD

**Issue by JetyWawoo** [uBlockOrigin/uAssets#13788] opened 2022-06-20 16:52 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://music.youtube.com/watch?v=GWVP4mDfKNA&list=OLAK5uy_n4XNf4ZQFHHLRPSA08MF98YjNyLhY613M`

### Category

ads

### Describe the issue

I am getting ads all the time on the **YouTube Music Web App** via Edge. I have it set to launch on startup. Before you ask, I did everything here:  [Youtube Issues · easylist/easylist Wiki · GitHub](https://github.com/easylist/easylist/wiki/Youtube-Issues). I cleared caches, turned off hardware acceleration, disabled other extensions, reinstalled UBlockOrigin, kept the default filters and added all the filters, updated the filters, all of it.

Seems to be the same issue as [#12747](https://github.com/uBlockOrigin/uAssets/issues/12747#issue-1204485440)

I did notice that when I hit "open in Microsoft Edge", refresh the page, and launch the web app again they seem to stop. However, if I close the app (with Edge also closed) and launch it again I start getting ads again and I have to repeat the process.
It seems like Edge has to be opened before you can launch the Web App, or else you will get ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/69184142/174647875-b1274206-c3db-4ac6-a02b-e11d5a001e1b.png)
![image](https://user-images.githubusercontent.com/69184142/174648360-da0e287f-83f6-4451-9bc0-58917ed003e7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 167046
  cosmetic: 206274
  scriptlet: 36687
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 3d.13h.45m
    adguard-annoyance: 54148-117, 3d.13h.45m
    adguard-generic: 64857-700, 3d.13h.45m
    adguard-mobile: 7862-102, 3d.13h.45m
    adguard-social: 17671-870, 3d.13h.45m
    adguard-spyware: 26152-1097, 3d.13h.45m
    adguard-spyware-url: 633-13, 3d.13h.45m
    block-lan: 43-0, 3d.13h.45m
    curben-phishing: 20303-0, 1h.9m
    curben-pup: 231-0, 1h.8m
    dpollock-0: 10375-1456, 3d.13h.45m
    fanboy-annoyance: 73501-4192, 3d.13h.45m
    fanboy-cookiemonster: 34505-34505, 3d.13h.45m
    fanboy-social: 23264-23263, 3d.13h.45m
    fanboy-thirdparty_social: 69-21, 3d.13h.45m
    ublock-annoyances: 4458-223, 3d.13h.45m
  default: 
    user-filters: 16-0, never
    easylist: 68467-1310, 3d.13h.45m
    easyprivacy: 27225-10406, 3d.13h.45m
    plowe-0: 3648-1464, 3d.13h.45m
    ublock-abuse: 75-0, 3d.13h.45m
    ublock-badware: 4158-319, 3d.13h.45m
    ublock-filters: 31800-3714, 3d.13h.45m
    ublock-privacy: 224-48, 3d.13h.45m
    ublock-quick-fixes: 204-15, 1h.7m
    ublock-unbreak: 1802-100, 3d.13h.45m
    urlhaus-1: 9732-1, 1h.6m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 388 ms (selfie)
  maxAssetCacheWait: 316 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    youtube.com: 22
    doubleclick.net: 3
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment] 2022-06-20 18:43
In ublock's dashboard, "Filter lists" tab, have you checked "Suspend network activity until all filter lists are loaded" ?

**Comment by JetyWawoo** [comment] 2022-06-20 19:12
That seems to have fixed the issue. Thanks.

**Comment by WaWi** [comment] 2022-06-24 02:12
I have the same issue with chrome. before, the blocking was working fine

ideally the adblocking on youtube music should work with default settings for non-technical users to also be able to profit

**Comment by JetyWawoo** [comment] 2022-06-25 00:04
Actually, it seems that "Suspend network activity" did not fix the issue. Still getting ads.

**Comment by mapx-** [comment] 2022-06-25 04:35
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by mapx-** 2022-06-25 04:35 UTC

**Comment by JetyWawoo** [comment] 2023-08-08 04:28
Solution:
Enable "Startup boost" in the Edge settings, along with "Suspend network activity until all filter lists are loaded" checked. "Continue running background extensions and apps when Microsoft edge is closed" is probably a good idea too.
