### ISSUE TITLE
webtoons.com: nuisance

### ISSUE THREAD

**Issue by T1MM5H** [uBlockOrigin/uAssets#22387] opened 2024-02-08 01:28 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.webtoons.com/`

### Category

nuisance

### Description

Will redirect to login screen with a JavaScript, upon opening, despite technically delivering content beforehand. Please judge if this is a paywall issue or nuisance, i am not aware of precedence.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 120
filterset (summary):
 network: 116896
 cosmetic: 36964
 scriptlet: 18983
 html: 2084
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37988-384, now
  ublock-badware: 7847-14, now
  ublock-privacy: 995-1, now
  ublock-unbreak: 2259-1, now
  adguard-mobile: 9050-133, now
  easylist: 80353-16594, now
  easyprivacy: 43342-849, now
  urlhaus-1: 7240-0, now
  plowe-0: 3785-1, now
  ublock-quick-fixes: 193-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1114 ms (selfie)
 maxAssetCacheWait: 467 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, ccsrv, )
  ##+js(set-constant, lcs_SerName, )
```
</details>

**Comment by ItsProfessional** [comment] 2024-02-08 05:36
Unable to reproduce. Regardless, this is out of scope.

**Closed** 2024-02-08 05:36 UTC
Labels: invalid, unable to reproduce
