### ISSUE TITLE
[nsfw] eio.io: detection

### ISSUE THREAD

**Issue by shawon2901** [uBlockOrigin/uAssets#14132] opened 2022-07-25 17:31 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eio.io/0jfD`

### Category

detection

### Describe the issue

AdBlock Is Detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 104
filterset (summary): 
  network: 121945
  cosmetic: 65819
  scriptlet: 19007
  html: 711
listset (total-discarded, last updated): 
  added: 
    curben-phishing: 28607-1, 1d.17h.32m
    fanboy-annoyance: 75722-33949, 2d.19h.11m
    IND-0: 11083-1, 1d.17h.33m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33038-308, 2d.6h.19m
    ublock-badware: 4207-0, 2d.6h.18m
    ublock-privacy: 240-1, 2d.6h.17m
    ublock-abuse: 76-0, 2d.6h.16m
    ublock-unbreak: 1853-0, 1d.22h
    ublock-quick-fixes: 249-0, 1d.21h.59m
    adguard-mobile: 7978-167, 2d.19h.11m
    easylist: 68753-25062, 1d.21h.58m
    easyprivacy: 27435-590, 1d.21h.57m
    urlhaus-1: 4853-0, 1d.21h.56m
    plowe-0: 3640-3, 1d.21h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 556 ms (selfie)
  maxAssetCacheWait: 238 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    eio.io: 14
    cloudflare.com: 1
    exe.io: 3
    google.com: 1
    googletagmanager.com: 1
    recaptcha.net: 2
```
</details>

**Comment by okiehsch** [comment] 2022-07-25 17:39
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14114
Already fixed update your filter lists.

**Closed by okiehsch** 2022-07-25 17:39 UTC
