### ISSUE TITLE
investing.com: nuisance

### ISSUE THREAD

**Issue by YodarTrading** [uBlockOrigin/uAssets#12848] opened 2022-04-19 13:01 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.investing.com/currencies/usd-jpy`

### Category

nuisance

### Describe the issue

There is an anti-adblock overlay that blocks access to the site. Please do not close this if not fixed. It makes the use of the website impossible. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 80381
  cosmetic: 42414
  scriptlet: 16434
  html: 637
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31132-28, 1d.20h.51m
    ublock-badware: 4081-3, 1d.20h.50m
    ublock-privacy: 211-0, 8d.20h.48m
    ublock-abuse: 74-0, 8d.7h.2m
    ublock-unbreak: 1772-0, 1d.20h.49m
    easylist: 65991-591, 1d.20h.48m
    easyprivacy: 26839-591, 6h.38m
    urlhaus-1: 7454-0, 21m
    plowe-0: 3684-2, 10d.20h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1270 ms (selfie)
  maxAssetCacheWait: 748 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    investing.com: 1
    cloudflareinsights.com: 1
    doubleclick.net: 1
    facebook.net: 1
    googletagmanager.com: 2
    hotjar.com: 1
    httpschecker.net: 1
    primis.tech: 1
```
</details>

**Comment by okiehsch** [comment] 2022-04-19 13:08
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/12831

Try the filters proposed at the end of the discussion.

**Closed by okiehsch** 2022-04-19 13:08 UTC
