### ISSUE TITLE
youtube.com: ads 

### ISSUE THREAD

**Issue by LOTHMH** [uBlockOrigin/uAssets#14182] opened 2022-07-31 13:23 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=2B-u8KMochE`

### Category

ads

### Describe the issue

Most Videos show starts of ads and then stop showing them after 1s. Happens to every Youtube Video and not just this one lately. I'm using OperaGX, tried reinstalling and it doesnt work. 

Also yes I disabled OperaGXs in-browser adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79858
  cosmetic: 45056
  scriptlet: 17521
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68901-51, 1d.16h.57m
    easyprivacy: 27459-123, 1d.16h.56m
    plowe-0: 3640-779, 5d.20h.32m
    ublock-abuse: 76-0, 5d.20h.30m
    ublock-badware: 4221-92, 1d.16h.55m
    ublock-filters: 32301-114, 1d.16h.54m
    ublock-privacy: 225-3, 5d.20h.26m
    ublock-quick-fixes: 291-10, 19h.55m
    ublock-unbreak: 1851-42, 1d.16h.53m
    urlhaus-1: 4852-0, 19h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 335 ms (selfie)
  maxAssetCacheWait: 143 ms
popupPanel: 
  blocked: 628
  blockedDetails: 
    youtube.com: 538
    doubleclick.net: 1
    google.com: 49
    googlevideo.com: 35
    sentry.io: 5
```
</details>

**Comment by MasterKia** [comment] 2022-07-31 14:10
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/Youtube-Issues

**Closed** 2022-07-31 15:49 UTC
