### ISSUE TITLE
youtube.com: ads on opera youtube

### ISSUE THREAD

**Issue by HockeyTips** [uBlockOrigin/uAssets#14062] opened 2022-07-18 09:06 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

On YouTube Website, while using the extension on Opera GX, YouTube is getting ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 79713
  cosmetic: 44610
  scriptlet: 17418
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 9h
  default: 
    user-filters: 0-0, never
    easylist: 68470-51, 9h.2m
    easyprivacy: 27423-123, 9h.1m
    plowe-0: 3644-780, 9h.8m
    ublock-abuse: 76-0, 9h.7m
    ublock-badware: 4224-95, 9h.5m
    ublock-filters: 32209-110, 9h.4m
    ublock-privacy: 226-3, 9h.6m
    ublock-unbreak: 1836-42, 9h.3m
    urlhaus-1: 5006-0, 8h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 933 ms (selfie)
  maxAssetCacheWait: 424 ms
popupPanel: 
  blocked: 1349
  blockedDetails: 
    youtube.com: 1267
    doubleclick.net: 12
    googleadservices.com: 9
    googlesyndication.com: 61
```
</details>

**Comment by krystian3w** [comment] 2022-07-18 10:18
Duplicate of #7636

**Comment by krystian3w** [comment] 2022-07-18 10:19
EasyList propostion to defend pre/mid roll ads in player: https://github.com/easylist/easylist/wiki/Youtube-Issues

**Closed** 2022-07-18 10:21 UTC
Labels: duplicate
