### ISSUE TITLE
Android 11 - Firefox mobile - New youtube ads under video are not being blocked

### ISSUE THREAD

**Issue by Candlemass** [uBlockOrigin/uAssets#11711] opened 2022-02-13 06:54 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Occurs on almost all videos.

### Describe the issue

Massive ad under the player when a video is being watched isn't being blocked.

### Screenshot(s)

https://i.postimg.cc/XJbcfTk7/Screenshot.png

### uBlock Origin version

1.41.2

### Browser name and version

Android 11 - Firefox 68.8

### Settings

https://i.postimg.cc/X784tZS6/Screenshot-20220212-233457-Firefox.png
https://i.postimg.cc/K8pFvd89/Screenshot-20220212-233514-Firefox.png
https://i.postimg.cc/hGJnJpJK/Screenshot-20220212-233554-Firefox.png
https://i.postimg.cc/FK2403c3/Screenshot-20220212-233622-Firefox.png
https://i.postimg.cc/1XS1jSvz/Screenshot-20220212-233630-Firefox.png

### Notes

I tried on an older device running Android 7 with Firefox 68.0 - UBlock Origin 1.35.2 with all the same settings and the problem does not occur

**Comment by uBlock-user** [comment] 2022-02-13 07:17
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed** 2022-02-13 09:02 UTC

**Comment by Yuki2718** [comment] 2022-02-13 09:03
It is NOT support forum here. Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).

**Comment by uBlock-user** [comment] 2022-02-13 09:13
> The cosnetic filter took care of the problem.

>* - [X] uBO with default lists/settings

You certainly didn't test with default lists/settings otherwise you wouldn't be having this issue in the first place.

**Comment by uBlock-user** [comment] 2022-02-13 09:14
> The cosnetic filter took care of the problem.

>* [X] uBO with default lists/settings

You certainly didn't test with default lists/settings otherwise you wouldn't be having this issue in the first place.

**Comment by Candlemass** [comment] 2022-02-13 12:38
@Yuki2718

Sorry but ever since reddit started allowing their advertisers to choose to censor content on the platform I no longer use that service.

**Comment by Candlemass** [comment] 2022-02-13 23:14
@krystian3w

Doesn't matter. The platform has a putrid stain on it's reputation for allowing advertisers to choose the narrative by censoring speech they don't agree with and by utilizing it you're supporting that.

There's also no guarantee that simply because you have ads disabled on your sub that it makes a difference.

**Comment by iam-py-test** [comment] 2022-02-13 23:29
Maybe a separate repo just for support questions should be created, as there are certainly many people who do not want to create a Reddit account

**Comment by uBlock-user** [comment] 2022-02-14 06:20
> Doesn't matter. The platform has a putrid stain on it's reputation for allowing advertisers to choose the narrative by censoring speech they don't agree with and by utilizing it you're supporting that.

That doesn't give you the excuse to start asking questions here, regardless of what you think of reddit, there are no exceptions to the rule.
