### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by RTV0073** [uBlockOrigin/uAssets#14223] opened 2022-08-03 02:53 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=WX9TRNmrth8`

### Category

breakage

### Describe the issue

When I click on this link, it just spins without displaying any video at all. This problem has started occurring intermittently on other links as well.  The problem does not occur when I diasable Ublock Origin. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 110706
  cosmetic: 153321
  scriptlet: 36941
  html: 721
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 66475-5642, 5m
    adguard-mobile: 8031-167, 5m
    adguard-annoyance: 55512-4791, 11m
    adguard-social: 18066-1652, 5m
    fanboy-thirdparty_social: 69-1, 5m
    fanboy-annoyance: 77508-65871, 11m
    fanboy-cookiemonster: 38344-16554, 11m
    fanboy-social: 23253-13666, 5m
    ublock-annoyances: 4523-7, 11m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33083-319, 11m
    ublock-badware: 4175-0, 11m
    ublock-privacy: 246-1, 11m
    ublock-abuse: 76-0, 11m
    ublock-unbreak: 1864-0, 11m
    easylist: 69064-25100, 11m
    easyprivacy: 27478-594, 11m
    plowe-0: 3640-3, 11m
    urlhaus-1: 4861-0, 11m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 24 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 769 ms (selfie)
  maxAssetCacheWait: 234 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    youtube.com: 11
    doubleclick.net: 3
    google.com: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-03 05:13
> - [X] I verified that the issue has not already been reported (use this button to find out)
> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> added: 
    adguard-generic: 66475-5642, 5m
    adguard-mobile: 8031-167, 5m
    adguard-annoyance: 55512-4791, 11m
    adguard-social: 18066-1652, 5m
    fanboy-thirdparty_social: 69-1, 5m
    fanboy-annoyance: 77508-65871, 11m
    fanboy-cookiemonster: 38344-16554, 11m
    fanboy-social: 23253-13666, 5m
    ublock-annoyances: 4523-7, 11m

Please read and follow the prerequisites carefully and truthfully instead of _**blindly ticking them**_.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues


Also disable all the extra filterlists and test with _**only the default filterlists**_.

**Comment by MasterKia** [comment] 2022-08-03 05:14
You don't need to enable "adguard-mobile" on a PC.

**Closed** 2022-08-03 05:58 UTC

**Comment by RTV0073** [comment] 2022-08-03 13:10
My apologies. I am not very knowledgeable about this stuff.  I did click on the button that popped up when for previously reported problems, but nothing showed up when I did that, so I assumed that I was okay. I must have done that wrong. I did not know that "default filterlists" is labeled "built in" in the ublock origins settings. I thought that all of the filters displayed were the defaults.  Wrong again.  Unchecking all filters except the ones labeled "built in" fixed the problem. Once again I apologize for wasting everyone's time. I'll go away now. 

    On Wednesday, August 3, 2022 at 12:13:21 AM CDT, MasterKia ***@***.***> wrote:  
 
 


   
   -  I verified that the issue has not already been reported (use this button to find out)
   -  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists



added:
adguard-generic: 66475-5642, 5m
adguard-mobile: 8031-167, 5m
adguard-annoyance: 55512-4791, 11m
adguard-social: 18066-1652, 5m
fanboy-thirdparty_social: 69-1, 5m
fanboy-annoyance: 77508-65871, 11m
fanboy-cookiemonster: 38344-16554, 11m
fanboy-social: 23253-13666, 5m
ublock-annoyances: 4523-7, 11m


Please read and follow the prerequisites carefully and truthfully instead of blindly ticking them.

Duplicate of #7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

Also disable all the extra filterlists and test with only the default filterlists.

**Comment by frshhh** [comment] 2022-08-03 21:48
Experiencing the same issue on _some_ videos. The issue started yesterday for me. 

- Tried disabling extra filterlists
- Tried creating a new Firefox profile with a fresh install of uBlock Origin
By disabling uBlock, and watching the ads, the video plays fine.

**Comment by MasterKia** [comment] 2022-08-04 02:27
@frshhh 

Go to https://github.com/uBlockOrigin/uAssets/issues/7636

Also see: https://github.com/easylist/easylist/wiki/youtube-issues
