### ISSUE TITLE
na.se: nuisance

### ISSUE THREAD

**Issue by LinAGKar** [uBlockOrigin/uAssets#12090] opened 2022-03-07 23:14 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.na.se/2022-03-07/sveriges-radio-direktsander-fran-nittalvsdalen-under-8-timmar-vi-vill-ge-lyssnarna-nagot-annat-att-tanka-pa-an-krig-och-pandemi`

### Category

nuisance

### Describe the issue

When EasyList is enabled, extra spacing is introduced in some points of articles. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220308-001101](https://user-images.githubusercontent.com/3390621/157133986-551eee5e-fd71-4b2a-8f86-77485a7aef8b.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 97
filterset (summary): 
  network: 82921
  cosmetic: 25164
  scriptlet: 16699
  html: 675
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    ublock-filters: 30871-264, 9m
    ublock-badware: 3955-3, 9m
    ublock-privacy: 206-1, 9m
    ublock-abuse: 72-0, 9m
    ublock-unbreak: 1737-0, 8m
    adguard-mobile: 7310-169, 5m
    easylist: 64349-24292, 8m
    easyprivacy: 26652-583, 8m
    urlhaus-1: 8437-0, 8m
    plowe-0: 3674-2, 8m
    SWE-1: 3996-332, 5m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2028 ms (selfie)
  maxAssetCacheWait: 1008 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    bonad.io: 1
    codigo.se: 1
    googletagmanager.com: 1
    myvisitors.se: 2
    rubiconproject.com: 1
```
</details>

**Comment by PerfectSalad** [comment] 2022-03-07 23:32
To be addressed in regional list - https://github.com/lassekongo83/Frellwits-filter-lists
@lassekongo83

**Closed** 2022-03-08 06:17 UTC
Labels: to be fixed by regional list

**Comment by lassekongo83** [comment] 2022-03-08 06:29
Unable to reproduce. Make sure cosmetic filtering isn't deactivated.

Otherwise it's possible I can't reproduce because of paywall.

**Comment by LinAGKar** [comment] 2022-03-08 09:05
Yes, sorry, that one is paywalled. Here is a non-paywalled example: https://www.na.se/2022-03-08/sa-ska-pensionarer-fa-kunskap-och-kraft-att-genomskada-bedragare

And yes, it does seem like it only happens when "Ignore generic cosmetic filters" is checked, which seems to be default on phones.

**Comment by mapx-** [comment] 2022-03-08 09:18
- no such PH an android maybe I don't see them because all the articles should be not-paywalled 
- on desktop on the right side:

`na.se##.article__outsider:has(.ad)`
