### ISSUE TITLE
sevenjournals.com: detection

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#10777] opened 2021-12-06 17:55 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://sevenjournals.com/morskoye-sushchestvo-pokhozheye-golubogo-drakona/`

### Category

detection

### Describe the issue

Website detects uBO, but not detects when visiting directly, only when visiting from adbtc.top with shortlink. Account required.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![OnPaste 20211206-215158](https://user-images.githubusercontent.com/79659024/144896962-d7435e42-fb1f-4892-8f7c-617d1acb98cd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78587
  cosmetic: 39395
  scriptlet: 16204
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30414-30, 55m
    ublock-badware: 3513-1, 55m
    ublock-privacy: 188-0, 55m
    ublock-abuse: 72-0, 55m
    ublock-unbreak: 1716-0, 55m
    easylist: 61281-551, 55m
    easyprivacy: 26438-474, 55m
    urlhaus-1: 8674-0, 55m
    plowe-0: 3697-3, 55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1238
  launchFromSelfie: false
popupPanel: 
  blocked: 42
```
</details>

**Comment by gorhill** [comment] 2021-12-06 18:18
You need to enable _"RUS: RU AdList"_ for web sites in Russian -- and if it still occurs, this should be fixed in that list. cc @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment] 2021-12-06 18:35
The problem is solved with: `sevenjournals.com##+js(abort-on-property-read, absda)`

However, I'm not sure if this rule needs to be added to RU AdList. It looks like this article is the only one in Russian.

**Comment by gorhill** [comment] 2021-12-06 18:37
I didn't realize this, so we should fix it in uBO's lists.

**Comment by datoshkr** [comment] 2021-12-06 18:59
Not fixed with RU AdList, nor sevenjournals.com##+js(abort-on-property-read, absda)

**Comment by uBlock-user** [comment] 2021-12-06 19:04
> from adbtc.top with shortlink

You didn't report the original link in the OP.

**Comment by datoshkr** [comment] 2021-12-06 19:12
Fixed when cosmetic filtering is disabled for this website...

**Comment by mapx-** [comment] 2021-12-06 19:25
@datoshkr  

> adbtc.top with shortlink
?

**Comment by datoshkr** [comment] 2021-12-06 19:33
> @datoshkr
> 
> > adbtc.top with shortlink
> 
> ?

Need account on [https://adbtc.top/](url) and visit "birdurls.com" shortlink from [https://adbtc.top/shortlink/](url) page, it redirects to "sevenjournals.com"

![OnPaste 20211206-233104](https://user-images.githubusercontent.com/79659024/144910100-9c2ff73c-6833-41f7-8d16-83a8ce48e15b.png)

**Comment by No-ADS** [comment] 2021-12-06 20:32
@datoshkr 
Add `sevenjournals.com##+js(nobab)` or `sevenjournals.com#@##banner_ad`


<details>

![2021-12-06_223213](https://user-images.githubusercontent.com/94611448/144918133-a9445895-c0ec-48e7-8358-21ba8df578d7.png)
<summary>Code</summary>
</details>

**Comment by datoshkr** [comment] 2021-12-06 20:39
> @datoshkr Add `sevenjournals.com##+js(nobab)` or `sevenjournals.com#@##banner_ad`
> Code

Both works

**Comment by No-ADS** [comment] 2021-12-06 20:59
@dimisa-RUAdList 
> However, I'm not sure if this rule needs to be added to RU AdList. It looks like this article is the only one in Russian.

`https://sevenjournals.com/page/25/` ././ -> /page/43/

**Comment by LikesHisComputer** [comment] 2021-12-06 22:01
![image](https://user-images.githubusercontent.com/95556652/144929784-bbd405d0-0e03-4485-bcfa-0271e9769027.png)

**Comment by LikesHisComputer** [comment] 2021-12-06 23:04
@datoshkr is there any name for services like `adbtc`? like, with URL shorteners? do you know any other similar services?

**Closed** 2021-12-06 23:35 UTC
Labels: account required

**Comment by datoshkr** [comment] 2021-12-07 05:24
> @datoshkr is there any name for services like `adbtc`? like, with URL monetizers ? do you know any other similar services?

I don't know correct name for websites like adbtc, but there is many websites which pays you some cryptocurrency for doing tasks, visiting shortlinks, viewing ads... We can talk about this with email, telegram, signal...
