### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by Nerva72** [uBlockOrigin/uAssets#12199] opened 2022-03-12 18:47 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Describe the issue

I am running uBlock 1.41.8 on Chrome 99.0.4844.51 (x64) on Windows 7 x64.

On Reddit, prior to logging-in, if I go to the login screen, normally on Chrome, when I click on the login field, Chrome inserts a drop-down of all logins for Reddit that are saved in Chrome, from which one can be selected to autofill the login and password.   But instead, the field is "locked" with the last login that was used -- if I try to click on it, I can't even edit what is shown in the field.

I played around with disabling individual lists in uBlock, and discovered some of them didn't trigger the problem, while others did.   The ones that caused the problem (if any one of them were enabled) were "My filters", "uBlock filters", "uBlock filters - Badware risks", "uBlock filters - Privacy", and "EasyList".   However, as long as none of those lists were enabled, Reddit would still work properly even when enabling "uBlock filters - Resource abuse", "uBlock filters - Unbreak", "EasyPrivacy", "Online Malicious URL Blocklist", and "Peter Lowe's Ad and tracking server list".   So, there are some kinds of lists that cause the problem and others that don't -- perhaps someone with better understanding of the lists can figure out what the common denominator is.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 39605
  cosmetic: 226
  scriptlet: 75
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easylist: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
  default: 
    easyprivacy: 26669-100, now
    plowe-0: 3671-443, now
    ublock-abuse: 72-0, now
    ublock-unbreak: 1725-27, now
    urlhaus-1: 8437-0, now
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 327 ms (selfie)
  maxAssetCacheWait: 260 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    reddit.com: 4
    redditmedia.com: 1
```
</details>

**Comment by mapx-** [comment] 2022-03-12 19:14
`"My filters"` => your own filters, did you add some reddit filters on your own ?

**Comment by mapx-** [comment] 2022-03-12 19:18
- reset uBO to default settings
- go into dashboard, filter lists tab, click "purge all caches", click "update now"

- disable any other extension in chrome
- test again

**Comment by iam-py-test** [comment] 2022-03-12 19:22
I can't reproduce either.

**Comment by PerfectSalad** [comment] 2022-03-12 19:54
> ```yaml
>   removed: 
>     user-filters: null
>     easylist: null
>     ublock-badware: null
>     ublock-filters: null
>     ublock-privacy: null
>   default: 
>     easyprivacy: 26669-100, now
>     plowe-0: 3671-443, now
>     ublock-abuse: 72-0, now
>     ublock-unbreak: 1725-27, now
>     urlhaus-1: 8437-0, now
> filterset (user): [array of 40 redacted]
> ```

> [x] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists



> * I did not answer truthfully to **all** the above checkpoints

Please read or if you already did, re-read what is checked in your issue

**Comment by Nerva72** [comment] 2022-03-12 20:07
OK, I tried disabling all other extensions and then re-added them to figure out if there was a conflict.   Turns out it's a conflict with Google Translate, of all things.   For some reason on Reddit it doesn't get along with certain filter lists in uBlock.

**Closed** 2022-03-12 20:36 UTC
Labels: invalid, unable to reproduce

**Comment by iam-py-test** [comment] 2022-03-12 21:19
> OK, I tried disabling all other extensions and then re-added them to figure out if there was a conflict. Turns out it's a conflict with Google Translate, of all things. For some reason on Reddit it doesn't get along with certain filter lists in uBlock.

This is why it is strongly recommended you:
- Test with ALL default settings
- Test in a new browser profile so that most browser settings & extensions are not active (gets number 1 too)

**Comment by Nerva72** [comment] 2022-03-12 22:59
Maybe so, but from my vantage point, does it matter?   Adblock, ABP, etc. don't have issues with GOOGLE TRANSLATE, of all things.   And I told you the uBlock lists that cause the problem.   And you don't care.   Fine, it's not like I'm a paying customer.   But that's exactly why I don't bother with all the diagnostic shit you want users to do -- because at the end of the day, I knew you'd say, "not our problem" and close the issue.   But your extension still doesn't work with Google Translate.

**Comment by iam-py-test** [comment] 2022-03-12 23:14
> Maybe so, but from my vantage point, does it matter? Adblock, ABP, etc. don't have issues with GOOGLE TRANSLATE, of all things. And I told you the uBlock lists that cause the problem. And you don't care. Fine, it's not like I'm a paying customer. But that's exactly why I don't bother with all the diagnostic shit you want users to do -- because at the end of the day, I knew you'd say, "not our problem" and close the issue. But your extension still doesn't work with Google Translate.

Can you link to the Google translate extension and I can test on a VM?

**Comment by Nerva72** [comment] 2022-03-13 05:42
Sure, I appreciate the effort.   Here's the extension:

https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

**Comment by mapx-** [comment] 2022-03-13 06:41
@Nerva72 I added the extension, no issue on my end, still able to edit the credentials.
Did you follow the steps here => https://github.com/uBlockOrigin/uAssets/issues/12199#issuecomment-1065946804
?

**Comment by krystian3w** [comment] 2022-03-13 13:30
https://github.com/uBlockOrigin/uAssets/issues/12199#issuecomment-1065952754 - Config can be generated before reset uBO to stock config. For this no help add reset counter with value 0+.
