### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by spikepsych** [uBlockOrigin/uAssets#18509] opened 2023-06-14 10:04 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

video ads dont seem to get blocked at all on twitch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 3d.23h.47m
Chromium: 114
filterset (summary):
 network: 92986
 cosmetic: 39286
 scriptlet: 17573
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67018-49, 4d.13h.17m
  easyprivacy: 30865-56, 5h.39m
  plowe-0: 3364-920, 9d.6h.18m
  ublock-badware: 7345-131, 4d.5h.13m
  ublock-filters: 33471-108, 4d.5h.15m
  ublock-privacy: 395-5, 4d.15h.19m
  ublock-quick-fixes: 254-8, 9h.40m
  ublock-unbreak: 2034-34, 4d.5h.14m
  urlhaus-1: 6560-0, 13h.41m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 229 ms (selfie)
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 128
 network:
  amazon-adsystem.com: 2
  d2v02itv0y9u9t.cloudfront.net: 1
  imrworldwide.com: 3
  scorecardresearch.com: 93
  sentry.io: 29
 extended:
  ##+js(window.open-defuser, amazon-adsystem)
```
</details>

**Comment by okiehsch** [comment] 2023-06-14 10:26
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by okiehsch** 2023-06-14 10:26 UTC
