### ISSUE TITLE
mail.yandex.ru: ads

### ISSUE THREAD

**Issue by silent23d** [uBlockOrigin/uAssets#11276] opened 2022-01-12 05:50 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yandex.ru/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок23](https://user-images.githubusercontent.com/97582808/149071397-13a937a0-7873-400b-b548-6bb67a854aef.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 113511
  cosmetic: 96561
  scriptlet: 28781
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61674-871, 15h.54m
    adguard-mobile: 7061-64, 15h.54m
  default: 
    RUS-0: 40821-9, 15h.57m
    easylist: 62859-973, 15h.54m
    easyprivacy: 26616-217, 15h.53m
    plowe-0: 3684-921, 15h.52m
    ublock-abuse: 76-1, 15h.50m
    ublock-badware: 3699-208, 15h.1m
    ublock-filters: 30130-2985, 15h.1m
    ublock-privacy: 186-4, 15h.1m
    ublock-unbreak: 1716-93, 15h.1m
    urlhaus-1: 6896-0, 15h.1m
filterset (user): [empty]
modifiedUserSettings: 
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 941 ms (selfie)
popupPanel: 
  blocked: 16
```
</details>

**Comment by mapx-** [comment] 2022-01-12 06:35
@dimisa-RUAdList

**Comment by uBlock-user** [comment] 2022-01-12 06:38
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11137

**Closed by uBlock-user** 2022-01-12 06:38 UTC

**Comment by dmitryportvine** [comment] 2022-01-12 08:12
@gorhill
Maybe you should add **RU AdList: Counters** to the **Privacy** section?

**Comment by silent23d** [comment] 2022-01-12 08:27
> @gorhill Maybe you should add **RU AdList: Counters** to the **Privacy** section?
![ewsafsd](https://user-images.githubusercontent.com/97582808/149091058-5dad6af3-94dd-43a7-8f4e-699311ecec7f.JPG)

was added

**Comment by mapx-** [comment] 2022-01-12 09:37
@silent23d it's about a very specific list: **Counters**

**Comment by silent23d** [comment] 2022-01-12 10:22
> Maybe you should add **RU AdList: Counters** to the **Privacy** section?
![ewgdfs](https://user-images.githubusercontent.com/97582808/149122250-9491fea5-e90a-48bf-a5eb-8988e641d51e.JPG)

**Comment by silent23d** [comment] 2022-01-12 10:33
https://easylist-downloads.adblockplus.org/cntblock.txt

imported this page and everything worked out

**Comment by silent23d** [comment] 2022-01-12 10:33
thanks to all

**Comment by gorhill** [comment] 2022-01-12 12:10
> Maybe you should add RU AdList: Counters to the Privacy section

@dimisa-RUAdList can make that list automatically imported in uBO with a `!#include` directive if he wants.

**Comment by dimisa-RUAdList** [comment] 2022-01-12 12:26
If I add this list to RU AdList for uBO with a `!#include` directive, the rules it contains will quickly become useless. The rules are aimed at recidivists who consistently and efficiently fight blockers. That is why they are on the optional list, not the regular one. But if this filter appears in the list of pre-installed (but not activated), it will make it easier for users to connect it. This is probably what @dmitryportvine had in mind. Although the opposite effect is possible if advertisers react to this.

**Comment by dmitryportvine** [comment] 2022-01-12 19:44
> But if this filter appears in the list of pre-installed (but not activated), it will make it easier for users to connect it. This is probably what @dmitryportvine had in mind.

Yes, that's what I mean.
@gorhill ?

**Comment by gorhill** [comment] 2022-01-12 20:24
As a rule, there are no regional list which are not enabled by default -- I don't want to make an exception to this.

**Comment by dmitryportvine** [comment] 2022-01-12 20:36
In this case, there is a reason for exclusion, this filter is necessary for users of Yandex sites. There are a lot of such people...

**Comment by dimisa-RUAdList** [comment] 2022-01-12 21:11
In fact, Counters solves the problem not only of Yandex domains, but also of another major operator, Rambler Group (afisha.ru, letidor.ru, motor.ru, passion.ru, quto.ru, eda.ru, rns.online, championat.com, gazeta.ru, lenta.ru, rambler.ru, wmj.ru). Yes, and it was about adding Counters not to the regional filters section, but to the Privacy section.

**Comment by dmitryportvine** [comment] 2022-01-12 21:55
@gorhill 
Do you really not see the problem? Or is it a kind of ignoring?
