### ISSUE TITLE
www.cambro.tv [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#6825] opened 2020-01-14 01:58 UTC
### URL(s) where the issue occurs

`https://www.cambro.tv/52746/missbella-sweet-insomnia-1-asmr-cam-premium-free-porn-videos/`

### Describe the issue

[Pressing play on the video opens up a redirect and a popup redirect if you try to fullscreen the video.]

### Versions

- Browser/version: [Chrome v79]
- uBlock Origin version: [1.24.2]

### Settings

- [Default]

**Comment by okiehsch** [comment] 2020-01-14 03:17
Does
`cambro.tv##+js(aopr, puTSljawe)`
work for you?

**Comment by dumbusernameidk** [comment] 2020-01-14 03:53
> Does
> `cambro.tv##+js(aopr, puTSljawe)`
> work for you?

I've tried this approach earlier actually it stops the popup on play but it'll create a new duplicate tab + popup redirect to `awejmp` still happens.

**Comment by okiehsch** [comment] 2020-01-14 04:17
Using both
````
cambro.tv##+js(aopr, puTSljawe)
cambro.tv##+js(aopr, puURLstrpcht)
````
?

**Comment by dumbusernameidk** [comment] 2020-01-14 04:23
Clicking play still creates a duplicate tab of the video. I tried `cambro.tv##+js(disable-newtab-links` but nope nothing.

**Comment by okiehsch** [comment] 2020-01-14 04:26
I only get a popunder that is succesfully closed by the existing filter `*$popunder,domain=cambro.tv`
on my end.

> popup redirect to awejmp still happens if you try to fullscreen.

Is fixed if I add the mentioned filters on my end.

**Comment by dumbusernameidk** [comment] 2020-01-14 04:29
Hm whenever I clear cookies/cache after adding filters when I press play I don't get any popups/redirects instead I get a second tab with the same video. It's a bit odd and I'm not sure why it's doing that.

**Comment by okiehsch** [comment] 2020-01-14 04:30
> Hm whenever I clear cookies/cache after adding filters when I press play I don't get any popups/redirects instead I get a second tab with the same video.

You mean you then have two tabs with the same content?
On my end a second tab opens adn the first one closes because of thementioned popunder-filter.

**Comment by dumbusernameidk** [comment] 2020-01-14 04:33
Yep exactly.

**Comment by okiehsch** [comment] 2020-01-14 04:36
I can't reproduce.
Let's wait what others can or can't reproduce.

**Comment by dumbusernameidk** [comment] 2020-01-14 04:37
Found another video with a different popunder script.

```javascript
(function () {var alreadyRun = false;var isTouch = false;var isMoveTouch = false;var isLongTouch = false;var touchTimer;var bcs_popup_show = false;function checkUA(name) {return navigator.userAgent.indexOf(name) != -1;}function safariWinOpen(url) {var a = document.createElement('a');a.setAttribute('href', url);a.setAttribute('target', '_blank');var dispatch = document.createEvent('HTMLEvents');dispatch.initEvent('click', true, true);a.dispatchEvent(dispatch);}function doOpen(url, href) {if (!href) {return false;}if (alreadyRun) {return false;}if (bcs_popup_show == true){return true;}var wFeatures = 'toolbar=0,statusbar=1,resizable=1,scrollbars=1,menubar=0,location=1,directories=0';if (checkUA('Chrome')) {wFeatures = 'scrollbar=yes';}if (checkUA('OPR') || checkUA('Opera') || checkUA('Edge') || checkUA('Chrome') || checkUA('Firefox')) {var oldWindow = window;oldWindow.location = url;if (href) {window.open(href);} else {window.open(oldWindow.location);}return oldWindow;} else {if (checkUA('Safari')) {var oldSWindow = window;if (href) {window.open(href);} else {window.open(oldSWindow.location);}setTimeout(function () {oldSWindow.location = url;}, 100);alreadyRun = true;return oldSWindow;} else if (checkUA('IE') || checkUA('Trident')) {pu_window = window.open(url, 'bc_p_live_stream', wFeatures + ',height=850,width=1350');bcs_popup_show = true;setTimeout(window.focus);window.focus();setTimeout(function () {var a = window.open('about:blank');a.focus();a.close();window.focus();}, 200);}return pu_window;}}function setCookie(name, value, time) {var expires = new Date();expires.setTime(expires.getTime() + time);document.cookie = name + '=' + value + '; path=/; expires=' + expires.toGMTString();}function getCookie(name) {var cookies = document.cookie.toString().split('; ');var cookie, c_name, c_value;for (var n = 0; n < cookies.length; n++) {cookie = cookies[n].split('=');c_name = cookie[0];c_value = cookie[1];if (c_name == name) {return c_value;}}return null;}function initBCPopunder() {if (document.attachEvent) {document.attachEvent('onclick', checkTarget);} else if (document.addEventListener) {document.addEventListener('click', function (e) {if (!isTouch) {isLongTouch = true;checkTarget(e);}}, false);document.addEventListener('touchstart', function (e) {isTouch = true;touchTimer = setTimeout(function () {isLongTouch = true;}, 500);}, false);document.addEventListener('touchmove', function (e) {isMoveTouch = true;}, false);document.addEventListener('touchend', function (e) {if (!isMoveTouch && !isLongTouch) {checkTarget(e);}isTouch = false;isMoveTouch = false;isLongTouch = false;clearTimeout(touchTimer);}, false);}}function checkTarget(e) {if (!getCookie(bcs_cookie_name = 'bcs_cookie_live_stream')){var el = e.target;var url = 'https://bongacams5.com/track?c=655169&ps=popunder&csurl=httpss%3A%2F%2Fbongacams5.com%2Fpromo_popunder_live_stream%3Fc%3D655169%26ps%3Dpopunder%26top_model%3D1%26hd%3D1';if (!el.getAttribute('href')) {while ((el = el.parentElement) && !el.getAttribute('href')) ;}if (el && checkUrl(el.href)) {if (checkUA('OPR') || checkUA('Opera') || checkUA('Edge') || checkUA('Chrome') || checkUA('Firefox') || checkUA('Safari')) {e.preventDefault();}var win = doOpen(url, el.getAttribute('href'));setCookie(bcs_cookie_name = 'bcs_cookie_live_stream', 1, 43200000);}}}function checkUrl(url) {return url && url !== '#' && url.substr(0, 11) !== 'javascript:';}initBCPopunder();
})();```

**Comment by mapx-** [comment] 2020-01-14 07:50
Could you test only
```
cambro.tv##+js(set, flashvars.popunder_url, undefined)
cambro.tv##+js(aopr, onload)
```

**Comment by mapx-** [comment] 2020-01-14 08:02
> Found another video with a different popunder script.

url ?

**Comment by okiehsch** [comment] 2020-01-14 08:02
`cambro.tv##+js(set, flashvars.popunder_url, undefined)`
breaks the video player on my end.

**Comment by mapx-** [comment] 2020-01-14 08:12
what if you replace `undefined` by `null` ?

**Comment by okiehsch** [comment] 2020-01-14 08:18
The video works, but there is no difference between your filters and 
````
cambro.tv##+js(aopr, puTSljawe)
cambro.tv##+js(aopr, puURLstrpcht)
````
on my end, I still get the blocked popunder.

**Comment by mapx-** [comment] 2020-01-14 08:19
I get no `*$popunder,domain=cambro.tv` on my end

**Comment by okiehsch** [comment] 2020-01-14 08:22
I don't think 
`cambro.tv##+js(set, flashvars.popunder_url, null)`
achieves anything.

`cambro.tv##+js(set, flashvars.popunder_url, undefined)`
disables the popunder and sadly also breaks the videoplayer.

> I get no *$popunder,domain=cambro.tv on my end

Even if you remove all mentioned filters?
You may have to delete the existing cookies.

**Comment by mapx-** [comment] 2020-01-14 08:23
sometimes after 3-4 page refreshes I get the video even with `undefined`

**Comment by uBlock-user** [comment] 2020-01-14 08:23
The placeholder white area on the right hand side of the video player is clickable and clicking on it causes the popunder/up to trigger, none of the filters fix that. Need to make that area un-clickable.

**Comment by mapx-** [comment] 2020-01-14 08:25
sure, I deleted the cookies / cache every test I did. No popunders for me.

**Comment by okiehsch** [comment] 2020-01-14 08:26
> sure, I deleted the cookies / cache every test I did. No popunders for me.

So what can you reproduce?

**Comment by mapx-** [comment] 2020-01-14 08:26
Without my filters I get the popunder.

**Comment by okiehsch** [comment] 2020-01-14 08:29
Ok, then we misunderstood each other. I agree with that.
What I meant is if you remove your filters the popunder is blocked by the existing filter
`*$popunder,domain=cambro.tv`
?

**Comment by okiehsch** [comment] 2020-01-14 08:30
**dumbusernameidk ** Mentions that the popunder leads to two tabs beeing open on his end.
I can't reproduce that.

**Comment by mapx-** [comment] 2020-01-14 08:34
> dumbusernameidk Mentions that the popunder leads to two tabs beeing open on his end.

me neither.

And yes, without my filters I get `*$popunder,domain=cambro.tv`

**Comment by okiehsch** [comment] 2020-01-14 08:34
Can you try
````
cambro.tv##+js(aopr, onload)
www.cambro.tv###kt_player > [href^="https://www.cambro.tv/"]
````

**Comment by mapx-** [comment] 2020-01-14 08:38
working fine, no popunder

**Comment by uBlock-user** [comment] 2020-01-14 08:38
Those will do it, but using `aopr`, instead of `acis` might cause breakage in the future.

**Comment by uBlock-user** [comment] 2020-01-14 08:41
Random camgirl button leads to tracking leak --  `cambro.tv##.fp-brand`

**Comment by okiehsch** [comment] 2020-01-14 08:42
`acis` does not work on my end.
 I get redirected if I go to full screen

**Closed** 2020-01-14 08:46 UTC

**Comment by dumbusernameidk** [comment] 2020-01-14 12:06
Yes that does fix it.




> > Found another video with a different popunder script.
> 
> url ?

Doesn't seem the video has this anymore when I check the source page.
