### ISSUE TITLE
[nsfw] youtube.com: popups

### ISSUE THREAD

**Issue by Idontusethisanyways** [uBlockOrigin/uAssets#13237] opened 2022-05-15 13:19 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=U5w70kgP7nw`

### Category

popups

### Describe the issue

it's just keeps popping oufrom nowhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 100630
  cosmetic: 64866
  scriptlet: 18167
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    RUS-0: 41351-9, 1h.16m
    easylist: 66759-64, 1h.13m
    easyprivacy: 26976-218, 1h.12m
    plowe-0: 3672-808, 1h.11m
    ublock-abuse: 75-1, 1h.9m
    ublock-badware: 4128-94, 1h.7m
    ublock-filters: 31345-128, 1h.6m
    ublock-privacy: 214-2, 1h.5m
    ublock-quick-fixes: 219-0, 1h.4m
    ublock-unbreak: 1780-41, 1h.3m
    urlhaus-1: 8707-0, 1h.2m
filterset (user): [array of 2 redacted]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 597 ms (selfie)
  maxAssetCacheWait: 401 ms
popupPanel: 
  blocked: 54
  blockedDetails: 
    youtube.com: 33
    doubleclick.net: 4
    google.com: 13
    google.kz: 1
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by Yuki2718** [comment] 2022-05-15 14:56
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636
Plus, without screenshot we have no idea what you're talking about.

**Closed by Yuki2718** 2022-05-15 14:56 UTC
