### ISSUE TITLE
[nsfw] securly.com: detection

### ISSUE THREAD

**Issue by wgreene001** [uBlockOrigin/uAssets#11399] opened 2022-01-21 00:20 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.securly.com/blocked?useremail=wgreene001@student.hampton.k12.va.us&reason=globalblacklist&categoryid=BL&policyid=G&keyword=&url=cGxheS5nZWZvcmNlbm93LmNvbS9tYWxsLyMvc3RyZWFtZXI/bGF1bmNoU291cmNlPUdlRm9yY2VOT1cmY21zSWQ9MTAwMDEzMzExJnNob3J0TmFtZT1mb3J0bml0ZV9nZm5fcGMmYXBwTGF1bmNoTW9kZT1EZWZhdWx0JmFjY291bnRMaW5rZWQ9dHJ1ZQ==&ver=2.98.25&listType=BL`

### Category

detection

### Describe the issue

5tgfuedhufehddedhwehwhdwud

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79134
  cosmetic: 40563
  scriptlet: 16474
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63128-9, 1d.8h.18m
    easyprivacy: 26637-17, 1d.8h.17m
    plowe-0: 3681-816, 1d.8h.16m
    ublock-abuse: 76-0, 1d.8h.13m
    ublock-badware: 3724-67, 1d.8h.11m
    ublock-filters: 30200-149, 1d.8h.10m
    ublock-privacy: 190-3, 1d.8h.9m
    ublock-unbreak: 1686-41, 1d.8h.8m
    urlhaus-1: 8099-0, 6h.7m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4275 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment] 2022-01-21 06:12
Provide the steps to reproduce the issue.

Open the uBO logger, reproduce again the issue, go to the logger, select only the blocked requests / items in the logger then post here a screenshot with that content

**Comment by uBlock-user** [comment] 2022-01-21 06:22
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11399

**Closed by uBlock-user** 2022-01-21 06:22 UTC
