### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by nekromantik** [uBlockOrigin/uAssets#21397] opened 2023-12-13 22:33 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.reddit.com/`

### Description

Since new reddit layout the dark mode toggle does not stay on when UBO is on.
you turn dark mode on and it stays dark on current page until you go back to home page where it turns off

### Other extensions used

bitwarden
adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 275509
 cosmetic: 242710
 scriptlet: 48295
 html: 1331
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76030-7217, 3d.1h.4m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 4h.49m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2508-1, 1h.48m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94990-66014, 7d.3h.28m
  adguard-generic: 80642-4345, 3d.1h.5m
  adguard-mobile: 8790-100, 3d.1h.5m
  adguard-spyware-url: 1350-200, 3d.1h.4m
  block-lan: 55-0, 23d.3h.49m
  adguard-social: 22079-44, 3d.1h.4m
  fanboy-thirdparty_social: 68-0, 7d.1h.26m
  fanboy-cookiemonster: 49114-170, 1d.1h.49m
  ublock-annoyances: 6121-11, 5h.50m
  [2 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36957-127, 5h.50m
  ublock-badware: 7615-11, 5h.50m
  ublock-privacy: 933-52, 5h.50m
  ublock-unbreak: 2211-1, 5h.50m
  easylist: 75562-2628, 5h.50m
  easyprivacy: 33127-901, 5h.50m
  urlhaus-1: 11090-0, 4h.49m
  plowe-0: 3778-1, 2h.49m
  ublock-quick-fixes: 112-2, 5h.50m
filterset (user): [empty]
trustedset:
 added: [array of 83 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1514 ms (selfie)
 maxAssetCacheWait: 237 ms
popupPanel:
 blocked: 3
 network:
  reddit.com: 1
  ad-delivery.net: 1
  redditstatic.com: 1
 extended:
  ##.grecaptcha-badge
  ##.promotedlink:not([style^="height: 1px;"])
  ##[slot="use-app"]
  ##shreddit-experience-tree
  ##body:style(pointer-events:auto !important;)
  #@#body:style(pointer-events: auto !important; overflow: auto !i…
  #@#body:not(.with-listing-chooser):style(overflow: visible !impo…
  #@#a[href^="https://www.reddit.com/submit"]
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(abort-on-property-write, STICKY_CANARY)
  ##+js(set-constant, navigator.sendBeacon, noopFunc)
  ##+js(addEventListener-defuser, block-body-scrolling)
  ##+js(set-local-storage-item, xpromo-consolidation, 1)
  ##+js(remove-class, scroll-disabled, body, stay)
  ##+js(set-constant, Notification.requestPermission, noopFunc)
  ##+js(remove-class, m-blurred, .m-blurred)
  ##+js(remove-class, scroll-disabled, body)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])

```
</details>

**Comment by peace2000** [comment] 2023-12-14 04:03
Cannot reproduce. Did you follow all the steps on _Prerequisites_ ?

**Comment by nekromantik** [comment] 2023-12-14 17:13
> Cannot reproduce. Did you follow all the steps on _Prerequisites_ ?

started to work again but there is a slight delay in the page turning black as it still goes to white and then switches back

**Comment by peace2000** [comment] 2023-12-14 17:43
You should clear the cache and disable your custom filters one by one to see whether one of them affect the page and test on another browser profile or a browser.

Anyway, closing because this issue doesn't seem to be related to uBO or lists that we maintain.

**Closed by peace2000** 2023-12-14 17:43 UTC
Labels: unable to reproduce, Waiting for feedback
