### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by TeamCoco2** [uBlockOrigin/uAssets#14713] opened 2022-09-07 12:52 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

Ads continue during broadcast

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 83585
  cosmetic: 47929
  scriptlet: 18201
  html: 742
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33262-43, 23h.5m
    ublock-badware: 4221-0, 23h.4m
    ublock-privacy: 263-0, 4d.3h.50m
    ublock-abuse: 76-0, 4d.3h.49m
    ublock-unbreak: 1860-0, 23h.3m
    ublock-quick-fixes: 425-0, 3h.34m
    easylist: 64839-615, 23h.2m
    easyprivacy: 27489-618, 23h.1m
    urlhaus-1: 7346-0, 3h.35m
    plowe-0: 3671-3, 4d.3h.48m
    TUR-0: 8461-21, 23h.6m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1013 ms
  maxAssetCacheWait: 349 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    google-analytics.com: 2
    imrworldwide.com: 1
    scorecardresearch.com: 6
```
</details>

**Comment by MasterKia** [comment] 2022-09-07 12:53
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

You should comment here: https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-09-07 12:53
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-09-07 12:53 UTC
