### ISSUE TITLE
anichin.top: popups

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#19477] opened 2023-08-27 05:49 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://anichin.top/`

### Category

popups

### Description

Redirect and opened new tab

### Other extensions used

Dark reader 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 111301
 cosmetic: 136130
 scriptlet: 27154
 html: 1214
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 10776-14, 5m
  https://cdn.statically.io/gh/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 181-0, 5m
  https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 2251-0, 5m
  adguard-spyware-url: 1192-176, 5m
  adguard-social: 21261-164, 5m
  adguard-cookies: 27412-45, 5m
  adguard-popup-overlays: 23517-1027, 5m
  adguard-mobile-app-banners: 4576-12, 5m
  adguard-other-annoyances: 13323-99, 5m
  adguard-widgets: 2288-2, 5m
  ublock-annoyances: 5450-321, 5m
  ublock-cookies-adguard: 304-0, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 35542-542, 5m
  ublock-badware: 7782-0, 5m
  ublock-privacy: 570-43, 5m
  ublock-unbreak: 2168-1, 4m
  ublock-quick-fixes: 247-0, 4m
  adguard-mobile: 8579-18, 5m
  easylist: 69578-798, 4m
  easyprivacy: 33311-730, 2m
  urlhaus-1: 6000-0, 2m
  plowe-0: 3724-87, 2m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1587 ms
 maxAssetCacheWait: 906 ms
popupPanel:
 blocked: 10
 network:
  bbvbyzzyrerer.top: 1
  cloudflareinsights.com: 2
  friendshipmale.com: 1
  google-analytics.com: 1
  linkmonet.com: 2
  provenshoutmidst.com: 2
  simplewebanalysis.com: 1
 extended:
  ##.kln
  ##[href="https://klik.best/anichinmyid"]
  ##[href="https://klik.gg/anichin"]
  ##+js(json-prune, *, pop_type)
```
</details>

**Comment by okiehsch** [comment] 2023-08-27 07:19
Does 
`anichin.top##+js(nowoif)`
work for you?

**Comment by okiehsch** [comment] 2023-08-27 07:48
Thx, this will be fixed in the regional indonesian list and you have disable that list, so you will have to keep that filter in your filter list or enable the regional list.
@gmarcher

**Comment by ghajini** [comment] 2023-08-27 10:29
some more ads fix for **ABPIndo**

```
anichin.top##+js(aost, Promise, https)
anichin.top,hlsplayer.top##+js(nowoif)
zuperdrive.my.id##+js(nowoif, !zuperdrive)
zuperdrive.my.id###iframeAds
zuperdrive.my.id###directAds
||vdhostplayer.my.id^$frame,domain=zuperdrive.my.id
```

**Comment by partingscientist** [comment] 2023-08-27 10:59
> ```
> anichin.top##+js(aost, Promise, https)
> anichin.top,hlsplayer.top##+js(nowoif)
> zuperdrive.my.id##+js(nowoif, !zuperdrive)
> zuperdrive.my.id###iframeAds
> zuperdrive.my.id###directAds
> ||vdhostplayer.my.id^$frame,domain=zuperdrive.my.id
> ```

Are these all from `anichin.top`? Can you also provide the STR? For documentation purposes.

**Comment by partingscientist** [comment] 2023-08-27 11:02
I also found event-logging requests to `haveredsiren.space/pntne`. Perhaps any maintainers can confirm if the following are related to it?

https://github.com/easylist/easylist/blob/266a0b0b3e633f51e2fbb48ac1a4d1cbcc7a7b32/easylist/easylist_specific_block.txt#L515

**Comment by ghajini** [comment] 2023-08-27 11:08
play any videos
eg `https://anichin.top/swallowed-star-season-2-episode-01-subtitle-indonesia/`

**Comment by partingscientist** [comment] 2023-08-27 13:05
> play any videos eg `https://anichin.top/swallowed-star-season-2-episode-01-subtitle-indonesia/`

I cannot reproduce it.

**Comment by ghajini** [comment] 2023-08-27 15:58
> > play any videos eg `https://anichin.top/swallowed-star-season-2-episode-01-subtitle-indonesia/`
> 
> I cannot reproduce it.
> 

did you play video using various severs eg dailymotion v2 etc?

**Closed** 2023-08-27 16:11 UTC
Labels: to be fixed by regional list
