### ISSUE TITLE
cafe.naver.com: nuisance

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [uBlockOrigin/uAssets#12528] opened 2022-04-01 04:29 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cafe.naver.com/ufofloat/63296`

### Category

nuisance

### Describe the issue

This site has anti right click, select, and copy. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Chromium: 99
filterset (summary): 
  network: 81668
  cosmetic: 49736
  scriptlet: 19201
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4266-7, 3m
  default: 
    user-filters: 0-0, never
    KOR-1: 8156-0, 3m
    easylist: 65091-58, 3m
    easyprivacy: 26743-125, 3m
    plowe-0: 3690-811, 3m
    ublock-abuse: 72-0, 3m
    ublock-badware: 4001-88, 3m
    ublock-filters: 30476-91, 3m
    ublock-privacy: 205-2, 3m
    ublock-quick-fixes: 119-4, 3m
    ublock-unbreak: 1744-41, 3m
    urlhaus-1: 7425-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2246 ms
  maxAssetCacheWait: 316 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    naver.com: 7
```
</details>

**Comment by 88Va2wFDcYd1CT** [comment] 2022-04-01 05:28
Also some pages like https://cafe.naver.com/optimuslteuser/903637
It does not prevent copying, but automatically adds the source, article title, and author when copying and pasting.
I have this behavior https://cafe.naver.com/static/js/mycafe/javascript/autosourcing-1644284985000-8747.js
I think it is by this script.

**Comment by mapx-** [comment] 2022-04-01 06:57
for the added stuff on copy (`document.body.oncopy`), maybe it's related to
https://github.com/uBlockOrigin/uAssets/issues/7320

**Comment by okiehsch** [comment] 2022-04-01 07:16
> for the added stuff on copy 

Isn't that fixed by your filters too?
I can't reproduce.

**Comment by mapx-** [comment] 2022-04-01 07:27
if you go `https://cafe.naver.com/optimuslteuser/903637`

select & copy for example:
![image](https://user-images.githubusercontent.com/10303732/161215747-bc0f84ff-498d-456f-ab22-cfc5ffd467f5.png)

You'll get:
```
Q92 5G 성능업데이트
[출처] [SW 개선] 2022년 2분기 SW업데이트 계획 (‘22. 3월) (엘지모바일 사용자 카페 - V50,G8,V40,G7,V35,V30,G6,V20,Q9,Q8) | 작성자 zjvl
```

where the second row is that added by the page

**Comment by 88Va2wFDcYd1CT** [comment] 2022-04-01 07:34
cafe.naver.com##+js(set-constant, document.body.oncopy, null)
Adding a rule breaks the site.
Is there any other way?
![1](https://user-images.githubusercontent.com/101787143/161216938-a0c3266e-d7ed-4c8e-ae4a-09a0bdf3c6c0.png)

**Comment by stephenhawk8054** [comment] 2022-04-01 07:51
If I remember correctly, `naver.com` is the most popular site in Korea. I'm afraid the `aopr` filters could cause potential breakages. Should we narrow it to `cafe.naver.com`?

**Comment by mapx-** [comment] 2022-04-01 07:53
done

**Comment by mapx-** [comment] 2022-04-01 07:59
@88Va2wFDcYd1CT , yes, as I wrote above it's related to that older issue (7320), for now we can't fix it without @gorhill approach explained in 7320

**Closed by mapx-** 2022-04-01 07:59 UTC

**Comment by 88Va2wFDcYd1CT** [comment] 2022-04-01 08:01
@okiehsch @stephenhawk8054 @jayvdb 
Since naver.com is a popular site in Korea, it would be good to do so.
Thank you for your hard work.
