### ISSUE TITLE
ivi.ru video ads

### ISSUE THREAD

**Issue by hant0508** [uBlockOrigin/uAssets#1443] opened 2018-02-01 23:35 UTC
### URL(s) where the issue occurs

`https://www.ivi.ru/watch/172624`

### Describe the issue

There are some ad videos before the film. Also there's an anti-adblock warning at the top of the page.

### Screenshot(s)

![screenshot_2018-02-02](https://user-images.githubusercontent.com/28459131/35708638-10e56804-07c0-11e8-979d-9b6221b2f814.png)

### Versions

- Browser/version: Chromium 64.0.3282.119
- uBlock Origin version: 1.14.25rc1 (+ uBO Extra 2.61)

### Settings

Default filters + RUS (Adguard, RU AdList) + All Adguard

### Notes
The website requires Chromium-based browser, player doesn't work in Firefox.  Anti-adblock warning disappears after refreshing the page, video ads also are shown only once, so use private window.

UPD: It seems that you need Russian IP to reproduce the issue.

**Comment by okiehsch** [comment] 2018-02-02 00:10
`@@||ivi.tv^$generichide` fixes the anti-adblock warning on my end.
I do not get any pre-roll video ads at `https://www.ivi.ru/watch/172624`

**Comment by hant0508** [comment] 2018-02-02 00:21
> @@||ivi.tv^$generichide fixes the anti-adblock warning on my end.

Doesn't work for me, the warning appears again in new private window.
> I do not get any pre-roll video ads.

Which video do you see? Is it a trailer or a full film?

**Comment by okiehsch** [comment] 2018-02-02 00:37
The `generichide` filter works for me, without it I can reproduce the warning, with it there is no warning, so I can't help with that.

It is a trailer, I do not speak russian, so you would have to tell me how to play a full film.

**Comment by hant0508** [comment] 2018-02-02 00:47
As I mentioned in the issue, I guess you have to use Russian proxy to see the film and reproduce the issue. When I open the link I've provided, player with film (and with ads) opens automatically.

**Comment by okiehsch** [comment] 2018-02-02 00:51
Oh, I did not notice the need of a russian proxy in your notes, my bad.

Somebody else will haveto come up with a fix for this issue.

**Closed** 2018-02-02 22:02 UTC
