### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by stefan-bo** [uBlockOrigin/uAssets#15442] opened 2022-10-27 19:09 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bild.de/`
`https://www.bild.de/video/clip/news-ausland/bmw-gang-rastet-aus-brutale-verfolgungsjagd-auf-autobahn-81737744.bild.html`

### Category

detection

### Describe the issue

First time you visit the page it will shown as page with no content (white / blank). If you disable uBlock and refresh and then immediately activate uBlock you will get the following page:

`https://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html`

The white page thing can happen too with other links from bild.de but sometimes this problem even doesn't appear at all so it's kind of inconsistent. So I guess it will be difficult to debug :-/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bildschirmfoto vom 2022-10-27 20-55-28](https://user-images.githubusercontent.com/55791185/198377613-937898a0-455f-4f9e-9bd6-708bafd0744e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 90329
  cosmetic: 42110
  scriptlet: 17713
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6003-0, 35m
    easylist: 62400-58, 35m
    easyprivacy: 30818-1180, 35m
    plowe-0: 3671-866, 35m
    ublock-abuse: 76-0, 35m
    ublock-badware: 3938-105, 35m
    ublock-filters: 32234-141, 35m
    ublock-privacy: 260-1, 35m
    ublock-quick-fixes: 423-21, 35m
    ublock-unbreak: 1873-43, 35m
    urlhaus-1: 11029-0, 35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 340 ms (selfie)
  maxAssetCacheWait: 155 ms
popupPanel: 
  blocked: 56
  blockedDetails: 
    bild.de: 12
    adnxs.com: 1
    asadcdn.com: 6
    c-i.as: 1
    cxense.com: 1
    demdex.net: 10
    df-srv.de: 1
    doubleclick.net: 2
    facebook.net: 1
    googletagmanager.com: 1
    ioam.de: 2
    kameleoon.eu: 1
    msn.com: 1
    nmrodam.com: 1
    opecloud.com: 2
    outbrain.com: 2
    smartadserver.com: 5
    taboola.com: 6
```
</details>

**Comment by okiehsch** [comment] 2022-10-27 19:28
I can't reproduce the existing filters for `bild.de` still work on my end.
What browser are you using?

**Comment by stefan-bo** [comment] 2022-10-27 19:48
I can imagine. I am using Chrome Version 105.0.5195.125 and Pop!_OS 22.04. I also recognized that I don't have this issue with my workstation running windows 10 and chrome. So maybe it's really a weird specific bug with my machine?

**Comment by okiehsch** [comment] 2022-10-27 19:52
> So maybe it's really a weird specific bug with my machine?

Probably, it works for me and `bild.de` is a high traffic site, so if it suddenly became unusable for uBO-users we would have more users opening issues about it imo.

**Comment by stefan-bo** [comment] 2022-10-27 20:03
Yeah. Let me test this with Firefox for some time. If I will experience the same problems with that browser I will comment here again. What make me wonder is just that I didn't have this problems before with chrome and pop os. Unfortunately I don't remember when this started but it did some month ago (the white page thing where my little "trick" with the deactivation, refresh and reactivation thing worked) :-/

**Comment by okiehsch** [comment] 2022-10-28 06:54
Ok, I will close the issue for now but if it haooens again just post in this thread and I will reopen.

**Closed by okiehsch** 2022-10-28 06:54 UTC
Labels: unable to reproduce
