### ISSUE TITLE
chip.de malicious installers are back

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [uBlockOrigin/uAssets#178] opened 2016-10-26 22:59 UTC
### URL(s) where the issue occurs

http://www.chip.de/downloads/W10Privacy_81892989.html

### Describe the issue

see: https://github.com/uBlockOrigin/uAssets/issues/42
they were blocked in the past now they are visible again they seem to have noticed and circumvented the blocking so as to continue the spreading of ad- and malware

### Screenshot(s)

see: https://github.com/uBlockOrigin/uAssets/issues/42

### Versions

- Browser/version: Firefox 49
- uBlock Origin version: 1.9.16

### Settings

badware risks filter list enabled (which should block it but doesnt anymore)

### Notes

you probably need to access from windows to have that problem because their ad-/malware installers only work on windows so only windows users are targeted

**Comment by IDKwhattoputhere** [comment] 2016-10-26 23:12
`chip.de##[href^="javascript:DownloadStartInit"]`

**Comment by gorhill** [comment] 2016-10-26 23:16
Fixed with e1036a33dcdb459188726384aa72c210ed2260bb.

**Closed by gorhill** 2016-10-26 23:16 UTC

**Comment by IDKwhattoputhere** [comment] 2016-12-21 21:36
I have to use `||chip.de/downloader/guided-download/` for the real download button to show in Chrome and Firefox.

**Comment by okiehsch** [comment] 2016-12-21 21:57
With `http://www.chip.de/downloads/W10Privacy_81892989.html`
I just click on "Manuelle Installation" and get redirected to
`http://www.chip.de/downloads/c1_downloads_auswahl_81892990.html?t=1482356196&v=3600&s=7dc50aca2bb3253c419c126623759428`

If I use `||chip.de/downloader/guided-download/`
I have to click on the blue box marked "Download WC Privacy", but I
get redirected to the same address.

**Comment by IDKwhattoputhere** [comment] 2016-12-21 22:06
This is what it looks like for me:
![](https://cloud.githubusercontent.com/assets/16030872/21407833/ce06ee06-c7d1-11e6-8657-14aeabb97075.png)
If I disable element hiding it looks like this:
![](https://cloud.githubusercontent.com/assets/16030872/21407865/f6236f40-c7d1-11e6-9e20-891c5b1cf49c.png)
The blue button links to the malicious installer (`javascript:DownloadStartInit`).

**Comment by okiehsch** [comment] 2016-12-21 22:20
This is what it looks like for me.
![unbenannt](https://cloud.githubusercontent.com/assets/16838044/21408032/ed129646-c7d2-11e6-8167-177656c7e280.JPG)
With chrome and any non default filter disabled. 
Sorry I just can't reproduce.

The logger shows the following cosmetic filters.
![chip](https://cloud.githubusercontent.com/assets/16838044/21408176/d31b20cc-c7d3-11e6-836a-ee3e4b6757bd.PNG)

**Comment by IDKwhattoputhere** [comment] 2016-12-21 23:48
I take it all back. I had a userscript installed that interfered with the page. Very sorry.

**Comment by krystian3w** [comment] 2020-09-06 18:20
Update #42, #178, gorhill/uBlock#673, #6587

**Comment by krystian3w** [comment] 2020-09-06 18:22
<p>Update <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="153673611" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/42" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/42/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/42">#42</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="185532658" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/178" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/178/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/178">#178</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="104376646" data-permission-text="Title is private" data-url="https://github.com/gorhill/uBlock/issues/673" data-hovercard-type="issue" data-hovercard-url="/gorhill/uBlock/issues/673/hovercard" href="https://github.com/gorhill/uBlock/issues/673">gorhill/uBlock#673</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="524202202" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/6587" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/6587/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/6587">#6587</a></p>

**Comment by krystian3w** [comment] 2020-09-06 18:23
<p>Update <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="153673611" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/42" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/42/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/42">#42</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="185532658" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/178" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/178/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/178">#178</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="104376646" data-permission-text="Title is private" data-url="https://github.com/gorhill/uBlock/issues/673" data-hovercard-type="issue" data-hovercard-url="/gorhill/uBlock/issues/673/hovercard" href="https://github.com/gorhill/uBlock/issues/673">gorhill/uBlock#673</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="524202202" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/6587" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/6587/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/6587">#6587</a></p>

**Comment by krystian3w** [comment] 2020-09-06 18:24
<p>Update <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="153673611" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/42" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/42/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/42">#42</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="185532658" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/178" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/178/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/178">#178</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="104376646" data-permission-text="Title is private" data-url="https://github.com/gorhill/uBlock/issues/673" data-hovercard-type="issue" data-hovercard-url="/gorhill/uBlock/issues/673/hovercard" href="https://github.com/gorhill/uBlock/issues/673">gorhill/uBlock#673</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="524202202" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/6587" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/6587/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/6587">#6587</a></p>

**Comment by krystian3w** [comment] 2020-09-06 18:24
<p>Update <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="153673611" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/42" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/42/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/42">#42</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="185532658" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/178" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/178/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/178">#178</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="104376646" data-permission-text="Title is private" data-url="https://github.com/gorhill/uBlock/issues/673" data-hovercard-type="issue" data-hovercard-url="/gorhill/uBlock/issues/673/hovercard" href="https://github.com/gorhill/uBlock/issues/673">gorhill/uBlock#673</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="524202202" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/6587" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/6587/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/6587">#6587</a></p>
