### ISSUE TITLE
theatlantic.com anti-adblock

### ISSUE THREAD

**Issue by ksmustang** [uBlockOrigin/uAssets#1753] opened 2018-03-20 23:53 UTC
## URL(s) where the issue occurs

Does not occur on the main page for the site; occurs when clicking on articles such as the following:

https://www.theatlantic.com/technology/archive/2018/03/where-is-mark-zuckerberg/556049/
https://www.theatlantic.com/family/archive/2018/03/childhood-conformity/554453/

### Describe the issue

articles on the site display an anti-adblock message when ublock origin is enabled.

### Screenshot(s)

![theatlandic](https://user-images.githubusercontent.com/37599506/37688633-fd17c564-2c6e-11e8-9497-365af8a839fe.jpg)

### Versions

- Browser/version: Firefox 54.0.1
- uBlock Origin version: 1.15.6

### Settings

- Default

**Comment by okiehsch** [comment] 2018-03-20 23:56
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/1744

**Closed by okiehsch** 2018-03-20 23:56 UTC
