### ISSUE TITLE
Lots of unblocked ads on various readcomiconline.to pages

### ISSUE THREAD

**Issue by HereticWilson** [uBlockOrigin/uAssets#2389] opened 2018-05-27 21:38 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://readcomiconline.to/Comic/Global-Frequency`

### Describe the issue

[As the title says. Ads on either side of the page and one right in the middle]

### Screenshot(s)

https://imgur.com/a/RPDRYWH

### Versions

- Browser/version: [Opera 52.0.2871.64]
- uBlock Origin version: [uBlock Origin v1.16.6]

**Comment by mapx-** [comment] 2018-05-27 21:54
tested in FF / chrome / opera 54 => no side ads for me.
update your lists and test again.

**Comment by okiehsch** [comment] 2018-05-27 21:56
These ads are fixed on my end.
I can only reproduce your screenshot if I disable `uBO-filters`, so if your lists are up to date and your logger shows that 
`readcomiconline.to##script:inject(abort-on-property-read.js, Element.prototype.insertAdjacentElement)`
has been injected.
![unbenannt](https://user-images.githubusercontent.com/16838044/40590986-3de64492-6209-11e8-9587-a699fe2186e4.PNG)

The issue should be fixed.

**Comment by HereticWilson** [comment] 2018-05-27 21:56
Purged caches and updated all lists, they're still there.

**Comment by HereticWilson** [comment] 2018-05-27 21:59
@okiehsch I don't understand what you're saying exactly, but that doesn't show up in the logger for the site.

**Comment by okiehsch** [comment] 2018-05-27 22:01
That filter fixes the issu,e it disables the script that leads to the ads you are seeing, if it does not show up in your logger it has not been injected and that is the reason you are having this issue.

**Comment by HereticWilson** [comment] 2018-05-27 22:02
@okiehsch Ohhh, got it. Thanks.

**Comment by okiehsch** [comment] 2018-05-27 22:03
Does it work and/or show up in the logger if you add
````
readcomiconline.to##script:inject(abort-on-property-read.js, Element.prototype.insertAdjacentElement)
````
to your "My filters" tab?

**Comment by HereticWilson** [comment] 2018-05-27 22:04
@okiehsch Just edited the previous comment, nope it doesn't.

**Comment by mapx-** [comment] 2018-05-27 22:07
Did you disable opera builtin adblock ?
Try also updating to the last opera version

**Comment by HereticWilson** [comment] 2018-05-27 22:09
@mapx- Welp, disabling the Opera adblocker worked. Weird.

**Closed** 2018-05-27 22:15 UTC
Labels: unable to reproduce
