### ISSUE TITLE
9anime AdBlocker blocker

### ISSUE THREAD

**Issue by TheMather1** [uBlockOrigin/uAssets#2334] opened 2018-05-21 10:58 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www4.9anime.is/watch/beatless.8mlq/j0j9l2`

### Describe the issue

Loading the page with the uBlock filters active causes the video element to be replaced with an element containing the message:
"Please disable AdBlock then try again.
If you want to watch anime in high quality without ads,
just get a subscription in premium anime site.
Thanks for your supporting!"

### Versions

- Browser/version: Google Chrome/66.0.3359.181
- uBlock Origin version: AdNauseam/3.3.403

### Notes

Through disabling the uBlock filters and experimenting with custom filters, I have found that blocking either of the following elements, or their parent elements, triggers the script:
rcjsload_*
mgline *

**Comment by okiehsch** [comment] 2018-05-21 11:01
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2333

Update your uBO-filter list it is already fixed.

**Closed by okiehsch** 2018-05-21 11:01 UTC

**Comment by TheMather1** [comment] 2018-05-21 11:25
Filter is up to date. The update didn't solve the issue.

**Comment by okiehsch** [comment] 2018-05-21 11:46
Well, it does fix the issue using `uBO`, I have no clue if it does fix the issue using `AdNauseam`.

**Comment by uBlock-user** [comment] 2018-05-21 11:51
Why report here when using `Adnauseam` ? They have their issue tracker for that.

**Comment by TheMather1** [comment] 2018-05-21 11:58
Because the problem is caused by the uBlock filter, not by AdNauseam itself. Disabling the filter fixes the problem, though obviously that's not a permanent solution.

**Comment by uBlock-user** [comment] 2018-05-21 12:02
> caused by the uBlock filter

Which filter ?

**Comment by okiehsch** [comment] 2018-05-21 12:05
uBO-filters are, as the name implies, optimized for uBlock, there is no guarantee that they will work as intended if you use a different adblocker.

The filter that causes your issue is probably
`9anime.*###sidebar > .text-center.crop.widget:style(height: 5px !important)`
Add `9anime.*#@##sidebar > .text-center.crop.widget:style(height: 5px !important)` to your filter list and try again.

**Comment by TheMather1** [comment] 2018-05-21 12:37
That worked. Thank you!

**Comment by okiehsch** [comment] 2018-05-21 23:20
All 9anime issues post in #2333
from now on, no need for half a dozen different issues for one site.
