### ISSUE TITLE
zf.ro Anti Adblocker

### ISSUE THREAD

**Issue by radusw** [uBlockOrigin/uAssets#787] opened 2017-10-27 11:31 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.zf.ro/`

### Describe the issue
Anti adblocker

### Versions

- Browser/version: Firefox 56.0.2
- uBlock Origin version: 1.14.16

### Notes
`www.zf.ro##script:contains(adblock)` did not work. Any ideas why?
Solved by: `||www.zf.ro^$inline-script`

**Comment by mapx-** [comment] 2017-10-27 11:46
You could try
zf.ro##script:inject(abort-current-inline-script.js, adblock)

I cannot reproduce your issue, even adding Rolist in uBo.
However, `script:contains`  is deprecated and  FF 56 full of bugs. You should use (beta)  FF 57

**Comment by okiehsch** [comment] 2017-10-27 16:50
I can't reproduce, `script:contains` does not work with the  uBO-webextension.

**Comment by tcptomato** [comment] 2017-11-02 17:57
I had the same issue with `prosport.ro` and took a similar approach ( block inline script & whitelist good behaviour ). 

I managed to reproduce the issue with `zf.ro` on chrome, you have to be in developer mode and in the network tab check `disable caches`.

**Comment by okiehsch** [comment] 2017-11-02 18:47
I can indeed reproduce if I load `www.zf.ro` with the console open and `i401xox.com` requests blocked,
if I then close the console and reload I will still get the adblock message.
The fix for this behaviour is to delete cookies, then reload.
I still can't reproduce with Firefox.

**Closed** 2017-12-07 15:14 UTC
