### ISSUE TITLE
cnn.gr adblock detected

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#5978] opened 2019-07-19 19:06 UTC
AdBlocker detected
This site is financed by advertising. Because of an installed ad blocker in your browser the advertising is blocked. Please disable your ad blocker to watch the video.

https://www.cnn.gr/news/ellada/story/184901/seismos-athina-katerreyse-akatoikito-spiti-stin-ermoy-lygise-o-stayros-stin-ag-eirini

thanks

**Comment by JobcenterTycoon** [comment] 2019-07-19 23:30
@okiehsch i get pre video ads

**Comment by okiehsch** [comment] 2019-07-20 01:50
> i get pre video ads

I can't reproduce.

**Comment by JobcenterTycoon** [comment] 2019-07-20 02:12
i tried it again with default settings but i still get ads.

Browser: Firefox 68.0.1
uBlock version: uBlock Origin v1.20.2

**Comment by okiehsch** [comment] 2019-07-20 02:21
No ads for me with a deault setup.
Does your logger show any "media" requests?

**Comment by llacb47** [comment] 2019-07-20 02:22
Can't reproduce anti-adblock or preroll ads either.

**Comment by JobcenterTycoon** [comment] 2019-07-20 03:02
> 
> 
> No ads for me with a default setup.
> Does your logger show any "media" requests?

yes. example:

`https://db04ac130328ddea8d724cf.glomex.cloud/U2FsdGVkX1_J-pKAVVv80COjIpOmUpAVGl1LzVS-UY94F0eLhO6fIA63uMyzAg9WMl_pdSSkjqRryRRjlBM8Lq8y3CZP9UWWN8bKqMl2-nOCeIoX5srV75UWO4t8Lvq0?signature=30eff5ac24828526c969bf63063b730c4fb238d1&expires=1563592147075`
![mediarequests87496](https://user-images.githubusercontent.com/48647394/61573230-6577f280-aaab-11e9-824d-888f01d120c1.PNG)

**Comment by okiehsch** [comment] 2019-07-20 03:29
I get the glomex requests but not media requests on my end.

**Comment by lain566** [comment] 2019-07-20 04:52
@okiehsch I can't reproduce video ads on `cnn.gr`, but I can reproduce video ads on `merkur.de`.
They broke my solution, the only solution I found is this filter.

`player.glomex.com##+js(set-constant.js, parseInt, noopFunc)`

**Comment by okiehsch** [comment] 2019-07-20 05:09
> I can reproduce video ads on merkur.de.

 `player.glomex.com##+js(set-constant.js, parseInt, noopFunc)` works for me as well.

@JobcenterTycoon Does that filter also fix the pre-roll ads at `cnn.gr`?

**Comment by okiehsch** [comment] 2019-07-20 05:26
I tried some other glomex sites and the old solution does indeed not work anymore.
https://github.com/uBlockOrigin/uAssets/commit/83976efbf60d740bf35eac58f9317feb92d5fe49

**Comment by JobcenterTycoon** [comment] 2019-07-20 16:02
yes it works

**Comment by krystian3w** [comment] 2019-07-20 18:01
Possible kill `preroll`

`https://static.webcamera.pl/player/swinoujscie_cam_3be0ba-webcamera.html?preroll-wait=true`

Anti adblock should by fixed by:

 `@@||static.webcamera.pl/webcamera/ads.js$script,domain=static.webcamera.pl`

**Comment by lain566** [comment] 2019-07-20 18:59
@krystian3w I can't reproduce pre-roll ads. If I enable polish regional filters, I see many exception filters in the logger, maybe that's the problem.

This filter works for me instead of an exception filter.
`webcamera.pl##+js(setTimeout-defuser.js, hasAdblockCallback, 20000)`

**Closed** 2019-07-20 19:47 UTC
Labels: unable to reproduce
