### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by binhpham99** [uBlockOrigin/uAssets#20115] opened 2023-10-16 21:49 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=km9AHPk7mIs`

### Category

detection

### Description

Ad Blockers detected when using Youtube

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112666779/ea95256a-398d-4980-8a7c-3004a97c934c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 105459
 cosmetic: 39983
 scriptlet: 18709
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 71852-11, 11m
  easyprivacy: 33185-64, 11m
  plowe-0: 3729-1069, 11m
  ublock-badware: 7270-133, 11m
  ublock-filters: 34947-145, 11m
  ublock-privacy: 561-6, 11m
  ublock-quick-fixes: 233-92, 11m
  ublock-unbreak: 2137-31, 11m
  urlhaus-1: 11930-0, 11m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 146 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel:
 blocked: 18
 network:
  youtube.com: 1
  doubleclick.net: 3
  google.com: 14
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /(requiressl.*?)"adSlots.*…
  ##+js(trusted-replace-fetch-response, /(requiressl.*?)"adPlaceme…
  ##+js(trusted-replace-fetch-response, /(requiressl.*?)"playerAds…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
```
</details>

**Comment by 3kh0** [comment] 2023-10-16 21:51
Duplicate of #19976

**Closed** 2023-10-16 21:57 UTC
