### ISSUE TITLE
youtube detction

### ISSUE THREAD

**Issue by MocnyWariacik69** [uBlockOrigin/uAssets#20100] opened 2023-10-15 20:14 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

youtube detection adblock, i cleared cache and update filters

### URL(s) where the issue occurs.

https://www.youtube.com/

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/106545556/798fa9f7-1a1a-49d5-bf41-360f7eca0df5)

### uBO version

1.52.2

### Browser name and version

Google Chrome

### Settings

No one

### Notes

uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106869
 cosmetic: 47510
 scriptlet: 18909
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  POL-0: 7992-11, 26m
  POL-2: 1276-13, 26m
  easylist: 71743-34, 25m
  easyprivacy: 33201-64, 25m
  plowe-0: 3729-1076, 25m
  ublock-badware: 7302-134, 25m
  ublock-filters: 34960-182, 25m
  ublock-privacy: 561-6, 25m
  ublock-quick-fixes: 223-88, 25m
  ublock-unbreak: 2137-32, 25m
  urlhaus-1: 11950-0, 25m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 429 ms
 maxAssetCacheWait: 207 ms
popupPanel:
 blocked: 12
 network:
  github.com: 12

**Comment by gwarser** [comment] 2023-10-15 20:28
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19976

**Closed** 2023-10-15 20:28 UTC
