### ISSUE TITLE
I can't block facebook bottom corner popup

### ISSUE THREAD

**Issue by serial02** [uBlockOrigin/uAssets#16258] opened 2023-01-06 18:38 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello UBlock Origin team

 How to disable pop-up notifications in facebook settings?  The so-called pushes are all disabled, and even so, the bottom pop-up messages in the corner of the screen continue to appear.

 I have already disabled push calls and blocked pop-ups and notifications in page settings in the browser, but I have not been able to resolve this.  Can you help?

 I also used two different Adblock and none of them block this popup.
https://user-images.githubusercontent.com/32621790/211075611-e6d9d166-0bf2-43d2-8b79-98e9d650f6d8.png

### A specific URL where the issue occurs.

`https://www.facebook.com/`

### Steps to Reproduce

Appears sporadically even after disabling push notifications in facebook settings

### Expected behavior

That the pop-up no longer appears and is really definitely blocked

### Actual behavior

Does not block popup

### Configuration

https://user-images.githubusercontent.com/32621790/211077014-1d8f4f57-04d8-4b30-8dc8-51f94ac145fc.png

**Comment by garry-ut99** [comment] 2023-01-06 18:45
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/3367

**Closed** 2023-01-06 22:07 UTC
Labels: duplicate
