### ISSUE TITLE
movieweb.com: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#20490] opened 2023-11-06 16:37 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://movieweb.com/biggest-kaiju-movie-monsters/`

### Description

subscription request

AG fixed it with $cookie modifier, is there an other way since [uB0 doesn't support it](https://github.com/uBlockOrigin/uBlock-issues/issues/2926)?
https://github.com/AdguardTeam/AdguardFilters/commit/236ee4d13b1bb3c514788770da08291092b9776c

### Other extensions used

none

### Screenshot(s)

![dd](https://github.com/uBlockOrigin/uAssets/assets/1375223/2d5efaa2-80d0-43e6-bee9-14669e7e38a8)

### Configuration

<details>
<summary>Details</summary>

```yaml
default filters lists

```
</details>

**Comment by gorhill** [comment] 2023-11-06 16:43
Unable to reproduce using default settings/lists.

You will have to investigate this yourself.

**Comment by mapx-** [comment] 2023-11-06 16:45
@superlex you linked filters for other pages ?!
`xda-developers.com|androidpolice.com`

**Comment by gorhill** [comment] 2023-11-06 16:53
> AG fixed it with $cookie modifier,

You link to a commit that doesn't make use of `#cookie` modifier, it's the `remove-cookie` scriptlet, which is supported in uBO.

Anyway, closing this as this is an unactionable report, the troubleshooting information should always be provided, not removed, otherwise it's for OP to investigate on their side.

**Closed by gorhill** 2023-11-06 16:53 UTC
Labels: unable to reproduce

**Comment by superlex** [comment] 2023-11-06 17:12
@mapx- 
yes, because the issue (and the fix) was the same.

@gorhill 
I can no longer replicate it in any of three sites, sorry.  
Btw, AG make use of both #cookie modifier and remove-cookie scriptlet, the first one to prevent the cookie form being set, the second one to remove it (but it works only if you reload the page).
In other words, after you scrolled some articles:
 - using only the scriptlet you get the subscription request, but it's removed if you reload the page;
 - using the $cookie modifier you don't get the subscription request at all.

> Anyway, closing this as this is an unactionable report, the troubleshooting information should always be provided, not removed, otherwise it's for OP to investigate on their side.
You're right, sorry.

**Comment by gorhill** [comment] 2023-11-06 17:27
After navigating to how many articles is the overlay supposed to appear?

I see a cookie named `unauthenicatedArticleLimitReached` with value `false` in dev tools.

**Comment by superlex** [comment] 2023-11-06 17:41
> After navigating to how many articles is the overlay supposed to appear?

After 5/6 articles. 

> I see a cookie named unauthenicatedArticleLimitReached with value false in dev tools.

Yes, and after you reached the limit it's set to true.

> The code that make use of that cookie is in https://movieweb.com/public/build/valnet-footer-article.db7311a2.js

You' reright, infact the only way I found to remove the overlay was preventing trackUnauthenticatedArticleViews(), but it still wouldn't let you continue reading.

**Comment by stephenhawk8054** [comment] 2023-11-07 07:43
Which country are you when accessing the site?

**Comment by superlex** [comment] 2023-11-07 21:42
@stephenhawk8054 

Italy.
Do you think it could depend on this?

**Comment by superlex** [comment] 2023-11-11 15:17
Fixed here for  `xda-developers.com|androidpolice.com`
https://github.com/uBlockOrigin/uAssets/issues/20059
Simply add movieweb too.
