### ISSUE TITLE
zonafilm.in

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uAssets#9089] opened 2021-05-14 10:04 UTC
`zonafilm.in` is back on IP `http://144.91.105.32/`

in own CMS added block to select elements.

```
http://144.91.105.32/download-film-365-days-sub-indo-full-movie/
```

fyi:

* @Hakame-kun (uBlock-Filters-Indonesia)   (still not on official regional sources)
*  **`@realodix`** added fixes to AdBlockID https://github.com/realodix/AdBlockID/commit/08158078959faeb5f76dca376491fabd3ba69c30  (still not on official regional sources)
* @gmarcher (ABPindo)

**Comment by mapx-** [comment] 2021-05-14 19:40
@strict-block what's the issue here ?

**Comment by gmarcher** [comment] 2021-05-15 07:59
> 
> 
> @strict-block what's the issue here ?
maybe user can't right click and select text.

it's fine for ABPindo, and too few visitor

**Comment by uBlock-user** [comment] 2021-05-15 08:39
@gmarcher so the issue is addressed in ABPIndo list ?

**Closed** 2021-05-15 08:41 UTC

**Comment by strict-block** [comment] 2021-05-16 14:43
> what's the issue here ?

"added block to select elements."

**Comment by strict-block** [comment] 2021-05-16 14:47
> so the issue is addressed in ABPIndo list ?

must addresed if he no issues with selection and right click:

> >  it's fine for ABPindo
