### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by anggg1** [uBlockOrigin/uAssets#14479] opened 2022-08-21 16:44 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/queue`

### Category

ads

### Describe the issue

Not working on Spotify. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 81152
  cosmetic: 45370
  scriptlet: 17674
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69593-51, 2d.4h.6m
    easyprivacy: 27390-126, 2d.4h.5m
    plowe-0: 3630-777, 7d.8h.29m
    ublock-abuse: 76-0, 10d.9h.11m
    ublock-badware: 4243-92, 2d.4h.4m
    ublock-filters: 32513-121, 2d.4h.3m
    ublock-privacy: 231-3, 10d.9h.10m
    ublock-quick-fixes: 381-0, 1h.55m
    ublock-unbreak: 1829-41, 2d.4h.2m
    urlhaus-1: 5688-0, 1h.54m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 60505 ms (selfie)
  maxAssetCacheWait: 4862 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    spotify.com: 3
    googleoptimize.com: 1
    sentry.io: 12
```
</details>

**Comment by MasterKia** [comment] 2022-08-21 16:45
> I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Do it twice and test again.

**Comment by MasterKia** [comment] 2022-08-21 16:47
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14419#issuecomment-1221374376

**Closed by MasterKia** 2022-08-21 16:47 UTC
