### ISSUE TITLE
tranimeizle.net: popups

### ISSUE THREAD

**Issue by Darktowertr** [uBlockOrigin/uAssets#10631] opened 2021-11-27 14:23 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.tranimeizle.net/`

### Category

popups

### Describe the issue

Pop-up betting advertisement and betting site advertisements in the footer section

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 159123
  cosmetic: 75430
  scriptlet: 27427
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61615-663, 2d.7h.40m
    adguard-spyware: 25148-634, 2d.7h.40m
    adguard-spyware-url: 390-12, 2d.7h.40m
    block-lan: 44-0, 2d.7h.40m
    curben-phishing: 23724-0, 3h.5m
    curben-pup: 0-0, 3h.3m
    dpollock-0: 16966-202, 2d.7h.39m
    fanboy-thirdparty_social: 69-0, 2d.7h.39m
    mvps-0: 8730-1816, 2d.7h.39m
  default: 
    TUR-0: 8988-56, 2d.7h.40m
    easylist: 61081-994, 2d.7h.39m
    easyprivacy: 26314-10782, 2d.7h.39m
    plowe-0: 3699-1453, 2d.7h.39m
    ublock-abuse: 70-0, 2d.7h.39m
    ublock-badware: 3436-181, 2d.7h.39m
    ublock-filters: 29597-2840, 2d.7h.39m
    ublock-privacy: 188-24, 2d.7h.39m
    ublock-unbreak: 1694-101, 2d.7h.39m
    urlhaus-1: 10146-4, 3h.1m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [empty]
  triggered: 
    no-csp-reports: * true
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1099
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment] 2021-11-27 14:25
Why did you close the issue?

**Comment by gorhill** [comment] 2021-11-27 14:32
This works for me:

    tranimeizle.net##+js(nowoif)

The popup can be easily reproduce by removing all cookies and navigating to the page again.

**Closed** 2021-11-27 14:40 UTC
