### ISSUE TITLE
[nsfw] myvidster.com: popups

### ISSUE THREAD

**Issue by Regenbogenwaeldler** [uBlockOrigin/uAssets#20348] opened 2023-10-28 23:29 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.myvidster.com/`

### Category

popups

### Description

Sometimes, when you didn't use myvidster for a specific time, it starts to open a pop up window to a different NSFW page, when you click elsewhere on the website. After that, it takes a few hours, 'til this happens again.

### Other extensions used

True Key by McAffee
McAffee WebAdvisor
Crumbs
Volume Master
7TV
Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107250
 cosmetic: 45109
 scriptlet: 18945
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7165-0, 3m
  easylist: 72103-21, 3m
  easyprivacy: 32875-73, 3m
  plowe-0: 3722-1073, 2m
  ublock-badware: 7361-138, 2m
  ublock-filters: 35354-161, 2m
  ublock-privacy: 655-6, 2m
  ublock-quick-fixes: 184-123, 2m
  ublock-unbreak: 2134-35, 2m
  urlhaus-1: 11530-0, 2m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 924 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 9
 network:
  myvidster.com: 1
  disqus.com: 2
  exosrv.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  traffichaus.com: 1
  viglink.com: 2
 extended:
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by u-RraaLL** [comment] 2023-10-29 01:07
Duplicate of #20347

**Closed by u-RraaLL** 2023-10-29 01:06 UTC
