### ISSUE TITLE
youtube.com: [blocking video youtube]

### ISSUE THREAD

**Issue by test1111a1a** [uBlockOrigin/uAssets#20151] opened 2023-10-18 22:49 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Hvw2cNQUuUc`

### Category

[unknown]

### Description

youtube block the video, i cant see . i need to disable the ad blocker :'/

have a good day !

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/148399733/27ecf81b-96e3-4b41-9c06-8a814bea2205)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 122630
 cosmetic: 49002
 scriptlet: 18839
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-2, never
  FRA-0: 28470-39, 1h.46m
  easylist: 71825-95, 1h.46m
  easyprivacy: 33186-334, 1h.46m
  plowe-0: 3729-1080, 1h.46m
  ublock-badware: 7270-146, 1h.46m
  ublock-filters: 34966-221, 1h.46m
  ublock-privacy: 562-7, 1h.46m
  ublock-quick-fixes: 224-82, 1h.46m
  ublock-unbreak: 2125-36, 1h.45m
  urlhaus-1: 10360-0, 1h.45m
filterset (user): [array of 4 redacted]
trustedset:
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 255 ms (selfie)
 maxAssetCacheWait: 134 ms
popupPanel:
 blocked: 1
 network:
  doubleclick.net: 1
 extended:
  ###player-ads
  ###offer-module
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /(source=.*?)"adSlots.*?\}…
  ##+js(trusted-replace-fetch-response, /(source=.*?)"adPlacements…
  ##+js(trusted-replace-fetch-response, /(source=.*?)"playerAds.*?…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by 3kh0** [comment] 2023-10-18 22:54
Duplicate of #19976

**Comment by Sebastianroczz** [comment] 2023-10-18 23:11
THERE IS A THREAD FOR YOUTUBE REPORTS 
![image](https://github.com/uBlockOrigin/uAssets/assets/132775390/834101f3-ec43-4fdd-a3be-020b1f39f8bd)

**Closed** 2023-10-18 23:30 UTC
