### ISSUE TITLE
urldefense.com: breakage

### ISSUE THREAD

**Issue by ZCLINGER-NEFCO** [uBlockOrigin/uAssets#25350] opened 2024-09-17 17:40 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When visiting some URL's re-written by Proofpoint's URL Defense, uBlock somehow ends up breaking the URL. 

### A specific URL where the issue occurs.

`https://urldefense.com/v3/__https://www.portainer.io/hs/preferences-center/en/direct?data=W2nXS-N30h-M1W45lXqV2nFX8ZW3SzKNq3gnnN0W4cQh6C1Bnn1kW1VjfB24fr2-BW4mm3dy3T2wkqW2MWfBj49z9PPW4mqs512qWTfrW4px5K71Nn7N2W32DKbz1V7s-qW21bSln2KWpS4W1SdHmq2YwgS9W3P8RNt2r6W8pW49QSSt1_tcPsW3GSrf749CfyJW2PPdX33JPrgmW4hcHf84hm-NmW2FS2pd2sMKL-W2YGYkz43RS-9W4pjpV52t0rxlW3SB_f94psLW2W3_Sm6w2FGVTjW3K2-cG4fzZLWW2qDSdB3bzPyBW3j8X_q2PMxWzW36CtK22MvcXrW4hNdFB3DLWP3W3VMWNy3SYMyvW1Vs-MC43NZJNW4hLsTd2B1T2JW2sB9wk3DMh2mW2D0QS-2t04tYW43Cpv42Tz6SwW32rgcB3_SfvDW4mq1yB36nnnkW3BNLQw2YfSH9W49sKsP3z4zKPW3zd1YL1Zm6S3W4kmj3Z2sQ7WVW36xkSD2RSm5hW1Q0SqC30sK9ZW2-kSbQ2nH5KcW36fNc_2RjGNjW36pblN43qsbhW2CCNvJ3_SL29W1_sQHx4fqK9NW3Sy1cb4mpD3h0&utm_campaign=XNF&utm_source=hs_automation&utm_medium=email&utm_content=264158909&_hsenc=p2ANqtz--9JvIgI266aB1UVizENwYNYREZSotsXOhWcMNeKjZLJO9ZwmR9xlyfsQN2orbT25IymZ_vKUNTANMKQMVQBnzowi2339ExVoOKMJaHx0t2yn5esgg&_hsmi=264158909__;!!MlclJBHn!0eDf-zTf69h-IhFT9WDu2GIXAtCy6RENwguPVpTF1k2K-Nbnzy1NXix2Gj7azc8yDFyI2z3Tz4nTFuGe2hlLzsBl$`

### Steps to Reproduce

1) install uBlock Origin
2) click a URL re-written by Proofpoint

### Expected behavior

Redirect properly

### Actual behavior

uBO breaks the URL sending the user to Proofpoint's URL Defense Error page. 

### uBO version

1.59.0

### Browser name and version

Chrome / Firefox / Edge - Latest

### Operating System and version

Win11 Build 22621

**Comment by stephenhawk8054** [comment] 2024-09-18 00:03
> click a URL re-written by Proofpoint

Where can I click on that link? What are the steps to reproduce from beginning?

**Comment by ZCLINGER-NEFCO** [comment] 2024-09-18 00:17
I provided one of the URL's in the issue.
Proofpoint re-writes every email we get.

Literally we click any click re-written by Proofpoint and the issue happens with ublock.

Zach Clinger
Cyber Security Administrator, NEFCO

[https://www.gonefco.com/images/content/nefco_logo_sig.png]<https://www.gonefco.com/>

[https://www.gonefco.com/images/content/phone_sig.png]          Office  860-290-9044 x10232
[https://www.gonefco.com/images/content/email_sig.png]          Email   ***@***.***
[https://www.gonefco.com/images/content/web_sig.png]            gonefco.com<https://www.gonefco.com/>


[http://www.gonefco.com/images/content/emailSigUse.jpg]<https://catalogs.gonefco.com/Current-Promotion>


________________________________

**Comment by stephenhawk8054** [comment] 2024-09-18 01:09
> I provided one of the URL's in the issue.
> Proofpoint re-writes every email we get.
>
> Literally we click any click re-written by Proofpoint and the issue happens with ublock.

Yes, I know. I mean we need to know the original link that redirects to your link above. Your link above returns `Proofpoint's URL Defense Error` page even when I don't use any extensions.

**Comment by LogicalSoIutions** [comment] 2024-09-18 01:14
That's awkward, my apologies entirely. I copied the URL from the wrong browser.

This is directly from my inbox - trying this URL in a browser w/ no extensions will load ~ 

https://urldefense.com/v3/__https://www.portainer.io/hs/preferences-center/en/direct?data=W2nXS-N30h-RXW3b1JD94fpNscW38jq2n34vptMW2r8Bbd2r7HtcW2zvprG3by6zKW1XqbJ3237MD2W3z7W8x3_N7M4W2Mm7853X_7RzW3SZ-cq2nDCTFW3d2Flz3VMv_YW2sPPvG3_XswtW3LYyfs4cwPxNW2sBC2z1V2WK-W38sNjd1SvNHqW2xWHFb4hp9MrW1XdK0c47MnftW2KTjqF1V0nspW2PKtqs3BYSW3W3d7kyT2nGg7YW1ShBdX2KMXp1W2nXp7Z41-BlzW38rsbQ4hd581W2r1svW30jp73W4kN0Vp1Lv_LDW3VwDCR3j7HvHW1Lnpjf2v-FkrW4pc0zL2FvjT7W38D5pk32gwLtW2Pl2Bl2Kw-WwW2y22Z438cRcVW2HW91Y3G-9SHW1SyHt83ZG7PGW4kp1Rq3jtFjcW3VBnBh3B-9kQW4cCtRr3ZsJGgW2qLhSP1S0-qHW2p7vcn3yXRpNW4hwnzr2RBxDwW34nDKH3F1hDtW3bB94T4fsKK7W34FNfl32CRg2W4cH9bz1BxKzmW3yZYyb3DMMZkW1SzzHB3QRJrjW2zZkRD3R7nlCW1Z4ysB2Cxj2KW3SBvQX2vPDgp0&utm_campaign=XNF&utm_source=hs_automation&utm_medium=email&utm_content=264158264&_hsenc=p2ANqtz-_pWIackTRdeMquaUhgev9jqzueRVUdnhVfGNfe4FN-MHZjfLEB2L690m0Pcbe6sCpQD2Kl2L8du73D-0qIbUYg3TrgPbxdXcWWKAOCgDgyTvhnBgA&_hsmi=264158264__;!!MlclJBHn!yN4srhlJqWA-VKqLmm2Ko1T7WX660OU1Rat5J4m2fbFF3HEQwbtpe7jgr3fj5NyszctOE0Q0ZJ_l_88t6o1DlgsL$

It ultimately ends up at

https://www.portainer.io/hs/preferences-center/en/direct?data=W2nXS-N30h-RXW3b1JD94fpNscW38jq2n34vptMW2r8Bbd2r7HtcW2zvprG3by6zKW1XqbJ3237MD2W3z7W8x3_N7M4W2Mm7853X_7RzW3SZ-cq2nDCTFW3d2Flz3VMv_YW2sPPvG3_XswtW3LYyfs4cwPxNW2sBC2z1V2WK-W38sNjd1SvNHqW2xWHFb4hp9MrW1XdK0c47MnftW2KTjqF1V0nspW2PKtqs3BYSW3W3d7kyT2nGg7YW1ShBdX2KMXp1W2nXp7Z41-BlzW38rsbQ4hd581W2r1svW30jp73W4kN0Vp1Lv_LDW3VwDCR3j7HvHW1Lnpjf2v-FkrW4pc0zL2FvjT7W38D5pk32gwLtW2Pl2Bl2Kw-WwW2y22Z438cRcVW2HW91Y3G-9SHW1SyHt83ZG7PGW4kp1Rq3jtFjcW3VBnBh3B-9kQW4cCtRr3ZsJGgW2qLhSP1S0-qHW2p7vcn3yXRpNW4hwnzr2RBxDwW34nDKH3F1hDtW3bB94T4fsKK7W34FNfl32CRg2W4cH9bz1BxKzmW3yZYyb3DMMZkW1SzzHB3QRJrjW2zZkRD3R7nlCW1Z4ysB2Cxj2KW3SBvQX2vPDgp0&utm_campaign=XNF&utm_source=hs_automation&utm_medium=email&utm_content=264158264&_hsenc=p2ANqtz-_pWIackTRdeMquaUhgev9jqzueRVUdnhVfGNfe4FN-MHZjfLEB2L690m0Pcbe6sCpQD2Kl2L8du73D-0qIbUYg3TrgPbxdXcWWKAOCgDgyTvhnBgA&_hsmi=264158264

**Comment by ZCLINGER-NEFCO** [comment] 2024-09-18 01:18
That's awkward, my apologies entirely. I copied the URL from the wrong browser.

This is directly from my inbox - trying this URL in a browser w/ no extensions will load ~ 

https://urldefense.com/v3/__https://www.portainer.io/hs/preferences-center/en/direct?data=W2nXS-N30h-RXW3b1JD94fpNscW38jq2n34vptMW2r8Bbd2r7HtcW2zvprG3by6zKW1XqbJ3237MD2W3z7W8x3_N7M4W2Mm7853X_7RzW3SZ-cq2nDCTFW3d2Flz3VMv_YW2sPPvG3_XswtW3LYyfs4cwPxNW2sBC2z1V2WK-W38sNjd1SvNHqW2xWHFb4hp9MrW1XdK0c47MnftW2KTjqF1V0nspW2PKtqs3BYSW3W3d7kyT2nGg7YW1ShBdX2KMXp1W2nXp7Z41-BlzW38rsbQ4hd581W2r1svW30jp73W4kN0Vp1Lv_LDW3VwDCR3j7HvHW1Lnpjf2v-FkrW4pc0zL2FvjT7W38D5pk32gwLtW2Pl2Bl2Kw-WwW2y22Z438cRcVW2HW91Y3G-9SHW1SyHt83ZG7PGW4kp1Rq3jtFjcW3VBnBh3B-9kQW4cCtRr3ZsJGgW2qLhSP1S0-qHW2p7vcn3yXRpNW4hwnzr2RBxDwW34nDKH3F1hDtW3bB94T4fsKK7W34FNfl32CRg2W4cH9bz1BxKzmW3yZYyb3DMMZkW1SzzHB3QRJrjW2zZkRD3R7nlCW1Z4ysB2Cxj2KW3SBvQX2vPDgp0&utm_campaign=XNF&utm_source=hs_automation&utm_medium=email&utm_content=264158264&_hsenc=p2ANqtz-_pWIackTRdeMquaUhgev9jqzueRVUdnhVfGNfe4FN-MHZjfLEB2L690m0Pcbe6sCpQD2Kl2L8du73D-0qIbUYg3TrgPbxdXcWWKAOCgDgyTvhnBgA&_hsmi=264158264__;!!MlclJBHn!yN4srhlJqWA-VKqLmm2Ko1T7WX660OU1Rat5J4m2fbFF3HEQwbtpe7jgr3fj5NyszctOE0Q0ZJ_l_88t6o1DlgsL$

It ultimately ends up at

https://www.portainer.io/hs/preferences-center/en/direct?data=W2nXS-N30h-RXW3b1JD94fpNscW38jq2n34vptMW2r8Bbd2r7HtcW2zvprG3by6zKW1XqbJ3237MD2W3z7W8x3_N7M4W2Mm7853X_7RzW3SZ-cq2nDCTFW3d2Flz3VMv_YW2sPPvG3_XswtW3LYyfs4cwPxNW2sBC2z1V2WK-W38sNjd1SvNHqW2xWHFb4hp9MrW1XdK0c47MnftW2KTjqF1V0nspW2PKtqs3BYSW3W3d7kyT2nGg7YW1ShBdX2KMXp1W2nXp7Z41-BlzW38rsbQ4hd581W2r1svW30jp73W4kN0Vp1Lv_LDW3VwDCR3j7HvHW1Lnpjf2v-FkrW4pc0zL2FvjT7W38D5pk32gwLtW2Pl2Bl2Kw-WwW2y22Z438cRcVW2HW91Y3G-9SHW1SyHt83ZG7PGW4kp1Rq3jtFjcW3VBnBh3B-9kQW4cCtRr3ZsJGgW2qLhSP1S0-qHW2p7vcn3yXRpNW4hwnzr2RBxDwW34nDKH3F1hDtW3bB94T4fsKK7W34FNfl32CRg2W4cH9bz1BxKzmW3yZYyb3DMMZkW1SzzHB3QRJrjW2zZkRD3R7nlCW1Z4ysB2Cxj2KW3SBvQX2vPDgp0&utm_campaign=XNF&utm_source=hs_automation&utm_medium=email&utm_content=264158264&_hsenc=p2ANqtz-_pWIackTRdeMquaUhgev9jqzueRVUdnhVfGNfe4FN-MHZjfLEB2L690m0Pcbe6sCpQD2Kl2L8du73D-0qIbUYg3TrgPbxdXcWWKAOCgDgyTvhnBgA&_hsmi=264158264

**Comment by stephenhawk8054** [comment] 2024-09-18 01:43
> This is directly from my inbox - trying this URL in a browser w/ no extensions will load ~ 
> 
```yml
https://urldefense.com/v3/__https://www.portainer.io/hs/preferences-center/en/direct?data=W2nXS-N30h-RXW3b1JD94fpNscW38jq2n34vptMW2r8Bbd2r7HtcW2zvprG3by6zKW1XqbJ3237MD2W3z7W8x3_N7M4W2Mm7853X_7RzW3SZ-cq2nDCTFW3d2Flz3VMv_YW2sPPvG3_XswtW3LYyfs4cwPxNW2sBC2z1V2WK-W38sNjd1SvNHqW2xWHFb4hp9MrW1XdK0c47MnftW2KTjqF1V0nspW2PKtqs3BYSW3W3d7kyT2nGg7YW1ShBdX2KMXp1W2nXp7Z41-BlzW38rsbQ4hd581W2r1svW30jp73W4kN0Vp1Lv_LDW3VwDCR3j7HvHW1Lnpjf2v-FkrW4pc0zL2FvjT7W38D5pk32gwLtW2Pl2Bl2Kw-WwW2y22Z438cRcVW2HW91Y3G-9SHW1SyHt83ZG7PGW4kp1Rq3jtFjcW3VBnBh3B-9kQW4cCtRr3ZsJGgW2qLhSP1S0-qHW2p7vcn3yXRpNW4hwnzr2RBxDwW34nDKH3F1hDtW3bB94T4fsKK7W34FNfl32CRg2W4cH9bz1BxKzmW3yZYyb3DMMZkW1SzzHB3QRJrjW2zZkRD3R7nlCW1Z4ysB2Cxj2KW3SBvQX2vPDgp0&utm_campaign=XNF&utm_source=hs_automation&utm_medium=email&utm_content=264158264&_hsenc=p2ANqtz-_pWIackTRdeMquaUhgev9jqzueRVUdnhVfGNfe4FN-MHZjfLEB2L690m0Pcbe6sCpQD2Kl2L8du73D-0qIbUYg3TrgPbxdXcWWKAOCgDgyTvhnBgA&_hsmi=264158264__;!!MlclJBHn!yN4srhlJqWA-VKqLmm2Ko1T7WX660OU1Rat5J4m2fbFF3HEQwbtpe7jgr3fj5NyszctOE0Q0ZJ_l_88t6o1DlgsL$
```

Hmm... When I load this URL, I still see the same error even without any extensions

![image](https://github.com/user-attachments/assets/994bb69c-537f-4aaa-8848-57b4bebf4653)

**Comment by ZCLINGER-NEFCO** [comment] 2024-09-18 01:51
That's very strange - I've tested on all the machines that I was originally having issues with and on a fresh browser the issue does not exist for me.  o.O

If you'd like a HAR capture I'd be happy to provide one.

![ilZk 1](https://github.com/user-attachments/assets/06956fb8-6103-4ca1-aade-3d36a3146ae2)

![u3Oi](https://github.com/user-attachments/assets/6db7d4eb-c145-4233-9b4b-cebd3089c829)

**Comment by stephenhawk8054** [comment] 2024-09-18 02:02
Ok, looks like it's an issue with Firefox (at least in `Strict` mode) too. I can load the link successfully with chromium.

---

Can you test this filter?

```adb
*$removeparam=_hsenc,badfilter
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by ZCLINGER-NEFCO** [comment] 2024-09-18 02:05
Oh my lanta, that worked!! 

Thank you. 

Just like uBO can be applied via GPO, can this filter be added via filter as well? 

Thank you for the help, massively appreciated.

**Comment by stephenhawk8054** [comment] 2024-09-18 02:14
Fixed in https://github.com/uBlockOrigin/uAssets/commit/599212c931d42019878d2eea50081b52ca7ab2c9 . The filter lists will auto-update to users in about 5-6 hours.

**Closed** 2024-09-18 02:13 UTC

**Comment by stephenhawk8054** [comment] 2024-09-18 02:15
cc @Alex-302 @iam-py-test

**Comment by Alex-302** [comment] 2024-09-18 08:51
@stephenhawk8054 We have `@@||urldefense.com^$removeparam` for urldefense.com because of an error even with removing UTM params

https://github.com/AdguardTeam/AdguardFilters/issues/89618

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/205e7f7f-c650-4cb2-a24d-b236a4efcdb4)


</details>

**Comment by Alex-302** [comment] 2024-09-18 08:54
Hm. It seems the same problem with uBO when removing only UTMs

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/e81cdb9e-6003-4d44-a453-eb820470968b)


</details>

**Comment by iam-py-test** [comment] 2024-09-18 12:12
Thank you for informing me @stephenhawk8054, but the Actually Legitimate URL Shortener has the same exclusion as AdGuard, so it should not be impacted.
