### ISSUE TITLE
Midroll Ads Aren't being blocked CityTV.com

### ISSUE THREAD

**Issue by w4tadrag** [uBlockOrigin/uAssets#3847] opened 2018-10-26 21:04 UTC
Link:
`https://www.citytv.com/toronto/?video=5851984747001`

### Describe the issue
This is based on this issue https://github.com/uBlockOrigin/uAssets/issues/1173. It was able to block the beginning ads when the video starts, but it's not able to block midroll ads. 

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: uBlock Origin 1.17.0

### Settings
default settings

**Comment by ZaphodBeebblebrox** [comment] 2018-10-27 01:55
I'm region locked. @gorhill, you're canadian, right? Could you take a look at this?

**Comment by uBlock-user** [comment] 2018-10-27 06:38
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/1905

**Comment by kulfoon** [comment] 2018-10-27 06:46
> I'm region locked

So what, can't use e a proxy? https://www.google.pl/search?q=free+proxy+list

**Closed** 2018-10-27 08:05 UTC
