### ISSUE TITLE
Spotify stops playing music when an audio ad is loaded

### ISSUE THREAD

**Issue by SURE-E** [uBlockOrigin/uAssets#3561] opened 2018-09-24 19:16 UTC
### URL(s) where the issue occurs

`https://open.spotify.com/`

### Describe the issue

Spotify stops playing music when an audio ad is loaded. 

### Screenshot(s)

ℹ️ Coming soon.  

### Versions

- Browser/version: Version 69.0.3497.100 (Official Build) (64-bit)
- OS: Win10, V10.0.16299 Build 26299
- uBlock Origin version: uBlock Origin v1.16.18

### Settings

![image](https://user-images.githubusercontent.com/17045972/45972332-754cb480-c009-11e8-8245-174a10f7ee63.png)
![image](https://user-images.githubusercontent.com/17045972/45972356-8269a380-c009-11e8-8dff-be7cffc82fb2.png)

### Notes

1.  Unable to resume music by manually clicking play.  All buttons are disabled.
1.  Unable to resume music by pressing `F5` and then clicking play.  All buttons continue to be disabled.
1.  Unable to resume music by pressing `Ctrl` + `F5` and then clicking play.  All buttons continue to be disabled.  
1.  Unable to resume music by: 
    1. Login to spotify in incognito window
    1. Go back to original window
    1. Click Connect to a device > This Web Browser
        * ![image](https://user-images.githubusercontent.com/17045972/45973068-69fa8880-c00b-11e8-9373-1716d2bb74c3.png)
    1. Click play button
    - **Observe:  Nothing happens. Button appears active, but has no click behavior.**
1.  Sometimes able to resume music by: 
    1. Login to spotify in incognito window
    1. Click play button (in incognito window)
    1. Go back to original window
    1. Click Connect to a device > This Web Browser
        * ![image](https://user-images.githubusercontent.com/17045972/45973068-69fa8880-c00b-11e8-9373-1716d2bb74c3.png)
    1. Click play button
    - **Observe:  ~30% chance music resumes.**
1.  Also tried `Purge all caches` and `Update now`
        ![image](https://user-images.githubusercontent.com/17045972/45973668-1e48de80-c00d-11e8-9faf-c35b3a0bdec9.png)

**Comment by okiehsch** [comment] 2018-09-24 19:36
I can't reproduce, what is your OS ?

**Comment by krystian3w** [comment] 2018-09-25 13:19
https://github.com/CHEF-KOCH/CKs-FilterList/issues/36 - Windows 10?

**Comment by SURE-E** [comment] 2018-09-25 16:08
@okiehsch - OS is Win 10, v 10.0.16299 Build 16299.  Main reported updated. 
@krystian3w - The `CHEF-KOCH` filter is disabled because of that report.  You reckon it's not really disabled maybe?

**Comment by mapx-** [comment] 2018-09-25 16:21
Test again using only the default setup (no annoyances lists)

**Comment by SURE-E** [comment] 2018-09-25 17:32
@okiehsch - Roger.
@krystian3w - 😄 
@mapx- Affirmative.  Default restored.  Begining retest ...

**Comment by SURE-E** [comment] 2018-09-26 19:52
**Retest Results**: Issue persists
- `Making History` stopped playing.  
- Timer set itself to 0:00

To resume playback, I had to click the pause button a few times to get it to switch over to a play button.  Then I was able to click the play button.  

![image](https://user-images.githubusercontent.com/17045972/46105427-ecb64b80-c1a3-11e8-89a3-b6aef54363fc.png)

**Comment by mrsamse** [comment] 2019-01-08 13:53
I've got the same issue in Chrome (71.0.3578.98) on MacOS (10.14.2). After spamming the "pause button" 3 or 4 times it continues.

**Comment by okiehsch** [comment] 2019-01-09 03:17
https://github.com/uBlockOrigin/uAssets/issues/3561#issuecomment-424430274

I still can't reproduce using Chromium/Chrome and Windows 10 or Linux.
I can't test on a MacOS device.

**Comment by germaloney11** [comment] 2019-03-22 12:34
Can this pink/purple ad banner also be blocked please?
eg. `https://i.imgur.com/pplrcop.jpg`

Link: `https://open.spotify.com/browse/featured`

**Comment by nkoester** [comment] 2019-03-27 14:55
I encounter the same behaviour on firefox on linux:
```
$ uname -a
Linux 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux

$ firefox --version
Mozilla Firefox 66.0.1
```

I am using the same filter list as shown in the screenshots by @SURE-E and reloading the tab makes it work again. Sometime the tab also actually crashes and eats all memory it can get :/

**Comment by lightspeed397** [comment] 2019-05-04 21:37
I had a similar issue. What fixed my was disabling EasyPrivacy subscription list it was blocking a necessary spotify component.

**Comment by mapx-** [comment] 2019-05-04 21:52
> it was blocking a necessary Spotify component

What component (and what filter if you identified it in the logger) ?

**Comment by mapx-** [comment] 2019-05-22 13:06
closing for now.

**Comment by dshoreman** [comment] 2019-06-12 05:51
I'm getting a similar issue to @nkoester. It plays fine for a while, until it gets to ads. They get blocked, but the web player ends up consuming **all** available memory until the entire system grinds to a halt, forcing a hard reboot:

![image](https://user-images.githubusercontent.com/1521802/59325596-9bbb9880-8cdb-11e9-8c5c-c6a1b9d81032.png)

Prior to Spotify going insane, the Web Content process of firefox was only using around 2GB, with ~8GB free overall.

Sometimes if I catch it soon enough (within a few seconds), I can close the tab to "fix" it. Last time though, I was too late. Despite being able to close the tab, it wasn't soon enough for Firefox (67.0.2 on Arch) to free the RAM and the system still locked up.

Tried disabling the EasyPrivacy filter list, but it unfortunately didn't solve anything.

**Comment by mapx-** [comment] 2019-06-12 14:01
You should try these indications (not related specifically to adblockers)
https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Spotify-in-Firefox-Doesn-t-work/td-p/1669454

**Closed** 2019-06-14 12:16 UTC
Labels: unable to reproduce

**Comment by dshoreman** [comment] 2019-06-15 11:25
@mapx- The link you posted appears to solve a different issue where Spotify *doesn't work at all*, but that is not the case here.

The issue is **Spotify works *perfectly* until uBlock kicks in** and blocks the audio ads. At that point, it *immediately consumes **all** RAM*, crashing the system.

Now I've had some time to test, I disabled uBlock on the `open.spotify.com` domain to confirm that it works fine normally. Spotify successfully played its ads (ironically for Firefox):
![image](https://user-images.githubusercontent.com/1521802/59550760-92922c00-8f66-11e9-825a-2dce5198f967.png)
...then continued to play without issue.

It's played through two blocks of ads so far, and memory usage still hasn't increased.

**Comment by mapx-** [comment] 2019-06-15 12:19
- tested in FF, I got ads .. but no issue .. the memory is ok
- could you add 
`@@||spotify.com/$xhr,1p`

and test again ?

**Comment by dshoreman** [comment] 2019-06-16 08:19
Tested with the exception but the tab still froze on the first ad. I managed to get a screenshot of the logger before killing Firefox, but I'd already closed the tab (hoping it would stop eating RAM... it didn't) so excuse the dimness:

![image](https://user-images.githubusercontent.com/1521802/59561244-e576ec80-9015-11e9-8621-a6b4b027c904.png)

I'll test some more with uBo disabled to see if I can find anything obvious when the ads play. Searching up older bugs it seems a similar issue in 2017 [didn't happen in playlists](https://github.com/uBlockOrigin/uAssets/issues/724#issuecomment-353432503), so I might try a playlist later in case that still applies. If it does, it could help to find some differences.

**Comment by dshoreman** [comment] 2019-06-16 11:57
@mapx- Going to keep playing for a while longer then test the same rules in Firefox, but so far it's been going for about an hour in Chrome (with two ad breaks as far as I can tell)

![image](https://user-images.githubusercontent.com/1521802/59563680-174b7b80-9035-11e9-8f39-81773e8134dd.png)

Current filters:
```
@@||securepubads.g.doubleclick.net/pcs/*$xmlhttprequest,domain=open.spotify.com
@@||pubads.g.doubleclick.net/pagead/conversion/*$xmlhttprequest,domain=open.spotify.com
```

I tried the `doubleclick.net/pcs` rule first, but still had the issue so added the second one. Still need to test further to see if it needs both exceptions or only the conversion one - will post back later.

**Comment by MartinLichtblau** [comment] 2019-10-02 14:51
@dshoreman Is Spotify running stable now? I tried your filters but it still still crashes in Chrome when an advertisement appears.

**Comment by dshoreman** [comment] 2019-10-28 21:24
@MartinLichtblau I only ended up using the second rule—the first rule in my previous comment is commented out in my filters. Iirc, with both rules enabled it would still crash occasionally.

That said, I rarely use Spotify now. Last time I *did* use it I was able to play music all day without issues, but that was more than a couple months ago so it's entirely possible something else has changed since.

**Comment by lightspeed397** [comment] 2019-12-10 19:06
Sorry for the delay in my response, I haven't used spotify for several months, until recently but for the past few weeks since I've been using spotify I have not had a Problem even with Easy spotify enabled, so the issue seems to be fixed for me anyway.

**Comment by dotSomething** [comment] 2020-01-17 14:27
:information_source: Issues persists for me.  I've tried @dshoreman's filter too. 

I saw these calls being blocked every several seconds during playback.  They did not stop the player: 
![image](https://user-images.githubusercontent.com/17045972/72616862-c6bb3a00-3905-11ea-8680-3c96848a2400.png)

I saw these calls in between songs.  They did not stop the player: 
![image](https://user-images.githubusercontent.com/17045972/72616989-0a15a880-3906-11ea-89a2-5a3ec2304ea2.png)

Here's the block of calls I saw when the player stopped: 
![image](https://user-images.githubusercontent.com/17045972/72619347-09334580-390b-11ea-8bc9-1d959afdb647.png)

I'm guessing the culprit is `spclient` since the other calls had not previous stopped playback?  I was able to resume playback thereafter, but playback began skipping songs in the playlist.  

@lightspeed397 - What's `Easy spotify`?  I don't see that as option in `Filter Lists`.

**Comment by SleepyKitten-Games** [comment] 2021-06-27 21:04
@dshoreman:
> Current filters:
> 
> ```
> @@||securepubads.g.doubleclick.net/pcs/*$xmlhttprequest,domain=open.spotify.com
> @@||pubads.g.doubleclick.net/pagead/conversion/*$xmlhttprequest,domain=open.spotify.com
> ```
I put those filters into My Filters, it still only blocks Spotify ads sometimes, and the site also sometimes gets confused.
After around 10-15 songs, an ad will try to play but then get blocked, and songs will start playing again. Then after another 10-15 songs, another ad will try to play, it will get blocked, and then the site will get stuck:
![image](https://user-images.githubusercontent.com/24967983/123559046-c1535780-d767-11eb-9272-7fcebf28639f.png)
Pressing the pause button resumes the music. It only works like that on the actual Spotify page, however - doing the same series of actions in Chrome's audio controls just removes Spotify from the list of audio sources (specifically, it either seems to get removed when you press pause again or it gets removed automatically when the ad gets blocked and Spotify gets stuck) and you have to navigate back to Spotify to get the songs playing again.
Ideally I would prefer to not have to press the pause button to bring the songs back, especially since I often use the Chrome audio controls panel to navigate/pause songs while I am working on other tabs. 
Interestingly, this does not happen if I use the app to skip songs - so far I have not had to pause the songs to bring music back when I am using exclusively the app.
Desktop OS: Windows 10 version 20H2
Chrome version: 91.0.4472.114 (Official Build) (64-bit)

Mobile OS: Android version 8 (I'm not able to update to anything beyond 8, it's a Samsung S7 so it doesn't have access to the higher versions)
Spotify app version: 8.6.36.1070
