### ISSUE TITLE
freep.com: ads

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#23124] opened 2024-03-31 14:54 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freep.com/story/sports/mlb/tigers/2024/03/31/detroit-tigers-opening-day-2024-comerica-park-parking-tickets-traffic/73135890007/`

### Category

ads

### Description

Shows leftover ads to the sides of the article

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/c229f765-29d0-4908-a354-e30bcd1d8318)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 221905
 cosmetic: 46133
 scriptlet: 19734
 html: 1723
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1491-106, 2m
  block-lan: 61-0, 2m
  curben-phishing: 14052-3, 2m
  dpollock-0: 11664-461, 2m
  adguard-spyware: 100833-32277, 2m
 default:
  user-filters: 6-0, never
  ublock-filters: 37659-138, 4m Δ
  ublock-badware: 8065-15, 4m Δ
  ublock-privacy: 777-0, 4m Δ
  ublock-unbreak: 2307-1, 4m Δ
  ublock-quick-fixes: 183-0, 4m Δ
  easylist: 84577-934, 4m Δ
  easyprivacy: 50423-940, 4m Δ
  urlhaus-1: 8680-5, 2m
  plowe-0: 3762-0, 2m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 31 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 245 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel: null
```
</details>

**Comment by ItsProfessional** [comment] 2024-03-31 16:05
Duplicate of #23120. See my comment here: https://github.com/uBlockOrigin/uAssets/issues/23120#issuecomment-2028805866

**Closed by ItsProfessional** 2024-03-31 16:05 UTC
