### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by haydnphilipdesign** [uBlockOrigin/uAssets#20002] opened 2023-10-07 11:03 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

detection

### Description

youtube popup overlay preventing playback unless ads are allowed

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 114398
 cosmetic: 189037
 scriptlet: 28886
 html: 1246
listset (total-discarded, last-updated):
 added:
  adguard-social: 21847-856, now
  fanboy-cookiemonster: 48486-3879, now
  fanboy-social: 16234-9, now
  ublock-annoyances: 5471-7, now
  adguard-cookies: 27780-63, now
  adguard-popup-overlays: 24558-1604, now
  adguard-mobile-app-banners: 4647-8, now
  adguard-other-annoyances: 13628-312, now
  adguard-widgets: 2312-4, now
  easylist-annoyances: 3986-130, now
  easylist-chat: 141-11, now
  easylist-newsletters: 6522-20, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 35868-402, now
  ublock-badware: 7188-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2183-0, now
  ublock-quick-fixes: 178-0, now
  easylist: 71567-784, now
  easyprivacy: 33214-809, now
  urlhaus-1: 10870-0, now
  plowe-0: 3718-1, now
filterset (user): [array of 4 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 518 ms (selfie)
 maxAssetCacheWait: 218 ms
popupPanel:
 blocked: 44
 network:
  youtube.com: 25
  doubleclick.net: 5
  google.com: 14
 extended:
  ##.ytp-share-button
  ###player-ads
  ###social-links
  ##tp-yt-paper-dialog.ytd-popup-container.style-scope > .ytd-popu…
  ###ticker.ytd-masthead
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, …
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune-fetch-response, [].playerResponse.adPlacements…
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/,…
```
</details>

**Comment by gwarser** [comment] 2023-10-07 11:07
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19976

**Closed by gwarser** 2023-10-07 11:07 UTC
