### ISSUE TITLE
Blocking PayPal payments on eBay in Chrome

### ISSUE THREAD

**Issue by mre33** [uBlockOrigin/uAssets#6987] opened 2020-02-22 14:52 UTC
### Description

Within the last two weeks I have been unable to pay for items on eBay using PayPal.  

At checkout, after providing PayPal credentials, the pop-up box that opens never loads.  The small rotating circle goes on forever. 
After much testing I disabled UBlock and eliminated the issue.  I have since turned off UBlock for that PayPal address and things are back to normal. 

Apparently UBlock is now blocking some url needed by the PayPal - eBay gateway.  As this issue is very hard for the average user to identify I thought a bug report was in order. 
In an earlier call to eBay tech support they were unable to identify the problem and said they were getting lots of reports.  I think this may be causing widespread issues and needs to be addressed.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [click buy it now on any ebay item]
2. [select PayPal as payment method]
3. [provide your credentials in PayPal window]

### Expected behavior:

[PayPal logs you in and allows payment]

### Actual behavior:

[Window never loads.  Sits forever with rotating circle.]

### Your environment

* uBlock Origin version: 1.23
* Browser Name and version: Google Chrome or Edge Chromium
* Operating System and version: Windows 10 Pro

**Comment by mapx-** [comment] 2020-02-22 15:03
I tested on my side and I landed on the `Confirm and pay` page (stopped there because it's only a test). So, no issue on my side.

0. reset uBO to default settings
1. purge & update all the lists
2. test again.

**Comment by mre33** [comment] 2020-02-22 15:36
The reset and purge does appear to fix the issue.  That said, eBay tech support is apparently unaware of what is causing this problem.  If it could be narrowed down to the specific url or setting and fixed without action by end users that would be good.  If there is a way to make eBay aware that would also be good.

**Comment by mapx-** [comment] 2020-02-22 15:40
You should narrow down the cause if now it works with default settings.
Maybe you added some other lists, some custom filter ?

**Closed by mapx-** 2020-02-22 15:40 UTC

**Comment by mre33** [comment] 2020-02-22 15:54
Actually, other than disabling it on a very few websites I don't recall ever touching the settings.  In fact I recently switched browsers from Chrome to Edge Chromium and had installed a fresh copy of uBO on it so it should have been stock.  Now that I did the reset/purge it would be impossible to debug unless it starts to exhibit the problem again.  If it does I will dig a little deeper.

What finally tipped me off to suspect uBlock was an answer in some forum comment somewhere that I found after doing a Google search for the issue.  I saw lots of people with the same issue so I suspect it has caused a few problems.  One other interesting thing is that Internet Explorer with uBlock running would still work on eBay/PayPal.  I think maybe it uses a different path to enable payments.

**Comment by mre33** [comment] 2020-02-22 16:02
Scratch that last sentence.  uBlock is not on Internet Explorer.

**Comment by mapx-** [comment] 2020-02-22 16:06
I fixed yesterday an issue on paypal but something about mastercard
https://github.com/uBlockOrigin/uAssets/issues/6978

Maybe it was the same issue ..

**Comment by mre33** [comment] 2020-02-22 16:22
Very similar if not the same.  Thanks for your responses!  Hopefully the issue is fixed.

**Comment by uBlock-user** [comment] 2020-02-22 16:24
> Scratch that last sentence. uBlock is not on Internet Explorer.

IE doesn't support extensions of any kind.

**Comment by mre33** [comment] 2020-02-22 16:45
IE does support add-ons.  I have LastPass and a few others running on it but I very seldom use it for anything other than testing my web designs or accessing my old cameras with ActiveX.  I did use it to test the eBay/PayPal issue and mistakenly thought it had uBO installed.
