### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by durali07** [uBlockOrigin/uAssets#11126] opened 2021-12-29 18:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/watch?v=VIJO1fAuGbI&list=PLbSAmJpE_X5MBHyoPDLMmkc_g1eiemgw-&index=23`

### Category

ads

### Describe the issue

aralarda reklem çıktı

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 80228
  cosmetic: 47032
  scriptlet: 16841
  html: 0
listset (total-discarded, last updated): 
  default: 
    TUR-0: 9451-98, 3d.2h.10m
    easylist: 62259-19, 3d.2h.8m
    easyprivacy: 26552-22, 3d.2h.6m
    plowe-0: 3691-812, 12d.4h.27m
    ublock-abuse: 81-0, 3d.2h.4m
    ublock-badware: 3629-65, 3d.2h.2m
    ublock-filters: 30146-152, 3d.2h
    ublock-privacy: 193-2, 3d.1h.58m
    ublock-unbreak: 1704-39, 3d.1h.56m
    urlhaus-1: 7737-0, 21h.21m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6419
  launchFromSelfie: true
popupPanel: 
  blocked: 454
```
</details>

**Comment by gwarser** [comment] 2021-12-29 18:29
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

@durali07 if it happened on Chrome startup, Ctrl+F5 should fix it.

**Closed by gwarser** 2021-12-29 18:29 UTC
