### ISSUE TITLE
 hotcleaner.com

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#8555] opened 2021-02-10 07:51 UTC
### URL(s) where the issue occurs

`https://www.hotcleaner.com/`

### Describe the issue

Cookies

### Screenshot(s)
`https://www.hotcleaner.com/`

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/107480218-ecf0ef00-6b84-11eb-9ab8-48286aed5861.png)
</details>

`https://www.hotcleaner.com/whitelist-the-website-in-adblock.html`
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/107480306-06923680-6b85-11eb-9a33-a68030cb3424.png)
</details>

`https://www.hotcleaner.com/clickclean_chrome.html`
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/107480334-1447bc00-6b85-11eb-8c2b-10f84566e3cf.png)
</details>

### Versions

- Browser/version:  Google Chrome
- uBlock Origin version: 1.33.2

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by Alex4567890** [comment] 2021-02-10 08:38
Posted on the EasyList Forum (forums.lanik.us)

**Comment by uBlock-user** [comment] 2021-02-10 08:40
Not seeing the cookies overlay but rather an anti-adblock annoyance -- 

```
hotcleaner.com##.adsbygoogle:upward(1)
hotcleaner.com##+js(nostif, /adblock|hidden/)
```

**Comment by P0Rtvine** [comment] 2021-02-10 08:51
@uBlock-user 
Yep it works!

**Comment by ryanbr** [comment] 2021-02-10 08:51
No cookie on `hotcleaner.com`

**Comment by uBlock-user** [comment] 2021-02-10 09:00
> But not stable

The script is at the very top and is using `MutationObserver`, would have to stop/break that one.

**Comment by P0Rtvine** [comment] 2021-02-10 09:01
@ryanbr 
`https://www.hotcleaner.com/cookie-editor/`

<details>
<summary>Screen</summary>

![2021-02-10_105933](https://user-images.githubusercontent.com/57287308/107487739-29294d00-6b8f-11eb-936d-6d34d90b507a.png)
</details>

Perhaps only for Europeans?

**Comment by mapx-** [comment] 2021-02-10 09:02
try

`||googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=hotcleaner.com,redirect-rule=googlesyndication_adsbygoogle.js`

I got cookies but after a while not anymore

**Comment by uBlock-user** [comment] 2021-02-10 09:02
That's an annoyance, won't be fixed in uBO lists as you can close it and doesn't require extended syntax.

**Comment by uBlock-user** [comment] 2021-02-10 09:04
@mapx- Won't stop the placeholders from appearing after a while.

**Comment by P0Rtvine** [comment] 2021-02-10 09:06
@mapx- 
> try
> 
> `||googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=hotcleaner.com,redirect-rule=googlesyndication_adsbygoogle.js`

Nothing changed

**Comment by mapx-** [comment] 2021-02-10 09:08
my filter was only for anti adb warning

**Comment by uBlock-user** [comment] 2021-02-10 09:08
For Firefox adding `hotcleaner.com##^script:has-text(MutationObserver)` does the job.

**Comment by uBlock-user** [comment] 2021-02-10 09:53
@P0Rtvine how about `hotcleaner.com##.adsbygoogle:upward(1):remove()` instead ?

**Comment by P0Rtvine** [comment] 2021-02-10 13:13
@uBlock-user 
Doesn't work on all pages, and you don't hide cookie messages, and EasyList doesn't support such syntax.

`https://www.hotcleaner.com/clickclean_firefox.html` https://imgur.com/AwEwauK
`https://www.hotcleaner.com/webcam-test/`  https://imgur.com/tbj4pod
`https://www.hotcleaner.com/cookie-editor/` https://imgur.com/9jblGrk

**Comment by uBlock-user** [comment] 2021-02-10 13:38
@P0Rtvine the filter I asked is for anti-adb and the huge placeholder it creates, does it work for that or not ?

**Comment by P0Rtvine** [comment] 2021-02-10 13:41
@uBlock-user  
Yes, it works

**Comment by uBlock-user** [comment] 2021-02-10 13:57
For cookie-overlay, you can add `hotcleaner.com##.bqF`

**Comment by P0Rtvine** [comment] 2021-02-10 14:01
There is a random class https://imgur.com/AwEwauK

**Comment by uBlock-user** [comment] 2021-02-10 14:03
Generated by shadow-root which is closed...

**Comment by P0Rtvine** [comment] 2021-02-10 14:07
Can't hide it? This is my first time seeing this for cookies

**Comment by uBlock-user** [comment] 2021-02-10 14:12
Won't work for everyone, try -- `hotcleaner.com##+js(aopr, Element.prototype.attachShadow)`

**Comment by P0Rtvine** [comment] 2021-02-10 14:16
The scriptlet works, can be added to uBlock filters- Annoyances as an exception?

**Comment by uBlock-user** [comment] 2021-02-10 14:24
Does it work after you reboot the browser and open the website or after opening the site in a new tab ?

**Comment by P0Rtvine** [comment] 2021-02-10 14:26
No, alas it doesn't work.
The scriptlet, works every other time, not a panacea, you can close the topic.

**Closed** 2021-02-10 14:28 UTC

**Comment by dimisa-RUAdList** [comment] 2021-02-10 15:33
I don't get a cookie warning.

But judging by the screenshot from the first post, there is enough: `hotcleaner.com##style:first-child + div[class] + div[class]`

**Comment by P0Rtvine** [comment] 2021-02-11 07:26
@gorhill 
I can't bypass the overlay without accepting cookies, right?
uBO can't replace cookies.
http://ipic.su/7yPyKI.png

**Comment by wout-codes** [comment] 2021-02-11 07:32
@P0Rtvine Fixed in AdGuard Annoyances and Base filters.

**Comment by mapx-** [comment] 2021-02-11 07:55
test

`hotcleaner.com##[class]:matches-css(position: fixed)`

**Comment by uBlock-user** [comment] 2021-02-11 08:22
To avoid false positives, add `div` -- `hotcleaner.com##div[class]:matches-css(position: fixed)`

**Comment by dimisa-RUAdList** [comment] 2021-02-11 09:11
Or: `hotcleaner.com##body > div[class]:matches-css(position: fixed)`

**Comment by dimisa-RUAdList** [comment] 2021-02-11 12:02
@ryanbr 
As far as I understand, for EasyList Cookie you can add a rule like:
`hotcleaner.com#?#body > div[class]:-abp-properties(position: fixed)`

**Comment by mapx-** [comment] 2021-02-11 12:18
`-abp-properties` is not translated by uBO, so I'll add our syntax to uBO annoyances

**Comment by P0Rtvine** [comment] 2021-04-20 10:38
Cookies again
<details>
<summary>Gif</summary>

![112](https://user-images.githubusercontent.com/57287308/115382212-1c535600-a1dd-11eb-83d6-aa8014cdc9b2.gif)
</details>

**Comment by P0Rtvine** [comment] 2021-04-20 17:20
@uBlock-user

**Comment by uBlock-user** [comment] 2021-04-20 17:39
How dod I reproduce the cookie overlay ? Added filter for ad-placeholders.

**Comment by dimisa-RUAdList** [comment] 2021-04-20 18:11
`hotcleaner.com##style:first-child ~ div` ?

**Comment by P0Rtvine** [comment] 2021-04-20 18:18
@dimisa-RUAdList 
`hotcleaner.com##style:first-child ~ div`
Scrolling with the wheel does not work.

@uBlock-user 
May be VPN?

**Comment by mapx-** [comment] 2021-04-20 18:27
> How do I reproduce the cookie overlay ? Added filter for ad-placeholders.

close the tab, remove cookies + cache, reopen the tab

**Comment by uBlock-user** [comment] 2021-04-20 18:30
> close the tab, remove cookies + cache, reopen the tab

No change, tried with Polish and Russian VPN, still nothing.

**Comment by mapx-** [comment] 2021-04-20 18:36
@P0Rtvine  test for breakage

`hotcleaner.com##+js(aopr, String.fromCharCode)`

**Comment by P0Rtvine** [comment] 2021-04-20 19:10
@mapx- 
> hotcleaner.com##+js(aopr, String.fromCharCode)

does not work stably

May be?
`hotcleaner.com##body > div[id]:matches-css(position: fixed):style(visibility: hidden !important)`

@uBlock-user 
> ad-placeholders


<details>
<summary>Screen</summary>

![2021-04-20_220834](https://user-images.githubusercontent.com/57287308/115450924-2c8f2380-a225-11eb-96f7-ef9e3db49d34.png)
</details>

**Comment by uBlock-user** [comment] 2021-04-20 19:33
Removed the previously added ad-placeholder added filters, fixed anti-picker script for FF.

**Comment by P0Rtvine** [comment] 2021-04-21 06:56
@uBlock-user 

It works for me

`hotcleaner.com##body > div[id]:matches-css(position: fixed):style(visibility: hidden !important)` ?

<details>
<summary>Gif</summary>

![112](https://user-images.githubusercontent.com/57287308/115509636-5416d800-a287-11eb-9727-ba432f9c926c.gif)
</details>

**Comment by P0Rtvine** [comment] 2021-04-21 09:00
`hotcleaner.com##body > div[class]:matches-css(position: fixed)`

This rule is also required here
`https://www.hotcleaner.com/cookie-editor/`

<details>
<summary>Screen</summary>

![2021-04-21_115751](https://user-images.githubusercontent.com/57287308/115526869-26d32580-a299-11eb-81ae-87e7fd083f81.png)
</details>

**Comment by stephenhawk8054** [comment] 2021-12-14 03:06
I think the html script filter:

`hotcleaner.com##^script:has-text(Function.prototype.apply)`

breaks the button `Click&Clean for Mozilla Firefox` in Firefox now. Clicking on it has no reactions.

URL: `https://www.hotcleaner.com/clickclean_firefox.html`

![image](https://user-images.githubusercontent.com/66517106/145925258-d0f68f55-221b-4146-bb97-d9f3db84a3ac.png)

However, whitelisting that filter causes the cookie banner flashes (appears and disappears) continuously (maybe because of `MutationObserver` that's mentioned above?), unless I whitelist this filter too:

`hotcleaner.com##body > div[class]:matches-css(position: fixed)`
