### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by JustHackedTV** [uBlockOrigin/uAssets#18773] opened 2023-07-01 19:22 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/` Still shows adds

### Category

ads

### Description

a

### Other extensions used

a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.1h.29m
Firefox: 114
filterset (summary):
 network: 94047
 cosmetic: 42690
 scriptlet: 18065
 html: 971
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34557-41, 15h.37m
  ublock-badware: 7672-1, 15h.36m
  ublock-privacy: 457-0, 4d.20h.2m
  ublock-unbreak: 2094-0, 15h.35m
  ublock-quick-fixes: 276-45, 1h.20m
  easylist: 67511-774, 4d.20h
  easyprivacy: 30611-625, 4d.19h.59m
  urlhaus-1: 5224-0, 15h.32m
  plowe-0: 3737-1, 8d.20h.20m
  spa-1: 5314-34, 15h.33m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 188986 ms (selfie)
 maxAssetCacheWait: 907 ms
popupPanel:
 blocked: 53
 network:
  amazon-adsystem.com: 2
  d2v02itv0y9u9t.cloudfront.net: 1
  google-analytics.com: 1
  imrworldwide.com: 1
  scorecardresearch.com: 46
  sentry.io: 2
 extended:
  ##+js(window.open-defuser, amazon-adsystem)
```
</details>

**Comment by okiehsch** [comment] 2023-07-01 19:23
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by okiehsch** 2023-07-01 19:23 UTC
