### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18446] opened 2023-06-10 04:06 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aliexpress.com/category/21/education-office-supplies.html?category_redirect=1`

### Category

breakage

### Description

On Firefox, when ublock filters - Ads , is enabled. The product boxes does not appear.

### Screenshot(s)

![Screenshot 2023-06-10 060524](https://github.com/uBlockOrigin/uAssets/assets/19490515/f628c77d-8128-4498-947e-083a4ae7fae4)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 244961
 cosmetic: 174926
 scriptlet: 26129
 html: 1108
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2220-0, 7m
  adguard-spyware-url: 1065-144, 7m
  block-lan: 47-0, 7m
  curben-phishing: 109850-36, 7m
  curben-pup: 199-0, 7m
  adguard-social: 20487-806, 7m
  fanboy-thirdparty_social: 69-0, 7m
  fanboy-cookiemonster: 47410-3783, 7m
  fanboy-social: 16069-19, 7m
  ublock-annoyances: 5027-7, 7m
  NOR-0: 3203-11, 7m
  adguard-spyware: 43636-13707, 7m
  adguard-cookies: 25834-42, 7m
  adguard-popup-overlays: 22620-1277, 7m
  adguard-other-annoyances: 12817-65, 7m
  easylist-newsletters: 6088-11, 7m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34344-430, 1m
  ublock-badware: 7347-0, 9m
  ublock-privacy: 435-2, 9m
  ublock-unbreak: 2045-0, 9m
  ublock-quick-fixes: 198-0, 9m
  easylist: 66968-782, 9m
  easyprivacy: 31000-614, 9m
  urlhaus-1: 6309-0, 9m
  plowe-0: 3734-2, 9m
filterset (user): [empty]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1635 ms
 maxAssetCacheWait: 8 ms
popupPanel: 
 blocked: 21
 network: 
  creativecdn.com: 1
  criteo.net: 1
  ds-aksb-a.akamaihd.net: 1
  facebook.net: 1
  go-mpulse.net: 1
  google-analytics.com: 1
  google.com: 1
  mmstat.com: 13
  yandex.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment] 2023-06-10 04:30
Can you test if adding this filter works?

```adb
aliexpress.com#@#div[data-spm="main"] > a[class*="--container--"] span[class*="--ad--"]:upward(div[data-spm="main"] > a[class*="--container--"])
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > Click &#10003; `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` to reload the page and test again.

**Comment by Schanzation** [comment] 2023-06-10 12:10
Yes, when I added that to "My Filters" it works as normal

**Comment by stephenhawk8054** [comment] 2023-06-10 12:29
Are you using any other extensions?

**Comment by Schanzation** [comment] 2023-06-10 12:36
![Screenshot 2023-06-10 143430](https://github.com/uBlockOrigin/uAssets/assets/19490515/0471ba98-b8dd-41ef-a8a3-58448674f0f9)

I tried disabling user-agent switcher and localCDN but problem still the same. Guess I just have to use this website in private window or another browser

**Comment by stephenhawk8054** [comment] 2023-06-10 12:39
Can you do these steps:

1. Turn off all other extensions and test again
2. If it still happens, create another firefox profile with only uBO's default settings (don't enable or add any other filter lists)

**Comment by Schanzation** [comment] 2023-06-10 12:45
Thanks. I'll make a new profile later. Disabling all other extensions didn't work. Opening Firefox in "New private window" with ublock origin with default settings works.

**Comment by stephenhawk8054** [comment] 2023-06-10 13:09
> Yes, when I added that to "My Filters" it works as normal, but the first page is boxes with ads.

Keep the filter above. Does this filter hide the ads for you?

```adb
aliexpress.com##div[data-spm="main"] > a[class*="--container--"][href*="&aem_p4p_detail"]
```

**Comment by Schanzation** [comment] 2023-06-10 13:20
No, it hide the products. Hide everything.

**Comment by stephenhawk8054** [comment] 2023-06-10 13:24
Does it happen when you sign in or sign out?

**Comment by Schanzation** [comment] 2023-06-10 13:32
Doesn't seem to make a difference

**Comment by stephenhawk8054** [comment] 2023-06-10 13:42
Quite strange. I cannot reproduce it though trying in many ways. We'll need to see if there would be other reports to have more information about this. For now let's wait if there are others that can reproduce it or not. 

If no one can reproduce it for some time, we will close the issue. But just keep the above filter and you can continue commenting here when you find more information, we all get notified with new comments even when the issue is closed.

**Comment by Schanzation** [comment] 2023-06-10 13:44
Thank you! That sounds great.

**Closed** 2023-06-11 05:16 UTC

**Comment by MarkSpizu** [comment] 2024-02-12 11:55
I had the same problem today. I solved it only after disabling EasyList filter.
