### ISSUE TITLE
1337x.to: popups

### ISSUE THREAD

**Issue by iatejosh** [uBlockOrigin/uAssets#17184] opened 2023-03-15 13:45 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://1337x.to/torrent/5589811/The-Voice-S23E04-1080p-WEB-h264-KOGi-TGx/`

### Category

popups

### Description

1337x.to suddenly has pop ups. No new extensions or anything was added to my browser.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 86204
  cosmetic: 38992
  scriptlet: 17032
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63745-44, 1d.10h.58m
    easyprivacy: 31040-1174, 4d.15h.10m
    plowe-0: 3755-932, 8d.15h.25m
    ublock-abuse: 78-0, 6d.7h.14m
    ublock-badware: 4710-114, 2d.15h.2m
    ublock-filters: 31981-77, 2d.15h.1m
    ublock-privacy: 289-1, 6d.7h.15m
    ublock-quick-fixes: 375-19, 10h.55m
    ublock-unbreak: 1923-39, 2d.15h.4m
    urlhaus-1: 6901-0, 10h.54m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2903 ms (selfie)
  maxAssetCacheWait: 412 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    1337x.to: 3
    acdcdn.com: 1
    befirstcdn.com: 1
    denbsd.com: 1
    youradexchange.com: 1
```
</details>

**Comment by garry-ut99** [comment] 2023-03-15 13:49
> * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

You didn't, a duplicate of: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+1337x.to%3A+popups+

**Comment by Daxy7** [comment] 2023-03-15 16:45
what are the urls for the popups?

**Comment by mapx-** [comment] 2023-03-15 18:06
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Closed by mapx-** 2023-03-15 18:06 UTC
Labels: unable to reproduce

**Comment by Bug-Cache** [comment] 2025-05-20 08:56
![Image](https://github.com/user-attachments/assets/5d272d1d-3f42-4df5-b54d-c8e8545a778e)

https://1337x.to/torrent/2138911/MommyGotBoobs-17-03-31-Ariella-Ferrera-Thats-My-Bush-XXX-1080p-MP4-KTR-N1C/

pop-ups
