### ISSUE TITLE
Insane amount of wikia FANDOM "sponsored content" ads EVERYWHERE!

### ISSUE THREAD

**Issue by ogotbanned** [uBlockOrigin/uAssets#5430] opened 2019-04-25 01:07 UTC
### URL(s) where the issue occurs
````
https://oldschoolrunescape.fandom.com/wiki/Money_making_guide
https://oldschoolrunescape.fandom.com/wiki/Old_School_RuneScape_Wiki
````
^ scroll down for cancer and lulzs
`https://oldschoolrunescape.fandom.com/wiki/Special:Search?query=apex+legends`
scroll down for related stories. 
`https://oldschoolrunescape.fandom.com/wiki/Treasure_Trails/Guide/Cryptic_clues`
menu bar is 100% ads top lel ^

### Describe the issue

ads. ads  EVERYWHERE!

### Screenshot(s)

![inf scroll ad cancer](https://user-images.githubusercontent.com/49357984/56703050-fbbe9700-66bb-11e9-955a-16e1b2060006.png)
![adcancer4](https://user-images.githubusercontent.com/49357984/56703051-fbbe9700-66bb-11e9-87cf-70e1a5fdde82.png)
![ad cancer ay](https://user-images.githubusercontent.com/49357984/56703052-fbbe9700-66bb-11e9-8271-91684ceb5491.png)
![ad caner 1](https://user-images.githubusercontent.com/49357984/56703053-fbbe9700-66bb-11e9-9f8b-de4e09d352ee.png)

### Versions

- Browser/version: [here]
- uBlock Origin version: [uBlock Origin v1.18.16 + ubo extra b]

### Settings

- ubo exta and everyhing turned on in ubo

### Notes

This as been going on for years, im not sure if it just that the ublock team gave up... but FANDOM doesn't have random number  ads like facebook so wat is going on?

**Comment by Hrxn** [comment] 2019-04-25 01:19
Wikia/Fandom have been running that IL crap for a while, but normally uBO Extra should deal with that on Chrom(e|ium).

I can't seem to reproduce those ads right now (except with uBO only).

But what do you mean by 'everything turned on' in uBO?
I hope not using all filter lists simultaneously or something. Please try running the extension with only the default options.

**Comment by ogotbanned** [comment] 2019-04-25 01:25
You might have custom filters. With stock firefox ESR i see these ads still.

**Comment by ogotbanned** [comment] 2019-04-25 01:41
This research was done via stock chrome. It can be reproduced. I hope i don't have to spam filterlists sites easylist, adguard, etc  to get this fixed... *sigh*

**Comment by okiehsch** [comment] 2019-04-25 01:45
I use stock Chrome and can't reproduce, I really don't care what you do.

**Comment by ogotbanned** [comment] 2019-04-25 01:47
... 
![chrome stock](https://user-images.githubusercontent.com/49357984/56704309-776f1280-66c1-11e9-9481-41d25a8a057c.png)
![lulzs2](https://user-images.githubusercontent.com/49357984/56704310-776f1280-66c1-11e9-8621-32c0af6f0898.png)

**Comment by okiehsch** [comment] 2019-04-25 01:59
Sorry, I thought the issue is about Instart Logic.
You issue about the realated posts and fanfeeds, which link to other fandom sites is what exactly?

**Comment by ogotbanned** [comment] 2019-04-25 02:02
Please see the links and screenshots above. My issue is that under easylist policy, these ads are NOT self promo and should be blocked.[1]
https://easylist.to/pages/policy.html

**Comment by okiehsch** [comment] 2019-04-25 02:06
Here is a quote from `uAssets` [readme](https://github.com/uBlockOrigin/uAssets/blob/master/README.md)

"If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

anti-adblock
ad-reinsertion
popups/popunders
site breakage
will always be fixed in uAssets even if they don't require extended syntax."

**Comment by ogotbanned** [comment] 2019-04-25 02:07
This is a case of ad-reinsertion
popups/popups  as i can see ads. At the very least, please add SOMETHING to ublock annoyances.  Eg: the filter. Guess il be spamming the crap out of the filter forums.

**Comment by ogotbanned** [comment] 2019-04-25 02:18
For extra proof
Version 74.0.3729.108 (Official Build) (64-bit) chrome 
logger:  https://pastebin.com/raw/CZPRWVH7
firefox esr with filter mods https://pastebin.com/jvScDMgD a bit of a warning, my filters are aggressive as hell, but it still doesn't discount the fact that there are ads "sponsored  content"  that have been unblocked for years for an unknown reason?

**Comment by okiehsch** [comment] 2019-04-25 02:21
I am not doubting that you see stuff like
![image](https://user-images.githubusercontent.com/16838044/56705488-60f0a780-6711-11e9-99e0-3c1b7da5eef5.png)


so there is no need to post "proof".
Open an issue at `EasyList` maybe they will agree that this is not self-promotion.

**Comment by ogotbanned** [comment] 2019-04-25 02:22
I will, but easylist hasn't fixed this for YEARS. Its disappointing that one of the few sites easylist won't touch can't be added. but alas, i guess thats life.

**Comment by dumbusernameidk** [comment] 2019-04-25 14:27
The fan feed is hardly considered an ad it's just how wikia works. If it's such an eye sore just use inspect element on it.

**Comment by ogotbanned** [comment] 2019-04-25 19:01
> 
> 
> The fan feed is hardly considered an ad it's just how wikia works. If it's such an eye sore just use inspect element on it.

Wikia and the FANDOM company have a history of serving very annoying  ads in recent years. This isn't a case of an amateur posting his crap blog  posts everywhere.
[1] https://old.reddit.com/r/assholedesign/comments/adfmhr/so_many_pop_ups_on_fandom_wiki_you_cant_even/
[2] https://old.reddit.com/r/assholedesign/search?q=fandom&restrict_sr=on&include_over_18=on



fun fact: Jimmy whales is president. Yes, that Jimbo. Its one of the reason why i hate the guy. [1] 
https://en.wikipedia.org/wiki/Wikia/

**Comment by mapx-** [comment] 2019-04-25 19:32
@ryanbr

**Closed by mapx-** 2019-04-25 19:32 UTC

**Comment by dumbusernameidk** [comment] 2019-04-25 19:51
> > The fan feed is hardly considered an ad it's just how wikia works. If it's such an eye sore just use inspect element on it.
> 
> Wikia and the FANDOM company have a history of serving very annoying ads in recent years. This isn't a case of an amateur posting his crap blog posts everywhere.
> [1] https://old.reddit.com/r/assholedesign/comments/adfmhr/so_many_pop_ups_on_fandom_wiki_you_cant_even/
> [2] https://old.reddit.com/r/assholedesign/search?q=fandom&restrict_sr=on&include_over_18=on
> 
> If you want a history of wikia and its connection to wikipedia see here [1]
> https://en.wikipedia.org/wiki/Wikia/
> https://en.wikipedia.org/wiki/Jimmy_Wales#Wikia_and_later_pursuits
> https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=21865011

But those issues aren't related to what you're asking for. The first one is on mobile and probably doesn't have uBO. Second one is probably fixed already seeing as I don't get the ads. I mean if you don't use uBO and update the filters you're liable to get ads.

What you want is to just hide the fan feed which like I said use inspect element.
