### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Felix2144** [uBlockOrigin/uAssets#14534] opened 2022-08-26 04:06 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=vNBY2Y18HfU`

### Category

ads

### Describe the issue

So, is get Ads on YouTube Videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 103
filterset (summary): 
  network: 83356
  cosmetic: 48117
  scriptlet: 17702
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 22-2, never
    DEU-0: 5915-0, 23h.8m
    easylist: 68715-57, 1d.3h.11m
    easyprivacy: 27415-136, 1d.3h.10m
    plowe-0: 3632-777, 6d.13h.7m
    ublock-abuse: 76-0, 15h.5m
    ublock-badware: 4161-96, 1d.3h.13m
    ublock-filters: 32530-143, 1d.3h.14m
    ublock-privacy: 241-3, 15h.6m
    ublock-quick-fixes: 390-4, 23h.7m
    ublock-unbreak: 1838-42, 1d.3h.12m
    urlhaus-1: 5668-0, 23h.9m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5812 ms (selfie)
  maxAssetCacheWait: 2053 ms
popupPanel: 
  blocked: 533
  blockedDetails: 
    youtube.com: 511
    doubleclick.net: 7
    google.de: 1
    googleadservices.com: 1
    googlesyndication.com: 13
```
</details>

**Comment by MasterKia** [comment] 2022-08-26 04:10
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-26 04:10 UTC
