### ISSUE TITLE
washingtonpost.com

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uAssets#9185] opened 2021-05-25 11:38 UTC
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.washingtonpost.com`

### Describe the issue

Site starts giving annoying paywall popup after like 10? articles even though content is still available when you block it.

Also a lot of ugly ad slots all around the page and in last screenshot useless empty bar at bottom.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/84513173/119489459-62638280-bd64-11eb-848f-8c79a94b1d3f.png)
![image](https://user-images.githubusercontent.com/84513173/119489480-698a9080-bd64-11eb-8dfe-90e4ea23d1ec.png)
![image](https://user-images.githubusercontent.com/84513173/119489519-7313f880-bd64-11eb-9e57-039d38e9fe58.png)

### Versions

- Browser/version: Firefox for Android 88.1.3
- uBlock Origin version: 1.35.2

### Settings

- No changes

### Notes

Need to fix scrolling after you block paywall popup.

**Comment by Nojuuu** [comment] 2021-05-25 11:43
Went to check and seems to appear on desktop too.

![image](https://user-images.githubusercontent.com/84513173/119491838-12d28600-bd67-11eb-81d3-e86ac347be4f.png)

**Comment by IThinkIAmCool** [comment] 2021-05-25 11:48
As per https://github.com/uBlockOrigin/uAssets README.md: "Circumventing a paywall is considered [out of scope.](https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-392009540)"

**Comment by IThinkIAmCool** [comment] 2021-05-25 11:48
Is this anti adb?

**Comment by uBlock-user** [comment] 2021-05-25 12:05
We don't fix paywalls.

**Closed by uBlock-user** 2021-05-25 12:05 UTC

**Comment by uBlock-user** [comment] 2021-05-25 12:13
Filter -- `||washingtonpost.com/pwapiv2/$xhr,1p`

**Comment by Nojuuu** [comment] 2021-05-25 12:16
> 
> 
> We don't fix paywalls.

Understood. How about those ugly ad slots?

**Comment by uBlock-user** [comment] 2021-05-25 12:23
@Nojuuu Enable _Ignore generic cosmetic filters_ in Settings pane.

**Comment by uBlock-user** [comment] 2021-05-25 12:23
@Nojuuu Disable _Ignore generic cosmetic filters_ in Settings pane.

**Comment by Nojuuu** [comment] 2021-05-25 12:41
@uBlock-user that doesn't help 

![image](https://user-images.githubusercontent.com/84513173/119499459-6943c280-bd6f-11eb-89b2-46f2d2e4fd31.png)

![image](https://user-images.githubusercontent.com/84513173/119499639-94c6ad00-bd6f-11eb-838b-4735f63c0a7a.png)

**Comment by uBlock-user** [comment] 2021-05-25 12:43
Can't reproduce, besure to be on default lists/settings.

**Comment by Nojuuu** [comment] 2021-05-25 12:44
> 
> 
> Can't reproduce, besure to be on default lists/settings.

Happens only on mobile.

**Comment by uBlock-user** [comment] 2021-05-25 12:50
`washingtonpost.com##div.mb-lg.mt-lg.pb-lg.pt-lg.bc-gray-lighter.bh.b.justify-center.items-center.flex.dn-hp-sm-to-mx`

works ?

**Comment by Nojuuu** [comment] 2021-05-25 12:57
> 
> 
> `washingtonpost.com##div.mb-lg.mt-lg.pb-lg.pt-lg.bc-gray-lighter.bh.b.justify-center.items-center.flex.dn-hp-sm-to-mx`
> 
> works ?

Yes, maybe with :has-text(Ad) to make sure it doesn't break anything else?

there was also that ##mobile-footer-ad-wrapper

**Comment by uBlock-user** [comment] 2021-05-25 13:04
No need, there are only four of them and all four are used as Ad placeholders.
