### ISSUE TITLE
Seattle Times [Anti-Adblock]

### ISSUE THREAD

**Issue by TheMCNerd2017** [uBlockOrigin/uAssets#1663] opened 2018-03-05 04:41 UTC
### URL(s) where the issue occurs

`www.seattletimes.com`

### Describe the issue

When attempting to read an article, the screen becomes blurred and a message pops up telling me to enable ads or purchase a subscription comes up.

### Screenshot(s)

https://i.imgur.com/OSjJZ5P.png

### Versions

- Browser/version: Google Chrome 64-bit / 64.0.3282.186 (Official)
- uBlock Origin version: 1.15.2

### Settings

- Changed 'userResourcesLocation' to `https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoResources.txt`
- Enabled several extra filters through the 3rd-Party filters menu.

### Notes

This happens whenever you attempt to read any article on the site. Stopping the page from loading prevents the popup from appearing. Disabling JavaScript prevents the whole page from loading.

**Comment by okiehsch** [comment] 2018-03-05 05:02
This is fixed by
`seattletimes.com##script:inject(setTimeout-defuser.js, SEATIMESCO.browser.adBlock.baitLoaded, 300)`
which is already part of the uBO-filter list.
I can only reproduce if I disable that filter.

**Closed** 2018-03-05 22:40 UTC
Labels: unable to reproduce

**Comment by terrorist96** [comment] 2018-11-21 22:13
I see anti-adblock.
`https://www.seattletimes.com/seattle-news/politics/judge-dismisses-nra-lawsuit-over-seattles-new-gun-storage-law/`
![image](https://user-images.githubusercontent.com/12802056/48870961-cfbb8480-edb0-11e8-8f74-ea4eb8cdfcb4.png)

**Comment by okiehsch** [comment] 2018-11-21 22:36
I can't reproduce consistently, rather weird detection mechanism.
`seattletimes.com##+js(set-constant.js, SEATIMESCO.browser.adBlock.baitLoaded, true)`
works for me.
