### ISSUE TITLE
amazon.co.uk: ads

### ISSUE THREAD

**Issue by 8armdevil** [uBlockOrigin/uAssets#14663] opened 2022-09-03 22:15 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.co.uk/gp/video/detail/B08BBTPX9Q/ref=atv_dp_season_select_s1`

### Category

ads

### Describe the issue

Normal ads show during freeview content on amazon prime video 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/112783651/188289177-b74ee007-18bf-4b1d-bad9-d7be20657530.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82552
  cosmetic: 42065
  scriptlet: 17739
  html: 739
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33174-37, 3d.23h.50m
    ublock-badware: 4206-0, 18h.16m
    ublock-privacy: 263-0, 4d.23h.52m
    ublock-abuse: 76-0, 4d.23h.51m
    ublock-unbreak: 1859-0, 18h.15m
    easylist: 65738-628, 18h.14m
    easyprivacy: 27453-578, 18h.13m
    urlhaus-1: 7674-0, 1h.40m
    plowe-0: 3634-3, 4d.19h.49m
    ublock-quick-fixes: 420-0, 1h.41m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 593 ms (selfie)
  maxAssetCacheWait: 163 ms
popupPanel: 
  blocked: 83
  blockedDetails: 
    amazon.co.uk: 10
    amazon.com: 63
    media-amazon.com: 9
    ssl-images-amazon.com: 1
```
</details>

**Comment by okiehsch** [comment] 2022-09-04 08:23
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/13166 
The amazon ads are usually SSAI, so nothing we can do even if we could reproduce.

**Closed** 2022-09-04 08:43 UTC
Labels: duplicate, SSAI, geo specific, account required
