### ISSUE TITLE
OCREGISTER.COM

### ISSUE THREAD

**Issue by jkrreed** [uBlockOrigin/uAssets#3280] opened 2018-08-21 21:52 UTC
### URL(s) where the issue occurs

`https://www.ocregister.com/2011/03/29/how-to-circumvent-ny-times-pay-wall/`

### Describe the issue

When trying to view an article on ocregister.com, an anti-adblock pop-up appears, blocking the text of the article, disabling the ability to scroll, and blurring out the body text. When using Nano Adblock and Nano Defender, the anti-adblock pop-up is disabled and another appears instead stating that the monthly article limit has been reached and disabling the site the same as before.

The link above is to an article published in 2011 showing how to get around NYT's paywall, so I thought that was an appropriate page to use as a sample.

### Screenshot(s)

n/a

### Versions

- Browser/version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- uBlock Origin version: Nano Defender 15.0.0.36 & Nano Adblocker 1.0.0.64

### Settings

- None changed

**Comment by okiehsch** [comment] 2018-08-21 21:58
I can't reproduce with `uBlock Origin`, this has already been fixed on the 12th of July, see https://github.com/uBlockOrigin/uAssets/commit/3571dc5dec1b81adfd580a7c2509e0d4a3c6c47c

That fix still works on my end.

**Closed** 2018-08-21 22:03 UTC
Labels: unable to reproduce

**Comment by jspenguin2017** [comment] 2018-08-22 00:08
Works fine for me too: 
![image](https://user-images.githubusercontent.com/7283682/44435425-3096af00-a56d-11e8-8a9e-a5a783ac5bbe.png)
