### ISSUE TITLE
mtv.fi: detection

### ISSUE THREAD

**Issue by axumux** [uBlockOrigin/uAssets#22460] opened 2024-02-12 18:29 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.mtv.fi/video/0bb49959c799fe2ea2a3/jakso-4526-miki-senkin-muijari
```

### Description

Detects uBlock Origin (needs login)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://gyazo.com/502d88001818f483d3097802add26504

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 122894
 cosmetic: 47564
 scriptlet: 19153
 html: 2104
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37890-291, 1h.1m Δ
  ublock-badware: 7849-14, 1h.1m Δ
  ublock-privacy: 995-0, 1h.1m Δ
  ublock-unbreak: 2261-1, 1h.1m Δ
  easylist: 80796-547, 1h.1m Δ
  easyprivacy: 50199-851, now
  urlhaus-1: 7300-0, now
  plowe-0: 3782-1, now
  FIN-0: 2282-0, now
  ublock-quick-fixes: 217-0, 1h.1m Δ
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 564 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  mtv.fi: 1
  bugsnag.com: 14
  fwmrm.net: 2
  youborafds01.com: 4
 extended:
  ##.avod-web-player-pause
  ##.visit-advertiser-link
  ##.avod-web-player-csai:remove()
  ##.avod-web-player-skin > #skin-wrapper > div > div:has-text(Mai…
  ##+js(json-prune-fetch-response, bumpers, , propsToMatch, url:/p…
  ##+js(xml-prune, MediaFile, , fi-mtv3.videoplaza.tv/proxy/distri…

```
</details>

**Comment by mapx-** [comment] 2024-02-12 18:38
does this work ?

`||imasdk.googleapis.com^$script,xhr,3p,redirect-rule=noopjs,domain=mtv.fi`

**Comment by axumux** [comment] 2024-02-12 18:45
> does this work ?
> 
> `||imasdk.googleapis.com^$script,xhr,3p,redirect-rule=noopjs,domain=mtv.fi`

Unfortunately no effect

**Comment by mapx-** [comment] 2024-02-12 18:50
what about:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$xhr,domain=mtv.fi
||imasdk.googleapis.com/pal/sdkloader/pal.js$redirect-rule=noop.js,domain=mtv.fi
```

**Comment by axumux** [comment] 2024-02-12 18:54
> what about:
> 
> ```
> @@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$xhr,domain=mtv.fi
> ||imasdk.googleapis.com/pal/sdkloader/pal.js$redirect-rule=noop.js,domain=mtv.fi
> ```

Sorry, no effect

**Comment by mapx-** [comment] 2024-02-12 19:08
ok, remove all filters above, add this 1:

`@@||v.fwmrm.net/ad/$xhr,domain=mtv.fi`

**Comment by axumux** [comment] 2024-02-12 19:19
> ok, remove all filters above, add this 1:
> 
> `@@||v.fwmrm.net/ad/$xhr,domain=mtv.fi`

Still no change

**Comment by mapx-** [comment] 2024-02-12 19:21
well, in chrome is working, for firefox disable for now the finnish list

**Comment by mapx-** [comment] 2024-02-12 19:24
or keep that list and add

`&browser=mozillafirefox$xhr,removeparam=browser,from=mtv.fi|mtvuutiset.fi,badfilter`

@peace2000

**Comment by axumux** [comment] 2024-02-12 19:31
> well, in chrome is working, for firefox disable for now the finnish list

Using chrome I am still getting detection with `@@||v.fwmrm.net/ad/$xhr,domain=mtv.fi` filter

With firefox I avoid detection by using the list and `&browser=mozillafirefox$xhr,removeparam=browser,from=mtv.fi|mtvuutiset.fi,badfilter`

**Comment by peace2000** [comment] 2024-02-13 14:01
The recent issue with `mtv.fi` was caused by this adjustment: https://github.com/easylist/easylist/commit/7b83399606451f3b7c1e7d481856270764c3d572

And it was fixed by this: https://github.com/easylist/easylist/commit/44de1b180e0b5e6eb7ef390ff42a84129a91714c (though the filter by @mapx- should achieve the same result...)

The current filter set works fine on my end. I'm using Firefox also.

@axumux Try to update Easylist, enable the Finnish list and remove any custom filters.

**Closed** 2024-02-13 14:24 UTC
Labels: account required, broken by EasyList
