### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by NinetyKek** [uBlockOrigin/uAssets#12921] opened 2022-04-23 11:46 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Ad takes up one of the video slots on the homepage.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/81204025/164893149-4aaacf93-0ce2-4e67-bd94-83ce066078e5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81658
  cosmetic: 42616
  scriptlet: 16544
  html: 638
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31271-31, 2d.11h.39m
    ublock-badware: 4096-5, 2d.11h.38m
    ublock-privacy: 211-1, 10d.4h.59m
    ublock-abuse: 74-0, 10d.4h.58m
    ublock-unbreak: 1774-0, 2d.11h.37m
    easylist: 66250-595, 2d.11h.36m
    easyprivacy: 26856-591, 2d.11h.35m
    urlhaus-1: 8442-1, 11h.30m
    plowe-0: 3687-0, 9d.12h.41m
    ublock-quick-fixes: 177-0, 11h.31m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 161 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 1373
  no-cosmetic-filtering: true
  blockedDetails: 
    youtube.com: 1206
    doubleclick.net: 6
    google.com: 70
    googlesyndication.com: 3
    googlevideo.com: 88
```
</details>

**Comment by krystian3w** [comment] 2022-04-23 21:19
Duplicate of #7636

**Closed** 2022-04-24 03:04 UTC
Labels: duplicate
