### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by tracer123** [uBlockOrigin/uAssets#14267] opened 2022-08-05 14:11 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.instagram.com/`

### Category

ads

### Describe the issue

Sponsored ads have begun to reappear, even after purging cache/updating/disabling ghostery

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="660" alt="Screen Shot 2022-08-05 at 9 09 50 AM" src="https://user-images.githubusercontent.com/1967036/183094763-de6a6309-2228-4979-9d0f-7a5b03b48367.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80212
  cosmetic: 45348
  scriptlet: 17555
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 227-7, never
    easylist: 69091-51, 1d.18h.52m
    easyprivacy: 27478-123, 1d.18h.51m
    plowe-0: 3638-777, 6d.11h.12m
    ublock-abuse: 76-0, 7d.8h.53m
    ublock-badware: 4171-92, 1d.18h.50m
    ublock-filters: 32439-122, 22h.33m
    ublock-privacy: 226-3, 7d.8h.52m
    ublock-quick-fixes: 357-58, 22h.32m
    ublock-unbreak: 1851-42, 1d.18h.49m
    urlhaus-1: 5003-0, 22h.31m
filterset (user): [array of 227 redacted]
trustedset: 
  added: [array of 94 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 185 ms (selfie)
  maxAssetCacheWait: 46 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    instagram.com: 33
```
</details>

**Comment by MasterKia** [comment] 2022-08-05 14:15
> even after purging cache/updating/disabling ghostery

Remove Ghostery and test with only uBlock Origin.

**Comment by krystian3w** [comment] 2022-08-08 06:41
Try unsubscribe suspicious profiles on Instagram.

Also remove old friends if you have about his long logout (6 months with no comeback reasons)

**Comment by krystian3w** [comment] 2022-08-08 06:43
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14147

**Closed** 2022-08-08 06:43 UTC
Labels: unable to reproduce, No Feedback => closing

**Comment by MasterKia** [comment] 2022-08-18 19:37
@tracer123 Force update your lists, it's fixed.

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
