### ISSUE TITLE
wiadomosci.gazeta.pl: breakage

### ISSUE THREAD

**Issue by darkseji** [uBlockOrigin/uAssets#22215] opened 2024-01-26 09:03 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wiadomosci.gazeta.pl/wiadomosci/14,114884,30633271.html`

### Category

breakage

### Description

Live feed is blocked.

### Other extensions used

Feedbro, Neat URL, Social Fixer for Facebook

### Screenshot(s)

<details>
<summary>1st screenshot with blocker on, 2nd screenshot with blocker off, all with default settings</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63911601/b2af4139-d345-413c-aead-296d42b86be0)

![image](https://github.com/uBlockOrigin/uAssets/assets/63911601/8141cf0b-fe7a-4f21-ba4e-e22fcb3d53af)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 119590
 cosmetic: 97189
 scriptlet: 24110
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 8687-9, now
  POL-2: 1280-14, now
  fanboy-cookiemonster: 49437-177, now
 default:
  user-filters: 12-0, never
  easylist: 79812-37, 47m Δ
  easyprivacy: 43563-40, 47m Δ
  plowe-0: 3783-1180, now
  ublock-badware: 7796-136, 47m Δ
  ublock-filters: 36693-259, 47m Δ
  ublock-privacy: 992-6, 47m Δ
  ublock-quick-fixes: 132-5, 47m Δ
  ublock-unbreak: 2196-33, 47m Δ
  urlhaus-1: 8550-0, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 35 redacted]
 removed:
  chrome-scheme
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 915 ms (selfie)
 maxAssetCacheWait: 148 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  gazeta.pl: 1
  cookielaw.org: 1
  gemius.pl: 1
  googletagmanager.com: 1
  im-g.pl: 2
  onetrust.com: 1
  speedcurve.com: 1
 extended:
  ##.adviewDFPBanner
  ##[id^="banC"], [id^="banP"], [class^="ban0"], [class*="DFP-"], …
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, dfpParams.slots, null)
```
</details>

**Comment by okiehsch** [comment] 2024-01-26 09:25
Caused by 
`gazeta.pl##+js(set, dfpParams.slots, null)`
in the regional polish list.

Add
`gazeta.pl#@#+js(set, dfpParams.slots, null)`
to your filter list.
@garry-ut99

**Comment by darkseji** [comment] 2024-01-26 10:15
Confirmed, adding gazeta.pl#@#+js(set, dfpParams.slots, null) solved the issue.

**Comment by garry-ut99** [comment] 2024-01-26 15:40
> okiehsch: Caused by `gazeta.pl##+js(set, dfpParams.slots, null)` in the regional polish list.

The fully story is that it landed in POL list because it was suggested a week ago 
by @D4niloMR and @dportvine in this issue :
 - https://github.com/uBlockOrigin/uAssets/issues/22085

hence I added it for all compatible domains :
https://github.com/MajkiIT/polish-ads-filter/blob/34ce2fe791894a9a2ab64734ea8dbb617688c5ba/polish-adblock-filters/adblock_ublock.txt#L401

Now I wonder whether there are breakages on the other domains or not, 
and whether I should remove it from all the domains or only from `gazeta.pl`.

The scriptlet removes a part of the ad placehodlers, but not all of them, 
and regardless of the scriptlet, all the ad placeholders are already fixed also by cosmetic filters anyway :
https://github.com/MajkiIT/polish-ads-filter/blob/34ce2fe791894a9a2ab64734ea8dbb617688c5ba/polish-adblock-filters/adblock.txt#L5718

**Comment by okiehsch** [comment] 2024-01-26 16:25
> Now I wonder whether there are breakages on the other domains or not,
and whether I should remove it from all the domains or only from gazeta.pl
....
regardless of the scriptlet, all the ad placeholders are already fixed also by cosmetic filters anyway 

If it's only about placeholders I would remove it to be sure no other breakage occurs.

**Comment by dportvine** [comment] 2024-01-26 16:41
I don't see breakage on the `ukrayina.pl`

**Comment by okiehsch** [comment] 2024-01-26 16:48
Me neither, but why keep it if the issue it fixes is fixed by https://github.com/MajkiIT/polish-ads-filter/blob/34ce2fe791894a9a2ab64734ea8dbb617688c5ba/polish-adblock-filters/adblock.txt#L5718
?
One of the two filters is redundant and I would keep the "safer" filter.

**Comment by garry-ut99** [comment] 2024-01-26 18:20
> okiehsch : but why keep it if the issue it fixes is fixed by (...)
> okiehsch : One of the two filters is redundant

Partially yes, but not completely, sometimes two lines of defense can be better than one line of defence, because a scriptlet can prevent new incoming ads/ad placeholders whose names will be unknown/different than names of already existing ads/placeholders included in cosmetic filters, which means: less work to prevent ads, but I must admit that well crafted cosmetic filters can be good as well.

> okiehsch : If it's only about placeholders I would remove it to be sure no other breakage occurs.
> okiehsch : and I would keep the "safer" filter.

Regardless of what I've written above, probably such safe approach is the best in the current case, given the current specific case here is a big group of sites (AGORA PL Group), we can compare it to another big group of sites (WP Group): we resigned 2 years ago from scriptlets in favor of many well crafted cosmetic filters, because scriptlets were constantly breaking WP sites over and over trought several years :
- https://github.com/abp-filters/abp-filters-anti-cv/issues/183#issuecomment-497728301
- https://github.com/abp-filters/abp-filters-anti-cv/issues/183#issuecomment-622925067
- https://github.com/uBlockOrigin/uAssets/issues/12214#issuecomment-1436088746

as for AGORA PL Group I don't remember / don't know the history of breakages caused by scriptlets, so I'm not sure how high is the risk, but I think we shouldn't risk breakages on a large groups of popular websites, unless someone visits all the domains & subdomains separately, then investigate and makes sure there are no breakages, but even if one makes sure there are no breakages on the other sites at the moment, code on the sites might change at any time and might cause a breakage at any time, I think the best choice, at least for now, will be when I remove / disable the scriptlet for all domains until somebody investigates and makes sure about the safety, so - yes it's going to be disabled or removed as for now in the next Pull Request.

**Closed** 2024-01-27 17:30 UTC
Labels: to be fixed by regional list
