### ISSUE TITLE
onlyfaucet.com

### ISSUE THREAD

**Issue by Kamany89** [uBlockOrigin/uAssets#21947] opened 2024-01-12 18:28 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

onlyfaucet.com

### Description

This site detected ubo and Reloads repeatedly

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-12 202300](https://github.com/uBlockOrigin/uAssets/assets/154012912/517e4f94-ee4d-4616-9caf-4a0abba928b4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by gorhill** [comment] 2024-01-12 18:30
Closing as invalid due to removing troubleshooting information and:

> - [x] I did not answer truthfully to ALL the above checkpoints.

**Closed by gorhill** 2024-01-12 18:30 UTC

**Comment by Kamany89** [comment] 2024-01-13 13:13
What's wrong here guys ?

**Comment by ItsProfessional** [comment] 2024-01-13 13:19
1. unable to reproduce
2. you didn't provide troubleshooting info
3. you checked all the boxes without reading them

**Comment by Kamany89** [comment] 2024-01-13 13:28
@ItsProfessional Sorry for this mistake 
but i can't understand the 1 and 2 steps ?

**Comment by mapx-** [comment] 2024-01-13 13:30
Do we need an account to reproduce the issue ?

**Comment by Kamany89** [comment] 2024-01-13 13:32
@mapx- 'engbaskotaa333@gmail.com'

**Comment by mapx-** [comment] 2024-01-13 13:34
still incomplete:

- account required
- claim some crap => detection

test this filter:

`onlyfaucet.com##+js(rmnt, script, fetch)`

**Comment by Kamany89** [comment] 2024-01-13 13:40
@mapx- Yes its works well, but why bitmedia Advertisements appear

**Comment by mapx-** [comment] 2024-01-13 13:45
> why bitmedia Advertisements appear

- provide the link of the page where you get it
- provide a screenshot with that ad on page

**Comment by Kamany89** [comment] 2024-01-13 13:48
@mapx- 'onlyfaucet.com/faucet/currency/btc'
screen 
![Screenshot 2024-01-13 154701](https://github.com/uBlockOrigin/uAssets/assets/154012912/f955d914-fe9f-46a4-9ef2-dea475a3d5ac)

**Comment by mapx-** [comment] 2024-01-13 14:02
I cannot reproduce that ad, maybe it depends on the country or you are not using a default setup (reset uBO to default lists / settings )

**Comment by Kamany89** [comment] 2024-01-13 14:13
@mapx- Ok, Thank you sir

**Comment by Nordmoon** [comment] 2024-02-24 08:37
![Screenshot_2024-02-24-15-35-51-76_4d38fce200f96aeac5e860e739312e76](https://github.com/uBlockOrigin/uAssets/assets/159579156/e6baaaba-2225-40bf-9014-e92bce7be93b)
Detected again, please solved sir 🙏

**Comment by Nordmoon** [comment] 2024-02-28 01:40
thx u so much 🙂
