### ISSUE TITLE
cdn.elastic.snaplogic.com: breakage

### ISSUE THREAD

**Issue by bazinga286** [uBlockOrigin/uAssets#17343] opened 2023-03-30 07:37 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cdn.elastic.snaplogic.com/sl/designer.html?v=12376`

### Category

breakage

### Description

login to SnapLogic platform does not work since this morning, when uBlockOrigin is disabled it works fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 88074
  cosmetic: 39689
  scriptlet: 17470
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65003-45, 1h.4m
    easyprivacy: 30725-1175, 1d.20h.52m
    plowe-0: 3751-934, 1h.5m
    ublock-abuse: 78-0, 1d.13h.44m
    ublock-badware: 5477-114, 1h.3m
    ublock-filters: 33106-93, 1h.2m
    ublock-privacy: 295-2, 1d.13h.43m
    ublock-quick-fixes: 451-11, 23m
    ublock-unbreak: 1945-42, 1h.1m
    urlhaus-1: 6995-0, 22m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 429 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment] 2023-03-30 08:08
tested with a fake account, however the site is checking it

```
Login Failed:
Password/username combination is invalid or your account is locked.
Click "[Forgot password?](https://cdn.elastic.snaplogic.com/sl/login.html?password=forgot)" to reset your login credentials.
```

> login to SnapLogic platform does not work since this morning

meaning ? an error like above ? other ?

**Comment by peace2000** [comment] 2023-03-31 19:38
I managed to create a fake/test account. Though I cant reproduce the issue. Tested on FF and on Chrome.

![kuva](https://user-images.githubusercontent.com/17256841/229213443-b061b9b6-9c46-4100-b190-804bee30461f.png)

Please try to update your filter lists and then reset uBlock.

**Comment by peace2000** [comment] 2023-04-01 18:44
Works still on my end, no feedback so closing this.

**Closed by peace2000** 2023-04-01 18:44 UTC
Labels: unable to reproduce, account required, Waiting for feedback
