### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by forg3y** [uBlockOrigin/uAssets#15537] opened 2022-11-04 02:35 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

ad runs still show video ads on da page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 88953
  cosmetic: 38398
  scriptlet: 16605
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62730-55, 2d.9h.20m
    easyprivacy: 30841-1170, 1d.11h.28m
    plowe-0: 3671-865, 11d.7h.34m
    ublock-abuse: 76-0, 11d.7h.37m
    ublock-badware: 3953-105, 2d.9h.19m
    ublock-filters: 31116-131, 2d.9h.18m
    ublock-privacy: 257-1, 11d.7h.36m
    ublock-quick-fixes: 452-20, 23h.36m
    ublock-unbreak: 1885-42, 2d.9h.17m
    urlhaus-1: 11522-0, 23h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 302 ms (selfie)
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 2
    google-analytics.com: 1
    imrworldwide.com: 2
    scorecardresearch.com: 8
    sentry.io: 2
    serving-sys.com: 1
```
</details>

**Comment by liamengland1** [comment] 2022-11-04 02:56
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed** 2022-11-04 06:18 UTC
