### ISSUE TITLE
web2.0calc.com anti-adblock and cookie warning

### ISSUE THREAD

**Issue by ParkerPaul** [uBlockOrigin/uAssets#6814] opened 2020-01-11 23:46 UTC
### URL(s) where the issue occurs

`https://web2.0calc.com/`

### Describe the issue

To test anti-adblock:
- Visit `https://web2.0calc.com/`
- Select "I accept all cookies"
- Preform a calculation (type anything into the calculator and press enter)
- Anti-adblock overlay will show

Offending javascript from [web2.0calc.js](https://web2.0calc.com/js/web2.0calc.js?v106):

```
if (typeof adsbygoogle != "undefined" && typeof adsbygoogle.loaded != "undefined") {
	// loaded
} else {
	if (adblockmodal.hasClass("show")==false) {
		window.setTimeout(function(){
			adblockmodal.find("img.ayblock").attr("src", "/img/block1.jpg");
		}, 3200);
		adblockmodal.modal("show");
		adblockmodal.addClass("show");
	}
```

To test cookie consent warning:
- Clear cookies
- Visit `https://web2.0calc.com/`
- Cookie consent overlay will show

Also, if you opt out of tracking cookies, it limits calculations to 3 per hour.
- Select "Configure" from the cookie consent overlay
- Deselect the checkbox labeled "I accept third party cookies used to..."
- Select "I accept selected cookies" (beneath the button it should say "3 calculations per hour")
- Preform 4 calculations
- Calculation limit overlay shows ("We're sorry, but you have reached the calculation limit for this hour")

### Screenshot(s)

https://imgur.com/a/uyfKGxS

### Versions

- Browser/version: Firefox
- uBlock Origin version: v1.24.2

### Settings

All filter lists enabled, except for adblock warning removal (which doesn't solve the problem), experimental, and mobile ads

### Notes
All overlays can be removed just fine using cosmetic filters, but I think a more long term solution for the anti-adblock would use scriptlet injection/redirection.

**Comment by uBlock-user** [comment] 2020-01-12 04:57
Already fixed in uBlock Filters, force update that list.

> but I think a more long term solution for the anti-adblock would use scriptlet injection/redirection.

If the dev decides to play the cat and mouse game, there would be no long-term solution.

**Comment by uBlock-user** [comment] 2020-01-12 05:08
> Calculation limit overlay shows ("We're sorry, but you have reached the calculation limit for this hour")

Can't reproduce that either. Remove any existing cookies after updating the uBlock Filters list and try again.

**Comment by mapx-** [comment] 2020-01-12 07:28
I can reproduce the calculation limit, addressed

**Comment by JobcenterTycoon** [comment] 2021-01-14 16:21
` ||web2.0rechner.de/*/$subdocument` only covers one site `web2.0calc.com` needs this filter too

**Comment by uBlock-user** [comment] 2021-01-14 16:26
> web2.0calc.com needs this filter too

Can't reproduce at `0calc` domains

**Comment by JobcenterTycoon** [comment] 2021-01-14 16:50
the ad only appears when i decline cookies (after 10 seconds or after a reload)

**Comment by uBlock-user** [comment] 2021-01-14 16:52
||web2.0calc.*/*/$subdocument

**Closed** 2021-01-14 16:52 UTC
