### ISSUE TITLE
cielotv.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#20077] opened 2023-10-14 00:33 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Cookie dialog. You can't hide it, otherwise videos don't load.

### URL(s) where the issue occurs.

`https://www.cielotv.it/`
`https://www.cielotv.it/streaming.html`

### Screenshot(s)

<img width="1151" alt="cookies" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/53e69984-85c4-45ee-83cd-89d1f57298a4">

### Notes

Try setting consentUUID cookie

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 282202
 cosmetic: 170411
 scriptlet: 42625
 html: 1256
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 57023-5028, 53m
  adguard-generic: 78520-7181, 53m
  adguard-spyware: 61462-19379, 53m
  block-lan: 54-0, 53m
  curben-phishing: 87546-15, 53m
  adguard-social: 21886-34, 9m
  adguard-cookies: 27805-45, 9m
  adguard-popup-overlays: 24596-977, 9m
  adguard-mobile-app-banners: 4656-11, 9m
  adguard-other-annoyances: 13651-189, 9m
  adguard-widgets: 2321-3, 9m
  ublock-annoyances: 5514-348, 53m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35827-596, 53m
  ublock-badware: 7301-0, 53m
  ublock-privacy: 591-0, 53m
  ublock-unbreak: 2183-1, 53m
  ublock-quick-fixes: 212-0, 53m
  easylist: 71741-31388, 53m
  easyprivacy: 33201-728, 53m
  urlhaus-1: 12095-0, 53m
  plowe-0: 3729-1, 53m
  ITA-0: 10514-19, 53m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1841 ms
 maxAssetCacheWait: 1131 ms
```
</details>

**Comment by krystian3w** [comment] 2023-10-14 01:19
Test with EL Cookies, maybe fixed with old and wide `set-constant`.

**Closed** 2023-10-14 05:04 UTC

**Comment by krystian3w** [comment] 2023-10-14 21:35
@peace2000 can you check change date to 1970 from added 2023?

**Comment by peace2000** [comment] 2023-10-17 19:05
@krystian3w I cannot see that dialog. Not sure if that trick would work for this page as I can't reproduce.

**Comment by superlex** [comment] 2023-11-08 15:40
@mapx- 

It looks like they changed consentUUID value.
<img width="1147" alt="dd" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/3778413d-0771-4119-9c3a-5dc8e26d9e04">

**Comment by mapx-** [comment] 2023-11-08 18:39
@superlex `sky.it` or `cielo.it` ?

**Comment by superlex** [comment] 2023-11-08 19:45
@mapx- 

the site is `cielotv.it` but the script comes from `cmp.sky.it`. So I think the rule could be
`cmp.sky.it##+js(trusted-click-element, button[aria-label="Continua senza accettare"])`
(I tried it and it works)

<img width="822" alt="sky-cielo" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/919b3238-e4fa-41e0-96b7-1fffd68aae22">

**Comment by superlex** [comment] 2023-11-08 20:14
Thank you mapx- :)
