### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by taff-blur** [uBlockOrigin/uAssets#14371] opened 2022-08-12 14:15 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yandex.ru/`

### Category

ads

### Describe the issue

The giant advertisement right underneath the search bar does not go away at all, no matter how hard I try to remove it. It doesn't work on any of their websites really.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/111134507/184371954-36fe04d2-11de-4f84-bb2f-7cec342f1b39.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 187372
  cosmetic: 244773
  scriptlet: 37731
  html: 731
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31219-18382, 6m
    adguard-generic: 66823-5600, 1m
    adguard-mobile: 8124-150, 1m
    adguard-spyware: 26780-1036, 1m
    adguard-spyware-url: 710-2, 1m
    block-lan: 43-0, 1m
    curben-phishing: 40599-5, 1m
    curben-pup: 188-0, 1m
    adguard-annoyance: 55899-5620, 1m
    adguard-social: 18151-1060, 1m
    fanboy-thirdparty_social: 68-0, 1m
    fanboy-annoyance: 78635-66030, 1m
    fanboy-cookiemonster: 39323-304, 1m
    fanboy-social: 23270-28, 1m
    ublock-annoyances: 4529-4, 1m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33100-79, 57m
    ublock-badware: 4211-0, 56m
    ublock-privacy: 247-0, 55m
    ublock-abuse: 76-0, 54m
    ublock-unbreak: 1867-1, 53m
    ublock-quick-fixes: 368-1, 52m
    easylist: 69394-805, 51m
    easyprivacy: 27328-9912, 50m
    urlhaus-1: 5190-0, 49m
    plowe-0: 3629-3, 48m
    RUS-0: 40408-333, 1h.3m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3575 ms
  maxAssetCacheWait: 1795 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    yandex.ru: 25
    yandex.net: 11
    yastatic.net: 5
```
</details>

**Comment by MasterKia** [comment] 2022-08-12 14:18
> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

>   added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31219-18382, 6m
    adguard-generic: 66823-5600, 1m
    adguard-mobile: 8124-150, 1m
    adguard-spyware: 26780-1036, 1m
    adguard-spyware-url: 710-2, 1m
    block-lan: 43-0, 1m
    curben-phishing: 40599-5, 1m
    curben-pup: 188-0, 1m
    adguard-annoyance: 55899-5620, 1m
    adguard-social: 18151-1060, 1m
    fanboy-thirdparty_social: 68-0, 1m
    fanboy-annoyance: 78635-66030, 1m
    fanboy-cookiemonster: 39323-304, 1m
    fanboy-social: 23270-28, 1m
    ublock-annoyances: 4529-4, 1m

Please test using **_only the default lists_**.

**Comment by MasterKia** [comment] 2022-08-12 14:20
Also:

> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14299

Follow the instructions said here:
https://github.com/uBlockOrigin/uAssets/issues/14299#issuecomment-1207383983

**Closed by MasterKia** 2022-08-12 14:20 UTC

**Comment by taff-blur** [comment] 2022-08-12 14:22
My bad, my bad, thanks for letting me know.

**Comment by MasterKia** [comment] 2022-08-12 14:23
By the way, you don't need to use "adguard-mobile" list on the desktop.
