### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by boraxDS123** [uBlockOrigin/uAssets#14611] opened 2022-08-31 17:06 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

[](url)<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://user-images.githubusercontent.com/112575330/187737929-d5925f52-9842-4b58-9958-453e6501a0fb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 83978
  cosmetic: 49661
  scriptlet: 18142
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    TUR-0: 8695-20, 3d.7h.6m
    easylist: 67231-68, 3d.7h.3m
    easyprivacy: 27437-131, 3d.7h.2m
    plowe-0: 3634-777, 3d.7h.1m
    ublock-abuse: 76-0, 3d.6h.59m
    ublock-badware: 4162-96, 3d.6h.57m
    ublock-filters: 32502-130, 3d.6h.56m
    ublock-privacy: 241-3, 3d.6h.55m
    ublock-quick-fixes: 403-4, 1d.1h.24m
    ublock-unbreak: 1839-41, 3d.6h.53m
    urlhaus-1: 6984-0, 1d.1h.23m
filterset (user): [array of 3 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 782 ms (selfie)
  maxAssetCacheWait: 461 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 5
    ttvnw.net: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-31 17:15
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment] 2022-08-31 17:16
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Closed by MasterKia** 2022-08-31 17:15 UTC
