### ISSUE TITLE
AyeFiles blocking anti-adblock

### ISSUE THREAD

**Issue by olartic** [uBlockOrigin/uAssets#4284] opened 2018-12-10 04:34 UTC
### URL(s) where the issue occurs
`ayefiles.com`

Test "Free Download" here, with a photo:
`https://ayefiles.com/wjggumivvubk`

Message comes up on a second page, when you try downloading as a Free Download. After three seconds of countdown, both Captcha and countdown are removed, an element overwrites them that reads:
> File Publisher doesn't allow Adblock downloads for free users
> Please disable Adblock and Click here to Reload
> OR 
> buy PREMIUM account
 

If you remove that element, the Captcha seems to be missing, and no downloading can be done.

If a screenshot is needed, I can add one.

- Browser/version: 71.0.3578.80
- uBlock Origin version:  v1.17.4

### Settings

- followed `https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin`
- I've added a few filters that are not active on AyeFiles

**Comment by okiehsch** [comment] 2018-12-10 04:44
I can't reproduce, this has already been fixed in `uAssets` and the fix still works on my end.

![image](https://user-images.githubusercontent.com/16838044/49711241-91daaf00-fc3e-11e8-99b2-dd52c91de030.png)

**Comment by jspenguin2017** [comment] 2018-12-10 16:54
I can't reproduce neither. 
![image](https://user-images.githubusercontent.com/7283682/49747834-8482ec00-fc61-11e8-8489-3cbe5eb6b32e.png)

**Closed** 2018-12-11 08:04 UTC
Labels: unable to reproduce
