### ISSUE TITLE
Unblock PerimeterX Bot Defender

### ISSUE THREAD

**Issue by omriiluz** [uBlockOrigin/uAssets#6558] opened 2019-11-13 00:53 UTC
### URL(s) where the issue occurs

```
https://www.invaluable.com/
https://www.bloomberg.com/
https://seatgeek.com/
https://seekingalpha.com/
```

### Describe the issue

PerimeterX Bot Defender is a website security service used by hundreds of popular sites across the web. It is using Javascript to profile user behavior to identify malicious behavior. more details can be found at https://www.perimeterx.com. PerimeterX does not collect PII data or track the users. The information is only used to decide if to grant access to the site.

Some rules from the EasyPrivacy list are blocking our ability to run our code and causing normal users to be blocked. 

Examples from the conversations with the EasyList team:
https://github.com/easylist/easylist/pull/3723#issuecomment-508870872
https://github.com/easylist/easylist/commit/0f70a983eff105a88780f6fc6d3fbfac3478ae12
https://github.com/easylist/easylist/pull/3724

We are asking to create a filter override for the blocked `perimeterx.net` domain and for `/api/v2/collector`

### Screenshot(s)

https://github.com/easylist/easylist/commit/6489947a49ea29002534a1c064c695e2fb0eee5f#commitcomment-35818636

### Versions

- Browser/version: all
- uBlock Origin version: all

### Settings

- none

**Comment by llacb47** [comment] 2019-11-13 01:11
Really? I understand that the nature of bot detection involves fingerprinting, but that is something that the EasyPrivacy list explicitly blocks. https://github.com/easylist/easylist/commit/6489947a49ea29002534a1c064c695e2fb0eee5f#commitcomment-35818463

**Comment by safruti** [comment] 2019-11-13 01:46
PerimeterX is not a tracking service, we have strict privacy policy and these rules are causing issues to users on hundreds of web sites (as you identified on the thread on easyprivacy). 
The fingerprinting and other mechanisms rendered by easyprivacy as trackers are used solely to secure access to the site, and not correlating any data to PII.
This isn't different from recaptcha that is whitelisted (and is tracking users), and the result of blocking the script will result in the site visitors forced to solve recaptchas.

**Comment by uBlock-user** [comment] 2019-11-13 05:55
> This isn't different from recaptcha

Sure, it is, reCaptcha is unavoidable and results in site breakage, yours does not.

> as currently this is negatively impacting the experience of uBlockOrigin users on many sites.

and what about Adguard/ABP/Adblock users ? Why do you care about uBlock Origin users only ?

**Comment by krystian3w** [comment] 2019-11-13 18:15
- ABP no use default EasyPrivacy - if that list spoils pages.

- AdBlock by β:fish: have only EasyList Lite where put block rules / exceptions (as if they were trying to overwrite something).
   `https://cdn.adblockcdn.com/filters/easylist_lite.txt`

- For AdGuard possible report anonymously: https://reports.adguard.com/en/new_issue.html

**Comment by omriiluz** [comment] 2019-11-14 01:58
We are working to resolve this issue on each extension using the EasyPrivacy list.

While PerimeterX uses fingerprinting technology to identify threats, the usage of this technology is not to track users and it's never used or available in order identify, target or track users. 

There is a negative impact to users of uBlockOrigin as they will see more catpchas on hundreds of sites. The PerimeterX tool is not as unavoidable as reCaptcha, but it deployed on some of the largest and most popular sites on the internet today.

**Comment by ZaphodBeebblebrox** [comment] 2019-11-26 17:59
see a0dd5d3

**Comment by uBlock-user** [comment] 2019-11-26 18:52
@ZaphodBeebblebrox You meant https://github.com/uBlockOrigin/uAssets/commit/ebec09871ec0accafbd37fe932a67c70dad6eb80 ?

**Comment by omriiluz** [comment] 2019-11-26 19:10
https://github.com/uBlockOrigin/uAssets/commit/ebec09871ec0accafbd37fe932a67c70dad6eb80 will help unblock the user from solving captcha (which is great in itself), but it will not help with avoiding getting a captcha. The purpose of this thread was to unbreak the root cause, thus avoiding the user seeing any impact.

**Comment by omriiluz** [comment] 2019-11-26 19:11
@ZaphodBeebblebrox, I'd appreciate reopening this issue.

**Comment by mapx-** [comment] 2019-11-26 19:23
We could add
`@@||perimeterx.net/api/*/collector$xhr`

What do you think @okiehsch @gorhill @gwarser

**Comment by uBlock-user** [comment] 2019-11-26 19:24
Refreshing the page works and captCha can be avoided like that once it occurs.

**Comment by mapx-** [comment] 2019-12-02 15:15
It seems that there is no agreement to address the problem, closing

**Comment by mapx-** [comment] 2020-01-12 21:09
https://forums.lanik.us/viewtopic.php?p=152424#p152424

**Comment by llacb47** [comment] 2020-01-12 21:30
Narrow to `@@||*/captcha/PX*/captcha.js$script,1p` ?

**Comment by krystian3w** [comment] 2020-01-12 21:32
`@@/captcha/PX*/captcha.js$script,1p`

works identical?

**Comment by okiehsch** [comment] 2020-01-15 22:01
> Narrow to `@@||*/captcha/PX*/captcha.js$script,1p` ?

The captcha is not broken on every site using that script, atleast on my end.
For example
````
https://twentytwowords.com/kylie-jenner-and-travis-scott-are-planning-on-having-another-child-together/`
````
with the script blocked.
![image](https://user-images.githubusercontent.com/16838044/72475344-ffb2bc00-37ea-11ea-8de2-b91682cd80ea.png)

**Comment by llacb47** [comment] 2020-01-15 22:58
They started asking people to subscribe to this list on captcha page: `https://abp.perimeterx.com/whitelist.txt`

**Comment by okiehsch** [comment] 2020-01-15 23:09
`https://abp.perimeterx.com/whitelist.txt`
We could badfilter them. 😁

**Comment by omriiluz** [comment] 2020-01-16 19:15
Then these users wouldn't be able to use the site... That was the only option we could think of to resolve the issue.

**Comment by mapx-** [comment] 2020-01-16 19:18
@omriiluz `seekingalpha` has been fixed
other sites with captcha broken ?

**Comment by krystian3w** [comment] 2020-01-16 19:23
> `https://www.bloomberg.com/`

@llacb47  #6819 

again have troubles with: `https://www.bloomberg.com/europe`
 
![obraz](https://user-images.githubusercontent.com/35370833/72555753-81632200-389d-11ea-815b-bbc5b5574522.png) | ![obraz](https://user-images.githubusercontent.com/35370833/72555878-c5eebd80-389d-11ea-85b0-d024b561e95f.png)
--- | ---
`||cedexis.net^$3p` | `||cedexis.net^$3p,badfilter`
broken | layout look fine

<details> <summary> filter log: </summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 0,3 | script | `https://2-01-3073-0019.cdx.cedexis.net/` | `aliasURL=https://www.bloomberg.com/service-worker.js` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/BWHaasGrotesk-55Roman-Web,BWHaasGrotesk-75Bold-Web,Bloomberg/font-face.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/fence/v4/styles.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/css/module/story_package/_variation/six_up_images-98a2c8aaf3.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/css/module/story_package/_variation/3_up_autoplay-54196db3b8.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/bbnav/public/stylesheets/bb-global-footer-7fce47d03a.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/Bloomberg/font-face.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/css/components/dataStrip/dataStrip-a3c93caf50.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/vendor/css/reg-ui-client-162e0da6e2.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/css/components/masthead/masthead-63fcec205f.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/Bloomberg%20Logotypes-Medium,BWHaasGrotesk-75Bold-Web,BWHaasGrotesk-95Black-Web,BWHaasGrotesk-55Roman-Web/font-face.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0019.cdx.cedexis.net/` | `aliasURL=https://www.bloomberg.com/tophat/assets/v2.4.0/that.css` |
| +1 | \|\|cedexis.net^$3p | -- | behind-the-scene | 0,3 | xhr | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/AvenirNextPForBBG:400,600/styled-font-face.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/images/favicon-black-63fe5249d3.png` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/images/apple-touch-icon-180x180-c1a237984e.png` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/module/newsletter/newsletter_signup-187d8919e5.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/module/newsletter/NewsletterView-c75216c0e4.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/module/story_package/StoryPackageView-86101ff87c.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/module/single_story/SingleStoryView-9964bee019.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/lazyLoad/lazyLoad-57e6ac79dd.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/auto_page_reload/auto_page_reload-8ba99caff1.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/continuous_client/prev_viewed-78792dbc70.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/geoip/geoip-e5fab131a4.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/lazy_images/lazy_images-95fa8c8eb4.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/dependencies/dependencies-cbd0a4f059.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/initialize_pianola/initialize_pianola-08be4cc87d.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/timestamp/timestamp-c932de4e4c.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/abba_variants/abba_variants-9fdac72210.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/abba/abba-4de8a9504e.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/polyfills/polyfill-60a44ed0c6.sync.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/event_bus/event_bus-a9f299e831.sync.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/js/header-d7841082fc7455378b3b.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0019.cdx.cedexis.net/` | `aliasURL=https://www.bloomberg.com/tophat/assets/v2.4.0/that.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iM1_7u4Hydjg/v1/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iwaNv4EATB1k/v1/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iF0X4nuARsvE/v0/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iIpxs4bO4b30/v0/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iqHc7JLeH1Hg/v0/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iuaRT6QalS0E/v0/800x600.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/fence/v4/app.bundle.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/BWHaasGrotesk-55Roman-Web,BWHaasGrotesk-75Bold-Web,Bloomberg/font-face.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/fence/v4/styles.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/polyfills/polyfill-60a44ed0c6.sync.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/js/event_bus/event_bus-a9f299e831.sync.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | script | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/js/header-d7841082fc7455378b3b.js` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iM1_7u4Hydjg/v1/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iwaNv4EATB1k/v1/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iF0X4nuARsvE/v0/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iIpxs4bO4b30/v0/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iqHc7JLeH1Hg/v0/25x19.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | image | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iuaRT6QalS0E/v0/800x600.jpg` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/css/module/story_package/_variation/six_up_images-98a2c8aaf3.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/javelin/public/hub/css/module/story_package/_variation/3_up_autoplay-54196db3b8.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/bbnav/public/stylesheets/bb-global-footer-7fce47d03a.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/Bloomberg/font-face.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/css/components/dataStrip/dataStrip-a3c93caf50.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/vendor/css/reg-ui-client-162e0da6e2.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/s3/navi/css/components/masthead/masthead-63fcec205f.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/Bloomberg%20Logotypes-Medium,BWHaasGrotesk-75Bold-Web,BWHaasGrotesk-95Black-Web,BWHaasGrotesk-55Roman-Web/font-face.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0019.cdx.cedexis.net/` | `aliasURL=https://www.bloomberg.com/tophat/assets/v2.4.0/that.css` |
| +0 | \|\|cedexis.net^$3p | -- | `www.bloomberg.com` | 3 | css | `https://2-01-3073-0012.cdx.cedexis.net/` | `aliasURL=https://assets.bwbx.io/font-service/css/AvenirNextPForBBG:400,600/styled-font-face.css` |


</details>

**Comment by omriiluz** [comment] 2020-01-16 19:25
@mapx-  we are verifying one by one and will respond later today

**Comment by mapx-** [comment] 2020-01-16 19:30
@krystian3w is `bloomberg` affected by perimeterX ?!

**Comment by krystian3w** [comment] 2020-01-16 19:34
IDK but EasyPrivacy with `CNAME uncloaking` complety breakage site.

https://github.com/easylist/easylist/blob/7b133ada6121742d3cdb96070bc8fec5bbd46472/easyprivacy/easyprivacy_trackingservers.txt#L430

**Comment by llacb47** [comment] 2020-01-16 20:05
Off-topic! I'm sure @omriiluz has better things to do than read about how CNAME uncloaking breaks Bloomberg.com.

**Comment by omriiluz** [comment] 2020-01-20 05:11
@mapx- these are not showing the captcha element due to the block:
https://www.hotelscombined.com/?_pxhc=1
https://creativemarket.com/?_pxhc=1

**Comment by mapx-** [comment] 2020-01-20 12:29
fixed `hotelscombined` , I get no  captcha for `creativemarket`

**Comment by prateekrastogi** [comment] 2020-01-26 15:01
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by llacb47** [comment] 2020-01-27 01:28
@mapx- broken on `bloomberg.com`

![image](https://user-images.githubusercontent.com/16567977/73145219-52596700-407a-11ea-9377-7965ee3c4e4b.png)

![image](https://user-images.githubusercontent.com/16567977/73145226-5dac9280-407a-11ea-9686-841a5a59947c.png)

**Closed** 2020-02-02 07:49 UTC

**Comment by llacb47** [comment] 2020-04-30 17:25
Needing additional whitelisting @mapx- 
![image](https://user-images.githubusercontent.com/16567977/80740266-d68e1100-8ae5-11ea-87b2-682a2249a95b.png)
`@@||pxchk.net/api/v2/collector/ocaptcha$xhr`

Due to `||pxchk.net^$third-party` in EasyPrivacy

Since I was blocked `pxcdn.net` I needed to add `@@||px-cdn.net/api/v2/collector/ocaptcha$xhr` as well.

**Comment by gwarser** [comment] 2020-06-26 10:23
Is this still issue in uBO on `seekingalpha.com`? 

https://www.reddit.com/r/uBlockOrigin/comments/hfezpq/avoiding_captcha_activated_by_adblockers_possible/

**Comment by mapx-** [comment] 2020-06-26 11:46
I cannot reproduce the captcha thing

**Comment by krystian3w** [comment] 2020-06-26 13:13
Also uses paywall - maybe JS conflit like "frozen" nodes.

**Comment by gorhill** [comment] 2020-06-26 13:27
I get a paywall on my side, _"Read with Free Trial"_.
