### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by F4z** [uBlockOrigin/uAssets#268] opened 2017-01-19 21:07 UTC
Google Chrome 55.0.2883.87 m (64-bit)
uBlock Origin 1.10.4

Default filter lists + POL

Could someone help me blocks ads on this website? - `http://teleshow.wp.pl/cenzura-w-telewizji-co-usilowaly-zatuszowac-stacje-telewizyjne-6081099139236993g/2`

They use random adresses from where ads are loaded, for example - `https://teleshow.wp.pl/nZRaBYtZHDF9BiM_WjAdZSAEMSkbNB0_BAQwKh01AGdjRzA8HzMKKW9TcW1CY158IQ9_LRE2Cyk6DjV_K2dWbGNSdGBFbFZjYFhkKRwuAzZvFSc1ESkGNSVPNSlaKgJ1MQQsIwEoD3clTDY8GD8ZMygLK3QXNUMvIQguNgM7AiN_GyMtASkUNSUAIXQHLg85OARvLRE2Cy07GzszGj9DbGJZc2lNY19pa1Nxb01jXT19U2QJIxscPzRcNzcfNAEtPEcSDjUpGWdjWHBpUgo5GyEJf2BDb0g8PhI2OAAzCmdjRxIONQUPPjAFf2hSKR4zPFwSCQM-CQonMwNvUWksLjA4DjRGA1siHkRxGxYMIgALGyc1PD1ICBcqNjgTM1M5IAgxLR07ADUNEy03FTYKNWkHIzIAI1UwMwInMisxGyghCitiGTsAMyIULjgXMA9hMQQsIwEoD2ElCCM9GzcBKTEIeS0CKlUqJwMuMBcjHS4rCiNiAD8CPyUIODMVBR41PhIpOE8tBzs2Di82BzkHBSYXMmISOwUuKz42LxphHig3GycqKy4YKmkPJyAZOxxhIgQlOA58GSoNES44DT8cBT0SIz0ONQAjb1FkLRU9HWcbIABoWW1IODEXf2s=/`

Most of these ads are hidden by these rules from `POL: polskie filtry do Adblocka i uBlocka`:
`opinie.wp.pl,facet.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,kobieta.wp.pl,film.wp.pl##body > div:nth-of-type(1)[style^="display: block;"]`
`opinie.wp.pl,facet.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,kobieta.wp.pl,film.wp.pl##div[class^="_"]:matches-css(background-size: 56px 45px)`

but I think it would be better to block them, not only hide.

I also can not watch video here - `http://sportowefakty.wp.pl/boks/658929/premier-boxing-champions-noc-egzekucji-na-florydzie`
because I see message that I am using "adblock".
Any idea how to block ads and be able to watch video?

![image](https://cloud.githubusercontent.com/assets/11742596/22124272/6bea0864-de8f-11e6-9c51-e77864843713.png)

**Comment by okiehsch** [comment] 2017-01-19 21:31
`teleshow.wp.pl,sportowefakty.wp.pl##script:inject(abort-on-property-write.js, habahaba)`
`||rek.www.wp.pl^$xmlhttprequest,redirect=nooptext,domain=sportowefakty.wp.pl`
works on my end.

**Comment by F4z** [comment] 2017-01-19 22:16
Thank you for your answer.

First rule works for me too, similar rule is even on a special Polish filter list for uBlock - https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock_ublock.txt#L121


Second rule works for me in Chrome if I add `important` - `||rek.www.wp.pl/vad.xml$xmlhttprequest,redirect=nooptext,domain=wp.pl,important`
but unfortunately it does not work in Firefox.

**Comment by okiehsch** [comment] 2017-01-19 22:32
Sorry I only tested in Chrome, this is not the first time the redirection  `xmlhttprequest,redirect=nooptext,domain=example.com` does work in Chrome
but not in Firefox, the same happened in https://github.com/uBlockOrigin/uAssets/issues/242#issuecomment-269247585

**Comment by F4z** [comment] 2017-01-19 23:02
Ok, no problem.
Thank you for your help.

**Comment by F4z** [comment] 2017-01-20 17:21
@okiehsch please add `~www.wp.pl` to this rule, because without that this website is blank - `http://www.wp.pl/`

`~www.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)`

**Comment by okiehsch** [comment] 2017-01-20 17:35
Sorry.

**Comment by F4z** [comment] 2017-01-20 17:44
No problem.
Thank you :)

By the way, could you reopen this issue, maybe someone will find solution for adblock message before video (for Firefox).

**Comment by okiehsch** [comment] 2017-01-20 17:46
Again sorry, I closed by mistage through the commit message.

**Comment by gorhill** [comment] 2017-01-20 17:53
I [just added](https://github.com/gorhill/uBlock/commit/8f46662a24f2a73725e36368a19715e2b2a173ab) the [uBO-specific POL list](https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt) to uBO stock lists (requires uBO v1.10.5b10), and it should be enabled by default for Polish users. Eventually any filter specific to Polish sites in _"uBlock filters"_ should be moved to that list.

**Comment by gorhill** [comment] 2017-01-20 18:04
Isn't `wp.pl##body:style(overflow: auto !important)` needed for `http://teleshow.wp.pl`? I can't scroll without this.

**Comment by okiehsch** [comment] 2017-01-20 18:16
No problems scrolling on my end with Chrome/Firefox.

**Comment by F4z** [comment] 2017-01-20 18:18
> I just added the uBO-specific POL list to uBO stock lists (requires uBO v1.10.5b10+), and it should be enabled by default for Polish users.

Thank you.

> Isn't wp.pl##body:style(overflow: auto !important;) needed for http://teleshow.wp.pl? I can't scroll without this.

I do not have this problem.

**Comment by F4z** [comment] 2017-01-20 18:37
> I just added the uBO-specific POL list to uBO stock lists (requires uBO v1.10.5b10+), and it should be enabled by default for Polish users. Eventually any filter specific to Polish sites in "uBlock filters" should be moved to that list.


@gorhill is it normal that I do not see this list until I update filter lists?
uBO 1.10.5.12

Before update
![image](https://cloud.githubusercontent.com/assets/11742596/22160702/18fa3206-df47-11e6-9f02-fa1a38c64d62.png)

After update
![image](https://cloud.githubusercontent.com/assets/11742596/22160745/509706d0-df47-11e6-9580-1c5df4890558.png)

And unfortunately it is not enabled by default.

**Comment by gorhill** [comment] 2017-01-20 18:44
> is it normal that I do not see this list until I update filter lists?

Yes, because I committed the change after I published b12.

> And unfortunately it is not enabled by default.

Yes, I corrected myself afterward to add "at first-time install". I am evaluating auto-enabling a newly added list if it matches locale or if it is not marked as being off by default.

**Comment by F4z** [comment] 2017-01-20 19:09
Ok, I understand. Thank you for your answer.

**Comment by gwarser** [comment] 2017-01-21 11:52
`~www.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)`

poczta.wp.pl is broken


`~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)`

**Comment by okiehsch** [comment] 2017-01-21 18:41
What exactly is broken?
Site renders fine on my end, as far as I can tell.
![pols](https://cloud.githubusercontent.com/assets/16838044/22176760/6733f702-e011-11e6-94ba-cf955e2241a3.JPG)

**Comment by gwarser** [comment] 2017-01-21 19:09
You are redirected to `profil.wp.pl` to log in.
`poczta.wp.pl` is a mailbox - interface newer loads (spinning wheel)
![image](https://cloud.githubusercontent.com/assets/886325/22176961/65440df2-e015-11e6-9cd0-593a66d8dae4.jpg)

**Comment by F4z** [comment] 2017-01-22 18:21
I also asked here about that - https://forum.adguard.com/index.php?threads/resolved-kobieta-wp-pl.18565/
They made JavaScript rule for Adguard and it works, I do not have ads and I can play video - https://forum.adguard.com/index.php?threads/resolved-kobieta-wp-pl.18565/page-2#post-123248

@gorhill Could you add/implement this script to uBO resources, for example as a `wp.pl-defuser.js`?

`document.cookie.split(";").forEach(function(a){-1!=a.indexOf("PWA_adbd")&&(document.cookie=a.replace(/^ +/,"").replace(/=.*/,"=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=."+location.hostname.split(".").reverse()[1]+"."+location.hostname.split(".").reverse()[0]))}); (function(){function a(){"object"==typeof arguments[0]&&(arguments[0].detection=!1);b.apply(window,arguments)}function b(){}function d(){"advertisement"!=arguments[0]&&c.apply(window,arguments)}var c=window.addEventListener;Object.defineProperties(window,{SentinelDetector:{get:function(){return function(){this.start=function(){}}},set:function(){}},getScript:{get:function(){return a},set:function(a){b=a}},addEventListener:{get:function(){return d},set:function(a){c=a}}})})();`

**Comment by jspenguin2017** [comment] 2017-08-30 03:10
Does that script rule still work? It doesn't seem to work for me. The current "solution" I have is almost 200 lines of spaghetti code: https://github.com/jspenguin2017/uBlockProtector/blob/fd6798b292c5840c01b400a43c3841092a4d5d59/Extension%20Compiler/Extension/content/content-rules.js#L440-L615

It replaces the player which causes it to lose some functionalities, as they start to include videos from other sources it starts to be a real pain to patch, so I started looking for a cleaner solution.

**Comment by jspenguin2017** [comment] 2017-09-01 01:00
I think I got it... That was easier than I expected. 
https://github.com/jspenguin2017/uBlockProtector/issues/552

**Closed** 2018-01-27 14:22 UTC

**Comment by krystian3w** [comment] 2022-10-10 16:04
@JobcenterTycoon disable may need this filter:

```adb
wp.pl##div[class]:if(>div[class]:first-child:has-text(REKLAMA):if-not(>*))

! - BLANK: https://wiadomosci.wp.pl/nastolatka-zlamala-kregoslup-odtwarzajac-trend-z-tiktoka-6805506852260608a
```

If MajkiIT don't rewrite in 7 days. To reproduce maybe needed is uBo dev if works fine in uBo stable and no match to repair in https://github.com/uBlockOrigin/uBlock-issues/issues/2228#issuecomment-1238957269
