### ISSUE TITLE
open.spotify.com: [unknown]

### ISSUE THREAD

**Issue by kekkc** [uBlockOrigin/uAssets#14355] opened 2022-08-11 22:25 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

[unknown]

### Describe the issue

As soon as ads are played within free spotify playback stops (mute) and doesn't repeat again.

Reproduce: you need a free spotify account
1. Login to open.spotify.com
2. Playback any playlist
3. Hit "forward" to the next song multiple times until the ad will start

Actual Result:
1. Playback is muted and playback doesn't continue any more

Expected Result:
1. Ad is skipped and the next song in the playlist is played directly as with previous ublock versions some weeks ago

Tested in a fresh Firefox Portable with standard ublock installation without any customizations.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 86349
  cosmetic: 102636
  scriptlet: 19222
  html: 723
listset (total-discarded, last updated): 
  removed: 
    easylist: null
  added: 
    https://easylist-downloads.adblockplus.org/easylist_noadult.txt: 65697-512, 18m
    https://easylist-downloads.adblockplus.org/fanboy-notifications.txt: 826-0, 18m
    fanboy-cookiemonster: 39177-88, 18m
    fanboy-social: 23265-8, 18m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33099-69, 18m
    ublock-badware: 4211-0, 18m
    ublock-privacy: 247-0, 18m
    ublock-abuse: 76-0, 18m
    ublock-unbreak: 1868-0, 18m
    easyprivacy: 27324-670, 18m
    urlhaus-1: 4761-0, 18m
    plowe-0: 3634-3, 18m
    DEU-0: 5894-2, 18m
    ublock-quick-fixes: 374-1, 18m
filterset (user): [empty]
trustedset: 
  added: [array of 35 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 289 ms (selfie)
  maxAssetCacheWait: 267 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 1
```
</details>

**Comment by MasterKia** [comment] 2022-08-12 03:56
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14231

**Closed** 2022-08-12 03:56 UTC
Labels: duplicate
