### ISSUE TITLE
uk.businessinsider.com anti-adblock script

### ISSUE THREAD

**Issue by lol768** [uBlockOrigin/uAssets#406] opened 2017-05-17 17:20 UTC
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://uk.businessinsider.com/nikki-haley-donald-trump-2016-3?r=US&IR=T`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

![](https://lol768.com/i/_P.tv.1r.cK.np.yP.W8.3m)

### Versions

- Browser/version: Firefox v54.0a2 (2017-04-18)
- uBlock Origin version: uBlock Origin v1.12.4

### Settings

- Enabled Prevent WebRTC from leaking local IP addresses
- Added custom filter `en-gb.facebook.com###pagelet_growth_expanding_cta`

### Notes

Elements: `.fc-dialog-overlay`(path: `html div div.fc-dialog-overlay`), `.fc-root` (path: `html div div.fc-root`)

Relevant code: https://gist.github.com/anonymous/5f84e8b77f2938e7a86824ccd956f7d6 (unsure where this is loaded from)

**Comment by gorhill** [comment] 2017-05-17 17:48
Unable to reproduce.

**Comment by gorhill** [comment] 2017-05-17 17:50
You have anything else aside uBO blocking stuff?

**Comment by okiehsch** [comment] 2017-05-17 19:08
I can reproduce, basically the same issue as the one fixed with https://github.com/uBlockOrigin/uAssets/commit/df49d382dcbb5a6ae0f897feeb475e97bdc3b242
````
businessinsider.com##script:inject(abort-on-property-read.js, stop)
||em0n.com^$domain=businessinsider.com
````
solves this issue.

**Closed** 2017-05-17 19:09 UTC
Labels: unable to reproduce

**Comment by KiLL4FuNK** [comment] 2018-10-27 13:56
anti-adblock

`https://www.businessinsider.com/10-healthcare-companies-likely-to-get-acquired-2018-10`

**Comment by ZaphodBeebblebrox** [comment] 2018-10-27 14:04
Isn't that a paywall, not anti-adblock?
