### ISSUE TITLE
haberturk.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3527] opened 2018-09-20 14:30 UTC
URL(s) where the issue occurs

`https://www.haberturk.com/cansu-taskin-sezonu-kapatmadi-magazin-haberleri-2149072-magazin/3`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by mapx-** [comment] 2018-09-20 15:50
fixed in turkish list

**Closed by mapx-** 2018-09-20 15:50 UTC

**Comment by felix-22** [comment] 2021-11-04 15:00
Similiar to : https://github.com/uBlockOrigin/uAssets/issues/10230 - a big nasty ad placeholder at the top caused by `@@||haberturk.com^$generichide` in uBlock filters – Annoyances  :

![r](https://user-images.githubusercontent.com/75935068/140337800-7b29f53e-cd2b-498d-8853-53c3b8b0840e.png)
