### ISSUE TITLE
[nsfw] chan.sankakucomplex.com: detection

### ISSUE THREAD

**Issue by MarsDDDDD** [uBlockOrigin/uAssets#19825] opened 2023-09-22 23:04 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chan.sankakucomplex.com/`

### Category

nuisance

### Description

I am aware of the issue revolving this website raised 2 days ago, but after that one got fixed, there seems to be a new issue where the first three lines of the image are blurred out. It could be residue from the last fix, or the site may have updated their adblock detection.

### Other extensions used

Dark reader, privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://files.catbox.moe/uykdvb.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 112178
 cosmetic: 50013
 scriptlet: 18657
 html: 1047
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 35618-114, 6m
  ublock-badware: 8033-6, 6m
  ublock-privacy: 589-0, 6m
  ublock-unbreak: 2166-0, 6m
  ublock-quick-fixes: 180-0, 6m
  easylist: 71074-671, 6m
  easyprivacy: 33169-772, 6m
  urlhaus-1: 3899-0, 6m
  plowe-0: 3719-1, 6m
filterset (user): [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 329 ms (selfie)
 maxAssetCacheWait: 124 ms
popupPanel:
 blocked: 11
 network:
  sankakucomplex.com: 1
  otaserve.net: 10
 extended:
  ##.scad
  ##iframe[src^="//c.otaserve.net"]
  ##[data-revive-zoneid]
  ##a[href^="https://s.zlinkc.com/"]
  ##+js(abort-current-script, Post.detect, show)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
```
</details>

**Comment by D4niloMR** [comment] 2023-09-22 23:40
test without privacy badger

**Comment by MarsDDDDD** [comment] 2023-09-22 23:54
That seems to be the cause... Sorry for not having tested everything out, I jumped to the conclusion thinking this is related to the issue raised a few days before.

**Comment by MarsDDDDD** [comment] 2023-09-23 00:21
My bad for going back and forth, after a bit of testing I am pretty sure that the issue is caused by none other than ublock. The blur filter reappeared after a while and switching privacy badger on and off doesn't change anything. I've tried comment and uncommenting this line which seemingly has no effect either.

**Comment by D4niloMR** [comment] 2023-09-23 00:30
I cant't reproduce on a new profile and default uBlock Origin in Firefox

**Comment by D4niloMR** [comment] 2023-09-23 01:07
I'm able to reproduce now, test:

```adb
sankakucomplex.com##+js(aopw, blacklist_method)
```

**Comment by MarsDDDDD** [comment] 2023-09-23 01:13
It seems that it only occurs when you are signed in. I created a new profile in firefox and the pop up described in #19806 is back after I signed in with my account.

And no, that doesn't seem to fix it.

**Comment by MarsDDDDD** [comment] 2023-09-23 01:25
Found some information regarding the issue:
https://sleazyfork.org/en/scripts/475850-delete-anti-adblock-sankaku-complex
I suggest to merge this post into #19806 as it seems to be the same issue.

**Comment by D4niloMR** [comment] 2023-09-23 01:56
> And no, that doesn't seem to fix it.

try: 
```adb
sankakucomplex.com##+js(rmnt, script, blur)
sankakucomplex.com##+js(acs, Post.fortitude, show)
```

**Comment by MarsDDDDD** [comment] 2023-09-23 02:02
> ```
> sankakucomplex.com##+js(rmnt, script, blur)
> sankakucomplex.com##+js(acs, Post.fortitude, show)
> ```

No luck, and the userscript updated a few minutes ago stopped working as well.

**Comment by D4niloMR** [comment] 2023-09-23 02:15
> No luck, and the userscript updated a few minutes ago stopped working as well.

I updated the filter

**Comment by MarsDDDDD** [comment] 2023-09-23 02:16
Right it's working, for now at least.

**Comment by MarsDDDDD** [comment] 2023-09-23 02:28
...Aaaand the arms race continues.

**Comment by D4niloMR** [comment] 2023-09-23 02:35
I'm not a contributor, and this filter wasn't even merged, lol.

He also changed the `[style="z-index: 1000000;"]`

You think it's a mere coincidence or he's watching here?

**Comment by MarsDDDDD** [comment] 2023-09-23 02:41
Hmmmmn I wonder why that tampermonkey script updated half an hour ago also stopped working :thinking: 

No they are actively watching how their anti adblock performs, as the userscript suggests in its description.

**Comment by D4niloMR** [comment] 2023-09-23 03:09
updated again

**Comment by MarsDDDDD** [comment] 2023-09-23 03:24
Wait till they change their subscription url and everything breaks again.

Can't thank u enough for ur effort btw.

**Comment by mapx-** [comment] 2023-09-23 05:28
`sankakucomplex.com##+js(rpnt, script, /.*_0x.*/, closeThis();)`

**Comment by Balorlord** [comment] 2023-09-23 07:35
chan.sankakucomplex.com##div:nth-of-type(13)
chan.sankakucomplex.com##+js(set, document.write, noopFunc)
chan.sankakucomplex.com##+js(set, document.querySelector, noopFunc)

**Closed** 2023-09-23 14:10 UTC

**Comment by D4niloMR** [comment] 2023-09-23 20:28
sometimes the images get blurred:

(NSFW)https://github.com/uBlockOrigin/uAssets/assets/70459964/5d6b89f1-1c48-47c7-b506-bb589111c25a

by the class `blacklisted`

**Comment by Couchy** [comment] 2023-09-24 02:05
Removing the blacklisted class from everything works for me as a quick fix. It might have a legitimate use though.

chan.sankakucomplex.com##.blacklisted:remove-class(blacklisted)

**Comment by soskamified** [comment] 2023-09-26 02:23
So as of write now none of the filters seem to work, as the pop up still appears. This may need to be reopened.

**Comment by soskamified** [comment] 2023-09-26 02:27
So as of right now, the pop up doesn't appear, but I am still redirected to a different adblocker detected page.

**Comment by mapx-** [comment] 2023-09-26 05:55
I cannot reproduce the detection. Did you disable any other extension ?

**Comment by soskamified** [comment] 2023-09-26 06:59
I think I figured it out, I had some other custom filters that caused the warning to trigger, and I was able to locate the problem filter.

**Comment by MarsDDDDD** [comment] 2023-10-13 20:09
SITREP, nuisance: Liking posts and search suggestion bar stopped functioning. Just purged caches and updated today for youtube. Dunno whether I should open a new issue so here u go.

**Comment by mapx-** [comment] 2023-10-13 20:12
it's ok here

**Comment by mapx-** [comment] 2023-10-13 20:14
provide an example page, if an account is required etc

**Comment by mapx-** [comment] 2023-10-13 20:31
see if this filter fixes your issue:

`sankakucomplex.com#@#+js(no-xhr-if, googlesyndication)`
