### ISSUE TITLE
Show YouTube Unsubscribe Box Cosmetic Filter

### ISSUE THREAD

**Issue by CypressWebs** [uBlockOrigin/uAssets#11186] opened 2022-01-04 05:56 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.youtube.com

### Describe the issue

I tried to whitelist the youtube unsubscribe overlay from the cosmetic filter but had no luck. I have tried all the following to get it to work. I have added a screenshot of what I want to show. The screenshot is when the plugin is turned off. Thanks

! 2022-01-04 https://www.youtube.com
www.youtube.com#@#.opened
www.youtube.com#@#.style-scope.yt-confirm-dialog-renderer
www.youtube.com#@##main.style-scope.yt-confirm-dialog-renderer
www.youtube.com#@#.style-scope .ytd-popup-container
www.youtube.com#@#.yt-confirm-dialog-renderer[dialog][dialog][dialog]

### Screenshot(s)

![www youtube com (1)](https://user-images.githubusercontent.com/96221870/148015462-ac370724-e703-4b1e-a435-8a2d405ed359.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78349
  cosmetic: 40312
  scriptlet: 16397
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62576-9, now
    easyprivacy: 26599-17, now
    plowe-0: 3682-817, now
    ublock-abuse: 76-0, now
    ublock-badware: 3648-65, now
    ublock-filters: 30109-140, now
    ublock-privacy: 194-3, now
    ublock-unbreak: 1737-39, now
    urlhaus-1: 7628-0, now
filterset (user): [array of 43 redacted]
trustedset: 
  added: [array of 64 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 354
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment] 2022-01-04 05:57
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2022-01-04 05:57 UTC

**Comment by CypressWebs** [comment] 2022-01-04 06:07
I guess if it's a "duplicate" please just delete this thread.
