### ISSUE TITLE
2ip.ru

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#7890] opened 2020-09-09 06:45 UTC
### URL(s) where the issue occurs

`https://2ip.ru/`

### Describe the issue

AdBlock detected

### Screenshot(s)

![92563644-8dfb1700-f280-11ea-9d1e-a15dc11eabd1](https://user-images.githubusercontent.com/57287308/92564762-5db47800-f282-11ea-86ad-298a70ad2c5a.png)

### Versions

- Browser/version: Opera|Stable
- uBlock Origin version: 1.29.2

### Settings
![image](https://user-images.githubusercontent.com/57287308/92563778-c7338700-f280-11ea-9803-c3e799d298fb.png)

**Comment by mapx-** [comment] 2020-09-09 07:02
keep the default setup, test again

**Comment by P0Rtvine** [comment] 2020-09-09 07:08
@mapx- 
![2020-09-09_100606](https://user-images.githubusercontent.com/57287308/92565937-2646cb00-f284-11ea-8b6c-36e8ab5a0a2f.png)
![2020-09-09_100621](https://user-images.githubusercontent.com/57287308/92565943-28108e80-f284-11ea-82d7-05098ea1cefe.png)

**Comment by uBlock-user** [comment] 2020-09-09 07:10
force update uBlock Filters, I fixed it a day or so ago.

**Comment by uBlock-user** [comment] 2020-09-09 07:13
fixed in https://github.com/uBlockOrigin/uAssets/commit/aa8737ffe2b16d48beb8a132c6003c9cece35379

**Comment by mapx-** [comment] 2020-09-09 07:15
still working fine in opera even enabling vpn / block trackers / block ads

**Comment by P0Rtvine** [comment] 2020-09-09 07:19
It doesn't work for me
**Disable Opera's VPN/adblocker if it is not working.** - Off
https://i.imgur.com/OTbLYk8.gif

**Comment by uBlock-user** [comment] 2020-09-09 07:21
It's showing you the IP address of your ISP, how is it not working ?

**Comment by uBlock-user** [comment] 2020-09-09 07:22
Try with Chrome/Firefox on default settings.

**Comment by P0Rtvine** [comment] 2020-09-09 07:27
**Also did you disable all other extensions in Opera ?**
Yes, only uBO.
Chrome
![2020-09-09_102237](https://user-images.githubusercontent.com/57287308/92567926-141a5c00-f287-11ea-8a56-b85fcda7e3fc.png)

**Comment by uBlock-user** [comment] 2020-09-09 07:32
I tried to recreate the scenario with a Ukraine VPN and still can't reproduce, something on your end is causing this.

**Comment by P0Rtvine** [comment] 2020-09-09 07:37
@uBlock-user 
list of requests - https://dropmefiles.com/WXmoo
page snapshot - https://dropmefiles.com/Xagva

**Comment by uBlock-user** [comment] 2020-09-09 07:41
Add `2ip.ru#@#.advMenuTab` and see if that works.

**Comment by P0Rtvine** [comment] 2020-09-09 07:42
Yes, it works.

**Closed** 2020-09-09 07:46 UTC
Labels: unable to reproduce

**Comment by P0Rtvine** [comment] 2020-09-09 09:48
Fixed in **RU AdList** https://hg.adblockplus.org/ruadlist/rev/1e84d4094ef4
