### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Indianballe** [uBlockOrigin/uAssets#13829] opened 2022-06-24 20:39 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=BTp6Dx966uc`

### Category

ads

### Describe the issue

I get both ads while having ublock enabled (using Opera gx) 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 101
filterset (summary): 
  network: 81395
  cosmetic: 46319
  scriptlet: 17623
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    SWE-1: 3949-0, 1d.23h.38m
    easylist: 68820-59, 1d.23h.35m
    easyprivacy: 27251-129, 1d.23h.34m
    plowe-0: 3647-785, 1d.23h.33m
    ublock-abuse: 75-0, 1d.23h.31m
    ublock-badware: 4211-93, 1d.23h.29m
    ublock-filters: 31861-113, 1d.23h.28m
    ublock-privacy: 224-3, 1d.23h.27m
    ublock-quick-fixes: 228-2, 20h.26m
    ublock-unbreak: 1811-42, 1d.23h.25m
    urlhaus-1: 4651-0, 20h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 541 ms (selfie)
  maxAssetCacheWait: 221 ms
popupPanel: 
  blocked: 58
  blockedDetails: 
    youtube.com: 37
    doubleclick.net: 5
    googleadservices.com: 2
    googlesyndication.com: 14
```
</details>

**Comment by Procyon-b** [comment] 2022-06-24 20:51
Have you tried with "Suspend network activity until all filter lists are loaded" enabled? (ublock's dashboard, "Filter lists" tab)

**Comment by krystian3w** [comment] 2022-06-24 22:59
Duplicate of #7636

**Closed** 2022-06-25 04:28 UTC
Labels: duplicate
