### ISSUE TITLE
Ad bypass on techweez.com

### ISSUE THREAD

**Issue by RobertOrinCharles** [uBlockOrigin/uAssets#2949] opened 2018-07-20 20:33 UTC
### URL(s) where the issue occurs

`http://www.techweez.com/2018/07/20/gsma-360-report-kigali/`

### Describe the issue

All articles on the site above post an ad that bypasses default filters.

### Versions

- Browser/version: Firefox 61.0.1
- uBlock Origin version: 1.16.14

### Settings

- Default.

### Notes

The filter below seems to resolve this issue.

`www.techweez.com##.a-63.a-single`

**Comment by okiehsch** [comment] 2018-07-20 20:35
Before ou open countless issues.
If an issue can be fixed without using extended syntax, i.e. `script:inject`, `redirect` or [procedural cosmetic](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters) filters and the issue is not about

- anti-adblock 
- ad-reinsertion
- popups/popunders
- site breakage

The issue will, as a rule of thumb, not be fixed by `uAssets`, because fixing it in `EasyList` if possible is 
 preferable.

**Closed** 2018-07-20 20:36 UTC

**Comment by smed79** [comment] 2018-07-20 20:48
https://forums.lanik.us/viewtopic.php?f=62&t=41236
