### ISSUE TITLE
[NSFW] pornhub.com - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#471] opened 2017-06-24 10:47 UTC
Ad elements/blank ads are created on pages on `https://www.pornhub.com`.

**SS:** https://i.imgur.com/Opd70y1.png
**Error URL:** `https://www.pornhub.com/video`

These ad elements seem to be created by an inline script, though I am unable to pinpoint the exact one. 

There is also an ad leftover above video players: `pornhub.com##.abovePlayer`

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by okiehsch** [comment] 2017-06-24 17:43
`pornhub.com##script:inject(abort-on-property-read.js, dcEl)`
works on my end but I still classify this as an annoyance, so I won't fix it in `uBO-filters`.

**Comment by gotitbro** [comment] 2017-06-24 20:01
@okiehsch Seems like a cosmetic filter would be better in this case as it takes sometime before the ad frame is blocked and sometimes it even isn't blocked with the above filter.

**_Adguard English Filter_** list has a filter which hides the top ad but not the bottom one:
`pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])`


This again does not seem to be annoyance to me. I guess the definition needs to be clarified.

**Comment by okiehsch** [comment] 2017-06-24 20:13
@gorhill are blank ad spaces an annoyance in your view or should they be fixed in `uBO-filters`?

**Comment by Hrxn** [comment] 2017-06-24 22:16
Should be included, in my opinion. Striving for consistency with the default option _"Hide placeholders of blocked elements"_.

**Comment by gotitbro** [comment] 2017-06-24 22:37
I would also like to clarify that I am not asking for going after all blank ads/elements but only when the content itself is affected.

**Comment by okiehsch** [comment] 2017-06-24 22:42
> only when the **content** itself is affected.

I agree with that, I just don't see it in this issue. 
I would also agree that it is more than an annoyance if there are so many blank ads/elements on
a given site that it looks like whoever designed that site was either drunk or incompetent. Again not the case in this issue in my opinion.

**Comment by gotitbro** [comment] 2017-06-24 22:48
>I just don't see it in this issue.

I would argue otherwise and say that ad elements are getting directly in the way of content. Here again we have differing views and that's why I was asking for a clear cut definition.

**Comment by okiehsch** [comment] 2017-06-24 22:57
> a clear cut definition.
There is no clear cut definition of annoyance, what is merely a "nuissance" for me, may very well be "abhorrent" to you or vice versa.
Le's agree to disagree and wait what gorhills "definition" is.

**Comment by gorhill** [comment] 2017-06-25 00:53
Does these placeholders exist if using Adguard English filters?

**Comment by okiehsch** [comment] 2017-06-25 00:59
Yes.

**Comment by gotitbro** [comment] 2017-06-25 02:07
@gorhill @okiehsch No they don't. I literally picked this filter from that list:
`pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])`

You can test by adding only: https://filters.adtidy.org/extension/chromium/filters/2.txt to "**_Custom filters_**" and disabling the others.

**Comment by okiehsch** [comment] 2017-06-25 02:20
I added Adguard English filters to my default setting

![adg](https://user-images.githubusercontent.com/16838044/27513186-da9b1634-595c-11e7-8064-4a2ff6d4e38b.png)

and I still get the blank ads/elements
![adgu](https://user-images.githubusercontent.com/16838044/27513193-03cbd58e-595d-11e7-8cfb-e421517a3c9c.PNG)

**Comment by okiehsch** [comment] 2017-06-25 02:45
I double checked, the filter 
````
pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])
````
Logger using Chrome shows no hit
![pornb](https://user-images.githubusercontent.com/16838044/27513277-98301ec6-5960-11e7-849e-d27aca3a287a.PNG)
on my end.

**Comment by gotitbro** [comment] 2017-06-25 03:03
@okiehsch Works with both the filter list and manually added filter on my side: https://i.imgur.com/ePFREqV.png

Does not show up when the log entries are filtered, can be seen without filtering.

Also what URL have you added for the Adguard English filter? It shows up only as "English filter" on my end when I add `https://filters.adtidy.org/extension/chromium/filters/2.txt`: 
![ba7jbrn 1](https://user-images.githubusercontent.com/20359493/27513358-d080a348-5980-11e7-96c3-74722a026dfe.png)

**Comment by okiehsch** [comment] 2017-06-25 03:18
I installed it from `filterlists.com`, anyway it is the same list.
I now reinstalled uBO but this filter still does not work for me while `pornhub.com##script:inject(abort-on-property-read.js, dcEl)`, which works for me, does not work for you, quite the impasse.

**Comment by Hrxn** [comment] 2017-06-25 07:31
Might be caused by dynamic filtering settings?

**Comment by gotitbro** [comment] 2017-06-25 09:50
@okiehsch https://filterlists.com lists the old URLs for Adguard lists try the new ones from here: https://kb.adguard.com/en/general/adguard-ad-filters

I did not say that the filter suggested by you does not work. Its just that blocked frames take time to hide (they are hidden by the website itself and cause the suggested filter to take effect a little late). Here is a screencapture better explaining the issue: https://streamable.com/1xzz9

It is just that a cosmetic filter is better in this case.

**Comment by Alex-302** [comment] 2017-06-25 10:07
Guys, please check this rule:
```
pornhub.com##.nf-videos > div.sectionWrapper > div.sectionTitle+div[class*=" "][-ext-has='> div[class] > a.removeAdLink']
```
If it helps, I will add it to Adguard English filter
`https://filters.adtidy.org/extension/ublock/filters/2.txt`

**Comment by Alex-302** [comment] 2017-06-25 10:12
@gotitbro 

> It shows up only as "English filter" on my end when I add https://filters.adtidy.org/extension/chromium/filters/2.txt:

We have a separate filters for uBO:
`https://filters.adtidy.org/extension/ublock/filters/*.txt`
<details>

* number of the filter:
  - `1` - Russian;
  - `2` - English;
  - `3` - Spyware;
  - `4` - Social filter;
  - `6` - German;
  - `7` - Japanese;
  - `8` - Dutch;
  - `13` - Turkish;
</details>

**Comment by gotitbro** [comment] 2017-06-25 12:53
@Alex-302 Thanks for that, is there a listing of all supported extensions, OSes and other platforms.

Another thing thing to note is that even if I use the `chromium` URL uBo automatically rejects unsupported filters.

**Comment by okiehsch** [comment] 2017-06-25 16:26
@gotitbro you said 

> sometimes it even isn't blocked with the above filter

if a filter only works most of the time it is pretty useless in my opinion.
I agree that, because of the delay you demonstrated. a working cosmetic filter would be better in this case.

@Alex-302 thanks but your proposed filter does not work for me.

**Comment by Alex-302** [comment] 2017-06-25 17:45
@gotitbro 
maybe HTML is different. Please upload saved page(HTML+resources)

**Comment by gotitbro** [comment] 2017-06-25 20:36
@Alex-302 It might be, here you go with the saved page:
https://uploadfiles.io/lat1q

**Comment by gotitbro** [comment] 2017-06-27 02:35
Adguard filters that work for me (converted automatically by uBO to its syntax):
```
pornhub.com##body > .wrapper + div[class]:if(> .removeAdLink)
pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])
```

These hide all the ad elements described in the initial post.

**Comment by Alex-302** [comment] 2017-06-27 17:12
but the rules
```
pornhub.com##body > .wrapper + div[class][-ext-has='> .removeAdLink']
pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])
```
are already exists in English filter.

**Comment by gotitbro** [comment] 2017-06-27 18:21
@Alex-302 Posted here as Adguard filters are not the default ones in uBO and other users who might not be using those can see the fix.

**Comment by Alex-302** [comment] 2017-06-27 18:22
Ok, got it.

**Comment by gotitbro** [comment] 2017-06-27 19:06
@gorhill So, what will be done with such issues? Will they be resolved in uBO filters or are they simply annoyances (I don't think they are)? 

Should the Adguard filters be default or be presented as options (I think it will be highly beneficial as has also been expressed by you)?

Please clarify these points, thank you.

**Comment by gorhill** [comment] 2017-06-28 15:33
Does that work?

    pornhub.com##.nonesuch:has(> div[class] > a.removeAdLink)

**Comment by okiehsch** [comment] 2017-06-28 15:38
That filter works for me.

**Comment by gotitbro** [comment] 2017-06-29 05:45
@gorhill Does not work for me. I don't even get that element `.nonesuch` on the site as can be seen in the saved webpage I uploaded above (https://uploadfiles.io/lat1q).

**Comment by gorhill** [comment] 2017-06-29 13:02
Elements with class `.nonesuch` are created dynamically with javascript, line 4511 in your HTML file.

My filter works for me with default filter lists/settings, and no other extension installed, only uBO.

**Comment by gorhill** [comment] 2017-06-29 13:12
@gotitbro Does this work?

    pornhub.com##script:inject(abort-on-property-read.js, page_params.zoneDetails)

**Comment by gotitbro** [comment] 2017-06-29 15:52
@gorhill This has the same effect as the first filter suggested by @okiehsch in this issue:
https://github.com/uBlockOrigin/uAssets/issues/471#issuecomment-310893230

The ad element takes time to hide and the filter does not cover the ad space above the footer.

**Comment by kasper93** [comment] 2017-06-29 22:30
I like how they try to make it hard to hide those ads. 

There is already 
```
pornhub.com##.sectionWrapper > div[class]:has(:scope > div > .ad-link)
```
in uBlock list so the "top" section is taken care of. At least static part of it. After page load it is replaced with `.nonesuch` and this is taken care by @gorhill filter
```
pornhub.com##script:inject(abort-on-property-read.js, page_params.zoneDetails)
```
there is footer one which is not taken care now by uBlock list. 

> The ad element takes time to hide
@gotitbro Yes, you will see delay before static element is hidden, those are dynamic filters and uBlock hides them during page load. So they can blink. 

Here are filters for top/footer ads, which hopefully fulfill your needs. 
```
pornhub.com##div[class]:has(> a.removeAdLink:first-child)
pornhub.com##div:has(> div[class]:only-child > a.removeAdLink:first-child)
pornhub.com##script:inject(abort-on-property-read.js, page_params.zoneDetails)
```

**Comment by gorhill** [comment] 2017-06-29 22:55
> The ad element takes time to hide

The delay is impossible to prevent.

Removing myself from this issue, as it does not look like any solution will be deemed acceptable.

**Comment by gotitbro** [comment] 2017-06-30 10:01
@kasper93 I have EasyList enabled, why wouldn't I?

@gorhill I see no delay in the hiding of elements on the home page if add these filters from the Adguard English Filter (as mention in this comment https://github.com/uBlockOrigin/uAssets/issues/471#issuecomment-311236044):
```
pornhub.com##body > .wrapper + div[class]:if(> .removeAdLink)
pornhub.com##.sectionWrapper > div[class*=" "]:if(> div[class]:only-child > a.removeAdLink)
pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])
```

Though a little delay is seen on the search results page (https://www.pornhub.com/video/search?search=hello) the above filters work perfectly fine for me.

**Comment by kasper93** [comment] 2017-06-30 10:34
There is no delay because 
```
pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])
```
is pure css filter, unlike ones with `has()` operator which are more robust, but need to be evaluated by content script.

**Comment by stanlane** [comment] 2017-08-24 12:33
https://github.com/uBlockOrigin/uAssets/issues/483

**Comment by kasper93** [comment] 2017-08-26 11:34
@stanlane And why exactly do you spam here?

@okiehsch Maybe you could merge those filters (and close ticket) so people don't comeback here periodically.  Hopefully that's all things. But I can't really tell.

```
pornhub.com##.abovePlayer:has(.sponsor-text)
pornhub.com##div[class]:has(> a.removeAdLink:first-child)
pornhub.com##div:has(> div[class]:only-child > a.removeAdLink:first-child)
pornhub.com##script:inject(abort-on-property-read.js, page_params.zoneDetails)
```

**Comment by stanlane** [comment] 2017-09-02 06:43
NEW: "Ads by trafficjunky" will appear when you pause the videos. Here is how to remove it:

> www.pornhub.com###pb_block

**Closed** 2017-12-13 18:18 UTC

**Comment by C0nw0nk** [comment] 2018-06-03 20:49
```https://fuck-journey.com/tds?tdsId=u2079tro_r&tds_campaign=u2079tro&utm_source=dda&utm_medium=web&utm_campaign=tj_wtab&utm_term={utm_term}``` Advertisement URL's as fake menu items to misslead into clicking.
