### ISSUE TITLE
uBlockOrigin I think it breaks https://www.caminogeek.com/ and https://www.softzone.es/

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#8250] opened 2020-11-20 23:16 UTC
### URL(s) where the issue occurs
```
https://www.caminogeek.com/
https://www.softzone.es/
```

### Describe the issue
This has been happening to me since the previous version of Firefox and after tests of all kinds, activating and deactivating filters without solving anything, I have decided to expose it in the repository. It is one of the strangest cases that have happened to me since I use uBlock origin.

From what I have observed during testing, uBlock origin and the Only-HTTPS mode of the Firefox options are involved. (The HTTPS-only mode comes in the Privacy and security section of the Firefox options).

I have tried with the default Firefox configuration and with my custom configuration, with both the problem happens.

Firefox's HTTPS-only option can be blamed as the cause of the problem but it leaves me in doubt as disabling or uninstalling uBlock DOES NOT break pages.

I try to explain ...

- If I disable or uninstall uBlock and enable "Enable HTTPS-only mode in all windows" in the Firefox options it DOES NOT break the pages. Sometimes, not always, it breaks the page but if I update it it fixes.

- If I activate uBlock, it breaks the pages by activating or deactivating "Activate HTTPS-only mode in all windows" in the Firefox options.

 

### Screenshot(s)
https://user-images.githubusercontent.com/44229110/99858460-e6f2ff80-2b8d-11eb-9cab-4678dd530cf0.png

https://user-images.githubusercontent.com/44229110/99858472-eeb2a400-2b8d-11eb-9598-b712c7f588bb.png

### Versions
- Browser/version: [Firefox Browser 64-Bit v83.0.0]
- uBlock Origin version: [v1.31.0]

### Settings
https://user-images.githubusercontent.com/44229110/99858646-510ba480-2b8e-11eb-9066-e1925cf228bb.jpg
https://user-images.githubusercontent.com/44229110/99858661-5668ef00-2b8e-11eb-9dab-3df7cc3d526c.png

**Comment by Yuki2718** [comment] 2020-11-21 06:37
I can't reproduce with the same settings minus Stop Autoplay list (relaunched after turning on HTTPS-only mode just in case), Firefox 83.0 + uBO 1.31.0 accessed from Madrid IP.

**Comment by mapx-** [comment] 2020-11-21 08:36
for the first site (loading correctly from the beginning), test:

`@@||googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=caminogeek.com`

**Comment by okiehsch** [comment] 2020-11-21 09:59
The filter mentioned by **mapx-** works on my end, what also works is loading the site bypassing the cache, so it looks atlest partially like a site issue to me.

**Comment by uBlock-user** [comment] 2020-11-21 10:03
It's a site issue, jQuery fails to load as per the console.

**Comment by mapx-** [comment] 2020-11-21 11:06
no issue on my end for softzone

**Comment by Jose1971AB** [comment] 2020-11-21 20:22
Hello friends, good night.

Sorry for the delay in responding, I have been unable to connect before.

**A new page has emerged** in which the same thing happens as in the ones I cited in my question [**https://www.redeszone.net/**] and more exactly in [**https://www.redeszone.net/2019/02/27/webrtc-deshabilitar-chrome-firefox/**]

**Please do not close the case, I am a basic user and I need to do the necessary tests, which are somewhat complicated for me. As I mentioned in my question it is the weirdest thing that has happened to me with uBlock. I will not delay in answering you, give me a little time.**

Thank you all

**Comment by Jose1971AB** [comment] 2020-11-21 22:35
Good night again friends

With the EDGE Chromiun browser it works fine, even without the filter that @mapx- offers me, it only happens to me with Firefox.

Leaving the My filters section empty also happens, so I don't know where the fault may be.

According to the filter offered by @mapx- 
`@@ || googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=caminogeek.com` obviously only works for [https://www.caminogeek.com/] but still according to the tests carried out the following happens to me ...

If I leave the only-HTTPS mode activated in the Firefox options, it does NOT work in any way, not even with the filter
`@@ || googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=caminogeek.com`

If I include the filter and deactivate the HTTPS-only mode it works but when I refresh the page it breaks again, that is ... it only works when restarting firefox and entering the page for the first time, if I update it again it breaks and it stops working, to make it work again I have to restart Firefox again.

The remaining two pages still do not work

I don't know what else to try, I don't know what could happen.

I go to bed, I can't take it anymore, I fall asleep, tomorrow will be another day.

Greetings and thank you very much

**Comment by uBlock-user** [comment] 2020-11-22 05:45
@Jose1971AB As said this is a site issue, look at the console, jQuery fails to load and there's another Uncaught TypeError, site issues cannot be fixed by uBO. Even with mapx-'s filter the images fail to load intermitttently on my side and I have to bypass cache to make them load again.

**Comment by Jose1971AB** [comment] 2020-11-22 12:18
Hello uBlock-user, good morning friend

Do you mean to say that it is a Firefox error and uBlock cannot solve it right? ... because in EDGE Chromium all 3 pages are perfectly visible.

**I don't know to what extent it is a Firefox or page error** because what I don't understand is that if I disable or uninstall uBlock and enable "Enable HTTPS-only mode in all windows" in the Firefox options it DOES NOT break the pages. Sometimes, not always, it breaks the page but if I update it it fixes.

I don't know friend ... what a mess !!!

**Note**: could you leave this issue open for a while to see if someone comes up with something to solve it? ... in case it is obviously possible. I would appreciate it.

**Comment by uBlock-user** [comment] 2020-11-22 12:28
> Do you mean to say that it is a Firefox error and uBlock cannot solve it right?

Site issue, contact the admin of the site and tell him to fix the jQuery failure and uncaught errors getting lodged in the console.

**Closed** 2020-11-22 12:28 UTC
Labels: external

**Comment by Jose1971AB** [comment] 2020-11-22 18:35
Hi @uBlock-user, good night friend.

> @uBlock-user 
Site issue, contact the admin of the site and tell him to fix the jQuery failure and uncaught errors getting lodged in the console.

Sorry to bother you again, but how to do that? ... would I have to do it for each page? ... would that be through the Contact section of each page? ... I don't know how to do that could you inform a bit? ...

Anyway, thank you very much for everything.

Greetings friends

**Comment by Yuki2718** [comment] 2020-11-23 04:44
> 
> Sorry to bother you again, but how to do that? ... would I have to do it for each page? ... would that be through the Contact section of each page? ... I don't know how to do that could you inform a bit? ...
> 

Yes and yes if the page has the contact info. If it doesn't, just give up. uBO **is** a content-blocker and NOT a tool to fix site issues caused by site admin's incompetence.

**Comment by Jose1971AB** [comment] 2020-11-23 18:23
Hello @Yuki2718 good afternoon friend.

Ok ... I'll try to do it, see how it turns out.

Greetings and thanks for everything.
