### ISSUE TITLE
blogto.com: breakage

### ISSUE THREAD

**Issue by h2559** [uBlockOrigin/uAssets#23709] opened 2024-05-15 07:30 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

so i go to this website called blogTO, and one of the default filters (when I reset the extension) disables instagram enbeds, 

one of the ways to get around this is to disable (edit: one of the ads list, either ublock filter ads, or easylist, i forget which exactly), which is bad because a lot of other ads gets passed thru, and then i read that someone said you can just add instagram to the trusted sites so that the entire website gets whitelisted! it all works now, but there is a strange bug...

### A specific URL where the issue occurs.

```yaml
https://www.blogto.com/eat_drink/2024/05/cafe-olimpico-montreal-coming-toronto/
```

### Steps to Reproduce

1. reset ublock origin to defaults (optional, but lets work with a clean slate)
2. go to trusted sites and add instagram.com
3. go to blogto.com, click on an article until you see an instagram enbed, it should be blank
4. refresh the webpage, the embed should show up now!

### Expected behavior

at step 3, step 4 should happen instead, without refreshing a second time

i took some screenshots:
https://github.com/uBlockOrigin/uBlock-issues/assets/20052727/d0537112-7017-455f-95ff-4cde3f3bafb2

https://github.com/uBlockOrigin/uBlock-issues/assets/20052727/01789ebc-38dd-49a5-b282-d7b6ad486d3e

https://github.com/uBlockOrigin/uBlock-issues/assets/20052727/15ae4e53-8afa-4c3a-8d97-5bd840090aa3

https://github.com/uBlockOrigin/uBlock-issues/assets/20052727/354b3d4d-817d-4da5-ab16-bfb04b8ded91

### Actual behavior

step 4 happens

i don't know why this happens, but i am guessing the filter lists logic doesnt activate the trusted list section the first time, it needs a refresh?

### uBO version

 1.57.0

### Browser name and version

Version 124.0.6367.201

### Operating System and version

mac os x big sur 11.7.10

**Comment by garry-ut99** [comment] 2024-05-15 13:43
I could reproduce the blank embed instagram only the first time I visited: `https://www.blogto.com/eat_drink/2024/05/le-lert-toronto/` (on Firefox) but not anymore, despite I tried many times, on both Firefox and Chromium, hence I'm unable to determine whether it was caused by filters or not, because I can no longer reproduce.

**Comment by krystian3w** [comment] 2024-05-15 13:54
Sometimes they don't load for me in the 'Virtualna Poland' area, and less often in the Polsat-Interia group.

**Comment by stephenhawk8054** [comment] 2024-05-16 03:36
I also could only reproduce the first time visit the site yesterday. After that I could not reproduce it any more.

**Comment by garry-ut99** [comment] 2024-05-16 08:22
Has happened again today for me: blank at the first visit only (in Firefox), then I have tried to reproduce in Chromium immediately afterwards: I did reproduce but only after several page reloads (means: not at the first visit). Nothing blocking `instagram.com` in the logger, except the beacon which appears even when the instagram embed does load, so there doesn't seem to be any relationship.

Next time I will try to visit the page and reproduce the issue with uBlock disabled to make sure whether it's caused by filters or not.

**Comment by stephenhawk8054** [comment] 2024-05-16 23:43
@h2559 Currently can you reproduce the issue any more?

**Comment by gorhill** [comment] 2024-05-17 17:49
> I have reproduced again the blank embed instagram in Chromium with uBlock disabled.

Closing as an external issue, unrelated to uBO.

**Closed by gorhill** 2024-05-17 17:49 UTC

**Comment by stephenhawk8054** [comment] 2024-05-22 14:52
The problem is the embed can be not-appear at random even without uBO.

**Comment by stephenhawk8054** [comment] 2024-05-22 15:07
Yes, I was asking to see if you still had the issue with your link above because at that time, there's only our speculations.

Anyways, the only way to investigate this issue is having clear steps to reproduce. Otherwise, we can't do much.

**Comment by stephenhawk8054** [comment] 2024-05-22 15:14
As said, the issue can be from the website itself, as others were able to reproduce even without uBO.
