### ISSUE TITLE
Ublock origin

### ISSUE THREAD

**Issue by kucpy** [uBlockOrigin/uAssets#20396] opened 2023-11-01 08:26 UTC
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello I have a problem with u block origin on youtube. When I went to youtube i have black screen. Also, no video loads, just a black screen and some problem appears

### URL(s) where the issue occurs.

youtube.com/watch

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/149570698/e03a3d0b-8738-4748-a13b-1da57afd78ac)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106171
 cosmetic: 47893
 scriptlet: 19017
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  POL-0: 8002-11, 12m
  POL-2: 1276-13, 12m
  easylist: 72237-38, 12m
  easyprivacy: 32852-64, 12m
  plowe-0: 3722-1079, 12m
  ublock-badware: 7402-138, 12m
  ublock-filters: 35150-183, 12m
  ublock-privacy: 659-6, 12m
  ublock-quick-fixes: 183-113, 21m
  ublock-unbreak: 2134-33, 12m
  urlhaus-1: 11290-0, 11m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 108 ms
```
</details>

**Comment by gwarser** [comment] 2023-11-01 08:28
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19976

**Closed** 2023-11-01 08:28 UTC
