### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Darksempaii** [uBlockOrigin/uAssets#14171] opened 2022-07-30 01:21 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=ynNkSpa8F6c`

### Category

ads

### Describe the issue

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82952
  cosmetic: 49940
  scriptlet: 17753
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68901-51, 9h.3m
    easyprivacy: 27459-123, 9h.2m
    plowe-0: 3645-779, 9d.6h.43m
    spa-0: 3898-36, 4h.57m
    spa-1: 4572-172, 9h.1m
    ublock-abuse: 76-0, 9d.6h.43m
    ublock-badware: 4209-92, 9h
    ublock-filters: 32336-166, 8h.59m
    ublock-privacy: 225-3, 9d.6h.43m
    ublock-quick-fixes: 291-18, 4h.56m
    ublock-unbreak: 1851-44, 8h.58m
    urlhaus-1: 4839-0, 4h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 927 ms (selfie)
  maxAssetCacheWait: 624 ms
popupPanel: 
  blocked: 561
  blockedDetails: 
    youtube.com: 474
    doubleclick.net: 17
    google.com: 36
    google.com.mx: 1
    googlesyndication.com: 21
    googlevideo.com: 12
```
</details>

**Comment by hKQwHW** [comment] 2022-07-30 03:32
cannot reproduce using chrome on win 11

**Comment by MasterKia** [comment] 2022-07-30 12:29
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/Youtube-Issues

**Closed** 2022-07-30 12:39 UTC
