### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by Mverte77** [uBlockOrigin/uAssets#14427] opened 2022-08-19 03:54 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=2GuRongO41o`

### Category

breakage

### Describe the issue

Video not load, y check whit not ublock, and work, thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 175149
  cosmetic: 228109
  scriptlet: 38157
  html: 732
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 67046-5539, 2h.57m
    adguard-mobile: 8154-150, 2h.57m
    adguard-spyware: 26471-1109, 2h.57m
    adguard-spyware-url: 718-2, 2h.57m
    block-lan: 43-0, 2h.57m
    adguard-annoyance: 56479-4930, 2h.57m
    adguard-social: 18227-1060, 2h.57m
    fanboy-thirdparty_social: 68-0, 2h.57m
    fanboy-annoyance: 79471-63572, 2h.57m
    fanboy-cookiemonster: 40078-133, 2h.57m
    fanboy-social: 23293-28, 2h.57m
    ublock-annoyances: 4532-4, 2h.57m
    JPN-1: 7655-37, 2h.56m
    curben-phishing: 43914-4, 2h.56m
  default: 
    user-filters: 106-12, never
    ublock-filters: 33222-165, 2h.57m
    ublock-badware: 4247-0, 2h.57m
    ublock-privacy: 247-0, 2h.57m
    ublock-abuse: 76-0, 2h.57m
    ublock-unbreak: 1845-1, 2h.57m
    easylist: 69582-939, 2h.57m
    easyprivacy: 27362-9779, 2h.57m
    urlhaus-1: 4611-0, 2h.57m
    plowe-0: 3635-3, 2h.56m
    spa-0: 3858-3, 2h.56m
    spa-1: 4599-110, 2h.56m
    ublock-quick-fixes: 406-0, 2h.56m
filterset (user): [array of 106 redacted]
trustedset: 
  added: [array of 62 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 1024
  prefetchingDisabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 626 ms (selfie)
  maxAssetCacheWait: 307 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    youtube.com: 22
    doubleclick.net: 2
    google.com: 2
    google.com.mx: 1
    googlevideo.com: 3
```
</details>

**Comment by MasterKia** [comment] 2022-08-19 03:55
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/youtube-issues

**Closed by MasterKia** 2022-08-19 03:55 UTC
