### ISSUE TITLE
perchance.org: detection

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#20666] opened 2023-11-14 00:53 UTC
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://perchance.org/ai-text-to-image-generator`

### Category

detection

### Description

Site states the following: 
https://github.com/uBlockOrigin/uAssets/assets/73433060/eef881bf-cab1-4a39-9dc8-51f47d0de565

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/130af5ac-9e40-4256-8fd4-7c09d751cdf3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104574
 cosmetic: 43638
 scriptlet: 18842
 html: 1100
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36423-152, now
  ublock-badware: 7498-9, now
  ublock-privacy: 661-0, now
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 183-7, 1h.36m
  easylist: 75306-699, now
  easyprivacy: 32876-725, now
  urlhaus-1: 11030-0, 1h.37m
  plowe-0: 3724-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 29 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 297 ms
 maxAssetCacheWait: 105 ms
popupPanel:
 blocked: 5
 network:
  criteo.net: 1
  googletagmanager.com: 1
  id5-sync.com: 1
  pub.network: 1
  snigelweb.com: 1
 extended:
  ##[data-freestar-ad]
  ##+js(addEventListener-defuser, message, adPoweredPluginInUse)
  ##+js(replace-node-text, script, !await, await)
```
</details>

**Comment by Antiokh** [comment] 2023-11-27 14:00
Again detected

**Comment by huyszn** [comment] 2024-01-07 04:56
@ItsProfessional I get the detection on this page: `https://perchance.org/ai-story-generator`. You have to wait around 1 minute on this page before the detection alert appears.

**Comment by mrsemi** [comment] 2024-01-07 18:20
Still getting detection after filter updates.

**Comment by mrsemi** [comment] 2024-01-07 19:01
Latest update breaks the functionality of the page

**Comment by mrsemi** [comment] 2024-01-08 04:18
Detected again
![Screenshot_20240107-231809](https://github.com/uBlockOrigin/uAssets/assets/155864310/5a73d89a-e8db-41e7-83aa-beea43914a97)

**Comment by sanitycandy** [comment] 2024-01-08 07:34
I can confirm I am getting the same error on a different generator at `https://perchance.org/incorrect-quote-generator`, no idea if I should open another issue as it's a slightly different URL so I'm going to post it here. Same image as the last screenshot where it turns to a completely white screen after a few seconds with the same text.

**Comment by huyszn** [comment] 2024-01-08 07:45
The site owner keeps using `${""}` to break the filters. `innerHTML` changed to `inner${""}HTML`

**Comment by iam-py-test** [comment] 2024-01-08 11:32
`perchance.org##+js(nostif, inner)` causes breakage for me:
![image](https://github.com/uBlockOrigin/uAssets/assets/84232764/06d3718f-050e-4aec-a8ea-2a404a4dcd4f)
Also causes anti-blocker (which I have been yet to solve).
Thanks

**Comment by ItsProfessional** [comment] 2024-01-14 08:32
This is an **ongoing** issue. Why did you close it?

**Comment by Spectral-Dreams** [comment] 2024-01-14 19:03
Can confirm. Still getting this issue on that particular site.

**Comment by ItsProfessional** [comment] 2024-01-14 19:43
https://github.com/uBlockOrigin/uAssets/commit/efb3b11afd956b0536ea44b7dcebbbc193fee20e

**Comment by iam-py-test** [comment] 2024-01-16 19:58
```javascript
if(!window.alert.toString().includes("window.alert")) {
throw new Error("hmm");
}
```
The author is detecting `perchance.org##+js(set-constant, alert, noopFunc)` with the above code and throwing an error, causing an infinite loading screen.
The toString of normal window.alert never contains the string `window.alert`. However, they check if window.alert is writable by setting window.alert to a function containing that string.
I have found `perchance.org##+js(set, String.prototype.includes, trueFunc)` bypasses this check, as `includes` will always return true. Still, it's hacky and probably breaks something.

**Comment by Feuerswut** [comment] 2024-01-18 01:07
> ```javascript
> if(!window.alert.toString().includes("window.alert")) {
> throw new Error("hmm");
> }
> ```
> The author is detecting `perchance.org##+js(set-constant, alert, noopFunc)` with the above code and throwing an error, causing an infinite loading screen.
> The toString of normal window.alert never contains the string `window.alert`. However, they check if window.alert is writable by setting window.alert to a function containing that string.
> I have found `perchance.org##+js(set, String.prototype.includes, trueFunc)` bypasses this check, as `includes` will always return true. Still, it's hacky and probably breaks something.

broken again it seems. worked yesterday.

**Comment by MDMCK10** [comment] 2024-01-18 20:30
> I have found `perchance.org##+js(set, String.prototype.includes, trueFunc)` bypasses this check, as `includes` will always return true. Still, it's hacky and probably breaks something.

Looks like the site owner may be watching this thread, as now there is a new check based around exactly that:

```js
if(`bbb`.includes("a")) {
    throw new Error("sus");
    uruf8ufd.jfurwe8j;
}
```

**Comment by MDMCK10** [comment] 2024-01-18 20:56
Latest update fixed anti-adblock, but `perchance.org##+js(rpnt, script, 'throw')` causes breakage here: https://perchance.org/ai-chat

**Comment by mapx-** [comment] 2024-01-18 21:02
@MDMCK10 removed

**Comment by ItsProfessional** [comment] 2024-01-19 08:22
> I am now 100% certain the site owner is monitoring this thread.

It's obvious. This thread is about defusing the detection as it's updated, not discussing about the webmasters' intentions or whatever. Please don't post such off-topic comments. Only comment when the detection mechanism is updated.

**Comment by MDMCK10** [comment] 2024-01-19 19:29
new detection:
```js
if (`bbb`.includes("a")) {
  throw new Error("sus");
  uruf8ufd.jfurwe8j;
}
window.iudu843975 = "bbb";
if (window.iudu843975[`in${''}cludes`]("a")) {
  throw new Error("sus");
  uruf8ufd.jfurwe8j;
}
```

**Comment by MDMCK10** [comment] 2024-01-20 18:40
`perchance.org##+js(set, String.prototype.includes, trueFunc)` causes breakage for legitimate uses of `.includes()`:
![image](https://github.com/uBlockOrigin/uAssets/assets/21245760/bcd74efb-d6d8-4c72-958f-c7cec901fccc)

**Comment by mapx-** [comment] 2024-01-20 18:57
page link ?

**Comment by MDMCK10** [comment] 2024-01-20 19:04
> page link ?

@mapx- I believe this to be applicable to any user-created "generator" on the site that makes use of the "includes" feature.
Here is an example I created that shows the issue: https://perchance.org/8vfiwfnk4y

**Comment by mapx-** [comment] 2024-01-20 21:16
@MDMCK10 see if helps the last update

**Comment by MDMCK10** [comment] 2024-01-21 08:48
> @MDMCK10 see if helps the last update

works fine.

**Comment by griffi-gh** [comment] 2024-01-21 21:04
Unbreak/Quick fixes lists seem to be triggering the detection

**Comment by MDMCK10** [comment] 2024-01-21 21:42
@griffi-gh
> Some rules in Unbreak/Quick fixes lists seems to be triggering the detection. Page loads successfuly without any ads with both temporarily disabled...

Have you tried [force updating](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes) the quick fixes list?
Disabling quick fixes causes detection on my side, no detection with it enabled.
Unbreak doesn't make any difference.

**Comment by griffi-gh** [comment] 2024-01-21 21:48
@MDMCK10 
ah they're both up-to-date

**Comment by mapx-** [comment] 2024-01-21 21:58
@griffi-gh 
You have to update `quick fixes` => click this [link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1)

**Comment by MDMCK10** [comment] 2024-01-22 14:12
new detection:
```js
(async function() {
  await new window[`Prom${""}ise`](r => setTimeout(r, 1000));
  if (!window.shouldExist39857034) {
    document[`bo${""}dy`].innerHTML = "";
    window.successfulPageLoad = false;
  }
})();
```

**Comment by griffi-gh** [comment] 2024-01-22 17:36
this bypasses the "kill screen":
```js
Object.defineProperty(document.body, 'innerHTML', {
  set: _=>_
});

Object.defineProperty(window, 'successfulPageLoad', {
  writable: false
});
```

I wonder if it would be possible to do sth like this with just uBlock's `+js` stuff

**Comment by liamengland1** [comment] 2024-01-22 18:38
Still getting detected even after https://github.com/uBlockOrigin/uAssets/commit/5b3b58ff6d3d14a7a2e7ad20818f353bd393fd1e on my side

**Comment by mapx-** [comment] 2024-01-22 19:15
page ?

**Comment by liamengland1** [comment] 2024-01-22 20:31
Never mind, when I force-updated quick fixes it did not pull the latest version. I forced updated again and now it works

**Comment by Spectral-Dreams** [comment] 2024-01-31 19:12
^ Still doesn't work. Getting detected and blocked. FWIW, I'm trying to access these 2 particular pages:
https://perchance.org/ai-story-generator
https://perchance.org/ai-story-outline

all filters and stuff updated.

**Comment by MDMCK10** [comment] 2024-02-08 13:37
Currently being detected at https://perchance.org/ai-chat
![image](https://github.com/uBlockOrigin/uAssets/assets/21245760/a7fae125-ba22-465d-9723-a8ae89600dbc)
to see the detection, wait 1-2 minutes, or use `perchance.org##+js(nano-stb, ., 60000, 0.05)` to get it to show up faster.

**Comment by ItsProfessional** [comment] 2024-02-08 13:48
Fixed recently, update lists.

**Comment by MDMCK10** [comment] 2024-02-08 14:03
> Fixed about 30 minutes ago, update lists.

Detection remains as of https://github.com/uBlockOrigin/uAssets/commit/c805f7fc795f57a2d6d164d868616ab71f25e7ea.
Already force updated lists (and confirmed that they match the above mentioned commit) and can still reproduce, please double check.

**Comment by Spectral-Dreams** [comment] 2024-02-15 14:51
yep, still getting detected 😩

**Comment by S00pergang** [comment] 2024-02-22 07:20
Anti adblock sucks but making a page auto reload if adblock is detected is a new low

**Comment by MDMCK10** [comment] 2024-02-22 17:08
Still detected after https://github.com/uBlockOrigin/uAssets/commit/abfda6f39d9380e57288ce4f3efc7de31784eae2

detection caused by iframe check (view-source:https://perchance.org/ai-chat, line 808):
```js
if ([...document.querySelectorAll("iframe")].filter(el => el.src).map(
    el => new URL(el.src).hostname).find(n => n[
      `ends${window.empty883974329}With`](
      `dou${window.empty883974329}bleclick.net`) || n[
      `ends${window.empty883974329}With`]("onetag-sys.com") || n[
      `ends${window.empty883974329}With`]("openx.net") || n[
      `ends${window.empty883974329}With`](".google.com") || n[
      `ends${window.empty883974329}With`](
      `amazon-ad${window.empty883974329}system.com`) || n[
      `ends${window.empty883974329}With`]("rubiconproject.com") || n[
      `ends${window.empty883974329}With`]("criteo.com") || n[
      `ends${window.empty883974329}With`]("3lift.com") || n[
      `ends${window.empty883974329}With`]("googlesyndication.com") ||
    n[`ends${window.empty883974329}With`]("connectad.io"))) {
  window[window.ftcFn1Name]("/api/count?key=abprbclasi");
  clasi = true;
  iframes = true;
}
```

**Comment by colleirose** [comment] 2024-03-09 05:49
It takes a few minutes for it to be detected for me, but it's detected after generating some images.

**Comment by ItsProfessional** [comment] 2024-03-13 06:19
@Tornadoalley There is no need for you to investigate the detection using ChatGPT to figure out what it means. Just let us know when the detection script is updated (e.g. with a comment like `Needs update.`), and we'll update our filters.

**Comment by JobcenterTycoon** [comment] 2024-04-18 08:39
Works fine for me. How to reproduce?

**Comment by JobcenterTycoon** [comment] 2024-04-18 11:10
Firefox but i also tested chrome.

**Comment by stephenhawk8054** [comment] 2024-07-28 02:50
https://github.com/uBlockOrigin/uAssets/issues/24648

**Closed** 2024-07-28 11:15 UTC
