### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by PsyHoGK** [uBlockOrigin/uAssets#14217] opened 2022-08-02 21:27 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://e.mail.ru/inbox/`

### Category

ads

### Describe the issue

Ads suddenly came back, and simple point and click to add filter not work anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-08-03 at 03-28-52 Входящие - Почта Mail ru](https://user-images.githubusercontent.com/92857819/182484877-d29d28c1-aa25-4112-9976-7b8497e88298.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 103
filterset (summary): 
  network: 97674
  cosmetic: 67191
  scriptlet: 17514
  html: 714
listset (total-discarded, last updated): 
  default: 
    user-filters: 19-0, never
    ublock-filters: 33083-95, 5h.6m
    ublock-badware: 4174-0, 5h.5m
    ublock-privacy: 242-0, 1d.4h.26m
    ublock-abuse: 76-0, 1d.4h.25m
    ublock-unbreak: 1865-0, 5h.4m
    easylist: 69026-592, 5h.3m
    easyprivacy: 27474-580, 5h.2m
    urlhaus-1: 4401-0, 9h.8m
    plowe-0: 3639-3, 1d.4h.23m
    RUS-0: 40348-158, 13h.9m
    ublock-quick-fixes: 344-1, 9h.7m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 258 ms (selfie)
  maxAssetCacheWait: 309 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    mail.ru: 41
    imgsmail.ru: 1
```
</details>

**Comment by krystian3w** [comment] 2022-08-02 23:33
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14206

**Comment by krystian3w** [comment] 2022-08-02 23:33
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/14207

**Comment by krystian3w** [comment] 2022-08-02 23:33
Check after purge all cache:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by dimisa-RUAdList** [comment] 2022-08-03 05:10
@PsyHoGK 
You need to do this:
> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
>

**Comment by PsyHoGK** [comment] 2022-08-03 05:22
> Check after purge all cache:
> 
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

It seems to work, thank you.

**Closed** 2022-08-03 05:22 UTC

**Comment by DazzRune** [comment] 2022-08-08 11:33
> > Check after purge all cache:
> > https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
> 
> It seems to work, thank you.

But not for me 😡[pic](https://ibb.co/7VL1tm4)

**Comment by dimisa-RUAdList** [comment] 2022-08-08 11:36
@DazzRune 
Do it twice.

**Comment by DazzRune** [comment] 2022-08-08 11:38
> @DazzRune Do it twice.
No effect!

**Comment by krystian3w** [comment] 2022-08-08 11:40
Multi-account?

**Comment by DazzRune** [comment] 2022-08-08 11:43
> Multi-account?

Do you mean email account? No, it's not. If you mean browser account, it is.

**Comment by DazzRune** [comment] 2022-08-08 11:49
Just updated all filters again so it helped!
