### ISSUE TITLE
ADS

### ISSUE THREAD

**Issue by apostoliskr** [uBlockOrigin/uAssets#23884] opened 2024-05-28 16:30 UTC
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.pronews.gr/
```

### Description

ADS

### Other extensions used

DARK RADER  ,  SIMBLE TRANSLATE

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1716913095472](https://github.com/uBlockOrigin/uAssets/assets/170970054/dc171f6a-4bc5-485e-85fb-cc5e19b309e6)

![1716913095463](https://github.com/uBlockOrigin/uAssets/assets/170970054/aefc6855-456f-4185-aa91-71c89c19f0d9)
![Uploading 1716913095466.jpg…]()

![1716913095469](https://github.com/uBlockOrigin/uAssets/assets/170970054/403d5b13-5c52-4abc-bb79-e33c3d99ea2d)
![Uploading 1716913095475.jpg…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137042
 cosmetic: 47032
 scriptlet: 19551
 html: 1829
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38300-112, 4h.38m Δ
  ublock-badware: 8947-0, 4h.38m Δ
  ublock-privacy: 951-2, 4h.38m Δ
  ublock-unbreak: 2349-2, 4h.38m Δ
  ublock-quick-fixes: 164-68, 4h.38m Δ
  easylist: 87238-166, 4h.38m Δ
  easyprivacy: 50987-64, 4h.38m Δ
  urlhaus-1: 13430-0, 9h.22m
  plowe-0: 3727-1159, 9h.22m
  GRC-0: 1095-8, 9h.23m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 743 ms
 maxAssetCacheWait: 322 ms
 cacheBackend: indexedDB
```
</details>

**Comment by JobcenterTycoon** [comment] 2024-05-28 16:35
@kargig

**Comment by garry-ut99** [comment] 2024-05-28 16:39
Duplicate of:
- https://github.com/uBlockOrigin/uAssets/issues/23872

**Closed** 2024-05-28 16:44 UTC
Labels: duplicate, to be fixed by regional list
