### ISSUE TITLE
cheatsquad.gg cosmetic and one filter

### ISSUE THREAD

**Issue by Janmm14** [uBlockOrigin/uAssets#7273] opened 2020-04-22 10:50 UTC
### URL(s) where the issue occurs

1. `https://cheatsquad.gg/dl/GnynDy/`
2. `https://cheatsquad.gg/`

### Describe the issue

1. placeholder for ads not removed
2. hover with mouse on "Minecraft" and an ad gets shown Edit: Same for hovering "Roblox".

### Screenshot(s)

1. the red circles show the place of the not-removed placeholders
![grafik](https://user-images.githubusercontent.com/3533175/79972856-e0d15f00-8496-11ea-98ba-2e652a55653d.png)
2.
![grafik](https://user-images.githubusercontent.com/3533175/79973190-67863c00-8497-11ea-9a63-cee7b56ea509.png)

### Versions

- Browser/version: Firefox 75.0
- uBlock Origin version: 1.26.0

### Settings

- I'm pretty sure my settings did not cause these issues. They hould be fairly default.

### Notes

Fix for 1. 
```
cheatsquad.gg##div.list_container>div.ad_nomargin.ad_largeleaderboard
```

Fix for 2.
```
cheatsquad.gg##.tooltip::before:style(display:none !important)
cheatsquad.gg##.tooltip::after:style(display:none !important)
```

**Comment by uBlock-user** [comment] 2020-04-22 10:55
@ryanbr

**Comment by mapx-** [comment] 2020-04-22 12:31
It should be addressed here in uAssets (we have anti adb filter already for that site), and without using uBO specific filters I don't know how can be fixed

I wrote these filters, but still remains the background when you hover upon the buttons

```
cheatsquad.gg##+js(ra, onclick, [onclick*="window.open"])
cheatsquad.gg##+js(ra, data-tooltip)
||cheatsquad.gg/img/pa.svg$image,1p
||cheatsquad.gg/img/rn.png$image,1p
```

**Comment by uBlock-user** [comment] 2020-04-22 12:33
> without using uBO specific filters I don't know how can be fixed

The first issue can be fixed with `cheatsquad.gg##.ad_largeleaderboard`, the second requires a bit specificity  for a cosmetic filter to avoid false positives.

**Comment by mapx-** [comment] 2020-04-22 12:34
The buttons can not be completely hidden so no classic cosmetic filters will help

**Comment by mapx-** [comment] 2020-04-22 12:36
I don't know if we can chain :style with matches-css for ::after

**Comment by Janmm14** [comment] 2020-04-22 12:41
> 
> 
> I don't know if we can chain :style with matches-css for ::after

The filters I wrote above obviously work for me. I resorted to `::after:style(display:none !important)`, because the default hiding ignored the `::after` and hid the whole menu button

**Closed** 2020-04-22 12:46 UTC

**Comment by krystian3w** [comment] 2020-04-22 15:06
`cheatsquad.gg##.tooltip:after, .tooltip:before`

How this hide too many pseudo-elements?

**Comment by Janmm14** [comment] 2020-04-22 15:58
> 
> 
> `cheatsquad.gg##.tooltip:after, .tooltip:before`
> 
> How this hide too many pseudo-elements?

Using that rule hides "Minecraft" and "Roblox" menu points completely on that web page (using ubo 1.26.0 on firefox 75)

aka you have to use `:style(display:none !important)` to be able to hide css pseudo elements

**Comment by gwarser** [comment] 2020-04-22 16:00
> Using that rule hides "Minecraft" and "Roblox" menu points completely on that web page

This is only Element Picker glitch. There is no difference between `##.tooltip::after` and `##.tooltip::after:style(display:none !important)`

**Comment by Janmm14** [comment] 2020-04-22 16:03
> 
> 
> > Using that rule hides "Minecraft" and "Roblox" menu points completely on that web page
> 
> This is only Element Picker glitch. There is no difference between `##.tooltip::after` and `##.tooltip::after:style(display:none !important)`

Oh, thanks. Tested it and you're 100% right

@mapx-

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 17:43
anti adb on `https://cheatsquad.gg/csgo`

**Comment by Janmm14** [comment] 2021-11-11 18:29
@mapx- This doesnt solve it completely for me, just the complete dom change is aborted. Sometimes reloading causes a popup with darkgray background and green and white text to still appear.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 18:37
should nano-sib be used?

`https://cheatsquad.gg/cheat/G2JBPF` => the button that upon clicks redirects to a page with a countdown => waiting for countdown => clicking the green button => `work.ink` link with anti adb

**Comment by okiehsch** [comment] 2021-11-11 18:45
@IEnjoyDrinkingGoodWater does
````
cheatsquad.gg##+js(nano-sib, clearInterval)
@@||work.ink^$ghide
````
work for you`?

@Janmm14 I can't reproduce.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:02
@okiehsch is `, clearInterval` needed?
should `work.ink##.ad` be added?

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:04
> @IEnjoyDrinkingGoodWater does
> 
> ```
> cheatsquad.gg##+js(nano-sib, clearInterval)
> @@||work.ink^$ghide
> ```
> 
> work for you`?
> 
> @Janmm14 I can't reproduce.

@okiehsch is `, clearInterval` needed?
should `work.ink##.ad` be added?

**Comment by okiehsch** [comment] 2021-11-11 19:05
Have you tried without `, clearInterval`?

I can add `work.ink##.ad`.

**Comment by okiehsch** [comment] 2021-11-11 19:08
To be clear if I add `cheatsquad.gg##+js(nano-sib)` it interferes with @mapx- filter 
`cheatsquad.gg##+js(nosiif, visibility, 1000)`
and the anti adblock message should reappear because we boost all setIntervall calls.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:09
err, i have a question... is combating some forms of anti adb illegal in the US or the EU?

**Comment by uBlock-user** [comment] 2021-11-11 19:11
> illegal in the US or the EU?

Legality has to do something with an existing law, which is none.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:12
> > illegal in the US or the EU?
> 
> Legality has to do something with an existing law, which is none.

does it not conflict with copyright law?

**Comment by Janmm14** [comment] 2021-11-11 19:15
> 
> 
> @IEnjoyDrinkingGoodWater does
> 
> ```
> cheatsquad.gg##+js(nano-sib, clearInterval)
> @@||work.ink^$ghide
> ```
> 
> work for you`?
> 
> @Janmm14 I can't reproduce.

Thanks, I can't reproduce on clean firefox install either. Seems like the Firefox Add-On "Font Fingerprint Defender" interfered there.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:16
> > illegal in the US or the EU?
> 
> Legality has to do something with an existing law, which is none.

does it not conflict with copyright law(s)?

**Comment by okiehsch** [comment] 2021-11-11 19:18
@Janmm14 thanks for the feedback.

**Comment by uBlock-user** [comment] 2021-11-11 19:18
> `work.ink` link with anti adb

Can't reproduce any... besure to test on default settings + all other extensions disabled.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:18
> > illegal in the US or the EU?
> 
> Legality has to do something with an existing law, which is none.

does it not conflict with copyright laws?

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:19
> > `work.ink` link with anti adb
> 
> Can't reproduce any... besure to test on default settings + all other extensions disabled.

have you tested in Google Chrome?

**Comment by okiehsch** [comment] 2021-11-11 19:19
Yes, I have.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:20
also, kinda off-topic, but also related, do you have any recommendations for VPN(s)?

**Comment by uBlock-user** [comment] 2021-11-11 19:21
> have you tested in Google Chrome?

Yes, no change.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:22
> > have you tested in Google Chrome?
> 
> Yes, no change.

US IP? (don't quote, will delete)

**Comment by uBlock-user** [comment] 2021-11-11 19:22
@okiehsch Do you see it ?

**Comment by okiehsch** [comment] 2021-11-11 19:23
> also, kinda off-topic, but also related, do you have any recommendations for VPN(s)?

Very impressive, first you report an anti adblock issue, then you want to discuss the legality of fixing such issues, then you seek software advice.

**Comment by okiehsch** [comment] 2021-11-11 19:23
@uBlock-user No.

**Comment by uBlock-user** [comment] 2021-11-11 19:24
So why add filters then ?

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:24
> > also, kinda off-topic, but also related, do you have any recommendations for VPN(s)?
> 
> Very impressive, first you report an anti adblock issue, then you want to discuss the legality of fixing such issues, then you seek software advice.

I have devoted a considerable amount of time to contibuting to uBO before.

**Comment by okiehsch** [comment] 2021-11-11 19:25
Sorry, I thought you meant https://github.com/uBlockOrigin/uAssets/issues/7273#issuecomment-966529572
I can't reproduce that.

I can reproduce the rest.

**Comment by uBlock-user** [comment] 2021-11-11 19:26
> I have devoted a considerable amount of time to contibuting to uBO before.

For questions, use https://www.reddit.com/r/uBlockOrigin/

**Comment by okiehsch** [comment] 2021-11-11 19:27
> I have devoted a considerable amount of time to contibuting to uBO before.

I fail to see the relevance, you report an issue and then want us to discuss the legality of the issue you reported in the first place.
Looks like trolling to me.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:27
@mapx- back me up =))

**Comment by uBlock-user** [comment] 2021-11-11 19:28
> I thought you meant 

I meant do you see anti-adb on `https://work.ink/l/v/G2JBPF`

**Comment by okiehsch** [comment] 2021-11-11 19:28
> I meant do you see anti-adb on `https://work.ink/l/v/G2JBPF`

Yes, the ghide filter fixes it on my end.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:30
> > I have devoted a considerable amount of time to contibuting to uBO before.
> 
> I fail to see the relevance, you report an issue and then want us to discuss the legality of the issue you reported in the first place. Looks like trolling to me.

Asking for VPN recommendation(s) from people who also test ad blocking on websites didn't seem like trolling to me.

**Comment by uBlock-user** [comment] 2021-11-11 19:31
Regardless of trolling or not, such off-topic questions are not to asked here, this isn't the place for that, period.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:33
I asked a legality-related question on the subreddit quite some time ago.

**Comment by okiehsch** [comment] 2021-11-11 19:34
> Asking for VPN recommendation(s) from people who also test ad blocking on some websites didn't seem like trolling to me.

How can you read my comment
"you report an issue and then want us to discuss the legality of the issue you reported in the first place. Looks like trolling to me."

and deduce from it that I meant that asking for VPN recommendations is trolling?

**Comment by uBlock-user** [comment] 2021-11-11 19:35
> I asked a legality-related question on the subreddit quite some time ago.

Then be satisfied with the answer you got, no need to do that here.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:36
> > I asked a legality-related question on the subreddit quite some time ago.
> 
> Then be satisfied with the answer you got, no need to do that here.

did you answer on the subreddit? also, it would make much more sense to ask you since you have fixed addressed anti adb in uAssets.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:37
anywhere I gotta go somewhere, have a great time y'all!

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-11 19:37
anyway, I gotta go somewhere, have a great time y'all!

**Comment by uBlock-user** [comment] 2021-11-11 19:38
> did you answer on the subreddit? 

I don't know, I don't remember. 

> also, it would make much more sense to ask you since you have fixed addressed anti adb in uAssets.

Then ping me on the sub-reddit instead of asking here. This issue has nothing with your quesiton and we have gone way-topic now.

**Comment by uBlock-user** [comment] 2021-11-11 19:38
> did you answer on the subreddit? 

I don't know, I don't remember. 

> also, it would make much more sense to ask you since you have fixed addressed anti adb in uAssets.

Then ping me on the sub-reddit instead of asking here. This issue has nothing to do with your question and we have gone way-topic now.

**Comment by stephenhawk8054** [comment] 2021-11-13 04:06
Another anti-adblock with domain `work.ink`. Wait about 10 seconds, an anti-adblock appears.

URL: `https://work.ink/en/l/v/ioHDbW`

![image](https://user-images.githubusercontent.com/66517106/141605036-4c295f69-c173-4e08-b185-b566fcb23555.png)

Firefox 94.0.1. ublock 1.38.6 default.

Proposed filter:

`||adnxs.com^$subdocument,redirect=nooptext,domain=work.ink`

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-13 19:54
`https://cheatcloud.cc/download-best-free-csgo-hacks-cheats/goesp/` - after clicking on the download button I encountered a countdown

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-13 19:56
*account required*
*countdown*
`https://cheatermad.com/free-csgo-hvh-cheat-hajisense/` - while logged in => download button => countdown

**Comment by okiehsch** [comment] 2021-11-13 19:58
Can you test
`cheatermad.comcc##+js(nano-sib, clearInterval)`

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-13 20:01
account required
`https://cheater.ninja/best-csgo-free-cheat-hajisense/` - while logged in -- download button => page with countdown

**Comment by okiehsch** [comment] 2021-11-13 20:01
Well, try `##+js(nano-sib, clearInterval)` with all of them.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-13 20:06
> Well, try `##+js(nano-sib, clearInterval)` with all of them.

when in focus seemed to work alright with the countdown pages related to the last two links I gave in this issue.

**Comment by IEnjoyDrinkingGoodWater** [comment] 2021-11-14 01:38
`https://cheatsquad.gg/cheat/PMBNiN` => download button => countdown page => `work.ink` url => button for continuing => `anonym.ninja` URL -- countdown

**Comment by JobcenterTycoon** [comment] 2021-12-29 18:14
`https://work.ink/l/v/G2JBPF` stuck in loading and consumes much ressources with adblock enabled

**Comment by JobcenterTycoon** [comment] 2021-12-29 22:48
Now i get a anti adblock screen, also the site crash the debugger.

Fix for the anti adb: `||doubleclick.net^$frame,redirect-rule=noopframe,domain=work.ink`

**Comment by mapx-** [comment] 2021-12-29 23:08
yes, they changed quickly the trick

**Comment by JobcenterTycoon** [comment] 2022-01-02 19:33
The site has like linkvertise a few "verification" steps like read a article. Example `https://work.ink/en/l/X/ExLoader` but after a bunch of wasted minutes i get this


<img width="434" alt="Unbenannt2" src="https://user-images.githubusercontent.com/48647394/147887207-05a103a8-72ca-4f95-a1a2-559055807466.PNG">

Any way to defuse this?

**Comment by krystian3w** [comment] 2022-01-02 22:36
Try reproduce with AdGuard Addon and maybe AdGuard team found bug in EasyList/EasyPrivacy or use scriptlets compatible with uBo syntax.

**Comment by Branzeturi** [comment] 2022-05-23 23:40
> The site has like linkvertise a few "verification" steps like read a article. Example `https://work.ink/en/l/X/ExLoader` but after a bunch of wasted minutes i get this

@JobcenterTycoon @mapx- `work.ink##.you-need-to-update-your-adblock-filter`
