### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#11545] opened 2022-02-02 13:44 UTC
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/results?search_query=mikrotik+wms`

### Category

ads

### Describe the issue

youtube ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/152165299-b5ee7888-c476-4c95-9f64-31287a7307ea.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 67355
  cosmetic: 94737
  scriptlet: 33705
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1824-9, 1d.6h.35m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6012-3, 1d.6h.33m
    IDN-0: 9045-210, 1d.6h.31m
    adguard-annoyance: 49761-171, 1d.6h.21m
    adguard-generic: 61443-818, 1d.6h.23m
    adguard-mobile: 7157-58, 1d.6h.27m
    adguard-spyware: 25859-597, 1d.6h.25m
    ublock-annoyances: 4375-189, 1d.6h.29m
  default: 
    ublock-abuse: 77-0, 1d.6h.10m
    ublock-badware: 3831-166, 1d.6h.19m
    ublock-filters: 30176-3300, 1d.6h.16m
    ublock-privacy: 194-27, 1d.6h.14m
    ublock-unbreak: 1693-88, 1d.6h.12m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
  suspendTabsUntilReady: false
supportStats: 
  launchToReadiness: 666 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by uBlock-user** [comment] 2022-02-02 13:47
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Closed by uBlock-user** 2022-02-02 13:47 UTC

**Comment by gwarser** [comment] 2022-02-02 16:55
```
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
```

Really?
