### ISSUE TITLE
sultanovic.net [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#9488] opened 2021-06-29 23:42 UTC
### URL(s) where the issue occurs
`
http://sultanovic.net/forum/`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/123880985-c3f1b080-d911-11eb-8a21-c0859d082ad7.png)

### Versions

- Browser/version: Firefox 89.0.2
- uBlock Origin version: 1.36.0

### Settings

Default Settings
-

### Notes

Only get this banner when connected to a VPN.

**Comment by uBlock-user** [comment] 2021-06-30 05:55
> Only get this banner when connected to a VPN.

Does that VPN come with built-in blocker of its own ?

**Comment by uBlock-user** [comment] 2021-06-30 06:05
Issue caused by other extensions are not addressed in uAssets.

**Closed by uBlock-user** 2021-06-30 06:05 UTC
Labels: external, unable to reproduce
